(mes
 (meta (engine 'AI5) (charset "English") (dictbase 128))
(dict-build)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "19.pd8")
 (proc 15)
 (set-arr~ @ 6 1)
 (image "t.pd8")
 (proc 16)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "tan.pd8")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 0)
 (load "t.s4" (~ @ 2))
 (animate 0 0 0)
 (animate 1 0)
 (set-arr~ @ 7 0)
 (while
  (== 1 1)
  (<>
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 256 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (if-else (== N 2)
     (<>
      (text #:color 7 "" 0 ": H-hey Ako")
      (wait)
      (text #:color 2 "Ako: Welcome..." 0 ".")
      (wait)
      (text #:color 7 "" 0 ": Ako... Are you alone?")
      (wait)
      (text #:color 2 "Ako: Yes, I'm alone... Mako is currently going
to school.")
      (wait)
      (text #:color 7 "" 0 ": I see... Is Mako also alone?")
      (wait)
      (text #:color 2 "Ako: How strange " 0 "...
You really are acting funny.")
      (wait)
      (text #:color 7 "" 0 ": Ehh, you see...")
      (wait)
      (text #:color 2 "Ako: Is there something you want to talk
about?")
      (wait)
      (text #:color 7 "" 0 ": Yeah...")
      (wait)
      (cond
       ((< (: 106) 6) (<> (text #:color 2 "Ako: What is it?") (wait)))
       ((> (: 106) 5) (<> (text #:color 2 "Ako: What...?") (wait)))
       (else (<>)))
      (text #:color 7 "" 0 ": W-well... I want to make things
official between us.")
      (wait)
      (text #:color 7 "" 0 ": I'm serious about this, not playing
around like usual.")
      (wait)
      (text #:color 2 "Ako: " 0 "...")
      (wait)
      (text #:color 7 "" 0 ": Y-Yes.")
      (wait)
      (cond
       ((< (: 106) 3)
        (<>
         (sound 1)
         (set-var I 13)
         (proc 26)
         (text #:color 2 "Ako: " 0 "... The thing is... I...
I really dislike you.")
         (wait)
         (text #:color 7 "" 0 ": Gwaaaahhh...")
         (wait)
         (sound 1)
         (set-var I 47)
         (proc 26)
         (text #:color 2 "Ako: To be brutally honest, I don't even want to
look you in the face, understand?")
         (wait)
         (text #:color 7 "" 0 ": A-Ako...")
         (wait)
          (text #:color 2 "Ako: " 0 " every time you come to this
pharmacy it makes me want to close the shop.")
         (wait)
         (text #:color 7 "" 0 ": N-No way...")
         (wait)
         (text #:color 2 "Ako: If possible, I want you to never come here
again. Could you drop by by another pharmacy
from now on?")
         (wait)
         (text #:color 7 "" 0 ": N-No way...")
         (wait)
         (text #:color 2 "Ako: So, could you go home...?
And " 0 ", if you keep talking I'll start
feeling depressed.")
         (wait)
         (set-reg: 821 1)
         (slot 1 1)
         (mes-jump "y15.mes")))
       ((< (: 106) 6)
        (<>
         (sound 1)
         (set-var I 13)
         (proc 26)
         (text #:color 2 "Ako: " 0 "... I... I don't like you.")
         (wait)
         (text #:color 7 "" 0 ": Gwaaaahhh...")
         (wait)
         (sound 1)
         (set-var I 47)
         (proc 26)
         (text #:color 2 "Ako: I'm sorry... I'd rather pretend we never
had this conversation.")
         (wait)
         (text #:color 7 "" 0 ": A-Ako...")
         (wait)
         (text #:color 2 "Ako: I don't even know what I'm supposed to do
during a confession... It's enough to make me
feel sick.")
         (wait)
         (text #:color 7 "" 0 ": N-No way...")
         (wait)
         (text #:color 2 "Ako: If possible, I want you to never come here
again. Could you drop by by another pharmacy
from now on?")
         (wait)
         (text #:color 7 "" 0 ": N-No way...")
         (wait)
         (text #:color 2 "Ako: So, could you go home...?
And " 0 ", if you keep talking I'll start
feeling depressed.")
         (wait)
         (set-reg: 821 1)
         (slot 1 1)
         (mes-jump "y15.mes")))
       ((< (: 106) 13)
        (<>
         (sound 1)
         (set-var I 12)
         (proc 26)
         (text #:color 2 "Ako: " 0 " I like you too as well but...")
         (wait)
         (text #:color 7 "" 0 ": (Yes!!)")
         (wait)
         (text #:color 2 "Ako: After some thinking...
You're quite close with other girls as well,
so...")
         (wait)
         (sound 1)
         (set-var I 46)
         (proc 26)
         (text #:color 7 "" 0 ": But out of all of them
I like you the most.")
         (wait)
         (text #:color 2 "Ako: I'm sorry " 0 ", I like you but... I'd
like to stay as friends.")
         (wait)
         (text #:color 7 "" 0 ": N-No way...")
         (wait)
         (text #:color 2 "Ako: Tomorrow you go back to school,
so good luck " 0 ".")
         (wait)
         (text #:color 7 "" 0 ": ...")
         (wait)
         (text #:color 2 "Ako: " 0 ", please go home.")
         (wait)
         (text #:color 7 "" 0 ": ...")
         (wait)
         (set-reg: 821 2)
         (slot 1 1)
         (mes-jump "y15.mes")))
       ((< (: 106) 16)
        (<>
         (sound 1)
         (set-var I 21)
         (proc 26)
         (text #:color 2 "Ako: I am so, so happy.")
         (wait)
         (text #:color 2 "Ako: " 0 "... For you to ask me such a
thing... It's like a dream come true.")
         (wait)
         (sound 1)
         (set-var I 29)
         (proc 26)
         (text #:color 7 "" 0 ": Ako...")
         (wait)
         (text #:color 2 "Ako: " 0 " if it's something you want, I'll
give it to you.")
         (wait)
         (text #:color 7 "" 0 ": ...")
         (wait)
         (text #:color 2 "Ako: So, please... Don't abandon me.")
         (wait)
         (text #:color 7 "" 0 ": O-Of course.")
         (wait)
         (text #:color 2 "Ako: " 0 "...")
         (wait)
         (text #:color 7 "" 0 ": Ako...")
         (wait)
         (text #:color 2 "Ako: " 0 "!!")
         (wait)
         (text #:color 7 "" 0 ": Ako!!")
         (wait)
         (text #:color 2 "Ako: " 0 "!!!")
         (wait)
         (set-reg: 821 3)
         (slot 1 1)
         (mes-jump "y15.mes")))
       (else (<>))))
     (<>))))
 (set-arr~ @ 7 1))