(mes
 (meta (engine 'AI5) (charset "English") (dictbase 128))
(dict-build)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "19.pd8")
 (proc 15)
 (set-arr~ @ 6 1)
 (image "t.pd8")
 (proc 16)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "tan.pd8")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 0)
 (load "t.s4" (~ @ 2))
 (animate 0 0 0)
 (animate 1 0)
 (set-arr~ @ 7 0)
 (while
  (== 1 1)
  (<>
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 256 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (if-else (== N 2)
     (<>
      (text #:color 7 "" 0 ": H-hey Ako")
      (wait)
      (text #:color 2 "Ako: Welcome..." 0 ".")
      (wait)
      (text #:color 7 "" 0 ": Ako... You alone?")
      (wait)
      (text #:color 2 "Ako: Yes, I'm alone... Mako is still at the
school.")
      (wait)
      (text #:color 7 "" 0 ": I see... Is Mako also alone?")
      (wait)
      (text #:color 2 "Ako: You're acting strange " 0 "...
You really are acting funny.")
      (wait)
      (text #:color 7 "" 0 ": Ehh, you see...")
      (wait)
      (text #:color 2 "Ako: Is there something you want to talk about?")
      (wait)
      (text #:color 7 "" 0 ": Yes.")
      (wait)
      (cond
       ((< (: 106) 6) (<> (text #:color 2 "Ako: What is it?") (wait)))
       ((> (: 106) 5) (<> (text #:color 2 "Ako: What?") (wait)))
       (else (<>)))
      (text #:color 7 "" 0 ": W-well... I want to go out with you.")
      (wait)
      (text #:color 7 "" 0 ": I mean it, seriously... Since I'm not
my usual self today.")
      (wait)
      (text #:color 2 "Ako: " 0 "...")
      (wait)
      (text #:color 7 "" 0 ": Y-Yes.")
      (wait)
      (cond
       ((< (: 106) 3)
        (<>
         (sound 1)
         (set-var I 13)
         (proc 26)
         (text #:color 2 "Ako: " 0 "... The thing is... I...
I don't like you the same way.")
         (wait)
         (text #:color 7 "" 0 ": Gwaaaahhh...")
         (wait)
         (sound 1)
         (set-var I 47)
         (proc 26)
         (text #:color 2 "Ako: I'm saying it honestly, I don't even
want to look you in the face, understand?")
         (wait)
         (text #:color 7 "" 0 ": A-Ako...")
         (wait)
         (text #:color 2 "Ako: " 0 " each time you go to this
pharmacy it makes me want to close the shop.")
         (wait)
         (text #:color 7 "" 0 ": I-I see...")
         (wait)
         (text #:color 2 "Ako: If possible, could you go
to a different pharmacy next time?")
         (wait)
         (text #:color 7 "" 0 ": I-Is that so...")
         (wait)
         (text #:color 2 "Ako: So, could you go home...?
And " 0 ", if you keep talking I'll
start feeling depressed.")
         (wait)
         (set-reg: 821 1)
         (slot 1 1)
         (mes-jump "y15.mes")))
       ((< (: 106) 6)
        (<>
         (sound 1)
         (set-var I 13)
         (proc 26)
         (text #:color 2 "Ako: I... " 0 " I don't like you")
         (wait)
         (text #:color 7 "" 0 ": Gwaaaahhh...")
         (wait)
         (sound 1)
         (set-var I 47)
         (proc 26)
         (text #:color 2 "Ako: I'm sorry but... Now I'd like to ")
         (wait)
         (text #:color 7 "" 0 ": A-Ako...")
         (wait)
         (text #:color 2 "Ako: Generally during a confession
I don't know what to do...")
         (wait)
         (text #:color 7 "" 0 ": I-I see...")
         (wait)
         (text #:color 2 "Ako: If possible, could you go
to a different pharmacy next time?")
         (wait)
         (text #:color 7 "" 0 ": I-Is that so...")
         (wait)
         (text #:color 2 "Ako: So, could you go home...?
And " 0 ", if you keep talking I'll
start feeling depressed.")
         (wait)
         (set-reg: 821 1)
         (slot 1 1)
         (mes-jump "y15.mes")))
       ((< (: 106) 13)
        (<>
         (sound 1)
         (set-var I 12)
         (proc 26)
         (text #:color 2 "Ako: " 0 " I like you too as well but...")
         (wait)
         (text #:color 7 "" 0 ": (Yes!!)")
         (wait)
         (text #:color 2 "Ako: After some thinking...
You're quite close with other girls as well,
so...")
         (wait)
         (sound 1)
         (set-var I 46)
         (proc 26)
         (text #:color 7 "" 0 ": Out of all of them
I like you the most.")
         (wait)
         (text #:color 2 "Ako: I'm sorry" 0 "...
I like you but as painful as it is for me,
I'd like to stay as friends.")
         (wait)
         (text #:color 7 "" 0 ": I-I see...")
         (wait)
         (text #:color 2 "Ako: Tomorrow you go back to school,
so good luck " 0 ".")
         (wait)
         (text #:color 7 "" 0 ": ...")
         (wait)
         (text #:color 2 "Ako: " 0 "... Hope you can return soon.")
         (wait)
         (text #:color 7 "" 0 ": ...")
         (wait)
         (set-reg: 821 2)
         (slot 1 1)
         (mes-jump "y15.mes")))
       ((< (: 106) 16)
        (<>
         (sound 1)
         (set-var I 21)
         (proc 26)
         (text #:color 2 "Ako: I am so, so happy.")
         (wait)
         (text #:color 2 "Ako: " 0 "... I've never dreamed of
something like this.")
         (wait)
         (sound 1)
         (set-var I 29)
         (proc 26)
         (text #:color 7 "" 0 ": Ako...")
         (wait)
         (text #:color 2 "Ako: " 0 " I really want to be with you...
So I'll do for anything for you.")
         (wait)
         (text #:color 7 "" 0 ": ...")
         (wait)
         (text #:color 2 "Ako: But... I won't reject")
         (wait)
         (text #:color 7 "" 0 ": O-Of course.")
         (wait)
         (text #:color 2 "Ako: " 0 "...")
         (wait)
         (text #:color 7 "" 0 ": Ako...")
         (wait)
         (text #:color 2 "Ako: " 0 "!!")
         (wait)
         (text #:color 7 "" 0 ": Ako!!")
         (wait)
         (text #:color 2 "Ako: " 0 "!!!")
         (wait)
         (set-reg: 821 3)
         (slot 1 1)
         (mes-jump "y15.mes")))
       (else (<>))))
     (<>))))
 (set-arr~ @ 7 1))