(mes
 (meta (engine 'AI5) (charset "English") (dictbase 128))
(dict-build)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (sound 1)
 (set-var I 3)
 (proc 26)
 (while
  (== 1 1)
  (<>
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 256 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (if-else (== N 2)
     (<>
      (text #:color 7 "" 0 ":Alright, this is Ako's data.")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "19.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "t.pd8")
      (proc 16)
      (set-arr~ @ 6 1)
      (image "tan.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "t.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "" 0 ": Her name is \"Ako Saito\", she's a woman
who works at the Saito Pharmacy.")
      (wait)
      (text #:color 7 "" 0 ": Ako is the younger sister of \"Mako
Saito\", Sakimake Academy's doctor, Mako and I
attend there.)
      (wait)
      (text #:color 7 "" 0 ": I was thinking, doesn't she have a
inferiority complex regarding Mako?")
      (wait)
      (text #:color 7 "" 0 ": Well, I guess that's normal when you
have such a beautiful sister.")
      (wait)
      (if-else (== (: 314) 1)
        (<>
         (slot 1 5)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "30.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "t11.pd8")
         (proc 16)
         (set-arr~ @ 6 1)
         (image "t11an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "t11.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "" 0 ": That reminds me, Ako and I once went
to a coffee shop together... We licked our
spoons and talked about various things.")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "t10.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 0)
         (text #:color 7 "" 0 ": Hehehe, thanks to Satomi for giving me
this spoon I was able to enjoy myself.")
         (wait)
         (text #:color 7 "" 0 ": Hmm, at the time I was so aroused...
that my willy almost lifted the table, yup.")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "t08.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 6 1)
         (image "t08an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "t08.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "" 0 ": So, after going to the park with Ako,
I noticed she seemed as happy as a child.")
         (wait)
         (text #:color 7 "" 0 ": After climbing the ladybug she said
that she wanted to play in the slide...")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "t07.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 6 1)
         (image "t07an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "t07.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "" 0 ": Well, that pose was really
stimulating...  For a children's game it was
unreasonable that her panties were at full
sight.")
         (wait)
         (text #:color 7 "" 0 ": On top of that, her butt was not
coming out of the slide... Hihihi, thanks to
that I was able to touch her chest and various
other parts.")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "t03.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 6 1)
         (image "t03an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "t03.s4" (~ @ 2))
         (set-arr~ @ 7 0)
         (animate 0 8 0)
         (animate 4 8)
         (text #:color 7 "" 0 ": The final touch was a little kiss—
just a small reward. After that, she beamed with
joy and dashed off.")
         (wait)
         (text #:color 7 "" 0 ": ...")
         (wait)
         (text #:color 7 "" 0 ": Somehow I misunderstood?")
         (wait)
         (text #:color 7 "" 0 ": ...")
         (wait)
         (text #:color 7 "" 0 ": Oh, well... No point in thinking too
much about it.")
         (wait))
        (<>))
      (if-else (== (: 667) 1)
        (<>
         (slot 1 5)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "t09.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 6 1)
         (image "t09an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "t09.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "" 0 ": That's right, it is not I who has been
deep in thought... It's her.")
         (wait)
         (text #:color 7 "" 0 ": Mako told me that Ako, was at the
riverbank... And we talked about many topics
while we were at it.")
         (wait)
         (text #:color 7 "" 0 ": ...")
         (wait)
         (text #:color 7 "" 0 ": Hmmm... Guess that my speaking skills
will bring forth some outcome.")
         (wait))
        (<>))
      (if-else (== (: 676) 1)
        (<>
         (slot 1 5)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "t06.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 0)
         (text #:color 7 "" 0 ": That's right, I don't know what I was
thinking when I went to the pharmacy and
couldn't see Ako...")
         (wait)
         (text #:color 7 "" 0 ": I was selfish when I entered that
shop.")
         (wait)
         (text #:color 7 "" 0 ": That pose Ako made when I was looking
for something... She was really surprised.")
         (wait)
         (text #:color 7 "" 0 ": While I was looking at her pose, I
gradually became horny...")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "t04.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 6 1)
         (image "t04an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "t04.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "" 0 ": She was surprised from the way I saw
her...
After that, she tormented me with questions.")
         (wait))
        (<>))
      (if-else (== (: 603) 1)
        (<>
         (text #:color 7 "" 0 ": I safely cleared her questions and
then I kissed her...")
         (wait)
         (text #:color 7 "" 0 ": While I was kissing her, her chest...
Hihihihi...")
         (wait)
         (slot 1 5)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "t04.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "t05.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 25)
         (set-arr~ @ 6 1)
         (image "t04an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "t04.s4" (~ @ 2))
         (set-arr~ @ 7 0)
         (animate 0 8 1)
         (animate 4 8)
         (text #:color 7 "" 0 ": She was surprised by this and I was
thrust away, so I forcibly removed her clothes.")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "t13.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 2)
         (image "t12.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 27)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 2)
         (image "t01.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 27)
         (proc 24)
         (set-arr~ @ 6 1)
         (image "t13an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "t13.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "" 0 ": ...")
         (wait)
         (text #:color 7 "" 0 ": However, she asked in such a insistent way, that I thought on leaving her.")
         (wait)
         (text #:color 7 "" 0 ": Then the opposite of \"going home\" happened... Really, I don't understand women's heart.")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "t13.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 2)
         (image "t12.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 27)
         (proc 24)
         (set-arr~ @ 6 1)
         (image "t13an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "t13.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "" 0 ": And then I stripped her of her clothes...")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "t13.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 6 1)
         (image "t13an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "t13.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "" 0 ": Umm... Her naked body was immensely
beautiful... Particularly her special parts.")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "t02.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 6 1)
         (image "t02an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "t02.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "" 0 ": ...")
         (wait)
         (text #:color 7 "" 0 ": And so... Ako and I made love.")
         (wait))
        (<>))
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "42.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (cond
       ((== (: 603) 0)
        (<>
         (text #:color 7 "" 0 ": Fufufu... Ako may be older than me,
but that's just how I like them.")
         (wait)))
       ((== (: 603) 1)
        (<>
         (text #:color 7 "" 0 ": But somehow after that she was
frightened...")
         (wait)
         (text #:color 7 "" 0 ": ...")
         (wait)
         (text #:color 7 "" 0 ": Well, it's unusual for me to be
worried about women.")
         (wait)))
       (else (<>)))
      (set-reg: 608 1)
      (slot 1 2)
      (mes-jump "myroom.mes"))
     (<>))))
 (set-arr~ @ 7 1))