(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\い
  #\。
  #\な
  #\っ
  #\ー
  #\、
  #\う
  #\か
  #\ン
  #\ま
  #\ん
  #\バ
  #\て
  #\で
  #\テ
  #\し
  #\だ
  #\は
  #\す
  #\よ
  #\る
  #\の
  #\に
  #\た
  #\こ
  #\あ
  #\お
  #\ゃ
  #\ち
  #\？
  #\ら
  #\れ
  #\！
  #\と
  #\が
  #\さ
  #\ご
  #\を
  #\や
  #\も
  #\り
  #\せ
  #\ル
  #\そ
  #\く
  #\カ
  #\ざ
  #\ト
  #\わ
  #\ふ
  #\ど
  #\ね
  #\タ
  #\え
  #\ろ
  #\け
  #\女
  #\俺
  #\客
  #\ラ
  #\事
  #\じ
  #\ス
  #\様
  #\何
  #\ニ
  #\言
  #\マ
  #\待
  #\子
  #\人
  #\み
  #\０
  #\シ
  #\ソ
  #\ケ
  #\ノ
  #\ウ
  #\店
  #\ば
  #\一
  #\酒
  #\帰
  #\入
  #\つ
  #\ぞ
  #\き
  #\大)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (set-arr~ @ 9 (&& (~ @ 9) 65534))
 (image "06.pd8")
 (set-arr~ @ 9 (// (~ @ 9) 1))
 (proc 9)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "06.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (cond
  ((== (: 476) 0)
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "06an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "06.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 35)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 1 "【バーテン】いらっしゃいませ。")
    (wait)
    (text #:color 7 "【" 0 "】こっちを向いて言えよ。")
    (wait)
    (text #:color 1 "【バーテン】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ちぇっ、愛想のない店だなあ。")
    (wait)))
  ((&& (== (: 609) 1) (> H 820) (== (: 611) 0) (== (: 617) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u.pd8")
    (proc 25)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "uan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 59)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あらっ！？")
    (wait)
    (text #:color 6 "【やよい】あら・・・こんばんは。")
    (wait)
    (text #:color 7 "【" 0 "】（まさか・・・誰かとデートじゃないだろうな。）")
    (wait)
    (text #:color 6 "【やよい】こんな場所で会うなんて奇遇ですね。")
    (wait)
    (text #:color 7 "【" 0 "】ふっ・・・これから僕と一緒に、お酒でもどう？")
    (wait)
    (text #:color 6 "【やよい】" 0 "さんは確か、未成年じゃなかったかしら？")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・知ってたの？")
    (wait)
    (text #:color 6 "【やよい】マスター、ごちそうさま・・・また来ます。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (image "06.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 9)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "06an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "06.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 35)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・ちょっと待ってよ。")
    (wait)
    (text #:color 1 "【バーテン】いらっしゃいませ。")
    (wait)
    (text #:color 7 "【" 0 "】うるさいな。")
    (wait)
    (text #:color 1 "【バーテン】・・・。")
    (wait)
    (set-reg: 611 1)))
  ((&& (== (: 617) 1) (> H 826) (== (: 624) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u.pd8")
    (proc 25)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "uan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 59)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれれっ！？")
    (wait)
    (text #:color 6 "【やよい】あら・・・" 0 "さん。")
    (wait)
    (text #:color 7 "【" 0 "】こんばんは・・・こんな所で会うなんて奇遇だね。")
    (wait)
    (text #:color 6 "【やよい】これから帰るところだったんです・・・" 0 "さんは女の子と待ち合わせですか？")
    (wait)
    (text #:color 7 "【" 0 "】俺が待ち合わせをするとしたら・・・それはやよいさんだけだ。")
    (wait)
    (text #:color 6 "【やよい】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 6 "【やよい】マスター、ごちそうさま・・・" 0 "さん、それじゃあ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (image "06.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 9)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "06an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "06.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 35)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (text #:color 1 "【バーテン】いらっしゃいませ。")
    (wait)
    (text #:color 7 "【" 0 "】黙れ・・・お前なんか嫌いだ。")
    (wait)
    (text #:color 1 "【バーテン】・・・。")
    (wait)
    (set-reg: 624 1)))
  ((&& (== (: 641) 0) (> H 820) (== (: 640) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "c.pd8")
    (proc 25)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "can.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "c.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 60)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】うわっ・・・と。")
    (wait)
    (text #:color 6 "【よしこ】" 0 "君・・・やっぱり来ましたね。")
    (wait)
    (text #:color 7 "【" 0 "】はあ？")
    (wait)
    (text
     #:color
     6
     "【よしこ】こんな店に出入りするのは、"
     0
     "君以外に考えられません・・・私は"
     0
     "君がこの店に来るんじゃなかと思って、ずっと待っていたんです。")
    (wait)
    (text #:color 7 "【" 0 "】おいおいおい。")
    (wait)
    (text #:color 6 "【よしこ】こんな店に出入りするなんて、とんでもありません・・・すぐに帰りなさい。")
    (wait)
    (text #:color 7 "【" 0 "】お、おい、押すなよ！？")
    (wait)
    (text #:color 6 "【よしこ】帰りなさいっ！！")
    (wait)
    (text #:color 7 "【" 0 "】わかったよう・・・もう。")
    (wait)
    (text #:color 1 "【バーテン】ありがとうございました。")
    (wait)
    (text #:color 7 "【" 0 "】うるさいっ！！")
    (wait)
    (text #:color 6 "【よしこ】帰りなさいっ！！")
    (wait)
    (set-reg: 640 1)
    (set-var N 24)
    (slot 1 3)
    (mes-jump "town1.mes")))
  ((== (: 476) 1)
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "06an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "06.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 35)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 1 "【バーテン】いらっしゃいませ。")
    (wait)
    (text #:color 7 "【" 0 "】俺様を迎える気があるなら、こっちを向いて喋れ。")
    (wait)
    (text #:color 1 "【バーテン】しゃかしゃかしゃかしゃか。")
    (wait)
    (text #:color 7 "【" 0 "】ちぇっ、無視しやがった・・・。")
    (wait))))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "外に出る") (text "やめる")))
      (cond
       ((&& (== N 1) (== (: 50) 0))
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・一人でいてもつまらないや。")
         (wait)
         (text #:color 1 "【バーテン】ありがとうごさいました。")
         (wait)
         (text #:color 7 "【" 0 "】何も頼んでないよーん、ざまーみろ。")
         (wait)
         (set-var N 24)
         (set-reg: 476 1)
         (slot 1 3)
         (mes-jump "town1.mes")))
       ((&& (== N 1) (== (: 50) 1))
        (<>
         (text #:color 7 "【" 0 "】帰ろうかな・・・一人でいても面白くないぜ。")
         (wait)
         (text #:color 1 "【バーテン】ありがとうごさいました・・・８００円になります。")
         (wait)
         (text #:color 7 "【" 0 "】こっちを向け。")
         (wait)
         (text #:color 1 "【バーテン】８００円。")
         (wait)
         (text #:color 7 "【" 0 "】ちぇっ・・・わかったよ。")
         (wait)
         (if-else (< M 800)
           (<>
            (text #:color 7 "【" 0 "】・・・。")
            (wait)
            (text #:color 7 "【" 0 "】はっはっはっ！！悪い、お金が足りないぞ。")
            (wait)
            (text #:color 1 "【バーテン】・・・。")
            (wait)
            (text #:color 7 "【" 0 "】はっはっはっ！！")
            (wait)
            (text #:color 1 "【バーテン】お客さん、仕方がないですから・・・皿でも洗ってください。")
            (wait)
            (text #:color 7 "【" 0 "】げっ！！皿洗いをやるのか！？")
            (wait)
            (text #:color 1 "【バーテン】それとも無銭飲食で、警察を呼びますか？")
            (wait)
            (text #:color 7 "【" 0 "】わ、わかったよ・・・やるよ、やればいいんだろ！！")
            (wait)
            (set-arr~ @ 7 1)
            (set-arr~ @ 1 4096)
            (set-arr~ @ 6 1)
            (image "kuro.pd8")
            (proc 24)
            (set-arr~ @ 7 0)
            (text #:color 6 "かちゃかちゃかちゃ・・・。")
            (wait)
            (text #:color 7 "【" 0 "】ふうふうふう。")
            (wait)
            (text #:color 1 "【バーテン】これもお願いします。")
            (wait)
            (text #:color 6 "かちゃかちゃかちゃ・・・。")
            (wait)
            (text #:color 7 "【" 0 "】ふうふうふう。")
            (wait)
            (text #:color 1 "【バーテン】これもお願いします。")
            (wait)
            (text #:color 6 "かちゃかちゃかちゃ・・・。")
            (wait)
            (text #:color 7 "【" 0 "】ふうふうふう。")
            (wait)
            (text #:color 1 "【バーテン】お客さん、もういいですよ・・・また暇になったらお金を持たずに来てくださいね。")
            (wait)
            (text #:color 7 "【" 0 "】ふうふう、はあはあ・・・な、なんてこった、３時間も働かされてしまった。")
            (wait)
            (set-var A 3)
            (proc 13)
            (proc 11)
            (set-var N 24)
            (set-reg: 476 1)
            (slot 1 3)
            (mes-jump "town1.mes"))
           (<>))
         (set-var M (- M 800))
         (proc 11)
         (text #:color 1 "【バーテン】ありがとうございましたー！！")
         (wait)
         (set-var N 24)
         (set-reg: 476 1)
         (slot 1 3)
         (mes-jump "town1.mes")))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・何となくだけど、まだここにいたい気分だ。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】でも・・・どうしていたい気分なんだろ？")
         (wait)))
       (else (<>)))))
    ((&& (== V 2) (== N 1) (== (: 50) 0))
     (<>
      (text #:color 1 "【バーテン】お客様、何に致しましょうか？")
      (wait)
      (text #:color 7 "【" 0 "】何を頼んでいいのか、よくわからないな・・・ちなみに俺は未成年だぞ。")
      (wait)
      (text #:color 1 "【バーテン】そうですか・・・それでは『")
      (set-var S (? 10))
      (if (== S 0) (<> (text "シ")))
      (if (== S 1) (<> (text "ル")))
      (if (== S 2) (<> (text "ソ")))
      (if (== S 3) (<> (text "ニ")))
      (if (== S 4) (<> (text "ト")))
      (if (== S 5) (<> (text "ケ")))
      (if (== S 6) (<> (text "カ")))
      (if (== S 7) (<> (text "ノ")))
      (if (== S 8) (<> (text "ト")))
      (if (== S 9) (<> (text "ラ")))
      (set-var S (? 10))
      (if (== S 0) (<> (text "シ")))
      (if (== S 1) (<> (text "ル")))
      (if (== S 2) (<> (text "ソ")))
      (if (== S 3) (<> (text "ニ")))
      (if (== S 4) (<> (text "ト")))
      (if (== S 5) (<> (text "ケ")))
      (if (== S 6) (<> (text "カ")))
      (if (== S 7) (<> (text "ノ")))
      (if (== S 8) (<> (text "ト")))
      (if (== S 9) (<> (text "ラ")))
      (set-var S (? 10))
      (if (== S 0) (<> (text "シ")))
      (if (== S 1) (<> (text "ル")))
      (if (== S 2) (<> (text "ソ")))
      (if (== S 3) (<> (text "ニ")))
      (if (== S 4) (<> (text "ト")))
      (if (== S 5) (<> (text "ケ")))
      (if (== S 6) (<> (text "カ")))
      (if (== S 7) (<> (text "ノ")))
      (if (== S 8) (<> (text "ト")))
      (if (== S 9) (<> (text "ラ")))
      (text "・ドリンク』などはいかがですか？・・・８００円になりますが。")
      (wait)
      (text #:color 7 "【" 0 "】よくわからないから、それでいいや。")
      (wait)
      (text #:color 1 "【バーテン】少々・・・しゃかしゃかしゃか・・・お待ち・・・しゃかしゃかしゃか・・・ください。")
      (wait)
      (text #:color 7 "【" 0 "】へえ、面白いな・・・ゼンマイ仕掛みたいなバーテンだ。")
      (wait)
      (text #:color 1 "【バーテン】お待たせしました、こちらが『")
      (set-var S (? 10))
      (if (== S 0) (<> (text "シ")))
      (if (== S 1) (<> (text "ル")))
      (if (== S 2) (<> (text "ソ")))
      (if (== S 3) (<> (text "ニ")))
      (if (== S 4) (<> (text "ト")))
      (if (== S 5) (<> (text "ケ")))
      (if (== S 6) (<> (text "カ")))
      (if (== S 7) (<> (text "ノ")))
      (if (== S 8) (<> (text "ト")))
      (if (== S 9) (<> (text "ラ")))
      (set-var S (? 10))
      (if (== S 0) (<> (text "シ")))
      (if (== S 1) (<> (text "ル")))
      (if (== S 2) (<> (text "ソ")))
      (if (== S 3) (<> (text "ニ")))
      (if (== S 4) (<> (text "ト")))
      (if (== S 5) (<> (text "ケ")))
      (if (== S 6) (<> (text "カ")))
      (if (== S 7) (<> (text "ノ")))
      (if (== S 8) (<> (text "ト")))
      (if (== S 9) (<> (text "ラ")))
      (set-var S (? 10))
      (if (== S 0) (<> (text "シ")))
      (if (== S 1) (<> (text "ル")))
      (if (== S 2) (<> (text "ソ")))
      (if (== S 3) (<> (text "ニ")))
      (if (== S 4) (<> (text "ト")))
      (if (== S 5) (<> (text "ケ")))
      (if (== S 6) (<> (text "カ")))
      (if (== S 7) (<> (text "ノ")))
      (if (== S 8) (<> (text "ト")))
      (if (== S 9) (<> (text "ラ")))
      (text "・ドリンク』でございます。")
      (wait)
      (text #:color 7 "【" 0 "】あれ？・・・さっきと言ってる事が違うような？")
      (wait)
      (text #:color 1 "【バーテン】違いません・・・どうぞ、ごゆっくり。")
      (wait)
      (set-reg: 50 1)))
    ((&& (== V 2) (== N 1) (== (: 50) 1))
     (<>
      (text #:color 1 "【バーテン】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】あれれ・・・注文をした後は、やたらに無口になるヤツだな。")
      (wait)))
    ((&& (== V 2) (== N 3) (== (: 10) 0))
     (<>
      (text #:color 7 "【" 0 "】おーいっ！！")
      (wait)
      (text #:color 1 "【バーテン】お客様、マナーを守ってもらいませんと・・・。")
      (wait)
      (text #:color 7 "【" 0 "】マナーって・・・何？")
      (wait)
      (text #:color 1 "【バーテン】ルールでございますね。")
      (wait)
      (text #:color 7 "【" 0 "】へえ・・・校則みたいなものか。")
      (wait)
      (set-reg: 10 1)))
    ((&& (== V 2) (== N 3) (== (: 10) 1))
     (<>
      (text #:color 7 "【" 0 "】おーいっ！！やっほー！！")
      (wait)
      (text #:color 1 "【バーテン】お客様・・・。")
      (wait)
      (text #:color 7 "【" 0 "】わかってるって、ルールだろ？・・・見せてくれよ、そのルールってやつを。")
      (wait)
      (text #:color 1 "【バーテン】ございません、ようするに常識という事でございます。")
      (wait)
      (set-reg: 10 2)))
    ((&& (== V 2) (== N 3) (== (: 10) 2))
     (<>
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 1 "【バーテン】ルールでございますね。")
      (wait)
      (text #:color 7 "【" 0 "】なるほど、ルールって言うのは黙ってる事なんだな。")
      (wait)))
    ((&& (== V 1) (== N 2) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】顔が見たいなあ・・・こっちを向いてくれ。")
      (wait)
      (text #:color 1 "【バーテン】見せるような顔ではございません。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 1) (== N 2) (== (: 11) 1))
     (<>
      (text #:color 7 "【" 0 "】たまには俺を相手にしてくれよ・・・な？")
      (wait)
      (text #:color 1 "【バーテン】お客様・・・こういう場所では一人でじっくり飲むのが、一番格好がいいのでございますよ。")
      (wait)))
    ((&& (== V 1) (== N 4) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】かわいい子だけど・・・彼女は危ないぜ。")
      (wait)
      (text #:color 7 "【" 0 "】そう、手紙の中に剃刀を入れるタイプだな・・・あるいは、玄関の前でずっと立ってるとか。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 4) (== (: 12) 1))
     (<>
      (text #:color 7 "【" 0 "】彼女はいい子だぜ・・・良妻賢母タイプだな。")
      (wait)
      (text #:color 7 "【" 0 "】言ってる事が違うだろ？・・ようするに、どうでもいい女って事だ。")
      (wait)
      (set-reg: 12 2)))
    ((&& (== V 1) (== N 4) (== (: 12) 2))
     (<>
      (text #:color 7 "【" 0 "】彼女は")
      (set-var S (? 10))
      (if (== S 0) (<> (text "悪魔")))
      (if (== S 1) (<> (text "バター")))
      (if (== S 2) (<> (text "娼婦")))
      (if (== S 3) (<> (text "犬")))
      (if (== S 4) (<> (text "ゴキブリ")))
      (if (== S 5) (<> (text "コンピューター")))
      (if (== S 6) (<> (text "アワビ")))
      (if (== S 7) (<> (text "カラス")))
      (if (== S 8) (<> (text "肉の塊")))
      (if (== S 9) (<> (text "トイレ")))
      (text "のような女性だ・・・って、俺はメチャクチャな事を言ってるな。")
      (wait)))
    ((&& (== V 1) (== N 5) (== (: 13) 0))
     (<>
      (text #:color 7 "【" 0 "】男か？・・・それとも女か？")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】髪は長いけど、服装は男に見えるし・・・。")
      (wait)
      (set-reg: 13 1)))
    ((&& (== V 1) (== N 5) (== (: 13) 1))
     (<> (text #:color 7 "【" 0 "】まん中をとって、やつはオカマという事にしておこう。") (wait)))
    ((&& (== V 1) (== N 6) (== (: 14) 0))
     (<>
      (text #:color 7 "【" 0 "】色々なお酒が並んでる・・・射撃の的にしたら面白そうだ。")
      (wait)
      (text #:color 1 "【バーテン】困ります、お客様。")
      (wait)
      (text #:color 7 "【" 0 "】あ・・・けっこう耳がいいんだね。")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 1) (== N 6) (== (: 14) 1))
     (<>
      (text #:color 7 "【" 0 "】バーボン、ウォッカ、ジン、スコッチ、ウィスキー、ブランデー・・・色々なお酒だな。")
      (wait)))
    ((&& (== V 1) (== N 7) (== (: 15) 0))
     (<>
      (text #:color 7 "【" 0 "】この中には何が入ってるんだろ？")
      (wait)
      (text #:color 1 "【バーテン】お酒でございます。")
      (wait)
      (text #:color 7 "【" 0 "】なんだ・・・上と同じか、つまらないの。")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 1) (== N 7) (== (: 15) 1))
     (<> (text #:color 7 "【" 0 "】この中にはお酒が入ってるそうだ・・・火をつけたら、きっとよく燃えるぞ。") (wait)))
    ((&& (== V 1) (== N 8) (== (: 16) 0))
     (<>
      (text #:color 7 "【" 0 "】ピカピカにみがいてある・・・鏡のようなカウンターだ。")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 1) (== N 8) (== (: 16) 1))
     (<>
      (text #:color 7 "【" 0 "】このカウンターの上で、ミニスカねーちゃんが踊るんでしょ？")
      (wait)
      (text #:color 1 "【バーテン】お下劣な深夜番組みたいな事はしません。")
      (wait)
      (text #:color 7 "【" 0 "】ちぇっ、俺ってお下劣が好きなんだよ。")
      (wait)))
    ((&& (== V 1) (== N 9) (== (: 17) 0))
     (<>
      (text #:color 7 "【" 0 "】ねえねえ、どうしてこの椅子ってこんなに高いの？")
      (wait)
      (text #:color 1 "【バーテン】カウンターの高さに合わせてますので。")
      (wait)
      (text #:color 7 "【" 0 "】だったら、椅子もカウンターも低くすればいいじゃない。")
      (wait)
      (text #:color 1 "【バーテン】・・・。")
      (wait)
      (set-reg: 17 1)))
    ((&& (== V 1) (== N 9) (== (: 17) 1))
     (<> (text #:color 7 "【" 0 "】座りにくい椅子だな・・・。") (wait)))
    ((&& (== V 1) (== N 10) (== (: 18) 0))
     (<>
      (text #:color 7 "【" 0 "】ねえ、あっちの席に移ってもいい？")
      (wait)
      (text #:color 1 "【バーテン】あちらは４人以上のお客様専用でございます。")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 1) (== N 10) (== (: 18) 1))
     (<>
      (text #:color 7 "【" 0 "】あのテーブルは、俺の部屋にピッタリだな・・・うん。")
      (wait)
      (text #:color 1 "【バーテン】・・・。")
      (wait)))
    ((&& (== V 1) (== N 11) (== (: 19) 0))
     (<>
      (text #:color 7 "【" 0 "】あれって・・・造花？")
      (wait)
      (text #:color 1 "【バーテン】花ではごさいません、観葉植物でございます。")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 1) (== N 11) (== (: 19) 1))
     (<>
      (text #:color 7 "【" 0 "】バナナの木かな？")
      (wait)
      (text #:color 1 "【バーテン】何度も言うようですが、観葉植物でございます。")
      (wait)))
    ((&& (== V 1) (== N 12) (== (: 20) 0))
     (<>
      (text #:color 7 "【" 0 "】大理石かな・・・すごいぞ。")
      (wait)
      (text #:color 1 "【バーテン】光栄でごさいます・・・あの柱は、天然の大理石を使用しております。")
      (wait)
      (set-reg: 20 1)))
    ((&& (== V 1) (== N 12) (== (: 20) 1))
     (<>
      (text #:color 7 "【" 0 "】あの柱は発砲スチロールでできてるそうだ・・・すごいなあ。")
      (wait)
      (text #:color 1 "【バーテン】・・・大理石でございます。")
      (wait)))
    ((&& (== V 1) (== N 13) (== (: 21) 0))
     (<>
      (text #:color 7 "【" 0 "】（店の雰囲気で、女を酔わす・・・か。）")
      (wait)
      (text #:color 7 "【" 0 "】（ようするに大人になればなる程、金をかけたくどき方をする訳だ・・・やだなあ大人って。）")
      (wait)
      (set-reg: 21 1)))
    ((&& (== V 1) (== N 13) (== (: 21) 1))
     (<> (text #:color 7 "【" 0 "】（奇麗だけど・・・俺には似合わないかな？）") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))