(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\の
  #\っ
  #\【
  #\】
  #\。
  #\て
  #\だ
  #\は
  #\た
  #\な
  #\ん
  #\る
  #\し
  #\、
  #\に
  #\ち
  #\を
  #\女
  #\か
  #\い
  #\彼
  #\ゃ
  #\よ
  #\そ
  #\と
  #\あ
  #\で
  #\う
  #\が
  #\も
  #\後
  #\れ
  #\わ
  #\前
  #\ン
  #\時
  #\俺
  #\ー
  #\け
  #\ら
  #\映
  #\画
  #\ぜ
  #\ま
  #\見
  #\１
  #\２
  #\日
  #\午
  #\忘
  #\今
  #\食
  #\く
  #\触)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (sound 1)
 (set-var I 6)
 (proc 26)
 (while
  (== 1 1)
  (<>
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((&& (== N 12) (== (: 467) 0))
     (<>
      (text #:color 7 "【" 0 "】そうだな・・・ちはるちゃんのデータを見よう。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "27.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "m11.pd8")
      (proc 16)
      (set-arr~ @ 6 1)
      (image "n.pd8")
      (proc 16)
      (set-arr~ @ 6 1)
      (image "nan.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】彼女の名前は『佐久間　ちはる』・・・先負駅の前でナンパした１９歳の女の子だ。")
      (wait)
      (slot 1 5)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "30.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "n06.pd8")
      (proc 16)
      (set-arr~ @ 6 1)
      (image "n06an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n06.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】ナンパして、喫茶店に行って・・・色々と話をしたんだよな。")
      (wait)
      (text #:color 7 "【" 0 "】その時、映画を見る約束をしたんだっけ。")
      (wait)
      (cond
       ((< H 820)
        (<>
         (text #:color 7 "【" 0 "】８月２０日の午後３時に、矢吹町の映画館の前だ・・・忘れちゃだめだぜ。")
         (wait)))
       ((&& (== H 820) (< T 1500))
        (<> (text #:color 7 "【" 0 "】今日の午後３時に、矢吹町の映画館の前だ・・・忘れちゃだめだぜ。") (wait)))
       ((&& (> T 820) (== (: 465) 0))
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】すっぽかしちゃったんだよな・・・ははは。")
         (wait)))
       (else (<>)))
      (if-else (== (: 465) 1)
        (<>
         (slot 1 3)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "n21.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "n10.pd8")
         (proc 16)
         (set-arr~ @ 6 1)
         (image "n10an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "n10.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】あのスーツ姿はよかったな・・・女の子って、着る服によって雰囲気が変わるんだ。")
         (wait)
         (slot 1 5)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "10.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 9)
         (set-arr~ @ 6 1)
         (image "n08.pd8")
         (proc 25)
         (set-arr~ @ 6 1)
         (image "n08an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "n08.s4" (~ @ 2))
         (animate 0 0 1)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】彼女は映画に夢中で、俺は何もできなかった・・・寝てたから退屈はしなかったけど。")
         (wait)
         (animate 0 8 0)
         (animate 4 8))
        (<>))
      (if-else (== (: 466) 1)
        (<>
         (slot 1 5)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (image "06.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 9)
         (set-arr~ @ 6 1)
         (image "n13.pd8")
         (proc 25)
         (set-arr~ @ 6 1)
         (image "n13an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "n13.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text
          #:color
          7
          "【"
          0
          "】その後、ちはるちゃんの知ってる店で食事をして・・・彼女が昔、水商売をやってたって知ったわけだ。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】彼女はムキになって、俺に料理を作ってくれると言ったんだよな・・・。")
         (wait)
         (cond
          ((< H 822)
           (<>
            (text #:color 7 "【" 0 "】約束は８月２２日の午後１時だぜ・・・忘れないようにしないとな。")
            (wait)))
          ((&& (== H 822) (< T 1300))
           (<> (text #:color 7 "【" 0 "】約束は今日の午後１時だぜ・・・忘れないようにしないとな。") (wait)))
          ((&& (> H 822) (== (: 467) 0))
           (<>
            (text #:color 7 "【" 0 "】・・・。")
            (wait)
            (text #:color 7 "【" 0 "】ははは・・・すっぽかしてしまった。")
            (wait)))
          (else (<>))))
        (<>))
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "42.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】ああ、ちはるちゃんのふとももが・・・目の前にチラつくぜ。")
      (wait)
      (set-reg: 608 1)
      (slot 1 2)
      (mes-jump "myroom.mes")))
    ((&& (== N 12) (== (: 467) 1))
     (<>
      (text #:color 7 "【" 0 "】ちはるちゃんのデータを見るのか・・・興奮しそうだなあ。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "27.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "m11.pd8")
      (proc 16)
      (set-arr~ @ 6 1)
      (image "n.pd8")
      (proc 16)
      (set-arr~ @ 6 1)
      (image "nan.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】彼女の名前は『佐久間　ちはる』・・・先負駅の前でナンパした１９歳の女の子だ。")
      (wait)
      (slot 1 5)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "30.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "n06.pd8")
      (proc 16)
      (set-arr~ @ 6 1)
      (image "n06an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n06.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】ナンパして、喫茶店に行って・・・色々と話をしたんだよな。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】しかし、まさかあんな関係になるなんて・・・あの時は思いもしなかったぞ。")
      (wait)
      (slot 1 3)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "n21.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "n10.pd8")
      (proc 16)
      (set-arr~ @ 6 1)
      (image "n10an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n10.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】あのスーツ姿はよかったな・・・女の子って、着る服によって雰囲気が変わるんだ。")
      (wait)
      (text #:color 7 "【" 0 "】彼女と一緒に映画を見て・・・。")
      (wait)
      (slot 1 5)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "10.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 9)
      (set-arr~ @ 6 1)
      (image "n08.pd8")
      (proc 25)
      (set-arr~ @ 6 1)
      (image "n08an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n08.s4" (~ @ 2))
      (animate 0 0 1)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】でも彼女は映画に夢中で、俺は何もできなかった・・・寝てたから退屈はしなかったけど。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (image "06.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 9)
      (set-arr~ @ 6 1)
      (image "n13.pd8")
      (proc 25)
      (set-arr~ @ 6 1)
      (image "n13an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n13.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】その後、ちはるちゃんの知ってる店で食事をして・・・彼女が昔、水商売をやってたって知ったわけだ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】彼女はムキになって、俺に料理を作ってくれると言ったんだよな・・・。")
      (wait)
      (text #:color 7 "【" 0 "】そして俺は彼女の家に行ったんだ・・・忘れもしない８月２２日の午後１時だった。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "05.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "n15.pd8")
      (proc 16)
      (set-arr~ @ 6 1)
      (image "n15an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n15.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】彼女のエプロン姿・・・かわいかったな。")
      (wait)
      (text #:color 7 "【" 0 "】俺は彼女に言われるままに家の中に入り・・・。")
      (wait)
      (slot 1 5)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "n16.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 6 1)
      (image "n16an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n16.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】彼女の手料理をたらふく食べたったわけだ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】でも、手料理を食べた後・・・今度はちはるちゃんを食べちゃったんだよなあ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "n14.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 6 1)
      (image "n14an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n14.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】だいたいあのエプロン姿が刺激的だったんだ・・・あの格好を見ているうちにムラムラしてきて・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "n18.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 6 1)
      (image "n18an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n18.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 7 "【" 0 "】そう・・・後ろからガハっといっちゃったんだよ。")
      (wait)
      (text #:color 7 "【" 0 "】胸を触って・・・その後、彼女の唇を奪ったんだ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "n20.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 6 1)
      (image "n20an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n20.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】ちはるちゃんの唇は、柔らかかったなあ・・・今でも感触が思い出せるぞ。")
      (wait)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】胸を触り、キスをしているうちに・・・彼女もだんだんその気になってきたんだ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "n01.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "n03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "n02.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "n04.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "n05.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 6 1)
      (image "n01an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n01.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text
       #:color
       7
       "【"
       0
       "】あの時のポーズはなかなか過激だったな・・・キッチンの上に座らせて、その上、脚をかばっと開いているなんて・・・。")
      (wait)
      (text #:color 7 "【" 0 "】おっとっと、鼻血が出そうだ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】そして・・・俺は彼女の服を一枚、一枚、脱がしていく。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "n01.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "n03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "n02.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "n04.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 6 1)
      (image "n01an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n01.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】エプロンを取って・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "n01.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "n03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "n02.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 6 1)
      (image "n01an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n01.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】シャツを脱がせ・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "n01.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "n03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 6 1)
      (image "n01an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n01.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】スカートを取り・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "n01.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 6 1)
      (image "n01an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n01.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】ああ・・・まるで今、目の前にちはるちゃんがいるようだ。")
      (wait)
      (text #:color 7 "【" 0 "】そして・・・俺と彼女は結ばれたんだ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "n19.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 6 1)
      (image "n19an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "n19.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】彼女の肌の温もり・・・柔らかい髪の毛・・・そしてアソコの感触。")
      (wait)
      (text #:color 7 "【" 0 "】うーん、全ての感触がまだ身体に残っているぜ・・・。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "42.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】ちはるちゃんに、友達って言われちゃったけど・・・でも二度と会えない訳じゃないしな。")
      (wait)
      (text #:color 7 "【" 0 "】彼女は最後の夏休みの思い出に、ふさわしい女性だったぞ・・・うん。")
      (wait)
      (set-reg: 608 1)
      (slot 1 2)
      (mes-jump "myroom.mes")))
    (else (<>)))))
 (set-arr~ @ 7 1))