(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\。
  #\だ
  #\は
  #\る
  #\い
  #\ち
  #\の
  #\！
  #\な
  #\、
  #\ん
  #\ン
  #\っ
  #\て
  #\こ
  #\か
  #\う
  #\ー
  #\に
  #\し
  #\ゃ
  #\よ
  #\が
  #\？
  #\を
  #\た
  #\く
  #\れ
  #\ピ
  #\ポ
  #\あ
  #\ら
  #\家
  #\ぞ
  #\け
  #\と
  #\ぜ
  #\す
  #\イ
  #\チ
  #\ャ
  #\ム
  #\押
  #\も
  #\日
  #\そ
  #\ま
  #\で
  #\ど
  #\入
  #\わ
  #\俺
  #\２
  #\来
  #\中
  #\欲)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "05.pd8")
 (proc 15)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "05.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (cond
  ((== (: 477) 0)
   (<>
    (text #:color 7 "【" 0 "】ここがちはるちゃんの家かな・・・？")
    (wait)
    (text #:color 7 "【" 0 "】『佐久間』と表札に書いてある・・・確かにここがちはるちゃんの家だ。")
    (wait)
    (if (&&
         (== (: 477) 0)
         (== (: 466) 1)
         (== (: 467) 0)
         (> H 822)
         (== (: 478) 0))
      (<>
       (text #:color 7 "【" 0 "】・・・。")
       (wait)
       (text
        #:color
        7
        "【"
        0
        "】俺は約束を破っちゃったんだよ・・・なんで俺は８月２２日の午後１時に、ここに来なかったんだろう？")
       (wait)
       (set-reg: 478 1)))))
  ((== (: 477) 1)
   (<>
    (text #:color 7 "【" 0 "】ちはるちゃんの家だぜ・・・どうするんだ？")
    (wait)
    (if (&&
         (== (: 477) 0)
         (== (: 466) 1)
         (== (: 467) 0)
         (> H 822)
         (== (: 478) 0))
      (<>
       (text #:color 7 "【" 0 "】・・・。")
       (wait)
       (text
        #:color
        7
        "【"
        0
        "】どうするんだって、俺は約束を破っちゃったんだよ・・・なんで俺は８月２２日の午後１時に、ここに来なかったんだろう？")
       (wait)
       (set-reg: 478 1))))))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "他の場所に行く") (text "中に入る") (text "やめる")))
      (cond
       ((&& (== N 1) (== (: 477) 0))
        (<>
         (text #:color 7 "【" 0 "】わかった・・・他の場所に行こう。")
         (wait)
         (set-var N 10)
         (set-reg: 477 1)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 1) (== (: 477) 1))
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・他の場所に行くか。")
         (wait)
         (set-var N 10)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 2) (> T 2300))
        (<> (text #:color 7 "【" 0 "】こんなに遅いんだぜ・・・明日にしようぜ。") (wait)))
       ((&& (== N 2) (< T 600))
        (<>
         (text #:color 7 "【" 0 "】はっはっはっ・・・目覚めのチャイムだな。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】やめよう・・・ちはるちゃんに嫌われてしまうぞ。")
         (wait)))
       ((&& (== N 2) (< H 822) (== (: 10) 0))
        (<>
         (text #:color 7 "【" 0 "】よーし、チャイムを押すぞ・・・。")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 7 "【" 0 "】・・・留守のようだぞ。")
         (wait)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)))
       ((&& (== N 2) (< H 822) (== (: 10) 1))
        (<>
         (text #:color 7 "【" 0 "】よーし、もう一度押してみるか・・・。")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 7 "【" 0 "】・・・いない。")
         (wait)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)))
       ((&& (== N 2) (> H 822) (== (: 467) 0))
        (<>
         (text #:color 7 "【" 0 "】よーし、チャイムを押すぞ・・・。")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 7 "【" 0 "】ちはるちゃんは・・・出かけてるのか？")
         (wait)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)))
       ((&& (== N 2) (== H 822) (< T 1230))
        (<>
         (text #:color 7 "【" 0 "】よーし、チャイムを押して・・・と。")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】あれれ！？・・・約束は今日のはずだけど、ちょっと早すぎたようだぞ。")
         (wait)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)))
       ((&& (== N 2) (== H 822) (> T 1229) (< T 1331))
        (<>
         (text #:color 7 "【" 0 "】よーし、チャイムを押すぞ・・・。")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 3 "【ちはる】はーい！！")
         (wait)
         (text #:color 7 "【" 0 "】" 0 "だけど・・・。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "n15.pd8")
         (proc 16)
         (set-arr~ @ 6 1)
         (image "n15an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "n15.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 6)
         (proc 26)
         (set-reg: 835 0)
         (animate 0 8 1)
         (animate 4 8)
         (text #:color 3 "【ちはる】" 0 "君・・・来てくれたのね。")
         (wait)
         (text #:color 7 "【" 0 "】（おおっと！！・・・ちはるちゃんのエプロン姿だ。）")
         (wait)
         (text #:color 3 "【ちはる】グット・タイミングよ・・・ほーら、いい匂いがするでしょう？")
         (wait)
         (text #:color 7 "【" 0 "】いい匂いって、ここは外だぜ。")
         (wait)
         (text #:color 3 "【ちはる】私の作る料理は、とってもフレーバーだから・・・ここまで匂うのよ。")
         (wait)
         (text #:color 7 "【" 0 "】くんか、くんか・・・わからない。")
         (wait)
         (text #:color 3 "【ちはる】あ、いっけない！！")
         (wait)
         (text #:color 7 "【" 0 "】へ！？")
         (wait)
         (text #:color 3 "【ちはる】お鍋を火にかけたままだわ・・・" 0 "君、早く中に入って！！")
         (wait)
         (text #:color 7 "【" 0 "】へ！？")
         (wait)
         (text #:color 3 "【ちはる】だから、早く家の中に入ってよ・・・大丈夫だったら、パパとママは昼間はいないわよ。")
         (wait)
         (slot 1 5)
         (mes-jump "chi_in.mes")))
       ((&& (== N 2) (== H 822) (> T 1330) (== (: 11) 0) (== (: 467) 0))
        (<>
         (text #:color 7 "【" 0 "】ちょっと遅刻しちゃったな・・・。")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】あれれ！？・・・返事がないぞ！？")
         (wait)
         (set-reg: 11 1)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)))
       ((&& (== N 2) (== H 822) (> T 1330) (== (: 11) 1) (== (: 467) 0))
        (<>
         (text #:color 7 "【" 0 "】も、もう一度チャイムを押して・・・なんだかアセるな。")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】駄目だ・・・誰も出て来ない。")
         (wait)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)))
       ((&& (== N 2) (> H 821) (< H 824) (== (: 467) 1) (== (: 30) 0))
        (<>
         (text #:color 7 "【" 0 "】よーし、チャイムを押すぞ・・・。")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "n15.pd8")
         (proc 16)
         (set-arr~ @ 6 1)
         (image "n15an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "n15.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 6)
         (proc 26)
         (set-reg: 835 0)
         (animate 0 8 1)
         (animate 4 8)
         (text #:color 3 "【ちはる】あ・・・" 0 "君。")
         (wait)
         (text #:color 7 "【" 0 "】ちはるちゃん・・・。")
         (wait)
         (text #:color 3 "【ちはる】ごめんね・・・もうパパが帰って来てるの。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 3 "【ちはる】じゃあね・・・ばいばい。")
         (wait)
         (text #:color 7 "【" 0 "】あ・・・。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "05.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)
         (text #:color 7 "【" 0 "】ちはるちゃんは・・・家の中に入ってしまった。")
         (wait)
         (set-reg: 30 1)))
       ((&& (== N 2) (> H 821) (< H 824) (== (: 467) 1) (== (: 30) 1))
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】よそうぜ・・・しつこい男は嫌われる。")
         (wait)))
       ((&& (== N 2) (> H 823) (== (: 467) 1) (== (: 30) 0))
        (<>
         (text #:color 7 "【" 0 "】よーし、チャイムを押すぞ・・・。")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】ちはるちゃんは・・・出かけてるのかな？")
         (wait)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)
         (set-reg: 30 1)))
       ((&& (== N 2) (> H 823) (== (: 467) 1) (== (: 30) 1))
        (<>
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】いない・・・他の場所に行くか。")
         (wait)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)))
       ((== N 3)
        (<>
         (text #:color 7 "【" 0 "】ここでちはるちゃんを待つのか？・・・俺はそんなに暇じゃないはずだぜ。")
         (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 1) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】電柱だな・・・下の方に黄色と黒のシマシマがある。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 1) (== (: 12) 1))
     (<> (text #:color 7 "【" 0 "】電柱だぜ・・・これを破壊すると、このあたり一帯は停電だ。") (wait)))
    ((&& (== V 1) (== N 2) (== (: 13) 0))
     (<>
      (text #:color 7 "【" 0 "】水銀灯だぜ・・・欲しいのか？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "欲しい") (text "欲しくない")))
      (cond
       ((== N 1) (<> (text #:color 7 "【" 0 "】いいや、絶対に欲しくない。") (wait)))
       ((== N 2) (<> (text #:color 7 "【" 0 "】いいや、欲しい。") (wait)))
       (else (<>)))
      (set-reg: 13 1)))
    ((&& (== V 1) (== N 2) (== (: 13) 1))
     (<> (text #:color 7 "【" 0 "】水銀灯だな・・・あれがなくて喜ぶのは、痴漢と泥棒ぐらいだ。") (wait)))
    ((&& (== V 1) (== N 3) (== (: 14) 0))
     (<>
      (text #:color 7 "【" 0 "】ちはるちゃんの家の入口だ・・・けっこう古風な造りだぞ。")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 1) (== N 3) (== (: 14) 1))
     (<> (text #:color 7 "【" 0 "】ここを入れば、ちはるちゃんの家の中だ・・・。") (wait)))
    ((&& (== V 1) (== N 4) (== (: 15) 0))
     (<>
      (text #:color 7 "【" 0 "】このあたりは住宅街のようだな・・・家の塀だらけだぜ。")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 1) (== N 4) (== (: 15) 1))
     (<> (text #:color 7 "【" 0 "】塀だ・・・いちいち見るもんじゃない。") (wait)))
    ((&& (== V 1) (== N 5) (== (: 16) 0))
     (<> (text #:color 7 "【" 0 "】樹木が繁ってるぜ・・・夏だからな。") (wait) (set-reg: 16 1)))
    ((&& (== V 1) (== N 5) (== (: 16) 1))
     (<>
      (text #:color 7 "【" 0 "】樹木があると言う事は、それだけ虫がたくさんいるって事だ・・・まあ、喜ぶのは子供だけだろうけど。")
      (wait)))
    ((&& (== V 1) (== N 6) (== (: 17) 0))
     (<>
      (text #:color 7 "【" 0 "】これがちはるちゃんの家だ・・・木造２階建だな。")
      (wait)
      (set-reg: 17 1)))
    ((&& (== V 1) (== N 6) (== (: 17) 1))
     (<> (text #:color 7 "【" 0 "】庭が広そうな家だな・・・。") (wait)))
    ((&& (== V 1) (== N 7) (== (: 18) 0))
     (<>
      (text #:color 7 "【" 0 "】『火・木・土が燃えるゴミ、水曜日が燃えないゴミ』・・・だそうだ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】そうだ、水曜日に健二をここに捨ててしまおう。")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 1) (== N 7) (== (: 18) 1))
     (<> (text #:color 7 "【" 0 "】住宅街の定番だぜ・・・ゴミの収拾日の貼紙だ。") (wait)))
    ((&& (== V 1) (== N 8) (== (: 19) 0))
     (<> (text #:color 7 "【" 0 "】道路だ・・・確かに舗装はされてない。") (wait) (set-reg: 19 1)))
    ((&& (== V 1) (== N 8) (== (: 19) 1))
     (<> (text #:color 7 "【" 0 "】細くて舗装されてないって事は・・・私道かな？") (wait)))
    ((&& (== V 1) (== N 9) (== (: 20) 0))
     (<> (text #:color 7 "【" 0 "】空は電線だらけだ・・・。") (wait) (set-reg: 20 1)))
    ((&& (== V 1) (== N 9) (== (: 20) 1))
     (<> (text #:color 7 "【" 0 "】建物が密集してるから、空が狭く見えるぞ・・・。") (wait)))
    ((&& (== V 1) (== N 10) (== (: 21) 0))
     (<> (text #:color 7 "【" 0 "】知らない人の家だ・・・どうでもいいぞ。") (wait) (set-reg: 21 1)))
    ((&& (== V 1) (== N 10) (== (: 21) 1))
     (<> (text #:color 7 "【" 0 "】だから、知らない人の家だって・・・。") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))