(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\い
  #\な
  #\。
  #\の
  #\、
  #\っ
  #\だ
  #\て
  #\ん
  #\る
  #\か
  #\は
  #\う
  #\に
  #\し
  #\あ
  #\？
  #\ら
  #\が
  #\と
  #\た
  #\よ
  #\！
  #\を
  #\で
  #\人
  #\ゃ
  #\く
  #\ー
  #\ち
  #\も
  #\さ
  #\こ
  #\そ
  #\お
  #\ね
  #\映
  #\画
  #\れ
  #\女
  #\ど
  #\一
  #\ま
  #\り
  #\子
  #\じ
  #\言
  #\わ
  #\や
  #\え
  #\け
  #\俺
  #\ト
  #\す
  #\み
  #\ッ
  #\ぜ
  #\チ
  #\男
  #\事
  #\つ
  #\き
  #\何
  #\美
  #\『
  #\』
  #\ろ
  #\見
  #\ケ
  #\中
  #\沙
  #\観
  #\前
  #\ば
  #\場
  #\行
  #\入
  #\パ
  #\君
  #\夏
  #\ス
  #\私
  #\ン
  #\来
  #\売
  #\せ
  #\館
  #\ぞ
  #\デ
  #\緒
  #\気
  #\ょ
  #\ル
  #\今
  #\哉
  #\達
  #\ク
  #\タ
  #\思
  #\出
  #\大
  #\マ
  #\ほ
  #\愛
  #\目
  #\イ
  #\友
  #\め
  #\ひ
  #\立
  #\次
  #\性
  #\間
  #\買
  #\聞
  #\ポ
  #\所
  #\ぶ
  #\書
  #\１
  #\毛
  #\郎
  #\カ
  #\本
  #\合)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "n21.pd8")
 (proc 24)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "n21an.pd8")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 0)
 (load "n21.s4" (~ @ 2))
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "04.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (cond
  ((== (: 202) 0)
   (<>
    (text
     #:color
     7
     "【"
     0
     "】ここは映画館の前だな・・・１階では『思ひ出どろどろ』、２階では『愛と肉棒の旅立ち』、３階では『下の毛半次郎』という映画をやっている。")
    (wait)
    (text #:color 7 "【" 0 "】ちぇっ、カップルだらけだぜ・・・一人で映画を見るのもつまらないしなあ。")
    (wait)))
  ((&& (== (: 396) 0) (== (: 250) 1) (== (: 481) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "i.pd8")
    (proc 25)
    (set-arr~ @ 6 1)
    (image "r.pd8")
    (proc 25)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ran.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "r.s4" (~ @ 2))
    (animate 0 0 2)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【一哉】" 0 "じゃないか・・・。")
    (wait)
    (text #:color 6 "【くるみ】こんにちは、" 0 "さん。")
    (wait)
    (text #:color 7 "【" 0 "】いいなあ、デートか？")
    (wait)
    (text #:color 5 "【一哉】本当にいいと思うか？・・・映画を見るなんて、小学生のデートだぜ。")
    (wait)
    (text #:color 6 "【くるみ】もう、そんな事ばっかり言うんだから。")
    (wait)
    (text #:color 5 "【一哉】ああ、俺も" 0 "みたいに自由に、大人のつき合いができる女性と、何人も何人も何人も、はあはあはあ。")
    (wait)
    (text #:color 7 "【" 0 "】おいおい、血管が浮き出てるぞ。")
    (wait)
    (text #:color 6 "【くるみ】あ、大変！！・・・一哉君、もう上演時間よ。")
    (wait)
    (text #:color 5 "【一哉】と言う訳だ・・・じゃあな、" 0 "。")
    (wait)
    (text #:color 6 "【くるみ】" 0 "さん、一哉君ね・・・" 0 "さんが一緒に遊んでくれないから、寂しいって言ってたのよ。")
    (wait)
    (text #:color 5 "【一哉】余計な事を言うなよ・・・。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21.pd8")
    (proc 24)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n21.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】くるみちゃんと一緒だったら、映画でもいいけどな・・・中は暗いし、色々とできるじゃないか。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あ、それ以前に・・・くるみちゃんが、触られるのをいやがるのか・・・納得した。")
    (wait)
    (set-reg: 396 1)))
  ((&& (== (: 397) 0) (== (: 261) 1))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "e.pd8")
    (proc 25)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ean.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "e.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 22)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれ？")
    (wait)
    (text #:color 6 "【かおり】また会ったわね・・・私達って縁があるのかしら？")
    (wait)
    (text #:color 7 "【" 0 "】そうだよきっと・・・縁があるんだから、これから一緒に映画を見ない？")
    (wait)
    (text #:color 6 "【かおり】残念でした、先約があるの・・・私はあんまり乗り気じゃないけど。")
    (wait)
    (text #:color 7 "【" 0 "】いいじゃない、そんなヤツ・・・俺と一緒に映画を見ようよう。")
    (wait)
    (text #:color 6 "【かおり】私もそうしたいけど、その人、怒ると恐いのよ・・・だから今日は駄目。")
    (wait)
    (text #:color 7 "【" 0 "】平気、平気、俺ってケンカ強いから。")
    (wait)
    (text #:color 6 "【かおり】噂をすれば、なんとかね・・・その恐い人が来ちゃった、じゃあね！！")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・待ってよ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21.pd8")
    (proc 24)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n21.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text
     #:color
     7
     "【"
     0
     "】げっ！！本当に恐いヤツだぜ・・・身体はでかいし、ついでに太ってるし、スーツはハデハデだし、ネクタイはバラの模様だ。")
    (wait)
    (set-reg: 397 1)))
  ((&& (== (: 398) 0) (== (: 271) 1) (== (: 685) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "l.pd8")
    (proc 25)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "lan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "l.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 3 "【美沙】" 0 "っ！！・・・何をしてるんだ？")
    (wait)
    (text #:color 7 "【" 0 "】よう、セーラー服少女・・・売春でもしてるのか？")
    (wait)
    (text #:color 3 "【美沙】" 0 "こそ逆に、売春してるやつを捜してるんじゃないか？")
    (wait)
    (text #:color 7 "【" 0 "】はっはっはっ、俺様は金で女は買わない主義だ・・・そんな事をしても、ちっとも楽しくない。")
    (wait)
    (text #:color 3 "【美沙】ようするに、金がないって事だよな・・・ははは。")
    (wait)
    (text
     #:color
     7
     "【"
     0
     "】美沙、俺に身体を買って欲しいんだったら素直にそう言えよ・・・美沙だったら、一本で買ってあげてもいいぜ。")
    (wait)
    (text #:color 3 "【美沙】１０マンエンか？")
    (wait)
    (text #:color 7 "【" 0 "】千円。")
    (wait)
    (text #:color 6 "ボクンッ！！")
    (wait)
    (text #:color 7 "【" 0 "】いったーい。")
    (wait)
    (text #:color 3 "【美沙】はあはあはあ、私の裸を見たら・・・そんな事は言えなくなるぜ。")
    (wait)
    (text #:color 7 "【" 0 "】そ、そんなにすごいの！？・・・胸毛が生えているとか？")
    (wait)
    (text #:color 6 "ドシュッ！！")
    (wait)
    (text #:color 7 "【" 0 "】いててて・・・け、蹴る事はないだろう、パンツが見えたけど。")
    (wait)
    (text #:color 3 "【美沙】" 0 "と話をすると、頭が痛くなってくる・・・どうしてこんなやつに・・・。")
    (wait)
    (text #:color 7 "【" 0 "】こんなやつに？")
    (wait)
    (text #:color 3 "【美沙】な、なんでもないよ・・・じゃあなっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21.pd8")
    (proc 24)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n21.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】いてててて・・・陸上部のくせに、脚を使うなんて・・・なんて女だよ。")
    (wait)
    (set-reg: 398 1)))
  ((&& (== (: 688) 1) (> T 1000) (< T 1900) (== (: 689) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "a.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "aan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "a.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 3 "【美沙】なんだよ。")
    (wait)
    (text #:color 7 "【" 0 "】何がだよ。")
    (wait)
    (text #:color 3 "【美沙】" 0 "・・・映画を観てる場合か？")
    (wait)
    (text #:color 7 "【" 0 "】俺が何をしようが勝手だろ・・・美沙にあれこれ言われる筋合いはない。")
    (wait)
    (text #:color 3 "【美沙】" 0 "に筋合いがなくても、私にはあるんだよ・・・私は美穂の友達だからな。")
    (wait)
    (text #:color 7 "【" 0 "】なあ・・・どうして美穂ちゃんの名前が出てくるんだ？")
    (wait)
    (text #:color 3 "【美沙】美穂が・・・落ち込んでいるからだよ。")
    (wait)
    (text #:color 7 "【" 0 "】それは前に聞いたぜ・・・で、それが俺と関係あるのか？")
    (wait)
    (text #:color 3 "【美沙】はあ・・・どうして" 0 "みたいなやつを・・・わからないなあ。")
    (wait)
    (text #:color 7 "【" 0 "】へ？")
    (wait)
    (text #:color 3 "【美沙】もういい・・・私は行くぜ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21.pd8")
    (proc 24)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n21.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あいつ、まだ生理が止まらないのかな・・・たれ流しってやつか？")
    (wait)
    (set-reg: 689 1)))
  ((&&
    (== (: 695) 1)
    (> H 819)
    (> T 1000)
    (< T 1900)
    (== (: 699) 0)
    (== (: 708) 0))
   (<>
    (text #:color 7 "【" 0 "】うーん・・・かわいい子がいないかな？")
    (wait)
    (text #:color 7 "【" 0 "】あれも駄目・・・これも駄目、と。")
    (wait)
    (text #:color 7 "【" 0 "】あの子は胸が大きいけど、おフェイスがちょっとな・・・。")
    (wait)
    (text #:color 3 "【女の声】" 0 "。")
    (wait)
    (text #:color 7 "【" 0 "】あの子は足首が細いけど・・・体型が三角スイのようだぞ。")
    (wait)
    (text #:color 3 "【女の声】" 0 "っ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "a.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "aan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "a.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】うーん・・・この子は顔もかわいいし体型もいいけど、言葉使いが悪い。")
    (wait)
    (text #:color 3 "【美沙】何が悪いって？")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・俺を呼び止めたからには、ただでは帰さないぞ。")
    (wait)
    (text #:color 3 "【美沙】なあ・・・美穂とデートか？")
    (wait)
    (text #:color 7 "【" 0 "】美穂ちゃんとデート？・・・俺がか？")
    (wait)
    (text #:color 3 "【美沙】なんだ・・・違うのか。")
    (wait)
    (text #:color 7 "【" 0 "】そうがっかりするな、ご希望とあればいつでもデートしてやるぜ。")
    (wait)
    (text #:color 3 "【美沙】真面目にか？")
    (wait)
    (text #:color 7 "【" 0 "】当り前だ、全身をぴかぴかに磨き上げて、精力剤を１リットル飲んで、真面目に彼女の前に現れてやる。")
    (wait)
    (text #:color 3 "【美沙】頭が痛くなってきた・・・じゃあな、" 0 "。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21.pd8")
    (proc 24)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n21.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】それでも足りないと言うのなら、ポコチンに赤いリボンをまいてやってもいいぞ。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】おーい、美沙っ！！聞いてるのかっ！？")
    (wait)
    (set-reg: 699 1)))
  ((&& (== (: 438) 1) (== (: 444) 0) (== (: 765) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "b.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "man.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 4 "【健二】ふう・・・。")
    (wait)
    (text #:color 7 "【" 0 "】源治。")
    (wait)
    (text #:color 4 "【健二】健二だっ！！")
    (wait)
    (text #:color 7 "【" 0 "】悪い、悪い、こんな場所で映画のヤミチケットを売ってるのか？")
    (wait)
    (text #:color 4 "【健二】僕はダフ屋じゃないぞ・・・さっきまで女の子と一緒に映画を見てたんだ。")
    (wait)
    (text #:color 7 "【" 0 "】ママの事か？")
    (wait)
    (text #:color 4 "【健二】ママじゃないっ！！")
    (wait)
    (text #:color 7 "【" 0 "】じゃあ、パパかな？")
    (wait)
    (text #:color 4 "【健二】ふっ・・・何とでも言え、これから他の女の子とデートなんだ・・・あばよ、" 0 "。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21.pd8")
    (proc 24)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n21.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】はっはっはっ、怒って行ってしまった。")
    (wait)
    (set-reg: 444 1)))
  ((&& (== (: 481) 1) (> H 818) (> T 800) (< T 1900) (== (: 512) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "q.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "qan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "q.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】くるみちゃん、一哉とデート・・・のわけがないか。")
    (wait)
    (text #:color 6 "【くるみ】何て言ったの？")
    (wait)
    (text #:color 7 "【" 0 "】い、いや・・・何でもない。")
    (wait)
    (text #:color 6 "【くるみ】私ね、友達と映画を見に来てたの・・・とっても面白かったわよ。")
    (wait)
    (text #:color 7 "【" 0 "】そりゃよかった・・・くるみちゃんが楽しいと、俺まで楽しくなってくるぜ。")
    (wait)
    (text #:color 6 "【くるみ】その友達がね、私が落ち込んでるから・・・すごく気を使ってくれたの。")
    (wait)
    (text #:color 7 "【" 0 "】ふーん、いい友達だな・・・。")
    (wait)
    (text #:color 6 "【くるみ】すっごくかわいいのよ、『まるこ』ちゃんって言うんだけど・・・" 0 "さん知ってる？")
    (wait)
    (text #:color 7 "【" 0 "】まるこちゃん！？・・・い、いや、いい名前だねえ。")
    (wait)
    (text #:color 6 "【くるみ】その子ね、" 0 "さんのファンなの・・・今度紹介してもいい？")
    (wait)
    (text #:color 7 "【" 0 "】その『ま○こ』ちゃん・・・あ、いけない。")
    (wait)
    (text #:color 6 "【通行人Ａ】やだ・・・変な事を言ってる人がいるわよ。")
    (wait)
    (text #:color 5 "【通行人Ｂ】まったく、昼間っからあんな事を言っとるとは・・・日本の将来はどうなるんじゃ！！")
    (wait)
    (text #:color 4 "【通行人Ｃ】やらしいなあ、あんな・・・平気で『ま○こ』なんて、普通言えないぜ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21.pd8")
    (proc 24)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n21.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 5 "【通行人Ｄ】お前なあ、そういう言葉を言うなら場所を選べよ・・・言うやつより、聞いてるやつの方が恥ずかしいんだぜ。")
    (wait)
    (text #:color 6 "【通行人Ｅ】変態！！")
    (wait)
    (text #:color 7 "【" 0 "】まいったなあ、ボロボロに言われてしまった・・・あれれ！？")
    (wait)
    (text #:color 7 "【" 0 "】おーい、くるみちゃーん！！")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】どこかに行っちゃったよ・・・おい。")
    (wait)
    (set-reg: 512 1)))
  ((&& (== (: 467) 1) (== (: 849) 0) (> H 828))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n10.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "n10an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n10.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 6)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 3 "【ちはる】あれえ、" 0 "君じゃない・・・映画でも見に来たの？")
    (wait)
    (text #:color 7 "【" 0 "】ちはるちゃん・・・セックスしてる？")
    (wait)
    (text #:color 3 "【ちはる】恥ずかしい事を言わないでよ・・・" 0 "君として以来、一回もしてないわよ。")
    (wait)
    (text #:color 7 "【" 0 "】そっちだって、平気で恥ずかしい事を言うじゃないか。")
    (wait)
    (text #:color 3 "【ちはる】" 0 "君とのセックスがよすぎちゃって、他の人とする気になれないわ。")
    (wait)
    (text #:color 7 "【" 0 "】俺も同感だな。")
    (wait)
    (text #:color 3 "【ちはる】嘘ばっかり。")
    (wait)
    (text #:color 3 "【ちはる】・・・。")
    (wait)
    (text #:color 3 "【ちはる】考えてみたら、ここで一緒に映画を見たのよね・・・" 0 "君は寝ちゃったけど。")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・。")
    (wait)
    (text #:color 3 "【ちはる】" 0 "君にとって・・・私ってただの思い出なのかしら？")
    (wait)
    (text #:color 7 "【" 0 "】え？")
    (wait)
    (text #:color 3 "【ちはる】ううん、何でもないの・・・じゃあね、エッチな" 0 "君！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21.pd8")
    (proc 24)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n21.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】なんだよ・・・もう少し話をしてくれてもいいじゃないか。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】彼女、何か言いたそうだったけど・・・まあいいか。")
    (wait)
    (set-reg: 849 1)))
  ((&&
    (== (: 566) 1)
    (== (: 569) 1)
    (> H 817)
    (> T 800)
    (< T 1700)
    (== (: 573) 0)
    (== (: 571) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "e.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ean.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "e.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 22)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【かおり】もう・・・あったまきちゃう、ぶつぶつぶつ。")
    (wait)
    (text #:color 7 "【" 0 "】ありゃ・・・かおりさんだよ。")
    (wait)
    (text #:color 6 "【かおり】もう、約束を破るなんて最低だわ。")
    (wait)
    (text #:color 7 "【" 0 "】俺の事？")
    (wait)
    (text #:color 6 "【かおり】あいつめ・・・今度店に来たら噛じってやるから、ぷんぷん！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21.pd8")
    (proc 24)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n21.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】もしかして、かおりさん・・・俺の存在に気づいてない？")
    (wait)
    (set-reg: 573 1)))
  ((&&
    (== (: 235) 1)
    (== (: 488) 1)
    (== (: 491) 0)
    (> T 1000)
    (< T 1900)
    (== (: 500) 0)
    (== (: 539) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "jan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 2 "【夏子】" 0 "君・・・。")
    (wait)
    (text #:color 7 "【" 0 "】誰かと思ったら、夏子さん・・・一哉と一緒じゃないの？")
    (wait)
    (text #:color 2 "【夏子】ううん、一人よ・・・約束の時間までだいぶあるから、映画を観て時間をつぶしてたの。")
    (wait)
    (text #:color 7 "【" 0 "】なんだ・・・暇だったら俺を呼んでくれればいいのに。")
    (wait)
    (text #:color 2 "【夏子】そうね・・・そうすればよかったわ。")
    (wait)
    (text #:color 7 "【" 0 "】え！？")
    (wait)
    (text #:color 2 "【夏子】言っておくけど、約束って一哉君じゃないわよ・・・全然違う人だからね。")
    (wait)
    (text #:color 7 "【" 0 "】げっ！！・・・夏子さんって、そんなにたくさん男の友達がいるんだ。")
    (wait)
    (text #:color 2 "【夏子】女の子の友達・・・専門学校の同級生。")
    (wait)
    (text #:color 7 "【" 0 "】俺に紹介してくれ。")
    (wait)
    (text #:color 2 "【夏子】いやよ、紹介だなんて。")
    (wait)
    (text #:color 7 "【" 0 "】どうしてだよ。")
    (wait)
    (text #:color 2 "【夏子】どうしても・・・いやなの。")
    (wait)
    (text #:color 7 "【" 0 "】ケチ。")
    (wait)
    (text #:color 2 "【夏子】何とでも言いなさい・・・" 0 "君、私は時間がないから行くけど。")
    (wait)
    (text #:color 7 "【" 0 "】ケチ。")
    (wait)
    (text #:color 2 "【夏子】じゃあね、さようなら・・・。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21.pd8")
    (proc 24)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n21.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】ちぇっ・・・紹介してくれたっていいじゃないか。")
    (wait)
    (text
     #:color
     7
     "【"
     0
     "】あーあ、新しい女の子と知り合いになりたいなあ・・・かわいくて、スタイルがよくて、性格がよければ文句を言わないぜ、俺は。")
    (wait)
    (set-reg: 500 1)))
  ((&& (== (: 641) 0) (> H 817) (> T 800) (< T 2100) (== (: 644) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "c.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "can.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "c.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 60)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【よしこ】あら、" 0 "君・・・一人で映画を観に来たのかしら？")
    (wait)
    (text #:color 7 "【" 0 "】まさか、俺は一人で映画なんて観ないよ。")
    (wait)
    (text #:color 6 "【よしこ】映画は一人で観るものですよ・・・その方が集中できますから。")
    (wait)
    (text #:color 7 "【" 0 "】先生は一人でしか映画を観ないんでしょ？")
    (wait)
    (text #:color 6 "【よしこ】・・・。")
    (wait)
    (text #:color 6 "【よしこ】" 0 "君、今の言葉に深い意味はあります？")
    (wait)
    (text #:color 7 "【" 0 "】ありません。")
    (wait)
    (text #:color 6 "【よしこ】そう・・・ならいいですけど。")
    (wait)
    (text #:color 6 "【よしこ】映画ばかり観てないで、自分の将来の事をちゃんと考えてくださいね・・・来年は社会人なんですから。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21.pd8")
    (proc 24)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n21.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】来年は社会人か・・・わからないぜ、卒業できない可能性だってあるからな。")
    (wait)
    (set-reg: 644 1)))
  ((&&
    (== (: 519) 1)
    (== (: 523) 0)
    (> H 827)
    (> T 800)
    (< T 1900)
    (== (: 527) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "r.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ran.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "r.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】やあ、くるみちゃん。")
    (wait)
    (text #:color 6 "【くるみ】" 0 "さん・・・まさか、誰かさんとデート？")
    (wait)
    (text #:color 7 "【" 0 "】いいや、一人だけど。")
    (wait)
    (text #:color 6 "【くるみ】よかった・・・。")
    (wait)
    (text #:color 7 "【" 0 "】え？")
    (wait)
    (text #:color 6 "【くるみ】ううん・・・私は一人じゃないのよ。")
    (wait)
    (text #:color 7 "【" 0 "】そう。")
    (wait)
    (text #:color 6 "【くるみ】そうって・・・気にならないの？")
    (wait)
    (text #:color 7 "【" 0 "】はあ？")
    (wait)
    (text #:color 6 "【くるみ】待ち合わせしてるの、女の子だけど。")
    (wait)
    (text #:color 7 "【" 0 "】ふーん。")
    (wait)
    (text #:color 6 "【くるみ】ふーんって・・・それだけ？")
    (wait)
    (text #:color 2 "【くるみの友達】くるみちゃーん！！")
    (wait)
    (text #:color 6 "【くるみ】あ、来たみたい・・・じゃあね、" 0 "さん！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21.pd8")
    (proc 24)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n21.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】くるみちゃんの友達は・・・どんな子だ？")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】見なければよかった・・・。")
    (wait)
    (set-reg: 523 1)))
  ((&&
    (== (: 539) 1)
    (== (: 547) 1)
    (> H 828)
    (> T 800)
    (< T 2359)
    (== (: 533) 0)
    (== (: 527) 0)
    (== (: 550) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "jan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】な、夏子さんっ！！")
    (wait)
    (text #:color 2 "【夏子】" 0 "君・・・どうしたの、大声を出しちゃって。")
    (wait)
    (text #:color 7 "【" 0 "】夏子さんと会えた事がうれしいからさ。")
    (wait)
    (text #:color 2 "【夏子】・・・。")
    (wait)
    (text #:color 2 "【夏子】ありがとう・・・私も" 0 "君と会えてうれしいわよ。")
    (wait)
    (text #:color 7 "【" 0 "】ほ、本当！？・・・だったら今からデートしようぜ。")
    (wait)
    (text #:color 2 "【夏子】ごめんなさい、今から学校に行くの・・・また今度ね。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21.pd8")
    (proc 24)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n21.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】あ・・・ち、ちょっと待って。")
    (wait)
    (text #:color 7 "【" 0 "】あーあ、行っちゃった・・・学校よりも俺を大事にしてくれよう。")
    (wait)
    (set-reg: 550 1)))
  ((&&
    (== (: 728) 1)
    (== (: 710) 1)
    (> H 827)
    (< H 829)
    (> T 800)
    (< T 2359)
    (== (: 740) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【太郎】不潔だあっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21.pd8")
    (proc 24)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n21.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (set-reg: 740 1)))
  ((&&
    (== (: 728) 1)
    (== (: 710) 0)
    (> H 827)
    (< H 829)
    (> T 800)
    (< T 2359)
    (== (: 740) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【太郎】僕の勝ちだよ・・・" 0 "君。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21.pd8")
    (proc 24)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n21an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n21.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】今のは・・・幻影だろう。")
    (wait)
    (set-reg: 740 1)))
  ((== (: 202) 1)
   (<> (text #:color 7 "【" 0 "】映画館の前だ・・・あいかわらずカップルだらけだぜ。") (wait))))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "他の場所に行く") (text "中に入る") (text "やめる")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・他の場所に行こうぜ。")
         (wait)
         (set-var N 22)
         (set-reg: 202 1)
         (slot 1 3)
         (mes-jump "town1.mes")))
       ((&& (== N 2) (== (: 202) 0))
        (<>
         (text #:color 7 "【" 0 "】一人で映画を観るなんて・・・うっうっうっ。")
         (wait)
         (text
          #:color
          7
          "【"
          0
          "】どうせ一人で観るんだったら、いやらしい映画を観るさ・・・アニメ映画や恋愛映画なんて御免だよ。")
         (wait)))
       ((&& (== N 2) (== (: 202) 1))
        (<>
         (text #:color 7 "【" 0 "】一人で映画を見たくない・・・どうせだったら、かわいい女の子と一緒に見たいな。")
         (wait)))
       ((== N 3) (<> (text #:color 7 "【" 0 "】え？・・・映画館の前にまだいるのか！？") (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 1) (== (: 202) 0))
     (<> (text #:color 7 "【" 0 "】ここは『思ひ出どろどろ』のチケット売場だ。") (wait)))
    ((&& (== V 1) (== N 1) (== (: 202) 1))
     (<> (text #:color 7 "【" 0 "】『思ひ出どろどろ』のチケット売場だな・・・しかし、すごいタイトルだな。") (wait)))
    ((&& (== V 1) (== N 2) (== (: 202) 0))
     (<> (text #:color 7 "【" 0 "】ここは『愛と肉棒の旅立ち』のチケット売場だ。") (wait)))
    ((&& (== V 1) (== N 2) (== (: 202) 1) (== (: 10) 0))
     (<> (text #:color 7 "【" 0 "】『愛と肉棒の旅立ち』のチケット売場か・・・いやらしい映画じゃないぜ。") (wait)))
    ((&& (== V 1) (== N 2) (== (: 202) 1) (== (: 10) 1))
     (<>
      (text #:color 7 "【" 0 "】『愛と肉棒の旅立ち』のチケット売場だぜ・・・愛と涙の恋愛映画だ。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】恋愛なんてといものはだな、映画を見て感動するものじゃないのさ・・・実際に経験して感動するものなんだ。")))
    ((&& (== V 1) (== N 3) (== (: 202) 0))
     (<> (text #:color 7 "【" 0 "】『下の毛半次郎』のチケット売場だな・・・。") (wait)))
    ((&& (== V 1) (== N 3) (== (: 202) 1) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】『下の毛半次郎』のチケット映画だな・・・今はやりの、タレント監督映画だ。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 1) (== N 3) (== (: 202) 1) (== (: 11) 1))
     (<>
      (text #:color 7 "【" 0 "】『下の毛半次郎』のチケット売場だ・・・女の子が一番喜びそうにない映画だな。")
      (wait)))
    ((&& (== V 1) (== N 4) (== (: 202) 0))
     (<>
      (text #:color 7 "【" 0 "】チケット売場だぜ・・・ガラスが光っていて、中に誰がいるのかわからないが。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】きっとおばさんに違いない。")
      (wait)))
    ((&& (== V 1) (== N 4) (== (: 202) 1) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】ここでチケットを買うんだ・・・もっとも、俺は買う気がないけどね。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 4) (== (: 202) 1) (== (: 12) 1))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】チケットを買う場所だな・・・もっとも、俺には『一人で映画を見てはいけない』というポリシーがあるんだ。")
      (wait)))
    ((&& (== V 1) (== N 5) (== (: 202) 0))
     (<> (text #:color 7 "【" 0 "】チケット売場のブースだな・・・。") (wait)))
    ((&& (== V 1) (== N 5) (== (: 202) 1) (== (: 13) 0))
     (<>
      (text #:color 7 "【" 0 "】チケット売場のブースだ・・・別にめずらしい物じゃないぜ。")
      (wait)
      (set-reg: 13 1)))
    ((&& (== V 1) (== N 5) (== (: 202) 1) (== (: 13) 1))
     (<> (text #:color 7 "【" 0 "】だからチケット売場のブースだよ・・・そんなに興味があるのか？") (wait)))
    ((&& (== V 1) (== N 6) (== (: 202) 0))
     (<> (text #:color 7 "【" 0 "】次回予告と書いてあるが・・・何も書いてないじゃないか。") (wait)))
    ((&& (== V 1) (== N 6) (== (: 202) 1) (== (: 14) 0))
     (<>
      (text #:color 7 "【" 0 "】次回予告と書いてある黒板には何も書いてない・・・怠慢以外の何物でもないな。")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 1) (== N 6) (== (: 202) 1) (== (: 14) 1))
     (<> (text #:color 7 "【" 0 "】何度見ても、書いてなのものは書いてないんだ。") (wait)))
    ((&& (== V 1) (== N 7) (== (: 202) 0))
     (<> (text #:color 7 "【" 0 "】正面の壁には、ポスターが飾ってある・・・次の映画の予告かな？") (wait)))
    ((&& (== V 1) (== N 7) (== (: 202) 1) (== (: 15) 0))
     (<>
      (text #:color 7 "【" 0 "】ポスターの写真を見ると・・・潜水艦の映画かな？")
      (wait)
      (text #:color 7 "【" 0 "】タイトルは『宇宙潜艦ヤマト』となっているぞ。")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 1) (== N 7) (== (: 202) 1) (== (: 15) 1))
     (<>
      (text #:color 7 "【" 0 "】ポスターには『宇宙潜艦ヤマト』と書かれている・・・公開は９月みたいだな。")
      (wait)))
    ((&& (== V 1) (== N 8) (== (: 202) 0))
     (<> (text #:color 7 "【" 0 "】パネルが柱に飾ってあるが・・・中には何も入ってないじゃないか。") (wait)))
    ((&& (== V 1) (== N 8) (== (: 202) 1) (== (: 16) 0))
     (<>
      (text #:color 7 "【" 0 "】パネルが柱に飾ってあるな・・・。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】この柱をこすると、中からミッキーマウスの『うす』が出てくるんだぜ・・・この言葉の意味がわかった人は、３０歳以上だな。")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 1) (== N 8) (== (: 202) 1) (== (: 16) 1))
     (<> (text #:color 7 "【" 0 "】パネルだよ・・・中には何も入ってない。") (wait)))
    ((&& (== V 1) (== N 9) (== (: 202) 0))
     (<>
      (text #:color 7 "【" 0 "】四角い柱だ・・・横のワレメが入ってる。")
      (wait)
      (text #:color 7 "【" 0 "】ん？・・・言い方がいやらしかったか？")
      (wait)))
    ((&& (== V 1) (== N 9) (== (: 202) 1) (== (: 17) 0))
     (<> (text #:color 7 "【" 0 "】四角い柱だな・・・。") (wait)))
    ((&& (== V 1) (== N 10) (== (: 202) 0))
     (<>
      (text #:color 7 "【" 0 "】映画館の入口だ・・・『チケットを持っているかチェックするおねーさん』がいる。")
      (wait)))
    ((&& (== V 1) (== N 10) (== (: 202) 1) (== (: 18) 0))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】映画館の入口だな・・・この中に入ると暗くて、男女が入り乱れてて、空気が妙になま暖かい場所に行けるんだ。")
      (wait)
      (text #:color 2 "【おねーさん】いやらしい言い方をしないでください。")
      (wait)
      (text #:color 7 "【" 0 "】あ・・・聞こえた？")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 1) (== N 10) (== (: 202) 1) (== (: 18) 1))
     (<> (text #:color 7 "【" 0 "】はっはっはっ、とにかく映画館の入口だな。") (wait)))
    ((&& (== V 1) (== N 11) (== (: 202) 0))
     (<>
      (text #:color 7 "【" 0 "】映画館だぜ・・・１階から３階までが、全て映画館という世界一の建物だ。")
      (wait)
      (text #:color 7 "【" 0 "】ちょっと言いすぎだと思ったのは、俺だけじゃないだろう。")
      (wait)))
    ((&& (== V 1) (== N 11) (== (: 202) 1) (== (: 19) 0))
     (<>
      (text #:color 7 "【" 0 "】東洋一の近代的な映画館だぜ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ちょっと言いすぎだな・・・まあいいか、誰も聞いてる訳じゃないし。")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 1) (== N 11) (== (: 202) 1) (== (: 19) 1))
     (<>
      (text #:color 7 "【" 0 "】い、いかん・・・映画館を見ていると、反射的にパンツを脱ぎたくなってくるんだ。")
      (wait)))
    ((&& (== V 1) (== N 20) (== (: 202) 0))
     (<> (text #:color 7 "【" 0 "】かわいい子だな・・・処女の匂いがするぞ。") (wait)))
    ((&& (== V 1) (== N 20) (== (: 202) 1) (== (: 20) 0))
     (<>
      (text #:color 7 "【" 0 "】胸は小さいが、なかなかかわいいな・・・この女の子だったらやってもいいぜ。")
      (wait)
      (set-reg: 20 1)))
    ((&& (== V 1) (== N 20) (== (: 202) 1) (== (: 20) 1))
     (<>
      (text #:color 7 "【" 0 "】いくつくらいかな？・・・５歳か６歳ぐらいか？")
      (wait)
      (text #:color 7 "【" 0 "】冗談だよ・・・たぶん４０歳ぐらいだろう。")
      (wait)
      (text #:color 7 "【" 0 "】冗談だよ。")
      (wait)))
    ((&& (== V 1) (== N 21) (== (: 202) 0))
     (<>
      (text #:color 7 "【" 0 "】この男が邪魔だな・・・ああ、俺以外の男どもが死ねば、世の中の女は全て俺のものだあ！！")
      (wait)
      (text #:color 7 "【" 0 "】でもそんな事になったら・・・俺も女達に犯され続けて、３日ぐらいで衰弱死してしまいそうだ。")
      (wait)))
    ((&& (== V 1) (== N 21) (== (: 202) 1) (== (: 21) 0))
     (<>
      (text #:color 7 "【" 0 "】この男が邪魔だな・・・消えてなくなれ、しっしっしっ！！")
      (wait)
      (set-reg: 21 1)))
    ((&& (== V 1) (== N 21) (== (: 202) 1) (== (: 21) 1))
     (<>
      (text #:color 7 "【" 0 "】死ね・・・死ね・・・死んでしまえっ！！")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】死なないなあ・・・ははは。")
      (wait)))
    ((&& (== V 1) (== N 22) (== (: 202) 0))
     (<> (text #:color 7 "【" 0 "】ちっ、卑怯者め・・・俺に後ろ姿を向けるとは、情けないやつだぜ。") (wait)))
    ((&& (== V 1) (== N 22) (== (: 202) 1) (== (: 22) 0))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】隣にいる女性がかわいい女の子だったら、お前は世界一邪魔なやつだ・・・もしかわいくなかったら、お前は世界一偉い男だ、尊敬しちゃうぞ。")
      (wait)
      (set-reg: 22 1)))
    ((&& (== V 1) (== N 22) (== (: 202) 1) (== (: 22) 1))
     (<> (text #:color 7 "【" 0 "】ちょっと猫背だぜ・・・ニャアって言ってみな。") (wait)))
    ((&& (== V 1) (== N 23) (== (: 202) 0))
     (<>
      (text #:color 7 "【" 0 "】髪の毛が長い女性だ・・・後ろ姿だけ見ていると、かわいい予感がするんだが・・・？？？")
      (wait)
      (text #:color 7 "【" 0 "】何度か痛い目に遭ってるからな・・・振り向いたら、いきなり『動物園』ってやつだぜ、ははは。")
      (wait)))
    ((&& (== V 1) (== N 23) (== (: 202) 1) (== (: 23) 0))
     (<>
      (text #:color 7 "【" 0 "】この女の子はセーラー服を着てるのか？・・・と言う事は、横にいるおっさんは何者なんだ！？")
      (wait)
      (text #:color 7 "【" 0 "】『お父さんです』なんて言ったら、殴っちゃうぞ。")
      (wait)))
    ((&& (== V 1) (== N 24) (== (: 202) 0))
     (<> (text #:color 7 "【" 0 "】やだやだ、若いにーちゃんが一人で映画館に来てるぜ・・・寂しいやつだ。") (wait)))
    ((&& (== V 1) (== N 24) (== (: 202) 1) (== (: 24) 0))
     (<> (text #:color 7 "【" 0 "】そんな所で立ち止まってないで、とっとと中に入れよ・・・。") (wait)))
    ((&& (== V 1) (== N 25) (== (: 202) 0))
     (<>
      (text #:color 7 "【" 0 "】中に入る為には、このおねーさんにチケットを見せなければならない。")
      (wait)
      (text #:color 7 "【" 0 "】つまり・・・この映画館の中では一番偉い人だな、うん。")
      (wait)))
    ((&& (== V 1) (== N 25) (== (: 202) 1) (== (: 25) 0))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】中に入る為には、このおねーさんにチケットを見せるんだ・・・ポコチンを見せても、中には入れてくれない。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】中には入れてくれないかもしれないが、中に入れさせてくれるかもしれないな・・・うーん、どっちがいい？")
      (wait)
      (set-reg: 25 1)))
    ((&& (== V 1) (== N 25) (== (: 202) 1) (== (: 25) 1))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】バカな事ばかり言ってないで、と思っている人もいるだろうが・・・俺みたいな人間が将来は偉い人になるに決ってる。")
      (wait)
      (text #:color 7 "【" 0 "】おねーさんとは、何も関係ない事を考えてしまった。")
      (wait)))
    ((&& (== V 2) (== N 12) (== (: 202) 0))
     (<>
      (text #:color 7 "【" 0 "】ねえねえねえ、俺とデートでもしません？")
      (wait)
      (text #:color 2 "【女の人】ねえ、何の映画を観るの？")
      (wait)
      (text #:color 7 "【" 0 "】映画？・・・映画を観たい訳だ、なるほどね。")
      (wait)
      (text #:color 1 "【男の人】そうだな・・・『思ひ出どろどろ』なんてどうだい？")
      (wait)
      (text #:color 2 "【女の人】そうね、そうしましょうか。")
      (wait)
      (text #:color 7 "【" 0 "】・・・この寂しさは、いったい何なんだろう？")
      (wait)))
    ((&& (== V 2) (== N 12) (== (: 202) 1) (== (: 26) 0))
     (<>
      (text #:color 7 "【" 0 "】ねえねえねえ、俺とセックスでもしない？")
      (wait)
      (text #:color 2 "【女の人】映画を観て、食事をして・・・そのあとはどうするの？")
      (wait)
      (text #:color 7 "【" 0 "】そりゃあ、ひっひっひっ。")
      (wait)
      (text #:color 1 "【男の人】よかったら・・・僕の部屋に来ないか？")
      (wait)
      (text #:color 2 "【女の人】・・・うん。")
      (wait)
      (text #:color 7 "【" 0 "】何が『僕』だよ・・・お前の事を『冬彦』って読んでやる。")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 12) (== (: 202) 1) (== (: 26) 1))
     (<>
      (text #:color 2 "【女の人】あなた、うるさいわよ・・・邪魔しないで。")
      (wait)
      (text #:color 7 "【" 0 "】ほら、邪魔だってよ・・・あっちへ行け。")
      (wait)
      (text #:color 2 "【女の人】あなたの事を言ってるの！！")
      (wait)
      (text #:color 7 "【" 0 "】だから、お前の事だよ・・・しっしっしっ！！")
      (wait)
      (text #:color 2 "【女の人】ねえ、早く映画館の中に入りましょうよ。")
      (wait)
      (text #:color 1 "【男の人】そうだな・・・そうするか。")
      (wait)))
    ((&& (== V 2) (== N 13) (== (: 202) 0))
     (<>
      (text #:color 7 "【" 0 "】消えろ。")
      (wait)
      (text #:color 1 "【男の人】お前こそ、消えろ。")
      (wait)
      (text #:color 7 "【" 0 "】赤いネクタイしめているくせに、ナマイキだぞ。")
      (wait)
      (text #:color 1 "【男の人】大きなお世話だよ・・・あっちへ行ってろ。")
      (wait)
      (text #:color 2 "【女の人】そうよ、あっちへ行ってなさい。")
      (wait)
      (text #:color 7 "【" 0 "】ちくしょう、２対１じゃかなわないな。")
      (wait)))
    ((&& (== V 2) (== N 13) (== (: 202) 1) (== (: 27) 0))
     (<>
      (text #:color 7 "【" 0 "】ばか。")
      (wait)
      (text #:color 1 "【男の人】な、なんだよ・・・いきなり。")
      (wait)
      (text #:color 7 "【" 0 "】ばか。")
      (wait)
      (text #:color 1 "【男の人】変なやつだなあ・・・きっと気が狂ってるに違いない。")
      (wait)
      (text #:color 2 "【女の人】早く映画館の中に入りましょ？")
      (wait)
      (text #:color 1 "【男の人】そうだな、そうするか・・・。")
      (wait)
      (set-reg: 27 1)))
    ((&& (== V 2) (== N 13) (== (: 202) 1) (== (: 27) 1))
     (<>
      (text #:color 7 "【" 0 "】ポコチンが小さそうな男だな・・・。")
      (wait)
      (text #:color 1 "【男の人】お前なあ・・・いったい何を考えてるんだ！？")
      (wait)
      (text #:color 7 "【" 0 "】ほーら、小さいからムキになる。")
      (wait)
      (text #:color 2 "【女の人】大きいわよ、こーんなくらい。")
      (wait)
      (text #:color 7 "【" 0 "】あ・・・そう。")
      (wait)))
    ((&& (== V 2) (== N 14) (== (: 202) 0))
     (<>
      (text #:color 1 "【男の人】ああ・・・腰が痛い。")
      (wait)
      (text #:color 2 "【女の人】パパあ・・・昨日、がんばり過ぎたんじゃない？")
      (wait)
      (text #:color 7 "【" 0 "】パパはパパでも、本当のパパじゃないパパだな。")
      (wait)
      (animate 0 8 0)
      (animate 4 8)))
    ((&& (== V 2) (== N 14) (== (: 202) 1) (== (: 28) 0))
     (<>
      (text #:color 7 "【" 0 "】おっさん、背中がニャアニャア言ってるぜ。")
      (wait)
      (text #:color 1 "【男の人】ああ・・・腰が痛い・・・やはり『ブリッジをして、その上に女の子を乗せてクルクル回した』せいだ。")
      (wait)
      (text #:color 7 "【" 0 "】お前は雑技団か・・・まったく。")
      (wait)
      (animate 0 8 0)
      (animate 4 8)
      (set-reg: 28 1)))
    ((&& (== V 2) (== N 14) (== (: 202) 1) (== (: 28) 1))
     (<>
      (text #:color 7 "【" 0 "】おっさん、横にいる女性をくれ。")
      (wait)
      (text #:color 1 "【男の人】いいぜ、股間に１ミリのカニを、たくさん飼っているけどいいか？")
      (wait)
      (text #:color 7 "【" 0 "】・・・いらない。")
      (wait)))
    ((&& (== V 2) (== N 15) (== (: 202) 0))
     (<>
      (text #:color 2 "【女の人】かゆいわ・・・ああ、かゆい。")
      (wait)
      (text #:color 7 "【" 0 "】な、なんだよ・・・この女は。")
      (wait)))
    ((&& (== V 2) (== N 15) (== (: 202) 1) (== (: 29) 0))
     (<>
      (text #:color 7 "【" 0 "】おねーさん・・・それとも、お嬢さんかな？")
      (wait)
      (text #:color 2 "【女の人】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】まさか・・・おばさんじゃないだろうな！？")
      (wait)
      (text #:color 2 "【女の人】うるさいわね・・・かゆいんだから、横でゴチャゴチャ言わないでよ。")
      (wait)
      (text #:color 7 "【" 0 "】うーん、どこがどうかゆいんだろう？")
      (wait)
      (set-reg: 29 1)))
    ((&& (== V 2) (== N 15) (== (: 202) 1) (== (: 29) 1))
     (<>
      (text #:color 7 "【" 0 "】ねえねえ、もし君がかわいいんだったら・・・俺しデートをしないか？")
      (wait)
      (text #:color 2 "【女の人】かわいくなかったら？")
      (wait)
      (text #:color 7 "【" 0 "】この場で自殺してくれない？")
      (wait)))
    ((&& (== V 2) (== N 16) (== (: 202) 0))
     (<>
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 1 "【にーちゃん】ねえ、一人で映画を観るのも寂しいし・・・俺と一緒に映画を観ないか？")
      (wait)
      (text #:color 2 "【おねーさん】困ります・・・仕事中ですから。")
      (wait)
      (text #:color 7 "【" 0 "】ははは・・・うまくいく可能性が、異常に低いナンパをしているな。")
      (wait)))
    ((&& (== V 2) (== N 16) (== (: 202) 1) (== (: 30) 0))
     (<>
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 7 "【" 0 "】にーちゃん、一人で映画を観るくらいなら・・・俺と一緒に観ようか？")
      (wait)
      (text #:color 1 "【にーちゃん】・・・。")
      (wait)
      (text #:color 2 "【おねーさん】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】じ、冗談だよう・・・そんな目で俺を見るな。")
      (wait)
      (set-reg: 30 1)))
    ((&& (== V 2) (== N 16) (== (: 202) 1) (== (: 30) 1))
     (<>
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 1 "【にーちゃん】なあ・・・いいだろ？")
      (wait)
      (text #:color 2 "【おねーさん】でも・・・。")
      (wait)
      (text #:color 1 "【にーちゃん】いいじゃないか・・・仕事なんか、いつでもできるさ。")
      (wait)
      (text #:color 2 "【おねーさん】だって・・・。")
      (wait)
      (text #:color 1 "【にーちゃん】仕事はいつでもできるが・・・俺と一緒映画を観れるのは今だけだぜ。")
      (wait)
      (text #:color 2 "【おねーさん】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】あいつ・・・なかなかやるな。")
      (wait)))
    ((&& (== V 2) (== N 17) (== (: 202) 0))
     (<>
      (text #:color 7 "【" 0 "】入るぞ。")
      (wait)
      (text #:color 2 "【おねーさん】は！？")
      (wait)
      (text #:color 7 "【" 0 "】入るぞ・・・きみの身体の中に。")
      (wait)
      (text #:color 2 "【おねーさん】変態。")
      (wait)
      (text #:color 7 "【" 0 "】ありがとう。")
      (wait)))
    ((&& (== V 2) (== N 17) (== (: 202) 1) (== (: 31) 0))
     (<>
      (text #:color 7 "【" 0 "】おねーさん、立ちっぱなしだと足が疲れるでしょう？")
      (wait)
      (text #:color 2 "【おねーさん】いらっしゃいませ・・・チケットはお持ちですか？")
      (wait)
      (text #:color 7 "【" 0 "】俺もよく立ちっぱなしになるんだよ・・・特に朝が多いけど。")
      (wait)
      (text #:color 2 "【おねーさん】チケットは左のブースで売ってます・・・お買い求めになってからこちらにおいでくだい。")
      (wait)
      (text #:color 7 "【" 0 "】聞いちゃいない。")
      (wait)
      (set-reg: 31 1)))
    ((&& (== V 2) (== N 17) (== (: 202) 1) (== (: 31) 1))
     (<>
      (text #:color 7 "【" 0 "】ねえねえ、俺と一緒に映画を観ない？")
      (wait)
      (text #:color 1 "【にーちゃん】俺と一緒に観るんだよね？")
      (wait)
      (text #:color 2 "【おねーさん】どっちとも観ません・・・仕事中ですから。")
      (wait)
      (text #:color 7 "【" 0 "】ほーら、お前が悪いんだぞ・・・あっちへ行け。")
      (wait)
      (text #:color 1 "【にーちゃん】後から来て何を言ってるんだよ・・・お前こそあっちへ行け。")
      (wait)
      (text #:color 7 "【" 0 "】よーし、もう一度アタックしてみるか・・・。")
      (wait)))
    ((&& (== V 9) (== N 18) (== (: 202) 0))
     (<>
      (text #:color 2 "【女の人】きゃーーーーーーっ！！")
      (wait)
      (text #:color 7 "【" 0 "】ほほう、見た目よりはあるな・・・。")
      (wait)
      (text #:color 1 "【男の人】ど、どうしたんだい！？")
      (wait)))
    ((&& (== V 9) (== N 18) (== (: 202) 1) (== (: 32) 0))
     (<>
      (text #:color 2 "【女の人】きゃーーーーーっ！！")
      (wait)
      (text #:color 7 "【" 0 "】うーん、『ぶらじゃあ』はちゃんとしてるようだな・・・。")
      (wait)
      (text #:color 1 "【男の人】ど、どうしたんだい！？")
      (wait)
      (text #:color 2 "【女の人】あの子が・・・私の胸を・・・。")
      (wait)
      (text #:color 1 "【男の人】こらっ！！どこの子だ、ん！？")
      (wait)
      (text #:color 7 "【" 0 "】ここにいるよ。")
      (wait)
      (text #:color 1 "【男の人】だからどこだと聞いているんだ、ん？")
      (wait)
      (text #:color 7 "【" 0 "】あいつ・・・ケンカが弱いな。")
      (wait)
      (set-reg: 32 1)))
    ((&& (== V 9) (== N 18) (== (: 202) 1) (== (: 32) 1))
     (<>
      (text #:color 7 "【" 0 "】７８センチ・・・だろ？")
      (wait)
      (text #:color 2 "【女の人】きゃあ、きゃあ、きゃあっ！！")
      (wait)
      (text #:color 1 "【男の人】ど、どこにいるんだっ！！・・・僕の大事な彼女に、何をするうっ！！")
      (wait)
      (text #:color 7 "【" 0 "】だから・・・ここにいるってば。")
      (wait)))
    ((&& (== V 8) (== N 19) (== (: 202) 0))
     (<>
      (text #:color 7 "【" 0 "】うーん、胸は小さいが・・・お尻は大きい。")
      (wait)
      (text #:color 2 "【女の人】ねえ・・・今、私のお尻を触った？")
      (wait)
      (text #:color 1 "【男の人】え！？・・・お、俺はそんな事をしてないぜ。")
      (wait)))
    ((&& (== V 8) (== N 19) (== (: 202) 1) (== (: 33) 0))
     (<>
      (text #:color 2 "【女の人】きゃっ！！・・・ちょっと、お尻を触らないでよっ！！")
      (wait)
      (text #:color 1 "【男の人】俺は・・・触ってないぞ。")
      (wait)
      (text #:color 2 "【女の人】あの子よ、あそこにいる男の子！！")
      (wait)
      (text #:color 1 "【男の人】あの子か？")
      (wait)
      (text #:color 2 "【女の人】ううん。")
      (wait)
      (text #:color 1 "【男の人】じゃあ・・・あの子？")
      (wait)
      (text #:color 2 "【女の人】あなた・・・反対側向いているわよ。")
      (wait)
      (set-reg: 33 1)))
    ((&& (== V 8) (== N 19) (== (: 202) 1) (== (: 33) 1))
     (<>
      (text #:color 7 "【" 0 "】ほほう、いい尻してるじゃないかよ・・・。")
      (wait)
      (text #:color 2 "【女の人】い、いいかげんに・・・しなさいっ！！")
      (wait)
      (text #:color 1 "【男の人】そうだ、いいかげんにしろっ！！")
      (wait)
      (text #:color 2 "【女の人】ねえ・・・ちゃんと正面向いて言ったら？")
      (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))