(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\い
  #\【
  #\】
  #\。
  #\子
  #\の
  #\真
  #\な
  #\、
  #\は
  #\る
  #\う
  #\て
  #\っ
  #\を
  #\た
  #\し
  #\が
  #\ら
  #\と
  #\か
  #\で
  #\に
  #\く
  #\君
  #\生
  #\ん
  #\も
  #\先
  #\れ
  #\？
  #\ま
  #\だ
  #\よ
  #\こ
  #\見
  #\す
  #\！
  #\（
  #\）
  #\じ
  #\あ
  #\き
  #\ど
  #\そ
  #\俺
  #\さ
  #\痛
  #\わ
  #\つ
  #\け
  #\事
  #\ゃ
  #\り
  #\ス
  #\白
  #\胸
  #\ー
  #\下
  #\ね
  #\め
  #\ち
  #\目
  #\や
  #\大
  #\カ
  #\手
  #\分
  #\ト
  #\え
  #\一
  #\ご
  #\げ
  #\上
  #\ン
  #\ツ
  #\感
  #\夢
  #\衣
  #\間
  #\キ)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 9 (&& (~ @ 9) 65534))
 (set-arr~ @ 6 1)
 (image "g05.pd8")
 (set-arr~ @ 9 (// (~ @ 9) 1))
 (proc 24)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "g05an.pd8")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 0)
 (load "g05.s4" (~ @ 2))
 (animate 0 0 0)
 (animate 1 0)
 (set-arr~ @ 7 0)
 (animate 0 8 1)
 (animate 4 8)
 (set-arr~ @ 7 0)
 (load "g05.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (if (== (: 604) 0)
   (<>
    (text #:color 7 "【" 0 "】（うーん・・・またまた下半身だけがスカスカする。）")
    (wait)
    (text #:color 3 "【真子】" 0 "君、動かないで・・・揺れるでしょう？")
    (wait)
    (text #:color 7 "【" 0 "】（こんな姿、他の生徒に見られたら・・・とんでもない事になるぜ。）")
    (wait)
    (text #:color 3 "【真子】どこも悪くなさそうだけど・・・痛いのよねえ。")
    (wait)
    (set-reg: 604 1)))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<> (text "笑う")))
      (cond
       ((&& (== N 1) (== (: 10) 0))
        (<>
         (text #:color 7 "【" 0 "】わっはっはっはっ！！")
         (wait)
         (text #:color 3 "【真子】" 0 "君、くすぐったいの？")
         (wait)
         (set-reg: 10 1)))
       ((&& (== N 1) (== (: 10) 1))
        (<>
         (text #:color 7 "【" 0 "】はっはっはっはっ！！")
         (wait)
         (text #:color 3 "【真子】じっとしてて・・・揺れるから。")
         (wait)))
       (else (<>)))))
    ((&& (== V 2) (== N 1) (== (: 10) 0))
     (<>
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 3 "【真子】" 0 "君・・・どこも悪くないと思うけど。")
      (wait)
      (text #:color 7 "【" 0 "】うん・・・。")
      (wait)
      (text #:color 3 "【真子】先が赤く腫れてる訳じゃないし、亀頭にできものもできてないし。")
      (wait)
      (text #:color 7 "【" 0 "】（おいおい。）")
      (wait)
      (set-reg: 10 1)))
    ((&& (== V 2) (== N 1) (== (: 11) 0))
     (<>
      (text #:color 3 "【真子】" 0 "君、内臓疾患じゃないのかしら・・・前立線が悪くなると、同じような症状が起こる事があるのよ。")
      (wait)
      (text #:color 7 "【" 0 "】ははは・・・わからない。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 2) (== N 1) (== (: 12) 0))
     (<>
      (text #:color 3 "【真子】痛みが続くのなら、もう一度お医者さんに行った方がいいわよ。")
      (wait)
      (text #:color 7 "【" 0 "】ははは・・・は。")
      (wait)
      (text #:color 3 "【真子】・・・。")
      (wait)
      (text #:color 3 "【真子】" 0 "君、本当に痛いの？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "痛い") (text "痛くない")))
      (cond
       ((== N 1)
        (<> (text #:color 7 "【" 0 "】痛いなあ・・・とっても。") (wait) (set-reg: 13 1)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】実は・・・もう痛くない。")
         (wait)
         (text #:color 3 "【真子】・・・。")
         (wait)
         (text #:color 3 "【真子】" 0 "君っ！！")
         (wait)
         (set-reg: 108 (- (: 108) 1))))
       (else (<>)))
      (set-reg: 12 1)))
    ((&& (== V 2) (== N 1) (== (: 13) 1) (== (: 14) 0))
     (<>
      (text #:color 3 "【真子】" 0 "君・・・もう一度聞くけど、本当に痛いの？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "痛い") (text "痛くない")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】痛いなあ・・・本当に痛い。")
         (wait)
         (text #:color 3 "【真子】うーん、なんか変ねえ・・・。")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】実は・・・もう痛くない。")
         (wait)
         (text #:color 3 "【真子】・・・。")
         (wait)
         (text #:color 3 "【真子】" 0 "君っ！！")
         (wait)
         (set-reg: 108 (- (: 108) 1))
         (set-reg: 14 1)))
       (else (<>)))))
    ((&& (== V 2) (== N 1) (== (: 15) 0))
     (<>
      (text #:color 3 "【真子】こんなにマジマジと見て・・・先生が馬鹿みたいじゃない。")
      (wait)
      (text #:color 7 "【" 0 "】・・・ごめん。")
      (wait)
      (text #:color 3 "【真子】まあ、思春期の男の子だから・・・許してあげるけど、もうこんな事をしちゃ駄目よ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 3 "【真子】さあ・・・下着を早く上げなさい、もう見せる必要はないでしょ？")
      (wait)
      (text #:color 7 "【" 0 "】（真子先生、怒ったのかな・・・うーん。）")
      (wait)
      (text #:color 3 "【真子】いつまで出してするつもり？")
      (wait)
      (text #:color 7 "【" 0 "】へいへい・・・パンツを上げて、と。")
      (wait)
      (text #:color 7 "【" 0 "】・・・！？")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "g06.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】（あらら・・・これで二度目だな。）")
      (wait)
      (text #:color 3 "【真子】" 0 "君、腰をかがめたまま・・・固まっちゃってるわよ。")
      (wait)
      (text #:color 7 "【" 0 "】（・・・。）")
      (wait)
      (text #:color 7 "【" 0 "】（・・・。）")
      (wait)
      (text #:color 7 "【" 0 "】（あ・・・ま、まずい！？）")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "g05.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "g05an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "g05.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 3 "【真子】や、やだわ・・・" 0 "君。")
      (wait)
      (text #:color 7 "【" 0 "】ははは・・・ごめんなさい。")
      (wait)
      (text #:color 3 "【真子】もう・・・どうして大きくなっちゃうのよ。")
      (wait)
      (text #:color 7 "【" 0 "】真子先生の下着が見えた。")
      (wait)
      (text #:color 3 "【真子】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】あれれ・・・真子先生？")
      (wait)
      (text #:color 3 "【真子】" 0 "君のって・・・大きいわよ。")
      (wait)
      (text #:color 7 "【" 0 "】（な、なんか・・・真子先生の目の色が違うような！？）")
      (wait)
      (text #:color 3 "【真子】す、すごい・・・こんなの初めて見たわ。")
      (wait)
      (text #:color 7 "【" 0 "】ち、ちょっと・・・触られると、ますます大きくなるよっ！！")
      (wait)
      (text #:color 3 "【真子】ま、まだ大きくなるの！？")
      (wait)
      (text #:color 3 "【真子】・・・。")
      (wait)
      (text #:color 3 "【真子】" 0 "君・・・目をつぶってじっとしてなさい、これは命令です。")
      (wait)
      (set-reg: 108 (+ (: 108) 1))
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kuro.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (text #:color 7 "俺は真子先生の言う通り目をつぶる・・・。")
      (wait)
      (text #:color 7 "・・・。")
      (wait)
      (text #:color 7 "・・・。")
      (wait)
      (text #:color 7 "うひゃひゃ！？・・・な、なんだ、この生暖かい感触は！？")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "g09.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "g09an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "g09.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (sound 1)
      (set-var I 44)
      (proc 26)
      (set-reg: 836 0)
      (text #:color 7 "驚いた事に、真子先生の知的な口が俺のものを含んでいる・・・！？")
      (wait)
      (text #:color 3 "【真子】" 0 "君、目を開けないでね・・・" 0 "君は今、夢を見てるのよ。")
      (wait)
      (text #:color 7 "真子先生は俺のイチモツをしっかり握り、根元を手でしごき、尖端は口と舌で愛撫し続ける。")
      (wait)
      (animate 0 8 0)
      (animate 4 8)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 3 "【真子】本当・・・" 0 "君、もっと大きくなってきたわ。")
      (wait)
      (text #:color 7 "これは夢だ・・・夢に違いない。")
      (wait)
      (text #:color 3 "【真子】ああ・・・すごい・・・こんなのを入れたら・・・どんな感じがするのかしら？")
      (wait)
      (text #:color 7 "そう言うと、真子先生は自分の白衣のボタンを一つ、また一つをはずしていく。")
      (wait)
      (text #:color 3 "【真子】" 0 "君・・・いつからこんなに大きくなったの？")
      (wait)
      (text #:color 7 "白衣がはだけ、真子先生の胸元があらわになる・・・その胸を見て、俺は同じ事が聞きたくなった。")
      (wait)
      (text #:color 7 "真子先生は、俺のイチモツを口で愛撫しながら、手は自分の胸をまさぐっている・・・やはりこれは夢に違いない。")
      (wait)
      (text #:color 3 "【真子】あ・・・は・・・。")
      (wait)
      (text #:color 7 "俺のイチモツと真子先生の唇の隙間から、熱い息が漏れる。")
      (wait)
      (text #:color 3 "【真子】" 0 "君・・・これは夢よ、いいわね？")
      (wait)
      (text #:color 7 "真子先生はそそり立つ物から唇を離すと、濡れた瞳でじっと俺を見上げる。その瞳の色は、いつもの真子先生ではない。")
      (wait)
      (text #:color 3 "【真子】" 0 "君・・・こっちに来なさい。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "g12.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "g11.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "g10.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "g07.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "g12an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "g12.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 3 "【真子】" 0 "君・・・見て。")
      (wait)
      (text #:color 7 "真子先生は左手で胸をまさぐり、右手であの部分をまさぐる。")
      (wait)
      (text #:color 3 "【真子】ほら、聞こえるかしら・・・いやらしい音が。")
      (wait)
      (text
       #:color
       7
       "真子先生の指は、その部分の谷間に沿うように動いている・・・そして、その部分は下着の上からでも淫らな音をたてるほど、蜜があふれ出しているようだ。")
      (wait)
      (text #:color 3 "【真子】" 0 "君・・・ほら。")
      (wait)
      (text #:color 7 "そう言うと、真子先生は自分で服を脱ぎはじめた。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "g12.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "g11.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "g10.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "g12an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "g12.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 3 "【真子】どう・・・興奮する？")
      (wait)
      (text #:color 7 "真子先生は、白衣とシルクのシャツを床に落とした・・・両手は胸の陰部に置かれたままだ。")
      (wait)
      (text #:color 3 "【真子】胸が大きいと・・・男の人の視線を感じるのよ。")
      (wait)
      (text #:color 3 "【真子】" 0 "君も、よく見てたわね・・・正直に言いなさい。")
      (wait)
      (text #:color 7 "俺は咽の奥がカラカラに渇き声を出す事ができなかった・・・首を縦に振るのがせいいっぱいだ。")
      (wait)
      (text #:color 3 "【真子】そう・・・やっぱり見てたのね。")
      (wait)
      (text #:color 3 "【真子】でも胸だけじゃないでしょう・・・私の脚も見てたわね？")
      (wait)
      (text #:color 7 "俺は前と同じようにうなづいた。")
      (wait)
      (text #:color 3 "【真子】" 0 "君はいい子だから・・・特別に私の脚を見せてあげる。")
      (wait)
      (text #:color 7 "真子先生はスカートを床まで下ろし、そしてストッキングもくるくると下ろし始めた。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "g12.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "g11.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "g12an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "g12.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 3 "【真子】" 0 "君・・・どんな感じ？")
      (wait)
      (text #:color 7 "どんな感じか、という質問の答えは俺の股間を見ればわかる・・・これ以上はないほど、血液が充満している。")
      (wait)
      (text
       #:color
       7
       "真子先生は、俺の股間を見ながらうっすらと微笑む・・・しかしその微笑みは、いつもの知的なものとは明らかに違っている。")
      (wait)
      (text #:color 3 "【真子】" 0 "君・・・見たい？")
      (wait)
      (text #:color 7 "俺の目は真子先生の胸、そして股間へと注がれ、ロクに返事をする事ができない。")
      (wait)
      (text #:color 3 "【真子】どうなの、" 0 "君・・・見たいの、見たくないの？")
      (wait)
      (text #:color 7 "俺はようやく返事をする・・・真子先生は再び微笑むと、黒い下着をするすると脱ぎ始めた。")
      (wait)
      (slot 1 4)
      (mes-jump "g12.mes")))
    ((&& (== V 1) (== N 2))
     (<> (text #:color 7 "【" 0 "】（真子先生の手だ・・・白くて長い指だな。）") (wait)))
    ((&& (== V 1) (== N 3))
     (<> (text #:color 7 "【" 0 "】（うーん、俺のナニをじっくり見ている・・・照れるぜ。）") (wait)))
    ((&& (== V 1) (== N 4))
     (<> (text #:color 7 "【" 0 "】（奇麗だな・・・キラキラしてるよ。）") (wait)))
    ((&& (== V 1) (== N 5))
     (<> (text #:color 7 "【" 0 "】（白衣が似合うな・・・やよいさんといい勝負だ。）") (wait)))
    ((&& (== V 1) (== N 6))
     (<> (text #:color 7 "【" 0 "】（スカートからは、白いストッキングをはいた脚が出ている。）") (wait)))
    ((&& (== V 1) (== N 7))
     (<>
      (text #:color 7 "【" 0 "】（白衣に白いストッキングか・・・これでナースハットをしてたら、看護婦さんだぜ。）")
      (wait)))
    ((&& (== V 1) (== N 8))
     (<> (text #:color 7 "【" 0 "】（保健室の床だ・・・ゴミ一つ落ちてないな。）") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))