(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\の
  #\。
  #\は
  #\っ
  #\！
  #\な
  #\い
  #\ゃ
  #\こ
  #\じ
  #\る
  #\日
  #\室
  #\だ
  #\て
  #\か
  #\教
  #\ま
  #\ん
  #\神
  #\声
  #\ぞ
  #\た
  #\閉
  #\ド
  #\ア
  #\よ
  #\そ
  #\ど
  #\う
  #\ら
  #\、
  #\に
  #\鍵)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-reg: 1001 0)
 (if (== (: 414) 1) (<> (set-reg: 416 1)))
 (if (== (: 782) 1) (<> (set-reg: 783 1)))
 (if (== (: 790) 1) (<> (set-reg: 791 1)))
 (if (== (: 796) 1) (<> (set-reg: 797 1)))
 (if (== (: 802) 1) (<> (set-reg: 803 1)))
 (if (== (: 813) 1) (<> (set-reg: 814 1)))
 (if (== (: 817) 1) (<> (set-reg: 818 1)))
 (if (== (: 815) 1) (<> (set-reg: 816 1)))
 (if (== (: 836) 0) (<> (sound 1) (set-var I 19) (proc 26) (set-reg: 836 1)))
 (set-arr~ @ 7 1)
 (set-var A (+ (~ Z 23) 1))
 (set-var X (~ A 0))
 (set-var Y (~ A 1))
 (set-arr~ @ 6 2)
 (set-arr~ @ 1 4096)
 (image "chip4.pd8")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 1)
 (load "gakko3.mp" 4096)
 (field 15 4096)
 (field 0)
 (load "gakko3.c5" (+ Z 40))
 (field 1)
 (if-else (== (: 147) 0) (<> (field 14 1 1)) (<> (field 14 1 0)))
 (if-else (== (: 148) 0) (<> (field 14 2 1)) (<> (field 14 2 0)))
 (set-var A (+ (~ Z 23) 1))
 (if (== N 0) (<> (field 10 0)))
 (if (== N 1) (<> (field 10 1)))
 (if (== N 2) (<> (field 10 2)))
 (if (== N 3) (<> (field 10 3)))
 (if (== N 4) (<> (field 10 4)))
 (if (== (: 1023) 1) (<> (set-reg: 1023 0)))
 (field 2)
 (field 3)
 (field 5)
 (palette 3)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (if (== H 831)
   (<>
    (sound 1)
    (set-var I 16)
    (proc 26)
    (text #:color 7 "【" 0 "】・・・ん！？")
    (wait)
    (text #:color 5 "【神の声】" 0 "よ・・・今日は８月３１日じゃぞ。")
    (wait)
    (text #:color 7 "【" 0 "】それがどうしたんだよ。")
    (wait)
    (text #:color 5 "【神の声】明日からは新学期じゃ・・・今日こそお前の審判の日じゃっ！！")
    (wait)
    (text #:color 5 "【神の声】さあ、部屋に戻り自らの手で運命を定めるのじゃ・・・行くのじゃっ、" 0 "っ！！")
    (wait)
    (text #:color 7 "【" 0 "】どひゃー！！")
    (wait)
    (set-var H 831)
    (set-var T 1200)
    (proc 11)
    (slot 1 2)
    (mes-jump "kokuha.mes")))
 (while
  (== 1 1)
  (<>
   (mouse 0)
   (field 5)
   (while
    (== 1 1)
    (<>
     (if (== (: 1001) 0)
       (<>
        (if-else (!= (: 1000) 0)
          (<> (set-reg: 1000 (- (: 1000) 1)) (field 13 0 5))
          (<> (field 13 0 0)))))
     (field 12)
     (if (!= S 65535) (<> (break)))
     (delay W)))
   (set-var V S)
   (if (> V 49) (<> (set-var V (+ V 50))))
   (mouse 1)
   (set-var A (+ (~ Z 23) 1))
   (set-var X (~ A 0))
   (set-var Y (~ A 1))
   (set-var D (/ (~b A 9) 2))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 21 (+ 512 18))
   (set-arr~ @ 13 15 322 64 391)
   (color 8)
   (text-color 7)
   (clear)
   (set-var A 10)
   (proc 12)
   (proc 11)
   (cond
    ((&& (> V 0) (> H 830))
     (<>
      (sound 1)
      (set-var I 16)
      (proc 26)
      (text #:color 7 "【" 0 "】・・・ん！？")
      (wait)
      (text #:color 5 "【神の声】" 0 "よ・・・今日は８月３１日じゃぞ。")
      (wait)
      (text #:color 7 "【" 0 "】それがどうしたんだよ。")
      (wait)
      (text #:color 5 "【神の声】明日からは新学期じゃ・・・今日こそお前の審判の日じゃっ！！")
      (wait)
      (text #:color 5 "【神の声】さあ、部屋に戻り自らの手で運命を定めるのじゃ・・・行くのじゃっ、" 0 "っ！！")
      (wait)
      (text #:color 7 "【" 0 "】どひゃー！！")
      (wait)
      (set-var H 831)
      (set-var T 1200)
      (proc 11)
      (slot 1 2)
      (mes-jump "kokuha.mes")))
    ((&& (== V 101) (< T 830))
     (<>
      (text #:color 7 "【" 0 "】教室の鍵は閉まってる・・・。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 101) (> T 1800))
     (<>
      (text #:color 7 "【" 0 "】教室の鍵は閉まってる・・・。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((== V 101)
     (<>
      (text #:color 7 "【" 0 "】ここは２年Ｃ組の教室だ・・・ここにいても、何も起こらないぞ。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 102) (< T 830))
     (<>
      (text #:color 7 "【" 0 "】教室の鍵は閉まってる・・・。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 102) (> T 1800))
     (<>
      (text #:color 7 "【" 0 "】教室の鍵は閉まってる・・・。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((== V 102)
     (<>
      (text #:color 7 "【" 0 "】ここは３年Ａ組の教室だな・・・俺の教室じゃない。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 103) (< T 830))
     (<>
      (text #:color 7 "【" 0 "】トイレのドアは閉まってる・・・まいったな。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 103) (> T 1800))
     (<>
      (text #:color 7 "【" 0 "】トイレのドアは閉まってる・・・まいったな。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((== V 103)
     (<>
      (text #:color 7 "【" 0 "】ここは男子トイレだが・・・。")
      (wait)
      (text #:color 7 "【" 0 "】したくない時に来る場所じゃないな・・・他に行こうぜ。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((== V 104)
     (<>
      (text #:color 7 "【" 0 "】鍵がかかっている・・・入る事はできないぞ。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 105) (< T 830))
     (<>
      (text #:color 7 "【" 0 "】放送室のドアも開かない・・・。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 105) (> T 1800))
     (<>
      (text #:color 7 "【" 0 "】放送室のドアも開かない・・・。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 105) (== (: 271) 1) (== (: 274) 0))
     (<> (slot 1 3) (mes-jump "housou1.mes")))
    ((&& (== V 105) (== (: 318) 1) (== (: 319) 0) (== (: 641) 0))
     (<> (slot 1 3) (mes-jump "housou2.mes")))
    ((&& (== V 105) (== (: 668) 1) (> H 825) (== (: 674) 0) (== (: 671) 0))
     (<> (slot 1 3) (mes-jump "housou4.mes")))
    ((&& (== V 105) (== (: 641) 0) (== (: 637) 0) (> H 818))
     (<> (slot 1 3) (mes-jump "housou3.mes")))
    ((== V 105) (<> (slot 1 3) (mes-jump "housou.mes")))
    ((&& (== V 106) (< T 830))
     (<>
      (text #:color 7 "【" 0 "】ドアは開かないぞ・・・。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 106) (> T 1800))
     (<>
      (text #:color 7 "【" 0 "】ドアは開かないぞ・・・ちっ！！")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 106) (== (: 807) 1) (== (: 809) 0))
     (<> (slot 1 4) (mes-jump "special.mes")))
    ((== V 106)
     (<>
      (text #:color 7 "【" 0 "】ここは３年Ｂ組の教室だぜ・・・どうしてみんないないんだ？")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】そうだよ・・・夏休みだったな。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 107) (== D 0))
     (<> (set-var N 0) (slot 1 3) (mes-jump "gakko4.mes")))
    ((&& (== V 108) (== D 0))
     (<> (set-var N 1) (slot 1 3) (mes-jump "gakko2.mes")))
    (else (<>)))
   (<>))))