(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\じ
  #\【
  #\】
  #\い
  #\っ
  #\の
  #\。
  #\る
  #\ゃ
  #\な
  #\め
  #\は
  #\ん
  #\ひ
  #\時
  #\、
  #\間
  #\進
  #\！
  #\か
  #\ぢ
  #\で
  #\う
  #\よ
  #\日
  #\だ
  #\こ
  #\て
  #\も
  #\０
  #\ど
  #\お
  #\を
  #\？
  #\が
  #\今
  #\１
  #\く
  #\わ
  #\出
  #\張
  #\そ
  #\し
  #\ら
  #\に
  #\ー
  #\室
  #\ぜ
  #\ち
  #\神
  #\声
  #\た
  #\り
  #\開
  #\ま
  #\け
  #\３
  #\き)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-reg: 1001 0)
 (if (== (: 808) 1) (<> (set-reg: 809 1)))
 (if (== (: 836) 0) (<> (sound 1) (set-var I 19) (proc 26) (set-reg: 836 1)))
 (set-arr~ @ 7 1)
 (set-var A (+ (~ Z 23) 1))
 (set-var X (~ A 0))
 (set-var Y (~ A 1))
 (set-arr~ @ 6 2)
 (set-arr~ @ 1 4096)
 (image "chip4.pd8")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 1)
 (load "gakko4.mp" 4096)
 (field 15 4096)
 (field 0)
 (load "gakko4.c5" (+ Z 40))
 (field 1)
 (if-else (== (: 147) 0) (<> (field 14 1 1)) (<> (field 14 1 0)))
 (if-else (== (: 148) 0) (<> (field 14 2 1)) (<> (field 14 2 0)))
 (set-var A (+ (~ Z 23) 1))
 (if (== N 0) (<> (field 10 0)))
 (if (== N 1) (<> (field 10 1)))
 (if (== N 2) (<> (field 10 2)))
 (if (== N 3) (<> (field 10 3)))
 (if (== N 4) (<> (field 10 4)))
 (if (== N 5) (<> (field 10 5)))
 (if (== (: 1023) 1) (<> (set-reg: 1023 0)))
 (field 2)
 (field 3)
 (field 5)
 (palette 3)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (if (== H 831)
   (<>
    (sound 1)
    (set-var I 16)
    (proc 26)
    (text #:color 7 "【" 0 "】・・・ん！？")
    (wait)
    (text #:color 5 "【神の声】" 0 "よ・・・今日は８月３１日じゃぞ。")
    (wait)
    (text #:color 7 "【" 0 "】それがどうしたんだよ。")
    (wait)
    (text #:color 5 "【神の声】明日からは新学期じゃ・・・今日こそお前の審判の日じゃっ！！")
    (wait)
    (text #:color 5 "【神の声】さあ、部屋に戻り自らの手で運命を定めるのじゃ・・・行くのじゃっ、" 0 "っ！！")
    (wait)
    (text #:color 7 "【" 0 "】どひゃー！！")
    (wait)
    (set-var H 831)
    (set-var T 1200)
    (proc 11)
    (slot 1 2)
    (mes-jump "kokuha.mes")))
 (while
  (== 1 1)
  (<>
   (mouse 0)
   (field 5)
   (while
    (== 1 1)
    (<>
     (if (== (: 1001) 0)
       (<>
        (if-else (!= (: 1000) 0)
          (<> (set-reg: 1000 (- (: 1000) 1)) (field 13 0 5))
          (<> (field 13 0 0)))))
     (field 12)
     (if (!= S 65535) (<> (break)))
     (delay W)))
   (set-var V S)
   (if (> V 49) (<> (set-var V (+ V 50))))
   (mouse 1)
   (set-var A (+ (~ Z 23) 1))
   (set-var X (~ A 0))
   (set-var Y (~ A 1))
   (set-var D (/ (~b A 9) 2))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 21 (+ 512 18))
   (set-arr~ @ 13 15 322 64 391)
   (color 8)
   (text-color 7)
   (clear)
   (set-var A 10)
   (proc 12)
   (proc 11)
   (cond
    ((&& (> V 0) (> H 830))
     (<>
      (sound 1)
      (set-var I 16)
      (proc 26)
      (text #:color 7 "【" 0 "】・・・ん！？")
      (wait)
      (text #:color 5 "【神の声】" 0 "よ・・・今日は８月３１日じゃぞ。")
      (wait)
      (text #:color 7 "【" 0 "】それがどうしたんだよ。")
      (wait)
      (text #:color 5 "【神の声】明日からは新学期じゃ・・・今日こそお前の審判の日じゃっ！！")
      (wait)
      (text #:color 5 "【神の声】さあ、部屋に戻り自らの手で運命を定めるのじゃ・・・行くのじゃっ、" 0 "っ！！")
      (wait)
      (text #:color 7 "【" 0 "】どひゃー！！")
      (wait)
      (set-var H 831)
      (set-var T 1200)
      (proc 11)
      (slot 1 2)
      (mes-jump "kokuha.mes")))
    ((&& (== V 101) (< T 830))
     (<>
      (text #:color 7 "【" 0 "】あ、開かない・・・くそっ！！")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 101) (> T 1800))
     (<>
      (text #:color 7 "【" 0 "】教室のドアの鍵まで、閉める事はないじゃないかよう。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((== V 101)
     (<>
      (text #:color 7 "【" 0 "】ここは３年Ｃ組の教室だ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】何をしてるんだ？・・・俺はこの教室に用はないぞ。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 102) (< T 830))
     (<>
      (text #:color 7 "【" 0 "】開かない・・・まいったな。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 102) (> T 1800))
     (<>
      (text #:color 7 "【" 0 "】開かないぜ・・・俺のせいじゃない。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((== V 102) (<> (slot 1 3) (mes-jump "kyoshi.mes")))
    ((&& (== V 103) (< T 830))
     (<>
      (text #:color 7 "【" 0 "】トイレのドアまで閉めるなっ！！")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 103) (> T 1800))
     (<>
      (text #:color 7 "【" 0 "】ちっ・・・開かないよ。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((== V 103)
     (<>
      (text #:color 7 "【" 0 "】ここは女子トイレだぜ・・・中に入っても誰もいないよ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・いても入らないけど。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 104) (< T 830))
     (<>
      (text #:color 7 "【" 0 "】美術室に入るつもりはないけど、鍵がかかっていると妙に入りたくなるな。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 104) (> T 1800))
     (<>
      (text #:color 7 "【" 0 "】駄目だ・・・鍵がかかってる。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 104) (== (: 801) 1) (== (: 803) 0))
     (<> (slot 1 4) (mes-jump "special.mes")))
    ((&& (== V 104) (== (: 818) 0) (> H 811))
     (<> (slot 1 4) (mes-jump "special.mes")))
    ((== V 104)
     (<>
      (text #:color 7 "【" 0 "】ここは美術室だ・・・俺は絵を描くつもりはない。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 105) (< T 830))
     (<>
      (text #:color 7 "【" 0 "】音楽室のドアも閉まってる・・・。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 105) (> T 1800))
     (<>
      (text #:color 7 "【" 0 "】開かない・・・とにかく開かないんだ。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 105) (== (: 795) 1) (== (: 797) 0))
     (<> (slot 1 4) (mes-jump "special.mes")))
    ((&& (== V 105) (== (: 816) 0) (> H 812))
     (<> (slot 1 4) (mes-jump "special.mes")))
    ((== V 105)
     (<>
      (text #:color 7 "【" 0 "】音楽室だぜ・・・はっきり言って、俺は音楽の授業が嫌いだ。")
      (wait)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 106) (== D 0) (== (: 594) 0))
     (<> (set-var N 0) (slot 1 3) (mes-jump "gakko3.mes")))
    ((&& (== V 106) (== D 0) (== (: 594) 1))
     (<> (set-var N 0) (set-reg: 595 1) (slot 1 3) (mes-jump "gakko3.mes")))
    ((&& (== V 107) (> T 1800) (< M 1000))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao26.pd8")
      (proc 15)
      (sound 1)
      (set-var I 17)
      (proc 26)
      (set-reg: 836 0)
      (text #:color 1 "【じじい】ひっひっひっ・・・おこんばんわ。")
      (wait)
      (text #:color 1 "【じじい】今日は、特別出張サービスの四次元の家ぢゃ。")
      (wait)
      (text #:color 1 "【じじい】好きなだけ時間を進めてしんぜよう・・・もちろん出張料は格安で、１０００円でどうぢゃな？")
      (wait)
      (text #:color 1 "【じじい】と、思ったら・・・お前さんは持ち合わせがないようぢゃの。")
      (wait)
      (text #:color 1 "【じじい】ひっひっひっ、かわいそうぢゃが・・・朝まで校舎の中をウロウロする事ぢゃ。")
      (wait)))
    ((&& (== V 107) (< T 830) (< M 1000))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao26.pd8")
      (proc 15)
      (sound 1)
      (set-var I 17)
      (proc 26)
      (set-reg: 836 0)
      (text #:color 1 "【じじい】ひっひっひっ・・・おこんばんわ。")
      (wait)
      (text #:color 1 "【じじい】今日は、特別出張サービスの四次元の家ぢゃ。")
      (wait)
      (text #:color 1 "【じじい】好きなだけ時間を進めてしんぜよう・・・もちろん出張料は格安で、１０００円でどうぢゃな？")
      (wait)
      (text #:color 1 "【じじい】と、思ったら・・・お前さんは持ち合わせがないようぢゃの。")
      (wait)
      (text #:color 1 "【じじい】ひっひっひっ、かわいそうぢゃが・・・朝まで校舎の中をウロウロする事ぢゃ。")
      (wait)))
    ((&& (== V 107) (> T 1800))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao26.pd8")
      (proc 15)
      (sound 1)
      (set-var I 17)
      (proc 26)
      (set-reg: 836 0)
      (text #:color 1 "【じじい】ひっひっひっ・・・おこんばんわ。")
      (wait)
      (text #:color 1 "【じじい】今日は、特別出張サービスの四次元の家ぢゃ。")
      (wait)
      (text #:color 1 "【じじい】好きなだけ時間を進めてしんぜよう・・・もちろん出張料は格安で、１０００円でどうぢゃな？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show
       (<.>
        (text "１時間進める")
        (text "２時間進める")
        (text "３時間進める")
        (text "４時間進める")
        (text "５時間進める")
        (text "６時間進める")
        (text "７時間進める")
        (text "８時間進める")
        (text "やめる")))
      (set-arr~ @ 7 1)
      (cond
       ((== N 1) (<> (set-var A 1) (proc 13) (set-var M (- M 1000)) (proc 11)))
       ((== N 2) (<> (set-var A 2) (proc 13) (set-var M (- M 1000)) (proc 11)))
       ((== N 3) (<> (set-var A 3) (proc 13) (set-var M (- M 1000)) (proc 11)))
       ((== N 4) (<> (set-var A 4) (proc 13) (set-var M (- M 1000)) (proc 11)))
       ((== N 5) (<> (set-var A 5) (proc 13) (set-var M (- M 1000)) (proc 11)))
       ((== N 6) (<> (set-var A 6) (proc 13) (set-var M (- M 1000)) (proc 11)))
       ((== N 7) (<> (set-var A 7) (proc 13) (set-var M (- M 1000)) (proc 11)))
       ((== N 8) (<> (set-var A 8) (proc 13) (set-var M (- M 1000)) (proc 11)))
       ((== N 9)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【じじい】なんぢゃ・・・やめるのか？")
         (wait)))
       (else (<>)))
      (set-arr~ @ 13 28 48 65 127)
      (color 8)
      (clear)
      (text #:color 1 "【じじい】ひっひっひっ・・・御用の時は、いつでも来ておくれ。")
      (wait)
      (sound 1)
      (set-var I 19)
      (proc 26)
      (set-reg: 836 1)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&& (== V 107) (< T 830))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao26.pd8")
      (proc 15)
      (sound 1)
      (set-var I 17)
      (proc 26)
      (set-reg: 836 0)
      (text #:color 1 "【じじい】ひっひっひっ・・・おこんばんわ。")
      (wait)
      (text #:color 1 "【じじい】今日は特別感謝デーぢゃよ・・・出張サービスの四次元の家ぢゃ。")
      (wait)
      (text #:color 1 "【じじい】好きなだけ時間を進めてしんぜよう・・・もちろん出張料は格安で、１０００円でどうぢゃな？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show
       (<.>
        (text "１時間進める")
        (text "２時間進める")
        (text "３時間進める")
        (text "４時間進める")
        (text "５時間進める")
        (text "６時間進める")
        (text "７時間進める")
        (text "８時間進める")
        (text "やめる")))
      (set-arr~ @ 7 1)
      (cond
       ((== N 1) (<> (set-var A 1) (proc 13) (set-var M (- M 1000)) (proc 11)))
       ((== N 2) (<> (set-var A 2) (proc 13) (set-var M (- M 1000)) (proc 11)))
       ((== N 3) (<> (set-var A 3) (proc 13) (set-var M (- M 1000)) (proc 11)))
       ((== N 4) (<> (set-var A 4) (proc 13) (set-var M (- M 1000)) (proc 11)))
       ((== N 5) (<> (set-var A 5) (proc 13) (set-var M (- M 1000)) (proc 11)))
       ((== N 6) (<> (set-var A 6) (proc 13) (set-var M (- M 1000)) (proc 11)))
       ((== N 7) (<> (set-var A 7) (proc 13) (set-var M (- M 1000)) (proc 11)))
       ((== N 8) (<> (set-var A 8) (proc 13) (set-var M (- M 1000)) (proc 11)))
       ((== N 9)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【じじい】なんぢゃ・・・やめるのか？")
         (wait)))
       (else (<>)))
      (set-arr~ @ 13 28 48 65 127)
      (color 8)
      (clear)
      (text #:color 1 "【じじい】ひっひっひっ・・・御用の時は、いつでも来ておくれ。")
      (wait)
      (sound 1)
      (set-var I 19)
      (proc 26)
      (set-reg: 836 1)
      (set-var A (+ (~ Z 23) 1))
      (set-var X (~ A 0))
      (set-var Y (~ A 1))
      (set-var D (/ (~b A 9) 2))
      (set-var Y (+ Y 1))
      (set-var D 1)
      (set-arr~ A 0 X)
      (set-arr~ A 1 Y)
      (set-arr~b A 9 (* D 2))
      (field 2)
      (field 3)
      (field 5)
      (delay W)))
    ((&&
      (== V 107)
      (== D 0)
      (== (: 317) 1)
      (== (: 318) 0)
      (== D 0)
      (== (: 641) 0))
     (<> (slot 1 3) (mes-jump "okujyo1.mes")))
    ((&&
      (== V 107)
      (== (: 442) 1)
      (== (: 443) 0)
      (> H 822)
      (== D 0)
      (== (: 765) 0))
     (<> (slot 1 3) (mes-jump "okujyo2.mes")))
    ((&& (== V 107) (== (: 451) 1) (== (: 452) 0) (> H 820) (== D 0))
     (<> (slot 1 3) (mes-jump "okujyo3.mes")))
    ((&&
      (== V 107)
      (== (: 462) 1)
      (== (: 594) 0)
      (> H 818)
      (== D 0)
      (== (: 690) 0))
     (<> (slot 1 4) (mes-jump "okujyo6.mes")))
    ((&&
      (== V 107)
      (== (: 462) 1)
      (== (: 594) 0)
      (> H 818)
      (== D 0)
      (== (: 690) 1)
      (== (: 694) 1))
     (<> (slot 1 4) (mes-jump "okujyo6.mes")))
    ((&&
      (== V 107)
      (== (: 462) 1)
      (== (: 594) 1)
      (> H 818)
      (== D 0)
      (== (: 595) 0))
     (<> (slot 1 4) (mes-jump "okujyo6.mes")))
    ((&&
      (== V 107)
      (== (: 483) 1)
      (== (: 484) 0)
      (> H 819)
      (== (: 514) 0)
      (== D 0))
     (<> (slot 1 3) (mes-jump "okujyo4.mes")))
    ((&& (== V 107) (== D 0) (== (: 641) 0) (> H 820) (== (: 639) 0))
     (<> (slot 1 3) (mes-jump "okujyo7.mes")))
    ((&&
      (== V 107)
      (== (: 668) 1)
      (== (: 670) 0)
      (> H 825)
      (== D 0)
      (== (: 674) 0))
     (<> (slot 1 3) (mes-jump "okujyo8.mes")))
    ((&& (== V 107) (== (: 504) 1) (== (: 505) 0) (> H 820) (== D 0))
     (<> (slot 1 3) (mes-jump "okujyo5.mes")))
    ((&& (== V 107) (== (: 789) 1) (== (: 791) 0))
     (<> (slot 1 4) (mes-jump "special.mes")))
    ((&& (== V 107) (== (: 814) 0) (> H 810))
     (<> (slot 1 4) (mes-jump "special.mes")))
    ((&& (== V 107) (== D 0)) (<> (slot 1 3) (mes-jump "okujyo.mes")))
    (else (<>)))
   (<>))))