(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\っ
  #\の
  #\【
  #\】
  #\。
  #\て
  #\い
  #\し
  #\ん
  #\だ
  #\な
  #\、
  #\た
  #\か
  #\は
  #\う
  #\に
  #\と
  #\る
  #\を
  #\彼
  #\あ
  #\ち
  #\く
  #\よ
  #\ろ
  #\が
  #\そ
  #\ら
  #\俺
  #\で
  #\女
  #\ひ
  #\み
  #\ゃ
  #\り
  #\れ
  #\も
  #\ま
  #\ー
  #\け
  #\事
  #\こ
  #\ン
  #\デ
  #\『
  #\』
  #\方
  #\ど
  #\つ
  #\わ
  #\会
  #\き
  #\前
  #\氏
  #\言
  #\さ
  #\行
  #\出
  #\誘
  #\す
  #\思
  #\今)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (sound 1)
 (set-var I 18)
 (proc 26)
 (while
  (== 1 1)
  (<>
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((&& (== N 4) (== (: 406) 0))
     (<>
      (text #:color 7 "【" 0 "】よーし、ひろみちゃんのデータを見るんだな。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "28.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "o.pd8")
      (proc 16)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "oan.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "o.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】彼女の名前は『田町　ひろみ』・・・このマンションの近所にある『藤田製作所』のＯＬだ。")
      (wait)
      (text #:color 7 "【" 0 "】しかし、彼女の方から声をかけてくるなんて・・・びっくりだよなあ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】俺の事を色々と知っているようだが、いったいどういうつもりなんだ？")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】彼氏がいるって自分で言ってたし、電話番号は教えてくれないし・・・うーん、何がなんだかさっぱりわからんぞ。")
      (wait)
      (if-else (== (: 265) 1)
        (<>
         (slot 1 8)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "30.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "o10.pd8")
         (proc 16)
         (set-arr~ @ 6 1)
         (image "o09.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "o10an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "o10.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】確かにさっぱりわからないが、再び例の会社の前で会って・・・二人で喫茶店に行ったんだ。")
         (wait)
         (text #:color 7 "【" 0 "】いきなり『彼氏と別れる！！』なんて言い出して・・・情緒不安定な女だぜ。")
         (wait))
        (<>))
      (cond
       ((&& (== (: 264) 0) (< H 817))
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】しかし、ひろみちゃんの方からデートに誘ってくれたのに・・・どうして断ってしまったんだろ？")
         (wait)
         (text #:color 7 "【" 0 "】うーん、あの時の俺はどうかしていたに違いない。")
         (wait)))
       ((&& (== (: 264) 1) (< H 817))
        (<>
         (text
          #:color
          7
          "【"
          0
          "】そうそう、忘れちゃいけないぜ・・・１７日の午前１１時に、矢吹公園の入口で待ち合わせをしてるんだ。")
         (wait)
         (text #:color 7 "【" 0 "】しかし、彼女の方から誘ってくるなんて・・・びっくりだよなあ。")
         (wait)))
       ((&& (== (: 264) 1) (== (: 401) 0) (> H 817))
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】ははは、そうだよ・・・俺はひろみちゃんとのデートをすっぽかしてしまったんだ。")
         (wait)))
       ((&& (== (: 264) 1) (== (: 401) 0) (== H 817) (> T 1100))
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】ははは、そうだよ・・・俺はひろみちゃんとのデートをすっぽかしてしまったんだ。")
         (wait)))
       (else (<>)))
      (cond
       ((&& (== (: 401) 1) (== (: 405) 0))
        (<>
         (slot 1 8)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "o12.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "o12an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "o12.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text
          #:color
          7
          "【"
          0
          "】ああ、思い出しただけで腹が立ってくる・・・くどくつもりが、ただの相談相手になってしまった。")
         (wait)
         (text #:color 7 "【" 0 "】俺とした事が、パンティを拝んだだけなんて・・・情けないぜ、うっうっうっ。")
         (wait)))
       ((&& (== (: 405) 1) (== (: 422) 0))
        (<> (text #:color 7 "【" 0 "】彼女は・・・二度と俺の前に姿を現さないって行ってたよな。") (wait)))
       (else (<>)))
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "42.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (cond
       ((&& (== (: 401) 0) (< H 817))
        (<>
         (text #:color 7 "【" 0 "】ひろみちゃんの事をずっと考えていると、ポコチンがハレてくる・・・もうよそうぜ。")
         (wait)))
       ((&& (== (: 264) 1) (== (: 401) 0) (== H 817) (> T 1100))
        (<>
         (text
          #:color
          7
          "【"
          0
          "】まいったな・・・これでひろみちゃんと、いやらしい事ができる確率はぐっと低くなってしまった。")
         (wait)))
       ((&& (== (: 401) 0) (== (: 264) 1) (> H 817))
        (<>
         (text
          #:color
          7
          "【"
          0
          "】まいったな・・・これでひろみちゃんと、いやらしい事ができる確率はぐっと低くなってしまった。")
         (wait)))
       ((&& (== (: 401) 0) (== (: 264) 0) (> H 817))
        (<> (text #:color 7 "【" 0 "】まあいい・・・今度会ったら俺の方から誘えばいいんだ。") (wait)))
       ((== (: 401) 1)
        (<> (text #:color 7 "【" 0 "】もう考えるのはよそう・・・自己嫌悪におちいりそうだ。") (wait)))
       (else (<>)))
      (set-reg: 608 1)
      (slot 1 2)
      (mes-jump "myroom.mes")))
    ((&& (== N 4) (== (: 406) 1))
     (<>
      (text #:color 7 "【" 0 "】ひろみちゃんのデータを見るのか？")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "28.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "o.pd8")
      (proc 16)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "oan.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "o.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】彼女の名前は『田町　ひろみ』・・・このマンションの近所にある『藤田製作所』のＯＬだ。")
      (wait)
      (text #:color 7 "【" 0 "】最初は彼女の方から声をかけてきたんだよな・・・ついこの間の事なのに、なんだか懐かしいなあ。")
      (wait)
      (slot 1 8)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "30.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "o10.pd8")
      (proc 16)
      (set-arr~ @ 6 1)
      (image "o09.pd8")
      (proc 16)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "o10an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "o10.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】そして二人で喫茶店に行って、色々と話をしたんだよな・・・確かその時に彼氏の話がでたんだっけ。")
      (wait)
      (text #:color 7 "【" 0 "】そうだよ、あの喫茶店でデートの約束をしたんだ・・・忘れもしない、８月の１７日だった。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "o12.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "o12an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "o12.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】今思い出すと、なんだかおかしいや・・・くどこうと思ってたのに、見事にはずされてさ。")
      (wait)
      (text #:color 7 "【" 0 "】する話と言ったら、彼氏の相談ばかり・・・最後は『今から彼氏に会いに行く』だもんな、ははは。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】そうそう、あの冬彦とかいうやつが、わざわざ俺を待ち伏せして・・・その後に、今度はひろみちゃんが俺を待ってたんだっけ。")
      (wait)
      (text #:color 7 "【" 0 "】そして、彼女に誘われるままに会社に行ったんだ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "o15.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "o15an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "o15.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】しかし、いきなりあのポーズだもんな・・・びっくりしたよ。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】あれは完全に俺を誘っててたよな・・・俺にあげたい物があるなんて言っちゃって、実は自分の身体だったんだから。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "o01.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "o01an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "o01.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】そう、俺とひろみちゃんは、とろけるようなキスをして・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "o02.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "o02an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "o02.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 7 "【" 0 "】俺は彼女の服を、一枚づつ脱がして・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "o07.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "o03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "o04.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "o05.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "o06.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "o07an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "o07.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "o07.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "o03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "o04.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "o05.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "o07an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "o07.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "o07.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "o03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "o04.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "o07an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "o07.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "o07.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "o03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "o07an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "o07.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "o07.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "o07an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "o07.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】そして彼女と・・・愛し合ったんだ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "o08.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "o08an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "o08.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】ああ・・・彼女の身体のぬくもりは、今でも思い出す事ができる。")
      (wait)
      (text #:color 7 "【" 0 "】ちょっと寂しい別れ方だったけど・・・彼女の言う通り、あれでよかったのかもしれないな。")
      (wait)
      (text #:color 7 "【" 0 "】俺は彼女をつくらない主義だし、彼女だって俺のセックスフレンドって訳にはいかないだろう。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "42.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】ひろみちゃんの事は、思い出として心の中にしまっておこう・・・もう二度と会う事もないんだからな。")
      (wait)
      (set-reg: 608 1)
      (slot 1 2)
      (mes-jump "myroom.mes")))
    (else (<>)))))
 (set-arr~ @ 7 1))