(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\。
  #\な
  #\い
  #\美
  #\沙
  #\う
  #\っ
  #\だ
  #\て
  #\の
  #\か
  #\ん
  #\し
  #\（
  #\）
  #\あ
  #\、
  #\は
  #\に
  #\た
  #\よ
  #\？
  #\を
  #\く
  #\そ
  #\れ
  #\が
  #\も
  #\で
  #\ら
  #\る
  #\事
  #\ぜ
  #\ま
  #\わ
  #\こ
  #\ど
  #\ゃ
  #\気
  #\さ
  #\！
  #\け
  #\き
  #\言
  #\え
  #\俺
  #\お
  #\ろ
  #\一
  #\人
  #\好
  #\と
  #\じ
  #\時
  #\ー
  #\や
  #\め
  #\せ
  #\私
  #\ち
  #\元
  #\何
  #\悪
  #\嫌)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 9 (&& (~ @ 9) 65534))
 (set-arr~ @ 6 1)
 (image "39.pd8")
 (set-arr~ @ 9 (// (~ @ 9) 1))
 (proc 9)
 (set-arr~ @ 7 0)
 (slot 1 8)
 (set-arr~ @ 7 0)
 (load "l08.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (if (== (: 709) 0)
   (<>
    (text #:color 7 "【" 0 "】おーい・・・美沙。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ベットで・・・寝てるのかな？")
    (wait)
    (slot 1 8)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "l08.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 24)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "l08an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "l08.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】なんだよ・・・いるなら返事ぐらいしろよ。")
    (wait)
    (text #:color 3 "【美沙】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】（うーん・・・なんて言えばいいんだろ？）")
    (wait)
    (set-reg: 709 1)))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "他の場所に行く") (text "やめる")))
      (cond
       ((&& (== N 1) (== (: 50) 0))
        (<> (text #:color 7 "【" 0 "】（いや・・・まだここにいようぜ。）") (wait)))
       ((&& (== N 1) (== (: 50) 1))
        (<>
         (text #:color 7 "【" 0 "】じゃあ俺、行くぜ・・・。")
         (wait)
         (text #:color 3 "【美沙】うん・・・。")
         (wait)
         (set-var N 3)
         (slot 1 3)
         (mes-jump "gakko1.mes")))
       ((&& (== N 2) (== (: 50) 0))
        (<> (text #:color 7 "【" 0 "】（そうだな・・・まだここにいよう。）") (wait)))
       ((&& (== N 2) (== (: 50) 1))
        (<> (text #:color 7 "【" 0 "】（美沙を一人にしたほうがいいかな？）") (wait)))
       (else (<>)))))
    ((&& (== V 2) (== N 1) (== (: 10) 0))
     (<>
      (text #:color 7 "【" 0 "】美沙・・・。")
      (wait)
      (set-reg: 101 0)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show
       (<.> (text "元気そうだな") (text "痛そうだな") (text "おいしそうだな") (text "何も言わない")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】元気そうだな。")
         (wait)
         (text #:color 3 "【美沙】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】（あらら・・・返事がないよ。）")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】痛そうだな。")
         (wait)
         (text #:color 3 "【美沙】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】（あらら・・・返事がないよ。）")
         (wait)))
       ((== N 3)
        (<>
         (text #:color 7 "【" 0 "】おいしそうだな。")
         (wait)
         (text #:color 3 "【美沙】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】（あらら・・・返事がないよ。）")
         (wait)))
       ((== N 4)
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 3 "【美沙】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】（気まずい雰囲気だぜ。）")
         (wait)))
       (else (<>)))
      (set-reg: 10 1)))
    ((&& (== V 2) (== N 1) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】（うーん・・・どうしようかな？）")
      (wait)
      (set-reg: 101 0)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "笑わせる") (text "一緒に泣く") (text "何もしない")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】教室でさあ、一哉のやつを裸にして・・・お尻に菊の花を刺した時はおかしかったよなあ。")
         (wait)
         (text #:color 3 "【美沙】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】あの時の写真、今でも持ってるぜ。")
         (wait)
         (text #:color 3 "【美沙】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】（だ、だめかあ・・・。）")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】うっ・・・うっ・・・な、なんて言っていいのか。")
         (wait)
         (text #:color 3 "【美沙】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】こんな事になってしまうなんて・・・うっうっうっ。")
         (wait)
         (text #:color 3 "【美沙】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】（だ、だめだあ・・・。）")
         (wait)))
       ((== N 3)
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 3 "【美沙】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】（まいったな・・・。）")
         (wait)))
       (else (<>)))
      (set-reg: 11 1)))
    ((&& (== V 2) (== N 1) (== (: 11) 1))
     (<>
      (text #:color 7 "【" 0 "】（うーん・・・何をしてあげられるかな？）")
      (wait)
      (text #:color 3 "【美沙】" 0 "・・・。")
      (wait)
      (text #:color 7 "【" 0 "】え！？")
      (wait)
      (text #:color 3 "【美沙】どうして私が・・・ここにいる事がわかったの？")
      (wait)
      (text #:color 7 "【" 0 "】真子先生に聞いたのさ・・・。")
      (wait)
      (text #:color 3 "【美沙】なんだ・・・そうだったのか。")
      (wait)
      (set-reg: 11 2)))
    ((&& (== V 2) (== N 1) (== (: 10) 1))
     (<>
      (text #:color 3 "【美沙】" 0 "・・・。")
      (wait)
      (text #:color 7 "【" 0 "】な、なんだ？")
      (wait)
      (text #:color 3 "【美沙】どうして・・・こうなっちゃうんだろ。")
      (wait)
      (text #:color 7 "【" 0 "】うん・・・。")
      (wait)
      (text #:color 3 "【美沙】大会が近いのに・・・。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 3 "【美沙】ついてないよな・・・。")
      (wait)
      (text #:color 7 "【" 0 "】うん・・・ついてないな。")
      (wait)
      (set-reg: 10 2)))
    ((&& (== V 2) (== N 1) (== (: 10) 2) (== (: 710) 1))
     (<>
      (text #:color 3 "【美沙】" 0 "・・・。")
      (wait)
      (text #:color 7 "【" 0 "】え？")
      (wait)
      (text #:color 3 "【美沙】悪いけど・・・一人にしてくれないかな。")
      (wait)
      (text #:color 7 "【" 0 "】・・・わかった。")
      (wait)
      (set-reg: 50 1)))
    ((&& (== V 2) (== N 1) (< (: 113) 6))
     (<>
      (text #:color 3 "【美沙】" 0 "・・・。")
      (wait)
      (text #:color 7 "【" 0 "】え？")
      (wait)
      (text #:color 3 "【美沙】悪いけど・・・一人にしてくれないかな。")
      (wait)
      (text #:color 7 "【" 0 "】・・・わかった。")
      (wait)
      (set-reg: 50 1)))
    ((&& (== V 2) (== N 1) (== (: 10) 2) (== (: 50) 1))
     (<>
      (text #:color 3 "【美沙】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】（なあ・・・他の場所に行こうぜ。）")
      (wait)))
    ((&& (== V 2) (== N 1) (== (: 10) 2) (== (: 710) 0))
     (<>
      (text #:color 3 "【美沙】" 0 "・・・。")
      (wait)
      (text #:color 7 "【" 0 "】え？")
      (wait)
      (text #:color 3 "【美沙】一人に・・・しないでくれよ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・わかった。")
      (wait)
      (set-reg: 10 3)))
    ((&& (== V 2) (== N 1) (== (: 10) 3))
     (<>
      (text #:color 3 "【美沙】私が・・・自転車で転んだ時の事・・・覚えてる？")
      (wait)
      (text #:color 7 "【" 0 "】ああ、覚えてるぜ。")
      (wait)
      (text #:color 3 "【美沙】あの時さ・・・なんで美穂が" 0 "の事を好きなのか・・・わかったよ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 3 "【美沙】・・・。")
      (wait)
      (set-reg: 10 4)))
    ((&& (== V 2) (== N 1) (== (: 10) 4))
     (<>
      (text #:color 3 "【美沙】あの時の" 0 "ったらさ・・・息をぜいぜい言わせて。")
      (wait)
      (text #:color 7 "【" 0 "】ははは・・・。")
      (wait)
      (text #:color 3 "【美沙】汗なんかぐっしょりかいちゃって。")
      (wait)
      (text #:color 7 "【" 0 "】ははは・・・は。")
      (wait)
      (text #:color 3 "【美沙】私の事を・・・保健室まで運んでくれたんだよな。")
      (wait)
      (text #:color 7 "【" 0 "】重かったぜ・・・とっても。")
      (wait)
      (text #:color 3 "【美沙】あはは・・・運びがいがあっただろ？")
      (wait)
      (set-reg: 10 5)))
    ((&& (== V 2) (== N 1) (== (: 10) 5))
     (<>
      (text #:color 3 "【美沙】あの時のお礼をさ・・・何度も言おうと思ったんだけど。")
      (wait)
      (text #:color 7 "【" 0 "】いいよ、別に。")
      (wait)
      (text #:color 3 "【美沙】何となく、照れちゃって・・・。")
      (wait)
      (text #:color 7 "【" 0 "】美沙のお尻も触れたしさ・・・柔らかかったなあ。")
      (wait)
      (text #:color 3 "【美沙】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】まだ・・痛いのか？")
      (wait)
      (text #:color 3 "【美沙】ううん、もう全然・・・そんなにひどくないんだ。")
      (wait)
      (text #:color 7 "【" 0 "】そうか・・・よかった。")
      (wait)
      (set-reg: 10 6)))
    ((&& (== V 2) (== N 1) (== (: 10) 6))
     (<>
      (text #:color 3 "【美沙】" 0 "の背中って・・・広いんだよな。")
      (wait)
      (text #:color 7 "【" 0 "】そうか？")
      (wait)
      (text #:color 3 "【美沙】あの時から・・・ううん、もっと前からかもしれない。")
      (wait)
      (text #:color 7 "【" 0 "】？？？")
      (wait)
      (text #:color 3 "【美沙】私は・・・" 0 "の事が好きなんだなって。")
      (wait)
      (text #:color 7 "【" 0 "】はあ？")
      (wait)
      (text #:color 3 "【美沙】" 0 "はさ、私なんかに好かれたら・・・迷惑だろうけど。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 3 "【美沙】でも、" 0 "の背中で・・・はっきりわかったんだ。")
      (wait)
      (set-reg: 10 7)))
    ((&& (== V 2) (== N 1) (== (: 10) 7))
     (<>
      (text
       #:color
       3
       "【美沙】別に怪我をしたからってさ、こんな事を言ってるんじゃないよ・・・ただ、"
       0
       "の顔を見てたら急に言いたくなっちゃって。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text
       #:color
       3
       "【美沙】"
       0
       "はさ、私みたいな女の子より・・・かわいい女の子をいっぱい知ってるし、そっちの方が好きだろうし。")
      (wait)
      (text #:color 3 "【美沙】" 0 "の前で・・・男っぽい言葉使いを直そうとしたんだけど、どうも自分らしくないような気がして。")
      (wait)
      (text #:color 7 "【" 0 "】美沙は・・・美沙のままでいいよ。")
      (wait)
      (text #:color 3 "【美沙】え？")
      (wait)
      (text #:color 7 "【" 0 "】俺は美沙の事を・・・。")
      (wait)
      (set-reg: 101 0)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "好き") (text "嫌いじゃない") (text "嫌い")))
      (cond
       ((== N 1)
        (<>
         (sound 1)
         (set-var I 44)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 7 "【" 0 "】俺は美沙の事を好きだぜ・・・。")
         (wait)
         (text #:color 3 "【美沙】いいんだよ、気を使わなくたって。")
         (wait)
         (text #:color 7 "【" 0 "】気を使ってないよ・・・俺の正直な気持ちだ。")
         (wait)
         (text #:color 3 "【美沙】・・・。")
         (wait)
         (text #:color 3 "【美沙】・・・本当？")
         (wait)
         (text #:color 7 "【" 0 "】ああ・・・。")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】俺は美沙の事を嫌いじゃないぜ・・・。")
         (wait)
         (text #:color 3 "【美沙】ははは、嫌いじゃない・・・か。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 3 "【美沙】" 0 "、来てくれてうれしかったよ・・・悪いけど、一人にしてくれないか？")
         (wait)
         (text #:color 7 "【" 0 "】・・・わかった。")
         (wait)
         (set-reg: 50 1)))
       ((== N 3)
        (<>
         (text #:color 7 "【" 0 "】俺は美沙の事を嫌いだぜ。")
         (wait)
         (text #:color 3 "【美沙】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】（ああ、なんて強烈な言葉なんだ。）")
         (wait)
         (text #:color 3 "【美沙】" 0 "、せっかく来てくれたのに悪いけど・・・一人にしてくれないか？")
         (wait)
         (text #:color 7 "【" 0 "】・・・わかった。")
         (wait)
         (set-reg: 50 1)))
       (else (<>)))
      (set-reg: 10 8)))
    ((&& (== V 2) (== N 1) (== (: 10) 8) (== (: 50) 1))
     (<>
      (text #:color 3 "【美沙】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】（美沙を・・・一人にしてやろうぜ。）")
      (wait)))
    ((&& (== V 2) (== N 1) (== (: 10) 8))
     (<>
      (text #:color 7 "【" 0 "】俺は美沙の事が好きだよ・・・男っぽくても、気が強くても、言葉が悪くても、それでも好きだ。")
      (wait)
      (text #:color 3 "【美沙】うれしい・・・涙が出そう。")
      (wait)
      (text #:color 7 "【" 0 "】じゃあ・・・もっとうれしそうな顔をしてくれよ。")
      (wait)
      (text #:color 3 "【美沙】" 0 "に・・・うれしそうな顔にさせて欲しい。")
      (wait)
      (set-arr~ @ 7 0)
      (load "l08a.a6" 47104)))
    ((&& (== V 7) (== N 1))
     (<>
      (text #:color 3 "【美沙】あ・・・。")
      (wait)
      (slot 1 8)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "l09.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "l09an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "l09.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 3 "【美沙】ん・・・" 0 "。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 3 "【美沙】あ・・・い、いや。")
      (wait)
      (text #:color 7 "【" 0 "】（手、手が・・・勝手に動くう！？）")
      (wait)
      (text #:color 3 "【美沙】" 0 "・・・やめて・・・胸は・・・だめ。")
      (wait)
      (text #:color 7 "【" 0 "】（止まれえ・・・俺の手っ！！）")
      (wait)
      (text #:color 3 "【美沙】あん・・・ん・・・。")
      (wait)
      (text #:color 7 "【" 0 "】（と、止まれっ！！俺はパブロフの犬じゃないぞお！！）")
      (wait)
      (text #:color 3 "【美沙】" 0 "・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ははは・・・。")
      (wait)
      (text #:color 3 "【美沙】いいよ・・・そのまま続けても。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 3 "【美沙】あ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】（も、もう・・・だめだあっ！！）")
      (wait)
      (text #:color 3 "【美沙】きゃっ！！")
      (wait)
      (set-reg: 711 1)
      (slot 1 8)
      (mes-jump "l13.mes")))
    ((&& (== V 1) (== N 2) (== (: 12) 0))
     (<> (text #:color 7 "【" 0 "】（元気を出せよ・・・な、美沙。）") (wait) (set-reg: 12 1)))
    ((&& (== V 1) (== N 2) (== (: 12) 1))
     (<> (text #:color 7 "【" 0 "】（美沙には・・・そんな顔は似合わないよ。）") (wait)))
    ((&& (== V 1) (== N 3) (== (: 13) 0))
     (<> (text #:color 7 "【" 0 "】（美沙の髪だな・・・。）") (wait) (set-reg: 13 1)))
    ((&& (== V 1) (== N 3) (== (: 13) 1))
     (<> (text #:color 7 "【" 0 "】（ポニーテールまで・・・寂しそうに見える。）") (wait)))
    ((&& (== V 1) (== N 4) (== (: 14) 0))
     (<>
      (text #:color 7 "【" 0 "】（・・・。）")
      (wait)
      (text #:color 7 "【" 0 "】（さすがに・・・ふざけられないな。）")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 1) (== N 4) (== (: 14) 1))
     (<> (text #:color 7 "【" 0 "】（見るのは・・・よそうぜ。）") (wait)))
    ((&& (== V 1) (== N 5) (== (: 15) 0))
     (<> (text #:color 7 "【" 0 "】（痛々しいな・・・かわいそうだぜ。）") (wait) (set-reg: 15 1)))
    ((&& (== V 1) (== N 5) (== (: 15) 1))
     (<> (text #:color 7 "【" 0 "】（大会が近いのに・・・なんでこんな事になるんだろう。）") (wait)))
    ((&& (== V 1) (== N 6) (== (: 16) 0))
     (<>
      (text #:color 7 "【" 0 "】（・・・。）")
      (wait)
      (text #:color 7 "【" 0 "】（ああ・・・自分のスケベさを呪うぜ。）")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 1) (== N 6) (== (: 16) 1))
     (<> (text #:color 7 "【" 0 "】（俺って・・・煩悩だけで生きてるのかな。）") (wait)))
    ((&& (== V 1) (== N 7) (== (: 17) 0))
     (<> (text #:color 7 "【" 0 "】（元気ないなあ・・・無理もないけど。）") (wait) (set-reg: 17 1)))
    ((&& (== V 1) (== N 7) (== (: 17) 1))
     (<> (text #:color 7 "【" 0 "】（美沙・・・元気出せって。）") (wait)))
    ((&& (== V 1) (== N 8) (== (: 18) 0))
     (<>
      (text #:color 7 "【" 0 "】（ここは保健室だ・・・美沙と二人きりでいる。）")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 1) (== N 8) (== (: 18) 1))
     (<> (text #:color 7 "【" 0 "】（保健室だ・・・真子先生は、まだ校庭で話しているんだろう。）") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))