(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\い
  #\な
  #\。
  #\、
  #\っ
  #\か
  #\て
  #\は
  #\だ
  #\の
  #\ん
  #\あ
  #\る
  #\う
  #\し
  #\た
  #\！
  #\こ
  #\に
  #\？
  #\よ
  #\ら
  #\も
  #\ゃ
  #\が
  #\れ
  #\と
  #\り
  #\ち
  #\そ
  #\く
  #\で
  #\病
  #\ま
  #\院
  #\じ
  #\さ
  #\お
  #\を
  #\わ
  #\ー
  #\ね
  #\ど
  #\ぜ
  #\け
  #\や
  #\君
  #\す
  #\舞
  #\時
  #\事
  #\み
  #\俺
  #\え
  #\子
  #\悪
  #\診
  #\私
  #\間
  #\ろ
  #\言
  #\『
  #\』
  #\来
  #\つ
  #\ば
  #\麗
  #\女
  #\性
  #\夏
  #\日
  #\人
  #\生
  #\ぞ
  #\前
  #\き
  #\先
  #\医
  #\具
  #\合
  #\め
  #\車
  #\奇
  #\忘
  #\度
  #\行
  #\ふ
  #\登
  #\者
  #\一
  #\ッ
  #\気
  #\ン
  #\所
  #\看
  #\ほ
  #\ょ
  #\今
  #\別
  #\見
  #\休
  #\渡
  #\科
  #\場
  #\本)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "52.pd8")
 (proc 15)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "52.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (cond
  ((&&
    (== (: 374) 0)
    (== (: 162) 1)
    (== (: 305) 1)
    (> T 800)
    (< T 2000)
    (== (: 745) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "w.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "wan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "w.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 24)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ま、舞ちゃんっ！！")
    (wait)
    (text #:color 3 "【舞】あ・・・" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】舞ちゃん、どこか具合でも悪いの？")
    (wait)
    (text #:color 3 "【舞】どうしてそんな事を聞くのかしら？")
    (wait)
    (text #:color 7 "【" 0 "】だって・・・ほら。")
    (wait)
    (text #:color 3 "【舞】ああ、病院の前だから・・・私、病院に来た訳じゃないわ。")
    (wait)
    (text #:color 7 "【" 0 "】具合が悪くないの？・・・じゃあ、俺とデートをしよう。")
    (wait)
    (text #:color 3 "【舞】ごめんね、美沙ちゃんと約束があるの・・・またね。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "52.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (if (> T 1700) (<> (text #:color 7 "【" 0 "】約束って・・・こんな時間から？") (wait)))
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】まあいい・・・いつか絶対に、舞ちゃんとデートをしてやる。")
    (wait)
    (set-reg: 374 1)))
  ((&&
    (== (: 375) 0)
    (== (: 162) 1)
    (== (: 250) 1)
    (> T 800)
    (< T 2000)
    (== (: 481) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "r.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ran.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "r.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【くるみ】あ・・・" 0 "さん。")
    (wait)
    (text #:color 7 "【" 0 "】くるみちゃん、妊娠かい？")
    (wait)
    (text #:color 6 "【くるみ】私、妊娠するような事をしてないもん。")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・ちょっとはしないと、一哉がかわいそうだぜ。")
    (wait)
    (text #:color 6 "【くるみ】エッチな話は好きだけど、実際にするのはいや。")
    (wait)
    (text #:color 7 "【" 0 "】してみなけりゃ、いやなものかどうかわからないじゃないか。")
    (wait)
    (text #:color 6 "【くるみ】そうだけど・・・今はいや。")
    (wait)
    (text #:color 7 "【" 0 "】じゃあ、いつだったらいいの？")
    (wait)
    (text #:color 6 "【くるみ】結婚したら。")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・は。")
    (wait)
    (text #:color 6 "【くるみ】" 0 "さんも、あまりエッチな事ばかりしてると病気になっちゃうよ・・・じゃあね、ばいばい。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "52.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (if (: 1900)
      (<> (text #:color 7 "【" 0 "】ばいばいっ・・・て、くるみちゃん、こんな時間に散歩でもしてるのか？") (wait)))
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】かわいいなあ・・・一哉と別れて、俺の愛人になればいいのに。")
    (wait)
    (set-reg: 375 1)))
  ((&&
    (== (: 376) 0)
    (== (: 162) 1)
    (== (: 261) 1)
    (> T 800)
    (< T 2000)
    (== (: 566) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "e.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ean.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "e.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 22)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【かおり】あれ？")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・かおりさん。")
    (wait)
    (text #:color 6 "【かおり】名前、覚えててくれたのね・・・うれしいわ。")
    (wait)
    (text #:color 7 "【" 0 "】当然ですよ、かおりさんみたいな奇麗な人の名前は、忘れようとしても忘れる事ができない。")
    (wait)
    (text #:color 6 "【かおり】あなた・・・確か、" 0 "君だったわね。")
    (wait)
    (text #:color 6 "【かおり】学生にしておくのが、もったいないわねー・・・うちの店で働いたら、いいキャッチになれるわよ。")
    (wait)
    (text #:color 7 "【" 0 "】うちの店？・・・キャッチ？")
    (wait)
    (text #:color 6 "【かおり】あ、いけない・・・これから仕事なの、じゃあまたね！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "52.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】うーん、謎の女性だ・・・何をしてる人なんだろ？")
    (wait)
    (set-reg: 376 1)))
  ((&&
    (== (: 377) 0)
    (== (: 162) 1)
    (== (: 239) 1)
    (> T 800)
    (< T 2000)
    (== (: 641) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "c.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "can.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "c.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 60)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【よしこ】" 0 "君、夏風邪でもひいたの？")
    (wait)
    (text #:color 7 "【" 0 "】あらら・・・芹沢先生。")
    (wait)
    (text
     #:color
     6
     "【よしこ】お腹を出して寝てるからですよ・・・"
     0
     "君は一人暮しですけど、節度ある生活をしないとだめです、暑いからといってエアコンを・・・。")
    (wait)
    (text #:color 7 "【" 0 "】先生、俺はどこも悪くないってば。")
    (wait)
    (text #:color 6 "【よしこ】そうですか、健康な身体には健康な心が宿りますから・・・けっこうな事です。")
    (wait)
    (text #:color 7 "【" 0 "】先生も、たまにはハメをはずしてハメないと、欲求不満になっちゃうぜ。")
    (wait)
    (text #:color 6 "【よしこ】" 0 "君、今度そんな事を言ったら、校長先生に厳しく叱ってもらいますからね！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "52.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】ははは・・・あんな事を言って、怒られない方が不思議だぜ。")
    (wait)
    (set-reg: 377 1)))
  ((&& (== (: 467) 1) (== (: 843) 0) (> H 823) (> T 800) (< T 2359))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n10.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "n10an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n10.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 6)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれえ！？")
    (wait)
    (text #:color 3 "【ちはる】やだ・・・" 0 "君じゃない。")
    (wait)
    (text #:color 7 "【" 0 "】やだって事はないだろ？")
    (wait)
    (text #:color 3 "【ちはる】別に変な意味で言ったんじゃないわよ。")
    (wait)
    (text #:color 7 "【" 0 "】スーツなんか着ちゃって・・・何をしてるのかな、ん？")
    (wait)
    (text #:color 3 "【ちはる】おぢさんみたいな言い方をしないでよ・・・別に何もしてないわ。")
    (wait)
    (text #:color 3 "【ちはる】さてと・・・そろそろ家に帰ろうかなっと。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "52.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】おーい、まだ話は終ってないぞー！！")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ちぇっ。")
    (wait)
    (set-reg: 843 1)))
  ((&& (== (: 479) 1) (== (: 843) 0) (> H 823) (> T 800) (< T 2359))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "nan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 6)
    (proc 26)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (text #:color 3 "【ちはる】嘘つきは嫌いっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "52.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】うーん、けっこう根に持つ女の子だな。")
    (wait)
    (set-reg: 843 1)))
  ((&& (== (: 403) 1) (== (: 562) 0) (> H 819) (> T 800) (< T 1800))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "o14.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "o14an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "o14.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】げっ！！")
    (wait)
    (text #:color 4 "【冬彦】なんだよう・・・。")
    (wait)
    (text #:color 7 "【" 0 "】しっしっしっしっ！！")
    (wait)
    (text #:color 4 "【冬彦】よせよう、僕は犬じゃないぞう。")
    (wait)
    (text #:color 7 "【" 0 "】しーーーーっ！！しっしっ！！")
    (wait)
    (text #:color 4 "【冬彦】泣くぞう・・・泣いてやるぞう。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "52.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】あー、びっくりした・・・。")
    (wait)
    (set-reg: 562 1)))
  ((&& (== (: 745) 1) (> H 819) (< H 824) (> T 800) (< T 1800) (== (: 748) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "w.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "wan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "w.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 24)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あっ！！・・・舞ちゃんっ！！")
    (wait)
    (text #:color 3 "【舞】" 0 "君、こんにちは・・・聞かれる前に答えるけど、私は病気じゃないわよ。")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・よかった。")
    (wait)
    (text #:color 3 "【舞】" 0 "君、それより約束はちゃんと覚えている？")
    (wait)
    (set-reg: 101 1)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "覚えてる") (text "すっかり忘れた")))
    (if (== N 1)
      (<>
       (text #:color 7 "【" 0 "】覚えてるぜ・・・８月２４日、今度の日曜日だ。")
       (wait)
       (text #:color 3 "【舞】早く日曜日が来ないかしら。")
       (wait)
       (text #:color 7 "【" 0 "】うーん、俺もそう思うぜ。")
       (wait)
       (text #:color 3 "【舞】じゃあね、" 0 "君・・・私、もう行かないと。")
       (wait)))
    (if (== N 2)
      (<>
       (text #:color 7 "【" 0 "】えーと・・・あれれ！？")
       (wait)
       (text #:color 3 "【舞】忘れちゃったんでしょ？")
       (wait)
       (text #:color 7 "【" 0 "】うん、すっかり忘れちゃった。")
       (wait)
       (text #:color 3 "【舞】" 0 "君らしいわね・・・約束は８月２４日よ。")
       (wait)
       (text #:color 7 "【" 0 "】あ、そうだ・・・１０時に矢吹町の駅前だったな。")
       (wait)
       (text #:color 3 "【舞】ふふふ、私ね・・・" 0 "君のそういう所も好きなの。")
       (wait)
       (text #:color 7 "【" 0 "】え？")
       (wait)
       (text #:color 3 "【舞】やだ、何を言ってるのかしら・・・私ったら。")
       (wait)
       (text #:color 7 "【" 0 "】好き？・・・誰が？・・・誰を？")
       (wait)
       (text #:color 3 "【舞】じゃあ、私・・・行くわね。")
       (wait)
       (set-reg: 111 (+ (: 111) 1))))
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "52.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】うーん・・・さわやかな風を残して、舞ちゃんは行ってしまった。")
    (wait)
    (set-reg: 748 1)))
  ((&& (== (: 558) 1) (== (: 563) 0) (> H 822) (> T 800) (< T 1800))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "d.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "dan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "d.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 38)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・麗子さん。")
    (wait)
    (text #:color 2 "【麗子】こんにちは・・・" 0 "さん。")
    (wait)
    (text #:color 7 "【" 0 "】まさか、具合が悪いとか？")
    (wait)
    (text #:color 2 "【麗子】いいえ、そんな事は・・・。")
    (wait)
    (text #:color 7 "【" 0 "】具合が悪い時は、俺が看病するから・・・。")
    (wait)
    (text #:color 2 "【麗子】そんな優しい事を言わないでください・・・。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "52.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】まさか・・・泣いていたんじゃないだろうな？")
    (wait)
    (set-reg: 563 1)))
  ((&& (== (: 641) 0) (> H 817) (> T 800) (< T 2100) (== (: 643) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "c.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "can.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "c.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 60)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【よしこ】" 0 "君・・・具合でも悪いの？")
    (wait)
    (text #:color 7 "【" 0 "】先生、俺が具合が悪いように見える？")
    (wait)
    (text #:color 6 "【よしこ】まあ・・・そうですけど。")
    (wait)
    (text #:color 7 "【" 0 "】先生こそ、妊娠でもしたんじゃない？")
    (wait)
    (text #:color 6 "【よしこ】" 0 "君っ！！あ、あなたって人は・・・はあはあはあ。")
    (wait)
    (text #:color 7 "【" 0 "】そ、そんなに冷静な顔をして、言葉だけ興奮する事はないじゃないかよう。")
    (wait)
    (text #:color 6 "【よしこ】そんな言葉を言う時間があったら、勉強しなさいっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "52.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】うーん、怒ったよしこ先生って色っぽいな・・・俺の彼女にしてやってもいいぞ。")
    (wait)
    (set-reg: 643 1)))
  ((&&
    (== (: 539) 1)
    (== (: 547) 1)
    (> H 829)
    (> T 800)
    (< T 1800)
    (== (: 533) 0)
    (== (: 527) 0)
    (== (: 551) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j11.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あっ・・・夏子さんっ！！")
    (wait)
    (text #:color 2 "【夏子】" 0 "君・・・具合でも悪いの？")
    (wait)
    (text #:color 7 "【" 0 "】ああ、病院の前にいるからか・・・違うよ、全然。")
    (wait)
    (text #:color 2 "【夏子】そうよね、" 0 "君が病院に来る訳がないものね。")
    (wait)
    (text #:color 7 "【" 0 "】傷つくなあ、その言い方。")
    (wait)
    (text #:color 2 "【夏子】あははは・・・いつも元気だって誉めてるのよ。")
    (wait)
    (text #:color 7 "【" 0 "】夏子さんこそ、病院に用があるの？")
    (wait)
    (text #:color 2 "【夏子】私が？・・・まさか。")
    (wait)
    (text #:color 2 "【夏子】夏休みの終りよね・・・これからまた忙しくなるわね。")
    (wait)
    (text #:color 7 "【" 0 "】はあ・・・学校の事を考えると、頭が痛くなってくる。")
    (wait)
    (text #:color 2 "【夏子】お互いにがんばらないと・・・じゃあね、" 0 "君！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "52.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】夏子さんさあ、宿題を手伝ってくれない？・・・もちろん俺の部屋で。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ちっ、聞いちゃいないどころか・・・とっとと行ってしまった。")
    (wait)
    (set-reg: 551 1)))
  ((&& (== (: 581) 1) (> H 823) (> T 1000) (< T 1900) (== (: 588) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "e.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ean.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "e.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 22)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【かおり】やだあ、" 0 "君じゃない。")
    (wait)
    (text #:color 7 "【" 0 "】やだあって言われても困るけど・・・かおりさん。")
    (wait)
    (text #:color 6 "【かおり】挨拶みたいなものよ、気にしないで。")
    (wait)
    (text #:color 7 "【" 0 "】病院って事は・・・ヘルペス？")
    (wait)
    (text #:color 6 "【かおり】違うわよ。")
    (wait)
    (text #:color 7 "【" 0 "】じゃあ・・・毛ジラミ？")
    (wait)
    (text #:color 6 "【かおり】あのね、もし私が毛ジラミだったら、" 0 "君にうつってるわよ。")
    (wait)
    (text #:color 7 "【" 0 "】俺の後かもしれないだろ？")
    (wait)
    (text #:color 6 "【かおり】だから、私はしてないの・・・" 0 "君とした後は。")
    (wait)
    (text #:color 7 "【" 0 "】ふーん、へーえ、ほーお。")
    (wait)
    (text #:color 6 "【かおり】信じてないのね・・・まあ、あんな話を聞いたら信じられるわけがないわよね、あはははっ！！")
    (wait)
    (text #:color 7 "【" 0 "】明るいなあ、この明るさはどこからくるんだろう？")
    (wait)
    (text #:color 6 "【かおり】頭の中よ。")
    (wait)
    (text #:color 7 "【" 0 "】そうか、かおりさんは頭の中が具合悪いんだ。")
    (wait)
    (text #:color 6 "【かおり】じゃあ、" 0 "君・・・もう二度と会う事もないわね。")
    (wait)
    (text #:color 7 "【" 0 "】あ、嘘、嘘っ！！")
    (wait)
    (text #:color 6 "【かおり】あはは、こっちも嘘よ・・・街中で見かけたら声をかけて、じゃあね、ばいばい！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "52.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】明るいなあ・・・いいなあ、ああいう女性って。")
    (wait)
    (set-reg: 588 1)))
  ((> T 1900) (<> (text #:color 7 "【" 0 "】夜の病院か・・・夜勤の看護婦さんとかいるのかな？") (wait)))
  ((&& (> T 0) (< T 500))
   (<> (text #:color 7 "【" 0 "】ここは救急病院じゃないからな・・・この時間は診療時間外だ。") (wait)))
  ((== (: 162) 0)
   (<>
    (text #:color 7 "【" 0 "】あれれ！？・・・ここは病院だぜ。")
    (wait)
    (text #:color 7 "【" 0 "】ここは先負町、唯一の病院『登渡り医院』だぜ・・・『トワタリイイン』って読むんだ。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】どうして俺が病院に来なくちゃならんのだ・・・性欲が耳からあふれそうなほど健康なのに。")
    (wait)
    (set-reg: 162 1)))
  ((&& (== (: 162) 1) (== (: 580) 0))
   (<>
    (text #:color 7 "【" 0 "】病院に用はないはずだが・・・なぜか、クレゾールの匂いに引き寄せられてしまうぞ。")
    (wait)))
  ((&& (== (: 580) 1) (== (: 598) 0))
   (<> (text #:color 7 "【" 0 "】ここは病院だな・・・泌尿器科もある。") (wait)))
  ((== (: 598) 1)
   (<> (text #:color 7 "【" 0 "】この病院で、やよいさんは働いてるんだぜ・・・。") (wait))))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "他の場所に行く") (text "中に入る") (text "やめる")))
      (cond
       ((&& (== N 1) (== (: 190) 0) (> T 900) (< T 1900) (== (: 598) 0))
        (<>
         (text #:color 7 "【" 0 "】そうだな、他の場所に行こうぜ・・・。")
         (wait)
         (sound 1)
         (set-var I 37)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 6 "ドン！！")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "u.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "uan.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "u.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 59)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 6 "【奇麗な女性】あ、ごめんなさい！！")
         (wait)
         (text #:color 7 "【" 0 "】あてててて・・・びっくりした。")
         (wait)
         (text #:color 6 "【奇麗な女性】急いでいたから、ごめんなさいね・・・怪我はないですか？")
         (wait)
         (text #:color 7 "【" 0 "】怪我はないけど・・・。")
         (wait)
         (text #:color 6 "【奇麗な女性】よかった・・・じゃあ、私は急ぎますから。")
         (wait)
         (set-reg: 190 1)
         (set-var N 6)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&&
         (== N 1)
         (== (: 190) 1)
         (> H 810)
         (> T 900)
         (< T 1900)
         (== (: 281) 0)
         (== (: 598) 0))
        (<>
         (text #:color 7 "【" 0 "】そうだな、他の場所に行こうぜ・・・。")
         (wait)
         (sound 1)
         (set-var I 37)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 6 "ドスンッ！！")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "u.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "uan.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "u.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 59)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 6 "【奇麗な女性】あ・・・ごめんなさいね。")
         (wait)
         (text #:color 7 "【" 0 "】いてててっ！！")
         (wait)
         (text #:color 6 "【奇麗な女性】大丈夫ですか？")
         (wait)
         (text #:color 7 "【" 0 "】へ、平気だけど・・・前にもこんな事があったような？")
         (wait)
         (text #:color 6 "【奇麗な女性】怪我がなくてよかったわ・・・じゃあね、私は急ぎますから。")
         (wait)
         (text #:color 7 "【" 0 "】あ・・・ち、ちょっと。")
         (wait)
         (set-reg: 281 1)
         (set-var N 6)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 1) (== (: 190) 0))
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・病院は、病人が来る場所だ。")
         (wait)
         (set-var N 6)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 1) (== (: 190) 1))
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・病院は、病人が来る場所だ。")
         (wait)
         (set-var N 6)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 2) (> T 1900) (== (: 580) 1))
        (<> (text #:color 7 "【" 0 "】こんな時間だ・・・診療時間外だな。") (wait)))
       ((&& (== N 2) (< T 900) (== (: 580) 1))
        (<> (text #:color 7 "【" 0 "】こんな時間だ・・・診療時間外だな。") (wait)))
       ((&&
         (== N 2)
         (== (: 580) 1)
         (== (: 598) 0)
         (== (: 600) 0)
         (== (: 601) 0))
        (<>
         (text #:color 7 "【" 0 "】うーん・・・やっぱり診てもらった方がいいよな。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】『本日時々休診』・・・ふざけんなよ、おい。")
         (wait)
         (set-reg: 601 1)))
       ((&&
         (== N 2)
         (== (: 580) 1)
         (== (: 598) 0)
         (== (: 600) 0)
         (== (: 601) 1))
        (<>
         (text #:color 7 "【" 0 "】『本日時々休診』・・・ここの医者は怠け者なのか！？")
         (wait)
         (text #:color 7 "【" 0 "】ちくしょう・・・また今度来てみるか。")
         (wait)))
       ((&& (== N 2) (< M 300))
        (<>
         (text #:color 7 "【" 0 "】『本日時々休診』・・・ここの医者は怠け者なのか！？")
         (wait)
         (text #:color 7 "【" 0 "】ちくしょう・・・また今度来てみるか。")
         (wait)))
       ((&& (== N 2) (== (: 600) 1) (== (: 598) 0))
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・やっぱり診てもらおっと。")
         (wait)
         (slot 1 6)
         (mes-jump "sinryo.mes")))
       ((&& (== N 2) (== (: 598) 1) (< M 100))
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】『本日時々休診』・・・ふざけんなよ、おい。")
         (wait)))
       ((&& (== N 2) (== (: 598) 1) (== (: 617) 0))
        (<>
         (text #:color 7 "【" 0 "】また診てもらうのか？・・・医者は大丈夫だと言ったんだぜ。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】もう一度診てもらおうっと。")
         (wait)
         (slot 1 6)
         (mes-jump "sinryo1.mes")))
       ((&& (== N 2) (== (: 598) 1) (== (: 617) 1))
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・やよいさんに会えるぜ。")
         (wait)
         (slot 1 6)
         (mes-jump "sinryo1.mes")))
       ((&& (== N 2) (> T 1900))
        (<>
         (text #:color 7 "【" 0 "】よそうぜ・・・俺はどこも悪くない。")
         (wait)
         (text #:color 7 "【" 0 "】それにこんな時間だから、もう閉まっているだろう。")
         (wait)))
       ((&& (== N 2) (< T 900))
        (<>
         (text #:color 7 "【" 0 "】よそうぜ・・・俺はどこも悪くない。")
         (wait)
         (text #:color 7 "【" 0 "】それにこの時間じゃ、診察しているとは思えないぜ。")
         (wait)))
       ((== N 2) (<> (text #:color 7 "【" 0 "】よそうぜ・・・俺はどこも悪くない。") (wait)))
       ((== N 3)
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・もしかしたら、かわいい看護婦さんが出て来るかもしれないぞ。")
         (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 1) (== (: 10) 0))
     (<>
      (text #:color 7 "【" 0 "】病院の看板だ・・・『内科、泌尿器科』と書かれている。")
      (wait)
      (set-reg: 10 1)))
    ((&& (== V 1) (== N 1) (== (: 10) 1))
     (<> (text #:color 7 "【" 0 "】だからあ・・・病院の看板だぜ。") (wait)))
    ((&& (== V 1) (== N 2) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】病院の壁だな・・・別にまじまじと見るものじゃないだろう。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 1) (== N 2) (== (: 11) 1))
     (<> (text #:color 7 "【" 0 "】『登渡り医院』の壁だ・・・。") (wait)))
    ((&& (== V 1) (== N 3) (> T 1900))
     (<>
      (text #:color 7 "【" 0 "】あれれ！？・・・診療時間は終ってるのに、どうして車が置いてあるんだ？")
      (wait)
      (text #:color 7 "【" 0 "】車で来て、乗り忘れて帰ったとか？")
      (wait)))
    ((&& (== V 1) (== N 3) (> T 0) (< T 900))
     (<>
      (text #:color 7 "【" 0 "】あれれ！？・・・病院はまだ始まってないはずなのに、どうして車が置いてあるんだ？")
      (wait)
      (text #:color 7 "【" 0 "】車で来て、乗り忘れて帰ったとか？")
      (wait)))
    ((&& (== V 1) (== N 3) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】たくさん車が駐車しているな・・・評判のいい医者なのか、このあたりに病人が多いのかどちらかだな。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 3) (== (: 12) 1))
     (<> (text #:color 7 "【" 0 "】車がたくさん駐車している・・・。") (wait)))
    ((&& (== V 1) (== N 4) (== (: 13) 0))
     (<>
      (text #:color 7 "【" 0 "】けっこうでかい病院だよな・・・別棟ってやつか？")
      (wait)
      (set-reg: 13 1)))
    ((&& (== V 1) (== N 4) (== (: 13) 1))
     (<> (text #:color 7 "【" 0 "】いかにも病院って感じだな・・・。") (wait)))
    ((&& (== V 1) (== N 5) (== (: 14) 0))
     (<>
      (text #:color 7 "【" 0 "】『登渡り医院』と書かれているな・・・広告塔のようなもんだぞ。")
      (wait)
      (text #:color 7 "【" 0 "】そうだ・・・ハデな看板をかかげた病院ほど、ヤブだって知ってるかい？")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 1) (== N 5) (== (: 14) 1))
     (<> (text #:color 7 "【" 0 "】病院の名前が書かれている・・・ちゃんとスポットまでついてるぜ。") (wait)))
    ((&& (== V 1) (== N 6) (== (: 15) 0))
     (<>
      (text #:color 7 "【" 0 "】ここが病人の巣窟、『登渡り医院』だな・・・内科と泌尿器科専門の病院だ。")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 1) (== N 6) (== (: 15) 1))
     (<> (text #:color 7 "【" 0 "】２階・・・いや、３階建てかな？") (wait)))
    ((&& (== V 1) (== N 7) (== (: 16) 0))
     (<>
      (text #:color 7 "【" 0 "】『電波把握棒』だな・・・つまりアンテナだ。")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 1) (== N 7) (== (: 16) 1))
     (<> (text #:color 7 "【" 0 "】病院の屋上から、アンテナが突き出ている・・・。") (wait)))
    ((&& (== V 1) (== N 8) (== (: 17) 0))
     (<>
      (text #:color 7 "【" 0 "】なんだよ・・・まるでヤシの木みたいだな。")
      (wait)
      (text #:color 7 "【" 0 "】『南国情緒豊かな登渡り医院へようこそ！！』ってか？・・・生きられる患者も死にそうだぜ。")
      (wait)
      (set-reg: 17 1)))
    ((&& (== V 1) (== N 8) (== (: 17) 1))
     (<> (text #:color 7 "【" 0 "】どうせだったら、サルでも飼って・・・この木にぶらさげておけばいいのに。") (wait)))
    ((&& (== V 1) (== N 9) (== (: 18) 0))
     (<>
      (text #:color 7 "【" 0 "】はっはっはっ、日本もまだまだ捨てたもんじゃないぞ・・・こんなに緑がたくさんあるじゃないか。")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 1) (== N 9) (== (: 18) 1))
     (<>
      (text #:color 7 "【" 0 "】木だぜ・・・登るかい？")
      (wait)
      (set-reg: 101 0)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "はい") (text "いいえ")))
      (cond
       ((== N 1) (<> (text #:color 7 "【" 0 "】やだよ。") (wait)))
       ((== N 2) (<> (text #:color 7 "【" 0 "】登りたいなあ・・・。") (wait)))
       (else (<>)))
      (set-reg: 18 2)))
    ((&& (== V 1) (== N 9) (== (: 18) 2))
     (<> (text #:color 7 "【" 0 "】先負町には、緑がいっぱいだ・・・。") (wait)))
    ((&& (== V 1) (== N 10) (> T 1900) (== (: 19) 0))
     (<>
      (text #:color 7 "【" 0 "】夜空に雲がプカプカと浮かんでいる・・・。")
      (wait)
      (text #:color 7 "【" 0 "】あれれ・・・あの雲の形って、女性の×××に似てないか？")
      (wait)
      (text #:color 7 "【" 0 "】ほら、あれだよ・・・あの雲だよ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】あーあ、形が変わっちゃった。")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 1) (== N 10) (> T 0) (< T 500) (== (: 19) 0))
     (<>
      (text #:color 7 "【" 0 "】深夜に一人で病院の前に立ち、空をぼんやりと見つめている俺・・・。")
      (wait)
      (text #:color 7 "【" 0 "】けっこう気味が悪いぜ。")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 1) (== N 10) (== (: 19) 0))
     (<>
      (text #:color 7 "【" 0 "】はっはっはっはっはっは！！")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】はーーっはっはっはっ！！")
      (wait)
      (text #:color 7 "【" 0 "】最近、空を見てると無性におかしくなるんだ。")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 1) (== N 10) (== (: 19) 1))
     (<> (text #:color 7 "【" 0 "】空だな、晴れているぞ・・・きっと俺様のおかげだぜ。") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))