(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\い
  #\な
  #\、
  #\。
  #\て
  #\っ
  #\だ
  #\か
  #\ん
  #\る
  #\の
  #\う
  #\は
  #\に
  #\た
  #\を
  #\し
  #\こ
  #\あ
  #\？
  #\で
  #\と
  #\が
  #\ら
  #\！
  #\一
  #\く
  #\や
  #\も
  #\れ
  #\り
  #\よ
  #\そ
  #\ゃ
  #\す
  #\さ
  #\ま
  #\二
  #\健
  #\ち
  #\人
  #\哉
  #\ル
  #\お
  #\じ
  #\ー
  #\ろ
  #\わ
  #\何
  #\ホ
  #\テ
  #\事
  #\場
  #\け
  #\み
  #\ッ
  #\女
  #\所
  #\つ
  #\え
  #\ぜ
  #\ス
  #\ど
  #\俺
  #\来
  #\セ
  #\ょ
  #\気
  #\ば
  #\ラ
  #\物
  #\ク
  #\車
  #\ト
  #\間
  #\見
  #\違
  #\ぎ
  #\『
  #\』
  #\０
  #\持
  #\中
  #\入
  #\ね
  #\今
  #\思
  #\生
  #\き
  #\僕
  #\性
  #\前
  #\ぞ
  #\行
  #\ご
  #\合
  #\舞
  #\げ
  #\君
  #\時
  #\ン
  #\出
  #\イ
  #\早
  #\自)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "50.pd8")
 (proc 15)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "50.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (cond
  ((&&
    (== (: 382) 0)
    (== (: 261) 1)
    (== (: 173) 1)
    (== (: 578) 0)
    (== (: 839) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "e.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ean.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "e.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 22)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれれれっ！？")
    (wait)
    (text #:color 6 "【かおり】やだ・・・変な所で会っちゃったわね。")
    (wait)
    (text #:color 7 "【" 0 "】一人・・・ですか？")
    (wait)
    (text #:color 6 "【かおり】さてと・・・急いで帰らないと。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "50.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】まあいい・・・いつか絶対に、舞ちゃんとデートをしてやる。")
    (wait)
    (set-reg: 382 1)
    (set-reg: 839 1)))
  ((&&
    (== (: 383) 0)
    (== (: 250) 1)
    (== (: 173) 1)
    (> T 0)
    (< T 600)
    (== (: 481) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "i.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ran.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "r.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 5 "【一哉】げっ・・・" 0 "。")
    (wait)
    (text #:color 7 "【" 0 "】一哉君、こんな時間にこんな場所で、いったい何をやってるのかね？")
    (wait)
    (text #:color 5 "【一哉】ははは、ちょっと・・・な。")
    (wait)
    (text #:color 7 "【" 0 "】今日はくるみちゃんの姿が見えないな・・・。")
    (wait)
    (text #:color 5 "【一哉】こんな時間に、連れ歩けないよ・・・彼女は門限が厳しいんだ。")
    (wait)
    (text #:color 7 "【" 0 "】ははあ、もう浮気してるのか？")
    (wait)
    (text #:color 5 "【一哉】だ、だから違うってば・・・たまたま通りかかっただけさ。")
    (wait)
    (text #:color 7 "【" 0 "】こんな時間に？")
    (wait)
    (text #:color 5 "【一哉】さてと、帰ろっと・・・寝不足は美容に悪いからな。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "50.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】一哉が女をナンパして、ホテルに連れ込むとは思えないし・・・あいつ、何をしてたんだ？")
    (wait)
    (set-reg: 383 1)))
  ((&&
    (== (: 384) 0)
    (== (: 246) 1)
    (== (: 173) 1)
    (> T 800)
    (< T 2300)
    (== (: 419) 0)
    (== (: 765) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "b.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "man.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 4 "【健二】" 0 "・・・。")
    (wait)
    (text #:color 7 "【" 0 "】け、健二じゃないか・・・舞ちゃんと一緒だったら、生きてここから出られると思うなよ。")
    (wait)
    (text #:color 4 "【健二】僕も同じ事を言おうと思ってたぜ・・・一人か？")
    (wait)
    (text #:color 7 "【" 0 "】ああ。")
    (wait)
    (text #:color 4 "【健二】僕もだ。")
    (wait)
    (text #:color 7 "【" 0 "】そうか。")
    (wait)
    (text #:color 4 "【健二】" 0 "・・・舞の事はいいかげんにあきらめろ。")
    (wait)
    (text #:color 7 "【" 0 "】やなこった。")
    (wait)
    (text #:color 4 "【健二】無駄だよ・・・" 0 "じゃ身分が違う。")
    (wait)
    (text #:color 7 "【" 0 "】舞ちゃんがそういう事を考える女性だったらな・・・お前、そんな事もわかってないのか？")
    (wait)
    (text #:color 4 "【健二】僕は舞の全てを知ってるぞ・・・お前とはスタートラインが違うんだ。")
    (wait)
    (text #:color 4 "【健二】じゃあな・・・ああ、気分が悪い。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "50.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】・・・ふう。")
    (wait)
    (set-reg: 384 1)))
  ((&& (== (: 385) 0) (== (: 382) 1) (> H 812) (== (: 578) 0) (== (: 839) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "e.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ean.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "e.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 22)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【かおり】やだ・・・また会っちゃった。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 6 "【かおり】あ・・・約束があったんだ、急いで行かないと。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "50.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】くんか、くかん、くんか。")
    (wait)
    (text #:color 7 "【" 0 "】うーん、香水の香りを残して・・・彼女は行ってしまった。")
    (wait)
    (set-reg: 385 1)
    (set-reg: 839 1)))
  ((&& (== (: 386) 0) (== (: 382) 1) (> H 814) (== (: 578) 0) (== (: 839) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "e.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ean.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "e.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 22)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【かおり】あ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ま、また！？")
    (wait)
    (text #:color 6 "【かおり】ばいばい、" 0 "君。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "50.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】うーん、ちょっと気まずい雰囲気だったかな？")
    (wait)
    (set-reg: 386 1)
    (set-reg: 839 1)))
  ((&& (== (: 387) 0) (== (: 382) 1) (> H 815) (== (: 578) 0) (== (: 839) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "e.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ean.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "e.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 22)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【かおり】ま、またなの？・・・もういや！！")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・。")
    (wait)
    (text #:color 6 "【かおり】" 0 "君って・・・やる子だったのね、学生なのにすごいわ。")
    (wait)
    (text #:color 7 "【" 0 "】へ？")
    (wait)
    (text #:color 6 "【かおり】隠さなくていいの、あなたも私も同じ種類の人間なんだから・・・じゃあね、今度は他の場所で会いたいわね。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "50.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なんだよ・・・同じ種類の人間って？")
    (set-reg: 387 1)
    (set-reg: 839 1)))
  ((&& (== (: 446) 1) (== (: 447) 0) (> T 800) (< T 2359) (== (: 765) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "b.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "man.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 4 "【健二】ぎょっ！？")
    (wait)
    (text #:color 7 "【" 0 "】誰が『魚』だって？")
    (wait)
    (text #:color 4 "【健二】ふっ・・・会う早々レベルの低いギャグとはな、まったく仕方のない男だ。")
    (wait)
    (text #:color 7 "【" 0 "】なんだ、そこにいるのは『権之助』君じゃないか。")
    (wait)
    (text #:color 4 "【健二】健二。")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・冗談だよ、猿丸。")
    (wait)
    (text #:color 4 "【健二】どこに『猿丸』なんて名前のやつがいるんだっ！？")
    (wait)
    (text #:color 7 "【" 0 "】そう怒るな、便造。")
    (wait)
    (text #:color 4 "【健二】べ、べんぞう！？・・・俺は健二だっ！！")
    (wait)
    (text #:color 7 "【" 0 "】ところで健二・・・ホテルで何をしてるんだ？")
    (wait)
    (text #:color 4 "【健二】やっと僕の名前を覚えたようだな・・・ホテルで何をしてるって、決まってるだろう？")
    (wait)
    (text #:color 7 "【" 0 "】子供だからわからないんだ。")
    (wait)
    (text #:color 4 "【健二】なら教えてやろう、女性と愛し合ってたんだ。")
    (wait)
    (text #:color 7 "【" 0 "】ママか？")
    (wait)
    (text #:color 4 "【健二】違うっ！！そんな事をしたら、犯罪者だっ！！")
    (wait)
    (text #:color 7 "【" 0 "】じゃあ・・・パパ？")
    (wait)
    (text #:color 4 "【健二】ふっ・・・ぼ、僕を興奮させようとしても、そうはいかないぞ。")
    (wait)
    (text #:color 7 "【" 0 "】１００歩ゆずって、どこかの女性と愛し合っていたとして・・・どうして一人で出て来るんだよ。")
    (wait)
    (text #:color 4 "【健二】そ、それは・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ははあ・・・健二は小さくて、早いな。")
    (wait)
    (text #:color 4 "【健二】ぎくっ！！")
    (wait)
    (text #:color 7 "【" 0 "】ついでに皮までかぶってた日にゃあ・・・女に逃げられて当り前だ。。")
    (wait)
    (text #:color 4 "【健二】ぎくうっ！！・・・ぼ、僕はこれで失礼する。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "50.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】あれれ・・・走って行っちゃったぜ。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あいつ本当に・・・小さくて、早くて、皮かむりなのか？")
    (wait)
    (set-reg: 447 1)))
  ((&& (== (: 481) 1) (> H 817) (> T 800) (< T 1900) (== (: 510) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "q.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "qan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "q.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】く、くるみちゃん！？・・・こんな場所で何をしてるんだよ！？")
    (wait)
    (text #:color 6 "【くるみ】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】くるみちゃん？")
    (wait)
    (text #:color 6 "【くるみ】あ・・・" 0 "さん。")
    (wait)
    (text #:color 7 "【" 0 "】" 0 "さんじゃないぜ・・・まさか、一哉の事でヤケになって、おぢさんに春を売ってしまったとか！？")
    (wait)
    (text #:color 6 "【くるみ】いやだ・・・違うの。")
    (wait)
    (text #:color 7 "【" 0 "】何が違うんだよ。")
    (wait)
    (text #:color 6 "【くるみ】前にね、ここに一哉君と来たの・・・その事を思い出してた。")
    (wait)
    (text #:color 7 "【" 0 "】くるみちゃん・・・気持ちはわかるけど、セーラー服姿でこんな場所に立ってると誤解されちゃうぜ。")
    (wait)
    (text #:color 6 "【くるみ】わかってる・・・私、もう帰る。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "50.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】あ・・・ち、ちょっと待てよ。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】一哉も罪な野郎だぜ・・・まったく。")
    (wait)
    (set-reg: 510 1)))
  ((&&
    (== (: 528) 1)
    (== (: 535) 0)
    (> H 825)
    (> T 800)
    (< T 2300)
    (== (: 527) 0)
    (== (: 532) 0)
    (== (: 533) 0))
   (<>
    (text #:color 7 "【" 0 "】うーん・・・みんなエッチな事をしてるのかな？")
    (wait)
    (text #:color 5 "【男の声】" 0 "・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ぎょっ！？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j12.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j11.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】な、なんだよ・・・脅かすな。")
    (wait)
    (text #:color 5 "【一哉】最近下痢ぎみでさあ・・・ちょっとトイレを借りてたんだ。")
    (wait)
    (text #:color 7 "【" 0 "】トイレを借りるって・・・ここで借りたのか？")
    (wait)
    (text #:color 5 "【一哉】ああ、待ってくれないからなウ○コは・・・今度からお尻の穴に栓をしてから出かけるとしよう。")
    (wait)
    (text #:color 7 "【" 0 "】汚いなあ・・・一哉、そんな話をしてる場合じゃないだろ？")
    (wait)
    (text #:color 5 "【一哉】・・・。")
    (wait)
    (text #:color 5 "【一哉】そうだった・・・下痢をしてる場合じゃないんだ。")
    (wait)
    (text #:color 7 "【" 0 "】そうそう、せいぜいがんばれよ。")
    (wait)
    (text #:color 5 "【一哉】" 0 "ー・・・最近俺に対して冷たくないか？")
    (wait)
    (text #:color 7 "【" 0 "】はっはっはっ、みんなに嫌われる星の下に一哉は生まれてんだ・・・かわいそうに。")
    (wait)
    (text #:color 5 "【一哉】ああ、またゲリピーになりそうだ・・・じ、じゃあな、ううっ、も、もれるっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "50.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】はははははっ！！尻を押さえて走る一哉か・・・うーん、写真に撮っておきたいぞ。")
    (wait)
    (set-reg: 535 1)))
  ((&& (== (: 617) 1) (> H 826) (> T 1000) (< T 1900) (== (: 629) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "uan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 59)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【やよい】きゃっ！！")
    (wait)
    (text #:color 7 "【" 0 "】うわっと！！")
    (wait)
    (text #:color 6 "【やよい】あら・・・" 0 "さん。")
    (wait)
    (text #:color 7 "【" 0 "】や、やよいさん！？・・・こんな場所で何をしてるの！？")
    (wait)
    (text #:color 6 "【やよい】このホテルの支配人が、病院の先生の知り合いで・・・届け物をしてたんです。")
    (wait)
    (text #:color 7 "【" 0 "】届け物だけ？")
    (wait)
    (text #:color 6 "【やよい】それ以外に何かあります？")
    (wait)
    (text #:color 7 "【" 0 "】ついでに・・・変な事をしてない？")
    (wait)
    (text #:color 6 "【やよい】" 0 "さん、変な事って何ですか？")
    (wait)
    (text #:color 7 "【" 0 "】だから・・・変な事だよう。")
    (wait)
    (text #:color 6 "【やよい】そういう" 0 "さんこそ、ここに何をしに来たんですか？")
    (wait)
    (text #:color 7 "【" 0 "】俺の学校の先生が、ホテルの支配人と知り合いで・・・届け物をしてたんだよ。")
    (wait)
    (text #:color 6 "【やよい】さようなら、" 0 "さん。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "50.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】あ・・・じ、冗談だってば！！")
    (wait)
    (text #:color 7 "【" 0 "】あらら・・・彼女にはへたな冗談が通じないようだ。")
    (wait)
    (set-reg: 629 1)))
  ((> T 1900)
   (<> (text #:color 7 "【" 0 "】うーん・・・あたりが暗いと、いっそういやらしい雰囲気だな。") (wait)))
  ((&& (> T 0) (< T 500))
   (<>
    (text #:color 7 "【" 0 "】さて、質問です・・・このホテルでは何人の男女がセックスしてるでしょう？")
    (wait)
    (text #:color 7 "【" 0 "】なんて事を自問自答するより、俺もセックスしている側になりたい。")
    (wait)))
  ((== (: 173) 0)
   (<> (text #:color 7 "【" 0 "】あわわわわ・・・ど、どうして俺はラブホテルに来てしまったんだ！？") (wait)))
  ((&& (== (: 173) 1) (== (: 765) 0))
   (<>
    (text #:color 7 "【" 0 "】なあ・・・一人で来て、何をするつもりだ？")
    (wait)
    (text #:color 7 "【" 0 "】エッチビデオでも見て、『おなにひ』でもするのか？")
    (wait)))
  ((&& (== (: 765) 1) (== (: 766) 0))
   (<>
    (text #:color 7 "【" 0 "】誰も・・・いない。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】こ、こんなホテルなんか・・・大嫌いだあっ！！")
    (wait)
    (text #:color 7 "【" 0 "】うーん、なんとかして立ち直らないと・・・こういう時は、他の女の子とエッチをするのが一番だな。")
    (wait)
    (set-reg: 766 1)))
  ((== (: 766) 1)
   (<> (text #:color 7 "【" 0 "】ちっくしょう・・・このホテルに来るたびに腹が立ってくる。") (wait))))
 (if (== (: 766) 1) (<>))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "他の場所に行く") (text "中に入る") (text "やめる")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・一人で来ても何もする事がない場所だ。")
         (wait)
         (set-var N 11)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 2) (== (: 173) 0))
        (<>
         (text #:color 7 "【" 0 "】おいおい、本当に中に入るのか？・・・確かにここは２４時間、いつでも営業しているが・・・。")
         (wait)
         (text #:color 7 "【" 0 "】ご休憩が６８００円、ご宿泊が１２０００円か・・・一人でこんな大金を使う気になれないな。")
         (wait)
         (set-reg: 173 1)))
       ((&& (== N 2) (== (: 173) 1))
        (<>
         (text #:color 7 "【" 0 "】一人でラブホテルに泊まるのか？・・・一人だったら、カプセルホテルで十分だぜ。")
         (wait)))
       ((== N 3)
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・ここに来る恋人達を、好奇心に満ちた目でジロジロと見てやるか。")
         (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 1) (== (: 10) 0))
     (<>
      (text #:color 7 "【" 0 "】すっごい車だな・・・こんな車を持っているほどの金持ちなら、別荘でエッチをすればいいのに。")
      (wait)
      (text #:color 7 "【" 0 "】それとも今はやりの、持物は一流、生活は困窮ってやつか？")
      (wait)
      (set-reg: 10 1)))
    ((&& (== V 1) (== N 1) (== (: 10) 1))
     (<>
      (text #:color 7 "【" 0 "】せっかくすごい車があるんだから、俺様がサインをしてやろう・・・油性のマジックで。")
      (wait)))
    ((&& (== V 1) (== N 2) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】はやりの４ＷＤだな・・・ワイルドな車に乗っているのなら、外でセックスをすればいいのに。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 1) (== N 2) (== (: 11) 1))
     (<>
      (text #:color 7 "【" 0 "】俺だったら、４ＷＤで野原を駆け回り・・・野性的な女を、野性的に犯してやるぜ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】そうだ、俺は免許を持ってなかった。")
      (wait)))
    ((&& (== V 1) (== N 3) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】車の持主は、今ごろホテルの中で・・・。")
      (wait)
      (text #:color 7 "【" 0 "】くーーーっ！！うらやましいっ！！")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 3) (== (: 12) 1))
     (<> (text #:color 7 "【" 0 "】車だな・・・この駐車場でカーセックスをしてたら、さぞや怒られるだろう。") (wait)))
    ((&& (== V 1) (== N 4) (== (: 13) 0))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】たくさん植木があるなあ・・・いやらしさを和らげる為に植えられている物もあれば、中が覗かれにくいように植えられている物もある。")
      (wait)
      (set-reg: 13 1)))
    ((&& (== V 1) (== N 4) (== (: 13) 1))
     (<> (text #:color 7 "【" 0 "】だたの植木さ・・・。") (wait)))
    ((&& (== V 1) (== N 5) (== (: 14) 0))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】ここを入ると、フロントがあって・・・部屋の写真がパネルになっていて、ボタンを押すとキーが出てくる仕掛けさ。")
      (wait)
      (text #:color 7 "【" 0 "】って、一哉が言ってたな・・・あんないたいけな『くるみちゃん』とこのホテルに来てるのか？")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 1) (== N 5) (== (: 14) 1))
     (<>
      (text #:color 7 "【" 0 "】入口だ・・・今まで何人の恋人達が、ここを通ったのだろう。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】恋人達とは限らないか・・・。")
      (wait)))
    ((&& (== V 1) (== N 6) (== (: 16) 0))
     (<>
      (text #:color 7 "【" 0 "】うーん、見るからに『ラブホテル』って感じだな・・・耳をすますと、あえぎ声が聞こえてきそうだ。")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 1) (== N 6) (== (: 16) 1))
     (<>
      (text #:color 7 "【" 0 "】この中に、何人の人達がいたしているんだろう・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ああ、想像している自分が情けない・・・他の場所に行かないか？")
      (wait)))
    ((&& (== V 1) (== N 7) (== (: 17) 0))
     (<>
      (text #:color 7 "【" 0 "】壁がひときわ高いな・・・これで入口が鉄格子だったら、監獄だぜ。")
      (wait)
      (set-reg: 17 1)))
    ((&& (== V 1) (== N 7) (== (: 17) 1))
     (<>
      (text #:color 7 "【" 0 "】セックスは悪い事じゃないのに、どうして人目を忍んでするんだろう・・・。")
      (wait)
      (text #:color 7 "【" 0 "】そうか、セックス自体は悪い事じゃないが・・・その行為をする二人は忍んでする関係なんだな。")
      (wait)))
    ((&& (== V 1) (== N 8) (== (: 18) 0))
     (<>
      (text #:color 7 "【" 0 "】ははは、ここはお城か？")
      (wait)
      (text #:color 7 "【" 0 "】あの上にカラスがとまったら、串刺しになりそうだな。")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 1) (== N 8) (== (: 18) 1))
     (<> (text #:color 7 "【" 0 "】とんがり屋根だ・・・ここが普通の家だったら、大笑いだぜ。") (wait)))
    ((&& (== V 1) (== N 9) (== (: 19) 0))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】ここほど、空を見上げるのにフィットしない場所はないだろう・・・男は目をギラつかせて、一刻も早く建物の中に入ろうと思い・・・。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】女は恥ずかしいフリをするのも疲れるから、一刻も早く建物の中に入ろうと思う訳だ・・・空なんか見ている暇はないだろう。")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 1) (== N 9) (== (: 19) 1))
     (<> (text #:color 7 "【" 0 "】だから、俺も空は見ない・・・一人でながめるには、寂しすぎる場所だ。") (wait)))
    ((&& (== V 1) (== N 10) (== (: 20) 0))
     (<>
      (text #:color 7 "【" 0 "】地面はアスファルトのようだ・・・ゴミ一つ落ちていない。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】セックス産業が、一番客に気を使う業種だ・・・自称、『ラブホテル評論家』の俺様が言うんだから間違いない。")
      (wait)
      (text #:color 7 "【" 0 "】・・・もっとも金を持ってない客には、これほど非道な業種もないが。")
      (wait)
      (set-reg: 20 1)))
    ((&& (== V 1) (== N 10) (== (: 20) 1))
     (<> (text #:color 7 "【" 0 "】けっこう広い敷地だな・・・駐車場も広いぞ。") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))