(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\。
  #\る
  #\【
  #\】
  #\い
  #\く
  #\ん
  #\の
  #\、
  #\っ
  #\な
  #\み
  #\う
  #\だ
  #\て
  #\は
  #\に
  #\す
  #\を
  #\し
  #\か
  #\さ
  #\た
  #\お
  #\ば
  #\ま
  #\と
  #\俺
  #\あ
  #\が
  #\れ
  #\け
  #\り
  #\で
  #\ら
  #\ー
  #\０
  #\ゃ
  #\も
  #\よ
  #\ち
  #\や
  #\女
  #\こ
  #\？
  #\！
  #\事
  #\そ
  #\き
  #\彼
  #\べ
  #\ひ
  #\（
  #\）
  #\わ
  #\じ
  #\ロ
  #\プ
  #\ど
  #\ぐ
  #\ろ
  #\人
  #\言
  #\動
  #\ぜ
  #\円
  #\せ
  #\手
  #\め
  #\ね
  #\部
  #\ご
  #\見
  #\身
  #\体
  #\大
  #\目
  #\分
  #\ス
  #\２
  #\え
  #\つ
  #\突
  #\飛
  #\ッ
  #\ン
  #\ざ
  #\屋
  #\ず
  #\間
  #\胸
  #\普
  #\通
  #\テ
  #\ト
  #\悪
  #\帰
  #\度
  #\思
  #\キ
  #\ル
  #\下
  #\一
  #\恐
  #\ア
  #\デ
  #\気
  #\私
  #\び
  #\今
  #\師
  #\匠
  #\へ
  #\ょ
  #\ほ
  #\何
  #\物
  #\自
  #\唇
  #\感
  #\ビ
  #\む
  #\隣
  #\客
  #\ベ
  #\着
  #\上)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "50.pd8")
 (proc 15)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "17.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (if (== (: 515) 0)
   (<>
    (text #:color 7 "【" 0 "】くるみちゃん、今日から俺の事を師匠と呼ぶんだ。")
    (wait)
    (text #:color 6 "【くるみ】師匠？")
    (wait)
    (text #:color 7 "【" 0 "】そりゃそうだ、くるみちゃんを大人の女性に仕上げる師匠だぜ、俺は。")
    (wait)
    (text #:color 6 "【くるみ】・・・うん。")
    (wait)
    (text #:color 7 "【" 0 "】弟子は師匠の言う事を聞くもんだ・・・俺がする事に、一切文句を言わない・・・いいね？")
    (wait)
    (text #:color 6 "【くるみ】うん・・・わかった。")
    (wait)
    (text #:color 7 "【" 0 "】よーし・・・じゃあ中に入ろう。")
    (wait)
    (text #:color 2 "【おばさん】ひっひっひっ・・・いらっしゃい、すけべ。")
    (wait)
    (text #:color 7 "【" 0 "】気味の悪いばばあだな。")
    (wait)
    (text #:color 2 "【おばさん】休憩が６８００円、お泊まりが１２０００円だよ・・・すけべ。")
    (wait)
    (text #:color 7 "【" 0 "】うーん・・・どうするかな？")
    (wait)
    (set-reg: 101 1)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "休憩") (text "お泊まり")))
    (if (== N 1)
      (<> (text #:color 7 "【" 0 "】休憩だな・・・くるみちゃんを外泊させる訳にはいかない。") (wait)))
    (if (== N 2)
      (<>
       (text #:color 7 "【" 0 "】泊まりの方がゆっくりできるぜ、へっへっへっ。")
       (wait)
       (text #:color 6 "【くるみ】" 0 "さん・・・私、泊まれない。")
       (wait)
       (text #:color 7 "【" 0 "】でしょう？・・・休憩だぜ、おばはん。")
       (wait)))
    (text #:color 2 "【おばさん】休憩かね、すけべ・・・６８００円になります。")
    (wait)
    (text #:color 2 "【おばさん】すけべ。")
    (wait)
    (if (< M 6800)
      (<>
       (text #:color 7 "【" 0 "】６８００円ね・・・！？")
       (wait)
       (text #:color 7 "【" 0 "】た、足りない・・・どうしよう。")
       (wait)
       (text #:color 6 "【くるみ】" 0 "さん・・・これを使って。")
       (wait)
       (text #:color 7 "【" 0 "】そうだな、弟子が師匠の為に金を出すのは当り前だ・・・ほれ、おばはん、６８００円だぜ。")
       (wait)
       (set-reg: 112 (- (: 112) 2))))
    (if (> M 6799)
      (<>
       (text #:color 7 "【" 0 "】６８００円ね・・・ほれ、おばはん。")
       (wait)
       (set-var M (- M 6800))
       (proc 11)))
    (text #:color 2 "【おばさん】ありがとうございます、すけべ・・・鍵をどうぞ、すけべ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "kuro.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (text #:color 7 "【" 0 "】えーと・・・３０２号室か。")
    (wait)
    (text #:color 6 "【くるみ】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】おっと、ここだな・・・かちゃかちゃ、がちゃっ！！")
    (wait)
    (slot 1 8)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "17.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 9)
    (set-arr~ @ 6 1)
    (image "q04.pd8")
    (proc 25)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "q04an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "q04.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【くるみ】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】（うーん・・・なんていやらしい部屋なんだ。）")
    (wait)
    (text #:color 6 "【くるみ】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】（くんか、くんか・・・何とも言えない匂いがするな、男と女の愛液の匂いか？）")
    (wait)
    (set-reg: 515 1)))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<> (text "帰る")))
      (cond
       ((&& (== N 1) (== (: 10) 0))
        (<>
         (text #:color 7 "【" 0 "】（冗談じゃない・・・絶対に帰りたくないぞ。）")
         (wait)
         (set-reg: 10 1)))
       ((&& (== N 1) (== (: 10) 1))
        (<> (text #:color 7 "【" 0 "】（だからあ・・・絶対に帰らないってば。）") (wait)))
       (else (<>)))))
    ((&& (== V 2) (== N 1) (== (: 10) 0))
     (<>
      (text #:color 6 "【くるみ】" 0 "さん・・・恐い。")
      (wait)
      (text #:color 7 "【" 0 "】大丈夫だよ、くるみちゃん・・・僕がついてるじゃないか。")
      (wait)
      (text #:color 6 "【くるみ】だから恐いの・・・。")
      (wait)
      (text #:color 7 "【" 0 "】今さらそんな事を言われたってよう。")
      (wait)
      (set-reg: 10 1)))
    ((&& (== V 2) (== N 1) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】くるみちゃん・・・。")
      (wait)
      (text #:color 6 "【くるみ】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】（うーん、極度の緊張状態だな・・・粗相をしなければいいが。）")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 2) (== N 1) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】くるみちゃん、こっちにおいで・・・。")
      (wait)
      (text #:color 6 "【くるみ】いや・・・。")
      (wait)
      (text #:color 7 "【" 0 "】いやって・・・そこにずっと立ってるつもりか？")
      (wait)
      (text #:color 6 "【くるみ】だって・・・恐いんだもん。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 2) (== N 1) (== (: 13) 0))
     (<>
      (text #:color 7 "【" 0 "】くるみちゃん、俺は恐くないってば。")
      (wait)
      (text #:color 6 "【くるみ】いや・・・その目が恐い。")
      (wait)
      (text #:color 7 "【" 0 "】ほーら、こんなに優しい目をしてるだろ？")
      (wait)
      (text #:color 6 "【くるみ】・・・。")
      (wait)
      (text #:color 6 "【くるみ】動物の目をしてる。")
      (wait)
      (text #:color 7 "【" 0 "】人間だって動物じゃないかよう。")
      (wait)
      (text #:color 6 "【くるみ】だから恐いの。")
      (wait)
      (text #:color 7 "【" 0 "】わかった・・・俺を動物だと思わなければいいんだ。")
      (wait)
      (text #:color 6 "【くるみ】じゃあ・・・何なの？")
      (wait)
      (set-reg: 13 1)))
    ((&& (== V 2) (== N 1) (== (: 14) 0))
     (<>
      (text #:color 6 "【くるみ】" 0 "さん、動物じゃなければ・・・何なの？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show
       (<.>
        (if (== (: 15) 0) (text "ゴミ"))
        (if (== (: 16) 0) (text "ぬいぐるみ"))
        (if (== (: 17) 0) (text "昆虫"))
        (if (== (: 18) 0) (text "肉のかたまり"))
        (if (== (: 19) 0) (text "悪魔くん"))))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】ゴミ・・・そう、ゴミだと思ってくれ。")
         (wait)
         (text #:color 6 "【くるみ】" 0 "さんって人間のクズなの？")
         (wait)
         (text #:color 7 "【" 0 "】おう、誰もそんな事は言ってないだろ？")
         (wait)
         (text #:color 6 "【くるみ】だって・・・自分でゴミって言うんだもん。")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】俺の事をぬいぐるみだと思ってくれ。")
         (wait)
         (text #:color 6 "【くるみ】ぬいぐるみ？")
         (wait)
         (text #:color 7 "【" 0 "】そう・・・かわいい、かわいい" 0 "ちゃん人形。")
         (wait)
         (text #:color 6 "【くるみ】" 0 "さんは、ぬいぐるみなのね・・・だったら恐くない。")
         (wait)
         (set-reg: 16 1)
         (set-reg: 14 1)))
       ((== N 3)
        (<>
         (text #:color 7 "【" 0 "】俺の事を人間だと思わずに、昆虫だと思ってくれ。")
         (wait)
         (text #:color 6 "【くるみ】やだ・・・私、虫っいて嫌いなの。")
         (wait)
         (text #:color 7 "【" 0 "】あ・・・そう。")
         (wait)
         (text #:color 6 "【くるみ】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】（どうでもいいけど・・・ものすごく、くだらない会話をしてないか？）")
         (wait)
         (set-reg: 17 1)))
       ((== N 4)
        (<>
         (text #:color 7 "【" 0 "】わかった、俺の事を肉のかたまりだと思ってくれ・・・動く肉のかたまり。")
         (wait)
         (text #:color 6 "【くるみ】・・・。")
         (wait)
         (text #:color 6 "【くるみ】気持ち悪い。")
         (wait)
         (text #:color 7 "【" 0 "】なんだよう・・・これでも一生懸命考えてるんだぞう。")
         (wait)
         (set-reg: 18 1)))
       ((== N 5)
        (<>
         (text #:color 7 "【" 0 "】わかった・・・俺の事を悪魔くんだと思ってくれ。")
         (wait)
         (text #:color 6 "【くるみ】悪魔って悪い人なんでしょ？")
         (wait)
         (text #:color 7 "【" 0 "】悪い『人』かどうかは知らないけど。")
         (wait)
         (text #:color 6 "【くるみ】いや・・・私、悪い人に大人にされたくない。")
         (wait)
         (text #:color 7 "【" 0 "】あ・・・そう。")
         (wait)
         (set-reg: 19 1)))
       (else (<>)))))
    ((&& (== V 2) (== N 1) (== (: 20) 0))
     (<>
      (text #:color 7 "【" 0 "】くるみちゃん・・・。")
      (wait)
      (text #:color 6 "【くるみ】" 0 "さん・・・優しくして。")
      (wait)
      (set-reg: 20 1)
      (set-arr~ @ 7 0)
      (load "17a.a6" 47104)))
    ((&& (== V 7) (== N 1))
     (<>
      (text #:color 7 "俺は立ちすくんでるくるみの肩を、そっと抱きよせた。")
      (wait)
      (slot 1 8)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "q03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q03an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q03.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (sound 1)
      (set-var I 44)
      (proc 26)
      (set-reg: 835 0)
      (text #:color 6 "【くるみ】いやあ・・・。")
      (wait)
      (text #:color 7 "かまわず俺は、彼女の唇に自分の唇を合わせる・・・。")
      (wait)
      (text #:color 6 "【くるみ】・・・。")
      (wait)
      (text #:color 7 "くるみの目は開いたままだ・・・どうもやりにくい。")
      (wait)
      (text #:color 6 "【くるみ】んんっ・・・ん。")
      (wait)
      (text #:color 7 "俺はくるみにキスしながら、手を彼女の胸にそっと・・・。")
      (wait)
      (text #:color 6 "【くるみ】いやあっ！！")
      (wait)
      (slot 1 8)
      (sound 1)
      (set-var I 37)
      (proc 26)
      (set-reg: 835 0)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "17.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 9)
      (set-arr~ @ 6 1)
      (image "q04.pd8")
      (proc 25)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q04an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q04.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (sound 1)
      (set-var I 23)
      (proc 26)
      (set-reg: 835 0)
      (text #:color 7 "・・・突き飛ばされてしまった。")
      (wait)
      (text #:color 6 "【くるみ】" 0 "さんの・・・エッチ。")
      (wait)
      (text #:color 7 "【" 0 "】エッチと言われても・・・大人の女性になりたいって言ったの、くるみちゃんじゃないかよう。")
      (wait)
      (text #:color 6 "【くるみ】だって・・・だって・・・。")
      (wait)
      (text #:color 7 "【" 0 "】わかったよ・・・。")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "帰ろう") (text "もう一度する")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】わかった・・・もう帰ろう。")
         (wait)
         (text #:color 6 "【くるみ】・・・。")
         (wait)
         (text #:color 6 "【くるみ】・・・いや。")
         (wait)
         (text #:color 7 "【" 0 "】（いやって事は、していいって事だよな？）")
         (wait)))
       ((== N 2) (<> (text #:color 7 "【" 0 "】なあ・・・いいじゃないかよう。") (wait)))
       (else (<>)))
      (slot 1 8)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "q03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q03an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q03.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (sound 1)
      (set-var I 44)
      (proc 26)
      (set-reg: 835 0)
      (text #:color 6 "【くるみ】あ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】くるみちゃん・・・いつかは経験する事なんだぜ。")
      (wait)
      (text #:color 6 "【くるみ】うん・・・。")
      (wait)
      (text #:color 7 "俺は再びくるみの唇に、自分の唇をかさねる。")
      (wait)
      (text #:color 6 "【くるみ】んっ・・・んんん。")
      (wait)
      (text #:color 7 "やはり目は開いたままだ・・・。")
      (wait)
      (text #:color 6 "【くるみ】ん・・・いや・・・。")
      (wait)
      (text #:color 7 "俺の手は、すでにくるみの胸の上だ・・・彼女の胸は固く、小さい感じがする。")
      (wait)
      (text #:color 6 "【くるみ】ん・・・はあ。")
      (wait)
      (text #:color 7 "俺ははっきり言って困ってる・・・胸をもみもみしただけで、彼女はまた俺の事を突き飛ばすのだろうか？")
      (wait)
      (text #:color 6 "【くるみ】ん・・・ん・・・。")
      (wait)
      (text #:color 7 "うーん・・・どうしよう。")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "乱心する") (text "普通に進める")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】うおーーーっ！！")
         (wait)
         (text #:color 6 "【くるみ】きゃっ！？・・・ど、どうしたの！？")
         (wait)
         (text #:color 7 "【" 0 "】見せろよう・・・見せてくれよう。")
         (wait)
         (text #:color 6 "【くるみ】いやっ！！")
         (wait)
         (slot 1 8)
         (sound 1)
         (set-var I 37)
         (proc 26)
         (set-reg: 835 0)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "17.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 9)
         (set-arr~ @ 6 1)
         (image "q04.pd8")
         (proc 25)
         (set-arr~ @ 7 0)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "q04an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "q04.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 23)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 7 "また・・・突き飛ばされてしまった。")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】くるみちゃん・・・。")
         (wait)
         (text #:color 6 "【くるみ】あ・・・いや、手を動かさないで。")
         (wait)
         (text #:color 7 "【" 0 "】くるみちゃん・・・。")
         (wait)
         (text #:color 6 "【くるみ】いやっ！！")
         (wait)
         (slot 1 8)
         (sound 1)
         (set-var I 37)
         (proc 26)
         (set-reg: 835 0)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "17.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 9)
         (set-arr~ @ 6 1)
         (image "q04.pd8")
         (proc 25)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "q04an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "q04.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 23)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 7 "また・・・突き飛ばされてしまった。")
         (wait)))
       (else (<>)))
      (text #:color 6 "【くるみ】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】もう・・・帰ろう。")
      (wait)
      (text #:color 6 "【くるみ】いや。")
      (wait)
      (text #:color 7 "【" 0 "】あのねえ・・・。")
      (wait)
      (text #:color 6 "【くるみ】だって・・・勝手に身体が動いちゃうの。")
      (wait)
      (text #:color 7 "【" 0 "】だからあ、もう帰ろうよ。")
      (wait)
      (text #:color 6 "【くるみ】絶対にいや・・・" 0 "さん、くるみの身体が動かないようにして。")
      (wait)
      (text #:color 7 "【" 0 "】いいよ、もう・・・帰ろうぜ。")
      (wait)
      (text #:color 6 "【くるみ】いやっ！！")
      (wait)
      (slot 1 8)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "q03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q03an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q03.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (sound 1)
      (set-var I 44)
      (proc 26)
      (set-reg: 835 0)
      (text #:color 7 "【" 0 "】くるみちゃん・・・。")
      (wait)
      (text #:color 6 "【くるみ】私・・・絶対に帰らない。")
      (wait)
      (text #:color 7 "【" 0 "】だったら俺を突き飛ばすなよ。")
      (wait)
      (text #:color 6 "【くるみ】手が、勝手に動いちゃうの・・・ごめんなさい。")
      (wait)
      (sound 1)
      (set-var I 5)
      (proc 26)
      (text #:color 6 "ピンポーン！！")
      (wait)
      (text #:color 7 "【" 0 "】え！？")
      (wait)
      (sound 1)
      (set-var I 5)
      (proc 26)
      (text #:color 6 "ピンポーン！！")
      (wait)
      (text #:color 7 "【" 0 "】だ、誰！？")
      (wait)
      (text #:color 2 "【おばさん】当ホテル自慢のサービス、『動く大人の玩具屋』の時間がやってまいりました、すけべ。")
      (wait)
      (text #:color 7 "【" 0 "】『動く大人の玩具屋』！？")
      (wait)
      (text #:color 6 "【くるみ】いや・・・恥ずかしい、" 0 "さん離れて。")
      (wait)
      (slot 1 8)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "17.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 9)
      (set-arr~ @ 6 1)
      (image "q04.pd8")
      (proc 25)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q04an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q04.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (sound 1)
      (set-var I 23)
      (proc 26)
      (set-reg: 835 0)
      (text #:color 7 "【" 0 "】おうおうおう、おばはん・・・邪魔するなよう。")
      (wait)
      (text #:color 2 "【おばさん】ひっひっひっ、すけべ・・・当ホテル自慢のアイテムを御用意しておりますが、すけべ。")
      (wait)
      (text #:color 7 "【" 0 "】はあ？")
      (wait)
      (text #:color 2 "【おばさん】ご入り用ですよね・・・すけべ？")
      (wait)
      (text #:color 7 "【" 0 "】いらないよ、しっしっしっ！！")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ちょっと待てよ・・・いったい何があるんだ？")
      (wait)
      (text #:color 2 "【おばさん】今日は『ロープ感謝デー』でごさいますから、各種ロープを取り揃えております。")
      (wait)
      (text #:color 7 "【" 0 "】（ロープがあれば・・・くるみちゃんに突き飛ばされなくて済むかな？）")
      (wait)
      (text #:color 2 "【おばさん】すけべ・・・こんなロープはいかかでしょう？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "普通のロープ") (text "銀のロープ") (text "黄金のロープ")))
      (cond
       ((== N 1)
        (<>
         (text #:color 2 "【おばさん】ひっひっひっ・・・普通のロープですね、２０００円になります、すけべ。")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 2 "【おばさん】ひっひっひっ、すけべ・・・銀のロープですか？")
         (wait)
         (text #:color 5 "【隣の部屋の客】おばちゃん、銀のロープをおくれ。")
         (wait)
         (text #:color 2 "【おばさん】毎度ありがとうございます、すけべ・・・５０００円になります。")
         (wait)
         (text #:color 1 "【隣の隣の部屋の客】おばちゃん、黄金のロープをおくれ。")
         (wait)
         (text #:color 2 "【おばさん】毎度ありがとうございます、すけべ・・・１００００円になります。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 2 "【おばさん】お客さん、すけべ・・・あいにくですが、普通のロープしか残っておりません。")
         (wait)
         (text #:color 7 "【" 0 "】おい。")
         (wait)
         (text #:color 2 "【おばさん】すけべ。")
         (wait)
         (text #:color 7 "【" 0 "】ちぇっ・・・じゃあ、普通のロープでいいや。")
         (wait)
         (text #:color 2 "【おばさん】ひっひっひっ・・・普通のロープですね、２０００円になります、すけべ。")
         (wait)))
       ((== N 3)
        (<>
         (text #:color 2 "【おばさん】ひっひっひっ、すけべ・・・黄金のロープですか？")
         (wait)
         (text #:color 5 "【隣の部屋の客】おばちゃん、黄金のロープをおくれ。")
         (wait)
         (text #:color 2 "【おばさん】毎度ありがとうございます、すけべ・・・１００００円になります。")
         (wait)
         (text #:color 1 "【隣の隣の部屋の客】おばちゃん、銀のロープをおくれ。")
         (wait)
         (text #:color 2 "【おばさん】毎度ありがとうございます、すけべ・・・５０００円になります。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 2 "【おばさん】お客さん、すけべ・・・あいにくですが、普通のロープしか残っておりません？")
         (wait)
         (text #:color 7 "【" 0 "】おい。")
         (wait)
         (text #:color 2 "【おばさん】すけべ。")
         (wait)
         (text #:color 7 "【" 0 "】ちぇっ・・・じゃあ、普通のロープでいいや。")
         (wait)
         (text #:color 2 "【おばさん】ひっひっひっ・・・普通のロープですね、２０００円になります、すけべ。")
         (wait)))
       (else (<>)))
      (text #:color 7 "【" 0 "】２０００円か・・・。")
      (wait)
      (if (< M 2000) (<> (text #:color 7 "【" 0 "】（げっ！！・・・足りないっ！！）") (wait)))
      (text #:color 2 "【おばさん】お支払い方法には色々とございます、すけべ・・・どのコースに致しますか？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show
       (<.>
        (if (> M 1999) (text "２０００円払う"))
        (text "２４時間進める")
        (text "評判を悪くする")))
      (cond
       ((== N 1)
        (<>
         (text #:color 2 "【おばさん】２０００円キャッシュでございますね、すけべ・・・毎度ありがとうございます。")
         (wait)
         (set-var M (- M 2000))
         (proc 11)
         (text #:color 2 "【おばさん】スケベ。")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 2 "【おばさん】おやめずらしい、貴重な時間を２４時間いただける訳ですね？・・・すけべ。")
         (wait)
         (text #:color 2 "【おばさん】きっちりいただきます、すけべ・・・ありがとうございました。")
         (wait)
         (set-var A 24)
         (proc 13)
         (proc 11)))
       ((== N 3)
        (<>
         (text
          #:color
          2
          "【おばさん】ひっひっひっ、あなたに対する評判を下げさせていただきます・・・誰が下がるかは後でのお楽しみ、すけべ。")
         (wait)
         (text #:color 2 "【おばさん】・・・すけべ。")
         (wait)
         (text #:color 2 "【おばさん】きっちり下げさせていただきました、すけべ・・・ありがとうございました。")
         (wait)
         (set-reg: 114 (- (: 114) 2))))
       (else (<>)))
      (text #:color 7 "【" 0 "】（よーし、ロープを使って・・・ひっひっひっ。）")
      (wait)
      (text #:color 2 "【おばさん】ひっひっひっ、すけべ。")
      (wait)
      (text #:color 7 "【" 0 "】おい、いつまでそこに立ってるんだよ。")
      (wait)
      (text #:color 2 "【おばさん】お邪魔しました・・・すけべ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 6 "【くるみ】" 0 "さん・・・もう行った？")
      (wait)
      (text #:color 7 "【" 0 "】ああ、もう平気だ。")
      (wait)
      (text #:color 6 "【くるみ】" 0 "さん・・・こっちに来て。")
      (wait)
      (slot 1 8)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "q03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q03an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q03.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (sound 1)
      (set-var I 44)
      (proc 26)
      (set-reg: 835 0)
      (text #:color 6 "【くるみ】キスは平気になったの・・・でも、胸とか触られるとだめ。")
      (wait)
      (text #:color 7 "【" 0 "】はっはっはっ！！俺はお師匠さんだぜ・・・俺にまかせればいい。")
      (wait)
      (text #:color 7 "俺は再びくるみにキスをする・・・今度こそ失敗しないぞ。")
      (wait)
      (text #:color 6 "【くるみ】ん・・・ん・・・。")
      (wait)
      (text #:color 7 "目をつぶれよ、目を。")
      (wait)
      (text #:color 6 "【くるみ】んん・・・い、いや・・・胸はだめ。")
      (wait)
      (text #:color 7 "俺は手に握っているロープを、さっそく利用させてもらう事にした。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kuro.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (text #:color 6 "【くるみ】きゃっ！！・・・" 0 "さん、何をするの！？")
      (wait)
      (text #:color 7 "【" 0 "】こうすれば・・・くるみちゃんは、俺を突き飛ばさなくて済む。")
      (wait)
      (text #:color 6 "【くるみ】あんっ・・・痛い。")
      (wait)
      (text #:color 7 "【" 0 "】こうして・・・こうやって、ぐるぐるぐる。")
      (wait)
      (text #:color 6 "【くるみ】こんな事・・・みんなしてるの？")
      (wait)
      (text #:color 7 "【" 0 "】当り前じゃないか、いわば儀式みたいなもんだな・・・１００人中、１００人はこういう事をするんだ。")
      (wait)
      (text #:color 6 "【くるみ】なんだ・・・みんなやってる事なのね。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "q10.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "q05.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q10an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q10.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 6 "【くるみ】" 0 "さん・・・ちょっと恐い。")
      (wait)
      (text #:color 7 "【" 0 "】平気だって、何度も言うようだけど、みんな同じ事をしてるんだから。")
      (wait)
      (text #:color 6 "【くるみ】・・・うん。")
      (wait)
      (text #:color 7 "なんて刺激的なんだ・・・俺は一瞬、夢を見てるような気になってくる。")
      (wait)
      (text
       #:color
       7
       "もしかしたら、これは夢なのかもしれない・・・俺は夢でない事を確認する為に、目の前にいる彼女を無性に触りたい衝動にかられる。")
      (wait)
      (text #:color 6 "【くるみ】いや・・・。")
      (wait)
      (text #:color 7 "くるみは少しおびえてるようだ・・・しかし、俺の愛があれば彼女は安心して俺に身をゆだねるだろう。")
      (wait)
      (text #:color 7 "俺は彼女に軽くくちづけし、そっと抱きしめる・・・彼女の心臓の鼓動が俺の身体に伝わっている。")
      (wait)
      (text #:color 6 "【くるみ】あ・・・。")
      (wait)
      (text #:color 7 "彼女は俺の腕の中で、身体を縮めるようなしぐさをする・・・ああ、なんてかわいいんだろう。")
      (wait)
      (text #:color 7 "俺は彼女の胸に手をおき、小さく感じるその胸を優しくもむ。")
      (wait)
      (text #:color 6 "【くるみ】く・・・あ。")
      (wait)
      (text #:color 7 "彼女は俺を突き飛ばさない・・・。")
      (wait)
      (text #:color 6 "【くるみ】い、いいの・・・続けて。")
      (wait)
      (text #:color 7 "俺は胸を愛撫しながら、彼女のスカートの中に手を伸ばし・・・くるみの大事な部分をそっと撫でる。")
      (wait)
      (text #:color 6 "【くるみ】あ・・・ん・・・いや。")
      (wait)
      (text #:color 7 "その部分は濡れていない・・・さらに俺は、指先を奥の方へと伸ばす。")
      (wait)
      (text #:color 6 "【くるみ】くうっ・・・ん。")
      (wait)
      (text #:color 7 "下着の上からとはいえ、彼女にとっては十分に刺激的のようだ。")
      (wait)
      (text #:color 6 "【くるみ】" 0 "・・・さん。")
      (wait)
      (text #:color 7 "かまわず指を動かす・・・もっと動かす・・・さらに動かす。")
      (wait)
      (text #:color 6 "【くるみ】んあ・・・あ・・・んっ。")
      (wait)
      (text #:color 7 "くるみの呼吸がだんだん荒くなってくる・・・彼女の目はうるみ、俺を見つめる視線はすでに子供ではない。")
      (wait)
      (text #:color 6 "【くるみ】" 0 "・・・さん、私の事・・・好き？")
      (wait)
      (text #:color 7 "得てして、こういう事を聞いてくるもんだ・・・俺は彼女の目を見たまま軽くうなづく。")
      (wait)
      (text #:color 6 "【くるみ】うれしい・・・。")
      (wait)
      (text #:color 7 "俺はスカートのジッパーを下げる・・・そしてスカートを一気にはぎ取った。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "q10.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "q08.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q10an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q10.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 6 "【くるみ】・・・恥ずかしい。")
      (wait)
      (text #:color 7 "彼女の肌は驚くほど白い・・・しかし、見た目には十分に大人の身体をしていた。")
      (wait)
      (text #:color 6 "【くるみ】見ないで・・・。")
      (wait)
      (text
       #:color
       7
       "見ないで、と言われて目をそむけられる程、俺は人間ができていない。俺は彼女の言葉を無視するかのように、じっと肢体を見つめる。")
      (wait)
      (text #:color 7 "そっとふとももに手を伸ばす・・・思ったよりも、ずっと暖かく柔らかい。")
      (wait)
      (text #:color 6 "【くるみ】あ・・・くすぐったいの。")
      (wait)
      (text
       #:color
       7
       "俺は膝まづくようにし、彼女のふとももに舌を這わせる・・・なめらかで白い肌はほんんのりとピンク色に染まってきたようだ。")
      (wait)
      (text #:color 6 "【くるみ】う・・・あん・・・あ・・・。")
      (wait)
      (text
       #:color
       7
       "舌先をふとももから、脚のつけ根の方へと這わす・・・彼女はその部分に進む事を予感したのか、身体をよじりかすかな抵抗をしようとする。")
      (wait)
      (text #:color 7 "俺は舌先を彼女の肌から離した・・・。")
      (wait)
      (text #:color 6 "【くるみ】" 0 "さん・・・いいの、続けて。")
      (wait)
      (text #:color 7 "俺は彼女の上着を脱がす事にした・・・彼女の下着姿がどんなにかわいいか、この目で見たくなったからだ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "q10.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "q09.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q10an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q10.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "ぎょっ！！・・・ずいぶんと大人っぽい下着だな。")
      (wait)
      (text #:color 6 "【くるみ】あんっ・・・いやいや。")
      (wait)
      (text #:color 7 "かわいい・・・かわいすぎる。")
      (wait)
      (text
       #:color
       7
       "彼女の身体を隠してるいる物体は、ふたつのピンク色をした布だけだ・・・これをはがせば、彼女は生まれたままの姿になる。")
      (wait)
      (text #:color 7 "俺はすぐにでも、そうしたい衝動にかられた・・・が、彼女の身体はそれを拒んでいるようだ。")
      (wait)
      (text #:color 6 "【くるみ】" 0 "さん・・・離れないで。")
      (wait)
      (text #:color 7 "くるみを抱きしめ、再びキスをする・・・右手は胸をやさしく触り、左では彼女の大事な部分に触れている。")
      (wait)
      (text #:color 6 "【くるみ】ん・・・ん・・・。")
      (wait)
      (text #:color 7 "彼女の声がだんだんと大きくなる・・・それと同調して、下着の上がじっとりと濡れてくる。")
      (wait)
      (text #:color 7 "俺は耳元で、いやらしい言葉をささやいた・・・彼女の頬は赤く染まる。")
      (wait)
      (text #:color 6 "【くるみ】いや・・・いやらしいの。")
      (wait)
      (text
       #:color
       7
       "彼女は完全に興奮している、俺の両手の感触がその事を物語っている・・・俺は下着に手を伸ばし、彼女を生まれたままの姿にする事にした。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "q10.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q10an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q10.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (sound 1)
      (set-var I 54)
      (proc 26)
      (set-reg: 835 0)
      (text #:color 6 "【くるみ】・・・。")
      (wait)
      (text #:color 7 "くるみは無言のまま、恥ずかしそうに身をよじる・・・俺は急にくるみの事がいとおしくなってきた。")
      (wait)
      (text #:color 6 "【くるみ】" 0 "さん・・・" 0 "さん・・・。")
      (wait)
      (text #:color 7 "俺が抱きしめると、くるみも俺の身体に自分の身体を寄せてくる・・・彼女の唇は俺の唇を求めているようだった。")
      (wait)
      (text #:color 6 "【くるみ】んんっ・・・ん・・・ん・・・。")
      (wait)
      (text #:color 6 "【くるみ】・・・。")
      (wait)
      (text #:color 7 "長いキスのあと、俺は初めてじかに・・・彼女の秘密の場所へ手を這わせた。")
      (wait)
      (text #:color 7 "・・・。")
      (wait)
      (text #:color 7 "濡れている・・・その部分からは、密があふれ出していた。")
      (wait)
      (text #:color 6 "【くるみ】ああっ・・・あ・・・いやあ。")
      (wait)
      (text
       #:color
       7
       "俺の指先は、彼女の部分の中心をまさぐっている・・・その部分に指先が当たるたびに、彼女の身体がびくびく反応する。")
      (wait)
      (text #:color 6 "【くるみ】" 0 "さん・・・私を・・・ベットに連れてって。")
      (wait)
      (text #:color 7 "ベットに連れてくって事は、ロープをほどかないといけない・・・また俺は突き飛ばされるのだろうか？")
      (wait)
      (text #:color 6 "【くるみ】" 0 "さん、また突き飛ばしちゃいそう・・・だからもっとぐるぐるに縛って。")
      (wait)
      (text #:color 7 "うーん、この子は完全に誤解してる・・・こんな事をしてたら、アブノーマルな女の子になってしまいそうだ。")
      (wait)
      (text #:color 7 "俺は彼女に正直に言う事にした・・・普通はこんな事はしないと。")
      (wait)
      (text #:color 6 "【くるみ】いいの・・・" 0 "さんがそうしたいのなら。")
      (wait)
      (text
       #:color
       7
       "別に俺の趣味じゃないが、突き飛ばされるのがいやなだけだ・・・でも、こんな事を言っても言い訳にしかならないだろう。")
      (wait)
      (text #:color 7 "俺は今日一日、変態に徹する事に決めた・・・どうせ変態になるなら、徹底的に変態になってやろう。")
      (wait)
      (text #:color 6 "【くるみ】" 0 "さん・・・縛って・・・私を。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kuro.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】よーし、ぐるぐるぐるぐる。")
      (wait)
      (text #:color 6 "【くるみ】あ・・・ん。")
      (wait)
      (text #:color 7 "【" 0 "】ぐるぐるぐる・・・きゅきゅきゅっ！！")
      (wait)
      (text #:color 6 "【くるみ】こんな事・・・どこで覚えるの？")
      (wait)
      (text #:color 7 "【" 0 "】俺も不思議だな・・・覚えたつもりはないけど、勝手に手が動くんだ。")
      (wait)
      (text #:color 7 "【" 0 "】うーん、もしかしたら俺はこの道に合ってるのかもしれない。")
      (wait)
      (text #:color 6 "【くるみ】あんっ・・・くい込むう。")
      (wait)
      (slot 1 8)
      (mes-jump "q06.mes")))
    ((&& (== V 1) (== N 2))
     (<> (text #:color 7 "【" 0 "】（くるみちゃんの身体は・・・震えているようだ。）") (wait)))
    ((&& (== V 1) (== N 20) (== (: 21) 0))
     (<>
      (text #:color 7 "【" 0 "】（ありがちなシャンデリアだな・・・ぱっとサイデリアじゃないぜ。）")
      (wait)
      (set-reg: 21 1)))
    ((&& (== V 1) (== N 20) (== (: 21) 1))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】（うーん、こういう場所じゃないと飾れない照明だな・・・一般家庭に存在してたら、その家の良識を疑うぜ。）")
      (wait)))
    ((&& (== V 1) (== N 21) (== (: 22) 0))
     (<>
      (text #:color 7 "【" 0 "】（ベットだぜ・・・俺とくるみちゃんは、ここで結ばれるんだ。）")
      (wait)
      (set-reg: 22 1)))
    ((&& (== V 1) (== N 21) (== (: 22) 1))
     (<> (text #:color 7 "【" 0 "】（寝る為のベットではなくて、する為のベットだ・・・。）") (wait)))
    ((&& (== V 1) (== N 22) (== (: 23) 0))
     (<>
      (text #:color 7 "【" 0 "】（こんな場所でテレビを見るなんて・・・時間の無駄だぜ。）")
      (wait)
      (set-reg: 23 1)))
    ((&& (== V 1) (== N 22) (== (: 23) 0))
     (<>
      (text #:color 7 "【" 0 "】（テレビだ・・・２チャンネルは見たいけど、今はくるみちゃんがいるから・・・見ない。）")
      (wait)))
    ((&& (== V 1) (== N 23) (== (: 24) 0))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】（ビデオデッキがあるぜ・・・最近はラブホテルのフロントで、ビデオレンタルをする所があるくらいだからな。）")
      (wait)
      (set-reg: 24 1)))
    ((&& (== V 1) (== N 23) (== (: 24) 1))
     (<> (text #:color 7 "【" 0 "】（ビデオデッキだ・・・俺は使わないぜ。）") (wait)))
    ((&& (== V 1) (== N 24) (== (: 25) 0))
     (<>
      (text #:color 7 "【" 0 "】（この柱はインテリアだな・・・なくたって、天井が落ちる事はないだろう。）")
      (wait)
      (set-reg: 25 1)))
    ((&& (== V 1) (== N 24) (== (: 25) 1))
     (<> (text #:color 7 "【" 0 "】（ギザキザの柱だ・・・。）") (wait)))
    ((&& (== V 1) (== N 25) (== (: 26) 0))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】（絵が飾ってある・・・この部屋に来た人間で、絵の前に立ってじっくり鑑賞するやつはいないだろう。）")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 1) (== N 25) (== (: 26) 1))
     (<> (text #:color 7 "【" 0 "】（誰にも鑑賞されない、寂しい絵だ・・・。）") (wait)))
    ((&& (== V 1) (== N 26) (== (: 27) 0))
     (<>
      (text #:color 7 "【" 0 "】（トイレか・・・あるいは、バスルームのドアだろう。）")
      (wait)
      (set-reg: 27 1)))
    ((&& (== V 1) (== N 26) (== (: 27) 1))
     (<> (text #:color 7 "【" 0 "】（俺に必要な部屋は、ここだけでいい・・・ドアを開ける必要はないぜ。）") (wait)))
    ((&& (== V 1) (== N 27) (== (: 28) 0))
     (<>
      (text #:color 7 "【" 0 "】（大きな鏡があるな・・・ラブホテルの必須アイテムだぜ。）")
      (wait)
      (set-reg: 28 1)))
    ((&& (== V 1) (== N 27) (== (: 28) 1))
     (<> (text #:color 7 "【" 0 "】（大きな鏡だ・・・割ったら怒られるぞ。）") (wait)))
    ((&& (== V 1) (== N 28) (== (: 29) 0))
     (<> (text #:color 7 "【" 0 "】（うーん・・・いかにもって感じだぜ。）") (wait) (set-reg: 29 1)))
    ((&& (== V 1) (== N 28) (== (: 29) 1))
     (<>
      (text #:color 7 "【" 0 "】（よくよく見ると狭い部屋だな・・・まあここで生活する訳じゃないし、誰も文句は言わないだろう。）")
      (wait)
      (set-reg: 29 2)))
    ((&& (== V 1) (== N 28) (== (: 29) 2))
     (<> (text #:color 7 "【" 0 "】（ここはラブホテルだぜ・・・くるみちゃんと一緒なんだ。）") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))