(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\。
  #\【
  #\】
  #\の
  #\っ
  #\る
  #\、
  #\夏
  #\子
  #\い
  #\て
  #\な
  #\う
  #\は
  #\だ
  #\ん
  #\に
  #\し
  #\を
  #\た
  #\く
  #\！
  #\あ
  #\が
  #\か
  #\俺
  #\女
  #\彼
  #\で
  #\そ
  #\よ
  #\と
  #\見
  #\れ
  #\君
  #\き
  #\け
  #\ま
  #\も
  #\ら
  #\め
  #\ち
  #\ゃ
  #\さ
  #\す
  #\こ
  #\？
  #\ー
  #\じ
  #\わ
  #\つ
  #\り
  #\分
  #\み
  #\ろ
  #\身
  #\体
  #\ゅ
  #\胸
  #\ょ
  #\中
  #\え
  #\上
  #\部
  #\事
  #\や
  #\私
  #\ぴ
  #\ふ
  #\動
  #\ン
  #\目
  #\触
  #\せ
  #\好
  #\ど
  #\ね
  #\言
  #\顔
  #\ば
  #\指
  #\一
  #\お
  #\後
  #\気
  #\乳
  #\手
  #\興
  #\奮
  #\今
  #\出
  #\我
  #\慢
  #\び
  #\当
  #\げ
  #\悔
  #\哉
  #\嘘
  #\キ
  #\ス
  #\熱
  #\嫌
  #\房
  #\下
  #\間
  #\腰
  #\ク
  #\美)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 9 (&& (~ @ 9) 65534))
 (set-arr~ @ 6 1)
 (image "j08.pd8")
 (set-arr~ @ 9 (// (~ @ 9) 1))
 (proc 24)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "j08an.pd8")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 0)
 (load "j08.s4" (~ @ 2))
 (animate 0 0 0)
 (animate 1 0)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "j08.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (set-reg: 331 0)
 (if (== (: 544) 1)
   (<>
    (text #:color 2 "【夏子】" 0 "君・・・見るだけよ。")
    (wait)
    (text #:color 7 "【" 0 "】（奇麗だあ・・・夏子さん。）")
    (wait)
    (text #:color 2 "【夏子】ち、ちょっと・・・目つきがますます危なくなってない？")
    (wait)
    (text #:color 7 "【" 0 "】平気・・・見るだけ。")
    (wait)))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (set-reg: 331 (+ (: 331) 1))
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<> (text "興奮する")))
      (cond
       ((&& (== N 1) (== (: 10) 0))
        (<>
         (text #:color 7 "【" 0 "】ふうふうふうふうふうっ・・・。")
         (wait)
         (text #:color 7 "【" 0 "】はあはあはあはあはあっ・・・。")
         (wait)
         (text #:color 7 "【" 0 "】うーん、興奮したな。")
         (wait)
         (set-reg: 10 1)))
       ((&& (== N 1) (== (: 10) 1))
        (<>
         (text #:color 7 "【" 0 "】はっはっはっはっはっ！！")
         (wait)
         (text #:color 2 "【夏子】" 0 "君、そんなに興奮しないで。")
         (wait)))
       (else (<>)))))
    ((&& (== V 7) (== N 1) (== (: 11) 0))
     (<>
      (text #:color 2 "【夏子】だめ・・・見るだけでしょ？")
      (wait)
      (text #:color 7 "【" 0 "】うん、見るだけ・・・ちゅっ！！")
      (wait)
      (text #:color 2 "【夏子】きゃっ！！・・・も、もう、嘘つきね。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 7) (== N 1) (== (: 11) 1))
     (<>
      (text #:color 2 "【夏子】" 0 "君・・・キスはだめよ。")
      (wait)
      (text #:color 7 "【" 0 "】うん、見るだけ・・・ちゅっ！！")
      (wait)
      (text #:color 2 "【夏子】んっ・・・み、見るだけって言ったじゃない。")
      (wait)))
    ((&& (== V 7) (== N 2) (== (: 12) 0))
     (<>
      (text #:color 2 "【夏子】きゃっ！！・・・顔にキスするなんて、約束が違うじゃない。")
      (wait)
      (text #:color 7 "【" 0 "】うん・・・見るだけ。")
      (wait)
      (text #:color 2 "【夏子】キスする事と、見る事は全然違うでしょう？")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 7) (== N 2) (== (: 12) 1))
     (<>
      (text #:color 2 "【夏子】" 0 "君・・・キスしちゃだめよ。")
      (wait)
      (text #:color 7 "【" 0 "】うん、見るだけ・・・ちゅっ！！")
      (wait)
      (text #:color 2 "【夏子】も、もう・・・" 0 "君の嘘つき。")
      (wait)))
    ((&& (== V 8) (== N 3) (== (: 13) 0))
     (<>
      (text #:color 2 "【夏子】あ・・・" 0 "君、髪に触っちゃだめよ。")
      (wait)
      (text #:color 7 "【" 0 "】うん、見るだけ・・・。")
      (wait)
      (text #:color 2 "【夏子】見るだけって、触ってるじゃない。")
      (wait)
      (set-reg: 13 1)))
    ((&& (== V 8) (== N 3) (== (: 13) 1))
     (<>
      (text #:color 2 "【夏子】だめだってば・・・胸を見るだけって約束したでしょ？")
      (wait)
      (text #:color 7 "【" 0 "】うん、約束した・・・さわさわさわっ！！")
      (wait)
      (text #:color 2 "【夏子】あ・・・いや。")
      (wait)))
    ((&& (== V 10) (== N 4) (== (: 14) 0))
     (<>
      (text #:color 2 "【夏子】な、なに・・・顔を近づけて。")
      (wait)
      (text #:color 7 "【" 0 "】夏子さん・・・。")
      (wait)
      (text #:color 2 "【夏子】あっ・・・だ、だめ・・・首をなめるなんて。")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 10) (== N 4) (== (: 14) 1))
     (<>
      (text #:color 2 "【夏子】あ・・ん・・・だめだったらあ。")
      (wait)
      (text #:color 7 "【" 0 "】ぺろぺろぺろ・・・ぺろ。")
      (wait)
      (text #:color 2 "【夏子】" 0 "君・・・嘘はいけないのよ・・・もう。")
      (wait)))
    ((&& (== V 6) (== N 5) (> (: 331) 14))
     (<>
      (text #:color 2 "【夏子】だ、だめ・・・ブラを取ったらだめっ！！")
      (wait)
      (text #:color 7 "【" 0 "】だって、胸を見せてくれるって言ったじゃないか。")
      (wait)
      (text #:color 2 "【夏子】見せてるじゃない・・・" 0 "君だって、嘘をついたんだから。")
      (wait)
      (text #:color 7 "【" 0 "】夏子さんの身体・・・熱くなってる。")
      (wait)
      (text #:color 2 "【夏子】あたりまえよ、" 0 "君が色々とするから・・・ね、もうよしましょ？")
      (wait)
      (text #:color 7 "【" 0 "】胸を・・・見たい。")
      (wait)
      (text #:color 2 "【夏子】きゃあっ！！")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "j14.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "j13.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "j09.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "j14an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "j14.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 2 "【夏子】もう・・・強引なんだから。")
      (wait)
      (text #:color 7 "【" 0 "】胸だ・・・夏子さんの、うっうっうっうっ。")
      (wait)
      (text #:color 2 "【夏子】な、なによ・・・泣く事はないじゃない。")
      (wait)
      (text #:color 7 "【" 0 "】だって、見たかったんだよう。")
      (wait)
      (text #:color 2 "【夏子】・・・。")
      (wait)
      (text #:color 2 "【夏子】" 0 "君・・・そんなに私の事が好き？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "好き") (text "嫌い") (text "身体が好き")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】好きだ・・・。")
         (wait)
         (text #:color 2 "【夏子】" 0 "君・・・。")
         (wait)
         (set-reg: 109 (+ (: 109) 1))))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】嫌いだ・・・。")
         (wait)
         (text #:color 2 "【夏子】そう・・・私の事、嫌いなのね。")
         (wait)
         (text #:color 7 "【" 0 "】嫌いになれれば、こんなに苦しまなくて済む・・・。")
         (wait)
         (text #:color 2 "【夏子】" 0 "君・・・。")
         (wait)
         (set-reg: 109 (+ (: 109) 2))))
       ((== N 3)
        (<>
         (text #:color 7 "【" 0 "】身体が好きなんだ・・・。")
         (wait)
         (text #:color 2 "【夏子】そう・・・私の身体だけが好きなのね。")
         (wait)
         (text #:color 7 "【" 0 "】そう言えば・・・自分が楽になる。")
         (wait)
         (text #:color 2 "【夏子】どうして？")
         (wait)
         (text #:color 7 "【" 0 "】夏子さんの心まで好きになるのが恐いんだ・・・こんなに素敵な人を好きになるなんて。")
         (wait)
         (text #:color 2 "【夏子】" 0 "君・・・。")
         (wait)))
       (else (<>)))
      (text #:color 7 "【" 0 "】夏子さん・・・。")
      (wait)
      (text #:color 2 "【夏子】今度こそ・・・見るだけよ。")
      (wait)
      (text #:color 7 "俺は夏子の胸を見る・・・じっくりと見る。")
      (wait)
      (text #:color 2 "【夏子】ちょっと・・・恥ずかしいわね。")
      (wait)
      (text #:color 7 "夏子の乳首は、触れてないのに立っているような気がする・・・彼女も興奮しているのだろうか？")
      (wait)
      (text #:color 7 "しかし、これほど奇麗な乳房を見た事があっただろうか・・・彼女の胸は呼吸と共に、かすかに上下している。")
      (wait)
      (text #:color 2 "【夏子】" 0 "君・・・。")
      (wait)
      (text #:color 7 "彼女の顔は微笑んでいるように見える・・・俺は、震える手で、そっと彼女の乳房に触れてみた。")
      (wait)
      (text #:color 2 "【夏子】あ・・・。")
      (wait)
      (text #:color 7 "彼女は抵抗するそぶりを見せない・・・それどころか、俺の顔を見て女神のような笑みを浮かべている。")
      (wait)
      (text
       #:color
       7
       "俺は心の奥から湧き出てくる衝動を押さえきれない・・・彼女の目を見つめたまま、俺はふたつの乳房の間に顔を埋めた。")
      (wait)
      (text #:color 2 "【夏子】" 0 "君・・・触っちゃだめ。")
      (wait)
      (text #:color 7 "と言いつつ、彼女の俺の行動を受け入れている・・・。")
      (wait)
      (text #:color 7 "彼女の両手は、優しく俺の頭を押さえる・・・暖かい肌に包まれ、俺の耳は彼女の鼓動を聞いている。")
      (wait)
      (text #:color 2 "【夏子】" 0 "君・・・私だって、我慢しているのよ。")
      (wait)
      (text #:color 7 "俺は頭を胸の谷間から起こし、両手で乳房に触れる・・・柔らかく、弾力がある胸は俺の手の中ではずんでいる。")
      (wait)
      (text #:color 2 "【夏子】ん・・・あ・・・。")
      (wait)
      (text #:color 7 "乳房の先は、夏子の興奮を示すように大きくなっている・・・俺は舌先で乳首をころがし、軽く歯を立ててみる。")
      (wait)
      (text #:color 2 "【夏子】あっ・・・いやっ・・・我慢してるんだからあ。")
      (wait)
      (text #:color 7 "彼女の身体がびくっと動く・・・くびれた腰が、艶めかしくよじれる。")
      (wait)
      (text #:color 7 "俺は彼女の肢体の上から身体を起こした・・・彼女の顔は、やはり女神ののように微笑んでいる。")
      (wait)
      (text
       #:color
       7
       "俺が目で合図をすると、彼女は微笑んだままコクンとうなづいた・・俺はジッパーを下ろし、彼女のジーンズを脱がした。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "j14.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "j13.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "j14an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "j14.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "彼女の身体は美しかった・・・こんなに奇麗な身体が目の前にあるなんて、俺はなんて幸運な男なんだろう。")
      (wait)
      (text #:color 2 "【夏子】" 0 "君・・・私、我慢できなくなってきた。")
      (wait)
      (text #:color 7 "彼女の身体は熱くほてっている・・・プールで見た、あの美しい肢体が俺の身体の真下にある。")
      (wait)
      (text #:color 7 "俺は自分の興奮する物を取り出した・・・貧血になるかと心配したくなるほど、血液が充満しているようだ。")
      (wait)
      (text #:color 2 "【夏子】あ・・・私のふとももに当たってる。")
      (wait)
      (text #:color 7 "彼女は俺の物をまさぐる・・・白く細い指は、俺の一番敏感な部分を知っているようだった。")
      (wait)
      (text #:color 2 "【夏子】" 0 "君・・・こっちに来て。")
      (wait)
      (text #:color 7 "彼女はやおら立ち上がると、俺の股間に顔を近づける・・・そして濡れた瞳で俺の事を見上げた。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "j07.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "j07an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "j07.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 2 "【夏子】" 0 "君・・・こういうの嫌い？")
      (wait)
      (text #:color 7 "彼女はそう言うと、おれの固くなったものを口にふくませる・・・俺はたまらず目を閉じた。")
      (wait)
      (text #:color 7 "彼女の水着姿が目に浮かぶ・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "j03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "j03an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "j03.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "ああ・・・あの夏子さんが、俺のものを愛してくれてる。")
      (wait)
      (text #:color 7 "彼女は俺のものを深く頬ばったようだ・・・そして、また口から離し、そしてまた深く頬ばる。")
      (wait)
      (text "・・・。")
      (wait)
      (text "・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "j07.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "j07an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "j07.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 2 "【夏子】" 0 "君・・・欲しい。")
      (wait)
      (text #:color 7 "彼女の顔は上気している・・・俺は彼女をベットに寝かすと、最後の一枚を乱暴にはがした。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "j14.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "j14an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "j14.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (sound 1)
      (set-var I 55)
      (proc 26)
      (set-reg: 835 0)
      (text #:color 7 "俺は彼女の唇、首筋、胸とキスを繰り返す。")
      (wait)
      (text #:color 2 "【夏子】あっ・・・感じる・・・感じるわ。")
      (wait)
      (text #:color 7 "ちくびを口に含みながら、俺の手は彼女の濡れた部分をまさぐった。")
      (wait)
      (text #:color 2 "【夏子】あんっ・・・ん。")
      (wait)
      (text
       #:color
       7
       "その部分は、俺の指を吸い込みそうなくらい濡れている・・・ちょっと力を入れて触ると、指の付け根まで彼女の中に引き込まれてしまう。")
      (wait)
      (text #:color 2 "【夏子】んんっ・・・そ、そんなに・・・触らないで。")
      (wait)
      (text #:color 7 "俺はその花弁の中で、小さく突起している部分をさぐり当てた・・・その部分を指でつまみ、軽くころがしてみる。")
      (wait)
      (text #:color 2 "【夏子】くっ・・・ん・・・。")
      (wait)
      (text #:color 7 "彼女の上半身が弓のようにそる・・・胸がこぼれそうなくらいに揺れている。")
      (wait)
      (text #:color 7 "なおも俺は指でころがす・・・彼女の中からは、熱い蜜があふれ出してくる。")
      (wait)
      (text #:color 2 "【夏子】きて・・・私の中に・・・もう我慢できない。")
      (wait)
      (text #:color 7 "俺はわざとじらすように、指を夏子の中にすべりこませる・・・彼女の内側を俺の指が刺激する。")
      (wait)
      (text #:color 2 "【夏子】いや・・・ち、違うの・・・" 0 "君の・・・ちょうだい。")
      (wait)
      (text
       #:color
       7
       "俺は指を彼女のその部分から離し、少しだけ乱暴に両脚の間に割って入った・・・そして彼女の片足を俺の肩に乗せるようにする。")
      (wait)
      (text #:color 2 "【夏子】あ・・・。")
      (wait)
      (text #:color 7 "彼女のその部分は毛深くない・・・ピンク色の合わさった部分が、妙に艶めかしい。")
      (wait)
      (text
       #:color
       7
       "俺は自分のものをつかむと、彼女のその部分に押し当てる・・・ピンク色の合わさる部分からは、熱い蜜がしたたり落ちる。")
      (wait)
      (text #:color 2 "【夏子】あっ・・・んっ・・・" 0 "君。")
      (wait)
      (text #:color 7 "彼女は身体を弓なりにそらす・・・その途端、俺の固くなったものは、彼女の中に飲み込まれていった。")
      (wait)
      (text #:color 7 "俺は彼女の両脚を持ち上げる・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "j10.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "j10an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "j10.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 2 "【夏子】あっ・・・いいっ・・・すごい。")
      (wait)
      (text #:color 7 "俺はゆっくりと腰を動かす・・・そのたびに、奥深くへと飲み込まれるようだ。")
      (wait)
      (text #:color 2 "【夏子】あっ・・・あっ・・・そんな奥まで・・・。")
      (wait)
      (text #:color 2 "【夏子】当たる・・・当たっちゃう・・・。")
      (wait)
      (text #:color 7 "腰の動きを早くする、彼女の胸がぶるぶると震える・・・俺は俺自身と彼女が結ばれてる部分を見た。")
      (wait)
      (text #:color 7 "彼女のそこは、完全に俺のものを受け入れてる・・・動くたびに、その部分はひくひくと動いている。")
      (wait)
      (text #:color 2 "【夏子】あんっ・・・あっ・・・もっと・・・きて。")
      (wait)
      (text #:color 7 "俺はさらに腰の動きを早くする・・・彼女のお尻を軽く持ち上げるようにして、下から突き上げた。")
      (wait)
      (text #:color 2 "【夏子】ああっ・・・いいっ・・・素敵よ、" 0 "君っ！！")
      (wait)
      (text #:color 7 "彼女が声を上げるたびに、身体は弓のようにそり・・・今にもベットから落ちてしまいそうだ。")
      (wait)
      (text #:color 2 "【夏子】んっ・・・んっ・・・もっと・・・突いて・・・奥まで・・・。")
      (wait)
      (text #:color 7 "俺の腰は、高回転エンジンのように早くなる・・・彼女の胸が波のように揺れている。")
      (wait)
      (text #:color 2 "【夏子】くるっ・・・くるの・・・だめえ・・・続けて・・・くる・・・きちゃう！！")
      (wait)
      (text #:color 7 "彼女の中が、だんだんときつくなってくる・・・俺のものは、彼女の中で締めつけられている。")
      (wait)
      (text #:color 2 "【夏子】んっ・・・あっ・・・んんっ・・・。")
      (wait)
      (text #:color 7 "彼女の手が俺の背中をつかむ・・・はっきり言って痛い。")
      (wait)
      (text #:color 2 "【夏子】あっっっ・・・くる・・・だめえっ！！")
      (wait)
      (text #:color 7 "彼女の表情が甘美に満ちてくる・・・あきらかに絶頂に達しそうな雰囲気だ。")
      (wait)
      (text #:color 7 "それと同時に、彼女の中で俺のものが締めつけられる・・・まるで生物でもいるようにビクビクと動いている。")
      (wait)
      (text #:color 2 "【夏子】んっんっんっ・・・くっ！！")
      (wait)
      (text #:color 7 "俺は我慢できなくなってきた・・・身体の中から熱いものがこみ上げてくる。")
      (wait)
      (text #:color 2 "【夏子】" 0 "君っ・・・中はだめ・・・外に出してえっっ！！")
      (wait)
      (text #:color 2 "【夏子】くっ・・・んん・・・っっっっっ！！")
      (wait)
      (text #:color 7 "だ、駄目だ・・・もう我慢できないぞうっ！！")
      (wait)
      (text #:color 2 "【夏子】" 0 "君ーーーーーーーーーーっ！！")
      (animate 0 8 1)
      (animate 4 8)
      (animate 0 8 1)
      (animate 4 8)
      (wait)
      (text #:color 7 "どぴゅっ！！")
      (wait)
      (text #:color 7 "どぴゅぴゅーーーーーっ！！")
      (wait)
      (text #:color 7 "ぴゅぴゅぴゅぴゅぴゅぴゅぴゅぴゅっ！！")
      (wait)
      (text #:color 7 "と、止まらない・・・。")
      (wait)
      (text "・・・。")
      (wait)
      (text "・・・。")
      (wait)
      (text #:color 7 "俺は彼女の胸の上に・・・たっぷりと放出した。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kuro.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (sound 1)
      (set-var I 29)
      (proc 26)
      (set-reg: 835 0)
      (set-var A 1)
      (proc 13)
      (proc 11)
      (text #:color 2 "【夏子】・・・" 0 "君。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 2 "【夏子】すごく・・・よかった。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 2 "【夏子】まさか、こんな事をしちゃうなんて・・・。")
      (wait)
      (text #:color 7 "【" 0 "】うん・・・。")
      (wait)
      (text #:color 2 "【夏子】" 0 "君は・・・後悔してる？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "後悔してる") (text "後悔してない")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】後悔してるさ・・・夏子さんとこんな関係になるなんて。")
         (wait)
         (text #:color 2 "【夏子】そうよね・・・後悔してるって言われても、仕方がないわ。")
         (wait)
         (text #:color 2 "【夏子】・・・。")
         (wait)
         (text #:color 2 "【夏子】ちょっとだけ・・・寂しいけど。")
         (wait)
         (set-reg: 109 (+ (: 109) 2))))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】後悔なんかするはずがない・・・俺は今、すごく幸せな気分だ。")
         (wait)
         (text #:color 2 "【夏子】本当に？")
         (wait)
         (text #:color 7 "【" 0 "】ああ、こんな事で嘘をつく訳がないじゃないか。")
         (wait)
         (text #:color 2 "【夏子】うれしい・・・。")
         (wait)
         (set-reg: 109 (+ (: 109) 5))))
       (else (<>)))
      (text #:color 7 "【" 0 "】夏子さん・・・俺達って、これからどうなるんだろう？")
      (wait)
      (text #:color 2 "【夏子】それは、" 0 "君次第よ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 2 "【夏子】でも、今はだめ・・・一哉君の事もあるし。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 2 "【夏子】" 0 "君・・・私達、今まで通りの関係の方がいいと思うの。")
      (wait)
      (text #:color 7 "【" 0 "】今まで通りの関係？")
      (wait)
      (text #:color 2 "【夏子】そう・・・しばらく時間がたって、まだ私の事が好きでいてくれたら・・・。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 2 "【夏子】その時は・・・ね、わかるでしょう？")
      (wait)
      (text #:color 7 "【" 0 "】わかった・・・。")
      (wait)
      (text #:color 2 "【夏子】お腹の具合は平気？")
      (wait)
      (text #:color 7 "【" 0 "】ははは・・・もう大丈夫さ。")
      (wait)
      (text #:color 2 "【夏子】マンションの出口まで送ると、その後が寂しくなるから・・・ここでお別れしましょう。")
      (wait)
      (text #:color 7 "【" 0 "】うん・・・。")
      (wait)
      (text #:color 2 "【夏子】気をつけて帰ってね・・・。")
      (wait)
      (text #:color 7 "【" 0 "】じゃあ・・・。")
      (wait)
      (text #:color 2 "【夏子】あ・・・" 0 "君。")
      (wait)
      (text #:color 7 "【" 0 "】なに？")
      (wait)
      (text #:color 2 "【夏子】・・・。")
      (wait)
      (text #:color 2 "【夏子】いいの・・・何でもないわ。")
      (wait)
      (slot 1 3)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "48.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (sound 1)
      (set-var I 50)
      (proc 26)
      (set-reg: 835 1)
      (text #:color 7 "【" 0 "】ふう・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "j12.pd8")
      (proc 16)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "jan.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "j.s4" (~ @ 2))
      (animate 0 0 1)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 5 "【一哉】あれれっ！？・・・" 0 "じゃないか！？")
      (wait)
      (text #:color 7 "【" 0 "】ぎょえーっ！？")
      (wait)
      (text #:color 5 "【一哉】こんな所で、何をやってるんだ？")
      (wait)
      (text #:color 7 "【" 0 "】さっき美穂ちゃんや美沙にプールで、泳いでたと思うがしかし、うーん、どう思う？")
      (wait)
      (text #:color 5 "【一哉】お前・・・文法がめちゃくちゃだぜ。")
      (wait)
      (text #:color 7 "【" 0 "】ははは、ようするにだな・・・ただ歩いてるだけさ。")
      (wait)
      (text #:color 5 "【一哉】暇なんだなあ、" 0 "は。")
      (wait)
      (text #:color 7 "【" 0 "】暇？・・・そう、俺は暇なんだ。")
      (wait)
      (text #:color 7 "【" 0 "】暇だから、家に帰ろーっと・・・じゃあな、一哉！！")
      (wait)
      (set-var N 18)
      (slot 1 3)
      (mes-jump "town1.mes")))
    ((&& (== V 6) (== N 5) (== (: 15) 0))
     (<>
      (text #:color 2 "【夏子】あっ！！・・・だ、駄目よっ！！")
      (wait)
      (text #:color 7 "【" 0 "】うん・・・わかってる。")
      (wait)
      (text #:color 2 "【夏子】わかってないじゃない、その手を離して・・・お願い。")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 6) (== N 5) (== (: 15) 1))
     (<>
      (text #:color 2 "【夏子】だめえ・・・見せるのはここまで。")
      (wait)
      (text #:color 7 "【" 0 "】うん、わかってる・・・。")
      (wait)
      (text #:color 2 "【夏子】全然わかってないわ・・・だめよ、ブラを取っちゃ。")
      (wait)))
    ((&& (== V 9) (== N 6) (== (: 16) 0))
     (<>
      (text #:color 2 "【夏子】き、きゃあ・・・" 0 "君、胸を触っちゃだめだってば！！")
      (wait)
      (text #:color 7 "【" 0 "】うん、見るだけ・・・。")
      (wait)
      (text #:color 2 "【夏子】あ・・・ん・・・だめよ、だめっ！！")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 9) (== N 6) (== (: 16) 1))
     (<>
      (text #:color 2 "【夏子】いや・・・" 0 "君、もうやめて。")
      (wait)
      (text #:color 7 "【" 0 "】うん、見るだけ・・・もみもみもみ。")
      (wait)
      (text #:color 2 "【夏子】あは・・・ん。")
      (wait)))
    ((&& (== V 10) (== N 7) (== (: 20) 0))
     (<>
      (text #:color 2 "【夏子】" 0 "君・・・なめないでよ。")
      (wait)
      (text #:color 7 "【" 0 "】うん・・・見るだけ。")
      (wait)
      (text #:color 2 "【夏子】あっ・・・見るだけって言って・・・なめてるじゃない。")
      (wait)
      (text #:color 7 "【" 0 "】うん・・・見るだけ。")
      (wait)
      (set-reg: 20 1)))
    ((&& (== V 10) (== N 7) (== (: 20) 1))
     (<>
      (text #:color 2 "【夏子】あっ・・・いやよ・・・やめて。")
      (wait)
      (text #:color 7 "【" 0 "】うん・・・見るだけ。")
      (wait)
      (text #:color 2 "【夏子】" 0 "君の目って、舌についてるの？・・・あっ・・・だめ。")
      (wait)))
    ((&& (== V 12) (== N 8) (== (: 21) 0))
     (<>
      (text #:color 2 "【夏子】" 0 "君っ！！ズボンは下ろさなくていいのっ！！")
      (wait)
      (text #:color 7 "【" 0 "】うん・・・見るだけ。")
      (wait)
      (text #:color 2 "【夏子】私が" 0 "君のを見るわけじゃないでしょ？・・・ちゃんとズボンをはきなさい。")
      (wait)
      (set-reg: 21 1)))
    ((&& (== V 12) (== N 8) (== (: 21) 1))
     (<>
      (text #:color 2 "【夏子】" 0 "君っ・・・み、見せないでよ！！")
      (wait)
      (text #:color 7 "【" 0 "】うん・・・見るだけ。")
      (wait)
      (text #:color 2 "【夏子】違うの・・・私は見なくていいのよ。")
      (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))