(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\い
  #\【
  #\】
  #\な
  #\。
  #\の
  #\だ
  #\っ
  #\は
  #\ん
  #\て
  #\、
  #\か
  #\う
  #\る
  #\に
  #\た
  #\こ
  #\し
  #\よ
  #\ら
  #\あ
  #\と
  #\が
  #\も
  #\ろ
  #\で
  #\ゃ
  #\？
  #\ま
  #\を
  #\く
  #\会
  #\ち
  #\れ
  #\さ
  #\み
  #\！
  #\や
  #\じ
  #\社
  #\事
  #\そ
  #\ど
  #\ひ
  #\え
  #\り
  #\す
  #\け
  #\ぞ
  #\俺
  #\見
  #\わ
  #\言
  #\つ
  #\人
  #\き
  #\日
  #\所
  #\ぜ
  #\時
  #\関
  #\係
  #\君
  #\ー
  #\二
  #\建
  #\姿
  #\他
  #\間
  #\健
  #\知
  #\『
  #\』
  #\行
  #\何
  #\生
  #\ね
  #\一
  #\ば
  #\お
  #\誰
  #\合
  #\中
  #\入
  #\め
  #\今
  #\私
  #\バ
  #\ン
  #\出
  #\前
  #\場
  #\上
  #\来
  #\思
  #\物
  #\美
  #\沙
  #\気
  #\せ
  #\ル
  #\ト
  #\女
  #\テ
  #\者)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "28.pd8")
 (proc 15)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "28.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (cond
  ((&& (== (: 406) 1) (== (: 411) 0))
   (<>
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】" 0 "、未練がましいぞ・・・ひろみちゃんがああ言った以上、もう会う事は不可能だ。")
    (wait)
    (text
     #:color
     7
     "【"
     0
     "】もうこの会社に来るのはよそう・・・ひろみちゃんに俺の姿を見られたら、めめしい男だと思われちゃうからな。")
    (wait)
    (set-reg: 411 1)))
  ((&& (== (: 405) 1) (== (: 424) 0) (> H 820))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "o.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "oan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "o.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 18)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 2 "【ひろみ】あ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "28.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】走って・・・行ってしまった。")
    (wait)
    (set-reg: 424 1)))
  ((&& (== (: 368) 0) (== (: 151) 1) (== (: 365) 1) (> T 900) (< T 2300))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【太郎】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】うわっと！！")
    (wait)
    (text #:color 5 "【太郎】そんなに驚く事はないだろう。")
    (wait)
    (text #:color 7 "【" 0 "】俺だからこの程度で済んだんだ・・・他のやつだったら、ショック死してるかもしれないぜ。")
    (wait)
    (text #:color 5 "【太郎】君は大げさだな・・・物事はありのままに伝えるのが、人間の真の姿だぞ。")
    (wait)
    (text #:color 7 "【" 0 "】なに、訳のわからない事を言ってるんだ・・・しっしっ！！")
    (wait)
    (text #:color 5 "【太郎】わかった、今日のところは帰ろう。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "28.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】何が今日のところはだよ・・・。")
    (wait)
    (set-reg: 368 1)))
  ((&& (== (: 369) 0) (== (: 239) 1) (> T 900) (< T 1800) (== (: 641) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "c.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "can.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "c.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 60)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・芹沢先生。")
    (wait)
    (text #:color 6 "【よしこ】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】芹沢先生？")
    (wait)
    (text #:color 6 "【よしこ】" 0 "君・・・いつからそこにいたの？")
    (wait)
    (text #:color 7 "【" 0 "】今からです。")
    (wait)
    (text #:color 6 "【よしこ】そう・・・先生、忙しいから・・・またね。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "28.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】芹沢先生、何か考え事をしてるようだったぞ・・・。")
    (wait)
    (set-reg: 369 1)))
  ((&& (== (: 370) 0) (== (: 223) 1) (> T 900) (< T 1800) (== (: 685) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "a.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "aan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "a.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】美沙じゃないか・・・くんくんくん。")
    (wait)
    (text #:color 3 "【美沙】な、なんだよ。")
    (wait)
    (text #:color 7 "【" 0 "】なんか、いい匂いがする・・・くんくんくん。")
    (wait)
    (text #:color 3 "【美沙】私は香水なんかつけないぞ。")
    (wait)
    (text #:color 7 "【" 0 "】ヤキソバの匂いかな？・・・それとも、ラーメンの匂いかな？")
    (wait)
    (sound 1)
    (set-var I 37)
    (proc 26)
    (text #:color 6 "ボカッ！！")
    (wait)
    (text #:color 3 "【美沙】" 0 "のバカっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "28.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】いてててて・・・美沙のやつ、本気で殴りやがった。")
    (wait)
    (set-reg: 370 1)))
  ((&& (== (: 371) 0) (== (: 250) 1) (> T 900) (< T 1800) (== (: 481) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "i.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ran.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "r.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】一哉・・・。")
    (wait)
    (text #:color 5 "【一哉】はあ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なんだよ、いきなりため息か？")
    (wait)
    (text #:color 5 "【一哉】ああ・・・俺のこの、燃えたぎるマグマは・・・いったいどこから吹き出せばいいんだあ。")
    (wait)
    (text #:color 7 "【" 0 "】お前・・・何言ってんだ？")
    (wait)
    (text #:color 5 "【一哉】酒池肉林の" 0 "には、わかる訳がないよ・・・はあ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "28.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】なんかあいつ・・・歩き方までヨロヨロしてるぜ。")
    (wait)
    (set-reg: 371 1)))
  ((&& (== (: 445) 1) (== (: 446) 0) (> T 800) (< T 2359) (== (: 765) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "b.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "man.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】なんだ・・・健二じゃないか。")
    (wait)
    (text #:color 4 "【健二】やっと僕の存在を認める気になったか。")
    (wait)
    (text #:color 7 "【" 0 "】誰の？")
    (wait)
    (text #:color 4 "【健二】僕のだ。")
    (wait)
    (text #:color 7 "【" 0 "】お前・・・誰だ？")
    (wait)
    (text #:color 4 "【健二】さっき健二って、僕の名前を言ったじゃないか！！")
    (wait)
    (text #:color 7 "【" 0 "】健二君て言うのか、俺は" 0 "だ。")
    (wait)
    (text #:color 4 "【健二】知ってる。")
    (wait)
    (text #:color 7 "【" 0 "】で、お前は誰だ？")
    (wait)
    (text #:color 4 "【健二】もういい・・・" 0 "につき合うほど、暇じゃなかったんだ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "28.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あいつって、歩く姿までキザっぽいな・・・小指を立てながら歩いてるぞ。")
    (wait)
    (set-reg: 446 1)))
  ((&& (== (: 403) 1) (== (: 565) 0) (> H 825) (> T 800) (< T 1800))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "o14.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "o14an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "o14.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】げっ！！")
    (wait)
    (text #:color 4 "【冬彦】なんだよう・・・どうして君がここにいるんだよう。")
    (wait)
    (text #:color 7 "【" 0 "】はあ・・・どうしてこいつと会っちまうんだ？")
    (wait)
    (text #:color 4 "【冬彦】そんなに喜ぶなよう・・・。")
    (wait)
    (text #:color 7 "【" 0 "】これが喜んでいる顔か！？")
    (wait)
    (text #:color 4 "【冬彦】君は素直じゃないだけだよう・・・本当はうれしいはずだよう。")
    (wait)
    (text #:color 7 "【" 0 "】しっしっしっ・・・あっちに行けっ！！")
    (wait)
    (text #:color 4 "【冬彦】わかったよう・・・でも、ひろみちゃんは僕のものだからなあ。")
    (wait)
    (text #:color 7 "【" 0 "】いいんだよ、そんな事はどうでも・・・しっしっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "28.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ぞぞっ！！・・・どこかに隠れて、俺の事を見てるような気がする。")
    (wait)
    (set-reg: 565 1)))
  ((&& (== (: 467) 1) (== (: 844) 0) (> H 823) (> T 800) (< T 2359))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "nan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 6)
    (proc 26)
    (text #:color 3 "【ちはる】あ・・・" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】ちはるちゃん・・・また御飯を食べさせてくれよ。")
    (wait)
    (text #:color 3 "【ちはる】御飯を食べたあと、私も食べるんでしょう？")
    (wait)
    (text #:color 7 "【" 0 "】うん、どうしてバレたのかなあ。")
    (wait)
    (text #:color 3 "【ちはる】そんな事ばかりしてると、ズルズルいっちゃうわよ・・・私は" 0 "君を堕落させたくないから。")
    (wait)
    (text #:color 7 "【" 0 "】俺の事が嫌いなのか？")
    (wait)
    (text #:color 3 "【ちはる】そんな事はないわよ・・・私、" 0 "君の事が好きよ。")
    (wait)
    (text #:color 7 "【" 0 "】だったらいいじゃないかよう。")
    (wait)
    (text #:color 3 "【ちはる】あ、そろそろ行かないと・・・じゃあね" 0 "君！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "28.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】ちぇっ・・・走って言っちゃったよ。")
    (wait)
    (set-reg: 844 1)))
  ((&& (== (: 598) 1) (> H 822) (> T 1900) (== (: 616) 0) (== (: 617) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "uan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 59)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【やよい】あら・・・" 0 "さん。")
    (wait)
    (text #:color 7 "【" 0 "】やよいさん・・・デートしよう。")
    (wait)
    (text #:color 6 "【やよい】はあ？")
    (wait)
    (text #:color 7 "【" 0 "】だからあ、デートしようぜ。")
    (wait)
    (text #:color 6 "【やよい】デートって・・・誰と？")
    (wait)
    (text #:color 7 "【" 0 "】俺と。")
    (wait)
    (text #:color 6 "【やよい】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】わかった、じゃあ一緒にお茶しよう。")
    (wait)
    (text #:color 6 "【やよい】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】わかった・・・じゃあ、話をしよう。")
    (wait)
    (text #:color 6 "【やよい】してますけど。")
    (wait)
    (text #:color 7 "【" 0 "】だからね、そういう意味じゃなくてえ・・・。")
    (wait)
    (text #:color 6 "【やよい】私、そろそろ帰らないと・・・さようなら。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "28.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】なんだよ・・・俺の事が嫌いなのか？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "uan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 59)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ぎょっ！？")
    (wait)
    (text #:color 6 "【やよい】" 0 "さん、痛くなったら病院に来てくださいね・・・素人療法はよくないですから。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "28.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】嫌われてると言うより、単なる病人としか見てないな・・・ちくしょう。")
    (wait)
    (set-reg: 616 1)))
  ((&& (== (: 617) 1) (> H 825) (> T 1900) (== (: 628) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "uan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 59)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれえ・・・ここは病院じゃないよな。")
    (wait)
    (text #:color 6 "【やよい】" 0 "さん・・・変な所で会いますね。")
    (wait)
    (text #:color 7 "【" 0 "】まさか、転職したとか？")
    (wait)
    (text #:color 6 "【やよい】変な事を言わないでください・・・ここの会社に知り合いがいるだけです。")
    (wait)
    (text #:color 7 "【" 0 "】こんな時間に、知り合いと会ってるの？")
    (wait)
    (text #:color 6 "【やよい】残業してたみたいですよ・・・どんな職業でも、大変みたいですね。")
    (wait)
    (text #:color 7 "【" 0 "】まさか・・・知り合いって、ひろみさんじゃないだろうな。")
    (wait)
    (text #:color 6 "【やよい】ひろみさんって・・・誰ですか？")
    (wait)
    (text #:color 7 "【" 0 "】え！？・・・あ、ああ、この会社に働いてる女の人。")
    (wait)
    (text #:color 6 "【やよい】" 0 "さんって、女性の知り合いが多いんですね・・・それじゃあ、私は帰りますから。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "28.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あーあ・・・他の女の子の名前を出すなんて、俺も馬鹿だよなあ。")
    (wait)
    (set-reg: 628 1)))
  ((&& (> T 0) (< T 659))
   (<> (text #:color 7 "【" 0 "】こんな時間だ・・・人がいなくても不思議じゃないぞ。") (wait)))
  ((> T 1900) (<> (text #:color 7 "【" 0 "】こんな時間だ・・・人がいなくても不思議じゃないぞ。") (wait)))
  ((&& (== (: 265) 1) (== (: 270) 0) (== (: 411) 0) (== (: 405) 0))
   (<> (text #:color 7 "【" 0 "】ひろみさんはいないな・・・。") (wait) (set-reg: 270 1)))
  ((&& (== (: 152) 0) (== (: 411) 0) (== (: 405) 0))
   (<>
    (text #:color 7 "【" 0 "】うーん・・・見るからに『中小企業』って感じの会社だな。")
    (wait)
    (text #:color 7 "【" 0 "】人の気配がないが・・・バブルがはじけて倒産しちゃったとか？")
    (wait)
    (if (> T 1800)
      (<>
       (text #:color 7 "【" 0 "】・・・。")
       (wait)
       (text #:color 7 "【" 0 "】もっとも、午後６時を過ぎているから・・・人の気配がなくてもおかしい事はないな。")
       (wait)))
    (if (< T 830)
      (<>
       (text #:color 7 "【" 0 "】・・・。")
       (wait)
       (text #:color 7 "【" 0 "】こんな時間だから、みんな出勤していなくてもあたりまえか？")
       (wait)))
    (if (== E 0)
      (<>
       (text #:color 7 "【" 0 "】・・・。")
       (wait)
       (text #:color 7 "【" 0 "】今日は日曜日だった・・・ははは。")
       (wait)))
    (set-reg: 152 1)))
  ((&& (== (: 152) 1) (!= E 0) (== (: 411) 0) (== (: 405) 0))
   (<>
    (text #:color 7 "【" 0 "】うーん、誰もいないな・・・倒産したのかな？")
    (wait)
    (if (== (: 183) 1)
      (<>
       (text
        #:color
        7
        "【"
        0
        "】ひろみちゃんは、会社の中かな・・・勝手に入る事はできないし、放火でもすれば外に出て来るかもしれないぞ。")
       (wait)))))
  ((&& (== E 0) (== (: 411) 0) (== (: 405) 0))
   (<> (text #:color 7 "【" 0 "】今日は日曜日だからな・・・誰もいなくても、まったく不思議じゃないぞ。") (wait)))
  ((&& (== (: 152) 1) (== (: 411) 0) (== (: 405) 0))
   (<> (text #:color 7 "【" 0 "】ははは・・・また来てしまった。") (wait)))
  ((&& (== (: 405) 1) (== (: 411) 0))
   (<>
    (text #:color 7 "【" 0 "】ひろみちゃんが働いている会社だ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ひろみちゃんは・・・もう俺に会ってくれないだろう。")
    (wait)))
  ((== (: 411) 1)
   (<> (text #:color 7 "【" 0 "】" 0 "のばかばかばかっ・・・二度と来ないと誓ったのに。") (wait))))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "他の場所に行く") (text "中に入る") (text "やめる")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】ここにいても仕方がない・・・他の場所に行こうぜ。")
         (wait)
         (set-var N 4)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 2) (== E 0))
        (<>
         (text #:color 7 "【" 0 "】日曜日だからな・・・ビューティフルなＯＬと出会える可能性は皆無だ。")
         (wait)))
       ((&& (== N 2) (> T 1800))
        (<>
         (text #:color 7 "【" 0 "】もうこんな時間だぜ・・・会社は午後６時でおしまいだ。")
         (wait)
         (if-else (== (: 183) 1)
           (<>
            (text #:color 7 "【" 0 "】ひろみさんも、会社の中にいるはずがない・・・他の場所に行こうぜ。")
            (wait))
           (<>))))
       ((&& (== N 2) (< T 830))
        (<>
         (text #:color 7 "【" 0 "】この会社は何時から始まるんだろう・・・まだ営業してないみたいだな。")
         (wait)
         (if-else (&& (== (: 183) 1) (== (: 264) 0))
           (<>
            (text
             #:color
             7
             "【"
             0
             "】ひろみさんが出社するまで、ここで待つ・・・と言うほど親しい間柄じゃないな・・・他の場所に行くか。")
            (wait))
           (<>))))
       ((&& (== N 2) (== (: 265) 1) (== (: 264) 0) (== (: 273) 0))
        (<>
         (text #:color 7 "【" 0 "】ひろみさんに会いたい・・・勝手に中に入っちゃえ。")
         (wait)
         (text #:color 4 "【姿は見えないけど警備員】こらこら、勝手に入っちゃいけないよ。")
         (wait)
         (text #:color 7 "【" 0 "】俺はこの会社の関係者だぞ。")
         (wait)
         (text #:color 4 "【姿は見えないけど警備員】関係者って、どこの関係者なんだ？")
         (wait)
         (text #:color 7 "【" 0 "】ここで働いている『田町　ひろみ』って言う女性の関係者だ。")
         (wait)
         (text #:color 4 "【姿は見えないけど警備員】それだけじゃだめだ。")
         (wait)
         (text
          #:color
          7
          "【"
          0
          "】じゃあ、『ひろみさんがせっかくデートに誘ってくれたのに、断ってしまったバカなヤツという関係者』・・・というのはどうだ？")
         (wait)
         (text #:color 4 "【姿は見えないけど警備員】そういう話は会社じゃなくて、他の場所でやってくれ。")
         (wait)
         (set-reg: 273 1)))
       ((&& (== N 2) (== (: 273) 1))
        (<> (text #:color 7 "【" 0 "】入る事はできない・・・ちっ！！") (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】就職活動をするのはまだ早いぜ・・・今は夏休みを存分に楽しみたいんだ。")
         (wait)))
       ((== N 3)
        (<> (text #:color 7 "【" 0 "】まだここにいるのか？・・・いったい何をするつもりだ？") (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 1) (== (: 10) 0))
     (<>
      (text #:color 7 "【" 0 "】窓がいくつも並んでいる・・・")
      (wait)
      (text #:color 7 "【" 0 "】ちっ・・・一つぐらい、開いていてもいいんだけどな。")
      (wait)
      (set-reg: 10 1)))
    ((&& (== V 1) (== N 1) (== (: 10) 1))
     (<>
      (text #:color 7 "【" 0 "】窓だな・・・石でも投げて割ってやるか？")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)))
    ((&& (== V 1) (== N 2) (== (: 11) 0))
     (<> (text #:color 7 "【" 0 "】この会社の入口だ・・・人影はないぞ。") (wait) (set-reg: 11 1)))
    ((&& (== V 1) (== N 2) (== (: 11) 1))
     (<>
      (text #:color 7 "【" 0 "】この会社の入口だが・・・この建物の中は、いったいどんな感じなんだろう？")
      (wait)
      (if-else (&& (== (: 183) 1) (== (: 411) 0))
        (<> (text #:color 7 "【" 0 "】もう一度、ひろみさんに会えたら聞いてみるか・・・。") (wait))
        (<>))))
    ((&& (== V 1) (== N 3) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】塀と言うか・・・門と言うか・・・。")
      (wait)
      (text #:color 7 "【" 0 "】とにかく、道路と会社の敷地を隔てている『仕切り』だぜ。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 3) (== (: 12) 1))
     (<> (text #:color 7 "【" 0 "】幸運な事に、壁には何のいたずら描きもされていない。") (wait)))
    ((&& (== V 1) (== N 4) (== (: 155) 0))
     (<>
      (text #:color 7 "【" 0 "】『藤田制作所』と書かれている・・・ありがちな名前だな。")
      (wait)
      (if-else (&& (== (: 183) 1) (== (: 411) 0))
        (<>
         (text #:color 7 "【" 0 "】ひろみさんは、この会社で働いているのか・・・きっと退屈な毎日に違いない。")
         (wait))
        (<>))
      (set-reg: 155 1)))
    ((&& (== V 1) (== N 4) (== (: 155) 1) (== (: 13) 0))
     (<>
      (text #:color 7 "【" 0 "】この会社は『藤田製作所』という名称だ・・・俺様の人生には関係のない会社だろうな。")
      (wait)
      (if-else (&& (== (: 183) 1) (== (: 411) 0))
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】もし関係があるとすれば、ひろみさんだけだな・・・ああ、早く関係を結びたい。")
         (wait))
        (<>))
      (set-reg: 13 1)))
    ((&& (== V 1) (== N 4) (== (: 155) 1) (== (: 13) 1))
     (<>
      (text #:color 7 "【" 0 "】看板には『藤田製作所』と書かれているぞ・・・いったい何を造っている会社なんだ？")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】大人の玩具かな？")
      (wait)))
    ((&& (== V 1) (== N 5) (== (: 14) 0))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】屋上があるようだ・・・きっと、仕事でストレスがたまったやつらが、ダイビングをする為の場所だろう。")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 1) (== N 5) (== (: 14) 1))
     (<>
      (text #:color 7 "【" 0 "】きっとこの会社の屋上には、きちんとそろえられた靴と、遺書が置かれたままになっているに違いない。")
      (wait)))
    ((&& (== V 1) (== N 6) (== (: 15) 0))
     (<>
      (text #:color 7 "【" 0 "】自然を大切にしよう・・・なんて言うやつは、タバコを吸っちゃいけないし、車も乗っちゃいけないな。")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 1) (== N 6) (== (: 15) 1))
     (<>
      (text #:color 7 "【" 0 "】さわやかな緑が目にしみるぜ・・・まるで俺様に見られる為だけに生えている樹木だな。")
      (wait)))
    ((&& (== V 1) (== N 7) (== (: 16) 0) (== (: 183) 0))
     (<>
      (text #:color 7 "【" 0 "】あまり新しい建物には見えないが・・・きっと江戸時代にでも建てられたのだろう。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】いいんだよ、俺の人生には関係のない建物なんだから。")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 1) (== N 7) (== (: 183) 1) (== (: 16) 0) (== (: 411) 0))
     (<> (text #:color 7 "【" 0 "】ひろみさんの姿は見えない・・・ここにいても時間の無駄か？") (wait)))
    ((&& (== V 1) (== N 7) (== (: 16) 1))
     (<>
      (text #:color 7 "【" 0 "】この会社は３階建てだな・・・このあたりは住居地域だから、３階建て以上は建てられないんだ。")
      (wait)))
    ((&& (== V 1) (== N 8) (== (: 17) 0))
     (<>
      (text #:color 7 "【" 0 "】アンテナが立っている・・・衛星放送用のアンテナまであるぞ。")
      (wait)
      (text #:color 7 "【" 0 "】仕事をしながらテレビを見るなんざ、１０億万年早いぜ。")
      (wait)
      (set-reg: 17 0)))
    ((&& (== V 1) (== N 8) (== (: 17) 0))
     (<> (text #:color 7 "【" 0 "】サルとアンテナは、高い所に登りたがるもんだ・・・うん。") (wait)))
    ((&& (== V 1) (== N 9) (== (: 18) 0))
     (<>
      (text #:color 7 "【" 0 "】たぶん給水塔だろう・・・どうせタンクの中はサビだらけだ。")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 1) (== N 9) (== (: 18) 1))
     (<>
      (text #:color 7 "【" 0 "】東京の水は、どうしてこんなにまずいのか・・・それは、『おいしい水』を飲んだ経験があるからさ。")
      (wait)))
    ((&& (== V 1) (== N 10) (== (: 19) 0))
     (<>
      (text #:color 7 "【" 0 "】この建物は、この会社とは関係ないだろう・・・別にどうでもいい事だが。")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 1) (== N 10) (== (: 19) 1))
     (<>
      (text #:color 7 "【" 0 "】震度３でも倒壊しそうな家が建っている。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】はっはっはっ！！あそこの住人は、赤の他人の俺様にこんな事を言われているとは、夢にも思わないだろうな。")
      (wait)))
    ((&& (== V 1) (== N 11) (== (: 20) 0) (> T 2000) (< T 400))
     (<> (text #:color 7 "【" 0 "】空は暗い・・・だろ？") (wait)))
    ((&& (== V 1) (== N 11) (== (: 20) 0))
     (<>
      (text #:color 7 "【" 0 "】空を見上げると、鳥に糞をかけられるぞ・・・都会の鳥は、礼儀というものを知らないからな。")
      (wait)
      (set-reg: 20 1)))
    ((&& (== V 1) (== N 11) (== (: 20) 1))
     (<>
      (text #:color 7 "【" 0 "】素敵な女性と知り合えるのなら、空を見てやってもいいぞ。")
      (wait)
      (if-else (&& (== (: 183) 1) (== (: 411) 0))
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】空を見たから、ひろみさんと知り合えたのかな？")
         (wait))
        (<>))))
    (else (<>)))))
 (set-arr~ @ 7 1))