(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\。
  #\い
  #\な
  #\っ
  #\、
  #\ん
  #\て
  #\だ
  #\る
  #\の
  #\は
  #\う
  #\た
  #\あ
  #\か
  #\に
  #\よ
  #\し
  #\が
  #\と
  #\こ
  #\？
  #\で
  #\く
  #\ゃ
  #\ら
  #\み
  #\さ
  #\！
  #\を
  #\ち
  #\や
  #\も
  #\じ
  #\つ
  #\君
  #\ま
  #\そ
  #\れ
  #\事
  #\す
  #\り
  #\太
  #\郎
  #\ー
  #\ど
  #\え
  #\子
  #\お
  #\わ
  #\園
  #\ふ
  #\ね
  #\公
  #\ぶ
  #\言
  #\私
  #\け
  #\ぜ
  #\マ
  #\ろ
  #\き
  #\人
  #\俺
  #\二
  #\行
  #\ン
  #\健
  #\一
  #\め
  #\遊
  #\ロ
  #\何
  #\気
  #\出
  #\所
  #\夏
  #\タ
  #\ウ
  #\女
  #\ょ
  #\ト
  #\舞
  #\会
  #\今
  #\家
  #\聞
  #\イ
  #\大
  #\せ
  #\時
  #\ぞ
  #\げ
  #\来
  #\近
  #\び
  #\生
  #\誰
  #\間
  #\帰
  #\僕
  #\彼
  #\思
  #\達
  #\学
  #\ラ
  #\恋
  #\ス
  #\見
  #\住
  #\違
  #\ず
  #\歩
  #\哉
  #\楽
  #\ば
  #\（
  #\）
  #\コ
  #\対
  #\物
  #\入
  #\べ
  #\方
  #\痴)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "35.pd8")
 (proc 15)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "35.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (cond
  ((&& (== (: 156) 0) (< T 1800))
   (<>
    (text #:color 7 "【" 0 "】ここは、俺が住んでいるマンションの裏にある公園だ・・・今は誰も遊んでないようだな。")
    (wait)
    (if (< T 600)
      (<> (text #:color 7 "【" 0 "】ははは・・・こんな時間に遊んでいたら、逆に恐いぞ。") (wait)))))
  ((&& (== (: 156) 0) (> T 1800))
   (<>
    (text #:color 7 "【" 0 "】ここは、俺が住んでいるマンションの裏にある公園だ・・・今は誰も遊んでないようだな。")
    (wait)
    (text #:color 7 "【" 0 "】と言っても、こんな時間じゃあたりまえか・・・よい子はみんな家に帰っているな。")
    (wait)
    (set-reg: 156 1)))
  ((&& (== (: 710) 0) (== H 830) (> T 800) (< T 1900) (== (: 733) 0))
   (<>
    (text #:color 7 "【" 0 "】ふう・・・明日で夏休みも終りかあ。")
    (wait)
    (text #:color 5 "【男の声】" 0 "君。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】げっ！？・・・またマタロウか。")
    (wait)
    (text #:color 5 "【太郎】ふっふっふっ・・・今日は君に、僕の彼女を紹介しようと思ってな。")
    (wait)
    (text #:color 7 "【" 0 "】彼女！？・・・マタロウに！？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "f.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 2)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 27)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【美穂】こんにちは、" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】げえーーっ！？")
    (wait)
    (text #:color 5 "【太郎】まあそういう訳だ・・・これからもよろしく頼むよ、" 0 "君。")
    (wait)
    (text #:color 6 "【美穂】太郎君ったらね、私のあとをつけるほど好きなんだって・・・私の事が。")
    (wait)
    (text #:color 6 "【美穂】私、その事を聞いて感激しちゃったの。")
    (wait)
    (text #:color 7 "【" 0 "】ち、ちょっと違うような気が・・・する。")
    (wait)
    (text #:color 5 "【太郎】負け惜しみか、" 0 "君・・・ふっふっふっ。")
    (wait)
    (text #:color 6 "【美穂】じゃあね・・・私達、これからデートなの。")
    (wait)
    (text #:color 5 "【太郎】僕達はこれで失敬するよ・・・ふっふっふっ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】はあ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ふう・・・。")
    (wait)
    (text #:color 7 "【" 0 "】どうして・・・こうなるの？")
    (wait)
    (set-reg: 733 1)
    (set-reg: 102 (- (: 102) 5))))
  ((&& (== (: 753) 1) (== H 830) (> T 800) (< T 1900) (== (: 760) 0))
   (<>
    (slot 1 6)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "v14.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "v14an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "v14.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (animate 0 8 1)
    (animate 4 8)
    (sound 1)
    (set-var I 24)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・！？")
    (wait)
    (text #:color 4 "【健二】はーっはっはっはっはっ！！")
    (wait)
    (text #:color 3 "【舞】・・・。")
    (wait)
    (text #:color 4 "【健二】そういう事だよ、" 0 "君。")
    (wait)
    (text #:color 3 "【舞】・・・。")
    (wait)
    (text #:color 4 "【健二】そう、これでいいのさ！！")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 4 "【健二】何も言えないだろう、言葉などあるはずがないもんな、はーっはっはっはっ！！")
    (wait)
    (text #:color 3 "【舞】・・・。")
    (wait)
    (text #:color 4 "【健二】" 0 "君、もう舞に手を出すなよ・・・彼女は僕とつき合うと言ってくれたんだからな。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 4 "【健二】じゃあな、" 0 "君・・・ホテルに行こう、舞。")
    (wait)
    (text #:color 3 "【舞】はい・・・。")
    (wait)
    (slot 1 2)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なんで・・・こうなるの？")
    (wait)
    (set-reg: 760 1)
    (set-reg: 111 (- (: 111) 5))))
  ((&& (== (: 372) 0) (== (: 250) 1) (> T 800) (< T 1800) (== (: 481) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "r.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ran.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "r.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【くるみ】" 0 "さん！？")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・くるみちゃん。")
    (wait)
    (text #:color 6 "【くるみ】こんにちは、一人でお散歩？")
    (wait)
    (text #:color 7 "【" 0 "】散歩？・・・ははは、俺はジジイじゃないぜ。")
    (wait)
    (text
     #:color
     6
     "【くるみ】そうだ、このあいだ一哉君から聞いたんだけど・・・"
     0
     "さん、先負学園の校長室でカラオケ大会をやったって本当？")
    (wait)
    (text #:color 7 "【" 0 "】あれは楽しかったぜ・・・一哉も酒を飲んで暴れるし。")
    (wait)
    (text #:color 6 "【くるみ】いっけないんだ、未成年はお酒を飲んじゃいけないの。")
    (wait)
    (text #:color 7 "【" 0 "】おかげで、２週間学校に来なくていいって言われたけどね。")
    (wait)
    (text #:color 6 "【くるみ】変なの・・・悪いを事をして、お休みをもらえるの？")
    (wait)
    (text #:color 7 "【" 0 "】そうそう、先負学園って本当にいい学校だよ・・・本当は停学だけど。")
    (wait)
    (text #:color 6 "【くるみ】あ、いっけない・・・もう行かないと。")
    (wait)
    (text #:color 6 "【くるみ】" 0 "さん、お酒なんか飲んじゃだめ・・・じゃあバイバイ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】うーん、あんなにかわいい女の子が、どうして一哉の彼女なのか・・・いまだに理解できないぜ。")
    (wait)
    (set-reg: 372 1)))
  ((&& (== (: 373) 0) (== (: 296) 1) (> T 800) (< T 2100))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【太郎】おはよう、いや・・・こんにちは・・・いや、こんばんは、か？")
    (wait)
    (text #:color 7 "【" 0 "】（なんとなく、いやな予感がしたんだよ・・・。）")
    (wait)
    (text #:color 5 "【太郎】ぶつぶつぶつぶつ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あいかわらず病んでいるようだな、マタロウ。")
    (wait)
    (text #:color 5 "【太郎】ぶつぶつぶつぶつ・・・女の子なんて、勉強の邪魔だ。")
    (wait)
    (text #:color 7 "【" 0 "】だからあ、マタロウは恋をしてるんだって。")
    (wait)
    (text #:color 5 "【太郎】鯉？・・・『池などで飼う淡水魚、大形のウロコでおおわれ、口に二対のヒゲがある。』鑑賞用の魚類の事か？")
    (wait)
    (text #:color 7 "【" 0 "】鯉じゃなくて、恋だってば。")
    (wait)
    (text #:color 5 "【太郎】よ、よせ・・・恋なんて言葉は、僕は認めない。")
    (wait)
    (text #:color 7 "【" 0 "】恋。")
    (wait)
    (text #:color 5 "【太郎】やめてくれ・・・この言葉を口にするな。")
    (wait)
    (text #:color 7 "【" 0 "】恋。")
    (wait)
    (text #:color 5 "【太郎】よ、よせーーーっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】あらら・・・走って行っちゃったよ。")
    (wait)
    (set-reg: 373 1)))
  ((&& (== (: 458) 0) (== (: 324) 1) (> T 800) (< T 2300) (> H 817))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【太郎】やあ、" 0 "君・・・最近よく会うな。")
    (wait)
    (text #:color 7 "【" 0 "】どうでもいいけどさ、マタロウって情緒不安定じゃないか？")
    (wait)
    (text #:color 5 "【太郎】どうしてだ？")
    (wait)
    (text #:color 7 "【" 0 "】会うたびに雰囲気が違うぜ・・・妙に無口だったり、普段と同じだったり。")
    (wait)
    (text #:color 5 "【太郎】人間という生き物は、非常に多面的なんだ・・・だからこそ感情や知性が他の動物よりも優れている。")
    (wait)
    (text #:color 7 "【" 0 "】で、女の子の事はどうなったんだ？")
    (wait)
    (text #:color 5 "【太郎】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なあ・・・。")
    (wait)
    (text #:color 5 "【太郎】ぶつぶつぶつ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】おい・・・。")
    (wait)
    (text #:color 5 "【太郎】ああ・・・ふう・・・ぶつぶつぶつ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】あらら、フラフラと歩いて行ってしまった・・・いきなり自分の世界に入ってしまったのか？")
    (wait)
    (set-reg: 458 1)))
  ((&&
    (== (: 745) 1)
    (== (: 746) 0)
    (> H 824)
    (> T 800)
    (< T 1900)
    (== (: 753) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "w.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "wan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "w.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 24)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あらら・・・。")
    (wait)
    (text #:color 3 "【舞】" 0 "君・・・どうして来なかったの？")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・。")
    (wait)
    (text #:color 3 "【舞】私・・・楽しみにしてたのに。")
    (wait)
    (text #:color 7 "【" 0 "】ごめん。")
    (wait)
    (text #:color 3 "【舞】もういいの、" 0 "君の気持ちがわかったし・・・私も" 0 "君を嫌いになる努力をするわ。")
    (wait)
    (text #:color 7 "【" 0 "】そ、そんなあ・・・。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】どうしよう・・・。")
    (wait)
    (set-reg: 753 1)
    (set-reg: 111 (- (: 111) 1))))
  ((&& (== (: 419) 1) (== (: 426) 0) (> T 1000) (< T 1900) (> H 821))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれれ！？")
    (wait)
    (text #:color 6 "【さとみ】や、やだ・・・" 0 "じゃない。")
    (wait)
    (text #:color 6 "【さとみ】ちょっとマスターに頼まれて・・・買物ついでに散歩してるだけよ。")
    (wait)
    (text #:color 7 "【" 0 "】さとみ、俺は何も聞いてないぜ。")
    (wait)
    (text #:color 6 "【さとみ】そう？・・・そうよね、そうだったわね。")
    (wait)
    (text #:color 6 "【さとみ】さてと、いいかげんに戻らないと怒られちゃうわ・・・じゃあね、" 0 "。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】なんだ・・・変なやつだな。")
    (wait)
    (if (== (: 420) 1)
      (<> (text #:color 7 "【" 0 "】まさかさとみのやつ・・・あの時の事を思い出してたんじゃないだろうな？") (wait)))
    (set-reg: 426 1)))
  ((&& (== (: 641) 1) (== (: 656) 0) (> T 800) (< T 2000) (> H 828))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "c.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "can.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "c.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 60)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【よしこ】こんにちは、" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】よしこ先生・・・なんだか楽しそうだなあ。")
    (wait)
    (text #:color 6 "【よしこ】私ね、最近お料理を習い始めたんですよ・・・この近所に教えてくれる所があって。")
    (wait)
    (text #:color 7 "【" 0 "】へえ・・・花嫁修行ってやつ？")
    (wait)
    (text #:color 6 "【よしこ】ふふふ、違います・・・御飯をしっかり食べさせてあげたい人がいるんです。")
    (wait)
    (text #:color 7 "【" 0 "】へえ、彼氏がいるんだ。")
    (wait)
    (text #:color 6 "【よしこ】彼氏じゃないですけど・・・お礼をしたい子がいますから。")
    (wait)
    (text #:color 7 "【" 0 "】ふーん・・・。")
    (wait)
    (text #:color 6 "【よしこ】あらやだ・・・そろそろ行かないと。")
    (wait)
    (text #:color 6 "【よしこ】" 0 "君、楽しみにしててくださいね・・・じゃあ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】なんだか、スキップしそうな雰囲気だな・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】楽しみにって・・・何をだ？")
    (wait)
    (set-reg: 656 1)))
  ((&&
    (== (: 729) 1)
    (> H 824)
    (> T 800)
    (< T 2200)
    (== (: 711) 0)
    (== (: 851) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】どわっ！！・・・マ、マタロウじゃないか。")
    (wait)
    (text #:color 5 "【太郎】くどいようだが・・・一つ聞きたい事があるんだ。")
    (wait)
    (set-reg: 101 1)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "答える") (text "断る")))
    (if (== N 1)
      (<> (text #:color 7 "【" 0 "】わかったよ、答えてやるから・・・今度こそちゃんと聞けよ。") (wait)))
    (if (== N 2)
      (<>
       (text #:color 7 "【" 0 "】しっしっしっ、マタロウと話してる暇はないっ！！")
       (wait)
       (text #:color 5 "【太郎】いいや、聞かせてくれたまえ・・・そうしないと、ますます勉強が手につかなくなる。")
       (wait)
       (text #:color 7 "【" 0 "】ちっ、わかったよ・・・いったい何が聞きたいんだ？")
       (wait)))
    (text #:color 5 "【太郎】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】早く言えよ・・・マロタウ。")
    (wait)
    (text #:color 5 "【太郎】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】おいおい、またかよ・・・。")
    (wait)
    (text #:color 5 "【太郎】" 0 "君、今は時期じゃないかもしれない・・・悪いが次の機会にしよう。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】うーん、病んでるぜ・・・絶対に。")
    (wait)
    (set-reg: 851 1)))
  ((&& (== (: 419) 1) (== (: 431) 0) (> T 1900) (< T 2359) (> H 826))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【さとみ】きゃあっ！！")
    (wait)
    (text #:color 7 "【" 0 "】さ、さとみ！？・・・びっくりさせるなよ！！")
    (wait)
    (text #:color 6 "【さとみ】びっくりしたのは私の方よ・・・痴漢かと思っちゃった。")
    (wait)
    (text
     #:color
     7
     "【"
     0
     "】こんな上品な顔をした痴漢がいるか？・・・だいたい、こんな時間に一人でいるさとみの方が、痴漢に会いたいと思ってるんじゃないか？")
    (wait)
    (text #:color 6 "【さとみ】馬鹿な事を言わないでよ、痴漢なんて絶対にいや。")
    (wait)
    (text #:color 7 "【" 0 "】だったらとっとと帰る事だな・・・このあたりは痴漢がよく出るんだ。")
    (wait)
    (text #:color 6 "【さとみ】" 0 "じゃないの？")
    (wait)
    (text #:color 7 "【" 0 "】ちっがーうっ！！")
    (wait)
    (text #:color 6 "【さとみ】あははは・・・冗談よ。")
    (wait)
    (text #:color 6 "【さとみ】さてと・・・" 0 "の言う事をきいて、そろそろ帰ろうかな。")
    (wait)
    (text
     #:color
     7
     "【"
     0
     "】その方がいい、こうして話をしてても・・・どこかの影からさとみの身体をなめるように見てるやつがいるかもしれない。")
    (wait)
    (text #:color 6 "【さとみ】ねえ・・・家まで送って。")
    (wait)
    (text #:color 7 "【" 0 "】（え！？・・・さとみのやつ、めずらしい事を言うな。）")
    (wait)
    (text #:color 6 "【さとみ】" 0 "が変な事を言うから、恐くなってきちゃった・・・。")
    (wait)
    (set-reg: 101 1)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "送らない") (text "送る")))
    (if (== N 1)
      (<>
       (text #:color 7 "【" 0 "】さとみらしくない事を言うなよ・・・一人で帰れるだろ？")
       (wait)
       (text #:color 6 "【さとみ】うん・・・わかった、一人で帰るからいいわよ。")
       (wait)
       (set-reg: 105 (- (: 105) 1))))
    (if (== N 2)
      (<>
       (text #:color 7 "【" 0 "】仕方がない・・・送ってやるか。")
       (wait)
       (text #:color 6 "【さとみ】ありがとう・・・" 0 "。")
       (set-reg: 431 1)
       (set-var N 5)
       (set-reg: 105 (+ (: 105) 1))
       (set-reg: 435 1)
       (slot 1 2)
       (mes-jump "town1.mes")))
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】ちょっと・・・冷たかったかな？")
    (wait)
    (set-reg: 431 1)))
  ((&& (== (: 467) 1) (== (: 841) 0) (> H 822) (> T 800) (< T 1900))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n.pd8")
    (proc 16)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 6)
    (proc 26)
    (text #:color 7 "【" 0 "】あ、ちはるちゃん・・・。")
    (wait)
    (text #:color 3 "【ちはる】あら・・・" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】公園で何をしてるんだ？")
    (wait)
    (text #:color 3 "【ちはる】うん・・・ちょっとね。")
    (wait)
    (text #:color 7 "【" 0 "】（何か気になるなあ・・・。）")
    (wait)
    (text #:color 3 "【ちはる】私、用があるから・・・じゃあね、" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】お、おい・・・。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】俺の事・・・避けてるのかなあ？")
    (wait)
    (set-reg: 841 1)))
  ((&& (== (: 479) 1) (== (: 841) 0) (> H 822) (> T 800) (< T 1900))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n.pd8")
    (proc 16)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 6)
    (proc 26)
    (text #:color 7 "【" 0 "】あ・・・ちはるちゃん。")
    (wait)
    (text #:color 3 "【ちはる】あ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あの・・・。")
    (wait)
    (text #:color 3 "【ちはる】さよなら。")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】あーあ・・・行っちゃった。")
    (wait)
    (set-reg: 841 1)))
  ((&&
    (== (: 488) 1)
    (== (: 491) 0)
    (> T 800)
    (< T 1900)
    (== (: 499) 0)
    (== (: 539) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "jan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 2 "【夏子】あら・・・" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】（夏子さんだ・・・公園で何をしてるんだろ？）")
    (wait)
    (text #:color 2 "【夏子】" 0 "君の家って、この近所なんでしょ？・・・一哉君から聞いた事があるわ。")
    (wait)
    (text #:color 7 "【" 0 "】わかったあ！！・・・夏子さんは、俺の家に来るつもりだったんでしょ？")
    (wait)
    (text #:color 2 "【夏子】残念でした・・・この近所に友達の家があって、そこにお邪魔してたのよ。")
    (wait)
    (text #:color 2 "【夏子】そしたら偶然に" 0 "君に会ったの・・・" 0 "君は公園で遊んでたの？")
    (wait)
    (text #:color 7 "【" 0 "】あのねえ・・・俺は１８歳だぜ。")
    (wait)
    (text #:color 2 "【夏子】いいじゃない、１８歳だって・・・私は大人になっても少年の心を持ってる男の人が好き。")
    (wait)
    (text #:color 7 "【" 0 "】今から・・・公園で遊ぼうかなあ。")
    (wait)
    (text #:color 2 "【夏子】ふふっ、私は帰るわよ・・・じゃあね、" 0 "君。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ちぇっ・・・いい歳をして、誰が公園なんかで遊ぶかよ。")
    (wait)
    (set-reg: 499 1)))
  ((&& (== (: 598) 1) (> H 821) (> T 1900) (== (: 614) 0) (== (: 617) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "uan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 59)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】（あれま、こんな所にやよいさんがいる・・・。）")
    (wait)
    (text #:color 6 "【やよい】あ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ははは、こんばんわ・・・公園で一人遊び？")
    (wait)
    (text #:color 6 "【やよい】違います。")
    (wait)
    (text #:color 7 "【" 0 "】まさか、やよいさんの家がこの近所だとか？")
    (wait)
    (text #:color 6 "【やよい】私は先負町に住んでません・・・。")
    (wait)
    (text #:color 7 "【" 0 "】じゃあ・・・俺の家に遊びに来たとか？")
    (wait)
    (text #:color 6 "【やよい】" 0 "さん、私はこれで失礼します・・・どうぞお大事に。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】お大事にって・・・行っちゃったよ。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・わかった。")
    (wait)
    (text #:color 7 "【" 0 "】トイレだな、きっと・・・漏らすよりは、公園のトイレを借りた方がマシだ。")
    (wait)
    (set-reg: 614 1)))
  ((&& (== (: 558) 1) (== (: 560) 0) (> H 819) (> T 800) (< T 1800))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "d.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "dan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "d.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 38)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 2 "【麗子】あ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】麗子・・・さん。")
    (wait)
    (text #:color 2 "【麗子】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 2 "【麗子】じゃあ・・・さようなら。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】何を話していいか・・・わからなかったな。")
    (wait)
    (set-reg: 560 1)))
  ((&& (== (: 603) 1) (> H 826) (> T 1900) (== (: 678) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "t.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "tan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "t.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 3)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (text #:color 2 "【亜子】" 0 "君・・・ここで会えるなんて、私達ってやっぱり恋人同士ね。")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・。")
    (wait)
    (text #:color 2 "【亜子】" 0 "君の事を考えてて、気がついたらここに来ていたの・・・。")
    (wait)
    (text #:color 2 "【亜子】ああ、最初にキスした時の事が・・・昨日のように思い出されるわ。")
    (wait)
    (text #:color 2 "【亜子】だめよ・・・だめ・・・そして、あの出来事。")
    (wait)
    (text #:color 2 "【亜子】身体が熱くなってくるの・・・ああっ・・・だめっ・・・いやあっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・行っちゃった。")
    (wait)
    (set-reg: 678 1)))
  ((&&
    (== (: 519) 1)
    (== (: 524) 0)
    (> H 828)
    (> T 800)
    (< T 2100)
    (== (: 527) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "q.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "qan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "q.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【くるみ】" 0 "さん！？")
    (wait)
    (text #:color 7 "【" 0 "】なんだよ・・・どうして驚くんだ？")
    (wait)
    (text #:color 6 "【くるみ】ううん・・・今ね、ちょうど" 0 "さんの事を考えてたの。")
    (wait)
    (text #:color 7 "【" 0 "】俺の事を？")
    (wait)
    (text #:color 6 "【くるみ】うん・・・本物が目の前に出できたから、ちょっとびっくりしちゃった。")
    (wait)
    (text #:color 7 "【" 0 "】出てきたって、俺はオバケじゃないぜ。")
    (wait)
    (text #:color 6 "【くるみ】ねえ・・・" 0 "さん？")
    (wait)
    (text #:color 7 "【" 0 "】な、なんだよ・・・最近のくるみちゃんの目って、前と違うような気がするぜ。")
    (wait)
    (text #:color 6 "【くるみ】くすくすくす・・・私も大人になったの。")
    (wait)
    (text #:color 7 "【" 0 "】大人にねえ。")
    (wait)
    (text #:color 6 "【くるみ】この間ね・・・一哉君から電話があったみたい。")
    (wait)
    (text #:color 7 "【" 0 "】へえ・・・よかったじゃないか。")
    (wait)
    (text #:color 6 "【くるみ】でも、私・・・居留守使っちゃった。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 6 "【くるみ】くすくすくす・・・じゃあね、" 0 "さん。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】くるみちゃんが小悪魔的な女の子になったら・・・泣く男がぞろぞろ出てくる気がするぜ。")
    (wait)
    (set-reg: 524 1)))
  ((&&
    (== (: 728) 1)
    (== (: 710) 1)
    (> H 827)
    (< H 829)
    (> T 800)
    (< T 2359)
    (== (: 736) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ぎょっ！？")
    (wait)
    (text #:color 5 "【太郎】君達は・・・君達は・・・不潔だあっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あーあ・・・ヨロヨロと走って行っちゃったよ。")
    (wait)
    (set-reg: 736 1)))
  ((&&
    (== (: 728) 1)
    (== (: 710) 0)
    (> H 827)
    (< H 829)
    (> T 800)
    (< T 2359)
    (== (: 736) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【太郎】" 0 "君、また会ってしまったね。")
    (wait)
    (text #:color 7 "【" 0 "】はあ・・・どうして会うんだろ？")
    (wait)
    (text #:color 5 "【太郎】ふっふっふっ・・・僕の勝ちだよ。")
    (wait)
    (text #:color 7 "【" 0 "】はあ？")
    (wait)
    (text #:color 5 "【太郎】まあ・・・いずれわかるだろう。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "35.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】なんだよ・・・もったいぶりやがって。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】いったい何が勝ったんだ？・・・さっぱりわからないぜ。")
    (wait)
    (set-reg: 736 1)))
  ((&& (== (: 156) 1) (== (: 310) 0))
   (<>
    (text #:color 7 "【" 0 "】童心にかえって、ブランコにでも乗るか？")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】よそうぜ、恥ずかしい。")
    (wait)))
  ((== (: 310) 1) (<> (text #:color 7 "【" 0 "】公園だな・・・誰もいないようだ。") (wait))))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "他の場所に行く") (text "中に入る") (text "やめる")))
      (cond
       ((&&
         (== N 1)
         (== (: 284) 1)
         (> H 810)
         (> T 900)
         (< T 1900)
         (== (: 285) 0)
         (== (: 598) 0))
        (<>
         (text #:color 7 "【" 0 "】そうだな、他の場所に行こうぜ・・・。")
         (wait)
         (sound 1)
         (set-var I 37)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 6 "ドスンッ！！")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "u.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "uan.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "u.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 59)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 6 "【奇麗な女性】あ・・・ごめんなさいね、じゃあ私は急ぎますから。")
         (wait)
         (text #:color 7 "【" 0 "】おーーーーーいっ！！")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "35.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)
         (text #:color 7 "【" 0 "】今度ぶつかって来たら、絶対に文句を言ってやるっ！！")
         (wait)
         (set-var N 5)
         (set-reg: 285 1)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&&
         (== N 1)
         (== (: 263) 1)
         (> T 900)
         (< T 1900)
         (== (: 298) 0)
         (== (: 419) 0)
         (== (: 765) 0))
        (<>
         (text #:color 7 "【" 0 "】そうだな、他の場所に行こうぜ・・・。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "b.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "man.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "m.s4" (~ @ 2))
         (animate 0 0 1)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 4 "【健二】やあ、" 0 "君・・・公園で一人遊びか？")
         (wait)
         (text #:color 7 "【" 0 "】・・・誰だ？")
         (wait)
         (text #:color 4 "【健二】ふざけるな・・・健二だよ、同級生の。")
         (wait)
         (text #:color 7 "【" 0 "】なんだよ、どうしてこんな所に健二がいるんだ！？")
         (wait)
         (text #:color 4 "【健二】はっはっはっ、僕だってたまには歩くさ・・・これからパパとママと食事をしに行くんだ。")
         (wait)
         (text #:color 7 "【" 0 "】へえ・・・公園で食べるんだな、家はでかいが食生活は貧しいんだな。")
         (wait)
         (text #:color 4 "【健二】はっはっはっ、貧乏人に何を言われても、まったく腹が立たないな・・・じゃあな、貧乏人！！")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "35.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】けっこう暇なやつだよな・・・健二も。")
         (wait)
         (set-var N 5)
         (set-reg: 298 1)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・俺様のようなアダルトが、公園に用がある訳がないじゃないか。")
         (wait)
         (set-var N 5)
         (set-reg: 156 1)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((== N 2)
        (<> (text #:color 7 "【" 0 "】誰もいないぜ・・・しげみの中に入って、『おなにい』でもするのか？") (wait)))
       ((== N 3)
        (<> (text #:color 7 "【" 0 "】やめるって事は・・・ここに呆然と立ち尽くすって事だな。") (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 1) (== (: 10) 0) (== (: 156) 0))
     (<> (text #:color 7 "【" 0 "】いかにも公園の柵って感じだな・・。") (wait) (set-reg: 10 1)))
    ((&& (== V 1) (== N 1) (== (: 10) 1) (== (: 156) 0))
     (<>
      (text #:color 7 "【" 0 "】なんだよ・・・文句あんのか？")
      (wait)
      (text #:color 7 "【" 0 "】と、公園の柵にケンカを売っている場合じゃないぞ。")
      (wait)))
    ((&& (== V 1) (== N 1) (== (: 156) 1) (== (: 10) 0))
     (<>
      (text #:color 7 "【" 0 "】公園の柵だぜ・・・こんな物を見ていても、幸せにはなれない。")
      (wait)
      (set-reg: 10 1)))
    ((&& (== V 1) (== N 1) (== (: 156) 1) (== (: 10) 1))
     (<> (text #:color 7 "【" 0 "】おいおい、何度も見るなよ・・・。") (wait)))
    ((&& (== V 1) (== N 2) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】ここは公園だ・・・樹木が生えていても、なんら不思議はない。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 1) (== N 2) (== (: 11) 1))
     (<> (text #:color 7 "【" 0 "】うーん、一度は公園のしげみの中で、エッチな事をしてみたいもんだ。") (wait)))
    ((&& (== V 1) (== N 3) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】ブランコだな・・・ミニスカートのおねーちゃんが乗っていたら、かぶりつきで見てやるぜ。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 3) (== (: 12) 1))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】あーあ、パンツをはいていないミニスカートのおねーちゃんが、どうしてブランコに乗ってないんだ、ちっ！！")
      (wait)))
    ((&& (== V 1) (== N 4) (== (: 13) 0))
     (<>
      (text #:color 7 "【" 0 "】すべり台だな・・・すべって遊ぶ道具だ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】受験生は、絶対に遊ばないだろうな・・・まあ、俺は関係ない事だが。")
      (wait)
      (set-reg: 13 1)))
    ((&& (== V 1) (== N 4) (== (: 13) 1))
     (<> (text #:color 7 "【" 0 "】すべり台だな・・・子供用だから、そんなに高さはないぞ。") (wait)))
    ((&& (== V 1) (== N 5) (== (: 14) 0))
     (<> (text #:color 7 "【" 0 "】巨大なてんとう虫みたいだな・・・。") (wait) (set-reg: 14 1)))
    ((&& (== V 1) (== N 5) (== (: 14) 1))
     (<>
      (text #:color 7 "【" 0 "】この中に出たり入ったり・・・うっ！！")
      (wait)
      (text #:color 7 "【" 0 "】出たり入ったりと言っただけで、欲情してしまった・・・欲求不満なのかなあ？")
      (wait)))
    ((&& (== V 1) (== N 6) (== (: 15) 0))
     (<>
      (text #:color 7 "【" 0 "】小学生の時、鉄棒でポコチンをからませて病院にかつぎ込まれたやつを知っているぞ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】俺じゃないってば。")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 1) (== N 6) (== (: 15) 1))
     (<> (text #:color 7 "【" 0 "】鉄棒だな・・・肉棒じゃない。") (wait)))
    ((&& (== V 1) (== N 7) (== (: 16) 0))
     (<>
      (text #:color 7 "【" 0 "】これはトイレだろう・・・俗に言う、公衆トイレってやつだ。")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 1) (== N 7) (== (: 16) 1))
     (<> (text #:color 7 "【" 0 "】公園にあるトイレには、紙がないんだ・・・葉っぱでふけって事かな？") (wait)))
    ((&& (== V 1) (== N 8) (== (: 17) 0))
     (<>
      (text #:color 7 "【" 0 "】公園の側は住宅街だ・・・俺が住んでいるマンションは見えないが。")
      (wait)
      (set-reg: 17 1)))
    ((&& (== V 1) (== N 8) (== (: 17) 1))
     (<> (text #:color 7 "【" 0 "】じっくり見るほどの景色じゃない・・・どこにでもあるような町並みだな。") (wait)))
    ((&& (== V 1) (== N 9) (< T 1759) (> T 559))
     (<> (text #:color 7 "【" 0 "】いい天気だ・・・気分がいいな。") (wait)))
    ((&& (== V 1) (== N 9))
     (<> (text #:color 7 "【" 0 "】空には星がまたたいている・・・。") (wait)))
    ((&& (== V 1) (== N 10) (< T 1759) (> T 559))
     (<> (text #:color 7 "【" 0 "】明るいから、街路灯はついていない。") (wait)))
    ((&& (== V 1) (== N 10))
     (<> (text #:color 7 "【" 0 "】街路灯が、ぼんやりと公園を照らしている。") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))