(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\い
  #\な
  #\。
  #\、
  #\だ
  #\て
  #\ん
  #\る
  #\の
  #\っ
  #\か
  #\う
  #\は
  #\た
  #\あ
  #\に
  #\と
  #\し
  #\？
  #\く
  #\も
  #\が
  #\れ
  #\こ
  #\で
  #\よ
  #\ゃ
  #\ち
  #\み
  #\ら
  #\や
  #\を
  #\さ
  #\そ
  #\一
  #\ろ
  #\じ
  #\ー
  #\わ
  #\す
  #\ぜ
  #\公
  #\園
  #\！
  #\え
  #\ど
  #\け
  #\お
  #\ま
  #\哉
  #\り
  #\子
  #\き
  #\事
  #\何
  #\俺
  #\人
  #\来
  #\女
  #\ね
  #\つ
  #\ト
  #\君
  #\ラ
  #\美
  #\デ
  #\見
  #\夏
  #\所
  #\せ
  #\場
  #\行
  #\誰
  #\ル
  #\フ
  #\ン
  #\ひ
  #\今
  #\言
  #\思
  #\健
  #\二
  #\ょ
  #\本
  #\ば
  #\合
  #\沙
  #\達
  #\入
  #\彼
  #\気
  #\待
  #\へ
  #\私
  #\日
  #\ツ
  #\ふ
  #\中
  #\友
  #\町
  #\変
  #\度
  #\ほ
  #\性
  #\話
  #\当
  #\め
  #\穂
  #\ミ
  #\口
  #\街)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "31.pd8")
 (proc 15)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "31.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (cond
  ((< M 300)
   (<>
    (text #:color 7 "【" 0 "】・・・あれ？")
    (wait)
    (text #:color 7 "【" 0 "】こんな所に３００円落ちてる・・・これで先負町に帰れるぞ。")
    (wait)
    (sound 1)
    (set-var I 58)
    (proc 26)
    (set-reg: 835 0)
    (set-var M (+ M 300))
    (proc 11)
    (text #:color 7 "【" 0 "】助かったあ・・・。")
    (wait)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)))
  ((&&
    (== (: 392) 0)
    (== (: 264) 1)
    (== (: 189) 1)
    (> T 1800)
    (< T 2300)
    (< H 817))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "o.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "oan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "o.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 18)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれれ！？")
    (wait)
    (text #:color 2 "【ひろみ】やだ・・・変な場所で会っちゃった。")
    (wait)
    (text #:color 7 "【" 0 "】約束は、確か今度の日曜日じゃなかった？")
    (wait)
    (text #:color 2 "【ひろみ】そうだけど・・・何となく来たくなっちゃって。")
    (wait)
    (text #:color 7 "【" 0 "】そうだ、デートを今日にするってのはどう？")
    (wait)
    (text #:color 2 "【ひろみ】駄目なの、これからね彼氏と会うのよ・・・ほら、彼って夜行性だって言ったでしょ？")
    (wait)
    (text #:color 7 "【" 0 "】コウモリみたいなヤツだな。")
    (wait)
    (text #:color 2 "【ひろみ】今日こそはっきり言おうと思って・・・その事を考えてて、気がついたらここに来てたって訳。")
    (wait)
    (text #:color 7 "【" 0 "】別れ話か・・・。")
    (wait)
    (text #:color 2 "【ひろみ】さて、そろそろ行こうかな・・・本当はあまり行きたくないんだけど。")
    (wait)
    (text #:color 2 "【ひろみ】" 0 "君、今度の日曜日の事、忘れないでね・・・１１時にここで待ってるわね。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "31.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】いやあ、色々とあるもんだ・・・出会いがあれば別れがある、か。")
    (wait)
    (set-reg: 392 1)))
  ((&& (== (: 393) 0) (== (: 261) 1) (== (: 189) 1) (> T 1200) (< T 2300))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "e.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ean.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "e.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 22)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【かおり】あら、" 0 "君じゃない・・・あなたもここでデートなの？")
    (wait)
    (text #:color 7 "【" 0 "】あなたもって事は、かおりさんはデートなんだ。")
    (wait)
    (text #:color 6 "【かおり】お客さんとだけどね・・・しつこく誘うから、たまにはつき合ってあげないと。")
    (wait)
    (text #:color 7 "【" 0 "】お客さんねえ・・・。")
    (wait)
    (text #:color 6 "【かおり】あ、来たみたい・・・" 0 "君と一緒のところを見られたら、誤解されちゃいそう。")
    (wait)
    (text #:color 6 "【かおり】" 0 "君ってけっこういい男だと思うわよ・・・じゃあね！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "31.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】げっ・・・ハデなスーツの男だな、かおりさんってあんなヤツが趣味なのか？")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】いい男だと思ってるなら、やらせてくれよ・・・みんなもそう思うだろ？")
    (wait)
    (set-reg: 393 1)))
  ((&&
    (== (: 394) 0)
    (== (: 150) 1)
    (== (: 189) 1)
    (> T 800)
    (< T 1700)
    (== (: 481) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "i.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ran.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "r.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 5 "【一哉】やあやあ、" 0 "君・・・デートかい？")
    (wait)
    (text #:color 7 "【" 0 "】残念ながら、そうじゃない・・・ただブラブラしてるだけさ。")
    (wait)
    (text #:color 5 "【一哉】俺はこれからデートなんだ・・・うらやましいだろ？")
    (wait)
    (text
     #:color
     7
     "【"
     0
     "】でも一哉は、くるみちゃん以外とデートができないだろ？・・・俺なんてやろうと思えば、その辺にいるねーちゃんとだってできるんだぜ。")
    (wait)
    (text #:color 5 "【一哉】誰もくるみだなんて言ってないぜ、へっへっへっ。")
    (wait)
    (text #:color 7 "【" 0 "】あ、言ってやろ。")
    (wait)
    (text #:color 5 "【一哉】いいよ、くるみは子供だからな・・・俺は大人のおつき合いができる女性が好きなんだ。")
    (wait)
    (text #:color 7 "【" 0 "】ふーん。")
    (wait)
    (text #:color 5 "【一哉】あ、彼女が来たみたいだ・・・" 0 "、後をつけるなよ。")
    (wait)
    (text #:color 7 "【" 0 "】誰がそんな事をするか。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "31.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】と、言いつつ・・・どんな女の子だろ？")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text
     #:color
     7
     "【"
     0
     "】ひどい、ひどすぎる・・・確かに大人の女性には見えるが、１００倍かわいくしても、くるみちゃんにはかなわないような女だ。")
    (wait)
    (set-reg: 394 1)))
  ((&&
    (== (: 395) 0)
    (== (: 260) 1)
    (== (: 189) 1)
    (> T 800)
    (< T 2000)
    (== (: 685) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "a.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "aan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "a.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 3 "【美沙】よう、" 0 "。")
    (wait)
    (text #:color 7 "【" 0 "】よう、スポーツ少女。")
    (wait)
    (text #:color 3 "【美沙】誰かと待ち合わせか？")
    (wait)
    (text #:color 7 "【" 0 "】いいや・・・美沙は？")
    (wait)
    (text #:color 3 "【美沙】へっへっ・・・これから男の子とデートなんだ。")
    (wait)
    (text #:color 7 "【" 0 "】どうせ親戚の子供とかだろ？")
    (wait)
    (text #:color 3 "【美沙】あれれ、どうしてわかったんだ？")
    (wait)
    (text #:color 7 "【" 0 "】俺様ぐらいレベルが高いとだな、女性の顔を見ただけで、これから何をするのかわかってしまうんだ。")
    (wait)
    (text #:color 3 "【美沙】へえ・・・それにしては、よくフラれてるじゃないか。")
    (wait)
    (text #:color 7 "【" 0 "】中にはわかりにくい女もいるんだよう。")
    (wait)
    (text #:color 3 "【美沙】あ、来たみたいだ・・・悪いな" 0 "、一人で立ってろ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "31.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】走るのが早いなあ・・・もしかして美沙は、ロボットじゃないのか？")
    (wait)
    (set-reg: 395 1)))
  ((&& (== (: 467) 1) (== (: 847) 0) (> H 826) (> T 800) (< T 1900))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n10.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "n10an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n10.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 6)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれれ・・・ちはるちゃん。")
    (wait)
    (text #:color 3 "【ちはる】" 0 "君・・・公園に何をしに来たの？")
    (wait)
    (text #:color 7 "【" 0 "】俺は・・・何をしに来たんだっけ？")
    (wait)
    (text #:color 3 "【ちはる】わかった、ナンパでしょ？")
    (wait)
    (text #:color 7 "【" 0 "】ちはるちゃんもナンパしに来たの？")
    (wait)
    (text #:color 3 "【ちはる】私はここで待ち合わせ・・・ナンパなんかするわけないじゃない。")
    (wait)
    (text #:color 7 "【" 0 "】いいよなあ、女はいつも受身でさ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】待ち合わせって・・・もしかしてデート？")
    (wait)
    (text #:color 3 "【ちはる】ふふふ・・・気になる？")
    (wait)
    (text #:color 7 "【" 0 "】ちょっと。")
    (wait)
    (text #:color 3 "【ちはる】あ、彼氏が来たみたい・・・じゃあね！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "31.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】彼氏！？・・・いったいどんなヤツだ！？")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】な、なんだ、女の子じゃないか・・・からかいやがったな、ちくしょー！！")
    (wait)
    (set-reg: 847 1)))
  ((&& (== (: 479) 1) (== (: 847) 0) (> H 826) (> T 800) (< T 1900))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "nan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 6)
    (proc 26)
    (text #:color 7 "【" 0 "】あ・・・ちはるちゃん。")
    (wait)
    (text #:color 3 "【ちはる】何よ・・・私に話しかけないで。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "31.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】なんだよ・・・名前を呼んだだけじゃないか。")
    (wait)
    (set-reg: 847 1)))
  ((&& (== (: 483) 1) (== (: 494) 0) (> T 800) (< T 2000))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j12.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j11.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】・・・一哉！？")
    (wait)
    (text #:color 5 "【一哉】び、びっくりしたあ・・・" 0 "じゃないか、脅かすなよ。")
    (wait)
    (text #:color 7 "【" 0 "】なんで驚くんだよ・・・後ろめたい事をやってたんじゃないか？")
    (wait)
    (text #:color 5 "【一哉】何もしてないぜ・・・ただ、ちょっとな。")
    (wait)
    (text #:color 7 "【" 0 "】なんだよ、顔がハングアップしてるぜ。")
    (wait)
    (text #:color 5 "【一哉】何でもないよ・・・俺は行くぜ、" 0 "。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "31.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】お、おい・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なんだよ一哉のやつ・・・ここで何をしてたんだ？")
    (wait)
    (set-reg: 494 1)))
  ((&&
    (== (: 718) 1)
    (> H 823)
    (> T 800)
    (< T 1900)
    (== (: 721) 0)
    (== (: 728) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "f.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 27)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【美穂】" 0 "君・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あ、美穂ちゃん・・・公園でデートかい？")
    (wait)
    (text #:color 6 "【美穂】" 0 "君以外の人と、そんな事をしたくないもの。")
    (wait)
    (text #:color 7 "【" 0 "】（な、なんてかわいい性格なんだ・・・。）")
    (wait)
    (text #:color 6 "【美穂】だ、だめえ、" 0 "君の顔を見てるだけで・・・涙が出ちゃう。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "31.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】おーいっ・・・美穂ちゃんっ！！")
    (wait)
    (text #:color 7 "【" 0 "】はあはあはあ・・・俺はどうすればいいんだあ！？")
    (wait)
    (set-reg: 721 1)))
  ((&&
    (== (: 519) 1)
    (== (: 525) 0)
    (> H 828)
    (> T 800)
    (< T 1900)
    (== (: 527) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "r.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ran.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "r.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれれ・・・くるみちゃん。")
    (wait)
    (text #:color 6 "【くるみ】あ・・・" 0 "さん。")
    (wait)
    (text #:color 7 "【" 0 "】まさか・・・一人で公園に来てたとか？")
    (wait)
    (text #:color 6 "【くるみ】やだ、違うわよ・・・お友達が失恋しちゃって、その相談にのってたの。")
    (wait)
    (text #:color 7 "【" 0 "】くるみちゃんが！？")
    (wait)
    (text #:color 6 "【くるみ】やだわあ、私だって色々な経験をしてるのよ・・・だから、少しでも参考になればいいなって思って。")
    (wait)
    (text #:color 7 "【" 0 "】ふーん・・・変わったな、くるみちゃん。")
    (wait)
    (text #:color 6 "【くるみ】でしょう？・・・自分でもそう思う。")
    (wait)
    (if (== (: 515) 1)
      (<>
       (text #:color 6 "【くるみ】・・・。")
       (wait)
       (text #:color 6 "【くるみ】やっぱり、変わったのって・・・あの時からかなあ。")
       (wait)
       (text #:color 7 "【" 0 "】え？")
       (wait)
       (text #:color 6 "【くるみ】" 0 "さんが、私にエッチな事をしてくれたでしょ？")
       (wait)
       (text #:color 7 "【" 0 "】ははは・・・は。")
       (wait)
       (text #:color 6 "【くるみ】" 0 "さん・・・あの後、誰かとエッチな事をした？")
       (wait)
       (text #:color 7 "【" 0 "】え！？")
       (wait)
       (text #:color 6 "【くるみ】ううん、何でもない・・・くすくすくす。")
       (wait)))
    (if (&& (== (: 514) 1) (== (: 515) 0))
      (<>
       (text #:color 6 "【くるみ】・・・。")
       (wait)
       (text #:color 6 "【くるみ】でも・・・あの時、" 0 "さんに抱かれてたら、もっと変わってたかもしれない。")
       (wait)
       (text #:color 7 "【" 0 "】ははは・・・は。")
       (wait)
       (text #:color 6 "【くるみ】今の私・・・もう一哉君の彼女じゃないのよ。")
       (wait)
       (text #:color 7 "【" 0 "】ああ・・・。")
       (wait)
       (text #:color 6 "【くるみ】私の事・・・今も抱きたくない？")
       (wait)
       (text #:color 7 "【" 0 "】え！？")
       (wait)
       (text #:color 6 "【くるみ】ううん、何でもないの・・・くすくすくす。")
       (wait)))
    (text #:color 7 "【" 0 "】（うーん・・・くるみちゃんは、小悪魔になってしまった。）")
    (wait)
    (text #:color 6 "【くるみ】さてと、お家に帰ろうかな・・・じゃあね、" 0 "さん！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "31.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】くるみちゃんは・・・行ってしまったな。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】短期間で、こうも変わってしまうのだろうか・・・うーん。")
    (wait)
    (set-reg: 525 1)))
  ((&&
    (== (: 528) 1)
    (== (: 534) 0)
    (> H 824)
    (> T 800)
    (< T 2300)
    (== (: 527) 0)
    (== (: 532) 0)
    (== (: 533) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j12.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j11.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】よう、一哉！！")
    (wait)
    (text #:color 5 "【一哉】なんだ・・・" 0 "か。")
    (wait)
    (text #:color 7 "【" 0 "】いやあ、フケたなあ・・・最近の一哉の顔は、仕事に疲れ切った中年のおぢさんみたいだぜ。")
    (wait)
    (text #:color 5 "【一哉】ははは、心労がたたって・・・最近疲れやすいんだ。")
    (wait)
    (text #:color 7 "【" 0 "】歩き方もなんだかフラフラしてるしな・・・死期がせまってるんじゃないか？")
    (wait)
    (text #:color 5 "【一哉】" 0 "・・・普通、友達だったら元気づけるもんだぜ。")
    (wait)
    (text #:color 7 "【" 0 "】人の不幸ほど楽しいものはない。")
    (wait)
    (text #:color 5 "【一哉】あーあ、どうしてこんなやつと友達なんだろ・・・じゃあな、お前と話してるとますます落ち込みそうだ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "31.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】フラフラとクラゲのように歩いてるな・・・情けない。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】一哉が死んだら線香の一本でもあげよう、うん。")
    (wait)
    (set-reg: 534 1)))
  ((&& (== (: 617) 1) (> H 828) (> T 1900) (== (: 631) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "uan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 59)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれ・・・やよいさん。")
    (wait)
    (text #:color 6 "【やよい】あら・・・。")
    (wait)
    (text #:color 7 "【" 0 "】まさか、デートじゃないよね？・・・デートだったら俺としよう。")
    (wait)
    (text #:color 6 "【やよい】それって・・・誘ってくれてるのかしら？")
    (wait)
    (text #:color 7 "【" 0 "】それ以外の何物でもない・・・誘っているのさ。")
    (wait)
    (text #:color 6 "【やよい】ごめんなさいね、友達と約束をしてますから。")
    (wait)
    (text #:color 7 "【" 0 "】本当かなあ。")
    (wait)
    (text #:color 6 "【やよい】あ・・・来たようだわ。")
    (wait)
    (text #:color 7 "【" 0 "】本当だ・・・女の子だな。")
    (wait)
    (text #:color 6 "【やよい】また今度、誘ってくださいね・・・さようなら、" 0 "さん。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "31.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】また今度か・・・いったい、いつになる事やら。")
    (wait)
    (set-reg: 631 1)))
  ((&&
    (== (: 539) 1)
    (== (: 547) 1)
    (> H 829)
    (> T 800)
    (< T 2000)
    (== (: 533) 0)
    (== (: 527) 0)
    (== (: 552) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j11.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 2 "【夏子】" 0 "君・・・公園で何をしてるの？")
    (wait)
    (text #:color 2 "【夏子】・・・。")
    (wait)
    (text #:color 2 "【夏子】もしかして、誰かと待ち合わせ？")
    (wait)
    (text #:color 7 "【" 0 "】やだなあ、夏子さんと待ち合わせしてたんじゃないか・・・さあ、行こうぜ。")
    (wait)
    (text #:color 2 "【夏子】あははは・・・私は他の人と待ち合わせ。")
    (wait)
    (text #:color 7 "【" 0 "】一哉と？")
    (wait)
    (text #:color 2 "【夏子】ううん、違うわよ・・・学校のお友達。")
    (wait)
    (text #:color 7 "【" 0 "】本当かなあ・・・。")
    (wait)
    (text #:color 2 "【夏子】ほら、噂をすれば何とかね・・・あそこにいる彼女がそう。")
    (wait)
    (text #:color 7 "【" 0 "】へえ、かわいい子だな。")
    (wait)
    (text #:color 2 "【夏子】もう、" 0 "君こそ浮気者じゃない・・・だめよ、浮気しちゃ。")
    (wait)
    (text #:color 7 "【" 0 "】夏子さんが、俺の事を相手にしてくれないからだよう。")
    (wait)
    (text #:color 2 "【夏子】あははは・・・今度ゆっくり話を聞くわ、じゃあね！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "31.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】うーん・・・夏子さんの友達もかわいいな。")
    (wait)
    (text #:color 7 "【" 0 "】でも、夏子さんと比べたら・・・月とミドリ亀ってところだな。")
    (wait)
    (set-reg: 552 1)))
  ((> T 1900)
   (<>
    (text #:color 7 "【" 0 "】夜の公園ってのも、なかなかいいもんだぜ・・・もっとも、俺一人で来ている事が一番の問題だが。")
    (wait)))
  ((&& (> T 0) (< T 500))
   (<> (text #:color 7 "【" 0 "】深夜の公園か・・・きっと恋人達であふれているだろう。") (wait)))
  ((== (: 189) 0)
   (<>
    (text #:color 7 "【" 0 "】ここは『矢吹町公園』だぜ・・・俺が住んでいるマンションの裏にある公園とは大きさが段違いだぜ。")
    (wait)))
  ((== (: 189) 1)
   (<> (text #:color 7 "【" 0 "】『矢吹町公園』だ・・・国定公園に指定されている。") (wait))))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "他の場所に行く") (text "中に入る") (text "やめる")))
      (cond
       ((&&
         (== N 1)
         (== (: 298) 1)
         (> T 900)
         (< T 1900)
         (== (: 299) 0)
         (== (: 419) 0)
         (== (: 765) 0))
        (<>
         (text #:color 7 "【" 0 "】そうだな、他の場所に行こうぜ・・・。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "b.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "man.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "m.s4" (~ @ 2))
         (animate 0 0 1)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 4 "【健二】やあ・・・" 0 "じゃないか。")
         (wait)
         (text #:color 7 "【" 0 "】・・・誰だ？")
         (wait)
         (text #:color 4 "【健二】いいかげんにしろ・・・健二だよ、同級生の。")
         (wait)
         (text #:color 7 "【" 0 "】公園にゴミでも拾いに来たのか？")
         (wait)
         (text #:color 4 "【健二】その言葉を、そのまま返すぜ・・・だいたい恋人達の憩いの場で、一人で何をしてるんだ・・・覗きか？")
         (wait)
         (text #:color 7 "【" 0 "】そういう健二だって一人じゃないか・・・さてはフラれたな、いい気味だぜ。")
         (wait)
         (text #:color 4 "【健二】はっはっはっ！！僕がフラれるなんて事は、地球の磁場がひっくり返ってもない事だ。")
         (wait)
         (text #:color 4 "【健二】" 0 "と話をしてると、僕のレベルが下がりそうだ・・・僕はこれで失礼するよ。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "31.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】健二のやつ・・・ここで何をしてたんだろ？")
         (wait)
         (set-var N 14)
         (set-reg: 299 1)
         (slot 1 3)
         (mes-jump "town1.mes")))
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】よし、他の場所に行こう・・・公園は女連れで来る場所だ。")
         (wait)
         (set-var N 14)
         (slot 1 3)
         (mes-jump "town1.mes")))
       ((&& (== N 2) (== (: 189) 0))
        (<>
         (text #:color 7 "【" 0 "】一人で公園を散歩するのか？・・・そんな事をしたら、いっぺんにフケちゃうぜ。")
         (wait)
         (set-reg: 189 1)))
       ((&& (== N 2) (== (: 189) 1))
        (<>
         (text #:color 7 "【" 0 "】やだよ、どうせ公園の中は恋人同士でいっぱいだ。")
         (wait)
         (text #:color 7 "【" 0 "】ああ、うらやましそうな目をして公園の中を一人歩く、自分の姿が目に浮かぶぜ。")
         (wait)))
       ((== N 3)
        (<>
         (text #:color 7 "【" 0 "】ここにずっといるのか？")
         (wait)
         (text #:color 7 "【" 0 "】俺も暇だよなあ・・・情けなくなってきた。")
         (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 1) (== (: 10) 0))
     (<>
      (text #:color 7 "【" 0 "】ポールが５本立っている・・・ようするに、車やバイクが中に乗り入れないようにするものだ。")
      (wait)
      (set-reg: 10 1)))
    ((&& (== V 1) (== N 1) (== (: 10) 1))
     (<> (text #:color 7 "【" 0 "】ステンレスでできたポールだ・・・ツルピカハゲマル君だな。") (wait)))
    ((&& (== V 1) (== N 2) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】入口の両側には植え込みがある・・・だからこそ、ここが入口だとわかるんだぜ。")
      (wait)
      (text #:color 7 "【" 0 "】うーん、哲学だな。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 1) (== N 2) (== (: 11) 1))
     (<>
      (text #:color 7 "【" 0 "】植え込みだな・・・お金は落ちてない。")
      (wait)
      (text #:color 7 "【" 0 "】え？・・・お金なんか捜してないって？")
      (wait)
      (text #:color 7 "【" 0 "】なんだ、本当は落ちてたんだけど・・・拾うのはよそう。")
      (wait)
      (set-reg: 11 2)))
    ((&& (== V 1) (== N 2) (== (: 11) 2))
     (<> (text #:color 7 "【" 0 "】植え込みを見ていると、カリフラワーを思い出すな・・・俺は大嫌いなんだ。") (wait)))
    ((&& (== V 1) (== N 3) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】燃えるゴミと燃えないゴミは、ちゃんと分けて捨てないとな・・・うんうん。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 3) (== (: 12) 1))
     (<> (text #:color 7 "【" 0 "】ゴミ入れだぜ・・・できればここに、健二を捨ててやりたい。") (wait)))
    ((&& (== V 1) (== N 4) (== (: 13) 0))
     (<>
      (text #:color 7 "【" 0 "】誰も座ってないな・・・もっとも、入口から見えるところでいちゃつかないか。")
      (wait)
      (set-reg: 13 1)))
    ((&& (== V 1) (== N 4) (== (: 13) 1))
     (<> (text #:color 7 "【" 0 "】ベンチには誰も座ってない・・・みんなどこに隠れているんだ？") (wait)))
    ((&& (== V 1) (== N 5) (== (: 14) 0))
     (<>
      (text #:color 7 "【" 0 "】公園の入口だ・・・地面には、四角いレンガが敷かれている。")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 1) (== N 5) (== (: 14) 1))
     (<>
      (text #:color 7 "【" 0 "】公園の入口だぜ・・・この場所に一人で来る事は、ラブホテルの次に寂しいものだな。")
      (wait)))
    ((&& (== V 1) (== N 6) (== (: 15) 0))
     (<>
      (text #:color 7 "【" 0 "】小さな噴水だな・・・公園の規模と比べたら、ちょっとセコいんじゃないか？")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 1) (== N 6) (== (: 15) 1))
     (<>
      (text #:color 7 "【" 0 "】小さな噴水だ・・・。")
      (wait)
      (if-else (> T 1900)
        (<>
         (text #:color 7 "【" 0 "】夜になっても、噴水から水が出ている・・・こんな時間じゃ、誰も見てないと思うけどな。")
         (wait))
        (<>))))
    ((&& (== V 1) (== N 7) (== (: 16) 0))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】公園だから、緑がいっぱいだ・・・もし樹木が一本もない公園があったとしたら、俺はコウモンを見せてもいいぞ。")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 1) (== N 7) (== (: 16) 1))
     (<>
      (text #:color 7 "【" 0 "】緑と言っても女の名前じゃないぜ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】うーん、俺は誰に対して訴えているんだろう。")
      (wait)))
    ((&& (== V 1) (== N 8) (== (: 17) 0))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】左の奥に見える建物は、この公園の管理局だぜ・・・管理局と言っても、いったい何をやっているのやら？")
      (wait)
      (set-reg: 17 1)))
    ((&& (== V 1) (== N 8) (== (: 17) 1))
     (<> (text #:color 7 "【" 0 "】『矢吹町公園』の管理局だ・・・。") (wait)))
    ((&& (== V 1) (== N 9) (== (: 18) 0))
     (<>
      (text #:color 7 "【" 0 "】休憩所のような場所だろう・・・じじばばが集まりそうな所だな。")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 1) (== N 9) (== (: 18) 1))
     (<> (text #:color 7 "【" 0 "】屋根つきだぜ・・・塀に囲まれていたら、簡易ラブホテルと化すだろう。") (wait)))
    ((&& (== V 1) (== N 10) (> T 1800))
     (<> (text #:color 7 "【" 0 "】街灯がぼんやりと光っている・・・。") (wait)))
    ((&& (== V 1) (== N 10) (> T 0) (< T 500))
     (<>
      (text #:color 7 "【" 0 "】街灯には光がともっているな・・・その光を慕うようにして、虫が飛びかっているぜ。")
      (wait)))
    ((&& (== V 1) (== N 10) (== (: 19) 0))
     (<> (text #:color 7 "【" 0 "】街灯だな・・・。") (wait) (set-reg: 19 1)))
    ((&& (== V 1) (== N 10) (== (: 19) 1))
     (<> (text #:color 7 "【" 0 "】公園の街灯だ・・・。") (wait)))
    ((&& (== V 1) (== N 11) (== (: 20) 0))
     (<>
      (text #:color 7 "【" 0 "】遠くの方に、ビルが見えている・・・あれはどこの街だろう？")
      (wait)
      (set-reg: 20 1)))
    ((&& (== V 1) (== N 11) (== (: 20) 1))
     (<> (text #:color 7 "【" 0 "】ビルに霞がかかったように見える・・・よほど遠くにあるのだろうか？") (wait)))
    ((&& (== V 1) (== N 12) (> T 1900))
     (<> (text #:color 7 "【" 0 "】空には満天の星が・・・と言いたい所だが、ここは東京だ。") (wait)))
    ((&& (== V 1) (== N 12) (> T 0) (< T 500))
     (<> (text #:color 7 "【" 0 "】晴れているけど、星は数えるほどしか見えない・・・。") (wait)))
    ((&& (== V 1) (== N 12) (== (: 21) 0))
     (<>
      (text #:color 7 "【" 0 "】いい天気だな・・・空は俺の心のように澄んでいる。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (set-reg: 21 1)))
    ((&& (== V 1) (== N 12) (== (: 21) 1))
     (<> (text #:color 7 "【" 0 "】いいじゃないか、空なんて・・・首が疲れるだけだぜ。") (wait)))
    ((&& (== V 1) (== N 13) (== (: 22) 0))
     (<>
      (text #:color 7 "【" 0 "】ここは『矢吹町公園』だぜ・・・奥に行くと、ボート乗り場があるんだ。")
      (wait)
      (set-reg: 22 1)))
    ((&& (== V 1) (== N 13) (== (: 22) 1))
     (<> (text #:color 7 "【" 0 "】広い公園だなあ・・・。") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))