(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\。
  #\な
  #\い
  #\の
  #\、
  #\だ
  #\っ
  #\て
  #\ん
  #\に
  #\か
  #\は
  #\う
  #\あ
  #\る
  #\し
  #\よ
  #\？
  #\も
  #\ら
  #\を
  #\た
  #\子
  #\で
  #\く
  #\こ
  #\と
  #\れ
  #\ー
  #\が
  #\女
  #\！
  #\ゃ
  #\ま
  #\ち
  #\え
  #\り
  #\そ
  #\じ
  #\俺
  #\校
  #\す
  #\や
  #\さ
  #\つ
  #\わ
  #\美
  #\け
  #\先
  #\ぜ
  #\ね
  #\生
  #\ろ
  #\み
  #\学
  #\君
  #\ト
  #\真
  #\事
  #\せ
  #\前
  #\お
  #\ク
  #\出
  #\ッ
  #\ル
  #\何
  #\ラ
  #\中
  #\き
  #\時
  #\帰
  #\誰
  #\気
  #\言
  #\沙
  #\め
  #\一
  #\入
  #\上
  #\ふ
  #\ょ
  #\ば
  #\プ
  #\部
  #\今
  #\舞
  #\ス
  #\ポ
  #\目
  #\ン
  #\行
  #\穂
  #\走
  #\練
  #\習
  #\庭
  #\ど
  #\彼
  #\外
  #\輩
  #\ほ
  #\ぞ
  #\汗
  #\大
  #\人
  #\私
  #\太
  #\郎
  #\０
  #\イ
  #\げ
  #\陸
  #\見
  #\『
  #\』
  #\ブ
  #\男
  #\変
  #\手
  #\午
  #\ジ
  #\教
  #\ツ
  #\不)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (if (== (: 403) 1) (<> (set-reg: 404 1)))
 (if (== (: 692) 1) (<> (set-reg: 693 1)))
 (if (== (: 709) 1) (<> (set-reg: 712 1)))
 (if (== (: 785) 1) (<> (set-reg: 786 1)))
 (if (== (: 793) 1) (<> (set-reg: 794 1)))
 (if (== (: 799) 1) (<> (set-reg: 800 1)))
 (if (== (: 805) 1) (<> (set-reg: 806 1)))
 (if (== (: 811) 1) (<> (set-reg: 812 1)))
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "36.pd8")
 (proc 15)
 (if (&& (> T 829) (< T 1801))
   (<> (set-arr~ @ 6 1) (image "l01.pd8") (proc 16) (set-arr~ @ 7 0)))
 (if (== (: 835) 0)
   (<> (sound 1) (set-var I 50) (proc 26) (set-reg: 835 1) (set-reg: 836 0)))
 (set-arr~ @ 7 0)
 (load "36.a6" 47104)
 (if (&& (> T 829) (< T 1801)) (<> (set-arr~ @ 7 0) (load "36a.a6" 47104)))
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (cond
  ((< T 829) (<> (text #:color 7 "【" 0 "】誰もいない学校は気味が悪いな・・・。") (wait)))
  ((> T 1801) (<> (text #:color 7 "【" 0 "】誰もいない学校は気味が悪いな・・・。") (wait)))
  ((&& (== (: 154) 0) (< H 817))
   (<>
    (text #:color 7 "【" 0 "】げげげっ！！・・・夏休みだと言うのに、運動部の連中が練習しまくっているぞ。")
    (wait)
    (set-reg: 154 1)))
  ((&& (== (: 154) 1) (< H 817))
   (<>
    (text #:color 7 "【" 0 "】みんなスポーツに汗を流して、性欲を抑えているに違いない・・・うーん、なんて不健康なんだ。")
    (wait)))
  ((&& (> H 816) (== (: 409) 0))
   (<>
    (text #:color 7 "【" 0 "】ん？・・・また陸上部が練習を開始したようだ。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】美沙の姿が見えないな。")
    (wait)
    (set-reg: 409 1)))
  ((&& (== (: 641) 0) (> H 821) (> T 800) (< T 2100) (== (: 645) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "c.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "can.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "c.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 60)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【よしこ】" 0 "君、陸上部の練習を邪魔しちゃ駄目ですよ。")
    (wait)
    (text #:color 7 "【" 0 "】なんだよ・・・見てるだけじゃないか。")
    (wait)
    (text #:color 6 "【よしこ】" 0 "君の事ですからね・・・何をしても不思議じゃありません。")
    (wait)
    (text #:color 7 "【" 0 "】よしこ先生、今の俺は以前の俺とは違うんだぜ・・・もう大人になったんだ、下半身も含めて。")
    (wait)
    (text #:color 6 "【よしこ】一言余計です・・・それに『よしこ先生』と言うのはよしなさい。")
    (wait)
    (text #:color 7 "【" 0 "】いいじゃない、親しみがあって・・・俺は好きだなあ。")
    (wait)
    (text #:color 6 "【よしこ】何が『俺は好きだなあ』ですか・・・私は生徒と友達になった覚えはありませんよ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "36.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "l01.pd8")
    (proc 16)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】先生と生徒は友達ではない・・・確かにその通りさ。")
    (wait)
    (set-reg: 645 1)))
  ((&& (== (: 695) 1) (> H 821) (> T 1800) (== (: 703) 0) (== (: 708) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "a.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "aan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "a.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】おわっ！？")
    (wait)
    (text #:color 3 "【美沙】なんだ・・・" 0 "か。")
    (wait)
    (text #:color 7 "【" 0 "】な、なんだじゃないよ・・・何をやってるんだ、こんな時間に！？")
    (wait)
    (text #:color 3 "【美沙】いいだろ・・・別に。")
    (wait)
    (text #:color 7 "【" 0 "】かわいくないなあ・・・こんな場所にいると、恐いおじさんが寄ってくるぜ。")
    (wait)
    (text #:color 3 "【美沙】いいさ、別に・・・私なんて。")
    (wait)
    (text #:color 7 "【" 0 "】いいから帰れよ・・・危ないから。")
    (wait)
    (text #:color 3 "【美沙】・・・。")
    (wait)
    (text #:color 3 "【美沙】わかった・・・そうする。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "36.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】美沙のやつ・・・校庭のトラックを見つめてたな。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あいつ・・・何かあったんじゃないか？")
    (wait)
    (set-reg: 703 1)))
  ((&& (> H 825) (> T 1000) (== (: 690) 1) (== (: 708) 0))
   (<>
    (text #:color 7 "【" 0 "】うーん、みんな練習してるな・・・。")
    (wait)
    (text #:color 3 "【女の声】" 0 "君！！")
    (wait)
    (text #:color 7 "【" 0 "】ん？・・・誰だ？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "g.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "tan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "t.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 25)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】真子先生・・・校庭にいるなんて、めずらしいなあ。")
    (wait)
    (text #:color 3 "【真子】陸上部の顧問の先生と話をしてたのよ・・・美沙さんの事で。")
    (wait)
    (text #:color 7 "【" 0 "】美沙が・・・どうかしたの？")
    (wait)
    (text #:color 3 "【真子】ええ、ふとももの肉離れね・・・これで二度目なのよ。")
    (wait)
    (text #:color 7 "【" 0 "】二度目？")
    (wait)
    (text #:color 3 "【真子】ええ、自転車で転んだ時があったでしょ？・・・あの少し前に一回やってるのよ。")
    (wait)
    (text #:color 7 "【" 0 "】（なんだよ、美沙のやつ・・・俺に何も言わないで。）")
    (wait)
    (text #:color 3 "【真子】しばらく練習を休んでて、また再開したんだけど・・・また痛めちゃったみたいね。")
    (wait)
    (text #:color 7 "【" 0 "】で・・・美沙は？")
    (wait)
    (text #:color 3 "【真子】保健室で休んでるんじゃないかしら。")
    (wait)
    (text #:color 7 "【" 0 "】（ショックだろうなあ・・・大会も近いのに。）")
    (wait)
    (text #:color 3 "【真子】さてと、もう少し顧問の先生と話をしないと・・・じゃあね、" 0 "君。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "36.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "l01.pd8")
    (proc 16)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】美沙は・・・保健室か。")
    (wait)
    (set-var O H)
    (set-reg: 708 1)))
  ((&&
    (== (: 728) 1)
    (== (: 710) 1)
    (> H 827)
    (< H 829)
    (> T 800)
    (< T 2359)
    (== (: 741) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【太郎】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 5 "【太郎】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なんだよ、おい。")
    (wait)
    (text #:color 5 "【太郎】不潔だあっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "36.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "l01.pd8")
    (proc 16)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あいつ・・・転校しないかな。")
    (wait)
    (set-reg: 741 1)))
  ((&& (== (: 753) 1) (> H 827) (> T 830) (< T 1800) (== (: 757) 0))
   (<>
    (text #:color 7 "【" 0 "】ふう・・・。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "w.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "wan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "w.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 24)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 3 "【舞】・・・。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "36.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "l01.pd8")
    (proc 16)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】ん？")
    (wait)
    (text #:color 7 "【" 0 "】今・・・誰か通ったか？")
    (wait)
    (set-reg: 111 (- (: 111) 1))
    (set-reg: 757 1)))
  ((&&
    (== (: 728) 1)
    (== (: 710) 0)
    (> H 827)
    (< H 829)
    (> T 800)
    (< T 2359)
    (== (: 741) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】なんだよ・・・もう出て来るなよ。")
    (wait)
    (text #:color 5 "【太郎】ああ、楽しみだな・・・新学期が始まるのが。")
    (wait)
    (text #:color 5 "【太郎】ふっ・・・ふっ・・・僕の将来はバラ色だ。")
    (wait)
    (text #:color 7 "【" 0 "】よかったな。")
    (wait)
    (text #:color 5 "【太郎】そして、" 0 "君の将来は・・・ドブ色だ。")
    (wait)
    (text #:color 7 "【" 0 "】な、なんだ！？・・・トブ色って！？")
    (wait)
    (text #:color 5 "【太郎】ふっふっ・・・僕の勝ちだよ、" 0 "君。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "36.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "l01.pd8")
    (proc 16)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】うーん・・・何かにとりつかれてるとしか思えないぞ。")
    (wait)
    (set-reg: 741 1)))
  ((== (: 409) 1)
   (<> (text #:color 7 "【" 0 "】青春の汗を、彼らはグランドに流し・・・俺はベットの上で流すんだ。") (wait))))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show
       (<.> (text "外に出る") (text "中に入る") (text "プールに行く") (text "やめる")))
      (cond
       ((&& (== N 1) (== (: 154) 1) (> T 829) (< T 1800) (== (: 219) 0))
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・外に出るか。")
         (wait)
         (text #:color 5 "【男の声】" 0 "君。")
         (wait)
         (text #:color 7 "【" 0 "】へ？・・・そのダミ声は？")
         (wait)
         (set-reg: 309 0)
         (slot 1 3)
         (mes-jump "gate.mes")))
       ((&& (== N 1) (== (: 274) 1) (== (: 277) 0))
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・外に出よう。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "18.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "m.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "man.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "m.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 27)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 7 "【" 0 "】あれれ！？・・・美穂ちゃんも帰るの？")
         (wait)
         (text #:color 6 "【美穂】あのね・・・ちょっと言いたい事があって、ここで" 0 "君を待ってたの。")
         (wait)
         (text #:color 7 "【" 0 "】俺を？")
         (wait)
         (text #:color 6 "【美穂】えーと・・・。")
         (wait)
         (text #:color 7 "【" 0 "】へ？")
         (wait)
         (text #:color 6 "【美穂】あの・・・。")
         (wait)
         (text #:color 7 "【" 0 "】なに？")
         (wait)
         (text #:color 6 "【美穂】ううん、もういいの・・・さよなら。")
         (wait)
         (text #:color 7 "【" 0 "】あ・・・。")
         (wait)
         (set-reg: 277 1)
         (set-reg: 278 1)
         (set-reg: 309 0)
         (set-var N 1)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 1) (== (: 604) 1) (== (: 607) 0) (> T 830) (< T 1800))
        (<>
         (text #:color 7 "【" 0 "】ふう・・・外に出るか。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "18.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "g.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "tan.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "t.s4" (~ @ 2))
         (animate 0 0 1)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 25)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 3 "【真子】" 0 "君・・・こんにちは。")
         (wait)
         (text #:color 7 "【" 0 "】こ、こ、こんにちは。")
         (wait)
         (text #:color 3 "【真子】今日もいい天気ね・・・。")
         (wait)
         (text
          #:color
          7
          "【"
          0
          "】（うーん、以前とまったく変わらない真子先生が目の前にいる・・・やはりあれは夢だったのかな？）")
         (wait)
         (text #:color 3 "【真子】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】（俺も以前と変わらない態度をとらないと・・・気まずい雰囲気になりそうだな。）")
         (wait)
         (text #:color 3 "【真子】じゃあ・・・私は保健室に戻らないと。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "18.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】あ・・・ち、ちょっと。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】行ってしまった・・・俺も帰ろう。")
         (wait)
         (set-reg: 607 1)
         (set-reg: 673 1)
         (set-reg: 309 0)
         (set-var N 1)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&&
         (== N 1)
         (== (: 668) 1)
         (> H 825)
         (== (: 673) 0)
         (> T 830)
         (< T 1800))
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・帰ろうぜ。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "18.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "g.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "tan.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "t.s4" (~ @ 2))
         (animate 0 0 1)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 25)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 3 "【真子】あら、" 0 "君・・・帰るのかしら？")
         (wait)
         (text #:color 7 "【" 0 "】うん、真子先生が遊んでくれないからさ。")
         (wait)
         (text #:color 3 "【真子】遊ぶ相手を間違えてるわよ・・・私じゃなくて、亜子でしょう？")
         (wait)
         (text #:color 7 "【" 0 "】ううん、俺は目の前にいる女性を一番大事にする主義なんだ。")
         (wait)
         (text #:color 3 "【真子】亜子に会って、同じ事を言ってくれば？・・・あの子、喜ぶんじゃない？")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "18.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】そんな事はないさ、俺にだって相手を選ぶ権利が・・・あれ？")
         (wait)
         (text #:color 7 "【" 0 "】ちっ・・・誰もいないぜ、おい。")
         (wait)
         (set-reg: 673 1)
         (set-reg: 309 0)
         (set-var N 1)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&&
         (== N 1)
         (== (: 745) 1)
         (> H 818)
         (< H 824)
         (> T 830)
         (< T 1500)
         (== (: 747) 0))
        (<>
         (text #:color 7 "【" 0 "】帰ろうぜ・・・。")
         (wait)
         (text #:color 3 "【女の声】" 0 "君。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "18.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "v11.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "v11an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "v11.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 24)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 7 "【" 0 "】舞ちゃん・・・ええっ！？")
         (wait)
         (text #:color 3 "【舞】・・・。")
         (wait)
         (text #:color 3 "【舞】きゃあっ！！私ったら、あわてて水着のまま出てきちゃった！？")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "18.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】はあはあはあ・・・驚いたぜ。")
         (wait)
         (text #:color 7 "【" 0 "】舞ちゃんって、けっこうおちゃめだよな。")
         (wait)
         (set-reg: 747 1)
         (set-reg: 309 0)
         (set-var N 1)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&&
         (== N 1)
         (== (: 324) 1)
         (== (: 685) 1)
         (> H 820)
         (> T 830)
         (< T 1800)
         (== (: 716) 0))
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・外に出よう。")
         (wait)
         (slot 1 4)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "18.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "m12.pd8")
         (proc 16)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】あれれ・・・美穂ちゃん！？")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "18.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "m.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "man.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "m.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 27)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 7 "【" 0 "】や、やあ・・・。")
         (wait)
         (text #:color 6 "【美穂】えーと・・・。")
         (wait)
         (text #:color 7 "【" 0 "】え？")
         (wait)
         (text #:color 6 "【美穂】" 0 "君・・・あの・・・これ読んで。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "18.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)
         (text #:color 7 "【" 0 "】お、おい・・・。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】手紙を渡されちゃったよ・・・何が書いてあるんだろ？")
         (wait)
         (text #:color 7 "【" 0 "】えーと、『" 0 "君の心の中には誰が住んでますか？』・・・なんだこりゃ。")
         (wait)
         (text #:color 7 "【" 0 "】『私の心の中には・・・" 0 "君が住んでいます。』")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】美穂より・・・か。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】帰ろう・・・かな。")
         (wait)
         (set-reg: 716 1)
         (set-reg: 309 0)
         (set-var N 1)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&&
         (== N 1)
         (== (: 223) 1)
         (> H 810)
         (> T 829)
         (< T 1800)
         (== (: 260) 0))
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・外に出よう。")
         (wait)
         (set-reg: 309 0)
         (slot 1 3)
         (mes-jump "gate1.mes")))
       ((&&
         (== N 1)
         (== (: 292) 1)
         (== (: 288) 1)
         (> T 900)
         (< T 1800)
         (== (: 293) 0)
         (== (: 481) 0))
        (<>
         (text #:color 7 "【" 0 "】帰ろうかな・・・。")
         (wait)
         (set-reg: 309 0)
         (slot 1 3)
         (mes-jump "gate2.mes")))
       ((&&
         (== N 1)
         (== (: 519) 1)
         (> H 826)
         (> T 830)
         (< T 1800)
         (== (: 521) 0)
         (== (: 527) 0))
        (<>
         (text #:color 7 "【" 0 "】帰ろうっと。")
         (wait)
         (text #:color 6 "【くるみ】あ、" 0 "さんだ！！")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "18.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "q.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "qan.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "q.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 23)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 6 "【くるみ】" 0 "さんも、学校に用があったの？")
         (wait)
         (text #:color 7 "【" 0 "】ははは、俺は用がなくても学校に来るやつなんだ。")
         (wait)
         (text #:color 6 "【くるみ】ふーん・・・くすくすくす。")
         (wait)
         (text #:color 7 "【" 0 "】な、なんだよ。")
         (wait)
         (text #:color 6 "【くるみ】ううん、何でもないの・・・じゃあね、" 0 "さん。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "18.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)
         (text #:color 7 "【" 0 "】あ・・・。")
         (wait)
         (text #:color 7 "【" 0 "】いきなり元気だな・・・とっても不思議だ。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】今度こそ、帰ろうっと。")
         (wait)
         (set-reg: 309 0)
         (set-var N 1)
         (set-reg: 521 1)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&&
         (== N 1)
         (== (: 641) 0)
         (> H 819)
         (> T 830)
         (< T 1800)
         (== (: 638) 0))
        (<>
         (text #:color 7 "【" 0 "】帰ろう・・・かな？")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "18.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "c.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "can.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "c.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 60)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 6 "【よしこ】" 0 "君・・・こんにちは。")
         (wait)
         (text #:color 7 "【" 0 "】よしこ先生・・・。")
         (wait)
         (text #:color 6 "【よしこ】校庭で何をしてるのかしら？")
         (wait)
         (text #:color 7 "【" 0 "】いやあ、ちょっと掘ってただけだよ・・・何か出てこないかなって思って。")
         (wait)
         (text #:color 6 "【よしこ】何も出てきませんよ・・・そんな事をしたら、陸上部の迷惑になるじゃないですか。")
         (wait)
         (text
          #:color
          7
          "【"
          0
          "】（うーん、冗談が通じないのは・・・よしこ先生のキャラクターのせいか、それとも俺自身のキャラクターのせいか？）")
         (wait)
         (text #:color 6 "【よしこ】変な事をしたらいけませんよ・・・わかりましたね？")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "18.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】今度こそ外に出るぞ。")
         (wait)
         (set-reg: 309 0)
         (set-var N 1)
         (set-reg: 638 1)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】ははは・・・ここにいても誰も相手にしてくれそうにないな。")
         (wait)
         (text #:color 7 "【" 0 "】外に出るか・・・ちくしょう。")
         (wait)
         (set-var N 1)
         (set-reg: 309 0)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 2) (> T 1801))
        (<> (text #:color 7 "【" 0 "】あれれ・・・校舎の門が閉まっていて、中に入れないぞ。") (wait)))
       ((&& (== N 2) (< T 829))
        (<> (text #:color 7 "【" 0 "】ちぇっ・・・確か校舎の門が開くのは、午前８時３０分からだったな。") (wait)))
       ((&& (== N 2) (== (: 223) 0))
        (<>
         (text #:color 3 "【女の声】" 0 "っ！！")
         (wait)
         (slot 1 8)
         (mes-jump "l02.mes")))
       ((&& (== N 2) (== (: 223) 1))
        (<>
         (text #:color 7 "【" 0 "】中に入ろうぜ・・・誰かいるかもしれないぜ。")
         (wait)
         (set-var N 0)
         (slot 1 3)
         (mes-jump "gakko1.mes")))
       ((&& (== N 3) (< T 829))
        (<>
         (text #:color 7 "【" 0 "】だめだぜ・・・プールに入れるのは、午前８時３０分から午後６時までだ。")
         (wait)))
       ((&& (== N 3) (> T 1801))
        (<>
         (text #:color 7 "【" 0 "】だめだぜ・・・プールに入れるのは、午前８時３０分から午後６時までだ。")
         (wait)))
       ((&& (== N 3) (== (: 247) 0))
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・プールに行けば、水泳部の連中がいるはずだ。")
         (wait)
         (text
          #:color
          7
          "【"
          0
          "】そう言えば、あこがれの舞ちゃんも水泳部だったな・・・舞ちゃんのスクール水着を想像しただけで、ぴゅぴゅっと出ちゃいそうだ。")
         (wait)
         (slot 1 3)
         (mes-jump "pool.mes")))
       ((&& (== N 3) (== (: 247) 1) (== (: 248) 0))
        (<>
         (text #:color 7 "【" 0 "】またプールに行くのか？")
         (wait)
         (slot 1 3)
         (mes-jump "pool1.mes")))
       ((&& (== N 3) (== (: 248) 1) (> H 811) (== (: 305) 0) (== (: 309) 0))
        (<>
         (text #:color 7 "【" 0 "】プールに行くんだな・・・そうだ、俺はプールに行きたかったんだ。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (image "51.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 9)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】舞ちゃんは・・・？")
         (wait)
         (text #:color 3 "【舞】" 0 "君！！")
         (wait)
         (slot 1 3)
         (mes-jump "pool2.mes")))
       ((&& (== N 3) (== (: 308) 1) (> H 817) (== (: 745) 0) (< H 824))
        (<>
         (text #:color 7 "【" 0 "】よーし・・・舞ちゃんがいる事を願って、行ってみるか。")
         (wait)
         (slot 1 3)
         (mes-jump "pool7.mes")))
       ((&& (== N 3) (== (: 695) 1) (> H 820) (== (: 706) 0) (== (: 708) 0))
        (<> (slot 1 3) (mes-jump "pool6.mes")))
       ((&& (== N 3) (== (: 440) 1) (== (: 441) 0) (> H 821) (== (: 765) 0))
        (<> (slot 1 3) (mes-jump "pool3.mes")))
       ((&& (== N 3) (== (: 453) 1) (== (: 454) 0) (> H 822))
        (<> (slot 1 3) (mes-jump "pool4.mes")))
       ((&& (== N 3) (== (: 668) 1) (> H 825) (== (: 675) 0))
        (<> (slot 1 3) (mes-jump "pool5.mes")))
       ((&& (== N 3) (== (: 746) 1) (> H 824) (== (: 765) 0) (== (: 768) 0))
        (<> (slot 1 3) (mes-jump "pool8.mes")))
       ((&& (== N 3) (== (: 247) 1))
        (<>
         (text #:color 7 "【" 0 "】プールに行くか・・・目の保養になるからな。")
         (wait)
         (slot 1 3)
         (mes-jump "pool.mes")))
       ((== N 4) (<> (text #:color 7 "【" 0 "】え！？・・・まだここにいるつもりか？") (wait)))
       (else (<>)))))
    ((&& (== V 2) (== N 10) (== (: 18) 0) (== (: 409) 0))
     (<>
      (text #:color 2 "【女の子】ちょっと、ジャンプしている最中に話かけないでよっ！！")
      (wait)
      (text #:color 7 "【" 0 "】じゃあ、地面に降りてくるまで待つか・・・。")
      (wait)
      (text #:color 2 "【女の子】・・・。")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 2) (== N 10) (== (: 18) 1) (== (: 409) 0))
     (<>
      (text #:color 2 "【女の子】な、なによ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】別に・・・いつ地面に着くのかなーって。")
      (wait)))
    ((&& (== V 2) (== N 10) (== (: 409) 1))
     (<>
      (text #:color 2 "【女の子】あー、空中に浮かんでいるのって気持ちいいわあ。")
      (wait)
      (text #:color 7 "【" 0 "】セックスをしてイク時もそんな感じだろ？")
      (wait)
      (text #:color 2 "【女の子】黙れ、" 0 "。")
      (wait)))
    ((&& (== V 2) (== N 16) (== (: 19) 0) (== (: 409) 0))
     (<>
      (text #:color 4 "【男の子】ねえねえ、今晩いいだろう？")
      (wait)
      (text #:color 7 "【" 0 "】ロクな事を話してないな・・・こいつは。")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 2) (== N 16) (== (: 19) 1) (== (: 409) 0))
     (<>
      (text #:color 4 "【男の子】なあ・・・一回だけでいいからさ。")
      (wait)
      (text #:color 7 "【" 0 "】ちぇっ、スポーツ少年って顔をして・・・お前は俺よりもひどいやつだ。")
      (wait)))
    ((&& (== V 2) (== N 16) (== (: 409) 1))
     (<>
      (text #:color 4 "【男の子】ふああああ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】あああああっ・・・と。")
      (wait)
      (text #:color 7 "【" 0 "】ちくしょう、あくびがうつっちまったぜ。")
      (wait)))
    ((&& (== V 2) (== N 18) (== (: 20) 0) (== (: 409) 0))
     (<>
      (text #:color 6 "【女の子】今日は帰ったら、彼氏とエッチをしよっと・・・最近、彼ったら前戯の時間が短いのよねえ。")
      (wait)
      (text #:color 7 "【" 0 "】お前ら、スポーツに汗を流せ、汗を。")
      (wait)
      (text #:color 6 "【女の子】やだ、" 0 "よ・・・１メートル以内に近付くと、すでに入れられているって噂の・・・。")
      (wait)
      (text #:color 7 "【" 0 "】お前らなあ・・・。")
      (wait)
      (set-reg: 20 1)))
    ((&& (== V 2) (== N 18) (== (: 20) 1) (== (: 409) 0))
     (<> (text #:color 6 "【女の子】あーあ・・・部活が早く終らないかなあ、せっかくの夏休みなのに。") (wait)))
    ((&& (== V 2) (== N 18) (== (: 409) 1))
     (<>
      (text #:color 6 "【女の子】彼とのすばらしい一夜・・・思い出しただけで濡れちゃいそう。")
      (wait)
      (text #:color 7 "【" 0 "】なんだ、やる事はしっかりやってるんじゃないか。")
      (wait)))
    ((&& (== V 2) (== N 21) (== (: 21) 0) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】ねえねえ、君って何年生？")
      (wait)
      (text #:color 2 "【女の子】あれえ？・・・" 0 "先輩でしょ？")
      (wait)
      (text #:color 7 "【" 0 "】ははは、俺って有名だなあ。")
      (wait)
      (text #:color 2 "【女の子】だって・・・先輩が写真を見せてくれて、この人には気をつけろって。")
      (wait)
      (text #:color 7 "【" 0 "】誰だよ、その先輩って言うのは？")
      (wait)
      (text #:color 2 "【女の子】教えてあげない。")
      (wait)
      (set-reg: 21 1)))
    ((&& (== V 2) (== N 21) (== (: 21) 1) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】ねえねえ、電話番号を教えてよ・・・。")
      (wait)
      (text #:color 2 "【女の子】教えるとどうなるの？")
      (wait)
      (text #:color 7 "【" 0 "】俺と一緒にスポーツができるぜ・・・ベットの上で。")
      (wait)
      (text #:color 2 "【女の子】絶対に教えない。")
      (wait)
      (set-reg: 21 2)))
    ((&& (== V 2) (== N 21) (== (: 21) 2) (== (: 409) 0))
     (<>
      (text #:color 2 "【女の子】あの・・・練習中ですから。")
      (wait)
      (text #:color 7 "【" 0 "】わかったよう・・・ちっ。")
      (wait)))
    ((&& (== V 2) (== N 21) (== (: 409) 1))
     (<>
      (text #:color 2 "【女の子】やだ・・・" 0 "先輩。")
      (wait)
      (text #:color 7 "【" 0 "】" 0 "先輩はいいとして、その『やだ』って言うのは何なんだよ。")
      (wait)))
    ((&& (== V 2) (== N 23) (== (: 22) 0) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】かわいい子だな・・・こんな女の子、俺達の学校にいたっけ？")
      (wait)
      (text #:color 6 "【女の子】有名な" 0 "先輩・・・でしょ？")
      (wait)
      (text #:color 7 "【" 0 "】そうだよ、俺が" 0 "だ・・・こっそり練習を抜け出して、俺様とメイク・ラブしないかい？")
      (wait)
      (text #:color 6 "【女の子】バカみたい。")
      (wait)
      (set-reg: 22 1)))
    ((&& (== V 2) (== N 23) (== (: 22) 1) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】ねえ・・・かわいいなあ、俺とデートする気はない？")
      (wait)
      (text #:color 6 "【女の子】ありません。")
      (wait)
      (text #:color 7 "【" 0 "】ほーら、だんだんデートしたくなってくる・・・ほーら、ほーら。")
      (wait)
      (text #:color 6 "【女の子】いきなり５円玉を出して、目の前でブラブラさせないでください。")
      (wait)))
    ((&& (== V 2) (== N 23) (== (: 409) 1))
     (<>
      (text #:color 6 "【女の子】あ・・・先負学園の有名人。")
      (wait)
      (text #:color 7 "【" 0 "】はっはっはっ、サインをあげようか？")
      (wait)
      (text #:color 6 "【女の子】いりません。")
      (wait)))
    ((&& (== V 1) (== N 1) (== (: 10) 0) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】ほほう・・・これはベットの代わりになるな。")
      (wait)
      (text #:color 7 "【" 0 "】学校の校庭で、かわいい女の子と・・・こりゃあ、興奮するぜ。")
      (wait)
      (set-reg: 10 1)))
    ((&& (== V 1) (== N 1) (== (: 10) 1) (== (: 409) 0))
     (<> (text #:color 7 "【" 0 "】マットだな・・・中にはスポンジが入っているんだ。") (wait)))
    ((&& (== V 1) (== N 1) (== (: 409) 1))
     (<>
      (text #:color 7 "【" 0 "】ベットだな。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】知ってるよ、マットだろ？")
      (wait)))
    ((&& (== V 1) (== N 2) (== (: 11) 0) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】ハイ・ジャンプのポールだな・・・鉄棒じゃないぞ。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 1) (== N 2) (== (: 11) 1) (== (: 409) 0))
     (<> (text #:color 7 "【" 0 "】ハイ・ジャンプのポールだ。") (wait)))
    ((&& (== V 1) (== N 2) (== (: 409) 1))
     (<>
      (text #:color 7 "【" 0 "】『ポール・牧』だな・・・はっはっはっ！！")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ちっ、誰も聞いちゃいない。")
      (wait)))
    ((&& (== V 1) (== N 3) (== (: 12) 0) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】校庭のトラックだ・・・２００メートルはあるな。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 3) (== (: 12) 1) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】２００メートルのトラックだ。")
      (wait)
      (text #:color 7 "【" 0 "】俺はタバコを吸っているから、一周もすればゼエゼエいってしまいそうだ。")
      (wait)))
    ((&& (== V 1) (== N 3) (== (: 409) 1))
     (<> (text #:color 7 "【" 0 "】トラックだ・・・。") (wait)))
    ((&& (== V 1) (== N 4) (== (: 13) 0) (== (: 409) 0))
     (<> (text #:color 7 "【" 0 "】学校の正面玄関だな・・・。") (wait) (set-reg: 13 1)))
    ((&& (== V 1) (== N 4) (== (: 13) 1) (== (: 409) 0))
     (<> (text #:color 7 "【" 0 "】だから、学校の正面玄関だってば。") (wait)))
    ((&& (== V 1) (== N 4) (== (: 409) 1))
     (<>
      (text #:color 7 "【" 0 "】ここを入れば、校舎の中だ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】もっとも、午後６時を過ぎると入れなくなるぞ。")
      (wait)))
    ((&& (== V 1) (== N 5) (== (: 14) 0) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】俺が通っている学校だ・・・男女共学だし、校則も厳しいほうじゃない。")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 1) (== N 5) (== (: 14) 1) (== (: 409) 0))
     (<> (text #:color 7 "【" 0 "】４階建ての校舎だ・・・生徒数はあまり多くない。") (wait)))
    ((&& (== V 1) (== N 5) (== (: 409) 1))
     (<> (text #:color 7 "【" 0 "】俺達の学校だ・・・ここに通うのも、あと８ヶ月か。") (wait)))
    ((&& (== V 1) (== N 6) (== (: 15) 0) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】金網の柵の向こうには、住宅地だ・・・このあたりは夜になると、物騒な雰囲気なんだよなあ。")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 1) (== N 6) (== (: 15) 1) (== (: 409) 0))
     (<> (text #:color 7 "【" 0 "】学校の周りには、家並が続いている・・・。") (wait)))
    ((&& (== V 1) (== N 6) (== (: 409) 1))
     (<> (text #:color 7 "【" 0 "】学校の回りの景色なんて、もう見飽きたよ。") (wait)))
    ((&& (== V 1) (== N 7) (== (: 16) 0) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】屋上だな・・・校舎の中に入らないと、ここにたどり着く事はできないぞ。")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 1) (== N 7) (== (: 16) 1) (== (: 409) 0))
     (<> (text #:color 7 "【" 0 "】学校の屋上だ・・・今は誰もいないだろう。") (wait)))
    ((&& (== V 1) (== N 7) (== (: 409) 1))
     (<> (text #:color 7 "【" 0 "】屋上には・・・誰もいないな。") (wait)))
    ((&& (== V 1) (== N 8) (> T 1900))
     (<> (text #:color 7 "【" 0 "】空はもう暗くなっている・・・夜だもんな。") (wait)))
    ((&& (== V 1) (== N 8) (< T 600))
     (<> (text #:color 7 "【" 0 "】空はもう暗くなっている・・・夜だもんな。") (wait)))
    ((&& (== V 1) (== N 8) (== (: 409) 0))
     (<> (text #:color 7 "【" 0 "】空だな・・・今日も天気がいい。") (wait)))
    ((&& (== V 1) (== N 8) (== (: 409) 1))
     (<> (text #:color 7 "【" 0 "】いい天気だぜ・・・最近は雨が降らないな。") (wait)))
    ((&& (== V 1) (== N 9) (== (: 17) 0) (== (: 409) 0))
     (<> (text #:color 7 "【" 0 "】校庭だな・・・。") (wait) (set-reg: 17 1)))
    ((&& (== V 1) (== N 9) (== (: 17) 1) (== (: 409) 0))
     (<> (text #:color 7 "【" 0 "】校庭だ・・・俺がここを利用するのは、体育の授業の時ぐらいだ。") (wait)))
    ((&& (== V 1) (== N 9) (== (: 409) 1))
     (<> (text #:color 7 "【" 0 "】校庭だ・・・。") (wait)))
    ((&& (== V 1) (== N 11) (== (: 23) 0) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】よく跳ぶなあ・・・そのまま大空に飛んで行っちゃうんじゃないか？")
      (wait)
      (set-reg: 23 1)))
    ((&& (== V 1) (== N 11) (== (: 23) 1) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】ねえ・・・疲れない？")
      (wait)
      (text #:color 2 "【女の子】・・・。")
      (wait)))
    ((&& (== V 1) (== N 11) (== (: 409) 1))
     (<> (text #:color 7 "【" 0 "】このポーズのまま、抱き抱えて家に持って帰ろう。") (wait)))
    ((&& (== V 1) (== N 12) (== (: 24) 0) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】なんだか倒れそうな感じで走ってるな・・・。")
      (wait)
      (set-reg: 24 1)))
    ((&& (== V 1) (== N 12) (== (: 24) 1) (== (: 409) 0))
     (<> (text #:color 7 "【" 0 "】うーん、青春の汗ってやつか？・・・俺はごめんだぜ。") (wait)))
    ((&& (== V 1) (== N 12) (== (: 409) 1))
     (<> (text #:color 7 "【" 0 "】一生懸命走ってる・・・死ななければいいが。") (wait)))
    ((&& (== V 1) (== N 13) (== (: 25) 0) (== (: 409) 0))
     (<> (text #:color 7 "【" 0 "】うーん、全力疾走だな・・・偉い、偉い。") (wait) (set-reg: 25 1)))
    ((&& (== V 1) (== N 13) (== (: 25) 1) (== (: 409) 0))
     (<> (text #:color 7 "【" 0 "】走り方からして、マラソンって感じじゃないな。") (wait)))
    ((&& (== V 1) (== N 13) (== (: 409) 1))
     (<>
      (text #:color 7 "【" 0 "】人間は酸欠になると、コウコツ状態になるらしい・・・一種のエクスタシーだな。")
      (wait)))
    ((&& (== V 1) (== N 14) (== (: 26) 0) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】彼らは陸上部だな・・・夏の大会も近いから、みんな一生懸命練習している。")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 1) (== N 14) (== (: 26) 1) (== (: 409) 0))
     (<> (text #:color 7 "【" 0 "】うーん、死ななければいいが・・・。") (wait)))
    ((&& (== V 1) (== N 14) (== (: 409) 1))
     (<>
      (text #:color 7 "【" 0 "】走れっ！！もっと走れっ！！")
      (wait)
      (text #:color 7 "【" 0 "】ははは、見てるだけだから楽だな。")
      (wait)))
    ((&& (== V 1) (== N 15) (== (: 27) 0) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】彼は何をしているのかな・・・タイムを計ってるのか？")
      (wait)
      (set-reg: 27 1)))
    ((&& (== V 1) (== N 15) (== (: 27) 1) (== (: 409) 0))
     (<> (text #:color 7 "【" 0 "】一人だけ楽をしてるな・・・お前も走れ。") (wait)))
    ((&& (== V 1) (== N 15) (== (: 409) 1))
     (<> (text #:color 7 "【" 0 "】お前も走れっ！！") (wait)))
    ((&& (== V 1) (== N 17) (== (: 28) 0) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】いるんだよなあ・・・女目当てで、クラブに入るやつが。")
      (wait)
      (set-reg: 28 1)))
    ((&& (== V 1) (== N 17) (== (: 28) 1) (== (: 409) 0))
     (<> (text #:color 7 "【" 0 "】おーいっ！！スケベっ！！いちゃつくなら、体育倉庫でやれっ！！") (wait)))
    ((&& (== V 1) (== N 17) (== (: 409) 1))
     (<>
      (text #:color 7 "【" 0 "】トラックを走り、汗をかくやつもいれば・・・女を一生懸命くどくやつもいる。")
      (wait)))
    ((&& (== V 1) (== N 19) (== (: 29) 0) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】いいふとももをしてやがるぜ、おい。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】いいじゃないか、正直に言ったまでだ。")
      (wait)
      (set-reg: 29 1)))
    ((&& (== V 1) (== N 19) (== (: 29) 1) (== (: 409) 0))
     (<> (text #:color 7 "【" 0 "】うーん、彼女のふとももを枕にして寝てみたいぜ。") (wait)))
    ((&& (== V 1) (== N 19) (== (: 409) 1))
     (<> (text #:color 7 "【" 0 "】若い女ってのはいいなあ・・・って、ジジイみたいな言い方をしてしまった。") (wait)))
    ((&& (== V 1) (== N 22) (== (: 30) 0) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】１年生かな・・・くんかくんかくんか。")
      (wait)
      (text #:color 7 "【" 0 "】うーん、処女の香りがする。")
      (wait)
      (set-reg: 30 1)))
    ((&& (== V 1) (== N 22) (== (: 30) 1) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】決めた！！彼女の最初の男になってやろう。")
      (wait)
      (text #:color 2 "【女の子】お断りします。")
      (wait)))
    ((&& (== V 1) (== N 22) (== (: 409) 1))
     (<>
      (text #:color 7 "【" 0 "】ねえねえ、処女？")
      (wait)
      (text #:color 2 "【女の子】やだ・・・今時の娘で処女なんていないわよ。")
      (wait)
      (text #:color 7 "【" 0 "】あ・・・そうなの？")
      (wait)))
    ((&& (== V 1) (== N 24) (== (: 31) 0) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】大人しそうな子だな・・・俺の得意分野だぜ。")
      (wait)
      (text #:color 6 "【女の子】私、大人しくありませんよ。")
      (wait)
      (text #:color 7 "【" 0 "】あのさあ、喋る時ぐらいこっちを向いてよ。")
      (wait)
      (set-reg: 31 1)))
    ((&& (== V 1) (== N 24) (== (: 31) 1) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】三編みがかわいい子だ・・・あれを引っ張りながら、バックから責めて・・・ひっひっひっ。")
      (wait)))
    ((&& (== V 1) (== N 24) (== (: 409) 1))
     (<> (text #:color 7 "【" 0 "】かわいいなあ・・・俺好みだぜ。") (wait)))
    ((&& (== V 3) (== N 20) (== (: 32) 0) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】よせよ・・・あいつは、陸上部の顧問教師だ。")
      (wait)
      (set-reg: 32 1)))
    ((&& (== V 3) (== N 20) (== (: 32) 1) (== (: 409) 0))
     (<>
      (text #:color 7 "【" 0 "】やめようぜ・・・それでなくても、俺様は体育系の教師から目をつけられているんだ。")
      (wait)))
    ((&& (== V 3) (== N 20) (== (: 409) 1))
     (<> (text #:color 7 "【" 0 "】よせよ・・・もう停学はくらいたくない。") (wait)))
    ((&& (== V 8) (== N 25) (== (: 33) 0) (== (: 409) 0))
     (<>
      (text #:color 6 "さわさわさわっ！！")
      (wait)
      (text #:color 7 "【" 0 "】うーん、なんてすべすべした肌なんだ・・・この短パンの間から、手を入れさせてもらって。")
      (wait)
      (text #:color 7 "【" 0 "】ほほう、白いパンティじゃないか・・・ん？")
      (wait)
      (text #:color 7 "【" 0 "】なんだ、汗でぐっしょりじゃないか・・・どれどれ、おじさんが取り替えてあげよう。")
      (wait)
      (text #:color 6 "【女の子】あのー・・・側に来て、いやらしい事を耳元でささやかないでください。")
      (wait)
      (set-reg: 33 1)))
    ((&& (== V 8) (== N 25) (== (: 33) 1) (== (: 409) 0))
     (<>
      (text #:color 6 "【女の子】変な事をすると、顧問に言いつけますよ。")
      (wait)
      (text #:color 7 "【" 0 "】変な事ができるんだったら、いいつけられてもいい。")
      (wait)
      (text #:color 6 "【女の子】じゃあ・・・変な事をしたら、顧問の先生に" 0 "先輩の身体をもて遊んでもらいます。")
      (wait)
      (text #:color 7 "【" 0 "】絶対にいやだ。")
      (wait)))
    ((&& (== V 8) (== N 25) (== (: 409) 1))
     (<>
      (text #:color 7 "【" 0 "】うんうん、絹のような肌ざわりだ。")
      (wait)
      (text #:color 6 "【女の子】" 0 "先輩、不幸の手紙を送りますよ。")
      (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))