(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\ん
  #\っ
  #\【
  #\】
  #\い
  #\る
  #\。
  #\な
  #\、
  #\の
  #\て
  #\か
  #\た
  #\だ
  #\に
  #\く
  #\も
  #\ち
  #\ゃ
  #\は
  #\し
  #\う
  #\み
  #\と
  #\で
  #\あ
  #\女
  #\が
  #\彼
  #\を
  #\ど
  #\け
  #\俺
  #\一
  #\哉
  #\事
  #\そ
  #\す
  #\ー
  #\わ
  #\ら
  #\見
  #\ン
  #\よ
  #\え
  #\ぜ
  #\お
  #\生
  #\ま
  #\さ
  #\言
  #\？
  #\り
  #\じ
  #\き
  #\れ)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (sound 1)
 (set-var I 23)
 (proc 26)
 (set-reg: 835 0)
 (while
  (== 1 1)
  (<>
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((&& (== N 9) (== (: 515) 0))
     (<>
      (text #:color 7 "【" 0 "】そうだな・・・くるみちゃんのデータを見よう。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "29.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "i.pd8")
      (proc 16)
      (set-arr~ @ 6 1)
      (image "r.pd8")
      (proc 16)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "ran.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "r.s4" (~ @ 2))
      (animate 0 0 2)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】『仁科　くるみ』・・・俺の同級生であり、一哉の彼女でもある。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】どう見ても歳下に見えてしまうほど、幼い感じがするな・・・なぜか彼女も俺の事を『"
       0
       "さん』って呼ぶし。")
      (wait)
      (text #:color 7 "【" 0 "】くるみちゃんのお父さんは、男友達の事にうるさいんだ・・・まあ気持ちはわからないでもないが。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】でも、おかげで一哉はキスもできないあり様だ・・・もっとも、本当の所は本人達しか知らない事だけど。")
      (wait)
      (text #:color 7 "【" 0 "】くるみちゃんは、一哉にはもったいない女の子だな・・・かわいいし、明るいし、性格もいいし。")
      (wait)
      (if-else (== (: 291) 1)
        (<>
         (slot 1 2)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "12.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "q.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "qan.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "q.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text
          #:color
          7
          "【"
          0
          "】彼女は真子先生に、色々と相談してるようだ・・・彼女が悩む事と言ったら一哉の事に決まってるな。")
         (wait))
        (<>))
      (if-else (== (: 503) 1)
        (<>
         (slot 1 8)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "q01.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "q01an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "q01.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】俺はくるみちゃんと矢吹町駅で会って・・・彼女の相談に乗る為に、公園に行ったんだ。")
         (wait)
         (text
          #:color
          7
          "【"
          0
          "】そのおかげかどうか、わかけらないけど・・・くるみちゃんの表情が少しだけ明るくなったんだっけ。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "q02.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "q02an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "q02.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text
          #:color
          7
          "【"
          0
          "】そして二人でボートに乗ったんだ・・・あの時のくるみちゃんは、生唾ゴックンするほどかわいかった。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】パンティとふとももが見えてたんだぜ・・・おい、ちゃんと覚えているかい？")
         (wait))
        (<>))
      (if-else (== (: 514) 1)
        (<>
         (slot 1 8)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "12.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "q04.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "q04an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "q04.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】その後に・・・彼女はマンションの前に立ってたんだ。")
         (wait)
         (text #:color 7 "【" 0 "】驚いたよなあ、まさかあんな事を言い出すとは思ってもみなかったぜ。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】あれでいいんだよな・・・いくら俺でも、くるみちゃんを抱く事はできない。")
         (wait))
        (<>))
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "42.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (cond
       ((== (: 481) 0)
        (<>
         (text #:color 7 "【" 0 "】一哉の彼女じゃなかったら、とっくに俺様の毒牙にかかっているところだぜ、ふっ。")
         (wait)))
       ((&& (== (: 481) 1) (== (: 514) 0))
        (<> (text #:color 7 "【" 0 "】彼女はもう・・・一哉の彼女じゃないって考えていいのかな？") (wait)))
       ((&& (== (: 514) 1) (== (: 527) 0))
        (<> (text #:color 7 "【" 0 "】でも・・・ちょっと惜しい気がするぞ、うん。") (wait)))
       ((&& (== (: 527) 1) (== (: 734) 0))
        (<>
         (text #:color 7 "【" 0 "】最後には、くるみちゃんが一哉をふった事になるのか？・・・うーん、わからないもんだなあ。")
         (wait)))
       ((&& (== (: 527) 1) (== (: 734) 1))
        (<>
         (text #:color 7 "【" 0 "】で、結局くるみちゃんは、一哉とやり直す事になったんだ・・・ああ、アホらしい。")
         (wait)))
       (else (<>)))
      (set-reg: 608 1)
      (slot 1 2)
      (mes-jump "myroom.mes")))
    ((&& (== N 9) (== (: 515) 1))
     (<>
      (text #:color 7 "【" 0 "】くるみちゃんのデータを見るのか？")
      (wait)
      (text #:color 7 "【" 0 "】うーん・・・思い出しただけで、いきそうになっちゃうぞ。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "29.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "i.pd8")
      (proc 16)
      (set-arr~ @ 6 1)
      (image "r.pd8")
      (proc 16)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "ran.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "r.s4" (~ @ 2))
      (animate 0 0 2)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】『仁科　くるみ』・・・俺の同級生であり、一哉の彼女でも・・・もうないのか？")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】どう見ても歳下に見えてしまうほど、幼い感じがするな・・・なぜか彼女も俺の事を『"
       0
       "さん』って呼ぶし。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "12.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "q.pd8")
      (proc 16)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "qan.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】彼女は真子先生に、一哉の事を相談していたんだろう・・・しかし、一哉とは別れたも同然だ。")
      (wait)
      (if-else (== (: 503) 1)
        (<>
         (slot 1 8)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "q01.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "q01an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "q01.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】俺はくるみちゃんと矢吹町駅で会って・・・彼女の相談に乗る為に、公園に行ったんだ。")
         (wait)
         (text
          #:color
          7
          "【"
          0
          "】そのおかげかどうか、わかけらないけど・・・くるみちゃんの表情が少しだけ明るくなったんだっけ。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "q02.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "q02an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "q02.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text
          #:color
          7
          "【"
          0
          "】そして二人でボートに乗ったんだ・・・あの時のくるみちゃんは、生唾ゴックンするほどかわいかった。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】パンティとふとももが見えてたんだぜ・・・おい、ちゃんと覚えているかい？")
         (wait))
        (<>))
      (slot 1 8)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "12.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "q04.pd8")
      (proc 16)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q04an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q04.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】そして、彼女がマンションの前に立っていて・・・二人でホテルに行っちゃったんだよな。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "q03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q03an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q03.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】くるみちゃん・・・かわいかったよなあ。")
      (wait)
      (text #:color 7 "【" 0 "】俺は彼女を抱き寄せて、キスをしたんだ・・・何度も突き飛ばされたけど。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "q10.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "q05.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q10an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q10.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】そして、ロープを買って・・・ああ、興奮するぜい！！")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "q10.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "q08.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q10an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q10.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】指先が・・・くんか、くんか。")
      (wait)
      (text #:color 7 "【" 0 "】うーん、まだくるみちゃんの香りが残ってるような気がする。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "q10.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "q09.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q10an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q10.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】あんな下着をつけてるとは・・・夢にも思わなかったな。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "q10.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q10an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q10.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】うーん・・・奇麗な身体だった。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "q06.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q06an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q06.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】言っておくけど、俺は変態じゃないぞ・・・彼女が縛ってくれって言ったんだ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "q07.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q07an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q07.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】そして俺とくるみちゃんは結ばれた・・・ちょっと出すのが早かったけど。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "42.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】ホテルを出て・・・俺は彼女を送って行った。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】あの時にくるみちゃんが言った言葉が・・・妙に耳の中に残ってるなあ。")
      (wait)
      (set-reg: 608 1)
      (slot 1 2)
      (mes-jump "myroom.mes")))
    (else (<>)))))
 (set-arr~ @ 7 1))