(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\。
  #\い
  #\美
  #\穂
  #\っ
  #\な
  #\ん
  #\に
  #\て
  #\の
  #\ゃ
  #\だ
  #\か
  #\、
  #\あ
  #\し
  #\ち
  #\う
  #\（
  #\）
  #\ら
  #\る
  #\や
  #\く
  #\君
  #\？
  #\も
  #\は
  #\男
  #\こ
  #\め
  #\れ
  #\隣
  #\え
  #\ま
  #\た
  #\！
  #\き
  #\を
  #\で
  #\が
  #\ろ
  #\わ
  #\け
  #\お
  #\柔
  #\ど
  #\よ
  #\さ
  #\黙
  #\私
  #\俺
  #\り
  #\好
  #\手)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 9 (&& (~ @ 9) 65534))
 (set-arr~ @ 6 1)
 (image "m09.pd8")
 (set-arr~ @ 9 (// (~ @ 9) 1))
 (proc 24)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "m09an.pd8")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 0)
 (load "m09.s4" (~ @ 2))
 (animate 0 0 0)
 (animate 1 0)
 (set-arr~ @ 7 0)
 (animate 0 8 1)
 (animate 4 8)
 (set-arr~ @ 7 0)
 (load "m09.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (if (== (: 324) 1)
   (<>
    (text #:color 7 "【" 0 "】（美穂ちゃんと、座席の間に潜って・・・と。）")
    (wait)
    (text #:color 6 "【美穂】あ・・・" 0 "君、どこに行ったの？")
    (wait)
    (text #:color 7 "【" 0 "】ここにいるよ・・・。")
    (wait)
    (text #:color 6 "【美穂】一人にしないで・・・お願い。")
    (wait)
    (text #:color 7 "【" 0 "】もちろん、一人になんかしないさ・・・。")
    (wait)))
 (set-reg: 331 0)
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (set-reg: 331 (+ (: 331) 1))
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "笑う") (text "泣く")))
      (cond
       ((&& (== N 1) (== (: 10) 0))
        (<>
         (text #:color 7 "【" 0 "】わっはっはっはっはっ！！")
         (wait)
         (animate 0 8 2)
         (animate 4 8)
         (text #:color 5 "【隣の男】にゃあ？")
         (wait)
         (text #:color 7 "【" 0 "】黙れ、ネコ男。")
         (wait)
         (set-reg: 10 1)))
       ((&& (== N 1) (== (: 10) 1))
        (<>
         (text #:color 7 "【" 0 "】はーっはっはっはっはっ！！")
         (wait)
         (animate 0 8 2)
         (animate 4 8)
         (text #:color 5 "【隣の男】にゃ？")
         (wait)
         (text #:color 7 "【" 0 "】死ね、ネコ男。")
         (wait)))
       ((&& (== N 2) (== (: 11) 0))
        (<>
         (text #:color 7 "【" 0 "】えっえっえっえっ・・・。")
         (wait)
         (animate 0 8 2)
         (animate 4 8)
         (text #:color 5 "【隣の男】にゃにゃ？")
         (wait)
         (text #:color 7 "【" 0 "】うるさい。")
         (wait)
         (set-reg: 11 1)))
       ((&& (== N 2) (== (: 11) 1))
        (<>
         (text #:color 7 "【" 0 "】うっうっうっ・・・えっえっえっ。")
         (wait)
         (animate 0 8 2)
         (animate 4 8)
         (text #:color 5 "【隣の男】にゃ。")
         (wait)
         (text #:color 7 "【" 0 "】黙ってろ。")
         (wait)))
       (else (<>)))))
    ((> (: 331) 14)
     (<>
      (text #:color 6 "【美穂】だめえ・・・もう我慢できない。")
      (wait)
      (text #:color 7 "【" 0 "】美穂ちゃん、動かないで。")
      (wait)
      (text #:color 5 "【隣の男】にゃ？")
      (wait)
      (text #:color 7 "【" 0 "】黙れ。")
      (wait)
      (text #:color 6 "【美穂】" 0 "君・・・も、もうだめ。")
      (wait)
      (text #:color 7 "【" 0 "】いいから・・・このままで。")
      (wait)
      (animate 0 8 2)
      (animate 4 8)
      (text #:color 5 "【隣の男】にゃにゃ？")
      (wait)
      (text #:color 7 "【" 0 "】うるさい。")
      (wait)
      (text
       #:color
       6
       "【場内アナウンス】ただいまを持ちまして『思ひ出どろどろ』の上映を終了致しました、お忘れ物にお気をつけて・・・。")
      (wait)
      (set-var A 2)
      (proc 13)
      (proc 11)
      (text #:color 7 "【" 0 "】げっ！？・・・映画が終ってしまった。")
      (wait)
      (text #:color 5 "【隣の男】にゃーん。")
      (wait)
      (text #:color 7 "【" 0 "】固まってろ。")
      (wait)
      (text #:color 6 "【美穂】だ、だめ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】まだ明るくならない、もう少しこのままで・・・。")
      (wait)
      (animate 0 8 2)
      (animate 4 8)
      (text #:color 5 "【隣の男】にゃ？")
      (wait)
      (text #:color 7 "【" 0 "】いいかげんにしろ。")
      (wait)
      (text #:color 6 "【美穂】" 0 "君・・・私、外に出る。")
      (wait)
      (text #:color 7 "【" 0 "】あ・・・美穂ちゃん！？")
      (wait)
      (animate 0 8 2)
      (animate 4 8)
      (text #:color 5 "【隣の男】にゃにゃ？")
      (wait)
      (text #:color 7 "【" 0 "】うるさいっ！！")
      (wait)
      (slot 1 3)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "n21.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "f.pd8")
      (proc 16)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "fan.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "f.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (sound 1)
      (set-var I 27)
      (proc 26)
      (set-reg: 835 0)
      (text #:color 6 "【美穂】" 0 "君の・・・ばか。")
      (wait)
      (text #:color 7 "【" 0 "】あ・・・。")
      (wait)
      (field 14 1 1)
      (field 13 0 0)
      (field 13 1 1)
      (set-reg: 1001 0)
      (set-reg: 102 (+ (: 102) 5))
      (set-var N 22)
      (set-reg: 326 1)
      (mouse 4 49152)
      (mouse 0)
      (slot 1 3)
      (mes-jump "town1.mes")))
    ((&& (== V 7) (== N 1) (== (: 12) 0))
     (<>
      (text #:color 6 "【美穂】いや・・・私、初めてなの。")
      (wait)
      (text #:color 7 "【" 0 "】美穂ちゃんは、俺の事が嫌いかい？")
      (wait)
      (text #:color 6 "【美穂】・・・。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 7) (== N 1) (== (: 12) 1))
     (<>
      (text #:color 6 "【美穂】ん・・・。")
      (wait)
      (text #:color 7 "【" 0 "】（ああ・・・なんて柔らかいくちびるなんだ。）")
      (wait)))
    ((&& (== V 8) (== N 2) (== (: 13) 0))
     (<>
      (text #:color 6 "【美穂】いや・・・暗くて、誰に触られてるかわからない。")
      (wait)
      (text #:color 7 "【" 0 "】俺だよ・・・" 0 "だ。")
      (wait)
      (text #:color 6 "【美穂】" 0 "君・・・やめて。")
      (wait)
      (text #:color 7 "【" 0 "】（柔らかい髪・・・想像した通りだぜ。）")
      (wait)
      (set-reg: 13 1)))
    ((&& (== V 8) (== N 2) (== (: 13) 1))
     (<>
      (text #:color 7 "【" 0 "】美穂ちゃん・・・好きなんだ。")
      (wait)
      (text #:color 6 "【美穂】" 0 "君・・・私も・・・。")
      (wait)
      (text #:color 7 "【" 0 "】私も？")
      (wait)
      (text #:color 6 "【美穂】・・・。")
      (wait)
      (set-reg: 13 2)))
    ((&& (== V 8) (== N 2) (== (: 13) 2))
     (<> (text #:color 6 "【美穂】いや・・・。") (wait)))
    ((&& (== V 10) (== N 3) (== (: 15) 0))
     (<>
      (text #:color 6 "【美穂】あ・・・くすぐったあい。")
      (wait)
      (text #:color 7 "【" 0 "】美穂ちゃん・・・好きなんだよ。")
      (wait)
      (text #:color 6 "【美穂】だめ・・・ここは映画館よ。")
      (wait)
      (text #:color 7 "【" 0 "】じゃあ・・・他の場所に行こう。")
      (wait)
      (text #:color 6 "【美穂】いや・・・だめ・・・。")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 10) (== N 3) (== (: 15) 1))
     (<>
      (text #:color 6 "【美穂】だめえ・・・耳に息を吹きかけないで。")
      (wait)
      (text #:color 5 "【隣の男】にゃ？")
      (wait)
      (text #:color 7 "【" 0 "】黙れ。")
      (wait)))
    ((&& (== V 8) (== N 4) (== (: 14) 0))
     (<>
      (text #:color 6 "【美穂】" 0 "君の手って・・・大きい。")
      (wait)
      (text #:color 7 "【" 0 "】（大きいのは、手だけじゃないんだぜ・・・なんて口が割けても言えないな。）")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 8) (== N 4) (== (: 14) 1))
     (<>
      (text #:color 6 "【美穂】" 0 "君・・・お化粧が手についちゃう。")
      (wait)
      (text #:color 7 "【" 0 "】（すべすべした肌、柔らかい頬・・・かわいいなあ。）")
      (wait)))
    ((&& (== V 10) (== N 5) (== (: 16) 0))
     (<>
      (text #:color 6 "【美穂】いや・・・" 0 "君・・・。")
      (wait)
      (text #:color 7 "【" 0 "】だめだと言われても・・・困る。")
      (wait)
      (text #:color 6 "【美穂】こんな事をしてたら・・・芹沢先生に怒られちゃう。")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 10) (== N 5) (== (: 16) 1))
     (<>
      (text #:color 6 "【美穂】くすぐったい・・・" 0 "君。")
      (wait)
      (text #:color 7 "【" 0 "】（細い首だ・・・俺がなめる度に、びくびく震えてる。）")
      (wait)
      (text #:color 6 "【美穂】・・・いやあ。")
      (wait)))
    ((&& (== V 9) (== N 6) (== (: 17) 0))
     (<>
      (text #:color 6 "【美穂】あっ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】（ああ・・・美穂ちゃんの胸だあ。）")
      (wait)
      (text #:color 6 "【美穂】ん・・・。")
      (wait)
      (text #:color 7 "【" 0 "】（あまり大きくないけど・・・柔らかい。）")
      (wait)
      (text #:color 6 "【美穂】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】（美穂ちゃんの胸のぬくもりが・・・俺の手に伝わってくる。）")
      (wait)
      (set-reg: 17 1)))
    ((&& (== V 9) (== N 6) (== (: 17) 1))
     (<>
      (text #:color 6 "【美穂】" 0 "君・・・。")
      (wait)
      (text #:color 7 "【" 0 "】好きだから・・・触りたいんだ。")
      (wait)
      (text #:color 6 "【美穂】私・・・男の人に・・・こんな事されるの・・・一度もないの。")
      (wait)
      (text #:color 7 "【" 0 "】（かわいい・・・美穂ちゃんって、本当にかわいい。）")
      (wait)
      (set-reg: 17 2)))
    ((&& (== V 9) (== N 6) (== (: 17) 2))
     (<>
      (text #:color 6 "【美穂】いやあ。")
      (wait)
      (text #:color 7 "【" 0 "】（柔らかくて丸い・・・。）")
      (wait)
      (text #:color 6 "【美穂】" 0 "君・・・もうやめて。")
      (wait)))
    ((&& (== V 8) (== N 7) (== (: 18) 0))
     (<>
      (text #:color 6 "【美穂】いやっ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】（ちくしょう、脚が閉じてるから・・・触りにくいな。）")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 8) (== N 7) (== (: 18) 1))
     (<>
      (text #:color 6 "【美穂】あっ・・・ん。")
      (wait)
      (text #:color 7 "【" 0 "】（手を入れて・・・指先しか届かないぞ。）")
      (wait)
      (text #:color 6 "【美穂】やめて・・・こんな場所で・・・。")
      (wait)
      (set-reg: 18 2)))
    ((&& (== V 8) (== N 7) (== (: 18) 2))
     (<>
      (text #:color 6 "【美穂】いや・・・いやいや。")
      (wait)
      (text #:color 7 "【" 0 "】（美穂ちゃんのアソコは・・・少し湿ってるようだ。）")
      (wait)))
    ((&& (== V 5) (== N 8) (== (: 19) 0))
     (<>
      (text #:color 7 "【" 0 "】美穂ちゃん・・・もう少し、脚を開いて。")
      (wait)
      (text #:color 6 "【美穂】いや・・・。")
      (wait)
      (text #:color 7 "【" 0 "】好きなんだ・・・だから脚を開いて欲しい。")
      (wait)
      (text #:color 6 "【美穂】" 0 "君・・・。")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 5) (== N 8) (== (: 19) 1))
     (<>
      (text #:color 6 "【美穂】だめ・・・脚を開かせないで。")
      (wait)
      (text #:color 7 "【" 0 "】だって、触れないから・・・。")
      (wait)
      (text #:color 6 "【美穂】恥ずかしい・・・。")
      (wait)
      (set-reg: 19 2)))
    ((&& (== V 5) (== N 8) (== (: 19) 2))
     (<>
      (text #:color 7 "【" 0 "】（うーん、開いてくれそうにないな・・・。）")
      (wait)
      (text #:color 5 "【隣の男】にゃ？")
      (wait)
      (text #:color 7 "【" 0 "】黙ってろ。")
      (wait)))
    ((&& (== V 8) (== N 9) (== (: 20) 0))
     (<>
      (text #:color 6 "【美穂】ん・・・。")
      (wait)
      (text #:color 7 "【" 0 "】（美穂ちゃんの身体は・・・どこも柔らかいな。）")
      (wait)
      (set-reg: 20 1)))
    ((&& (== V 8) (== N 9) (== (: 20) 1))
     (<>
      (text #:color 6 "【美穂】" 0 "君・・・。")
      (wait)
      (text #:color 7 "【" 0 "】美穂ちゃんの・・・身体が欲しい。")
      (wait)
      (set-reg: 20 2)))
    ((&& (== V 8) (== N 9) (== (: 20) 2))
     (<>
      (text #:color 6 "【美穂】あん・・・" 0 "君って・・・やらしい。")
      (wait)
      (text #:color 7 "【" 0 "】好きな人だけに、いやらしくなれるんだ・・・。")
      (wait)))
    ((&& (== V 12) (== N 10) (== (: 21) 0))
     (<> (text #:color 7 "【" 0 "】（おいおいっ！！）") (wait) (set-reg: 21 1)))
    ((&& (== V 12) (== N 10) (== (: 21) 1))
     (<> (text #:color 7 "【" 0 "】（俺って余裕だなあ・・・こんな時にふざけるなんて。）") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))