(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\。
  #\の
  #\っ
  #\て
  #\な
  #\子
  #\生
  #\た
  #\だ
  #\先
  #\、
  #\真
  #\も
  #\い
  #\ん
  #\は
  #\で
  #\あ
  #\う
  #\か
  #\そ
  #\に
  #\を
  #\が
  #\見
  #\れ
  #\し
  #\と
  #\ら
  #\く
  #\事
  #\よ
  #\る
  #\俺
  #\つ
  #\ま
  #\人
  #\き
  #\こ
  #\夢
  #\徒
  #\前
  #\ゃ
  #\時
  #\え
  #\わ)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (sound 1)
 (set-var I 25)
 (proc 26)
 (set-reg: 835 0)
 (while
  (== 1 1)
  (<>
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((&& (== N 11) (== (: 604) 0))
     (<>
      (text #:color 7 "【" 0 "】そうだな・・・真子先生のデータを見よう。")
      (wait)
      (slot 1 3)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "39.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 9)
      (set-arr~ @ 6 1)
      (image "l07.pd8")
      (proc 25)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】『斎藤　真子』先生だな・・・先負学園の校医だ。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】生徒達の面倒見がよくて、優しくて、大人で、知的で、色っぽくて・・・男子生徒達は用がなくても保健室に行きたがる。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】何を隠そう、俺もその一人だ・・・他の女の子の前では緊張の『き』の字もないんだが、真子先生の前に立つとガラにもなく上がってしまうんだ。")
      (wait)
      (if-else (== (: 311) 1)
        (<>
         (slot 1 2)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "19.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "t.pd8")
         (proc 16)
         (set-arr~ @ 6 1)
         (image "g.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "tan.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "t.s4" (~ @ 2))
         (animate 0 0 2)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】そうそう、真子先生は駅前で薬局もやってるんだ・・・そこにはいつも妹の亜子さんがいる。")
         (wait))
        (<>))
      (if-else (== (: 253) 1)
        (<>
         (slot 1 4)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "g04.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "g04an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "g04.s4" (~ @ 2))
         (set-arr~ @ 7 0)
         (animate 0 8 0)
         (animate 4 8)
         (text #:color 7 "【" 0 "】そうそう、忘れちゃいけないのが・・・学校の階段で真子先生とぶつかった時の事だぞ。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text
          #:color
          7
          "【"
          0
          "】俺はなんてラッキーなんだ・・・先負学園の男子生徒の中で、あれほどの至近距離から真子先生の下着を見た者は俺ぐらいだぜ、うん。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】ああ・・・ずっと見ていたい。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait))
        (<>))
      (if-else (== (: 594) 1)
        (<>
         (slot 1 4)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "20.pd8")
         (proc 15)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "g02.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 25)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】そう言えば、屋上で真子先生と話をした時の内容は・・・けっこうきわどかったよな。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "g03.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "g03an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "g03.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (animate 0 8 1)
         (animate 4 8)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】あの時の真子先生も、すごく奇麗に見えた・・・できればずっと見ていたかったんだ。")
         (wait))
        (<>))
      (if-else (== (: 600) 1)
        (<>
         (slot 1 4)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "g05.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "g05an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "g05.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (animate 0 8 1)
         (animate 4 8)
         (text #:color 7 "【" 0 "】見ていたいじゃなくて・・・俺は見られちゃったんだよ、おい。")
         (wait)
         (text
          #:color
          7
          "【"
          0
          "】まいったよなあ、真子先生に言われるままに見せちゃったけど・・・真子先生、俺の事を軽蔑しただろうなあ。")
         (wait))
        (<>))
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "42.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (cond
       ((== (: 600) 0)
        (<> (text #:color 7 "【" 0 "】真子先生の私生活をのぞいてみたい・・・ゴクッ。") (wait)))
       ((== (: 600) 1)
        (<>
         (text #:color 7 "【" 0 "】でも真子先生って、俺のナニを見ても全然動じないんだもんな・・・つまんないの。")
         (wait)))
       (else (<>)))
      (set-reg: 608 1)
      (slot 1 2)
      (mes-jump "myroom.mes")))
    ((&& (== N 11) (== (: 604) 1))
     (<>
      (text #:color 7 "【" 0 "】真子先生のデータを見るのか？")
      (wait)
      (slot 1 3)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "39.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 9)
      (set-arr~ @ 6 1)
      (image "l07.pd8")
      (proc 25)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】真子先生とあんな事をするなんて・・・夢にも思わなかったな。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】そうだった・・・あれは夢だったんだ。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "19.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "t.pd8")
      (proc 16)
      (set-arr~ @ 6 1)
      (image "g.pd8")
      (proc 16)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "tan.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "t.s4" (~ @ 2))
      (animate 0 0 2)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】真子先生は駅前の薬局をやっていて・・・。")
      (wait)
      (slot 1 3)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "39.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 9)
      (set-arr~ @ 6 1)
      (image "g.pd8")
      (proc 25)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "tan.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "t.s4" (~ @ 2))
      (animate 0 0 1)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】なおかつ・・・先負学園の校医なんだ。")
      (wait)
      (text #:color 7 "【" 0 "】男子生徒からも、女子生徒からも人気があって・・・知的で、優しくて、大人の色気があって・・・。")
      (wait)
      (text #:color 7 "【" 0 "】俺にとっても・・・あこがれの存在だったんだ。")
      (wait)
      (slot 1 4)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "g04.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "g04an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "g04.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】そう言えば、階段で真子先生とぶつかって・・・真子のあられもない姿を見た事もあったな。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "20.pd8")
      (proc 15)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "g02.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 25)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】そして屋上で、真子先生が考え事をしてたんだ・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "g03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "g03an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "g03.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 7 "【" 0 "】あの時の真子先生の言葉の意味が・・・今になってやっとわかったよ、ははは。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】いくら知的で美人でも、真子先生だって女なんだよな。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "g05.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "g05an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "g05.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ははは・・・まさか、真子先生にナニを見てもらうとは思わなかったぜ。")
      (wait)
      (text #:color 7 "【" 0 "】医者に行く前に一度見てもらって・・・医者に行った後にもう一度見てもらって。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "g09.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "g09an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "g09.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】いきなり真子先生が俺のナニをナニして・・・。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】あの時の真子先生は・・・普通じゃなかったぜ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "g12.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "g11.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "g10.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "g07.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "g12an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "g12.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】そして・・・こんな事になってしまったんだ。")
      (wait)
      (text #:color 7 "【" 0 "】真子先生は自分で一枚づつ服を脱いで・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "g12.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "g11.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "g10.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "g12an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "g12.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "g12.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "g11.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "g12an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "g12.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】ああ・・・下着姿が色っぽかったよなあ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "g12.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "g12an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "g12.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】そう・・・これは夢だったんだ。")
      (wait)
      (text #:color 7 "【" 0 "】この姿も、何もかも・・・夢の中の出来事だ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "g08.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "g08an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "g08.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】そして二人が結ばれた事も・・・あれは夢なんだ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "42.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】" 0 "、本当に夢でいいのか・・・それで納得できるのか？")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】真子先生の事を考えると・・・胸がしめつけられそうだ。")
      (wait)
      (set-reg: 608 1)
      (slot 1 2)
      (mes-jump "myroom.mes")))
    (else (<>)))))
 (set-arr~ @ 7 1))