(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\ん
  #\の
  #\【
  #\】
  #\。
  #\っ
  #\た
  #\、
  #\て
  #\な
  #\だ
  #\に
  #\い
  #\し
  #\か
  #\は
  #\ち
  #\ゃ
  #\美
  #\穂
  #\と
  #\う
  #\が
  #\も
  #\そ
  #\を
  #\く
  #\で
  #\あ
  #\よ
  #\俺
  #\ら
  #\女
  #\る
  #\わ
  #\ま
  #\ー
  #\彼
  #\ど
  #\す
  #\れ
  #\つ
  #\じ
  #\子
  #\時
  #\さ
  #\会
  #\前
  #\け
  #\事
  #\ン
  #\『
  #\』
  #\ば
  #\感
  #\キ
  #\ス
  #\え
  #\？
  #\後
  #\脱
  #\言
  #\ぜ
  #\見
  #\一
  #\緒
  #\君
  #\中)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (sound 1)
 (set-var I 27)
 (proc 26)
 (set-reg: 835 0)
 (while
  (== 1 1)
  (<>
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((&& (== N 1) (== (: 710) 0))
     (<>
      (text #:color 7 "【" 0 "】よーし、美穂ちゃんのデータだな。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "m13.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "m13an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "m13.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】彼女の名前は『鈴木　美穂』・・・俺と同じ『先負学園』に通う同級生だな。")
      (wait)
      (text #:color 7 "【" 0 "】どちらかと言えば、大人しい感じがする子だ・・・俺も親しい訳じゃなから、よくわからないが・・・。")
      (wait)
      (text #:color 7 "【" 0 "】いやあ、それにしてもかわいい格好だったな・・・想像しただけで、いっぱつ抜けそうだぜ。")
      (wait)
      (if-else (== (: 277) 1)
        (<>
         (slot 1 3)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "25.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "m.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "man.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "m.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
         (set-arr~ @ 21 (+ 512 16))
         (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
         (set-arr~ @ 20 (&& (~ @ 20) 4095))
         (color 8)
         (set-arr~ @ 6 0)
         (set-arr~ @ 13 15 322 64 391)
         (clear)
         (text #:color 7 "【" 0 "】私服もいいが・・・美穂ちゃんのセーラー服もかわいかったな。")
         (wait)
         (text #:color 7 "【" 0 "】いつも見てるはずなのに、二人きりで放送室にいた時は柄にもなくドキドキしたぜ。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】そういえば、あの時の雰囲気は妙な感じだったな・・・どうしてだろう？")
         (wait))
        (<>))
      (if-else (== (: 313) 1)
        (<>
         (slot 1 2)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "29.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "f.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "fan.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "f.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text
          #:color
          7
          "【"
          0
          "】そして問題は、その後だよ・・・ああ、どうして亜子さんと一緒の時に美穂ちゃんに会っちゃうんだ！？")
         (wait)
         (text #:color 7 "【" 0 "】まったくついてないぜ、美穂ちゃんは無口になっちゃうし・・・とっとと行っちゃうし。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】と、考えてても仕方がない・・・時間は戻らないんだ。")
         (wait))
        (<>))
      (if-else (== (: 324) 1)
        (<>
         (slot 1 4)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "10.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 9)
         (set-arr~ @ 6 1)
         (image "m10.pd8")
         (proc 25)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "m10an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "m10.s4" (~ @ 2))
         (animate 0 0 1)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (animate 0 8 0)
         (animate 4 8)
         (text
          #:color
          7
          "【"
          0
          "】喫茶店の前で美穂ちゃんと会った後、今度は映画館の前で偶然会ったんだ・・・そして、一緒に映画を見る事になった。")
         (wait)
         (text #:color 7 "【" 0 "】かわいかったよなあ・・・いつも恥ずかしそうな表情をしてて、しぐさも女の子って感じだしな。")
         (wait)
         (slot 1 4)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "m08.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "m08an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "m08.s4" (~ @ 2))
         (set-arr~ @ 7 0)
         (animate 0 8 0)
         (animate 4 8)
         (text #:color 7 "【" 0 "】そして俺様は美穂ちゃんにキスしたんだ・・・彼女の唇は柔らかくて、暖かかった。")
         (wait)
         (text #:color 7 "【" 0 "】あの時、彼女の肩が小刻みに震えているのがわかった・・・そこがまたよかったんだけど。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "m09.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "m09an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "m09.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (animate 0 8 1)
         (animate 4 8)
         (animate 0 8 2)
         (animate 4 8)
         (text #:color 7 "【" 0 "】キスをしたあと・・・俺はかわいい美穂ちゃんの身体を触ったんだ。")
         (wait)
         (text #:color 7 "【" 0 "】うーん、あの時の美穂ちゃんの表情が、目をつぶらなくても頭に浮かんでくるぜ。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】美穂ちゃんの胸の感触、ふとももの暖かさ、くびれた腰、そして湿ったパンティ・・・。")
         (wait))
        (<>))
      (if-else (== (: 716) 1)
        (<>
         (slot 1 4)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "18.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "m12.pd8")
         (proc 16)
         (set-arr~ @ 7 0)
         (text
          #:color
          7
          "【"
          0
          "】そのあとは、しばらく美穂ちゃんと会わなかったが・・・彼女は学校の校門で俺の事を待ってたんだ。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "18.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "m.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "man.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "m.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】そう、俺に手紙を渡す為に・・・。")
         (wait)
         (text
          #:color
          7
          "【"
          0
          "】『"
          0
          "君の心の中には誰が住んでますか？・・・私の心の中には"
          0
          "君が住んでいます・・・美穂より。』か。")
         (wait))
        (<>))
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "42.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (cond
       ((== (: 324) 0)
        (<> (text #:color 7 "【" 0 "】とにかく美穂ちゃんは・・・中年男に好かれそうなロリロリ少女だな。") (wait)))
       ((&& (== (: 324) 1) (== (: 716) 0))
        (<>
         (text #:color 7 "【" 0 "】でも美穂ちゃんは、『" 0 "君のバカ』って言うと・・・走って行ってしまったんだよな。")
         (wait)
         (text #:color 7 "【" 0 "】あれ以来、美穂ちゃんに会ってない・・・なんだか気になるなあ。")
         (wait)))
       ((&& (== (: 716) 1) (== (: 728) 0))
        (<> (text #:color 7 "【" 0 "】うーん・・・美穂ちゃんは俺の事が好きなんだな。") (wait)))
       ((&& (== (: 728) 1) (== (: 733) 0))
        (<>
         (text #:color 7 "【" 0 "】で、その後はマンション前に美穂ちゃんが来て・・・。")
         (wait)
         (text #:color 7 "【" 0 "】彼女は走り去ってしまったんだ・・・たぶん美穂ちゃんとは、これでおしまいだろう。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】・・・はあ。")
         (wait)))
       ((== (: 733) 1)
        (<>
         (text #:color 7 "【" 0 "】なんて手紙を俺にくれたのに・・・どうしてマタロウとつき合うんだよ。")
         (wait)
         (text #:color 7 "【" 0 "】ちくしょう、俺が何をしたと言うんだあ！！")
         (wait)))
       (else (<>)))
      (set-reg: 608 1)
      (slot 1 2)
      (mes-jump "myroom.mes")))
    ((&& (== N 1) (== (: 710) 1))
     (<>
      (text #:color 7 "【" 0 "】美穂ちゃんのデータを・・・見るのか？")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "m13.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "m13an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "m13.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】彼女の名前は『鈴木　美穂』・・・俺と同じ『先負学園』に通う同級生だな。")
      (wait)
      (text #:color 7 "【" 0 "】どちらかと言えば、大人しい感じがする子だったけど、実際は・・・。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】うーん、よくわからないな。")
      (wait)
      (slot 1 3)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "25.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "m.pd8")
      (proc 16)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "man.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "m.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】彼女は放送部に入ってるんだよな・・・まあ、今となってはどうでもいい事だけど。")
      (wait)
      (text #:color 7 "【" 0 "】美穂ちゃんは、いつから俺の事が好きだったんだろ？・・・もっと早く言ってくれればいいのに。")
      (wait)
      (if-else (== (: 313) 1)
        (<>
         (slot 1 2)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "29.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "f.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "fan.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "f.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】そうだよ・・・亜子さんと一緒の時に、美穂ちゃんに会っちゃたんだよ。")
         (wait)
         (text #:color 7 "【" 0 "】美穂ちゃんの様子がおかしかったのも・・・亜子さんに対して嫉妬してたんだろう。")
         (wait))
        (<>))
      (slot 1 4)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "10.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 9)
      (set-arr~ @ 6 1)
      (image "m10.pd8")
      (proc 25)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "m10an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "m10.s4" (~ @ 2))
      (animate 0 0 1)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text
       #:color
       7
       "【"
       0
       "】喫茶店の前で美穂ちゃんと会った後、今度は映画館の前で偶然会ったんだ・・・そして、一緒に映画を見る事になった。")
      (wait)
      (text #:color 7 "【" 0 "】かわいかったよなあ・・・いつも恥ずかしそうな表情をしてて、しぐさも女の子って感じだしな。")
      (wait)
      (slot 1 4)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "m08.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "m08an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "m08.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】そして俺様は美穂ちゃんにキスしたんだ・・・彼女の唇は柔らかくて、暖かかった。")
      (wait)
      (text #:color 7 "【" 0 "】あの時、彼女の肩が小刻みに震えているのがわかった・・・そこがまたよかったんだけど。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "m09.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "m09an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "m09.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (animate 0 8 1)
      (animate 4 8)
      (animate 0 8 2)
      (animate 4 8)
      (text #:color 7 "【" 0 "】キスをしたあと・・・俺はかわいい美穂ちゃんの身体を触ったんだ。")
      (wait)
      (text #:color 7 "【" 0 "】うーん、あの時の美穂ちゃんの表情が、目をつぶらなくても頭に浮かんでくるぜ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】美穂ちゃんの胸の感触、ふとももの暖かさ、くびれた腰、そして湿ったパンティ・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "18.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "m12.pd8")
      (proc 16)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】そのあとは、しばらく美穂ちゃんと会わなかったが・・・彼女は学校の校門で俺の事を待ってたんだ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "18.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "m.pd8")
      (proc 16)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "man.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "m.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】そう、俺に手紙を渡す為に・・・。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】『"
       0
       "君の心の中には誰が住んでますか？・・・私の心の中には"
       0
       "君が住んでいます・・・美穂より。』か。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】俺が返事をしようとしても、そのたびに彼女は逃げちゃって・・・でも、そのあと美穂ちゃんがマンションの前に立ってたんだよ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "17.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 9)
      (set-arr~ @ 6 1)
      (image "m07.pd8")
      (proc 25)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "m07an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "m07.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】そして俺達はホテルに行ったんだ・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "m02.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "m03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "m04.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "m05.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "m06.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "m02an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "m02.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】俺は美穂ちゃんの服を脱がし・・・じゃなくて、服を脱いでもらったんだ。")
      (wait)
      (text #:color 7 "【" 0 "】まずはブラウスを脱いでもらって・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "m02.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "m03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "m04.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "m05.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "m02an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "m02.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】そしてスカートを脱いで・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "m02.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "m03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "m04.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "m02an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "m02.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】ストッキングを脱いで・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "m02.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "m03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "m02an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "m02.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】最後に・・・下着を俺が脱がせたんだ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "m02.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "m02an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "m02.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】美穂ちゃんの身体は小さく、胸も小さかったけど・・・すごくかわいかったよなあ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】だ、駄目だ・・・思い出すと、ポコチンが固くなってくる。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "m01.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "m01an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "m01.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 7 "【" 0 "】固くなったついでに思い出すと・・・こうなって、ああなって、最後には美穂ちゃんと結ばれたんだ。")
      (wait)
      (text #:color 7 "【" 0 "】うーん・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ちょっと・・・出ちゃったな。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "42.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】他の女の子と一緒にいる所を美穂ちゃんに見られたら・・・俺の人生は終ったようなもんだぞ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】気をつけよう・・・。")
      (wait)
      (set-reg: 608 1)
      (slot 1 2)
      (mes-jump "myroom.mes")))
    (else (<>)))))
 (set-arr~ @ 7 1))