(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\。
  #\い
  #\っ
  #\な
  #\、
  #\ん
  #\の
  #\て
  #\る
  #\う
  #\は
  #\だ
  #\か
  #\た
  #\あ
  #\し
  #\に
  #\よ
  #\？
  #\く
  #\こ
  #\ゃ
  #\が
  #\ち
  #\！
  #\れ
  #\も
  #\み
  #\と
  #\さ
  #\ら
  #\で
  #\君
  #\を
  #\そ
  #\ね
  #\美
  #\一
  #\事
  #\り
  #\ま
  #\ど
  #\す
  #\わ
  #\え
  #\じ
  #\ろ
  #\き
  #\私
  #\ー
  #\け
  #\や
  #\哉
  #\俺
  #\沙
  #\子
  #\ふ
  #\ン
  #\つ
  #\行
  #\言
  #\お
  #\穂
  #\夏
  #\舞
  #\部
  #\ば
  #\ず
  #\ぜ
  #\マ
  #\何
  #\太
  #\郎
  #\来
  #\人
  #\屋
  #\ひ
  #\家
  #\見
  #\め
  #\気
  #\日
  #\今
  #\シ
  #\ョ
  #\聞
  #\生
  #\思
  #\住
  #\前
  #\間
  #\待
  #\会
  #\ょ
  #\近
  #\所
  #\タ
  #\嫌
  #\達
  #\出
  #\度
  #\合
  #\先
  #\違
  #\変
  #\彼
  #\女
  #\戻
  #\二
  #\好
  #\時
  #\ト
  #\約
  #\束
  #\当
  #\ご
  #\せ
  #\手
  #\ぞ
  #\ス
  #\（
  #\）
  #\ロ
  #\訳
  #\ラ)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (if (&& (== H 830) (< (: 111) 6)) (<> (set-reg: 753 1)))
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "12.pd8")
 (proc 15)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "12.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (cond
  ((== (: 256) 0)
   (<>
    (text #:color 7 "【" 0 "】自分のマンションの前だ・・・どうするんだ？")
    (wait)
    (set-reg: 256 1)))
  ((&&
    (== (: 264) 1)
    (== (: 401) 0)
    (> T 800)
    (< T 2000)
    (> H 817)
    (== (: 402) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "o.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "oan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "o.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 18)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (text #:color 2 "【ひろみ】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】まずい・・・よな。")
    (wait)
    (text #:color 2 "【ひろみ】どうして来なかったの？・・・私、２時間も待ってたんだから。")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・デートの約束してたの、すっかり忘れてた。")
    (wait)
    (text #:color 2 "【ひろみ】私・・・約束破る人って、だいっ嫌い！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】嫌われても・・・当然だな。")
    (wait)
    (set-reg: 402 1)
    (set-reg: 103 0)))
  ((&&
    (== (: 464) 1)
    (== (: 465) 0)
    (== (: 479) 0)
    (> H 822)
    (> T 800)
    (< T 2359))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n.pd8")
    (proc 16)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 6)
    (proc 26)
    (text #:color 7 "【" 0 "】あ・・・まずい。")
    (wait)
    (text #:color 3 "【ちはる】まずいわよね・・・そりゃあまずいわよ。")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・は。")
    (wait)
    (text #:color 3 "【ちはる】私、ずっと待ってたんだから・・・約束を破るなんて最低だわ。")
    (wait)
    (text #:color 7 "【" 0 "】いや・・・実はね。")
    (wait)
    (text #:color 3 "【ちはる】言い訳なんか聞きたくない・・・さよならっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】ははは・・・は。")
    (wait)
    (text #:color 7 "【" 0 "】・・・はあ。")
    (wait)
    (set-reg: 479 1)
    (set-reg: 114 0)))
  ((&&
    (== (: 466) 1)
    (== (: 467) 0)
    (== (: 479) 0)
    (> H 822)
    (> T 800)
    (< T 2359))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n.pd8")
    (proc 16)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 6)
    (proc 26)
    (text #:color 7 "【" 0 "】あ・・・まずい。")
    (wait)
    (text #:color 3 "【ちはる】まずいわよね・・・そりゃあまずいわよ。")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・は。")
    (wait)
    (text #:color 3 "【ちはる】私、ずっと待ってたんだから・・・約束を破るなんて最低だわ。")
    (wait)
    (text #:color 7 "【" 0 "】いや・・・実はね。")
    (wait)
    (text #:color 3 "【ちはる】言い訳なんか聞きたくない・・・さよならっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】ははは・・・は。")
    (wait)
    (text #:color 7 "【" 0 "】・・・はあ。")
    (wait)
    (set-reg: 479 1)
    (set-reg: 114 0)))
  ((&&
    (== (: 745) 1)
    (== (: 746) 0)
    (> H 824)
    (> T 800)
    (< T 1900)
    (== (: 753) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "w.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "wan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "w.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 24)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あらら・・・。")
    (wait)
    (text #:color 3 "【舞】" 0 "君・・・どうして来なかったの？")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・。")
    (wait)
    (text #:color 3 "【舞】私・・・楽しみにしてたのに。")
    (wait)
    (text #:color 7 "【" 0 "】ごめん。")
    (wait)
    (text #:color 3 "【舞】もういいの、" 0 "君の気持ちがわかったし・・・私も" 0 "君を嫌いになる努力をするわ。")
    (wait)
    (text #:color 7 "【" 0 "】そ、そんなあ・・・。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】どうしよう・・・。")
    (wait)
    (set-reg: 753 1)
    (set-reg: 111 (- (: 111) 1))))
  ((&& (== (: 223) 1) (== (: 332) 0) (> T 900) (< T 1600) (== (: 685) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "a.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "aan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "a.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれ？")
    (wait)
    (text #:color 3 "【美沙】なんだ・・・" 0 "かよ。")
    (wait)
    (text #:color 7 "【" 0 "】マラソンでもやってるのか？")
    (wait)
    (text #:color 3 "【美沙】私だって、いつも陸上部の練習ばかりしてる訳じゃないぜ・・・今から友達と一緒に買物に行くんだ。")
    (wait)
    (text #:color 7 "【" 0 "】木刀でも買うんだろ？")
    (wait)
    (text #:color 3 "【美沙】" 0 "と話していると、アドレナリンが吹き出しそうになる・・・じゃあな！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】ありゃりゃ・・・走って行っちゃったよ。")
    (wait)
    (set-reg: 332 1)))
  ((&& (== (: 239) 1) (== (: 333) 0) (> T 900) (< T 1800) (== (: 641) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "c.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "can.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "c.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 60)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【よしこ】" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・芹沢先生。")
    (wait)
    (text #:color 6 "【よしこ】何をしているのかしら？")
    (wait)
    (text #:color 7 "【" 0 "】先生に会いに来たんです。")
    (wait)
    (text #:color 6 "【よしこ】あのね、会いに来たって・・・ここは道路で、偶然会っただけでしょ？")
    (wait)
    (text #:color 7 "【" 0 "】いいえ、ここで先生を待ち伏せしてたんです。")
    (wait)
    (text #:color 6 "【よしこ】もういいから・・・ちゃんと宿題もやるんですよ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】行っちゃった。")
    (wait)
    (set-reg: 333 1)))
  ((&& (== (: 251) 1) (== (: 324) 0) (== (: 334) 0) (> T 900) (< T 1700))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "man.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 27)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【美穂】あ・・・" 0 "君だ。")
    (wait)
    (text #:color 7 "【" 0 "】美穂ちゃん・・・会いたかったぜ。")
    (wait)
    (text #:color 6 "【美穂】私に？")
    (wait)
    (text #:color 7 "【" 0 "】当り前じゃないか・・・今からデートしよう。")
    (wait)
    (text #:color 6 "【美穂】私、これから出かけるの・・・また今度ね。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】ちぇっ・・・誰も俺を相手にしてくれない。")
    (wait)
    (set-reg: 334 1)))
  ((&& (== (: 182) 1) (== (: 335) 0) (> T 1900) (< T 2359) (== (: 412) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれれ？")
    (wait)
    (text #:color 6 "【さとみ】" 0 "・・・何をしてるの？")
    (wait)
    (text #:color 7 "【" 0 "】こっちが聞きたいよ・・・さとみこそ何をしてるんだ？")
    (wait)
    (text #:color 6 "【さとみ】" 0 "には関係ないじゃない・・・今から家に帰るだけよ。")
    (wait)
    (text #:color 7 "【" 0 "】ふーん、本当かなあ。")
    (wait)
    (text #:color 6 "【さとみ】じゃあね、ばいばい・・・いやらしい事をしちゃだめよ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】ん？・・・くんかくんか。")
    (wait)
    (text #:color 7 "【" 0 "】へえ、さとみって香水をつけてんだ。")
    (wait)
    (set-reg: 335 1)))
  ((&& (== (: 685) 1) (> T 800) (< T 1900) (== (: 686) 0) (== (: 690) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "a.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "aan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "a.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 3 "【美沙】あ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なんだ・・・美沙かよ。")
    (wait)
    (text #:color 3 "【美沙】" 0 "みたいなやつとは、話をしたくないぜ・・・じゃあな！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なんだよ・・・まだ怒ってるのか？")
    (wait)
    (set-reg: 686 1)))
  ((&& (== (: 692) 1) (> T 900) (< T 1900) (== (: 695) 0) (== (: 708) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "a.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "aan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "a.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 3 "【美沙】や、やあ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なんだよ・・・美沙じゃないか。")
    (wait)
    (text #:color 3 "【美沙】あのさあ・・・" 0 "。")
    (wait)
    (text #:color 7 "【" 0 "】なんだ・・・金はないぞ。")
    (wait)
    (text #:color 3 "【美沙】ち、違うよ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】俺は陸上部に入らないぞ。")
    (wait)
    (text #:color 3 "【美沙】違うってば・・・そんな事を言いに来たんじゃなくて。")
    (wait)
    (text #:color 7 "【" 0 "】キスでもしてやろうか？")
    (wait)
    (text #:color 3 "【美沙】・・・。")
    (wait)
    (text #:color 3 "【美沙】" 0 "の・・・馬鹿っ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】うーん、早いな・・・膝は完全に直ってるようだ。")
    (wait)
    (set-reg: 695 1)))
  ((&&
    (== (: 265) 1)
    (== (: 336) 0)
    (== (: 264) 1)
    (> T 800)
    (< T 1800)
    (< H 817))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "o.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "oan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "o.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 18)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 2 "【ひろみ】" 0 "君っ！！")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・ひろみちゃん。")
    (wait)
    (text #:color 2 "【ひろみ】今度の日曜日の事、ちゃんと覚えてる？")
    (wait)
    (text #:color 7 "【" 0 "】もちろんさ、矢吹町公園でデートするんだ・・・ちゃんと覚えてるよ。")
    (wait)
    (text #:color 2 "【ひろみ】よかった・・・約束の時間に遅れないでね、じゃあ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】わざわざ、それだけの事を言いに来たのか？")
    (wait)
    (set-reg: 336 1)))
  ((&& (== (: 265) 1) (== (: 336) 0) (== (: 264) 0) (> T 800) (< T 1800))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "o.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "oan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "o.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 18)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 2 "【ひろみ】" 0 "君っ！！")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・ひろみちゃん。")
    (wait)
    (text #:color 2 "【ひろみ】相変わらず元気がよさそうね・・・これからどこかに行くの？")
    (wait)
    (text #:color 7 "【" 0 "】えーと・・・俺はどうするつもりだったんだ！？")
    (wait)
    (text #:color 2 "【ひろみ】今度の日曜日、" 0 "君に断られちゃったから・・・別れようと思ってた彼氏とデートする事にしちゃった。")
    (wait)
    (text #:color 7 "【" 0 "】ふーん・・・。")
    (wait)
    (text #:color 2 "【ひろみ】彼氏ったらね、一緒に公園に行ってくれるって・・・ちゃんと昼間に。")
    (wait)
    (text #:color 7 "【" 0 "】へえ、よかったじゃない。")
    (wait)
    (text #:color 2 "【ひろみ】あ・・・私、もう行かないと。")
    (wait)
    (text #:color 2 "【ひろみ】" 0 "君、ばいばい！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】俺が女の子の誘いを断るなんて・・・地球の滅亡も近いぜ。")
    (wait)
    (set-reg: 336 1)))
  ((&& (== (: 745) 1) (> H 821) (< H 824) (> T 800) (< T 1800) (== (: 751) 0))
   (<>
    (text #:color 7 "【" 0 "】さてと・・・部屋に戻るのか？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "v.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "van.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "v.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 24)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 3 "【舞】" 0 "君・・・こんにちは。")
    (wait)
    (text #:color 7 "【" 0 "】舞ちゃんっ！！うれしいなあ、こんな所で会えるなんて。")
    (wait)
    (text #:color 3 "【舞】これからどこかに出かけるの？")
    (wait)
    (text #:color 7 "【" 0 "】いいや、戻って来たんだ・・・。")
    (wait)
    (text #:color 3 "【舞】" 0 "君の部屋って・・・どんな部屋なのかしら？")
    (wait)
    (set-reg: 101 1)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "汚染されてる") (text "無菌室") (text "１畳一間") (text "普通の部屋")))
    (if (== N 1)
      (<>
       (text #:color 7 "【" 0 "】俺の部屋は汚染されてるんだ・・・近づかない方がいいぜ。")
       (wait)
       (text #:color 3 "【舞】つまり・・・私は部屋の中に入れないって事よね。")
       (wait)
       (text #:color 7 "【" 0 "】（は、はずしてしまったあ！！）")
       (wait)))
    (if (== N 2)
      (<>
       (text #:color 7 "【" 0 "】俺の部屋は、無菌室のようにクリーンだぜ・・・ノミ一匹いないのさ。")
       (wait)
       (text #:color 3 "【舞】へえ・・・" 0 "君って神経質なんだ。")
       (wait)))
    (if (== N 3)
      (<>
       (text #:color 7 "【" 0 "】俺の部屋は、１畳一間の部屋さ・・・ちょっとすごいだろ。")
       (wait)
       (text #:color 3 "【舞】一畳一間って、どうやって寝てるのかしら？")
       (wait)
       (text #:color 7 "【" 0 "】立って寝てる。")
       (wait)
       (text #:color 3 "【舞】あははははっ・・・も、もうっお腹が痛くなっちゃうわ。")
       (wait)
       (set-reg: 111 (+ (: 111) 1))))
    (if (== N 4)
      (<>
       (text #:color 7 "【" 0 "】どんな部屋って・・・普通の部屋だぜ。")
       (wait)
       (text #:color 3 "【舞】色々と大変でしょう・・・一人だから。")
       (wait)
       (text #:color 7 "【" 0 "】舞ちゃん、洗濯しに来てくれる？")
       (wait)
       (text #:color 3 "【舞】ふふふ・・・" 0 "君って、洗濯してくれる女性がいっぱいいそうだから、私は遠慮しておくわ。")
       (wait)))
    (text #:color 3 "【舞】あ、いけない・・・これからお茶のお稽古なの。")
    (wait)
    (text #:color 7 "【" 0 "】お茶ねえ・・・。")
    (wait)
    (text #:color 3 "【舞】さようなら、" 0 "君・・・呼び止めてごめんなさい。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】お茶ねえ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】まあいいさ、日曜日になればずっと二人きりだ。")
    (wait)
    (set-reg: 751 1)))
  ((&&
    (== (: 726) 1)
    (> H 822)
    (> T 800)
    (< T 2200)
    (== (: 718) 0)
    (== (: 728) 0))
   (<>
    (text #:color 7 "【" 0 "】ふう・・・マンション前だぞ。")
    (wait)
    (text #:color 6 "【女の声】きゃっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "man.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 27)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【美穂】び、びっくりしたあ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】美穂ちゃん・・・俺の方が驚いたぜ。")
    (wait)
    (text #:color 6 "【美穂】ごめんなさい・・・誰かが後ろからつけて来るから、走って家に帰る途中だったの。")
    (wait)
    (text #:color 7 "【" 0 "】誰かがつけて来る？・・・いったい誰が？")
    (wait)
    (text
     #:color
     6
     "【美穂】ううん、恐くて後ろを振り向けなかったけど・・・私が止まると足音も止まって、私が走り出したらその人も走り出したの。")
    (wait)
    (text #:color 7 "【" 0 "】うーん・・・痴漢かな？")
    (wait)
    (text #:color 6 "【美穂】でも・・・もう平気みたい。")
    (wait)
    (text #:color 6 "【美穂】" 0 "君の姿を見て、どこかに行っちゃったのね・・・よかったあ。")
    (wait)
    (text #:color 7 "【" 0 "】（うーん・・・かわいいなあ。）")
    (wait)
    (text #:color 7 "【" 0 "】あのね、美穂ちゃん・・・。")
    (wait)
    (text #:color 6 "【美穂】だ、だめえ・・・手紙の返事は・・・恐くて聞けないの。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】美穂ちゃん、これから一緒にどこかに行かないか？")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あれれ・・・どこに行ったの？")
    (wait)
    (set-reg: 718 1)))
  ((&& (== (: 419) 1) (== (: 430) 0) (> T 1000) (< T 1900) (> H 825))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【さとみ】あ・・・" 0 "。")
    (wait)
    (text #:color 7 "【" 0 "】なんだよ・・・またさぼっているのか？")
    (wait)
    (text #:color 6 "【さとみ】違うわよ、今は休憩時間なの・・・一回家に戻って、これからまた喫茶店に行くところよ。")
    (wait)
    (text #:color 7 "【" 0 "】どうして俺の家の前にいるんだ？")
    (wait)
    (text #:color 6 "【さとみ】いいじゃない・・・別に。")
    (wait)
    (text #:color 7 "【" 0 "】本当は俺に会いに来たとか？")
    (wait)
    (text #:color 6 "【さとみ】うちのマスターってさ、店に出て接客するのをいやがるの・・・早く戻らないと怒られちゃうわ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】あらら・・・勝手に喋って、勝手に行っちゃったよ。")
    (wait)
    (if (== (: 420) 1)
      (<>
       (text #:color 7 "【" 0 "】・・・。")
       (wait)
       (text #:color 7 "【" 0 "】さとみのやつ・・・もう一度やって欲しくて、ここで俺を待っていたのか？")
       (wait)
       (text #:color 7 "【" 0 "】・・・。")
       (wait)
       (text #:color 7 "【" 0 "】違うな、考えすぎだ。")
       (wait)))
    (set-reg: 430 1)))
  ((&&
    (== (: 513) 1)
    (== (: 539) 0)
    (> H 827)
    (> T 800)
    (< T 2359)
    (== (: 546) 0)
    (== (: 533) 0)
    (== (: 527) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "jan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (text #:color 2 "【夏子】あ・・・じゃないわよ、" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・ごめん、約束した事をすっかり忘れてた。")
    (wait)
    (text #:color 2 "【夏子】別にかまわないのよ・・・" 0 "君が私と、関わりを持ちたくないって事がよくわかった訳だし。")
    (wait)
    (text #:color 7 "【" 0 "】そ、そんな事はないさあ。")
    (wait)
    (text #:color 2 "【夏子】街で見かけても、声をかけないでね・・・さようならっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】うーん、まいったな・・・嫌われてしまったようだ。")
    (wait)
    (set-reg: 109 0)
    (set-reg: 546 1)))
  ((&&
    (== (: 722) 1)
    (> H 824)
    (> T 800)
    (< T 2200)
    (== (: 711) 0)
    (== (: 850) 0))
   (<>
    (text #:color 7 "【" 0 "】さてと・・・部屋に戻るのか？")
    (wait)
    (text #:color 5 "【男の声】" 0 "君。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】な、なんだよ・・・マタロウじゃないか。")
    (wait)
    (text #:color 5 "【太郎】一つ聞きたい事があるんだが・・・。")
    (wait)
    (set-reg: 101 1)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "答える") (text "断る")))
    (if (== N 1) (<> (text #:color 7 "【" 0 "】なんだよ、聞きたい事って。") (wait)))
    (if (== N 2)
      (<>
       (text #:color 7 "【" 0 "】お断りだね、どうせロクな事じゃないんだ。")
       (wait)
       (text #:color 5 "【太郎】いいや、どうしても聞きたいんだ、ずいっ！！・・・聞いてもらうぞ、ずいっ！！")
       (wait)
       (text #:color 7 "【" 0 "】な、なんだよう・・・やけに迫力があるじゃないか。")
       (wait)))
    (text #:color 5 "【太郎】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】早く言えよ・・・マロタウ。")
    (wait)
    (text #:color 5 "【太郎】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】おい。")
    (wait)
    (text #:color 5 "【太郎】" 0 "君・・・悪いが急用を思い出したみたいだ、僕はこれで失敬する。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】なんだよ、マタロウのやつ・・・本当に急用を思い出したのか？")
    (wait)
    (set-reg: 850 1)))
  ((&& (== (: 467) 1) (== (: 845) 0) (> H 824) (> T 800) (< T 1900))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n10.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "n10an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n10.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 6)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ！！・・・ちはるちゃん！！")
    (wait)
    (text #:color 3 "【ちはる】び、びっくりしたあ・・・脅かさないでよ。")
    (wait)
    (text #:color 7 "【" 0 "】も、もしかして・・・俺の家に御飯を作りに来てくれたとか？")
    (wait)
    (text #:color 3 "【ちはる】へえ、" 0 "君の家ってこの近所なの？")
    (wait)
    (text #:color 7 "【" 0 "】近所って、ここは俺が住んでるマンションの前だぜ。")
    (wait)
    (text #:color 3 "【ちはる】一人暮らしって言ってたけど・・・ここに住んでるんだ。")
    (wait)
    (text #:color 7 "【" 0 "】さてと、今日は何を作ってくれるのかなあ。")
    (wait)
    (text #:color 3 "【ちはる】さてと、友達と約束してるの・・・じゃあね、" 0 "君。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】うっうっうっ・・・ちはるさんなんて大嫌いだあ。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・嘘。")
    (wait)
    (set-reg: 845 1)))
  ((&&
    (== (: 566) 1)
    (== (: 569) 1)
    (> H 817)
    (> T 800)
    (< T 1700)
    (== (: 572) 0)
    (== (: 571) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "e.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ean.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "e.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 22)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【かおり】あら・・・" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】あれれ！？・・・どうしてかおりさんが、こんな所にいるんだ！？")
    (wait)
    (text #:color 6 "【かおり】ふふふっ・・・彼氏の一人が、この近所に住んでるの。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 6 "【かおり】さーて、これから同伴して・・・その後、お店に行かないと。")
    (wait)
    (text #:color 6 "【かおり】じゃあね、" 0 "君・・・おなにいばかりしてちゃ駄目よ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】彼氏の『一人』がこの近所に住んでるね・・・ははは、さすがかおりさんだ。")
    (wait)
    (set-reg: 572 1)))
  ((&&
    (== (: 539) 1)
    (== (: 547) 0)
    (> H 827)
    (> T 800)
    (< T 2000)
    (== (: 533) 0)
    (== (: 527) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j11.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (text #:color 2 "【夏子】" 0 "君、こんにちは。")
    (wait)
    (text #:color 7 "【" 0 "】もしかして、俺の家に来てくれたの？")
    (wait)
    (text #:color 2 "【夏子】残念だけど違うわ・・・" 0 "君の家って、この近所なのよね。")
    (wait)
    (text #:color 7 "【" 0 "】うん・・・。")
    (wait)
    (text #:color 2 "【夏子】そんなにがっかりした顔をしないで・・・いつの日か、" 0 "君の部屋にお邪魔する事があるかもね。")
    (wait)
    (text #:color 7 "【" 0 "】できれば今日、そうして欲しいなあ・・・。")
    (wait)
    (text #:color 2 "【夏子】ごめんなさい、今日は大事な用があるの・・・じゃあね！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】ああ・・・行ってしまった。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】夏子さんの姿を見たあとは・・・なぜか切なくなってくるぜ。")
    (wait)
    (set-reg: 547 1)))
  ((&&
    (== (: 558) 1)
    (== (: 403) 1)
    (== (: 564) 0)
    (> H 824)
    (> T 800)
    (< T 1800))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "d.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "dan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "d.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 38)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 2 "【麗子】" 0 "・・・さん。")
    (wait)
    (text #:color 7 "【" 0 "】こんにちは・・・。")
    (wait)
    (text #:color 2 "【麗子】あの・・・私・・・。")
    (wait)
    (text #:color 7 "【" 0 "】え？")
    (wait)
    (text #:color 2 "【麗子】い、いえ・・・何でもありません。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】何か・・・言いたそうだったような？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "o14.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "o14an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "o14.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 4 "【冬彦】奇麗な人だな・・・君の知り合いか？")
    (wait)
    (text #:color 7 "【" 0 "】うわっと！！")
    (wait)
    (text #:color 4 "【冬彦】ひろみちゃんよりいいと思ってるな。")
    (wait)
    (text #:color 7 "【" 0 "】うるさいなあ、あっちに行け。")
    (wait)
    (text #:color 4 "【冬彦】なんだよう・・・僕は友達がいないんだぞう。")
    (wait)
    (text #:color 7 "【" 0 "】変な事を自慢するな、しっしっしっ！！")
    (wait)
    (text #:color 4 "【冬彦】泣くぞ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】しーーーーっ！！")
    (wait)
    (text #:color 4 "【冬彦】わかったよう・・・行けばいいんだろう。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】ちっ・・・なんて日だよ、まったく。")
    (wait)
    (set-reg: 564 1)))
  ((&& (== (: 603) 1) (> H 828) (> T 1900) (== (: 679) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "t.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "tan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "t.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 3)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれ？")
    (wait)
    (text #:color 2 "【亜子】ここが・・・" 0 "君が住んでるマンションよね。")
    (wait)
    (text #:color 7 "【" 0 "】そ、そうだけど・・・。")
    (wait)
    (text #:color 2 "【亜子】" 0 "君・・・浮気してないわよね？")
    (wait)
    (text #:color 7 "【" 0 "】う、う、うん。")
    (wait)
    (text #:color 2 "【亜子】それならいいの・・・じゃあ、おやすみなさい。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】亜子さん・・・まさか、ここで俺の事を待ってたんじゃないだろうな？")
    (wait)
    (set-reg: 679 1)))
  ((&&
    (== (: 514) 1)
    (== (: 515) 0)
    (== (: 519) 0)
    (> H 825)
    (> T 800)
    (< T 1900))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "q.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "qan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "q.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【くるみ】あ・・・" 0 "さん。")
    (wait)
    (text #:color 7 "【" 0 "】くるみちゃん・・・一哉と会えたのかい？")
    (wait)
    (text #:color 6 "【くるみ】ううん、最近電話もしてないし・・・もういいの。")
    (wait)
    (text #:color 7 "【" 0 "】（もういいって・・・どういう事なんだ？）")
    (wait)
    (text #:color 6 "【くるみ】この間、ごめんなさい・・・変な事を言っちゃって。")
    (wait)
    (text #:color 7 "【" 0 "】ああ・・・ちょうどこの場所だったよな。")
    (wait)
    (text #:color 6 "【くるみ】あの事は忘れて・・・私、もう大丈夫だから。")
    (wait)
    (text #:color 7 "【" 0 "】（くるみちゃん、妙に元気だけど・・・何かあったのかな？）")
    (wait)
    (text #:color 6 "【くるみ】" 0 "さん・・・ばいばい。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】変なの・・・ちょっと前まで、落ち込んでいたのに。")
    (wait)
    (set-reg: 519 1)))
  ((&&
    (== (: 514) 1)
    (== (: 515) 1)
    (== (: 519) 0)
    (> H 825)
    (> T 800)
    (< T 1900))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "q.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "qan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "q.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【くるみ】あ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】くるみちゃん・・・。")
    (wait)
    (text #:color 6 "【くるみ】なんだか・・・恥ずかしい。")
    (wait)
    (text #:color 7 "【" 0 "】お父さんに怒られなかった？")
    (wait)
    (text #:color 6 "【くるみ】怒られたけど・・・平気。")
    (wait)
    (text #:color 7 "【" 0 "】ふーん。")
    (wait)
    (text #:color 6 "【くるみ】" 0 "さん・・・私、あれから一哉君の家に電話してないの。")
    (wait)
    (text #:color 7 "【" 0 "】そうなんだ。")
    (wait)
    (text #:color 6 "【くるみ】もちろん、一哉君の家にも行ってないのよ。")
    (wait)
    (text #:color 7 "【" 0 "】そうか・・・。")
    (wait)
    (text #:color 6 "【くるみ】" 0 "さんが言った通りね・・・私、変わっちゃったみたい。")
    (wait)
    (text #:color 7 "【" 0 "】？？？")
    (wait)
    (text #:color 6 "【くるみ】もういいの一哉君の事は・・・じゃあね、" 0 "さん。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】うーん・・・彼女とエッチな事をしたんだよな、俺は。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あれは・・・夢だったのか？")
    (wait)
    (set-reg: 519 1)))
  ((&& (== (: 641) 0) (> H 817) (> T 800) (< T 2100) (== (: 642) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "c.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "can.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "c.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 60)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【よしこ】あら、" 0 "君・・・。")
    (wait)
    (text #:color 7 "【" 0 "】さようなら、よしこ先生。")
    (wait)
    (text #:color 6 "【よしこ】待ちなさい・・・私から逃げるって事は、また何かしたのね？")
    (wait)
    (text #:color 7 "【" 0 "】ははは、条件反射かな？・・・よしこ先生を見ると、ついつい。")
    (wait)
    (text #:color 6 "【よしこ】その『よしこ』先生はよしなさい。")
    (wait)
    (text #:color 6 "【よしこ】ちゃんと勉強をするんですよ・・・学生の本分は勉強ですからね。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】行ってしまった・・・よしこ先生は、ここで何をしてたんだろ？")
    (wait)
    (set-reg: 642 1)))
  ((&& (== (: 648) 1) (> H 820) (> T 800) (< T 2100) (== (: 650) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【太郎】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】な、なんだ・・・マタロウじゃないかよ。")
    (wait)
    (text #:color 5 "【太郎】君も知ってるのか？")
    (wait)
    (text #:color 7 "【" 0 "】何をだ？")
    (wait)
    (text #:color 5 "【太郎】学校の近くで、女性が痴漢に襲われたそうだ。")
    (wait)
    (text #:color 7 "【" 0 "】痴漢！？・・・いったい誰が襲われたんだ！？")
    (wait)
    (text #:color 5 "【太郎】そんな事までは知らない・・・・それより早く自首したまえ、悪い事をすればいずれ捕まる運命だ。")
    (wait)
    (text #:color 7 "【" 0 "】あのなあ・・・確かに俺はスケベだけど、痴漢なんて卑劣な真似しないんだよっ！！")
    (wait)
    (text #:color 5 "【太郎】まあいい、いずれ犯人は捕まるだろう・・・その時が楽しみだ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (if (== (: 647) 1) (<> (text #:color 7 "【" 0 "】あの悲鳴が・・・もしかして？") (wait)))
    (set-reg: 650 1)))
  ((&& (== (: 641) 1) (== (: 653) 0) (> T 900) (< T 1900) (> H 826))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "c.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "can.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "c.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 60)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (text #:color 6 "【よしこ】" 0 "君・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 6 "【よしこ】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】メガネ・・・またかけたんだね。")
    (wait)
    (text #:color 6 "【よしこ】そうですね・・・コンタクトにしようかとも、思ったんですけど。")
    (wait)
    (text #:color 7 "【" 0 "】メガネかけてても・・・先生は奇麗だよ。")
    (wait)
    (text #:color 6 "【よしこ】ありがとう。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 6 "【よしこ】じゃあ、私はこれで・・・ちゃんと勉強してくださいね。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】うーん・・・元気そうだったな。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なんだか、前と感じが違うような気がしたけど・・・気のせいかな？")
    (wait)
    (set-reg: 653 1)))
  ((&&
    (== (: 728) 1)
    (== (: 710) 1)
    (> H 827)
    (< H 829)
    (> T 800)
    (< T 2359)
    (== (: 735) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ぎょっ！？")
    (wait)
    (text #:color 5 "【太郎】君達は・・・君達は・・・不潔だあっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あいつ・・・走り方を美沙に習ったほうがいいな。")
    (wait)
    (set-reg: 735 1)))
  ((&&
    (== (: 728) 1)
    (== (: 710) 0)
    (> H 827)
    (< H 829)
    (> T 800)
    (< T 2359)
    (== (: 735) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【太郎】やあ、" 0 "君・・・ふっふっふっ。")
    (wait)
    (text #:color 7 "【" 0 "】何か言いたい事がありそうだな・・・。")
    (wait)
    (text #:color 5 "【太郎】別に・・・ふっふっふっ。")
    (wait)
    (text #:color 7 "【" 0 "】変なやつだな・・・用がないなら、あっちに行け。")
    (wait)
    (text #:color 5 "【太郎】僕はもう、君の力を必要としていないんだ・・・あっちに行ってやるよ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】気持ち悪いやつだぜ・・・。")
    (wait)
    (set-reg: 735 1)))
  ((&&
    (== (: 519) 1)
    (== (: 527) 0)
    (> H 829)
    (> T 830)
    (< T 2200)
    (== (: 514) 1)
    (== (: 515) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "i.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "r.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ran.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "r.s4" (~ @ 2))
    (animate 0 0 2)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【一哉】よ、よう・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あれれれ！？")
    (wait)
    (text #:color 6 "【くるみ】" 0 "さん、こんにちは・・・くすくすくす。")
    (wait)
    (text #:color 7 "【" 0 "】なんだよ・・・どうなってるんだ？")
    (wait)
    (text #:color 6 "【くるみ】あのね、一哉君がどうしても、もう一度つき合いたいって言うから・・・つき合ってあげるの。")
    (wait)
    (text #:color 5 "【一哉】ははは・・・はは・・・は。")
    (wait)
    (text #:color 6 "【くるみ】でもね、私は言ったの・・・好きな人がいるって。")
    (wait)
    (text #:color 5 "【一哉】ははは・・・は。")
    (wait)
    (text #:color 6 "【くるみ】そうしたらね、最初は友達でもいいからって。")
    (wait)
    (text #:color 7 "【" 0 "】一哉・・・思いっきり、立場が弱くなってないかい？")
    (wait)
    (text #:color 5 "【一哉】そ、そんな事はないさあ。")
    (wait)
    (text #:color 6 "【くるみ】くすくすくす・・・一哉君、私がまた好きになるまで、キスも変な事もしないって。")
    (wait)
    (text #:color 5 "【一哉】男として当然の事だよな、" 0 "？")
    (wait)
    (text #:color 6 "【くるみ】でもね、一哉君・・・永遠にキスできないと思うの。")
    (wait)
    (text #:color 5 "【一哉】ど、どうして！？")
    (wait)
    (text #:color 6 "【くるみ】だって私・・・好きな人ができちゃったんだもん。")
    (wait)
    (text #:color 5 "【一哉】そ、そんなあ。")
    (wait)
    (text #:color 6 "【くるみ】ね、" 0 "さん？")
    (wait)
    (text #:color 7 "【" 0 "】な、なんだよ。")
    (wait)
    (text #:color 6 "【くるみ】何でもない・・・くすくすくす。")
    (wait)
    (text #:color 5 "【一哉】ああ・・・こんな事になるなんて・・・どこで、どう間違えたんだろ？")
    (wait)
    (text #:color 6 "【くるみ】じゃあね、" 0 "さん・・・また会いましょ。")
    (wait)
    (text #:color 5 "【一哉】お、おい・・・待てよ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】あーあ・・・一哉がくるみちゃんを、必死で追いかけてるよ。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】しかし、何だったんだ・・・今のは？")
    (wait)
    (set-reg: 527 1)
    (set-reg: 734 1)))
  ((&&
    (== (: 519) 1)
    (== (: 527) 0)
    (> H 829)
    (> T 830)
    (< T 2200)
    (== (: 515) 1))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "q.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "qan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "q.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれ・・・くるみちゃん。")
    (wait)
    (text #:color 6 "【くるみ】私ね・・・" 0 "さんに会いに来たの。")
    (wait)
    (text #:color 7 "【" 0 "】俺に？")
    (wait)
    (text #:color 6 "【くるみ】うん、" 0 "さんに・・・だからもっとこっちに来て。")
    (wait)
    (text #:color 7 "【" 0 "】こう？")
    (wait)
    (text #:color 6 "【くるみ】もっと。")
    (wait)
    (text #:color 7 "【" 0 "】こ、このくらい？")
    (wait)
    (text #:color 6 "【くるみ】ううん、このくらい近くじゃないと・・・いや。")
    (wait)
    (slot 1 8)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "q03.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 25)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "q03an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "q03.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 29)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ぎょっ！？")
    (wait)
    (text #:color 6 "【くるみ】昨日の夜ね・・・一哉君が家に来たの。")
    (wait)
    (text #:color 7 "【" 0 "】そ、そう？")
    (wait)
    (text #:color 6 "【くるみ】でね・・・もう一度、私とつき合いたいって。")
    (wait)
    (text #:color 7 "【" 0 "】ふ、ふーん。")
    (wait)
    (text #:color 6 "【くるみ】どう思う？")
    (wait)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "つき合う") (text "つき合わない")))
    (if (== N 1)
      (<>
       (text #:color 7 "【" 0 "】そ、そりゃあ・・・せっかくだからつき合ったほうがいいんじゃない？")
       (wait)
       (text #:color 6 "【くるみ】そう・・・そういう事を言うんだ。")
       (wait)
       (text #:color 7 "【" 0 "】え？")
       (wait)
       (set-reg: 112 (- (: 112) 1))))
    (if (== N 2)
      (<>
       (text #:color 7 "【" 0 "】やめろよ、もう・・・一哉のやつ勝手すぎるぜ。")
       (wait)
       (set-reg: 112 (+ (: 112) 1))))
    (text #:color 6 "【くるみ】私ね、一哉君にそう言われた時に・・・" 0 "さんの顔が浮かんだの。")
    (wait)
    (text #:color 7 "【" 0 "】俺の顔が？")
    (wait)
    (text #:color 6 "【くるみ】そうしたら、勝手に口が動いて・・・いやだって言っちゃった。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 6 "【くるみ】一哉君、うなだれて帰って行ったわ。")
    (wait)
    (text #:color 7 "【" 0 "】うーん・・・。")
    (wait)
    (text #:color 6 "【くるみ】もう一度・・・キスして。")
    (wait)
    (text #:color 7 "【" 0 "】え！？・・・こ、ここで！？")
    (wait)
    (text #:color 6 "【くるみ】・・・ちゅっ！！")
    (wait)
    (text #:color 7 "【" 0 "】（ぎょっ！？）")
    (wait)
    (text #:color 6 "【くるみ】この事を言いたかっただけなの・・・" 0 "さん、ばいばい！！")
    (wait)
    (slot 1 2)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】俺の方が・・・キスされちゃった。")
    (wait)
    (set-reg: 527 1)))
  ((&& (== (: 709) 1) (== (: 711) 0) (> H 828) (> T 1800) (== (: 714) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "l.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "lan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "l.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (text #:color 3 "【美沙】よう、" 0 "・・・。")
    (wait)
    (text #:color 7 "【" 0 "】脚は・・・もういいのか？")
    (wait)
    (text #:color 3 "【美沙】まあまあだな。")
    (wait)
    (text #:color 7 "【" 0 "】そうか・・・まあまあか。")
    (wait)
    (text #:color 3 "【美沙】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 3 "【美沙】私・・・やっぱり・・・。")
    (wait)
    (text #:color 7 "【" 0 "】え？")
    (wait)
    (text #:color 3 "【美沙】い、いいや、何でもないよ・・・美穂を泣かすなよ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】お、おい・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】行っちゃった・・・。")
    (wait)
    (set-reg: 714 1)))
  ((&& (== (: 709) 1) (== (: 711) 1) (> H 828) (> T 1800) (== (: 714) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "l.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "lan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "l.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (text #:color 3 "【美沙】" 0 "・・・。")
    (wait)
    (text #:color 7 "【" 0 "】脚は・・・もういいのか？")
    (wait)
    (text #:color 3 "【美沙】うん・・・だいぶよくなったみたい。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 3 "【美沙】私・・・陸上部をやめるわよ。")
    (wait)
    (text #:color 7 "【" 0 "】（困った・・・。）")
    (wait)
    (text #:color 3 "【美沙】" 0 "は私の事が・・・好き？")
    (wait)
    (set-reg: 101 1)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "好き") (text "嫌い")))
    (if (== N 1)
      (<>
       (text #:color 7 "【" 0 "】す、好きだよ・・・。")
       (wait)
       (text #:color 3 "【美沙】うれしい・・・。")
       (wait)
       (set-reg: 113 (+ (: 113) 2))))
    (if (== N 2)
      (<>
       (text #:color 7 "【" 0 "】き、嫌いだあ。")
       (wait)
       (text #:color 3 "【美沙】！？")
       (wait)
       (text #:color 7 "【" 0 "】き、き、嫌いだあ！！")
       (wait)
       (text #:color 3 "【美沙】" 0 "なんか・・・死んじゃえっ！！")
       (wait)
       (set-reg: 113 (- (: 113) 5))
       (set-reg: 715 1)
       (set-var N 0)
       (slot 1 2)
       (mes-jump "town1.mes")))
    (text #:color 7 "【" 0 "】ははは・・・は。")
    (wait)
    (text #:color 3 "【美沙】その言葉を聞きたかったの・・・これで安心して眠れる。")
    (wait)
    (text #:color 7 "【" 0 "】よ、よかったねえ。")
    (wait)
    (text #:color 3 "【美沙】夏休みも、もう終りだけど・・・今度は学校でいっぱい会えるわね。")
    (wait)
    (text #:color 7 "【" 0 "】そ、そうだねえ。")
    (wait)
    (text #:color 3 "【美沙】一緒に学校に行って、一緒に帰ろうね。")
    (wait)
    (text #:color 7 "【" 0 "】い、いいなあ。")
    (wait)
    (text #:color 3 "【美沙】陸上部にいた時より、目の前がバラ色に見えるの・・・これも" 0 "のおかげ。")
    (wait)
    (text #:color 7 "【" 0 "】そ、そう？")
    (wait)
    (text #:color 3 "【美沙】じゃあね、" 0 "・・・私の夢を見てね。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】これで・・・いいのだろうか？")
    (wait)
    (set-reg: 714 1)))
  ((&&
    (> H 829)
    (> T 830)
    (< T 2200)
    (== (: 515) 1)
    (== (: 533) 0)
    (== (: 544) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "j12.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j11.s4" (~ @ 2))
    (animate 0 0 2)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 2 "【夏子】あ・・・" 0 "君。")
    (wait)
    (text #:color 5 "【一哉】ははは・・・" 0 "、元気そうだな。")
    (wait)
    (text #:color 7 "【" 0 "】一哉と夏子さんが一緒にいるって事は・・・どういう事なんだ？")
    (wait)
    (text #:color 5 "【一哉】実は・・・くるみちゃんにフラれた事を夏子さんに話したらさ、夏子さんが準恋人にしてくれるって。")
    (wait)
    (text #:color 7 "【" 0 "】準恋人？・・・夏子さん、ボランティアしちゃいけないな。")
    (wait)
    (text #:color 2 "【夏子】あはは・・・私もそう思ったんだけど、一哉君の話を聞いてたらかわいそうになっちゃって。")
    (wait)
    (text #:color 7 "【" 0 "】一哉に同情は禁物だよ・・・そんな事より、俺とつき合おう。")
    (wait)
    (text #:color 5 "【一哉】" 0 "ーっ・・・冗談でもやめてくれよう。")
    (wait)
    (text #:color 7 "【" 0 "】冗談じゃないのに。")
    (wait)
    (text #:color 2 "【夏子】まさか、一哉君の方がくるみちゃんにフラれるとは思ってなかったわね・・・びっくりしちゃった。")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・まあ、色々とあるんじゃないの？")
    (wait)
    (text #:color 2 "【夏子】あるわよねえ、" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】（な、なんだ・・・俺とくるみちゃんの事を知ってるのか？）")
    (wait)
    (text #:color 2 "【夏子】" 0 "君もがんばってね、色々と。")
    (wait)
    (text #:color 7 "【" 0 "】言われなくたって、がんばるよ・・・俺は。")
    (wait)
    (text #:color 5 "【一哉】じゃあな、" 0 "・・・俺達、これから食事をしに行くんだ。")
    (wait)
    (text #:color 2 "【夏子】" 0 "君も来る？")
    (wait)
    (text #:color 5 "【一哉】夏子さん、やめてくれよ・・・せっかく二人で行こうって言ったのに。")
    (wait)
    (text #:color 2 "【夏子】あはは、わかってるわよ・・・じゃあね、" 0 "君。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】夏子さんと一哉がねえ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】まあ、準恋人って事は恋人じゃないって事だし・・・まあフラれるぜ、一哉のやつは・・・ははは。")
    (wait)
    (set-reg: 533 1)))
  ((&&
    (== (: 728) 1)
    (== (: 710) 0)
    (> H 827)
    (< H 830)
    (> T 800)
    (< T 2000)
    (== (: 744) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "man.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 27)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (text #:color 6 "【美穂】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】美穂ちゃん・・・あ、あのさ。")
    (wait)
    (text #:color 6 "【美穂】嫌い・・・" 0 "君なんて。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あーあ・・・なんだか寂しい気分だぜ。")
    (wait)
    (set-reg: 744 1)
    (set-reg: 102 (- (: 102) 5))))
  ((&&
    (== (: 728) 1)
    (== (: 710) 1)
    (> T 800)
    (< T 1900)
    (> H 827)
    (< H 830)
    (== (: 744) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "man.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 27)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【美穂】" 0 "君・・・。")
    (wait)
    (text #:color 7 "【" 0 "】美穂ちゃんじゃないか・・・。")
    (wait)
    (text #:color 6 "【美穂】どうしても" 0 "君の顔が見たくなって・・・ずっとここで待ってたの。")
    (wait)
    (text #:color 7 "【" 0 "】俺の顔が見たくて、ここで待ってた！？")
    (wait)
    (text #:color 6 "【美穂】よかったあ、" 0 "君が顔が見れて・・・じゃあね、ばいばい。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】かわいいなあ、言うべきか・・・恐いなあ、と言うべきか。")
    (wait)
    (set-reg: 744 1)))
  ((&& (== (: 710) 0) (== H 830) (> T 800) (< T 1900) (== (: 733) 0))
   (<>
    (text #:color 7 "【" 0 "】ふう・・・明日で夏休みも終りかあ。")
    (wait)
    (text #:color 5 "【男の声】" 0 "君。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】げっ！？・・・またマタロウか。")
    (wait)
    (text #:color 5 "【太郎】ふっふっふっ・・・今日は君に、僕の彼女を紹介しようと思ってな。")
    (wait)
    (text #:color 7 "【" 0 "】彼女！？・・・マタロウに！？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "f.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 2)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 27)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【美穂】こんにちは、" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】げえーーっ！？")
    (wait)
    (text #:color 5 "【太郎】まあそういう訳だ・・・これからもよろしく頼むよ、" 0 "君。")
    (wait)
    (text #:color 6 "【美穂】太郎君ったらね、私のあとをつけるほど好きなんだって・・・私の事が。")
    (wait)
    (text #:color 6 "【美穂】私、その事を聞いて感激しちゃったの。")
    (wait)
    (text #:color 7 "【" 0 "】ち、ちょっと違うような気が・・・する。")
    (wait)
    (text #:color 5 "【太郎】負け惜しみか、" 0 "君・・・ふっふっふっ。")
    (wait)
    (text #:color 6 "【美穂】じゃあね・・・私達、これからデートなの。")
    (wait)
    (text #:color 5 "【太郎】僕達はこれで失敬するよ・・・ふっふっふっ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】はあ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ふう・・・。")
    (wait)
    (text #:color 7 "【" 0 "】どうして・・・こうなるの？")
    (wait)
    (set-reg: 733 1)
    (set-reg: 102 (- (: 102) 5))))
  ((&& (== (: 753) 1) (== H 830) (> T 800) (< T 1900) (== (: 760) 0))
   (<>
    (slot 1 6)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "v14.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "v14an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "v14.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (animate 0 8 1)
    (animate 4 8)
    (sound 1)
    (set-var I 24)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・！？")
    (wait)
    (text #:color 4 "【健二】はーっはっはっはっはっ！！")
    (wait)
    (text #:color 3 "【舞】・・・。")
    (wait)
    (text #:color 4 "【健二】そういう事だよ、" 0 "君。")
    (wait)
    (text #:color 3 "【舞】・・・。")
    (wait)
    (text #:color 4 "【健二】そう、これでいいのさ！！")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 4 "【健二】何も言えないだろう、言葉などあるはずがないもんな、はーっはっはっはっ！！")
    (wait)
    (text #:color 3 "【舞】・・・。")
    (wait)
    (text #:color 4 "【健二】" 0 "君、もう舞に手を出すなよ・・・彼女は僕とつき合うと言ってくれたんだからな。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 4 "【健二】じゃあな、" 0 "君・・・ホテルに行こう、舞。")
    (wait)
    (text #:color 3 "【舞】はい・・・。")
    (wait)
    (slot 1 2)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "12.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なんで・・・こうなるの？")
    (wait)
    (set-reg: 760 1)
    (set-reg: 111 (- (: 111) 5))))
  ((== (: 256) 1)
   (<> (text #:color 7 "【" 0 "】ここは俺が住んでいるマンションの前だ・・・。") (wait))))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "中に入る") (text "他の場所に行く") (text "やめる")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・俺も猛烈に部屋に戻りたい気分だぜ。")
         (wait)
         (slot 1 2)
         (mes-jump "myroom.mes")))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】部屋に戻っても何もする事はないし・・・他の場所に行くか。")
         (wait)
         (set-var N 0)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((== N 3) (<> (text #:color 7 "【" 0 "】え！？・・・ここで何をするの！？") (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 1) (== (: 10) 0))
     (<>
      (text #:color 7 "【" 0 "】電柱だな・・・これがないと俺は、テレビを見る事もコンピューターを使う事もできないんだ。")
      (wait)
      (set-reg: 10 1)))
    ((&& (== V 1) (== N 1) (== (: 10) 1))
     (<> (text #:color 7 "【" 0 "】電柱だぜ・・・好きなのか？") (wait)))
    ((&& (== V 1) (== N 2) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】マンションの入口だ・・・中に入って、階段を上がれば自分の部屋に戻る事ができる。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 1) (== N 2) (== (: 11) 1))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】半円のアーチが俺のマンションの入口だ・・・建物自体は、マンションと言うよりアパートって感じだな。")
      (wait)))
    ((&& (== V 1) (== N 3) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】マンションの周りを、塀が囲んでいる・・・当然の事だな。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 3) (== (: 12) 1))
     (<>
      (text #:color 7 "【" 0 "】アーチの両側には、塀が続いている・・・俺が子供だったら、この上に乗って遊ぶだろう。")
      (wait)))
    ((&& (== V 1) (== N 4) (== (: 13) 0))
     (<>
      (text #:color 7 "【" 0 "】俺が住んでるマンションだ・・・俺の部屋は２階だぞ。")
      (wait)
      (set-reg: 13 1)))
    ((&& (== V 1) (== N 4) (== (: 13) 1))
     (<>
      (text #:color 7 "【" 0 "】マンションと呼ぶ事がおこがましい建物だ・・・どうせだったら、タイル貼りにすればいいのに。")
      (wait)))
    ((&& (== V 1) (== N 5) (== (: 14) 0))
     (<>
      (text #:color 7 "【" 0 "】このあたりは住宅街だ・・・家並がずっと続いてるな。")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 1) (== N 5) (== (: 14) 1))
     (<> (text #:color 7 "【" 0 "】住宅地だぜ・・・色々な人が住んでいるんだ。") (wait)))
    ((&& (== V 1) (== N 6) (== (: 15) 0))
     (<> (text #:color 7 "【" 0 "】窓を開けると庭が見える家だな・・・。") (wait) (set-reg: 15 1)))
    ((&& (== V 1) (== N 6) (== (: 15) 1))
     (<>
      (text #:color 7 "【" 0 "】この家には、誰が住んでいるんだろ？")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】想像してわかる訳がないか・・・無駄な事を考えるのはよそうぜ。")
      (wait)))
    ((&& (== V 1) (== N 7) (== (: 16) 0))
     (<>
      (text #:color 7 "【" 0 "】木がたくさん生えている・・・って言うか、家を建てる時に植えられたものだろう。")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 1) (== N 7) (== (: 16) 1))
     (<>
      (text #:color 7 "【" 0 "】最初からこの地に生えてた木は、一本もないだろう。")
      (wait)
      (text #:color 7 "【" 0 "】１００年くらい前は、このあたりはどんな景色だったんだろ？")
      (wait)))
    ((&& (== V 1) (== N 8) (== (: 17) 0))
     (<>
      (text #:color 7 "【" 0 "】建物と木の隙間から、空が見えている・・・。")
      (wait)
      (cond
       ((> T 1900) (<> (text #:color 7 "【" 0 "】星は見えないな・・・雲ってるのか？") (wait)))
       ((&& (> T 0) (< T 600))
        (<> (text #:color 7 "【" 0 "】星は見えないな・・・雲ってるのか？") (wait)))
       (else (<>)))
      (set-reg: 17 1)))
    ((&& (== V 1) (== N 8) (== (: 17) 1))
     (<> (text #:color 7 "【" 0 "】空だな・・・何度見ても、何も起こりそうにない。") (wait)))
    ((&& (== V 1) (== N 9) (== (: 18) 0))
     (<>
      (text #:color 7 "【" 0 "】残念な事だが・・・金目の物は落ちてないようだ。")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 1) (== N 9) (== (: 18) 1))
     (<> (text #:color 7 "【" 0 "】道路だな・・・一応舗装されてるぜ。") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))