(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\。
  #\い
  #\っ
  #\な
  #\夏
  #\だ
  #\子
  #\ん
  #\の
  #\て
  #\、
  #\に
  #\さ
  #\は
  #\た
  #\か
  #\し
  #\う
  #\る
  #\よ
  #\ン
  #\？
  #\が
  #\ら
  #\あ
  #\を
  #\と
  #\も
  #\！
  #\こ
  #\わ
  #\君
  #\ま
  #\り
  #\ゃ
  #\で
  #\く
  #\事
  #\や
  #\じ
  #\ぜ
  #\れ
  #\き
  #\私
  #\マ
  #\シ
  #\ョ
  #\め
  #\そ
  #\俺
  #\ー
  #\部
  #\屋
  #\け
  #\ね
  #\チ)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "48.pd8")
 (proc 15)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "48.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (cond
  ((&&
    (== (: 539) 1)
    (== (: 547) 1)
    (> H 828)
    (> T 800)
    (< T 2359)
    (== (: 533) 0)
    (== (: 527) 0)
    (== (: 549) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "jan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 2 "【夏子】あら、" 0 "君じゃない。")
    (wait)
    (text #:color 7 "【" 0 "】夏子さん、会いたかったぜ。")
    (wait)
    (text #:color 2 "【夏子】" 0 "君、だめよ・・・部屋の中には入れられないわ。")
    (wait)
    (text #:color 2 "【夏子】約束したでしょう？・・・しばらくは、ああなる前の二人でいましょうって。")
    (wait)
    (text #:color 7 "【" 0 "】そうだけど・・・さ。")
    (wait)
    (text #:color 2 "【夏子】" 0 "君、まだ私の事を好き？")
    (wait)
    (text #:color 7 "【" 0 "】うん・・・。")
    (wait)
    (text #:color 2 "【夏子】ありがとう・・・もう少し時間がたってまだ私の事が好きだったら、その時は・・・ね？")
    (wait)
    (text #:color 7 "【" 0 "】わかった・・・。")
    (wait)
    (text #:color 2 "【夏子】私も" 0 "君の事が好き・・・大好きよ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "48.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】夏子さん・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】早く時間がたってしまえばいいのに・・・。")
    (wait)
    (set-reg: 549 1)
    (set-reg: 50 1)))
  ((&& (== (: 617) 1) (> H 829) (> T 1900) (== (: 626) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "uan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 59)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれれっ！？")
    (wait)
    (text #:color 6 "【やよい】" 0 "さん・・・こんな所で何をしているのかしら？")
    (wait)
    (text #:color 7 "【" 0 "】やよいさんこそ・・・。")
    (wait)
    (text #:color 6 "【やよい】私はこのマンションに友達がいますから・・・。")
    (wait)
    (text #:color 7 "【" 0 "】まさか・・・夏子さんって女性じゃないよね？")
    (wait)
    (text #:color 6 "【やよい】違いますよ・・・夏子さんって誰ですか？")
    (wait)
    (text #:color 7 "【" 0 "】（し、しまったあ・・・墓穴を掘ってしまった。）")
    (wait)
    (text #:color 6 "【やよい】おやすみなさい、" 0 "さん・・・夏子さんによろしく。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "48.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】ありゃりゃ・・・怒ったのか？")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】待てよ・・・怒るって事は、俺に気があるって事じゃないか？")
    (wait)
    (set-reg: 626 1)
    (set-reg: 116 (+ (: 116) 1))))
  ((&&
    (== (: 539) 1)
    (== (: 547) 1)
    (> H 829)
    (> T 800)
    (< T 2359)
    (== (: 533) 0)
    (== (: 527) 0)
    (== (: 553) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j11.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 2 "【夏子】" 0 "・・・君。")
    (wait)
    (text #:color 7 "【" 0 "】夏子さん・・・会いたかった。")
    (wait)
    (text #:color 2 "【夏子】うれしいわ・・・そう言ってくれると。")
    (wait)
    (text #:color 7 "【" 0 "】じゃあ、部屋に入れてくれ・・・もう一度、夏子さんを抱きたい。")
    (wait)
    (text #:color 2 "【夏子】駄目よ、" 0 "君・・・今はまだ友達でしょ？")
    (wait)
    (text #:color 7 "【" 0 "】もう時間はたってるぜ・・・俺の夏子さんへの気持ちは１ミリも変わってない。")
    (wait)
    (text #:color 2 "【夏子】本当に？")
    (wait)
    (text #:color 7 "【" 0 "】本当さ・・・なんだったら証拠を見せようか？")
    (wait)
    (text #:color 2 "【夏子】あははっ・・・" 0 "君の気持ちはわかったから、証拠は見せなくてもいいわよ。")
    (wait)
    (text #:color 7 "【" 0 "】ちぇっ・・・残念だな。")
    (wait)
    (text #:color 2 "【夏子】私も一哉君と話をして、けじめをつけないとね・・・そうしないと、" 0 "君とつき合えないもの。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 2 "【夏子】" 0 "君・・・明日になって気持ちが変わってなかったら、私に会いに来て欲しいの。")
    (wait)
    (text #:color 7 "【" 0 "】変わらないさ、絶対に。")
    (wait)
    (text #:color 2 "【夏子】じゃあ、明日・・・私に会いに来て。")
    (wait)
    (text #:color 7 "【" 0 "】わかった・・・。")
    (wait)
    (text #:color 2 "【夏子】じゃあね、" 0 "君・・・楽しみにしてるから。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "48.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】明日って・・・夏休みの最後の日じゃないか！？")
    (wait)
    (set-reg: 553 1)
    (set-reg: 50 1)))
  ((== (: 544) 1) (<> (text #:color 7 "【" 0 "】夏子さんが住んでるマンションだ・・・。") (wait))))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "他の場所に行く") (text "中に入る") (text "やめる")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・他の場所に行こう。")
         (wait)
         (set-var N 18)
         (slot 1 3)
         (mes-jump "town1.mes")))
       ((&& (== N 2) (== (: 50) 1))
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】ついさっき、俺の目の前からいなくなったのが・・・確か夏子さんだったような？")
         (wait)
         (text #:color 7 "【" 0 "】と、言う事は部屋にはいないって事だ・・・チャイム押しても無駄だぜ。")
         (wait)
         (set-reg: 50 2)))
       ((&& (== N 2) (== (: 50) 2))
        (<> (text #:color 7 "【" 0 "】無駄だよ・・・夏子さんは部屋にいない。") (wait)))
       ((&& (== N 2) (> T 2300))
        (<> (text #:color 7 "【" 0 "】こんなに遅いんだぜ・・・夏子さんに失礼だぜ。") (wait)))
       ((&& (== N 2) (< T 600))
        (<>
         (text #:color 7 "【" 0 "】はっはっはっ・・・俺がのチャイムと共に、夏子さんは目覚めるわけだ。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】やっぱり・・・やめた。")
         (wait)))
       ((&& (== N 2) (== (: 10) 0))
        (<>
         (text #:color 7 "【" 0 "】中に入るって事は、夏子さんの部屋を尋ねるって事だな。")
         (wait)
         (text #:color 7 "【" 0 "】よーし、チャイムを押して・・・。")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】いない・・・留守なのか？")
         (wait)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)
         (set-reg: 10 1)))
       ((&& (== N 2) (== (: 10) 1))
        (<>
         (text #:color 7 "【" 0 "】もう一度チャイムを押してみるか・・・。")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】夏子さんはいないようだ・・・。")
         (wait)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)))
       ((== N 3) (<> (text #:color 7 "【" 0 "】え！？・・・まだここにいるつもりか？") (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 1) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】マンションのアーチだな・・・俺が住んでるマンションとは大違いだぜ。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 1) (== N 1) (== (: 11) 1))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】こりをくぐめと、大きなガラスのドアがあって・・・オートロックだから、暗証番号を押さないと開かないようになってるんだ。")
      (wait)))
    ((&& (== V 1) (== N 2) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】このあたりは車の通りが多いからな・・・二酸化炭素をたっぷり吸った樹木だぜ。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 2) (== (: 12) 1))
     (<> (text #:color 7 "【" 0 "】樹木だぜ・・・別に変わったところはない。") (wait)))
    ((&& (== V 1) (== N 3) (== (: 13) 0))
     (<>
      (text #:color 7 "【" 0 "】この建物もマンションだろう・・・俺には関係ない建物だ。")
      (wait)
      (set-reg: 13 1)))
    ((&& (== V 1) (== N 3) (== (: 13) 1))
     (<> (text #:color 7 "【" 0 "】このマンションに、知り合いはいないはずだ・・・。") (wait)))
    ((&& (== V 1) (== N 4) (== (: 14) 0))
     (<>
      (text #:color 7 "【" 0 "】夏子さんが住んでるマンションだな・・・。")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 1) (== N 4) (== (: 14) 1))
     (<> (text #:color 7 "【" 0 "】おーいっ！！夏子さんっ！！・・・と叫んでも、聞こえるわけがない。") (wait)))
    ((&& (== V 1) (== N 5) (== (: 15) 0))
     (<>
      (text #:color 7 "【" 0 "】空を見上げると・・・。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】空だな、うん。")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 1) (== N 5) (== (: 15) 1))
     (<> (text #:color 7 "【" 0 "】だから空だってば・・・。") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))