(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\い
  #\。
  #\な
  #\っ
  #\、
  #\て
  #\だ
  #\る
  #\の
  #\か
  #\ん
  #\う
  #\あ
  #\？
  #\た
  #\よ
  #\し
  #\は
  #\が
  #\に
  #\と
  #\く
  #\ら
  #\を
  #\も
  #\こ
  #\で
  #\！
  #\ゃ
  #\わ
  #\れ
  #\そ
  #\ち
  #\じ
  #\美
  #\さ
  #\二
  #\え
  #\健
  #\言
  #\ま
  #\り
  #\み
  #\上
  #\事
  #\す
  #\何
  #\沙
  #\ー
  #\ろ
  #\け
  #\君
  #\屋
  #\き
  #\や
  #\舞
  #\校
  #\気
  #\ど
  #\見
  #\ね
  #\ふ
  #\僕
  #\お
  #\つ
  #\ス
  #\ン
  #\ぜ
  #\門
  #\持
  #\ば
  #\人
  #\来
  #\タ
  #\穂
  #\び
  #\め
  #\フ
  #\学
  #\ル
  #\色
  #\変
  #\入
  #\ょ
  #\女
  #\ぞ
  #\私
  #\生
  #\手
  #\子
  #\（
  #\）
  #\一)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "20.pd8")
 (proc 15)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "20.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (cond
  ((== (: 245) 0) (<> (text #:color 7 "【" 0 "】屋上だな・・・風が気持ちいい。") (wait)))
  ((&& (== (: 358) 0) (== (: 263) 1))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "l.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "lan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "l.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 836 0)
    (text #:color 7 "【" 0 "】なんだ・・・美沙じゃないかよ。")
    (wait)
    (text #:color 3 "【美沙】なんだ・・・" 0 "か。")
    (wait)
    (text #:color 7 "【" 0 "】お互いに同じ事を言ってどうするんだよ。")
    (wait)
    (text #:color 3 "【美沙】" 0 "じゃなくて、もっとかっこいい男だったらいいのに・・・って思ったんだよ。")
    (wait)
    (text #:color 7 "【" 0 "】へえ、美沙でも男に興味があるのか？")
    (wait)
    (text #:color 3 "【美沙】１８歳の乙女をつかまえて失礼だぞ・・・私だって・・・好きな男がいるんだから。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 3 "【美沙】ど、どうした・・・" 0 "！？")
    (wait)
    (text #:color 7 "【" 0 "】い、いや・・・美沙の言った言葉の衝撃が、あまりにも大きくて。")
    (wait)
    (sound 1)
    (set-var I 37)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "ボクンッ！！")
    (wait)
    (text #:color 7 "【" 0 "】いったーい。")
    (wait)
    (text #:color 3 "【美沙】ばかっ！！屋上から飛び降りて、死んじまえっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "20.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 19)
    (proc 26)
    (set-reg: 836 1)
    (text #:color 7 "【" 0 "】最近、美沙が短気になってるな・・・生理か？")
    (wait)
    (set-reg: 358 1)))
  ((&& (== (: 359) 0) (== (: 300) 1) (== (: 419) 0) (== (: 765) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "b.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "man.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 4 "【健二】" 0 "・・・。")
    (wait)
    (text #:color 7 "【" 0 "】健二・・・。")
    (wait)
    (text #:color 4 "【健二】見つめあってどうするんだ。")
    (wait)
    (text #:color 7 "【" 0 "】気持ち悪くなってきた・・・。")
    (wait)
    (text #:color 4 "【健二】こっちのセリフだ・・・せっかく人が帝王学を学んでいる時に邪魔されるとは。")
    (wait)
    (text #:color 7 "【" 0 "】帝王・・・切開？")
    (wait)
    (text #:color 4 "【健二】ふっ・・・所詮" 0 "はそのレベルだろう。")
    (wait)
    (text
     #:color
     4
     "【健二】かわいそうだから教えてやろう・・・屋上から人々を見下げて、自分がいかに人の上に立つ人間かを再認識してるんだ。")
    (wait)
    (text #:color 7 "【" 0 "】悪趣味だな・・・。")
    (wait)
    (text #:color 4 "【健二】何とでも言え、庶民には理解できない事だろう・・・それじゃあ僕は、用があるので失礼するよ。")
    (wait)
    (text #:color 7 "【" 0 "】階段を降りるより、ここから飛び降りた方が早いぜ・・・なんなら手伝おうか？")
    (wait)
    (text #:color 4 "【健二】ふっ・・・。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "20.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】あー、健二がいなくなると空気がおいしいなあ。")
    (wait)
    (set-reg: 359 1)))
  ((&& (== (: 357) 0) (== (: 222) 1) (== (: 253) 1))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "g.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "tan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "t.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 25)
    (proc 26)
    (set-reg: 836 0)
    (text #:color 3 "【真子】あら、" 0 "君・・・景色でも眺めに来たの？")
    (wait)
    (text #:color 7 "【" 0 "】えーと、そんなところかな？")
    (wait)
    (text #:color 3 "【真子】私はもう帰るけど、ちゃんと屋上のドアを閉めて帰ってね・・・それと、変な物を屋上から落とさないように。")
    (wait)
    (text #:color 7 "【" 0 "】へいへい。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "20.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 19)
    (proc 26)
    (set-reg: 836 1)
    (text #:color 7 "【" 0 "】あーあ、真子先生は帰ってしまった。")
    (wait)
    (set-reg: 357 1)))
  ((&& (== (: 695) 1) (> H 818) (== (: 697) 0) (== (: 708) 0))
   (<>
    (text #:color 7 "【" 0 "】うーん・・・気持ちいいな。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "l.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "lan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "l.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 3 "【美沙】何が気持ちいいんだ？")
    (wait)
    (text #:color 7 "【" 0 "】な、なんだよ・・・いきなり出てくるなよ。")
    (wait)
    (text #:color 3 "【美沙】そんなに驚く事はないだろ？")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】そう言えば、美沙って最近練習してないな・・・膝の怪我のせいなのか？")
    (wait)
    (text #:color 3 "【美沙】膝はもう大丈夫だけど・・・。")
    (wait)
    (text #:color 7 "【" 0 "】だけど？")
    (wait)
    (text #:color 3 "【美沙】いや、いいんだ・・・じゃあな、" 0 "！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "20.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 19)
    (proc 26)
    (set-reg: 836 1)
    (text #:color 7 "【" 0 "】お、おい・・・待てよ。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なんだよ美沙のやつ・・・変なやつだなあ。")
    (wait)
    (set-reg: 697 1)))
  ((&& (== (: 745) 1) (> H 820) (< H 824) (> T 800) (< T 1800) (== (: 750) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "w.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "wan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "w.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 24)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれれ！？")
    (wait)
    (text #:color 3 "【舞】あ・・・" 0 "君じゃない。")
    (wait)
    (text #:color 7 "【" 0 "】（うーん・・・いつ見てもかわいいなあ。）")
    (wait)
    (text #:color 3 "【舞】" 0 "君がね、校門から入って来るのがわかったわよ。")
    (wait)
    (text #:color 7 "【" 0 "】え・・・。")
    (wait)
    (set-reg: 101 1)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "校門？") (text "お尻の穴？") (text "黄門？")))
    (cond
     ((== N 1)
      (<>
       (text #:color 7 "【" 0 "】校門？")
       (wait)
       (text #:color 3 "【舞】そうよ、校門から入って来たでしょう？")
       (wait)
       (text #:color 7 "【" 0 "】だって・・・校門からしか、校庭に入れないよ。")
       (wait)))
     ((== N 2)
      (<>
       (text #:color 7 "【" 0 "】お尻の穴？")
       (wait)
       (text #:color 3 "【舞】・・・。")
       (wait)
       (text #:color 7 "【" 0 "】引いた・・・な。")
       (wait)))
     ((== N 3)
      (<>
       (text #:color 7 "【" 0 "】黄門？")
       (wait)
       (text #:color 3 "【舞】そうよ、校門から入って来たでしょう？")
       (wait)
       (text #:color 7 "【" 0 "】（ちっ、言葉で漢字は伝わらないぜ・・・つまんないの。）")
       (wait)))
     (else (<>)))
    (text #:color 3 "【舞】ふふふっ・・・" 0 "君って、陸上部の女の子達をじろじろ見て、それから校舎の中に入ってきたでしょ？")
    (wait)
    (text #:color 7 "【" 0 "】やだなあ・・・そんなとこまで見るなよう。")
    (wait)
    (text #:color 3 "【舞】それだけ、" 0 "君の事が気になるって事。")
    (wait)
    (text #:color 7 "【" 0 "】え！？")
    (wait)
    (text #:color 3 "【舞】や、やだ・・・変な事を言ったわね、私。")
    (wait)
    (text #:color 3 "【舞】じ、じゃあね・・・日曜日の約束、忘れないでね。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "20.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 19)
    (proc 26)
    (set-reg: 836 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あーあ・・・せっかく二人きりだったのに。")
    (wait)
    (set-reg: 750 1)))
  ((&& (== (: 419) 1) (== (: 432) 0) (> H 827))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 836 0)
    (text #:color 7 "【" 0 "】あれれ！？")
    (wait)
    (text #:color 6 "【さとみ】別にアルバイトをさぼってる訳じゃないわよ・・・ちゃんとマスターに断ってきたんだから。")
    (wait)
    (text #:color 7 "【" 0 "】何度も言うようだけど、俺は何も言ってないぜ。")
    (wait)
    (text #:color 6 "【さとみ】そうだった？")
    (wait)
    (text #:color 7 "【" 0 "】でも、屋上で何をしてるんだ・・・まさか、さとみ。")
    (wait)
    (text #:color 6 "【さとみ】変な事を言わないでよ・・・飛び降りる訳がないでしょ？")
    (wait)
    (text #:color 7 "【" 0 "】違うよ、一人で景色を見ながら『手淫』をするつもりじゃあ・・・？")
    (wait)
    (text #:color 6 "【さとみ】" 0 "・・・確かに以前と全くかわらないけど、少しは変わってももいいのよ。")
    (wait)
    (text #:color 7 "【" 0 "】怒った？")
    (wait)
    (text #:color 6 "【さとみ】呆れたわよ・・・せっかくのすがすがしい気分が台無しだわ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "20.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 19)
    (proc 26)
    (set-reg: 836 1)
    (text #:color 7 "【" 0 "】あらら・・・さとみが屋上からいなくなってしまった。")
    (wait)
    (set-reg: 432 1)))
  ((&& (== (: 718) 1) (> H 824) (== (: 722) 0) (== (: 728) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "man.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 27)
    (proc 26)
    (set-reg: 836 0)
    (text #:color 7 "【" 0 "】美穂ちゃん！？")
    (wait)
    (text #:color 6 "【美穂】" 0 "君も・・・学校に来てたの？")
    (wait)
    (text #:color 7 "【" 0 "】美穂ちゃんこそ・・・ここで何をしてるの？")
    (wait)
    (text #:color 6 "【美穂】あのね、私は・・・ぽっ。")
    (wait)
    (text #:color 7 "【" 0 "】？？？")
    (wait)
    (text #:color 6 "【美穂】ここでね、" 0 "君の事を・・・考えてたの。")
    (wait)
    (text #:color 7 "【" 0 "】（な、なんてかわいいんだあ！！）")
    (wait)
    (text #:color 6 "【美穂】きゃっ・・・言っちゃった、恥ずかしいっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "20.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 19)
    (proc 26)
    (set-reg: 836 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】だ、駄目だ・・・手紙をもらって以来、彼女とまともに話す事ができない。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 836 0)
    (text #:color 5 "【太郎】" 0 "君、誰から手紙を貰ったんだ？")
    (wait)
    (text #:color 7 "【" 0 "】うわわっ！？")
    (wait)
    (text #:color 5 "【太郎】教えてくれたまえ、誰から手紙を貰ったんだ？")
    (wait)
    (text #:color 7 "【" 0 "】マ、マタロウには関係ない事だろ。")
    (wait)
    (text #:color 5 "【太郎】・・・。")
    (wait)
    (text #:color 5 "【太郎】ふん、まあいい・・・君の事だ、そのうちわかるだろう。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "20.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 19)
    (proc 26)
    (set-reg: 836 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なんだよ、マタロウのやつ・・・美穂ちゃんと俺の話を聞いてたんじゃないだろうな。")
    (wait)
    (set-reg: 722 1)))
  ((&& (== (: 653) 1) (== (: 654) 0) (> H 826))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "c.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "can.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "c.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 60)
    (proc 26)
    (set-reg: 836 0)
    (text #:color 7 "【" 0 "】あれ・・・よしこ先生。")
    (wait)
    (text #:color 6 "【よしこ】" 0 "君、こんにちは・・・。")
    (wait)
    (text #:color 7 "【" 0 "】先生、また学校に来るようになったの？")
    (wait)
    (text #:color 6 "【よしこ】いいえ、用事があって寄っただけですよ・・・今からまた帰りますけど。")
    (wait)
    (text #:color 7 "【" 0 "】ふーん・・・。")
    (wait)
    (text #:color 6 "【よしこ】" 0 "君・・・あの時の事は内緒にしてくださいね。")
    (wait)
    (text #:color 7 "【" 0 "】うん・・・わかってる。")
    (wait)
    (text #:color 6 "【よしこ】もっともこんな事を言わなくても・・・" 0 "君は大丈夫でしょうけど。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 6 "【よしこ】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あの・・・。")
    (wait)
    (text #:color 6 "【よしこ】え？")
    (wait)
    (text #:color 7 "【" 0 "】い、いや・・・何でもない。")
    (wait)
    (text #:color 6 "【よしこ】" 0 "君・・・。")
    (wait)
    (text #:color 7 "【" 0 "】は？")
    (wait)
    (text #:color 6 "【よしこ】・・・。")
    (wait)
    (text #:color 6 "【よしこ】ううん、何でもないわ・・・じゃあ、さようなら。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "20.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 19)
    (proc 26)
    (set-reg: 836 1)
    (text #:color 7 "【" 0 "】うーん・・・俺は何を言おうとしたんだろう。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】それより、よしこ先生は何を言おうとしたんだ？")
    (wait)
    (set-reg: 654 1)))
  ((&&
    (== (: 767) 1)
    (> H 824)
    (> T 800)
    (< T 2100)
    (== (: 765) 0)
    (== (: 770) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "b.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "man.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】あれ・・・健二じゃないか。")
    (wait)
    (text #:color 4 "【健二】ふっ・・・邪魔が入ったぜ。")
    (wait)
    (text #:color 7 "【" 0 "】悪かったな健二・・・ティッシュ、貸そうか？")
    (wait)
    (text #:color 4 "【健二】ぼ、僕はそんな下劣な事はしないっ！！ここは学校の屋上だぞ！！")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・違ったの？")
    (wait)
    (text #:color 4 "【健二】僕はな、ここから舞の家を見てたんだ・・・そして僕の愛が届くように、ずっと舞の事を思い続けていたんだ。")
    (wait)
    (text #:color 7 "【" 0 "】何が『僕の愛』だよ・・・正直に言うと『僕の性欲』だろ？")
    (wait)
    (text #:color 4 "【健二】" 0 "と一緒にしないで欲しいな・・・僕の舞に対する気持ちは純粋なんだ。")
    (wait)
    (text #:color 7 "【" 0 "】じゃあ・・・キスしたいと思わないのか？")
    (wait)
    (text #:color 4 "【健二】思わないな・・・そばにいてくれればいい。")
    (wait)
    (text #:color 7 "【" 0 "】はっはっはっ、何もわかってないな・・・何もしなければ逆にフラれるだけだぜ。")
    (wait)
    (text #:color 4 "【健二】舞は" 0 "君が知ってる女性とは違うのさ・・・僕と同じように高級な人間だ。")
    (wait)
    (text #:color 7 "【" 0 "】ふあああああ・・・。")
    (wait)
    (text #:color 4 "【健二】あくびをするなっ！！")
    (wait)
    (text #:color 7 "【" 0 "】え！？・・・何か言った！？")
    (wait)
    (text #:color 4 "【健二】ふっ、まあいい・・・僕の愛は届いたはずだ、僕はこれで失礼するよ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "20.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】何が高級だよ・・・馬鹿らしいぜ、まったく。")
    (wait)
    (set-reg: 770 1)))
  ((&&
    (== (: 519) 1)
    (== (: 526) 0)
    (> H 829)
    (> T 830)
    (< T 1800)
    (== (: 527) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "q.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "qan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "q.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 836 0)
    (text #:color 7 "【" 0 "】ありゃりゃ・・・くるみちゃんがいるぞ。")
    (wait)
    (text #:color 6 "【くるみ】あ、" 0 "さん・・・気持ちいいわね、屋上から景色を見てると。")
    (wait)
    (text #:color 7 "【" 0 "】俺は屋上にいる女の子を下から見ていたい・・・もちろんその場合はスカートに限るぞ。")
    (wait)
    (text #:color 6 "【くるみ】くすくすっ・・・" 0 "さんって変わらないのね。")
    (wait)
    (text #:color 7 "【" 0 "】一哉とは・・・もういいか、その話は。")
    (wait)
    (text #:color 6 "【くるみ】うん、もういいの・・・全然考えてないし。")
    (wait)
    (text #:color 7 "【" 0 "】（そうあっさり言われると、今時は一哉がかわいそうになってきたな。）")
    (wait)
    (if (== (: 515) 1)
      (<>
       (text #:color 6 "【くるみ】ねえ、" 0 "さん・・・もう一回して。")
       (wait)
       (text #:color 7 "【" 0 "】はあ？")
       (wait)
       (set-arr~ @ 7 1)
       (set-arr~ @ 1 4096)
       (set-arr~ @ 9 (&& (~ @ 9) 65534))
       (set-arr~ @ 6 1)
       (image "q03.pd8")
       (set-arr~ @ 9 (// (~ @ 9) 1))
       (proc 25)
       (set-arr~ @ 7 1)
       (set-arr~ @ 1 4096)
       (set-arr~ @ 6 1)
       (image "q03an.pd8")
       (set-arr~ @ 6 0)
       (set-arr~ @ 7 0)
       (load "q03.s4" (~ @ 2))
       (animate 0 0 0)
       (animate 1 0)
       (set-arr~ @ 7 0)
       (sound 1)
       (set-var I 29)
       (proc 26)
       (set-reg: 836 0)
       (text #:color 6 "【くるみ】キス・・・して。")
       (wait)
       (text #:color 7 "【" 0 "】（な、なんだあ！？）")
       (wait)
       (text #:color 6 "【くるみ】いや？")
       (wait)
       (text #:color 7 "【" 0 "】いやじゃないけど、ちょっとびっくりした。")
       (wait)
       (text #:color 6 "【くるみ】じゃあ、私がしてあげる・・・ちゅっ！！")
       (wait)
       (text #:color 7 "【" 0 "】！？")
       (wait)))
    (text #:color 6 "【くるみ】じゃあね・・・ばいばい。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "20.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 19)
    (proc 26)
    (set-reg: 836 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】びっくりしたあ。")
    (wait)
    (set-reg: 526 1)))
  ((== (: 245) 1) (<> (text #:color 7 "【" 0 "】ふう・・・屋上だぜ。") (wait))))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "他の場所に行く") (text "やめる")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】わかった・・・校舎の中に戻ろう。")
         (wait)
         (set-reg: 245 1)
         (set-var N 1)
         (slot 1 3)
         (mes-jump "gakko4.mes")))
       ((== N 2) (<> (text #:color 7 "【" 0 "】屋上は気持ちいいぜ・・・もう少しここにいよう。") (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 1) (== (: 10) 0))
     (<>
      (text #:color 7 "【" 0 "】フェンスがある・・・アルミでできたフェンスだ。")
      (wait)
      (set-reg: 10 1)))
    ((&& (== V 1) (== N 1) (== (: 10) 1))
     (<> (text #:color 7 "【" 0 "】フェンスがぐるっと、屋上を取り囲んでいる。") (wait)))
    ((&& (== V 1) (== N 2) (== (: 11) 0))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】フェンスの向こうには、金網が張ってある・・・なにも自殺防止って訳じゃないくて、ボールとかが落ちないようになってるんだ。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 1) (== N 2) (== (: 11) 1))
     (<> (text #:color 7 "【" 0 "】金網が張ってある・・・３メートルぐらい高さがあるんじゃないか？") (wait)))
    ((&& (== V 1) (== N 3) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】窓を覗くと・・・ポンプとか配電盤とか色々な機械が見える。")
      (wait)
      (text #:color 7 "【" 0 "】ガタガタと震えているところを見ると、学校が夏休みでも機械は動いてるようだな。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 3) (== (: 12) 1))
     (<> (text #:color 7 "【" 0 "】窓の中は機械だらけだ・・・窓ガラスは、白くすすけている。") (wait)))
    ((&& (== V 1) (== N 4) (== (: 13) 0))
     (<>
      (text #:color 7 "【" 0 "】小さな建物の中は、色々な機械が詰め込まれるぞ・・・上には給水タンクが乗ってるな。")
      (wait)
      (set-reg: 13 1)))
    ((&& (== V 1) (== N 4) (== (: 13) 1))
     (<> (text #:color 7 "【" 0 "】５メートル四方の小さな建物だ・・・。") (wait)))
    ((&& (== V 1) (== N 5) (== (: 14) 0))
     (<>
      (text #:color 7 "【" 0 "】いい天気だな・・・雲がプカプカ浮かんでる。")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 1) (== N 5) (== (: 14) 1))
     (<> (text #:color 7 "【" 0 "】空だな・・・雲が浮かんでる。") (wait)))
    ((&& (== V 1) (== N 6) (== (: 15) 0))
     (<> (text #:color 7 "【" 0 "】地面を見ても、何も落ちてない・・・。") (wait) (set-reg: 15 1)))
    ((&& (== V 1) (== N 6) (== (: 15) 1))
     (<> (text #:color 7 "【" 0 "】灰色のブロックが敷き詰められてる・・・よくあるパターンだな。") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))