(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\ん
  #\っ
  #\る
  #\い
  #\。
  #\【
  #\】
  #\く
  #\あ
  #\み
  #\、
  #\な
  #\の
  #\う
  #\だ
  #\て
  #\し
  #\に
  #\か
  #\こ
  #\は
  #\や
  #\た
  #\と
  #\さ
  #\が
  #\ら
  #\わ
  #\！
  #\も
  #\を
  #\ろ
  #\れ
  #\え
  #\ぺ
  #\で
  #\俺
  #\？
  #\そ
  #\ど
  #\ま
  #\ち
  #\め
  #\事
  #\じ
  #\お
  #\見
  #\ゃ
  #\す
  #\よ
  #\ー
  #\言
  #\き
  #\女
  #\変
  #\ょ
  #\け
  #\彼
  #\中
  #\痛
  #\り
  #\今
  #\時
  #\何
  #\ふ
  #\出
  #\熱
  #\身
  #\ね
  #\つ
  #\一)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 9 (&& (~ @ 9) 65534))
 (set-arr~ @ 6 1)
 (image "q06.pd8")
 (set-arr~ @ 9 (// (~ @ 9) 1))
 (proc 24)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "q06an.pd8")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 0)
 (load "q06.s4" (~ @ 2))
 (animate 0 0 0)
 (animate 1 0)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "q06.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (set-reg: 331 0)
 (if (== (: 515) 1)
   (<>
    (text #:color 7 "【" 0 "】うーん、俺って天才だな。")
    (wait)
    (text #:color 6 "【くるみ】" 0 "さん・・・食い込むの。")
    (wait)
    (text #:color 7 "【" 0 "】何が？")
    (wait)
    (text #:color 6 "【くるみ】ここが・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ここが、じゃわからないな・・・げしょげしょげしょ。")
    (wait)
    (text #:color 6 "【くるみ】だから・・・ここが、食い込むのお。")
    (wait)
    (text #:color 7 "【" 0 "】ちゃんと言ってくれないとわからない。")
    (wait)
    (text #:color 6 "【くるみ】" 0 "さんの・・・いじわる。")
    (wait)))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (set-reg: 331 (+ (: 331) 1))
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<> (text "自分を縛る")))
      (cond
       ((&& (== N 1) (== (: 10) 0))
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】どうやって？")
         (wait)
         (set-reg: 10 1)))
       ((&& (== N 1) (== (: 10) 1))
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】だから、どうやって？")
         (wait)))
       (else (<>)))))
    ((&& (== V 7) (== N 1) (== (: 11) 0))
     (<> (text #:color 6 "【くるみ】んん・・・ん・・・ん・・・。") (wait) (set-reg: 11 1)))
    ((&& (== V 7) (== N 1) (== (: 11) 1))
     (<> (text #:color 6 "【くるみ】あ・・・ん・・・。") (wait)))
    ((&& (== V 8) (== N 2) (== (: 12) 0))
     (<>
      (text #:color 6 "【くるみ】優しい・・・" 0 "さん。")
      (wait)
      (text #:color 7 "【" 0 "】（おいおい、こんな事をしてる俺のどこが優しいんだ！？）")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 8) (== N 2) (== (: 12) 1))
     (<>
      (text #:color 6 "【くるみ】ん・・・。")
      (wait)
      (text #:color 6 "【くるみ】" 0 "さんの手って・・・大きい。")
      (wait)
      (text #:color 7 "【" 0 "】（どうせだったら、他の部分を大きいって言って欲しいな。）")
      (wait)))
    ((&& (== V 10) (== N 3) (== (: 13) 0))
     (<> (text #:color 6 "【くるみ】あん・・・くすぐったいの。") (wait) (set-reg: 13 1)))
    ((&& (== V 10) (== N 3) (== (: 13) 1))
     (<> (text #:color 6 "【くるみ】耳をぺろぺろしちゃ・・・いや。") (wait)))
    ((&& (== V 10) (== N 4) (== (: 14) 0))
     (<> (text #:color 6 "【くるみ】んんっ・・・あ。") (wait) (set-reg: 14 1)))
    ((&& (== V 10) (== N 4) (== (: 14) 1))
     (<> (text #:color 6 "【くるみ】あん・・・んんん。") (wait)))
    ((&& (== V 10) (== N 5) (== (: 15) 0))
     (<> (text #:color 6 "【くるみ】やだ・・・" 0 "さん、犬みたい。") (wait) (set-reg: 15 1)))
    ((&& (== V 10) (== N 5) (== (: 15) 1))
     (<>
      (text #:color 6 "【くるみ】んんっ・・・いや。")
      (wait)
      (text #:color 6 "【くるみ】顔をなめられるって・・・みんなこんな事するの？")
      (wait)))
    ((&& (== V 11) (== N 6) (== (: 16) 0))
     (<>
      (text #:color 6 "【くるみ】あんっ・・・い、痛い。")
      (wait)
      (text #:color 7 "【" 0 "】どこが？")
      (wait)
      (text #:color 6 "【くるみ】いや・・・言えない。")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 11) (== N 6) (== (: 16) 1))
     (<>
      (text #:color 6 "【くるみ】あっ・・・いやいや。")
      (wait)
      (text #:color 6 "【くるみ】んんっ・・・だめ・・・" 0 "さん・・・いや。")
      (wait)))
    ((&& (== V 9) (== N 7) (== (: 17) 0))
     (<> (text #:color 6 "【くるみ】あ・・・ああ・・・はあ。") (wait) (set-reg: 17 1)))
    ((&& (== V 9) (== N 7) (== (: 17) 1))
     (<> (text #:color 6 "【くるみ】んんっ・・・んんっ・・・んんん。") (wait)))
    ((&& (== V 10) (== N 8) (> (: 331) 14))
     (<>
      (text #:color 6 "【くるみ】" 0 "さんっ・・・も、もういやあ。")
      (wait)
      (text #:color 7 "くるみのあそこからは、蜜があふれ出している・・・俺はその部分をじっと見る。")
      (wait)
      (text #:color 6 "【くるみ】いやいや・・・見ないで・・・見ないでえ。")
      (wait)
      (text #:color 7 "もう我慢できない、俺の熱い塊からは血がふき出しそうになっている。")
      (wait)
      (text #:color 6 "【くるみ】こ、恐いの・・・優しくしてえ。")
      (wait)
      (text #:color 7 "俺は彼女の身体を抱きかかえると、そのままお尻を上に突き出させるように格好にする。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "q07.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "q07an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q07.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 6 "【くるみ】いやあ・・・恥ずかしい・・・見えちゃう。")
      (wait)
      (text #:color 7 "もうとっくに見えてる。")
      (wait)
      (text #:color 6 "【くるみ】いやいや・・・こんな格好、嫌い。")
      (wait)
      (text #:color 7 "ロープが食い込んでるのが、よくわかるポーズだ・・・そしてそのロープまでを、くるみは濡らしている。")
      (wait)
      (text #:color 6 "【くるみ】見ないで・・・見ないで" 0 "さん。")
      (wait)
      (text #:color 7 "もうたっぷり見てる。")
      (wait)
      (text #:color 6 "【くるみ】" 0 "さん・・・私から離れないで・・・もっと近くにいて。")
      (wait)
      (text #:color 7 "俺はくるみの背後から近付く・・・俺のイチモツは天井にまで届きそうだ、嘘だけど。")
      (wait)
      (text #:color 6 "【くるみ】ね、ねえ・・・これからどうするの？")
      (wait)
      (text #:color 7 "俺は何も言わず、彼女のあの部分に固い物を押しあてる。")
      (wait)
      (text #:color 6 "【くるみ】ああっ・・・こ、恐い・・・。")
      (wait)
      (text #:color 7 "ロープが邪魔だと思いつつ、俺はそのままどんどん押しあてる。")
      (wait)
      (text #:color 6 "【くるみ】んっ・・・。")
      (wait)
      (text #:color 7 "ロープがちょっと痛い。")
      (wait)
      (text #:color 7 "よく見ると今はやりのＴバックみたいだな・・・などと、くだらない事が頭の中に浮かんでは消える。")
      (wait)
      (text #:color 7 "いかんいかん、彼女を女にする事に集中しなければ・・・俺は彼女の耳にそっとささやく。")
      (wait)
      (text #:color 7 "【" 0 "】くるみちゃん・・・いくよ。")
      (wait)
      (text #:color 6 "【くるみ】うん・・・。")
      (wait)
      (text #:color 7 "俺は彼女と一体になる為に、腰にぐっと力を入れる。")
      (wait)
      (text #:color 6 "【くるみ】うっ・・・んっ・・・。")
      (wait)
      (text #:color 7 "彼女のつぼみは固く、なかなか俺を受け入れようとしない。")
      (wait)
      (text #:color 6 "【くるみ】い、痛いの・・・" 0 "さん。")
      (wait)
      (text #:color 7 "痛いと言われてやめたら、この子は永遠に処女のままだろう。")
      (wait)
      (text #:color 6 "【くるみ】あんっ・・・いいの・・・続けて・・・。")
      (wait)
      (text #:color 7 "【" 0 "】くみるちゃん、身体の力を抜いて・・・。")
      (wait)
      (text #:color 6 "【くるみ】うん・・・。")
      (wait)
      (text #:color 7 "くるみが身体の力を抜くと、ようやく俺の固いものが彼女の中に少しづつ吸い込まれていく。")
      (wait)
      (text #:color 6 "【くるみ】んっ・・・痛い・・・。")
      (wait)
      (text #:color 7 "彼女の中はすごく熱く、狭い・・・これでは俺の方が一気に昇天してしまいそうだ。")
      (wait)
      (text #:color 6 "【くるみ】こ、これで・・・おしまい？")
      (wait)
      (text #:color 7 "けっこうショックな事を言う子だ・・・俺はおしおきの為に、腰を動かす事にした。")
      (wait)
      (text #:color 6 "【くるみ】あっ・・・痛いの・・・もっとゆっくり・・・。")
      (wait)
      (text #:color 7 "くっ・・・こ、こんなにキツいの・・・生まれて初めてだあ。")
      (wait)
      (text #:color 6 "【くるみ】んっ・・・んっ・・・んっ・・・。")
      (wait)
      (text #:color 7 "俺は一生懸命、頭の中で九九をする事にした・・・ににんがし、にさんがろく、にしがはち。")
      (wait)
      (text #:color 6 "【くるみ】あんっ・・・こ、こんな事・・・みんなしてるの・・・ね。")
      (wait)
      (text #:color 7 "にごじゅう、にろくじゅうに・・・うっ・・・あっ・・・。")
      (wait)
      (text #:color 6 "【くるみ】あんっ・・・変な感じ・・・熱い・・・熱い。")
      (wait)
      (text #:color 7 "そ、そんな色っぽい声を・・・にしちじゅうし、にはちじゅうろく・・・出さないでくれえ！！")
      (wait)
      (text #:color 6 "【くるみ】" 0 "さあん・・・" 0 "さあん・・・あはんっ。")
      (wait)
      (text #:color 7 "も、もうだめだあ！！")
      (wait)
      (text #:color 6 "スポッ！！")
      (wait)
      (text #:color 6 "【くるみ】きゃっ！！")
      (wait)
      (text #:color 7 "俺は・・・くるみの背中に、たっぷりと放出してしまった。")
      (wait)
      (text #:color 7 "・・・。")
      (wait)
      (text #:color 7 "ちょっと早かったかな・・・ちくしょう。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kuro.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (sound 1)
      (set-var I 29)
      (proc 26)
      (set-reg: 835 0)
      (text #:color 6 "【くるみ】" 0 "さん・・・これで全部おしまい？")
      (wait)
      (text #:color 7 "【" 0 "】ちょっと早かったけど、おしまい。")
      (wait)
      (text #:color 6 "【くるみ】男の人がしたい事って・・・こんな事だったの？")
      (wait)
      (text #:color 7 "【" 0 "】そう・・・こんな事。")
      (wait)
      (text #:color 6 "【くるみ】私・・・どこか変わった？")
      (wait)
      (text #:color 7 "【" 0 "】うーん・・・どうだろう。")
      (wait)
      (text #:color 6 "【くるみ】なんだか・・・何も変わってないような気がする。")
      (wait)
      (text #:color 7 "【" 0 "】うーん・・・。")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "変わってない") (text "変わった")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】確かに変わってない。")
         (wait)
         (text #:color 6 "【くるみ】でしょ？")
         (wait)
         (text
          #:color
          7
          "【"
          0
          "】でも、中身が変わってるかもよ・・・今はわからないけど、今度一哉に会った時にわかるかもしれない。")
         (wait)
         (text #:color 6 "【くるみ】ふーん・・・。")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】変わったよ・・・すごく色っぽく見えるぜ。")
         (wait)
         (text #:color 6 "【くるみ】本当？")
         (wait)
         (text
          #:color
          7
          "【"
          0
          "】ああ・・・それに外見だけじゃなくて、中身も変わってるかもよ・・・今はわからないけど、今度一哉に会った時にわかるかもしれない。")
         (wait)
         (text #:color 6 "【くるみ】ふーん・・・。")
         (wait)))
       (else (<>)))
      (set-var A 2)
      (proc 13)
      (proc 11)
      (text #:color 6 "【くるみ】あ・・・私、もう帰らないと。")
      (wait)
      (text #:color 7 "【" 0 "】げっ・・・もうこんな時間か。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "50.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "q.pd8")
      (proc 16)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "qan.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "q.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (sound 1)
      (set-var I 23)
      (proc 26)
      (set-reg: 835 0)
      (text #:color 6 "【くるみ】こんな時間に帰ったら・・・きっとお父さんに怒られる。")
      (wait)
      (text #:color 6 "【くるみ】・・・。")
      (wait)
      (text #:color 6 "【くるみ】でも・・・ちゃんと言えば、お父さんだってわかってくれると思うの。")
      (wait)
      (text #:color 7 "【" 0 "】ち、ちょっと待ったあ・・・お父さんに何て言うつもり！？")
      (wait)
      (text #:color 6 "【くるみ】平気・・・たくろさうさんの事は言わないから、友達と会ってた事にする。")
      (wait)
      (text #:color 7 "【" 0 "】（・・・ふう。）")
      (wait)
      (text #:color 6 "【くるみ】私・・・なんだか変わったみたい。")
      (wait)
      (text #:color 7 "【" 0 "】え？")
      (wait)
      (text #:color 6 "【くるみ】今、" 0 "さんの顔を見た時・・・そう感じたの。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 6 "【くるみ】じゃあ・・・帰るね。")
      (wait)
      (text #:color 7 "【" 0 "】こんな時間だ、送って行くぜ。")
      (wait)
      (text #:color 6 "【くるみ】ううん、平気だから。")
      (wait)
      (text #:color 7 "【" 0 "】駄目だよ・・・危ないから。")
      (wait)
      (text #:color 6 "【くるみ】ありがとう・・・" 0 "さんって優しいのね。")
      (wait)
      (field 14 1 1)
      (field 13 0 0)
      (field 13 1 1)
      (set-reg: 1001 0)
      (set-reg: 112 (+ (: 112) 5))
      (set-var N 11)
      (set-reg: 517 1)
      (slot 1 2)
      (mes-jump "town1.mes")))
    ((&& (== V 10) (== N 8) (== (: 18) 0))
     (<>
      (text #:color 6 "【くるみ】あああんっ・・・いやいやっ！！")
      (wait)
      (text #:color 7 "【" 0 "】ぺろぺろぺろぺろぺろぺろっ！！")
      (wait)
      (text #:color 6 "【くるみ】いやいやっ！！だめだめっ！！")
      (wait)
      (text #:color 7 "【" 0 "】何が？")
      (wait)
      (text #:color 6 "【くるみ】なめたら・・・だめ。")
      (wait)
      (text #:color 7 "【" 0 "】どこを？")
      (wait)
      (text #:color 6 "【くるみ】あそこ。")
      (wait)
      (text #:color 7 "【" 0 "】あそこじゃわからない。")
      (wait)
      (text #:color 6 "【くるみ】・・・。")
      (wait)
      (text #:color 6 "【くるみ】・・・言えない。")
      (wait)
      (text #:color 7 "【" 0 "】ぺろぺろぺろぺろぺろっ！！")
      (wait)
      (text #:color 6 "【くるみ】あ・・・あんっ・・・熱くなってくるう。")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 10) (== N 8) (== (: 18) 1))
     (<> (text #:color 6 "【くるみ】あっ・・・あっ・・・あっ・・・いや。") (wait) (set-reg: 18 2)))
    ((&& (== V 10) (== N 8) (== (: 18) 2))
     (<>
      (text #:color 6 "【くるみ】")
      (set-var S (? 10))
      (if (== S 0) (<> (text "あんっ・・・")))
      (if (== S 1) (<> (text "い・・・")))
      (if (== S 2) (<> (text "んんっ・・・")))
      (if (== S 3) (<> (text "あはあ・・・")))
      (if (== S 4) (<> (text "んんんっ・・・")))
      (if (== S 5) (<> (text "恥ずかしい・・・")))
      (if (== S 6) (<> (text "だ、だめえ・・・")))
      (if (== S 7) (<> (text "あっ・・・")))
      (if (== S 8) (<> (text "んんあっ・・・")))
      (if (== S 9) (<> (text "い、いやあ・・・")))
      (text "ん・・・")
      (set-var S (? 10))
      (if (== S 0) (<> (text "あんっ・・・")))
      (if (== S 1) (<> (text "い・・・")))
      (if (== S 2) (<> (text "んんっ・・・")))
      (if (== S 3) (<> (text "あはあ・・・")))
      (if (== S 4) (<> (text "んんんっ・・・")))
      (if (== S 5) (<> (text "んあ・・・")))
      (if (== S 6) (<> (text "だ、だめえ・・・")))
      (if (== S 7) (<> (text "あっ・・・")))
      (if (== S 8) (<> (text "んんあっ・・・")))
      (if (== S 9) (<> (text "い、いやあ・・・")))
      (text "あんっ・・・")
      (set-var S (? 10))
      (if (== S 0) (<> (text "あんっ・・・")))
      (if (== S 1) (<> (text "い・・・")))
      (if (== S 2) (<> (text "んんっ・・・")))
      (if (== S 3) (<> (text "あはあ・・・")))
      (if (== S 4) (<> (text "んんんっ・・・")))
      (if (== S 5) (<> (text "んあ・・・")))
      (if (== S 6) (<> (text "だ、だめえ・・・")))
      (if (== S 7) (<> (text "あっ・・・")))
      (if (== S 8) (<> (text "んんあっ・・・")))
      (if (== S 9) (<> (text "い、いやあ・・・")))
      (text "。")
      (wait)))
    ((&& (== V 8) (== N 9) (== (: 19) 0))
     (<> (text #:color 6 "【くるみ】あ・・・あ・・・ん・・・あ・・・。") (wait) (set-reg: 19 1)))
    ((&& (== V 8) (== N 9) (== (: 19) 1))
     (<> (text #:color 6 "【くるみ】んっ・・・あんっ・・・んん。") (wait) (set-reg: 19 2)))
    ((&& (== V 8) (== N 9) (== (: 19) 2))
     (<>
      (text #:color 6 "【くるみ】")
      (set-var S (? 10))
      (if (== S 0) (<> (text "あんっ・・・")))
      (if (== S 1) (<> (text "い・・・")))
      (if (== S 2) (<> (text "んんっ・・・")))
      (if (== S 3) (<> (text "あはあ・・・")))
      (if (== S 4) (<> (text "んんんっ・・・")))
      (if (== S 5) (<> (text "んあ・・・")))
      (if (== S 6) (<> (text "だ、だめえ・・・")))
      (if (== S 7) (<> (text "あっ・・・")))
      (if (== S 8) (<> (text "んんあっ・・・")))
      (if (== S 9) (<> (text "い、いやあ・・・")))
      (set-var S (? 10))
      (if (== S 0) (<> (text "あんっ・・・")))
      (if (== S 1) (<> (text "い・・・")))
      (if (== S 2) (<> (text "んんっ・・・")))
      (if (== S 3) (<> (text "あはあ・・・")))
      (if (== S 4) (<> (text "んんんっ・・・")))
      (if (== S 5) (<> (text "んあ・・・")))
      (if (== S 6) (<> (text "だ、だめえ・・・")))
      (if (== S 7) (<> (text "あっ・・・")))
      (if (== S 8) (<> (text "んんあっ・・・")))
      (if (== S 9) (<> (text "い、いやあ・・・")))
      (set-var S (? 10))
      (if (== S 0) (<> (text "あんっ・・・")))
      (if (== S 1) (<> (text "い・・・")))
      (if (== S 2) (<> (text "んんっ・・・")))
      (if (== S 3) (<> (text "あはあ・・・")))
      (if (== S 4) (<> (text "んんんっ・・・")))
      (if (== S 5) (<> (text "んあ・・・")))
      (if (== S 6) (<> (text "だ、だめえ・・・")))
      (if (== S 7) (<> (text "あっ・・・")))
      (if (== S 8) (<> (text "んんあっ・・・")))
      (if (== S 9) (<> (text "い、いやあ・・・")))
      (text "。")
      (wait)))
    ((&& (== V 10) (== N 10) (== (: 20) 0))
     (<> (text #:color 7 "【" 0 "】ぺっぺっぺっ！！") (wait) (set-reg: 20 1)))
    ((&& (== V 10) (== N 10) (== (: 20) 1))
     (<>
      (text #:color 7 "【" 0 "】ぺろぺろ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】まずいぞ。")
      (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))