(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\ク
  #\イ
  #\ズ
  #\【
  #\】
  #\い
  #\郎
  #\っ
  #\、
  #\て
  #\。
  #\す
  #\な
  #\し
  #\の
  #\０
  #\よ
  #\う
  #\ま
  #\る
  #\だ
  #\で
  #\た
  #\お
  #\に
  #\か
  #\は
  #\ん
  #\あ
  #\と
  #\が
  #\さ
  #\！
  #\ら
  #\れ
  #\く
  #\え
  #\？
  #\も
  #\ね
  #\ち
  #\を
  #\り
  #\四
  #\五
  #\み
  #\わ
  #\次
  #\太
  #\三
  #\ゃ
  #\ン
  #\チ
  #\円
  #\行
  #\３
  #\問
  #\題
  #\１
  #\や
  #\挑
  #\戦
  #\そ
  #\ど
  #\せ
  #\金
  #\前
  #\ご
  #\ろ
  #\け
  #\色
  #\セ
  #\き
  #\ず
  #\８
  #\こ
  #\時
  #\女
  #\情
  #\報
  #\ぜ
  #\持
  #\ッ
  #\正
  #\解
  #\先
  #\出
  #\知
  #\ょ
  #\子
  #\月
  #\ざ
  #\院
  #\ば
  #\じ
  #\店
  #\事
  #\げ
  #\見
  #\来
  #\当
  #\午
  #\歳
  #\ぞ
  #\９
  #\彼
  #\手
  #\入
  #\校
  #\教
  #\ふ
  #\本
  #\病
  #\学
  #\生
  #\つ
  #\７
  #\上
  #\払
  #\ビ
  #\ャ
  #\ス
  #\方
  #\ほ
  #\残
  #\念
  #\帰)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (sound 1)
 (set-var I 48)
 (proc 26)
 (set-reg: 835 0)
 (while
  (== 1 1)
  (<>
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((&& (== V 157) (> H 816) (== (: 250) 1) (== (: 681) 0))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text #:color 1 "【クイズ太郎】さてさて、いらっしゃいよ・・・１０００円払えば３０００円と、ビックな幸運が手に入るチャンスだ。")
      (wait)
      (text
       #:color
       1
       "【クイズ太郎】もちろん、ただで貰おうなんて思っちゃいけないぜ・・・クイズに正解したらドーンとプレゼントしちゃおう！！")
      (wait)
      (text #:color 1 "【クイズ太郎】さあさあっ・・・挑戦してみるかい？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "挑戦する") (text "挑戦しない")))
      (set-arr~ @ 7 1)
      (cond
       ((&& (== N 1) (< M 1000))
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ太郎】いよっ！！男だねえ、そうこなくちゃ・・・あれれ！？")
         (wait)
         (text #:color 1 "【クイズ太郎】なんだ、お金を持ってないじゃないか・・・しっしっしっ、商売の邪魔だ、あっちへ行けっ！！")
         (wait)
         (break)))
       ((== N 1)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ太郎】いよっ！！男だねえ、そうこなくちゃ・・・お金は先にいただくよっ！！")
         (wait)
         (set-var M (- M 1000))
         (proc 11)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ太郎】さてさて、問題だ・・・『仁科　くるみ』ちゃんは知ってるよな？")
         (wait)
         (text #:color 1 "【クイズ太郎】そのくるみちゃんと、最初に会った場所はどこだったでしょうか？・・・これが問題だぜ。")
         (wait)
         (text #:color 1 "【クイズ太郎】さあさあ、答えておくれっ！！")
         (wait)
         (set-reg: 101 1)
         (set-arr~ @ 7 0)
         (proc 18)
         (menu-show
          (<.>
           (text "学校の校庭")
           (text "小さい公園")
           (text "大きい公園")
           (text "映画館の前")
           (text "喫茶店の前")
           (text "先負駅の前")
           (text "ラブホテルの前")
           (text "工事現場")
           (text "ひろみの会社")
           (text "学校の保健室")))
         (set-arr~ @ 7 1)
         (cond
          ((== N 5)
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ太郎】・・・。")
            (wait)
            (text #:color 1 "【クイズ太郎】ど、どうしてわかっちゃうのお！？")
            (wait)
            (text #:color 1 "【クイズ太郎】仕方がない、ほれっ・・・持ってけ泥棒っ！！")
            (wait)
            (text #:color 1 "【クイズ太郎】・・・。")
            (wait)
            (text
             #:color
             1
             "【クイズ太郎】わかってるさ、ビックな幸運の話だろ・・・学校の教室に行ってみな、きっとすげえものが見られるぜ。")
            (wait)
            (set-reg: 781 1)
            (sound 1)
            (set-var I 58)
            (proc 26)
            (set-reg: 835 0)
            (set-var M (+ M 3000))
            (proc 11)
            (set-arr~ @ 13 15 322 64 391)
            (color 8)
            (clear)
            (text #:color 7 "【" 0 "】よし、行ってみるか・・・。")
            (wait)))
          ((//
            (== N 1)
            (== N 2)
            (== N 3)
            (== N 4)
            (== N 6)
            (== N 7)
            (== N 8)
            (== N 9)
            (== N 10))
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ太郎】はっはっはっ！！残念でしたっ・・・また来てくれよっ！！")
            (wait)))
          (else (<>)))
         (set-reg: 681 1)))
       ((== N 2)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ太郎】なんだ、挑戦しないのか・・・商売の邪魔だ、帰ってくれよ。")
         (wait)
         (break)))
       (else (<>)))
      (break)))
    ((&& (== V 157) (> H 812) (== (: 253) 1) (== (: 682) 0))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text #:color 1 "【クイズ太郎】さてさて、いらっしゃいよ・・・１０００円払えば３０００円とビックな幸運が手に入るチャンスだ。")
      (wait)
      (text
       #:color
       1
       "【クイズ太郎】もちろん、ただで貰おうなんて思っちゃいけないぜ・・・クイズに正解したらドーンとプレゼントしちゃおう！！")
      (wait)
      (text #:color 1 "【クイズ太郎】さあさあっ・・・挑戦してみるかい？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "挑戦する") (text "挑戦しない")))
      (set-arr~ @ 7 1)
      (cond
       ((&& (== N 1) (< M 1000))
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ太郎】いよっ！！男だねえ、そうこなくちゃ・・・あれれ！？")
         (wait)
         (text #:color 1 "【クイズ太郎】なんだ、お金を持ってないじゃないか・・・しっしっしっ、商売の邪魔だ、あっちへ行けっ！！")
         (wait)
         (break)))
       ((== N 1)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ太郎】いよっ！！男だねえ、そうこなくちゃ・・・お金は先にいただくよっ！！")
         (wait)
         (set-var M (- M 1000))
         (proc 11)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ太郎】さてさて、問題だ・・・『斎藤　真子』先生は知ってるよな？")
         (wait)
         (text #:color 1 "【クイズ太郎】その真子先生と、階段でぶつかった事は覚えているだろう？")
         (wait)
         (text
          #:color
          1
          "【クイズ太郎】さてさて、問題だ・・・君は先生とぶつかり、先生の持っていた書類が空中にぶちまかれたわけだ！！")
         (wait)
         (text #:color 1 "【クイズ太郎】ずばり！！・・・その時、先生がはいていた下着の色は？")
         (wait)
         (text #:color 1 "【クイズ太郎】さあさあ、答えておくれっ！！")
         (wait)
         (set-reg: 101 1)
         (set-arr~ @ 7 0)
         (proc 18)
         (menu-show
          (<.>
           (text "白色")
           (text "ピンク色")
           (text "赤色")
           (text "茶色")
           (text "透明")
           (text "緑色")
           (text "黒色")
           (text "水色")
           (text "青色")
           (text "はいてない")))
         (set-arr~ @ 7 1)
         (cond
          ((== N 7)
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ太郎】・・・。")
            (wait)
            (text #:color 1 "【クイズ太郎】ど、どうしてわかっちゃうのお！？")
            (wait)
            (text #:color 1 "【クイズ太郎】仕方がない、ほれっ・・・持ってけ泥棒っ！！")
            (wait)
            (text #:color 1 "【クイズ太郎】・・・。")
            (wait)
            (text
             #:color
             1
             "【クイズ太郎】わかってるさ、ビックな幸運の話だろ・・・夕方に空き地に行ってみな、きっとすげえものが見られるぜ。")
            (wait)
            (set-reg: 784 1)
            (sound 1)
            (set-var I 58)
            (proc 26)
            (set-reg: 835 0)
            (set-var M (+ M 3000))
            (proc 11)
            (set-arr~ @ 13 15 322 64 391)
            (color 8)
            (clear)
            (text #:color 7 "【" 0 "】よし、行ってみるか・・・。")
            (wait)))
          ((//
            (== N 1)
            (== N 2)
            (== N 3)
            (== N 4)
            (== N 5)
            (== N 6)
            (== N 8)
            (== N 9)
            (== N 10))
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ太郎】はっはっはっ！！残念でしたっ・・・また来てくれよっ！！")
            (wait)))
          (else (<>)))
         (set-reg: 682 1)))
       ((== N 2)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ太郎】なんだ、挑戦しないのか・・・商売の邪魔だ、帰ってくれよ。")
         (wait)
         (break)))
       (else (<>)))
      (break)))
    ((&& (== V 157) (== (: 681) 1) (== (: 682) 1))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text #:color 1 "【クイズ太郎】悪いな・・・うちはもう店じまいだ。")
      (wait)
      (text #:color 1 "【クイズ太郎】俺の兄弟がやってる店もあるから・・・よかったら、そっちに行ってくれ。")
      (wait)
      (break)))
    ((== V 157)
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text #:color 1 "【クイズ太郎】悪いな・・・まだ君には問題が出せないんだ。")
      (wait)
      (text #:color 1 "【クイズ太郎】しばらくたってから、また店に来てくれよ・・・問題が出せる時を楽しみに待ってるぜ。")
      (wait)
      (break)))
    ((&& (== V 166) (> H 815) (== (: 264) 1) (== (: 683) 0))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text #:color 1 "【クイズ次郎】お前は客か？・・・１０００円払えば３０００円と、いい情報が手に入るチャンスだぞ。")
      (wait)
      (text #:color 1 "【クイズ次郎】もちろん、ただで貰おうなんて思うなよ・・・クイズに正解したらくれてやるぜ。")
      (wait)
      (text #:color 1 "【クイズ次郎】ふん・・・挑戦するか？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "挑戦する") (text "挑戦しない")))
      (set-arr~ @ 7 1)
      (cond
       ((&& (== N 1) (< M 1000))
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ次郎】なんだ、本当にやるのか？")
         (wait)
         (text #:color 1 "【クイズ次郎】・・・。")
         (wait)
         (text #:color 1 "【クイズ次郎】お前、金を持ってないな・・・しっしっしっ！！")
         (wait)
         (break)))
       ((== N 1)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ次郎】なんだよう・・・本当にやるのか？")
         (wait)
         (set-var M (- M 1000))
         (proc 11)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ次郎】仕方がない、問題を出してやるぜ・・・『田町　ひろみ』という女の子は知ってるよな？")
         (wait)
         (text #:color 1 "【クイズ次郎】お前はひろみという女と、一緒に喫茶店に行ったはずだ・・・そうだろう？")
         (wait)
         (text #:color 1 "【クイズ次郎】その喫茶店で君とひろみはデートの約束をした・・・さて、ここからが問題だぞ。")
         (wait)
         (text #:color 1 "【クイズ次郎】デートの約束は８月１７日の何時だ？・・・さあ、答えてみろよ。")
         (wait)
         (set-reg: 101 1)
         (set-arr~ @ 7 0)
         (proc 18)
         (menu-show
          (<.>
           (text "午前７時")
           (text "午前８時")
           (text "午前１０時")
           (text "午前１１時")
           (text "午後１時")
           (text "午後２時")
           (text "午後３時")
           (text "午後４時")
           (text "午後５時")
           (text "午後６時")))
         (set-arr~ @ 7 1)
         (cond
          ((== N 4)
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ次郎】・・・。")
            (wait)
            (text #:color 1 "【クイズ次郎】ど、どうしてわかるんだ！？")
            (wait)
            (text #:color 1 "【クイズ次郎】ちくしょう・・・持ってけ泥棒っ！！")
            (wait)
            (text #:color 1 "【クイズ次郎】いい情報も教えてやるぜ・・・ちょっともったいない気もするけどな。")
            (wait)
            (text #:color 1 "【クイズ次郎】学校の屋上に行ってみな・・・きっとすげえもんが見られるぜ。")
            (wait)
            (set-reg: 789 1)
            (sound 1)
            (set-var I 58)
            (proc 26)
            (set-reg: 835 0)
            (set-var M (+ M 3000))
            (proc 11)
            (set-arr~ @ 13 15 322 64 391)
            (color 8)
            (clear)
            (text #:color 7 "【" 0 "】よし、行ってみるか・・・。")
            (wait)))
          ((//
            (== N 1)
            (== N 2)
            (== N 3)
            (== N 5)
            (== N 6)
            (== N 7)
            (== N 8)
            (== N 9)
            (== N 10))
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ次郎】はずれだよ・・・ざまあみろ。")
            (wait)))
          (else (<>)))
         (set-reg: 683 1)))
       ((== N 2)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ次郎】帰れよ・・・ふん。")
         (wait)
         (break)))
       (else (<>)))
      (break)))
    ((&& (== V 166) (> H 818) (== (: 413) 1) (== (: 684) 0))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text #:color 1 "【クイズ次郎】お前は客か？・・・１０００円払えば３０００円といい情報が手に入るチャンスだぞ。")
      (wait)
      (text #:color 1 "【クイズ次郎】もちろん、ただで貰おうなんて思うなよ・・・クイズに正解したらくれてやるぜ。")
      (wait)
      (text #:color 1 "【クイズ次郎】ふん・・・挑戦するか？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "挑戦する") (text "挑戦しない")))
      (set-arr~ @ 7 1)
      (cond
       ((&& (== N 1) (< M 1000))
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ次郎】なんだ、本当にやるのか？")
         (wait)
         (text #:color 1 "【クイズ次郎】・・・。")
         (wait)
         (text #:color 1 "【クイズ次郎】お前、金を持ってないな・・・しっしっしっ！！")
         (wait)
         (break)))
       ((== N 1)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ次郎】なんだよう・・・本当にやるのか？")
         (wait)
         (set-var M (- M 1000))
         (proc 11)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ次郎】仕方がない、問題を出してやるぜ・・・『黒川　さとみ』という女の子は知ってるよな？")
         (wait)
         (text #:color 1 "【クイズ次郎】お前はさとみと河原で会ったはずだ・・・さて、問題だぞ。")
         (wait)
         (text #:color 1 "【クイズ次郎】話の中で、さとみの胸のサイズを聞いたはずだ・・・さあ、あの女の胸は何センチだ？")
         (wait)
         (set-reg: 101 1)
         (set-arr~ @ 7 0)
         (proc 18)
         (menu-show
          (<.>
           (text "７８センチ")
           (text "７９センチ")
           (text "８０センチ")
           (text "８１センチ")
           (text "８２センチ")
           (text "８３センチ")
           (text "８４センチ")
           (text "８５センチ")
           (text "８６センチ")
           (text "８７センチ")))
         (set-arr~ @ 7 1)
         (cond
          ((== N 3)
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ次郎】・・・。")
            (wait)
            (text #:color 1 "【クイズ次郎】ど、どうしてわかるんだ！？")
            (wait)
            (text #:color 1 "【クイズ次郎】ちくしょう・・・持ってけ泥棒っ！！")
            (wait)
            (text #:color 1 "【クイズ次郎】いい情報も教えてやるぜ・・・ちょっともったいない気もするけどな。")
            (wait)
            (text #:color 1 "【クイズ次郎】深夜のラブホテルに行ってみな・・・きっとすげえもんが見られるぜ。")
            (wait)
            (set-reg: 792 1)
            (sound 1)
            (set-var I 58)
            (proc 26)
            (set-reg: 835 0)
            (set-var M (+ M 3000))
            (proc 11)
            (set-arr~ @ 13 15 322 64 391)
            (color 8)
            (clear)
            (text #:color 7 "【" 0 "】よし、行ってみるか・・・。")
            (wait)))
          ((//
            (== N 1)
            (== N 2)
            (== N 4)
            (== N 5)
            (== N 6)
            (== N 7)
            (== N 8)
            (== N 9)
            (== N 10))
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ次郎】はずれだよ・・・ざまあみろ。")
            (wait)))
          (else (<>)))
         (set-reg: 684 1)))
       ((== N 2)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ次郎】帰れよ・・・ふん。")
         (wait)
         (break)))
       (else (<>)))
      (break)))
    ((&& (== V 166) (== (: 683) 1) (== (: 684) 1))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text #:color 1 "【クイズ次郎】もうこの商売はやらないよ・・・。")
      (wait)
      (text #:color 1 "【クイズ次郎】俺の兄弟がやってる店もあるから、そっちに行けよ・・・俺はもうこりごりだぜ。")
      (wait)
      (break)))
    ((== V 166)
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text #:color 1 "【クイズ次郎】ふんふん・・・お前みたいなやつに、問題は出してやらないよ。")
      (wait)
      (text #:color 1 "【クイズ次郎】また今度来てみるんだな・・・あばよっ！！")
      (wait)
      (break)))
    ((&& (== V 230) (> H 811) (== (: 162) 1) (== (: 775) 0))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text
       #:color
       1
       "【クイズ三郎】いらっしゃいませ・・・１０００円払えば３０００円と、とってもお得な情報が手に入るという、ビックなチャンスがあなたをお待ちしております。")
      (wait)
      (text #:color 1 "【クイズ三郎】もちろん、ただで差し上げる訳にはまいりません・・・クイズに正解したら差し上げます。")
      (wait)
      (text #:color 1 "【クイズ三郎】どう致しますか？・・・おやりになりますか？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "挑戦する") (text "挑戦しない")))
      (set-arr~ @ 7 1)
      (cond
       ((&& (== N 1) (< M 1000))
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ三郎】ありがとうございます。")
         (wait)
         (text #:color 1 "【クイズ三郎】・・・。")
         (wait)
         (text #:color 1 "【クイズ三郎】失礼ですが、お金をお持ちではないようですね・・・お引き取りください。")
         (wait)
         (break)))
       ((== N 1)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ三郎】ありがとうございます・・・それでは前金として、１０００円あずからせていただきます。")
         (wait)
         (set-var M (- M 1000))
         (proc 11)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ三郎】それでは問題です・・・簡単な問題ですからご安心ください。")
         (wait)
         (text #:color 1 "【クイズ三郎】先負町にある唯一の病院・・・あなたは行った事がありますね？")
         (wait)
         (text #:color 1 "【クイズ三郎】さて、その病院の名前は・・・いったい何でしょう？")
         (wait)
         (set-reg: 101 1)
         (set-arr~ @ 7 0)
         (proc 18)
         (menu-show
          (<.>
           (text "先負医院")
           (text "先負病院")
           (text "猿渡り医院")
           (text "猿渡り病院")
           (text "登渡り医院")
           (text "登渡り病院")
           (text "先負総合病院")
           (text "腰掛け医院")
           (text "腰掛け病院")
           (text "泌尿器病院")))
         (set-arr~ @ 7 1)
         (cond
          ((== N 5)
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ三郎】・・・。")
            (wait)
            (text #:color 1 "【クイズ三郎】す、すごい・・・ご正解ですっ！！")
            (wait)
            (text #:color 1 "【クイズ三郎】どうぞ、これが賞金の３０００円です・・・またおいでください。")
            (wait)
            (text
             #:color
             1
             "【クイズ三郎】おっと、まだお帰りになるのは早かったですね・・・とってもお得な情報を教えて差し上げます。")
            (wait)
            (text #:color 1 "【クイズ三郎】学校の音楽室に行ってごらんなさい・・・きっと面白いものが見れますよ。")
            (wait)
            (set-reg: 795 1)
            (sound 1)
            (set-var I 58)
            (proc 26)
            (set-reg: 835 0)
            (set-var M (+ M 3000))
            (proc 11)
            (set-arr~ @ 13 15 322 64 391)
            (color 8)
            (clear)
            (text #:color 7 "【" 0 "】よし、行ってみるか・・・。")
            (wait)))
          ((//
            (== N 1)
            (== N 2)
            (== N 3)
            (== N 4)
            (== N 6)
            (== N 7)
            (== N 8)
            (== N 9)
            (== N 10))
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ三郎】はずれです・・・残念でした。")
            (wait)))
          (else (<>)))
         (set-reg: 775 1)))
       ((== N 2)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ三郎】そうですか・・・また来てくださいね。")
         (wait)
         (break)))
       (else (<>)))
      (break)))
    ((&& (== V 230) (> H 817) (== (: 480) 1) (== (: 776) 0))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text
       #:color
       1
       "【クイズ三郎】いらっしゃいませ・・・１０００円払えば３０００円と、とってもお得な情報が手に入る、ビックなチャンスがあなたをお待ちしております。")
      (wait)
      (text #:color 1 "【クイズ三郎】もちろん、ただで差し上げる訳にはまいりません・・・クイズに正解したら差し上げます。")
      (wait)
      (text #:color 1 "【クイズ三郎】どう致しますか？・・・おやりになりますか？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "挑戦する") (text "挑戦しない")))
      (set-arr~ @ 7 1)
      (cond
       ((&& (== N 1) (< M 1000))
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ三郎】ありがとうございます。")
         (wait)
         (text #:color 1 "【クイズ三郎】・・・。")
         (wait)
         (text #:color 1 "【クイズ三郎】失礼ですが、お金をお持ちではないようですね・・・お引き取りください。")
         (wait)
         (break)))
       ((== N 1)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ三郎】ありがとうございます・・・それでは前金として、１０００円あずからせていただきます。")
         (wait)
         (set-var M (- M 1000))
         (proc 11)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ三郎】それでは問題です・・・簡単な問題ですからご安心ください。")
         (wait)
         (text
          #:color
          1
          "【クイズ三郎】夏子さんという女性を御存知のはずです・・・最近、彼女がブティックをやめてしまった事は知ってますね？")
         (wait)
         (text #:color 1 "【クイズ三郎】さて、問題です・・・夏子さんの代わりに店をやる女性の年齢は、いったいいくつでしょう？")
         (wait)
         (set-reg: 101 1)
         (set-arr~ @ 7 0)
         (proc 18)
         (menu-show
          (<.>
           (text "３１歳")
           (text "３２歳")
           (text "３３歳")
           (text "３４歳")
           (text "３５歳")
           (text "３６歳")
           (text "３７歳")
           (text "３８歳")
           (text "３９歳")
           (text "４０歳")))
         (set-arr~ @ 7 1)
         (cond
          ((== N 10)
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ三郎】・・・。")
            (wait)
            (text #:color 1 "【クイズ三郎】す、すごい・・・ご正解ですっ！！")
            (wait)
            (text #:color 1 "【クイズ三郎】どうぞ、これが賞金の３０００円です・・・またおいでください。")
            (wait)
            (text
             #:color
             1
             "【クイズ三郎】おっと、まだお帰りになるのは早かったですね・・・とってもお得な情報を教えて差し上げます。")
            (wait)
            (text
             #:color
             1
             "【クイズ三郎】とある会社に行くと、すごい光景を見る事ができますよ・・・もちろん、就業時間外に行かないと駄目ですけどね。")
            (wait)
            (set-reg: 798 1)
            (sound 1)
            (set-var I 58)
            (proc 26)
            (set-reg: 835 0)
            (set-var M (+ M 3000))
            (proc 11)
            (set-arr~ @ 13 15 322 64 391)
            (color 8)
            (clear)
            (text #:color 7 "【" 0 "】よし、行ってみるか・・・。")
            (wait)))
          ((//
            (== N 1)
            (== N 2)
            (== N 3)
            (== N 4)
            (== N 6)
            (== N 7)
            (== N 8)
            (== N 9)
            (== N 5))
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ三郎】はずれです・・・残念でした。")
            (wait)))
          (else (<>)))
         (set-reg: 776 1)))
       ((== N 2)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ三郎】そうですか・・・また来てくださいね。")
         (wait)
         (break)))
       (else (<>)))
      (break)))
    ((&& (== V 230) (== (: 775) 1) (== (: 776) 1))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text #:color 1 "【クイズ三郎】すいません、損してばかりなので廃業しました。")
      (wait)
      (text #:color 1 "【クイズ三郎】私の兄弟がやっている店がありますから・・・よろしければ、そちらの方にどうぞ。")
      (wait)
      (break)))
    ((== V 230)
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text #:color 1 "【クイズ三郎】すいません、まだ問題を用意してません・・・また今度来てみてください。")
      (wait)
      (break)))
    ((&& (== V 244) (== (: 709) 1) (== (: 777) 0))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text
       #:color
       1
       "【クイズ四郎】い、いらっしゃい・・・ク、クイズに正解すると１０００円が３０００円になり、さらに耳寄りな情報が手に入りますよう。")
      (wait)
      (text #:color 1 "【クイズ四郎】ほ、本当ですよお・・・そんな疑いの目で見ないでくださいよう。")
      (wait)
      (text #:color 1 "【クイズ四郎】ど、どうしますか？・・・やってもらえますか？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "挑戦する") (text "挑戦しない")))
      (set-arr~ @ 7 1)
      (cond
       ((&& (== N 1) (< M 1000))
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ四郎】あ、ありがとうございますう。")
         (wait)
         (text #:color 1 "【クイズ四郎】・・・。")
         (wait)
         (text #:color 1 "【クイズ四郎】お、お金を持ってないですよう・・・勘弁してくださいよう。")
         (wait)
         (break)))
       ((== N 1)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ四郎】あ、ありがとうございます・・・すいません、前金として１０００円もらえますか？")
         (wait)
         (set-var M (- M 1000))
         (proc 11)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ四郎】す、すいません・・・問題を出させていただきます。")
         (wait)
         (text
          #:color
          1
          "【クイズ四郎】あ、あなたのお友達に、美沙ちゃんという女の子がいます・・・彼女は先日、肉離れを起こしてしまいました。")
         (wait)
         (text #:color 1 "【クイズ四郎】ぼ、僕のせいじゃないですからね・・・言っておきますけど。")
         (wait)
         (text #:color 1 "【クイズ四郎】さ、さて、問題です・・・彼女は身体のどの部分を怪我してしまったのでしょう？")
         (wait)
         (set-reg: 101 1)
         (set-arr~ @ 7 0)
         (proc 18)
         (menu-show
          (<.>
           (text "頭")
           (text "顔")
           (text "胸")
           (text "左腕")
           (text "右腕")
           (text "右のおっぱい")
           (text "左のおっぱい")
           (text "お腹")
           (text "左脚")
           (text "右脚")))
         (set-arr~ @ 7 1)
         (cond
          ((== N 9)
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ四郎】・・・。")
            (wait)
            (text #:color 1 "【クイズ四郎】あ、当たってしまった・・・ぐっすん。")
            (wait)
            (text #:color 1 "【クイズ四郎】ど、どうぞ、これが賞金の３０００円です・・・ぐっすん。")
            (wait)
            (text #:color 1 "【クイズ四郎】わ、わかってますよう・・・耳寄りな情報も教えますよう。")
            (wait)
            (text #:color 1 "【クイズ四郎】が、学校の美術室に行くと、すごい事をやってますよ・・・ほ、本当ですよう。")
            (wait)
            (set-reg: 801 1)
            (sound 1)
            (set-var I 58)
            (proc 26)
            (set-reg: 835 0)
            (set-var M (+ M 3000))
            (proc 11)
            (set-arr~ @ 13 15 322 64 391)
            (color 8)
            (clear)
            (text #:color 7 "【" 0 "】よし、行ってみるか・・・。")
            (wait)))
          ((//
            (== N 1)
            (== N 2)
            (== N 3)
            (== N 4)
            (== N 6)
            (== N 7)
            (== N 8)
            (== N 5)
            (== N 10))
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ四郎】は、はずれです・・・怒らないでくださいね。")
            (wait)))
          (else (<>)))
         (set-reg: 777 1)))
       ((== N 2)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ四郎】そ、そんなあ・・・遊んでってくださいよう。")
         (wait)
         (break)))
       (else (<>)))
      (break)))
    ((&& (== V 244) (> H 810) (== (: 170) 1) (== (: 778) 0))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text
       #:color
       1
       "【クイズ四郎】い、いらっしゃい・・・ク、クイズに正解すると１０００円が３０００円になり、さらに耳寄りな情報が手に入りますよう。")
      (wait)
      (text #:color 1 "【クイズ四郎】ほ、本当ですよお・・・そんな疑いの目で見ないでくださいよう。")
      (wait)
      (text #:color 1 "【クイズ四郎】ど、どうしますか？・・・やってもらえますか？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "挑戦する") (text "挑戦しない")))
      (set-arr~ @ 7 1)
      (cond
       ((&& (== N 1) (< M 1000))
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ四郎】あ、ありがとうございますう。")
         (wait)
         (text #:color 1 "【クイズ四郎】・・・。")
         (wait)
         (text #:color 1 "【クイズ四郎】お、お金を持ってないですよう・・・勘弁してくださいよう。")
         (wait)
         (break)))
       ((== N 1)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ四郎】あ、ありがとうございます・・・すいません、前金として１０００円もらえますか？")
         (wait)
         (set-var M (- M 1000))
         (proc 11)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ四郎】す、すいません・・・問題を出させていただきます。")
         (wait)
         (text #:color 1 "【クイズ四郎】あ、あなたのお友達に、美穂ちゃんという女の子がいます・・・し、知ってますよね？")
         (wait)
         (text
          #:color
          1
          "【クイズ四郎】と、とってもかわいい子で、僕好みの子ですよね・・・時々僕も、は、花屋さんに行って、彼女の顔を見に・・・。")
         (wait)
         (text #:color 1 "【クイズ四郎】す、すいません・・・な、何もしてないですよう、僕は。")
         (wait)
         (text #:color 1 "【クイズ四郎】も、問題です・・・彼女はいつもリボンをしてますが、その色は何色でしょう？")
         (wait)
         (set-reg: 101 1)
         (set-arr~ @ 7 0)
         (proc 18)
         (menu-show
          (<.>
           (text "白色")
           (text "黄色")
           (text "黒色")
           (text "赤色")
           (text "青色")
           (text "紫色")
           (text "茶色")
           (text "緑色")
           (text "紺色")
           (text "ピンク色")))
         (set-arr~ @ 7 1)
         (cond
          ((== N 2)
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ四郎】・・・。")
            (wait)
            (text #:color 1 "【クイズ四郎】あ、当たってしまった・・・ぐっすん。")
            (wait)
            (text #:color 1 "【クイズ四郎】ど、どうぞ、これが賞金の３０００円です・・・ぐっすん。")
            (wait)
            (text #:color 1 "【クイズ四郎】わ、わかってますよう・・・耳寄りな情報も教えますよう。")
            (wait)
            (text
             #:color
             1
             "【クイズ四郎】く、車が置いてある場所に行くと、すごい事を見れるはずですよ・・・ほ、本当ですよう、嘘じゃないですよう。")
            (wait)
            (set-reg: 804 1)
            (sound 1)
            (set-var I 58)
            (proc 26)
            (set-reg: 835 0)
            (set-var M (+ M 3000))
            (proc 11)
            (set-arr~ @ 13 15 322 64 391)
            (color 8)
            (clear)
            (text #:color 7 "【" 0 "】よし、行ってみるか・・・。")
            (wait)))
          ((//
            (== N 1)
            (== N 9)
            (== N 3)
            (== N 4)
            (== N 6)
            (== N 7)
            (== N 8)
            (== N 5)
            (== N 10))
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ四郎】は、はずれです・・・怒らないでくださいね。")
            (wait)))
          (else (<>)))
         (set-reg: 778 1)))
       ((== N 2)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ四郎】そうですか・・・また来てくださいね。")
         (wait)
         (break)))
       (else (<>)))
      (break)))
    ((&& (== V 244) (== (: 777) 1) (== (: 778) 1))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text #:color 1 "【クイズ四郎】す、すいません、もう出す問題がないんですよう・・・。")
      (wait)
      (text #:color 1 "【クイズ四郎】わ、私の兄弟がやっている店がありますから・・・そっちに行ってくださいよう。")
      (wait)
      (break)))
    ((== V 244)
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text #:color 1 "【クイズ四郎】す、すいません、まだ問題を用意してません・・・また今度来てくださいよう。")
      (wait)
      (break)))
    ((&& (== V 265) (== (: 317) 1) (== (: 779) 0))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text
       #:color
       1
       "【クイズ五郎】いらっしゃあい・・・クイズに答えるだけで、１０００円が３０００円になって、さらにエッチな情報をお知らせするわよお。")
      (wait)
      (text #:color 1 "【クイズ五郎】もちろん、クイズに正解しないと駄目だからね・・・やってみる？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "挑戦する") (text "挑戦しない")))
      (set-arr~ @ 7 1)
      (cond
       ((&& (== N 1) (< M 1000))
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ五郎】うれしいわあ・・・。")
         (wait)
         (text #:color 1 "【クイズ五郎】・・・。")
         (wait)
         (text #:color 1 "【クイズ五郎】おうっ、金を持ってないじゃねえか・・・ふざけんなガキっ！！")
         (wait)
         (break)))
       ((== N 1)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ五郎】まあ、やってくれるのね・・・うれしいわあ。")
         (wait)
         (text #:color 1 "【クイズ五郎】前金として、１０００円いただくわねえ・・・じゃあ問題を出すわよお。")
         (wait)
         (set-var M (- M 1000))
         (proc 11)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ五郎】亜子さんの事は知ってるわよね・・・知らないとは言わせないわよお。")
         (wait)
         (text
          #:color
          1
          "【クイズ五郎】彼女のお尻が、すべり台にはさまった時の事は覚えているわよねえ・・・あなたがその事を忘れるはずがないもの。")
         (wait)
         (text #:color 1 "【クイズ五郎】問題を出すわよお・・・亜子さんのおヒップのサイズはいくつだったかしら？")
         (wait)
         (set-reg: 101 1)
         (set-arr~ @ 7 0)
         (proc 18)
         (menu-show
          (<.>
           (text "８５センチ")
           (text "８６センチ")
           (text "８７センチ")
           (text "８８センチ")
           (text "８９センチ")
           (text "９０センチ")
           (text "９１センチ")
           (text "９２センチ")
           (text "９３センチ")
           (text "９４センチ")))
         (set-arr~ @ 7 1)
         (cond
          ((== N 5)
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ五郎】・・・。")
            (wait)
            (text #:color 1 "【クイズ五郎】正解よお・・・すごい記憶力じゃない。")
            (wait)
            (text #:color 1 "【クイズ五郎】これが賞金の３０００円ね・・・また挑戦してねえ。")
            (wait)
            (text #:color 1 "【クイズ五郎】・・・。")
            (wait)
            (text #:color 1 "【クイズ五郎】わかってるわよお、エッチな情報でしょ？・・・あなたも好きねえ。")
            (wait)
            (text #:color 1 "【クイズ五郎】学校の教室に行ってみたらあ・・・エッチよお、きっと。")
            (wait)
            (set-reg: 807 1)
            (sound 1)
            (set-var I 58)
            (proc 26)
            (set-reg: 835 0)
            (set-var M (+ M 3000))
            (proc 11)
            (set-arr~ @ 13 15 322 64 391)
            (color 8)
            (clear)
            (text #:color 7 "【" 0 "】よし、行ってみるか・・・。")
            (wait)))
          ((//
            (== N 1)
            (== N 2)
            (== N 3)
            (== N 4)
            (== N 6)
            (== N 7)
            (== N 8)
            (== N 9)
            (== N 10))
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ五郎】残念ねえ、はずれよお。")
            (wait)))
          (else (<>)))
         (set-reg: 779 1)))
       ((== N 2)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ五郎】なによ、遊んでってくれないのお・・・冷たいわねえ。")
         (wait)
         (break)))
       (else (<>)))
      (break)))
    ((&& (== V 265) (== (: 762) 1) (== (: 780) 0))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text
       #:color
       1
       "【クイズ五郎】いらっしゃあい・・・クイズに答えるだけで、１０００円が３０００円になって、さらにエッチな情報をお知らせするわよお。")
      (wait)
      (text #:color 1 "【クイズ五郎】もちろん、クイズに正解しないと駄目だからね・・・やってみる？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "挑戦する") (text "挑戦しない")))
      (set-arr~ @ 7 1)
      (cond
       ((&& (== N 1) (< M 1000))
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ五郎】うれしいわあ・・・。")
         (wait)
         (text #:color 1 "【クイズ五郎】・・・。")
         (wait)
         (text #:color 1 "【クイズ五郎】おうっ、金を持ってないじゃねえか・・・ふざけんなガキっ！！")
         (wait)
         (break)))
       ((== N 1)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ五郎】まあ、やってくれるのね・・・うれしいわあ。")
         (wait)
         (text #:color 1 "【クイズ五郎】前金として、１０００円いただくわねえ・・・じゃあ問題を出すわよお。")
         (wait)
         (set-var M (- M 1000))
         (proc 11)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ五郎】舞ちゃんの事は知ってるわよねえ・・・彼女についての問題を出すわよお。")
         (wait)
         (text #:color 1 "【クイズ五郎】彼女と一緒に、遊園地に行ったわねえ・・・あの時の彼女との会話で誕生日の話が出たはずよお。")
         (wait)
         (text #:color 1 "【クイズ五郎】さあ、舞ちゃんの誕生日は何月でしょう？・・・簡単な問題よねえ。")
         (wait)
         (set-reg: 101 1)
         (set-arr~ @ 7 0)
         (proc 18)
         (menu-show
          (<.>
           (text "１月")
           (text "２月")
           (text "３月")
           (text "４月")
           (text "５月")
           (text "６月")
           (text "９月")
           (text "１０月")
           (text "１１月")
           (text "１２月")))
         (set-arr~ @ 7 1)
         (cond
          ((== N 10)
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ五郎】・・・。")
            (wait)
            (text #:color 1 "【クイズ五郎】正解よお・・・すごい記憶力じゃない。")
            (wait)
            (text #:color 1 "【クイズ五郎】これが賞金の３０００円ね・・・また挑戦してねえ。")
            (wait)
            (text #:color 1 "【クイズ五郎】・・・。")
            (wait)
            (text #:color 1 "【クイズ五郎】わかってるわよお、エッチな情報でしょ？・・・あなたも好きねえ。")
            (wait)
            (text #:color 1 "【クイズ五郎】夜中に空き地に行ってみたらあ・・・エッチよお、きっと。")
            (wait)
            (set-reg: 810 1)
            (sound 1)
            (set-var I 58)
            (proc 26)
            (set-reg: 835 0)
            (set-var M (+ M 3000))
            (proc 11)
            (set-arr~ @ 13 15 322 64 391)
            (color 8)
            (clear)
            (text #:color 7 "【" 0 "】よし、行ってみるか・・・。")
            (wait)))
          ((//
            (== N 1)
            (== N 2)
            (== N 3)
            (== N 4)
            (== N 6)
            (== N 7)
            (== N 8)
            (== N 9)
            (== N 5))
           (<>
            (set-arr~ @ 13 28 48 65 127)
            (color 8)
            (clear)
            (text #:color 1 "【クイズ五郎】残念ねえ、はずれよお。")
            (wait)))
          (else (<>)))
         (set-reg: 780 1)))
       ((== N 2)
        (<>
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 1 "【クイズ五郎】なによ、遊んでってくれないのお・・・冷たいわねえ。")
         (wait)
         (break)))
       (else (<>)))
      (break)))
    ((&& (== V 265) (== (: 779) 1) (== (: 780) 1))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text #:color 1 "【クイズ五郎】悪いわねえ、問題がないのよ・・・もう。")
      (wait)
      (text #:color 1 "【クイズ五郎】私の兄弟がやってる店があるからあ・・・そっちに行ってみたらどう？")
      (wait)
      (break)))
    ((== V 265)
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao28.pd8")
      (proc 15)
      (text #:color 1 "【クイズ五郎】ごめんなさいねえ・・・まだ問題を用意してないのお。")
      (wait)
      (text #:color 1 "【クイズ五郎】もう少し経験を積んでから来てみてねえ・・・今日は駄目なのよお。")
      (wait)
      (break)))
    (else (<>)))))
 (set-arr~ @ 7 1))