(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\な
  #\い
  #\。
  #\の
  #\だ
  #\、
  #\ん
  #\っ
  #\か
  #\る
  #\て
  #\に
  #\う
  #\は
  #\こ
  #\が
  #\し
  #\た
  #\あ
  #\？
  #\と
  #\で
  #\も
  #\よ
  #\く
  #\ち
  #\ら
  #\ゃ
  #\そ
  #\ー
  #\家
  #\ど
  #\さ
  #\子
  #\ま
  #\を
  #\え
  #\み
  #\ン
  #\麗
  #\俺
  #\ぜ
  #\り
  #\れ
  #\！
  #\や
  #\事
  #\一
  #\何
  #\美
  #\き
  #\人
  #\す
  #\つ
  #\け
  #\お
  #\ろ
  #\太
  #\郎
  #\住
  #\入
  #\ぞ
  #\じ
  #\見
  #\女
  #\君
  #\行
  #\イ
  #\穂
  #\言
  #\聞
  #\寂
  #\手
  #\哉
  #\性
  #\ロ
  #\中
  #\げ
  #\沙
  #\真
  #\気
  #\度
  #\チ
  #\ピ
  #\ポ)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "47.pd8")
 (proc 15)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "47.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (cond
  ((&& (== (: 153) 0) (== (: 280) 0))
   (<>
    (text #:color 7 "【" 0 "】ここは、俺の部屋の窓から庭が見える家だな・・・。")
    (wait)
    (text #:color 7 "【" 0 "】誰もいないようだけど・・・他人の家に勝手に入っちゃいけないぜ、おい。")
    (wait)))
  ((&& (== (: 366) 0) (== (: 287) 1) (> T 1000) (< T 2300) (== (: 481) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "i.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ran.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "r.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 5 "【一哉】やあ、" 0 "。")
    (wait)
    (text #:color 7 "【" 0 "】くんか、くんか・・・女の匂いがするぞ。")
    (wait)
    (text #:color 5 "【一哉】冗談はよせよ・・・そんな事より" 0 "、最後の夏休みの思い出はつくれそうか？")
    (wait)
    (text #:color 7 "【" 0 "】ぼちぼちだな。")
    (wait)
    (text #:color 5 "【一哉】なあ、そろそろ俺達とも遊ぼうぜ・・・みんな" 0 "がいないと、つまらないって言うんだ。")
    (wait)
    (text #:color 7 "【" 0 "】夏休みに入る前に言っただろ？・・・俺はこの夏休みを、女性の為だけに捧げるって。")
    (wait)
    (text #:color 5 "【一哉】ちぇっ、わかったよ・・・冷たいよなあ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "47.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】すまん一哉・・・今年の夏は、何かが起こる予感がするんだ。")
    (wait)
    (set-reg: 366 1)))
  ((&& (== (: 367) 0) (== (: 362) 1) (> T 1000) (< T 1800) (== (: 685) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "a.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "aan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "a.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 3 "【美沙】" 0 "、この家に引越したのか？")
    (wait)
    (text #:color 7 "【" 0 "】び、びっくりしたあ・・・イントロもなく、いきなり話しかけるなよ。")
    (wait)
    (text #:color 3 "【美沙】悪い、悪い・・・" 0 "がそんなにデリケートだとは、知らなかったぜ。")
    (wait)
    (text #:color 7 "【" 0 "】陸上競技用のシューズ・・・どうなった？")
    (wait)
    (text #:color 3 "【美沙】え？・・・ああ、いいのが見つかったよ。")
    (wait)
    (text #:color 7 "【" 0 "】ふーん。")
    (wait)
    (text #:color 3 "【美沙】" 0 "さあ・・・私のシューズの事、覚えててくれたんだな。")
    (wait)
    (text #:color 7 "【" 0 "】へ？・・・何の話？")
    (wait)
    (text #:color 3 "【美沙】ちぇっ、もういいや・・・じゃあな、" 0 "。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "47.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】おー、早い、早い・・・さすが陸上部だぜ。")
    (wait)
    (set-reg: 367 1)))
  ((&& (== (: 455) 0) (== (: 324) 1) (> T 1000) (< T 2300) (> H 817))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【太郎】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】おい。")
    (wait)
    (text #:color 5 "【太郎】おいとは何だ、君は挨拶もできないのか？")
    (wait)
    (text #:color 7 "【" 0 "】ここで何をしてるんだよ。")
    (wait)
    (text #:color 5 "【太郎】何もしてない・・・いや、何も手につかないんだ。")
    (wait)
    (text #:color 7 "【" 0 "】マタロウよ、そのまま悩み続けてると、そのうちノイローゼになっちまうぜ。")
    (wait)
    (text
     #:color
     5
     "【太郎】僕はノイローゼになんかならない・・・あれだけ勉強をやってノイローゼにならなかった僕が、女の事なんかでなる訳がない。")
    (wait)
    (text #:color 7 "【" 0 "】勉強は自分一人の問題だろ？・・恋愛は違うぜ、だから悩むんだ。")
    (wait)
    (text #:color 5 "【太郎】君と話してても、時間の無駄のようだ・・・僕は失礼する。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "47.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】頑固なやつだぜ・・・もっと自分に素直になればいいのに。")
    (wait)
    (set-reg: 455 1)))
  ((&& (== (: 481) 1) (> H 817) (> T 800) (< T 1900) (== (: 509) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "q.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "qan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "q.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれ・・・くるみちゃん。")
    (wait)
    (text #:color 6 "【くるみ】" 0 "さん、こんにちは。")
    (wait)
    (text #:color 7 "【" 0 "】この家に何か用？・・・まさか、くるみちゃんの親戚とか？")
    (wait)
    (text #:color 6 "【くるみ】ううん、全然違う・・・一哉君の家に行って、留守だったから帰ろうと思ったの。")
    (wait)
    (text #:color 6 "【くるみ】でも・・・何となく、真っ直ぐ帰る気がしないの。")
    (wait)
    (text #:color 7 "【" 0 "】じゃあ、俺様とデートしようか。")
    (wait)
    (text #:color 6 "【くるみ】ううん・・・やっぱりお家に帰る・・・じゃあ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "47.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】くるみちゃんは・・・スカートをなびかせて行ってしまった。")
    (wait)
    (set-reg: 509 1)))
  ((&&
    (== (: 723) 1)
    (> H 825)
    (> T 800)
    (< T 2000)
    (== (: 725) 0)
    (== (: 728) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "f.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 27)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれ・・・。")
    (wait)
    (text #:color 6 "【美穂】" 0 "君・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ここで・・・何をしてるの？")
    (wait)
    (text #:color 6 "【美穂】" 0 "君が住んでるマンションって・・・この近くだよね？")
    (wait)
    (text #:color 7 "【" 0 "】そうだよ・・・ほら、この反対側のマンション。")
    (wait)
    (text #:color 6 "【美穂】うん・・・。")
    (wait)
    (text #:color 7 "【" 0 "】もしかして、俺に会いに来たとか？")
    (wait)
    (text #:color 6 "【美穂】だって・・・" 0 "君、手紙くれないし。")
    (wait)
    (text #:color 7 "【" 0 "】だからあ、俺は手紙を書くのが嫌いなんだって。")
    (wait)
    (text #:color 6 "【美穂】でも・・・。")
    (wait)
    (text #:color 7 "【" 0 "】美穂ちゃん、俺の返事はね・・・")
    (wait)
    (text #:color 6 "【美穂】だめえ・・・やっぱり手紙じゃなきゃいやあ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "47.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】なんか・・・俺と美穂ちゃんって、電車の線路のような関係だな。")
    (wait)
    (text #:color 7 "【" 0 "】決して交わる事がない、なんちゃって・・・ははは。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】笑ってる場合じゃないな・・・。")
    (wait)
    (set-reg: 725 1)))
  ((&&
    (== (: 730) 1)
    (> H 824)
    (> T 800)
    (< T 2200)
    (== (: 711) 0)
    (== (: 852) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【太郎】" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】どひゃーーっ！！")
    (wait)
    (text #:color 5 "【太郎】重ねてくどいようだが・・・一つ聞きたい事があるんだ。")
    (wait)
    (set-reg: 101 1)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<> (text "どっちでもいい")))
    (if (== N 1)
      (<>
       (text #:color 7 "【" 0 "】ふう・・・どっちでもいいよ。")
       (wait)
       (text #:color 5 "【太郎】なんた、その投げやりな態度は・・・失礼だぞ。")
       (wait)
       (text #:color 7 "【" 0 "】あのなあ、マタロウが聞きたい聞きたいって言って・・・結局何も聞かないからだよ。")
       (wait)))
    (text #:color 5 "【太郎】今度こそ、聞くぞ・・・聞いてやるぞ。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 5 "【太郎】ああ、でも・・・" 0 "君がもし・・・そうなら・・・僕はどうしたらいいのだろう。")
    (wait)
    (text #:color 7 "【" 0 "】一人でぶつぶつ言うなよ。")
    (wait)
    (text #:color 5 "【太郎】" 0 "君、今日はお日柄が悪い・・・また今度にしよう。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "47.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あいつ・・・俺に何を聞こうとしてるんだ？")
    (wait)
    (set-reg: 852 1)))
  ((&& (== (: 153) 1) (== (: 280) 0))
   (<>
    (text #:color 7 "【" 0 "】俺はこの家に住んでいる人と、一度も会った事がない。")
    (wait)
    (text #:color 7 "【" 0 "】まさか、空き家って事はないだろうな？")
    (wait)))
  ((&& (== (: 280) 1) (== (: 554) 0))
   (<> (text #:color 7 "【" 0 "】あの和服姿の女性を見て以来・・・何となくこの家の事が気になるなあ。") (wait)))
  ((== (: 554) 1) (<> (text #:color 7 "【" 0 "】ここは麗子さんの家だ・・・。") (wait))))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "他の場所に行く") (text "中に入る") (text "やめる")))
      (cond
       ((&& (== N 1) (== (: 280) 0))
        (<>
         (text #:color 7 "【" 0 "】そうだよな・・・知り合いの家って訳じゃないし、ここにいても仕方がないな。")
         (wait)
         (set-var N 3)
         (set-reg: 153 1)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 1) (== (: 280) 1) (== (: 554) 0))
        (<>
         (text #:color 7 "【" 0 "】ここにいても、家の中に入れる訳じゃないし・・・他の場所に行こうぜ。")
         (wait)
         (set-var N 3)
         (set-reg: 153 1)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 1) (== (: 554) 1))
        (<>
         (text #:color 7 "【" 0 "】他の場所に行くのか？")
         (wait)
         (set-var N 3)
         (set-reg: 153 1)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 2) (> T 2300))
        (<> (text #:color 7 "【" 0 "】こんなに遅いんだぜ・・・泥棒と間違われちゃうよ。") (wait)))
       ((&& (== N 2) (< T 600))
        (<>
         (text #:color 7 "【" 0 "】はっはっはっ・・・俺がモーニングチャイムをしてあげよう。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】やめた。")
         (wait)))
       ((&& (== N 2) (== (: 554) 0))
        (<> (text #:color 7 "【" 0 "】中に入るって・・・ここは俺の家じゃないぜ。") (wait)))
       ((&& (== N 2) (== (: 554) 1) (== (: 558) 0))
        (<>
         (text #:color 7 "【" 0 "】よーし、チャイムを押して・・・。")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 2 "【麗子】はい・・・どちら様ですか？")
         (wait)
         (text #:color 7 "【" 0 "】" 0 "でーす！！")
         (wait)
         (slot 1 7)
         (mes-jump "reiko4.mes")))
       ((&& (== N 2) (== (: 558) 1) (== (: 559) 0))
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】麗子さんは忘れろと言ったが・・・あの寂しそうな瞳が頭から離れない。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】チャイムを押しちゃえ。")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 2 "【麗子】はい・・・どちら様ですか？")
         (wait)
         (text #:color 7 "【" 0 "】" 0 "・・・だけど。")
         (wait)
         (text #:color 2 "【麗子】・・・。")
         (wait)
         (text #:color 2 "【麗子】どうぞ・・・中にお入りになって。")
         (wait)
         (slot 1 7)
         (mes-jump "d01h.mes")))
       ((&& (== N 2) (== (: 559) 1))
        (<>
         (text #:color 7 "【" 0 "】またまた中に入るのか？")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 2 "【麗子】はい・・・。")
         (wait)
         (text #:color 7 "【" 0 "】" 0 "だけど・・・。")
         (wait)
         (text #:color 2 "【麗子】" 0 "さん・・・。")
         (wait)
         (text #:color 2 "【麗子】・・・。")
         (wait)
         (text #:color 2 "【麗子】どうぞ・・・ドアは開いてます、中にお入りになって。")
         (wait)
         (slot 1 7)
         (mes-jump "d01h.mes")))
       ((&& (== N 2) (== (: 554) 1) (== (: 45) 0))
        (<>
         (text #:color 7 "【" 0 "】麗子さんはいるかな？")
         (wait)
         (sound 1)
         (set-var I 5)
         (proc 26)
         (text #:color 6 "ピンポーン！！")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】いないようだ・・・ちっ。")
         (wait)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)
         (set-reg: 45 1)))
       ((&& (== N 2) (== (: 554) 1) (== (: 45) 1))
        (<> (text #:color 7 "【" 0 "】さっきチャイムを押したばかりだ・・・よそうぜ。") (wait)))
       ((== N 3) (<> (text #:color 7 "【" 0 "】え！？・・・まだここにいるつもりか？") (wait)))
       (else (<>)))))
    ((&& (== V 5) (== N 1) (== (: 10) 0))
     (<> (text #:color 7 "【" 0 "】開かないな・・・鍵が閉まっている。") (wait) (set-reg: 10 1)))
    ((&& (== V 5) (== N 1) (== (: 10) 1))
     (<>
      (text #:color 7 "【" 0 "】だから開かないぜ・・・乗り越えて入るか？")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】そんな事をしたら、本当の泥棒だ。")
      (wait)))
    ((&& (== V 1) (== N 2) (== (: 184) 0))
     (<>
      (text #:color 7 "【" 0 "】表札には『真行司』と書かれている・・・ずいぶんと偉そうな名字だな。")
      (wait)
      (set-reg: 184 1)))
    ((&& (== V 1) (== N 2) (== (: 184) 1) (== (: 280) 0))
     (<>
      (text #:color 7 "【" 0 "】だから、表札には『真行司』と書かれているぞ・・・いったいどんな人が住んでいるんだろう？")
      (wait)))
    ((&& (== V 1) (== N 2) (== (: 280) 1) (== (: 554) 0))
     (<> (text #:color 7 "【" 0 "】あの女性が『真行司さん』なのか？") (wait)))
    ((&& (== V 1) (== N 2) (== (: 554) 1))
     (<> (text #:color 7 "【" 0 "】ここに住んでいる人・・・『真行司　麗子』さんだ。") (wait)))
    ((&& (== V 1) (== N 3) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】石造りの門柱と、アルミの柵で囲まれている・・・よくあるパターンだな。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 1) (== N 3) (== (: 11) 1))
     (<> (text #:color 7 "【" 0 "】何度も見るほどの物じゃないだろう・・・ただの塀だ。") (wait)))
    ((&& (== V 1) (== N 4) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】ずいぶんと大きな木だな・・・この家自体は、そんなに古く見えないが。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 4) (== (: 12) 1))
     (<>
      (text #:color 7 "【" 0 "】木だ・・・子供の頃、こんな木に登ったものだぜ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】そうそう、好きな女の子と一緒に登って・・・木の上でお医者さんごっこをしたんだ・・・懐かしいなあ。")
      (wait)))
    ((&& (== V 1) (== N 5) (== (: 13) 0))
     (<> (text #:color 7 "【" 0 "】窓だな・・・ピッチリと閉まっている。") (wait) (set-reg: 13 1)))
    ((&& (== V 1) (== N 5) (== (: 13) 1) (== (: 280) 0))
     (<> (text #:color 7 "【" 0 "】人影は見えないが・・・空き家なのかな？") (wait)))
    ((&& (== V 1) (== N 5) (== (: 280) 1) (== (: 554) 0))
     (<>
      (text #:color 7 "【" 0 "】人影は見えない・・・俺が見た女性は掃除のおばさんで、この家にはやっぱり誰も住んでないとか？")
      (wait)))
    ((&& (== V 1) (== N 5) (== (: 554) 1))
     (<> (text #:color 7 "【" 0 "】麗子さんは・・・出かけているのかな？") (wait)))
    ((&& (== V 1) (== N 7) (> T 1800) (== (: 554) 0))
     (<>
      (text #:color 7 "【" 0 "】照明だな・・・明りはついているぞ。")
      (wait)
      (text #:color 7 "【" 0 "】と、言う事は・・・誰かが住んでいるって事だ。")
      (wait)
      (if-else (== (: 280) 1)
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】あの和服姿の女性が住んでるのかな・・・？")
         (wait))
        (<>))))
    ((&& (== V 1) (== N 7) (== (: 554) 0))
     (<> (text #:color 7 "【" 0 "】照明はついていない・・・。") (wait)))
    ((&& (== V 1) (== N 7)) (<> (text #:color 7 "【" 0 "】照明だよ・・・ちっ！！") (wait)))
    ((&& (== V 1) (== N 8) (== (: 14) 0))
     (<> (text #:color 7 "【" 0 "】ドアだな・・・当然閉まっているぞ。") (wait) (set-reg: 12 1)))
    ((&& (== V 1) (== N 8) (== (: 14) 1) (== (: 554) 0))
     (<>
      (text #:color 7 "【" 0 "】ここからではノックする事もできない・・・用がある訳じゃないから、どうでもいい事だが。")
      (wait)))
    ((&& (== V 1) (== N 8) (== (: 554) 1))
     (<>
      (text #:color 7 "【" 0 "】麗子さんのドアだ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ちょっと言い方がおかしかったような気がする。")
      (wait)))
    ((&& (== V 1) (== N 9) (== (: 15) 0) (== (: 554) 0))
     (<>
      (text #:color 7 "【" 0 "】なんだか・・・ポツンと植え込みがあるな。")
      (wait)
      (text #:color 7 "【" 0 "】寂しそうな雰囲気だ・・・ここに住んでいる人も、寂しい人なのかな？")
      (wait)
      (if-else (== (: 280) 1)
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text
          #:color
          7
          "【"
          0
          "】確かに雰囲気は寂しそうだったぜ・・・挨拶をした時、微笑んでいたようだけど、どことなく寂しげな微笑みだった。")
         (wait))
        (<>))
      (set-reg: 15 1)))
    ((&& (== V 1) (== N 9) (== (: 15) 1) (== (: 554) 0))
     (<> (text #:color 7 "【" 0 "】寂しげな植え込みだ・・・考えすぎか？") (wait)))
    ((&& (== V 1) (== N 9) (== (: 554) 1))
     (<> (text #:color 7 "【" 0 "】この植え込みも・・・麗子さんが手入れをしてるのかな？") (wait)))
    ((&& (== V 1) (== N 10) (== (: 16) 0) (== (: 554) 0))
     (<>
      (text #:color 7 "【" 0 "】俺の部屋の窓を開けると、この家の庭が見えるんだ。")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 1) (== N 10) (== (: 16) 1) (== (: 280) 0) (== (: 554) 0))
     (<> (text #:color 7 "【" 0 "】誰も住んでいないのなら、俺が住んでやってもいいぞ。") (wait)))
    ((&& (== V 1) (== N 10) (== (: 280) 1) (== (: 554) 0))
     (<>
      (text #:color 7 "【" 0 "】こんな大きな家に、あの和服姿の女性が一人暮し・・・ちょっと考えにくいぜ。")
      (wait)))
    ((&& (== V 1) (== N 10) (== (: 554) 1))
     (<> (text #:color 7 "【" 0 "】この家には、麗子さんが一人で住んでいる・・・寂しいだろうなあ。") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))