(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\一
  #\哉
  #\。
  #\な
  #\あ
  #\？
  #\だ
  #\い
  #\か
  #\ん
  #\っ
  #\が
  #\何
  #\る
  #\、
  #\て
  #\え
  #\う
  #\ゃ
  #\よ
  #\に
  #\た
  #\し
  #\く
  #\じ
  #\こ
  #\ど
  #\の
  #\行
  #\や
  #\は
  #\さ)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "27.pd8")
 (proc 15)
 (set-arr~ @ 6 1)
 (image "m11.pd8")
 (proc 16)
 (set-arr~ @ 6 1)
 (image "i.pd8")
 (proc 16)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "ran.pd8")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 0)
 (load "r.s4" (~ @ 2))
 (animate 0 0 1)
 (animate 1 0)
 (set-arr~ @ 7 0)
 (sound 1)
 (set-var I 62)
 (proc 26)
 (set-reg: 835 0)
 (set-arr~ @ 7 0)
 (load "i.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (if (== (: 289) 0)
   (<>
    (text #:color 7 "【" 0 "】一哉じゃないかよ。")
    (wait)
    (if (> T 2000)
      (<>
       (text #:color 5 "【一哉】・・・。")
       (wait)
       (text #:color 7 "【" 0 "】おい・・・こんな時間に何してるんだ？")
       (wait)))
    (text #:color 5 "【一哉】え？・・・なんだ、" 0 "か。")
    (wait)
    (text #:color 7 "【" 0 "】何をボーーッとしてるんだ？")
    (wait)
    (text #:color 5 "【一哉】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】おい・・・どうしたんだ？")
    (wait)
    (text #:color 5 "【一哉】あ？・・・何か言ったか？")
    (wait)
    (text #:color 7 "【" 0 "】だめだ、こりゃ。")
    (wait)
    (set-reg: 289 1)))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "他の場所に行く") (text "電車に乗る") (text "やめる")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】一哉・・・俺は行くぜ。")
         (wait)
         (text #:color 5 "【一哉】え？・・・ああ。")
         (wait)
         (text #:color 7 "【" 0 "】変なやつだなあ。")
         (wait)
         (set-var N 2)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 2) (< M 300))
        (<>
         (text #:color 7 "【" 0 "】じゃあな、一哉・・・俺は矢吹町に行ってくるぜ。")
         (wait)
         (text #:color 5 "【一哉】え？・・・ああ、じゃあな。")
         (wait)
         (text #:color 7 "【" 0 "】と思ったけど、お金が足りないから・・・やっぱり行くのはやめよう。")
         (wait)))
       ((&& (== N 2) (> M 299))
        (<>
         (text #:color 7 "【" 0 "】じゃあな、一哉・・・俺は矢吹町に行ってくるぜ。")
         (wait)
         (text #:color 5 "【一哉】え？・・・ああ、じゃあな。")
         (wait)
         (text #:color 7 "【" 0 "】変なやつだな・・・。")
         (wait)
         (set-var A 30)
         (proc 12)
         (set-var M (- M 300))
         (proc 11)
         (set-var N 0)
         (mes-call "den.mes")
         (slot 1 3)
         (mes-jump "yabuki.mes")))
       ((== N 3)
        (<>
         (text #:color 7 "【" 0 "】なあ・・・。")
         (wait)
         (text #:color 5 "【一哉】・・・え？")
         (wait)
         (text #:color 7 "【" 0 "】おい・・・。")
         (wait)
         (text #:color 5 "【一哉】はあ？")
         (wait)
         (text #:color 7 "【" 0 "】これでもまだ、ここにいるのか？")
         (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 2))
     (<>
      (text #:color 7 "【" 0 "】なあ・・・髪の事だけどさ。")
      (wait)
      (text #:color 5 "【一哉】・・・。")
      (wait)
      (text #:color 5 "【一哉】・・・。")
      (wait)
      (text #:color 5 "【一哉】・・・え？")
      (wait)))
    ((&& (== V 1) (== N 3))
     (<>
      (text #:color 7 "【" 0 "】一哉の顔ってさあ・・・。")
      (wait)
      (text #:color 5 "【一哉】・・・。")
      (wait)
      (text #:color 5 "【一哉】何か言ったか？")
      (wait)))
    ((&& (== V 1) (== N 4))
     (<>
      (text #:color 7 "【" 0 "】シャツがさあ・・・。")
      (wait)
      (text #:color 5 "【一哉】・・・。")
      (wait)
      (text #:color 5 "【一哉】まったくだよなあ。")
      (wait)
      (text #:color 7 "【" 0 "】何が？")
      (wait)
      (text #:color 5 "【一哉】何？")
      (wait)))
    ((&& (== V 1) (== N 5))
     (<>
      (text #:color 7 "【" 0 "】ネクタイがさあ・・・聞いてる？")
      (wait)
      (text #:color 5 "【一哉】ああ・・・どうしようもないな。")
      (wait)
      (text #:color 7 "【" 0 "】何が？")
      (wait)
      (text #:color 5 "【一哉】だから・・・何だっけ？")
      (wait)))
    ((&& (== V 1) (== N 6))
     (<>
      (text #:color 7 "【" 0 "】制服が・・・ね？")
      (wait)
      (text #:color 5 "【一哉】ああ・・・困っちゃうよなあ。")
      (wait)
      (text #:color 7 "【" 0 "】何が？")
      (wait)
      (text #:color 5 "【一哉】・・・。")
      (wait)
      (text #:color 5 "【一哉】・・・え？")
      (wait)))
    ((&& (== V 2) (== N 1) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】一哉よう・・・なんだか変だぜ。")
      (wait)
      (text #:color 5 "【一哉】ああ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】どうしたんだ？")
      (wait)
      (text #:color 5 "【一哉】別に・・・なんでもないさ。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 2) (== N 1) (== (: 11) 1))
     (<>
      (text #:color 7 "【" 0 "】ボーッとしてるな・・・。")
      (wait)
      (text #:color 5 "【一哉】仕方がないよなあ・・・うん。")
      (wait)
      (text #:color 7 "【" 0 "】何が仕方がないんだ？")
      (wait)
      (text #:color 5 "【一哉】・・・。")
      (wait)
      (text #:color 5 "【一哉】え？・・・俺、仕方がないなんて言ったか？")
      (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))