(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\い
  #\。
  #\な
  #\て
  #\っ
  #\だ
  #\、
  #\か
  #\う
  #\ん
  #\の
  #\あ
  #\に
  #\は
  #\る
  #\し
  #\と
  #\た
  #\ら
  #\さ
  #\が
  #\？
  #\も
  #\ゃ
  #\ま
  #\よ
  #\れ
  #\で
  #\！
  #\そ
  #\子
  #\り
  #\ち
  #\こ
  #\を
  #\ー
  #\み
  #\く
  #\じ
  #\ふ
  #\俺
  #\す
  #\お
  #\ど
  #\麗
  #\一
  #\え
  #\や
  #\け
  #\ろ
  #\ね
  #\わ
  #\人
  #\ぜ
  #\駅
  #\事
  #\夏
  #\何
  #\つ
  #\言
  #\君
  #\ス
  #\行
  #\女
  #\き
  #\美
  #\ン
  #\ば
  #\哉
  #\店
  #\間
  #\健
  #\今
  #\時
  #\物
  #\二
  #\ょ
  #\め
  #\思
  #\ぞ
  #\出
  #\ル
  #\車
  #\茶
  #\せ
  #\げ
  #\歩
  #\達
  #\電
  #\乗
  #\度
  #\買
  #\気
  #\『
  #\』
  #\穂
  #\前
  #\来
  #\ご
  #\荷
  #\用
  #\最
  #\マ
  #\年
  #\ト
  #\場
  #\所
  #\遅
  #\話
  #\戻
  #\緒
  #\奇
  #\重
  #\ほ
  #\ラ
  #\沙
  #\ツ
  #\友
  #\後
  #\休
  #\タ
  #\太
  #\郎
  #\分
  #\プ)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "27.pd8")
 (proc 15)
 (if (&& (< T 2359) (> T 659))
   (<>
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)))
 (set-arr~ @ 7 0)
 (load "27a.a6" 47104)
 (if (&& (> T 0) (< T 700)) (<> (load "27.a6" 47104)))
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (cond
  ((&& (== (: 151) 0) (== H 810) (< T 1050))
   (<>
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】駅前で待っていると言ったけど・・・一哉はまだ来てないようだな。")
    (wait)))
  ((&& (== (: 151) 0) (== H 810) (> T 1130) (< T 1300))
   (<>
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】一哉はいない・・・ちょっと来るのが遅かったか？")
    (wait)))
  ((&& (== (: 405) 1) (== (: 425) 0) (> H 825))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "o.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "oan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "o.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 18)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 2 "【ひろみ】あ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】またまた走って行ってしまった・・・彼女は俺と話す事すら避けてるようだ。")
    (wait)
    (set-reg: 425 1)))
  ((&& (== (: 361) 0) (== (: 151) 1) (> T 1000) (< T 1800) (== (: 480) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "jan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれれ！？・・・夏子さん！！")
    (wait)
    (text #:color 2 "【夏子】" 0 "君、こんにちは・・・暑いわね。")
    (wait)
    (text #:color 7 "【" 0 "】お店は？")
    (wait)
    (text #:color 2 "【夏子】ええ、ちょっとだけ閉めて・・・またすぐに戻るけど。")
    (wait)
    (text #:color 7 "【" 0 "】ここで会ったのも何かの縁だし・・・お茶でも飲もうよ。")
    (wait)
    (text #:color 2 "【夏子】ふふふ、ごめんね・・・ゆっくりしてられないの。")
    (wait)
    (text #:color 2 "【夏子】今度時間があったら、一緒にお茶しましょ？・・・またお店に遊びに来てね。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ちぇっ・・・。")
    (wait)
    (set-reg: 361 1)))
  ((&& (== (: 361) 0) (== (: 151) 0) (> T 1000) (< T 1800) (> H 810))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "jan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】！？")
    (wait)
    (text #:color 2 "【女の人】・・・何か？")
    (wait)
    (text #:color 7 "【" 0 "】い、いや・・・奇麗な人だなって思って。")
    (wait)
    (text #:color 2 "【女の人】ありがとう。")
    (wait)
    (text #:color 7 "【" 0 "】ここで会ったのも何かの縁だし・・・お茶でも飲みませんか？")
    (wait)
    (text #:color 2 "【女の人】ふふふ、ごめんね・・・ゆっくりしてられないの。")
    (wait)
    (text #:color 2 "【女の人】今度時間があったら、一緒にお茶しましょ？・・・じゃあね、かわいいボウヤ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ボウヤだって・・・子供扱いされてしまったぞ。")
    (wait)
    (set-reg: 361 1)))
  ((&&
    (== (: 554) 1)
    (== (: 555) 0)
    (> H 816)
    (> T 800)
    (< T 1800)
    (== (: 556) 0))
   (<>
    (slot 1 7)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "d02.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "d02an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "d02.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 38)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれ・・・麗子さん。")
    (wait)
    (text #:color 2 "【麗子】" 0 "さん・・・こんにちは。")
    (wait)
    (text #:color 7 "【" 0 "】ずいぶんと、たくさんの荷物だなあ。")
    (wait)
    (text #:color 2 "【麗子】あまり外に出ませんから・・・どうしても、一度にたくさん買ってしまいますの。")
    (wait)
    (text #:color 7 "【" 0 "】（あらら・・・ひたいに汗をかいちゃて。）")
    (wait)
    (text #:color 2 "【麗子】ふうふう・・・今日も暑いですね。")
    (wait)
    (text #:color 7 "【" 0 "】あの・・・。")
    (wait)
    (set-reg: 101 1)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "手伝う") (text "逃げる")))
    (if (== N 1)
      (<>
       (text #:color 2 "【麗子】何か？")
       (wait)
       (text #:color 7 "【" 0 "】俺、荷物を持ってあげるよ・・・なんだか重そうだし。")
       (wait)
       (text #:color 2 "【麗子】" 0 "さん・・・平気ですから。")
       (wait)
       (text #:color 7 "【" 0 "】いいからさ、ほら・・・荷物をちょうだい。")
       (wait)
       (text #:color 2 "【麗子】ありがとう・・・じゃあ、お言葉に甘えて。")
       (wait)
       (text #:color 7 "【" 0 "】麗子さんの家までだろ？")
       (wait)
       (text #:color 2 "【麗子】ええ・・・お願いします。")
       (wait)
       (set-reg: 115 (+ (: 115) 1))
       (set-reg: 555 1)
       (set-reg: 557 1)
       (set-reg: 556 1)
       (set-var N 2)
       (slot 1 2)
       (mes-jump "town1.mes")))
    (if (== N 2)
      (<>
       (text #:color 7 "【" 0 "】あ・・・俺、急用があったんだ。")
       (wait)
       (text #:color 2 "【麗子】そうですか・・・それでは、ごきげんよう。")
       (wait)))
    (slot 1 2)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あらら・・・フラフラ歩いてるよ、よっぽど重い荷物なんだな。")
    (wait)
    (set-reg: 115 (- (: 115) 1))
    (set-reg: 556 1)))
  ((&&
    (== (: 554) 1)
    (== (: 555) 0)
    (> H 816)
    (> T 800)
    (< T 1800)
    (== (: 556) 1))
   (<>
    (slot 1 7)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "d02.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "d02an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "d02.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 38)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ありゃりゃりゃりゃ！？")
    (wait)
    (text #:color 2 "【麗子】ふうふうふう・・・" 0 "さん、こんにちは。")
    (wait)
    (text #:color 7 "【" 0 "】（うーん、ほとんどギャグだぜ。）")
    (wait)
    (text #:color 2 "【麗子】あまり外に出ませんから・・・どうしても、一度にたくさん買ってしまいますの。")
    (wait)
    (text #:color 7 "【" 0 "】（あまり外に出ないって・・・何度も出てるじゃないかよう。）")
    (wait)
    (text #:color 2 "【麗子】ふうふうふうふうふう・・・暑いわあ、重いわあ。")
    (wait)
    (text #:color 7 "【" 0 "】あの・・・。")
    (wait)
    (set-reg: 101 1)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "手伝う") (text "逃げる")))
    (if (== N 1)
      (<>
       (text #:color 2 "【麗子】何か？")
       (wait)
       (text #:color 7 "【" 0 "】俺、荷物を持ってあげるよ・・・なんだか重そうだし。")
       (wait)
       (text #:color 2 "【麗子】" 0 "さん・・・平気ですから。")
       (wait)
       (text #:color 7 "【" 0 "】いいからさ、ほら・・・荷物をちょうだい。")
       (wait)
       (text #:color 2 "【麗子】ありがとう・・・じゃあ、お言葉に甘えて。")
       (wait)
       (text #:color 7 "【" 0 "】麗子さんの家までだろ？")
       (wait)
       (text #:color 2 "【麗子】ええ・・・お願いします。")
       (wait)
       (set-reg: 115 (+ (: 115) 1))
       (set-reg: 555 1)
       (set-reg: 557 1)
       (set-var N 2)
       (slot 1 2)
       (mes-jump "town1.mes")))
    (if (== N 2)
      (<>
       (text #:color 7 "【" 0 "】あ・・・俺、急用があったんだ。")
       (wait)
       (text #:color 2 "【麗子】そうですか・・・それでは、ごきげんよう。")
       (wait)
       (text #:color 2 "【麗子】重いわあ・・・ふうふうふうふう。")
       (wait)))
    (slot 1 2)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】うーん、前に会ったのは夢で・・・今のが現実だったのかな？")
    (wait)
    (set-reg: 115 (- (: 115) 1))))
  ((&& (== (: 362) 0) (== (: 233) 1) (> T 800) (< T 1800) (== (: 685) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "a.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "aan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "a.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (text #:color 3 "【美沙】何か『あ』なんだよ。")
    (wait)
    (text #:color 7 "【" 0 "】美沙、俺にケンカ売ってるのか？")
    (wait)
    (text #:color 3 "【美沙】売ってないで思い出した・・・売ってないんだよ、困っちゃってさ。")
    (wait)
    (text #:color 7 "【" 0 "】何が？")
    (wait)
    (text #:color 3 "【美沙】大会で使う陸上競技用の靴の話さ・・・気に入ったのがなくて困ってるんだ。")
    (wait)
    (text #:color 7 "【" 0 "】俺の靴を貸してやろうか？")
    (wait)
    (text #:color 3 "【美沙】水虫をうつされたくないからな・・・じゃあな、" 0 "。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】俺は・・・水虫じゃないぞ。")
    (wait)
    (set-reg: 362 1)))
  ((&& (== (: 363) 0) (== (: 182) 1) (> T 1000) (< T 1900) (== (: 412) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【さとみ】" 0 "・・・カツアゲでもしてるの？")
    (wait)
    (text #:color 7 "【" 0 "】あーあ、どうして俺の友達には口の悪いヤツが多いんだろう。")
    (wait)
    (text #:color 6 "【さとみ】顔が悪いのよりいいと思うけど・・・。")
    (wait)
    (text #:color 7 "【" 0 "】へいへい、さとみはかわいいよな、あー、かわいい。")
    (wait)
    (text #:color 6 "【さとみ】一哉と博司と幸治が店に来て・・・" 0 "が俺達と一緒に遊んでくれないってボヤいてたわよ。")
    (wait)
    (text #:color 7 "【" 0 "】最後の夏休みだぜ、男と一緒に過ごしてたまるか。")
    (wait)
    (text #:color 6 "【さとみ】まあ、せいぜいがんばって・・・私はミルクを買いに行かなきゃ、マスターったら人使いが荒いわよね。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】今年の夏休みは、女の子の事だけに集中するって決めたのさ・・・最後の夏休みだもんな。")
    (wait)
    (set-reg: 363 1)))
  ((&& (== (: 364) 0) (== (: 183) 1) (> T 700) (< T 1900) (< H 817))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "o.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "oan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "o.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 18)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 2 "【ひろみ】" 0 "君っ！！")
    (wait)
    (text #:color 7 "【" 0 "】・・・ん？")
    (wait)
    (text #:color 2 "【ひろみ】あーっ！！電車に乗り遅れちゃうっ！！・・・じゃあね！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】な、なんだよ・・・今のは。")
    (wait)
    (set-reg: 364 1)))
  ((&& (== (: 365) 0) (== (: 219) 1) (> T 700) (< T 2300))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【太郎】友よ。")
    (wait)
    (text #:color 7 "【" 0 "】帰ろう。")
    (wait)
    (text #:color 5 "【太郎】君はどうして僕から逃げるんだ？")
    (wait)
    (text #:color 7 "【" 0 "】帰ろう。")
    (wait)
    (text #:color 5 "【太郎】確かに君は人気がある・・・友達も多い。")
    (wait)
    (text #:color 5 "【太郎】それに比べ僕は、友達といえば君だけだ・・・もう少し大事にしてくれてもいいんじゃないか？")
    (wait)
    (text #:color 7 "【" 0 "】まいったな・・・。")
    (wait)
    (text #:color 5 "【太郎】いや、僕の友達は勉強だったな・・・家に帰ろう。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あいつ・・・分裂症なんじゃないか？")
    (wait)
    (set-reg: 365 1)))
  ((&& (== (: 360) 0) (== (: 170) 1) (== (: 324) 0) (> T 800) (< T 1800))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "f.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 27)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【美穂】" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・美穂ちゃん。")
    (wait)
    (text #:color 6 "【美穂】遊びに行くの？")
    (wait)
    (text #:color 7 "【" 0 "】うん、美穂ちゃんと一緒にね。")
    (wait)
    (text #:color 6 "【美穂】今日はだめ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】どうして？")
    (wait)
    (if (&& (> H 813) (< T 817))
      (<> (text #:color 6 "【美穂】どうしても・・・じゃあね、" 0 "君。") (wait)))
    (if (< T 814)
      (<> (text #:color 6 "【美穂】だって、これから花屋さんに戻らないと・・・じゃあね。") (wait)))
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】うーん、もっとプッシュすればよかったかな？")
    (wait)
    (set-reg: 360 1)))
  ((&& (== (: 419) 1) (== (: 428) 0) (> T 1000) (< T 1900) (> H 823))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【さとみ】あ・・・" 0 "じゃない。")
    (wait)
    (text #:color 7 "【" 0 "】さとみ、喫茶店の買物か？")
    (wait)
    (text #:color 6 "【さとみ】うん、またミルクを切らしちゃったの・・・急いで買いに行かないとね。")
    (wait)
    (text #:color 7 "【" 0 "】さとみって・・・喫茶店の仕事をしてる時が、一番生き生きしてないか？")
    (wait)
    (text #:color 6 "【さとみ】だって、私の夢は自分の喫茶店をやる事ですもの・・・その時は開店祝いをちょうだいね。")
    (wait)
    (text #:color 6 "【さとみ】あ、いけない・・・早く戻らないとマスターに怒られちゃう。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】自分の喫茶店をやる・・・か。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】俺は・・・何をしたいんだろ？")
    (wait)
    (set-reg: 428 1)))
  ((&& (== (: 753) 1) (> H 826) (> T 800) (< T 2000) (== (: 756) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "v.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "van.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "v.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 24)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 3 "【舞】あ・・・" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】舞ちゃん・・・あやまっても許してくれないかもしれないけど。")
    (wait)
    (text #:color 3 "【舞】" 0 "君・・・もう遅いわ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ふう・・・だめだこりゃ。")
    (wait)
    (set-reg: 111 (- (: 111) 1))
    (set-reg: 756 1)))
  ((&& (== (: 419) 1) (== (: 433) 0) (> T 1000) (< T 1900) (> H 828))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【さとみ】" 0 "・・・何をしてるの？")
    (wait)
    (text #:color 7 "【" 0 "】ははは、俺に聞くな・・・足の向くまま歩いてるだけさ。")
    (wait)
    (text #:color 6 "【さとみ】それって、死ぬほど暇って事？")
    (wait)
    (text #:color 7 "【" 0 "】いや、暇かと聞かれれば暇じゃないし・・・忙しいのかと聞かれれば、暇だとも言えるし。")
    (wait)
    (text #:color 6 "【さとみ】？？？・・・" 0 "、自分で言ってる事がわかってる？")
    (wait)
    (text #:color 7 "【" 0 "】夏休みももう終りだろ？・・・最後の夏休みだから、ブラブラ歩きながら色々と考えてるのさ。")
    (wait)
    (text #:color 6 "【さとみ】来年の３月で・・・卒業ね。")
    (wait)
    (text #:color 7 "【" 0 "】ああ・・・３年間なんてあっという間だった。")
    (wait)
    (text #:color 6 "【さとみ】卒業しても、『ＯＴＩＭＴＩＭ』に顔を出してね・・・私、あそこでお店をまかせてもらえる事になったの。")
    (wait)
    (text #:color 7 "【" 0 "】へえ・・・よかったじゃないか。")
    (wait)
    (text #:color 6 "【さとみ】あ、もうお店に戻らないと・・・じゃあね！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】そうか・・・さとみは『ＯＴＩＭＴＩＭ』の女マスターか。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】俺は来年・・・何をしてるんだ？")
    (wait)
    (set-reg: 433 1)))
  ((&& (== (: 444) 1) (== (: 445) 0) (> T 800) (< T 2359) (== (: 765) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "b.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "man.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】さてと、どこに行こうかな？")
    (wait)
    (text #:color 4 "【健二】" 0 "、僕を無視するなっ！！")
    (wait)
    (text #:color 7 "【" 0 "】それとも、自分のマンションに戻るかな。")
    (wait)
    (text #:color 4 "【健二】" 0 "っ！！")
    (wait)
    (text #:color 7 "【" 0 "】うーん・・・どうしようかなあ。")
    (wait)
    (text #:color 4 "【健二】" 0 "っ！！")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・健二、いつからそこにいたんだ？")
    (wait)
    (text #:color 4 "【健二】ふうふうふう。")
    (wait)
    (text #:color 7 "【" 0 "】なんだ、喋れないのか・・・かわいそうに。")
    (wait)
    (text #:color 4 "【健二】し、喋れるぞ・・・興奮して、目まいがしただけだ。")
    (wait)
    (text #:color 7 "【" 0 "】そうだ、最近睡眠不足だから・・・寝ちゃおうかな。")
    (wait)
    (text #:color 4 "【健二】" 0 "っ！！")
    (wait)
    (text #:color 7 "【" 0 "】やっぱり・・・何か食べてから寝るか。")
    (wait)
    (text #:color 4 "【健二】" 0 "っっ！！")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・健二じゃないか、いつからそこにいたんだ？")
    (wait)
    (text #:color 4 "【健二】ぜいぜいぜい・・・も、もういい。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】ははは・・・からかってやったぞ。")
    (wait)
    (set-reg: 445 1)))
  ((&& (== (: 467) 1) (== (: 842) 0) (> H 822) (> T 800) (< T 1900))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n.pd8")
    (proc 16)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 6)
    (proc 26)
    (text #:color 3 "【ちはる】あら・・・" 0 "君じゃない。")
    (wait)
    (text #:color 7 "【" 0 "】ちはる・・・ちゃん。")
    (wait)
    (text #:color 3 "【ちはる】やだ、またナンパしてるの？")
    (wait)
    (text #:color 7 "【" 0 "】違うってば、たまたま通りかかっただけだよ。")
    (wait)
    (text #:color 3 "【ちはる】ふーん・・・本当かしらねえ。")
    (wait)
    (text #:color 7 "【" 0 "】ちはるちゃんは何をしてるの？")
    (wait)
    (text #:color 3 "【ちはる】私ね、そろそろ仕事をしようかと思って・・・。")
    (wait)
    (text #:color 7 "【" 0 "】そうなんだ・・・プー子さんから脱出か。")
    (wait)
    (text #:color 3 "【ちはる】あ・・・面接の時間に遅れちゃう、じゃあね！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あらら・・・行っちゃたよ。")
    (wait)
    (set-reg: 842 1)))
  ((&& (== (: 479) 1) (== (: 842) 0) (> H 822) (> T 800) (< T 1900))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n.pd8")
    (proc 16)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 6)
    (proc 26)
    (text #:color 7 "【" 0 "】あ・・・ちはるちゃん。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あらら・・・走って行っちゃった。")
    (wait)
    (text #:color 7 "【" 0 "】うーん、もしかして嫌われたってやつか？")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】もしかしなくてもそうだろうな・・・。")
    (wait)
    (set-reg: 842 1)))
  ((&&
    (== (: 488) 1)
    (== (: 491) 0)
    (> T 800)
    (< T 1900)
    (== (: 497) 0)
    (== (: 539) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j11.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (text #:color 2 "【夏子】" 0 "君・・・こんにちは。")
    (wait)
    (text #:color 7 "【" 0 "】いやあ、いつも奇麗だなあ・・・夏子さんって。")
    (wait)
    (text #:color 2 "【夏子】" 0 "君も、いつも格好いいわよ。")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・さすが夏子さん、切り返すのがうまいや。")
    (wait)
    (text #:color 2 "【夏子】" 0 "君って、いつもそんな事ばかり言ってるんでしょ？")
    (wait)
    (text #:color 7 "【" 0 "】よく言われるなあ・・・そのセリフ。")
    (wait)
    (text #:color 2 "【夏子】って事は、そんな事ばかり言ってるって事よね・・・そのうち知らない人にでも言うようになっちゃうわよ。")
    (wait)
    (text #:color 7 "【" 0 "】（すでにそうだったりして・・・。）")
    (wait)
    (text #:color 2 "【夏子】じゃあね、" 0 "君・・・今度またお話をしましょ？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あーあ・・・夏子さんは行ってしまった。")
    (wait)
    (set-reg: 497 1)))
  ((&& (== (: 581) 1) (> H 821) (> T 800) (< T 2359) (== (: 583) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "e.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ean.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "e.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 22)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれ・・・かおりさん。")
    (wait)
    (text #:color 6 "【かおり】" 0 "君・・・首筋にキスマークがついてるわよ。")
    (wait)
    (text #:color 7 "【" 0 "】え！？")
    (wait)
    (text #:color 6 "【かおり】嘘よ、あはははっ！！")
    (wait)
    (text #:color 7 "【" 0 "】あのなあ・・・。")
    (wait)
    (text #:color 6 "【かおり】あ・・・いっけない、面接の時間に遅れちゃうっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あらららっ！？")
    (wait)
    (text #:color 7 "【" 0 "】なんだよ・・・あわただしいなあ。")
    (wait)
    (set-reg: 583 1)))
  ((&&
    (== (: 528) 1)
    (== (: 537) 0)
    (> H 827)
    (> T 800)
    (< T 2300)
    (== (: 527) 0)
    (== (: 532) 0)
    (== (: 533) 0))
   (<>
    (text #:color 7 "【" 0 "】ふう・・・先負駅だ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j12.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j11.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【一哉】" 0 "ーっ！！")
    (wait)
    (text #:color 7 "【" 0 "】な、なんだっ！？")
    (wait)
    (text #:color 5 "【一哉】俺だよ、一哉だ・・・そんなに驚く事はないじゃないか。")
    (wait)
    (text #:color 7 "【" 0 "】いきなり背後で大声を出されたら、誰だった驚くぞ・・・心臓が止まるかと思ったぜ。")
    (wait)
    (text #:color 5 "【一哉】" 0 "だったら平気だと思ってさ・・・ほら、お前って物事に動じないやつじゃないか。")
    (wait)
    (text #:color 7 "【" 0 "】俺はデリケートなんだよ・・・ところで、何か用か？")
    (wait)
    (text #:color 5 "【一哉】え？")
    (wait)
    (text #:color 7 "【" 0 "】呼び止めた以上は、何か用があるんだろ？")
    (wait)
    (text #:color 5 "【一哉】・・・。")
    (wait)
    (text #:color 5 "【一哉】・・・。")
    (wait)
    (text #:color 5 "【一哉】下痢だ・・・駅のトイレを借りよう。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "27.pd8")
    (proc 15)
    (set-arr~ @ 6 1)
    (image "m11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m11.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】な、なんてやつだ・・・お尻を押さえながら、駅の構内に入ってしまった。")
    (wait)
    (set-reg: 537 1)))
  ((> T 1900)
   (<>
    (if (== (: 835) 0)
      (<> (sound 1) (set-var I 50) (proc 26) (set-reg: 835 1)))
    (text #:color 7 "【" 0 "】うーん・・・夜だなあ。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】車の音が・・・あまりしないな。")
    (wait)))
  ((&& (> T 0) (< T 400))
   (<>
    (if (== (: 835) 0)
      (<> (sound 1) (set-var I 50) (proc 26) (set-reg: 835 1)))
    (text #:color 7 "【" 0 "】深夜だ・・・さすがに人影はない。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】みんな何をしているんだろう・・・素直に寝ているのか？")
    (wait)))
  ((&& (> T 359) (< T 700))
   (<>
    (if (== (: 835) 0)
      (<> (sound 1) (set-var I 50) (proc 26) (set-reg: 835 1)))
    (text #:color 7 "【" 0 "】ふあああ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】早朝だぜ・・・おい。")
    (wait)))
  ((== (: 174) 0)
   (<>
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ここが俺達の街で、一番にぎやかな場所・・・『先負駅』の周辺だ。")
    (wait)
    (text #:color 7 "【" 0 "】さてと、どうしようかな？")
    (wait)
    (set-reg: 174 1)))
  ((== (: 174) 1)
   (<>
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】先負駅だぜ・・・どうするんだ？")
    (wait))))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "他の場所に行く") (text "電車に乗る") (text "やめる")))
      (cond
       ((&&
         (== N 1)
         (== (: 281) 1)
         (> H 810)
         (> T 800)
         (< T 2200)
         (== (: 282) 0)
         (== (: 598) 0))
        (<>
         (text #:color 7 "【" 0 "】そうだな、他の場所に行こうぜ・・・。")
         (wait)
         (sound 1)
         (set-var I 37)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 6 "ドスンッ！！")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "u.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "uan.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "u.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 59)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 6 "【奇麗な女性】ごめんなさい・・・大丈夫？")
         (wait)
         (text #:color 7 "【" 0 "】いてててっ・・・あれ？")
         (wait)
         (text #:color 6 "【奇麗な女性】あ・・・時間がないわ、急いで電車に乗らないと。")
         (wait)
         (text #:color 7 "【" 0 "】お、おい・・・。")
         (wait)
         (set-reg: 282 1)
         (set-var N 2)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・他の場所に行こうぜ。")
         (wait)
         (set-var N 2)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 2) (> T 0) (< T 500))
        (<> (text #:color 7 "【" 0 "】電車に乗るって・・・今の時間は動いていないじゃないか。") (wait)))
       ((&& (== N 2) (< M 300))
        (<>
         (text #:color 7 "【" 0 "】さてと・・・電車に乗って、と。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】お金が足りない・・・。")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】電車に乗って行く場所と言えば・・・やはり一つ隣の『矢吹町』だな。")
         (wait)
         (text #:color 7 "【" 0 "】３００円で切符を買ってと・・・よーし、矢吹町駅に行こう。")
         (wait)
         (set-var A 30)
         (proc 12)
         (set-var M (- M 300))
         (proc 11)
         (set-var N 0)
         (mes-call "den.mes")
         (slot 1 3)
         (mes-jump "yabuki.mes")))
       ((== N 3)
        (<>
         (text #:color 7 "【" 0 "】待てよ・・・かわいい女の子がいるかもしれないぞ、もう少しここにいようぜ。")
         (wait)
         (if-else (&& (> T 0) (< T 700))
           (<>
            (text #:color 7 "【" 0 "】・・・。")
            (wait)
            (text #:color 7 "【" 0 "】ははは、そんな事を言っても、こんな時間じゃ誰も歩いていないか・・・。")
            (wait))
           (<>))))
       (else (<>)))))
    ((&& (== V 1) (== N 1) (== (: 10) 0))
     (<>
      (text #:color 7 "【" 0 "】駅前にはバスのターミナルがあるんだ・・・俺はバスが嫌いだけどね。")
      (wait)
      (set-reg: 10 1)))
    ((&& (== V 1) (== N 1) (== (: 10) 1))
     (<> (text #:color 7 "【" 0 "】バスが走っている・・・ように見える。") (wait)))
    ((&& (== V 1) (== N 2) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】『先負駅』と書かれている・・・俺はこの街が好きなんだ。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 1) (== N 2) (== (: 11) 1))
     (<> (text #:color 7 "【" 0 "】先負駅だ・・・『さきまけえき』って読むんだぜ。") (wait)))
    ((&& (== V 1) (== N 3) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】駅のコインロッカーだな・・・俺は利用するつもりはないぞ。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 3) (== (: 12) 1))
     (<> (text #:color 7 "【" 0 "】だからコインロッカーだ・・・。") (wait)))
    ((&& (== V 1) (== N 4) (== (: 13) 0))
     (<>
      (text #:color 7 "【" 0 "】駅の改札さ・・・電車に乗る為には、ここを通らないとな。")
      (wait)
      (set-reg: 13 1)))
    ((&& (== V 1) (== N 4) (== (: 13) 1))
     (<> (text #:color 7 "【" 0 "】駅の改札だ・・・最近、自動改札になったばかりだ。") (wait)))
    ((&& (== V 1) (== N 5) (== (: 14) 0))
     (<>
      (text #:color 7 "【" 0 "】俗に言う、駅ビルだな・・・かなりでかい建物だ。")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 1) (== N 5) (== (: 14) 1))
     (<>
      (text #:color 7 "【" 0 "】最近できたばかりの駅ビルだ・・・一番喜んでいるのは、この街の地主達だろう。")
      (wait)))
    ((&& (== V 1) (== N 6) (== (: 15) 0))
     (<>
      (text #:color 7 "【" 0 "】駅前には必ず樹木があるんだよな・・・１本や２本生えていたって、空気が奇麗になるとは思えないが。")
      (wait)
      (text #:color 7 "【" 0 "】まあいいさ、どうせ人類は１９９９年に滅亡するんだ・・・ははは。")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 1) (== N 6) (== (: 15) 1))
     (<>
      (text #:color 7 "【" 0 "】緑は美しい・・・なんて歯が浮くどころか、抜けそうな事を言うのはよそうぜ。")
      (wait)))
    ((&& (== V 1) (== N 7) (== (: 16) 0))
     (<>
      (text #:color 7 "【" 0 "】ターミナルにそって造られた歩道だな・・・人間様が歩くスペースだぜ。")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 1) (== N 7) (== (: 16) 1))
     (<>
      (text #:color 7 "【" 0 "】歩道だ・・・誰も歩いていないな。")
      (wait)
      (text #:color 7 "【" 0 "】無駄なスペースだぜ・・・俺様がそっと破壊してやろうか？")
      (wait)))
    ((&& (== V 1) (== N 8) (== (: 17) 0))
     (<>
      (text #:color 7 "【" 0 "】駅ビルが建つのと同時にオープンした、百貨店・・・つまりデパートだな。")
      (wait)
      (text #:color 7 "【" 0 "】とにかく値段が高いので有名だ・・・俺は一度もここで買い物をした事がない。")
      (wait)
      (set-reg: 17 1)))
    ((&& (== V 1) (== N 8) (== (: 17) 1))
     (<> (text #:color 7 "【" 0 "】デパートメントストアだな・・・今はバーゲン中のようだ。") (wait)))
    ((&& (== V 1) (== N 9) (== (: 18) 0))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】遠くの方にも、色々なビルが並んでいる・・・これだけ賑やかなんだから、エッチなラグジュアリスペースがあっていいと思うけど。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】ないんだよな、これが・・・もっとも俺は健全なる学生だから、そんな場所には行かない・・・と思うけど。")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 1) (== N 9) (== (: 18) 1))
     (<> (text #:color 7 "【" 0 "】とにかくたくさんのビルが建っている・・・。") (wait)))
    ((&& (== V 1) (== N 10) (== (: 19) 0))
     (<>
      (text #:color 7 "【" 0 "】いいじゃないか、空なんて・・・東京の空なんか見上げる価値などないさ。")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 1) (== N 10) (== (: 19) 1))
     (<>
      (text #:color 7 "【" 0 "】東京には空がない・・・誰が言った言葉だっけ？")
      (wait)
      (text #:color 7 "【" 0 "】俺か？・・・違うな。")
      (wait)))
    ((&& (== V 1) (== N 11) (== (: 20) 0))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】色々な人達が駅前にいる・・・電車に乗って宇宙に旅立つ人、恋人と心中の相談をする為に待っている人・・・。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】気にいらない人がいたら、刺し殺してやろうと身構えている人・・・柱の影に隠れて、手淫をしている人。")
      (wait)
      (text #:color 7 "【" 0 "】嘘だぜ、信じるなよ・・・ははは。")
      (wait)
      (set-reg: 20 1)))
    ((&& (== V 1) (== N 11) (== (: 20) 1))
     (<> (text #:color 7 "【" 0 "】見る価値のない人間ばかりだ・・・聞こえたら、殴られそうだけど。") (wait)))
    ((&& (== V 1) (== N 12) (== (: 21) 0))
     (<>
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 7 "【" 0 "】あの女性は・・・危ないな。")
      (wait)
      (text #:color 7 "【" 0 "】男の第６感がそう感じさせるぜ・・・あんな女性とつきあったら、ケツの穴の毛まで抜かれそうだ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】いいんだよ、とにかくそう感じさせるんだから・・・。")
      (wait)
      (animate 0 8 1)
      (animate 4 8)
      (set-reg: 21 1)))
    ((&& (== V 1) (== N 12) (== (: 21) 1))
     (<>
      (text #:color 7 "【" 0 "】危険な匂いがプンプンだ・・・きっと４０年後には俺様の女性遍歴を本にして出版するに違いない。")
      (wait)))
    ((&& (== V 2) (== N 1) (== (: 22) 0))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】どうして俺が、見知らぬおっさんと話さなければならんのだ・・・１億円くれるのなら、挨拶ぐらいはしてやってもいいぞ。")
      (wait)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】俺は何も見てないぞ。")
      (wait)
      (set-reg: 22 1)))
    ((&& (== V 2) (== N 1) (== (: 22) 1))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】おっさんと話すぐらいだったら、部屋で壁に向かって一人でブツブツと言っていた方がマシだぜ、フン！！")
      (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))