(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\い
  #\【
  #\】
  #\な
  #\の
  #\と
  #\。
  #\て
  #\っ
  #\は
  #\、
  #\ん
  #\た
  #\さ
  #\し
  #\だ
  #\み
  #\が
  #\か
  #\あ
  #\に
  #\る
  #\も
  #\で
  #\れ
  #\を
  #\つ
  #\ら
  #\そ
  #\言
  #\俺
  #\く
  #\事
  #\う
  #\二
  #\き
  #\ろ
  #\け
  #\え
  #\健
  #\彼
  #\ぜ
  #\ー
  #\時
  #\喫
  #\茶
  #\店
  #\わ
  #\ま
  #\女
  #\前
  #\よ
  #\ア
  #\ル
  #\バ
  #\イ
  #\ト
  #\ど
  #\や
  #\び)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (sound 1)
 (set-var I 42)
 (proc 26)
 (set-reg: 835 0)
 (while
  (== 1 1)
  (<>
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((&& (== N 3) (== (: 420) 0))
     (<>
      (text #:color 7 "【" 0 "】よーし、さとみのデータを見るんだな。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "30.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "p.pd8")
      (proc 16)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "pan.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "p.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】彼女の名前は『黒川　さとみ』・・・俺とは中学生の時からのつきあいだ。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】彼女は、駅前の喫茶店でアルバイトをしている・・・以前に聞いた事があるが、あの喫茶店のオーナーはさとみの親戚なんだよな。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】女好きを自認する俺でも、なぜかさとみには性欲がおきない・・・だからこそ、長くつきあっていられるのかもしれないが・・・。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】それにしても、どうしてあんなに口が悪いんだろう・・・さとみは彼氏がいるとか言っていたが、彼氏がかわいそうだぜ。")
      (wait)
      (if-else (== (: 413) 1)
        (<>
         (slot 1 2)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "16.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "p11.pd8")
         (proc 16)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】彼氏で思い出したけど・・・さとみのやつ、その彼氏の事で悩んでいるんじゃないか？")
         (wait)
         (slot 1 8)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "p13.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "p13an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "p13.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】喫茶店のアルバイトをさぼって、河原で一人で座ってるなんて・・・さとみらしくないよな。")
         (wait)
         (text #:color 7 "【" 0 "】あいつ、何も俺に言わないし・・・あいつが言わない以上、俺も無理に聞く訳にもいかないしな。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait))
        (<>))
      (cond
       ((&& (== (: 414) 1) (== (: 419) 0))
        (<>
         (slot 1 3)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "15.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "p01.pd8")
         (proc 16)
         (set-arr~ @ 7 0)
         (text
          #:color
          7
          "【"
          0
          "】どうしてさとみは、体育倉庫で泣いていたんだろう・・・あいつが泣くところなんて初めて見たぜ。")
         (wait)
         (text #:color 7 "【" 0 "】そう言えば、健二がいたな・・・まさかあの馬鹿が関係してるなんて事はないだろうな？")
         (wait)))
       ((&& (== (: 414) 1) (== (: 419) 1))
        (<>
         (slot 1 3)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "15.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "p01.pd8")
         (proc 16)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】さとみが泣いていた理由も、今はわかってる・・・全て健二か原因だったんだな。")
         (wait)))
       (else (<>)))
      (if-else (== (: 419) 1)
        (<>
         (slot 1 2)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "35.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "p02.pd8")
         (proc 16)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】そしてさとみから電話があって・・・俺は裏の公園に呼び出されたんだ。")
         (wait)
         (slot 1 8)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "p03.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "p03an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "p03.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】さとみは健二にフラれた・・・まったく健二の野郎、さとみをもてあそびやがって。")
         (wait)
         (text #:color 7 "【" 0 "】あいつは舞ちゃんが好きなんだろ！！・・・二股かけるなんて、とんでもないやつだぜ。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】ははは・・・人の事は言えないか。")
         (wait)
         (text
          #:color
          7
          "【"
          0
          "】とにかく、さとみは喫茶店のアルバイトに復帰すると言ってたしな・・・あとは時間が解決してくれればいいんだが。")
         (wait))
        (<>))
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "42.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】さとみとは、何でも言い合える間柄なんだ・・・女の友達だなんて、今でも信じられないぜ。")
      (wait)
      (set-reg: 608 1)
      (slot 1 2)
      (mes-jump "myroom.mes")))
    ((&& (== N 3) (== (: 420) 1))
     (<>
      (text #:color 7 "【" 0 "】さとみのデータを見るのか？・・・ティッシュを用意した方がいいぞ。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "30.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "p.pd8")
      (proc 16)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "pan.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "p.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】彼女の名前は『黒川　さとみ』・・・俺とは中学生の時からのつきあいだ。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】彼女は、駅前の喫茶店でアルバイトをしている・・・以前に聞いた事があるが、あの喫茶店のオーナーはさとみの親戚なんだ。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "16.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "p11.pd8")
      (proc 16)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】今から考えてみれば、あの時も健二との事を考えてたんだろう・・・。")
      (wait)
      (slot 1 8)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "p13.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "p13an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "p13.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】喫茶店のアルバイトをさぼって、河原で一人で座ってるなんて・・・さとみらしくないと思ったんだ。")
      (wait)
      (text #:color 7 "【" 0 "】あの時は俺に何も言わないし・・・あいつが言わない以上、俺も無理に聞く訳にもいかなかったしな。")
      (wait)
      (slot 1 3)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "15.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "p01.pd8")
      (proc 16)
      (set-arr~ @ 7 0)
      (text
       #:color
       7
       "【"
       0
       "】そして倉庫で泣いてたんだ・・・たぶん健二に会った事を考えると、あの時にはっきり言われたんだろう。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "35.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "p02.pd8")
      (proc 16)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】そしてさとみから電話あって・・・俺は裏の公園に呼び出されたんだ。")
      (wait)
      (slot 1 8)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "p03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "p03an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "p03.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】さとみは健二にフラれた・・・まったく健二の野郎、さとみをもてあそびやがって。")
      (wait)
      (text #:color 7 "【" 0 "】あいつは舞ちゃんが好きなんだろ！！・・・二股かけるなんて、とんでもないやつだぜ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ははは・・・人の事は言えないか。")
      (wait)
      (slot 1 8)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "p04.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "p04an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "p04.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text
       #:color
       7
       "【"
       0
       "】しかし、いきなりさとみが抱きついて来た時はびっくりしたぜ・・・もっとも、その後の事を考えれば大した事はないけど。")
      (wait)
      (text #:color 7 "【" 0 "】さとみは俺に言った・・・健二の事を忘れさせてくれ、と。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】さとみと・・・あんな関係になるなんて、思いもよらなかった。")
      (wait)
      (text #:color 7 "【" 0 "】俺は公園のしげみの中で、服を脱がし・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "p12.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "p08.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "p07.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "p06.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "p05.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 0)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "p12an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "p12.s4" (~ @ 2))
      (animate 0 0 1)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "p12.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "p08.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "p07.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "p06.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "p12an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "p12.s4" (~ @ 2))
      (animate 0 0 1)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】ひっひっひっ・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "p12.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "p08.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "p07.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "p12an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "p12.s4" (~ @ 2))
      (animate 0 0 1)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】へっへっへっ・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "p12.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 2)
      (image "p08.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 27)
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "p12an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "p12.s4" (~ @ 2))
      (animate 0 0 1)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】けっけっけっ・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "p12.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "p12an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "p12.s4" (~ @ 2))
      (animate 0 0 1)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】あいつの身体・・・奇麗だったよなあ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】おっとっと・・・ヨダレがたれてしまったぞ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "p10.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "p10an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "p10.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】そしてさとみと俺は・・・最後の一線を越えてしまったんだ。")
      (wait)
      (text #:color 7 "【" 0 "】それも、後ろからだぜ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "42.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (text
       #:color
       7
       "【"
       0
       "】さとみは、今まで通りの関係でいましょうって言ったけど・・・本当に友達の関係が続けられるのだろうか？")
      (wait)
      (set-reg: 608 1)
      (slot 1 2)
      (mes-jump "myroom.mes")))
    (else (<>)))))
 (set-arr~ @ 7 1))