(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\。
  #\い
  #\な
  #\か
  #\っ
  #\、
  #\だ
  #\て
  #\た
  #\の
  #\ん
  #\者
  #\が
  #\う
  #\医
  #\は
  #\？
  #\し
  #\看
  #\護
  #\婦
  #\ら
  #\で
  #\ま
  #\あ
  #\さ
  #\す
  #\く
  #\る
  #\と
  #\ね
  #\じ
  #\ど
  #\（
  #\）
  #\こ
  #\ょ
  #\に
  #\を
  #\！
  #\前
  #\ー
  #\れ
  #\え
  #\ろ
  #\ふ
  #\も
  #\よ
  #\そ
  #\り
  #\ッ
  #\お
  #\出
  #\コ
  #\ゃ
  #\ン
  #\痛
  #\ト
  #\け
  #\１
  #\や
  #\ち
  #\わ
  #\診
  #\む
  #\日
  #\見
  #\ポ
  #\ル
  #\生
  #\入
  #\待
  #\ぞ
  #\チ
  #\せ
  #\ぐ
  #\プ
  #\小
  #\ほ
  #\何
  #\察
  #\へ
  #\訳
  #\人
  #\膿
  #\名
  #\つ
  #\き
  #\大
  #\め
  #\事
  #\ご
  #\言
  #\私
  #\先
  #\検
  #\査
  #\紙
  #\レ
  #\カ)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "kuro.pd8")
 (proc 15)
 (set-arr~ @ 7 0)
 (slot 1 7)
 (set-arr~ @ 7 0)
 (load "53.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (if (== (: 598) 0)
   (<>
    (text #:color 7 "【" 0 "】ふう・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 6 "【看護婦】" 0 "さん・・・１番のドアからお入りください。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "53.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 9)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "u01.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 25)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "u02.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 25)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u01.s4" (~ @ 2))
    (animate 0 0 2)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 59)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【看護婦】そこの椅子におかけください。")
    (wait)
    (text #:color 1 "【医者】ほい、どうしました？")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あーっ！！")
    (wait)
    (text #:color 1 "【医者】え！？・・・な、なに！？")
    (wait)
    (text #:color 7 "【" 0 "】（こ、この看護婦・・・俺に何度もぶつかってきた女性じゃないか！？）")
    (wait)
    (text #:color 6 "【看護婦】・・・。")
    (wait)
    (text #:color 1 "【医者】キミねえ、いきなり大声を出して・・・ここは病院だから、大声を出さないように。")
    (wait)
    (set-reg: 598 1)))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "帰る") (text "やめる")))
      (cond
       ((&& (== N 1) (== (: 50) 0))
        (<> (text #:color 1 "【医者】待ちたまえ・・・まだ診察は終ってないぞ。") (wait)))
       ((&& (== N 1) (== (: 50) 1))
        (<>
         (text #:color 6 "【看護婦】お大事に・・・。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "kuro.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (text #:color 2 "【受け付け】" 0 "さん・・・３００円になります。")
         (wait)
         (text #:color 7 "【" 0 "】へいへい。")
         (wait)
         (set-var M (- M 300))
         (proc 11)
         (text #:color 2 "【受け付け】ありがとうございましたー。")
         (wait)
         (text #:color 7 "【" 0 "】なんだよ、ありがとうごさいましたって・・・まあいいか。")
         (wait)
         (set-var A 30)
         (proc 12)
         (proc 11)
         (set-var N 6)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 2) (== (: 50) 0))
        (<> (text #:color 7 "【" 0 "】（そうだな・・・ポコチンをまだ診てもらってないぞ。）") (wait)))
       ((&& (== N 2) (== (: 50) 1))
        (<>
         (text #:color 1 "【医者】キミ・・・まだ何か用かね？")
         (wait)
         (text #:color 7 "【" 0 "】そんな言い方ってないだろ・・・え？")
         (wait)))
       (else (<>)))))
    ((&& (== V 2) (== N 1) (== (: 10) 0))
     (<>
      (text #:color 1 "【医者】で、どうしました？")
      (wait)
      (text #:color 7 "【" 0 "】実は・・・。")
      (wait)
      (set-reg: 101 0)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show
       (<.>
        (text "頭が")
        (text "口が")
        (text "咽が")
        (text "腹が")
        (text "ポコチンが")
        (text "足が")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】頭が・・・。")
         (wait)
         (text #:color 1 "【医者】ふむ・・・頭がどうかしました？")
         (wait)
         (set-reg: 11 1)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】口が・・・。")
         (wait)
         (text #:color 1 "【医者】ふむ・・・口がどうかしました？")
         (wait)
         (set-reg: 11 2)))
       ((== N 3)
        (<>
         (text #:color 7 "【" 0 "】咽が・・・。")
         (wait)
         (text #:color 1 "【医者】ふむ・・・咽がどうかしました？")
         (wait)
         (set-reg: 11 3)))
       ((== N 4)
        (<>
         (text #:color 7 "【" 0 "】腹が・・・。")
         (wait)
         (text #:color 1 "【医者】ふむ・・・腹がどうかしました？")
         (wait)
         (set-reg: 11 4)))
       ((== N 5)
        (<>
         (text #:color 7 "【" 0 "】ポコチンが・・・。")
         (wait)
         (text #:color 1 "【医者】ふむ・・・ポコチンがどうかしました？")
         (wait)
         (set-reg: 11 5)))
       ((== N 6)
        (<>
         (text #:color 7 "【" 0 "】足が・・・。")
         (wait)
         (text #:color 1 "【医者】ふむ・・・足がどうかしました？")
         (wait)
         (set-reg: 11 4)))
       (else (<>)))
      (set-reg: 101 0)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "かゆい") (text "臭い") (text "痛い") (text "楽しい")))
      (cond
       ((== N 1) (<> (text #:color 7 "【" 0 "】かゆいんです。") (wait) (set-reg: 12 1)))
       ((== N 2) (<> (text #:color 7 "【" 0 "】臭いんです。") (wait) (set-reg: 12 2)))
       ((== N 3) (<> (text #:color 7 "【" 0 "】痛いんです。") (wait) (set-reg: 12 3)))
       ((== N 4) (<> (text #:color 7 "【" 0 "】楽しいんです。") (wait) (set-reg: 12 4)))
       (else (<>)))
      (text #:color 1 "【医者】ふむ・・・")
      (cond
       ((== (: 11) 1) (<> (text "頭が")))
       ((== (: 11) 2) (<> (text "口が")))
       ((== (: 11) 3) (<> (text "咽が")))
       ((== (: 11) 4) (<> (text "腹が")))
       ((== (: 11) 5) (<> (text "ポコチンが")))
       ((== (: 11) 6) (<> (text "足が")))
       (else (<>)))
      (cond
       ((== (: 12) 1) (<> (text "かゆいんですな。") (wait)))
       ((== (: 12) 2) (<> (text "臭いんですな。") (wait)))
       ((== (: 12) 3) (<> (text "痛いんですな。") (wait)))
       ((== (: 12) 4)
        (<>
         (text "楽しいんですな。")
         (wait)
         (text #:color 1 "【医者】・・・。")
         (wait)
         (text #:color 1 "【医者】なんですか、そりゃ？")
         (wait)
         (text #:color 6 "【看護婦】くすくすくすっ・・・。")
         (wait)))
       (else (<>)))
      (cond
       ((&& (== (: 11) 5) (== (: 12) 3))
        (<> (text #:color 7 "【" 0 "】はい・・・おかげさんで。") (wait) (set-reg: 10 1)))
       ((== (: 10) 0)
        (<>
         (text #:color 7 "【" 0 "】と、言うのは嘘です。")
         (wait)
         (text #:color 1 "【医者】・・・。")
         (wait)
         (text #:color 1 "【医者】ちゃんと答えてくれませんと、診察ができませんよ。")
         (wait)))
       (else (<>)))))
    ((&& (== V 2) (== N 1) (== (: 13) 0))
     (<>
      (text #:color 1 "【医者】で、いつごろからですか？")
      (wait)
      (text #:color 7 "【" 0 "】えーと・・・。")
      (wait)
      (set-reg: 101 0)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "１日前") (text "２日前") (text "もっと前") (text "忘れるほど前")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】１日前ぐらいかな？")
         (wait)
         (text #:color 1 "【医者】１日前から痛くなった訳だね。")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】２日前ぐらいかな？")
         (wait)
         (text #:color 1 "【医者】２日前ぐらいから、痛くなった訳だね。")
         (wait)))
       ((== N 3)
        (<>
         (text #:color 7 "【" 0 "】もっと前かな？")
         (wait)
         (text #:color 1 "【医者】はあ？")
         (wait)
         (text #:color 7 "【" 0 "】だから、もっと前。")
         (wait)
         (text #:color 1 "【医者】何と比べてもっと前なのかね？")
         (wait)
         (text #:color 7 "【" 0 "】今日から比べて、もっと前。")
         (wait)
         (text #:color 1 "【医者】えーと、もっと前から・・・痛くなった訳だね。")
         (wait)))
       ((== N 4)
        (<>
         (text #:color 7 "【" 0 "】忘れる程前から痛くなったかな。")
         (wait)
         (text #:color 1 "【医者】そんなに前から痛かったのかね？")
         (wait)
         (text #:color 7 "【" 0 "】最高で３日前までしか覚えられないんだよ。")
         (wait)
         (text #:color 1 "【医者】仕方がない人だな・・・３日以上前から痛くなった訳だね。")
         (wait)
         (text #:color 6 "【看護婦】くすくすくすっ・・・。")
         (wait)
         (set-reg: 116 (+ (: 116) 1))))
       (else (<>)))
      (set-reg: 13 1)))
    ((&& (== V 2) (== N 1) (== (: 14) 0))
     (<>
      (text #:color 1 "【医者】膿は出るかね？")
      (wait)
      (set-reg: 101 0)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "出ない") (text "少々") (text "１リットルほど")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】膿は・・・出てないかな？")
         (wait)
         (text #:color 1 "【医者】ふむ・・・膿は出てない訳だね。")
         (wait)
         (text #:color 7 "【" 0 "】おかげさまで。")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】膿は・・・ちょっと出てるかな？")
         (wait)
         (text #:color 1 "【医者】ふむ、膿はちょっと出てる訳だね。")
         (wait)
         (text #:color 7 "【" 0 "】おかげさまで。")
         (wait)))
       ((== N 3)
        (<>
         (text #:color 7 "【" 0 "】１リットルほど出てます。")
         (wait)
         (text #:color 1 "【医者】い、１リットルも膿が出てのるか！？")
         (wait)
         (text #:color 7 "【" 0 "】嘘です。")
         (wait)
         (text #:color 1 "【医者】あのねえ・・・私はキミと遊んでる暇はないのだよ。")
         (wait)
         (text #:color 7 "【" 0 "】ははは・・・。")
         (wait)))
       (else (<>)))
      (set-reg: 14 1)))
    ((&& (== V 2) (== N 1) (== (: 15) 0))
     (<>
      (text #:color 1 "【医者】さてと・・・じゃあ見せてもらおうかな。")
      (wait)
      (text #:color 7 "【" 0 "】べー。")
      (wait)
      (text #:color 1 "【医者】舌じゃないよ、ポコチンが痛いのに舌を見せてどうするのかね？")
      (wait)
      (text #:color 6 "【看護婦】先生、尿検査はどうなさいます？")
      (wait)
      (text #:color 1 "【医者】ああ、そうか・・・検査をしてから見せてもらおうかな。")
      (wait)
      (text #:color 6 "【看護婦】紙コップを渡しますから、受け付けの横にあるトイレでお小水を入れてください。")
      (wait)
      (text #:color 7 "【" 0 "】へいへい。")
      (wait)
      (text #:color 6 "【看護婦】お小水を入れた紙コップは、トイレの横にある小さな窓の所に置いてください。")
      (wait)
      (text #:color 7 "【" 0 "】へいへい。")
      (wait)
      (text #:color 6 "【看護婦】検査の結果はすぐに出ますから・・・はい、これが紙コップです。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kuro.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (sound 1)
      (text #:color 7 "【" 0 "】トイレに入って・・・紙コップに小水を入れて、と。")
      (wait)
      (text #:color 6 "じょろじょろ・・・じょろじょろ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】はあ・・・。")
      (wait)
      (text #:color 6 "じょろじょろ・・・じょろじょろ・・・。")
      (wait)
      (text #:color 6 "じょろじょろ・・・じょろじょろ・・・。")
      (wait)
      (text #:color 6 "じょろじょろ・・・じょろじょろ・・・。")
      (wait)
      (text #:color 6 "じょろじょろ・・・じょろじょろ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】あ、あれれ！？・・・止まらないぞ、あふれそうだ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】なんだよ・・・コップの中にしなければいいだけじゃないか。")
      (wait)
      (text #:color 7 "【" 0 "】ふう・・・。")
      (wait)
      (text #:color 7 "【" 0 "】えーと、紙コップを小さな窓に置いて・・・これでいいんだな。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】トイレを出て・・・待合室で待ってればいいのかな？")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ふああ・・・眠くなってくるぜ。")
      (wait)
      (text #:color 6 "【看護婦】" 0 "さん、１番のドアからどうぞ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "53.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 9)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "u01.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 25)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "u02.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 25)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "u01an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "u01.s4" (~ @ 2))
      (animate 0 0 2)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (sound 1)
      (set-var I 59)
      (proc 26)
      (set-reg: 835 0)
      (text #:color 1 "【医者】えーと・・・これが検査結果だね。")
      (wait)
      (text #:color 6 "どたどたどたっ・・・ばたんっ！！")
      (wait)
      (text #:color 7 "【" 0 "】な、何だ！？")
      (wait)
      (text
       #:color
       2
       "【太った看護婦】先生っ！！・・・１０５号室の患者さんが、自分の性器を自分でなめようとして、背骨の骨を折ってしまいました！！")
      (wait)
      (text #:color 1 "【医者】やややっ！！またあの患者か！！・・・悪いなキミ、ちょっと待っててくれたまえ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "53.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 9)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "u01.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 25)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "u01an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "u01.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 6 "【看護婦】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ははは・・・。")
      (wait)
      (text #:color 6 "【看護婦】少し待っててくださいね。")
      (wait)
      (text #:color 7 "【" 0 "】看護婦さん・・・俺の顔、見た事がない？")
      (wait)
      (text #:color 6 "【看護婦】どこかでお会いした事がありました？")
      (wait)
      (text #:color 7 "【" 0 "】（ちぇっ・・・覚えてないんだ。）")
      (wait)
      (text #:color 6 "【看護婦】少しお待ちください・・・すぐに戻ると思いますから。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 6 "【看護婦】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】あの・・・立ってると疲れない？")
      (wait)
      (text #:color 6 "【看護婦】大丈夫です、おかまいなく。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 6 "【看護婦】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】先生・・・遅いな。")
      (wait)
      (text #:color 6 "【看護婦】そうね、先生が戻るまで・・・やっぱり座ってようかしら。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "u04.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "u04an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "u04.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】（うわあ・・・奇麗な人だな。）")
      (wait)
      (text #:color 6 "【看護婦】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】（くんか、くんか・・・ほのかに、シャンプーの香りがする。）")
      (wait)
      (text #:color 7 "【" 0 "】（こんな奇麗な看護婦さん・・・初めて見たな。）")
      (wait)
      (text #:color 6 "【看護婦】あら？")
      (wait)
      (text #:color 7 "【" 0 "】え？")
      (wait)
      (text #:color 6 "【看護婦】あなたの顔・・・どこかで見た事があるわ。")
      (wait)
      (text #:color 7 "【" 0 "】だからあ、さっき聞いたじゃないか。")
      (wait)
      (text #:color 6 "【看護婦】思い出したわ！！・・・患者さん、私がぶつかった人でしょ？")
      (wait)
      (text #:color 7 "【" 0 "】ピンポーン！！・・・それも一度じゃないぜ。")
      (wait)
      (text #:color 6 "【看護婦】ごめんなさいね、あの時はすごく急いでいたの。")
      (wait)
      (text #:color 7 "【" 0 "】ねえねえ、看護婦さん・・・名前はなんて言うの？")
      (wait)
      (text #:color 6 "【看護婦】ほら、このナースハットに名前が入ってるでしょ？")
      (wait)
      (text #:color 7 "【" 0 "】えーと、やよい・・・くさなぎ？")
      (wait)
      (text #:color 6 "【看護婦】そう、『草薙　やよい』。")
      (wait)
      (text #:color 7 "【" 0 "】格好いい名前だなあ。")
      (wait)
      (text #:color 6 "【看護婦】ふふふ、ありがと。")
      (wait)
      (text #:color 7 "【" 0 "】（うーん・・・ずっーと見てても飽きないな、こんな奇麗な人が脚を組んで座って・・・脚を組んで？）")
      (wait)
      (text #:color 7 "【" 0 "】（ありゃりゃ・・・下着が見えそうだ。）")
      (wait)
      (text #:color 6 "【看護婦】どうかしました？")
      (wait)
      (text #:color 7 "【" 0 "】い、いいえ。")
      (wait)
      (text #:color 7 "【" 0 "】（もっと・・・こう、身体の位置を低くして。）")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "u05.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】（見えた・・・。）")
      (wait)
      (text #:color 7 "【" 0 "】（・・・。）")
      (wait)
      (text #:color 7 "【" 0 "】（黒・・・かな？）")
      (wait)
      (text #:color 6 "【看護婦】あなたの名前は・・・" 0 "さんね。")
      (wait)
      (text #:color 7 "【" 0 "】そうだね。")
      (wait)
      (text #:color 6 "【看護婦】学生さん？")
      (wait)
      (text #:color 7 "【" 0 "】そうだね。")
      (wait)
      (text #:color 6 "【看護婦】歳は・・・１８歳なのね、私の方が２つ歳上ね。")
      (wait)
      (text #:color 7 "【" 0 "】そうだね。")
      (wait)
      (text #:color 6 "【看護婦】そうだね、しか言わないのね。")
      (wait)
      (text #:color 7 "【" 0 "】そうだね。")
      (wait)
      (text #:color 1 "どたどたどた・・・。")
      (wait)
      (text #:color 6 "【看護婦】あ・・・先生が戻って来たみたい。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "53.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 9)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "u01.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 25)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "u02.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 25)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "u01an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "u01.s4" (~ @ 2))
      (animate 0 0 2)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 1 "【医者】ふうふうふう・・・待たせたね。")
      (wait)
      (text #:color 1 "【医者】えーと、検査結果は・・・これか。")
      (wait)
      (text #:color 1 "【医者】・・・。")
      (wait)
      (text #:color 1 "【医者】なんだ、どうでもいい結果じゃないか・・・つまらないな。")
      (wait)
      (text #:color 7 "【" 0 "】（なんだよ、どうでもいいって？）")
      (wait)
      (text #:color 1 "【医者】汚い手でポコチンをいじったか、よっぽど激しい性行為をしたか・・・どちらかだな、わっはっはっはっ！！")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 6 "【看護婦】・・・。")
      (wait)
      (text #:color 1 "【医者】はっはっ・・・は。")
      (wait)
      (text #:color 1 "【医者】これぐらいだったら、普通の生活をしてていっこうにかまわんよ・・・。")
      (wait)
      (set-reg: 50 1)
      (set-reg: 15 1)))
    ((&& (== V 2) (== N 1) (== (: 50) 1))
     (<>
      (text #:color 1 "【医者】ん？・・・他にどこか痛いのかね？")
      (wait)
      (text #:color 1 "【医者】どこも痛くないのなら、もういいよ・・・次の患者さんを診なくてはならんからね。")
      (wait)))
    ((&& (== V 2) (== N 5) (== (: 16) 0) (== (: 50) 0))
     (<>
      (text #:color 6 "【看護婦】・・・。")
      (wait)
      (text #:color 1 "【医者】こらこら、病状は私に話してくれたまえ。")
      (wait)
      (text #:color 7 "【" 0 "】ちぇっ、ちょっとぐらいいいじゃないかよう。")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 2) (== N 5) (== (: 16) 1) (== (: 50) 0))
     (<>
      (text #:color 6 "【看護婦】・・・。")
      (wait)
      (text #:color 1 "【医者】医者は私だよ・・・彼女は看護婦。")
      (wait)))
    ((&& (== V 2) (== N 5) (== (: 50) 1))
     (<> (text #:color 6 "【看護婦】受け付けで呼ばれたら、診察料を払ってください・・・お薬は出ませんから。") (wait)))
    ((&& (== V 1) (== N 2))
     (<> (text #:color 7 "【" 0 "】（ツルピカハゲマル君だ・・・。）") (wait)))
    ((&& (== V 1) (== N 3))
     (<> (text #:color 7 "【" 0 "】（聴診器だな・・・大人の玩具じゃないぞ。）") (wait)))
    ((&& (== V 1) (== N 4))
     (<> (text #:color 7 "【" 0 "】（太ってるなあ・・・医者の不養生を絵に描いたような医者だ。）") (wait)))
    ((&& (== V 1) (== N 6))
     (<> (text #:color 7 "【" 0 "】（この病院の看護婦さんだったのか・・・。）") (wait)))
    ((&& (== V 1) (== N 7))
     (<> (text #:color 7 "【" 0 "】（ナースハットをかぶってる・・・看護婦だから当り前だ。）") (wait)))
    ((&& (== V 1) (== N 8) (== (: 50) 0))
     (<> (text #:color 7 "【" 0 "】（うーん・・・彼女の名前が知りたい。）") (wait)))
    ((&& (== V 1) (== N 8) (== (: 50) 1))
     (<>
      (text #:color 7 "【" 0 "】（彼女の名前は『やよい』さんだ・・・さっそくコンピューターのデータに入れてやるぜ。）")
      (wait)))
    ((&& (== V 1) (== N 9))
     (<> (text #:color 7 "【" 0 "】（机だな・・・別に変わった所はないぞ。）") (wait)))
    ((&& (== V 1) (== N 10))
     (<>
      (text #:color 7 "【" 0 "】（うーん、何か書いてある事はわかるが・・・何が書いてあるかわわからない。）")
      (wait)))
    ((&& (== V 1) (== N 11))
     (<> (text #:color 7 "【" 0 "】（ここは診察室だ・・・色々な薬が置いてある。）") (wait)))
    ((&& (== V 1) (== N 12))
     (<> (text #:color 7 "【" 0 "】（カーテンがあるな・・・ベットを使う時は、このカーテンを閉めるんだ。）") (wait)))
    ((&& (== V 1) (== N 13))
     (<>
      (text #:color 7 "【" 0 "】（このベットは診察する為のものだ・・・セックスする為のベットではないぞ。）")
      (wait)))
    ((&& (== V 1) (== N 14))
     (<> (text #:color 7 "【" 0 "】（太ってる人は小さいと言うが・・・やっぱり小さそうだ。）") (wait)))
    ((&& (== V 1) (== N 15))
     (<> (text #:color 7 "【" 0 "】（カルテだな・・・いったい誰のカルテなんだ？）") (wait)))
    ((&& (== V 1) (== N 16))
     (<> (text #:color 7 "【" 0 "】（診察室だ・・・クレゾールの匂いが充満してる。）") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))