(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\い
  #\。
  #\っ
  #\な
  #\は
  #\た
  #\、
  #\者
  #\医
  #\か
  #\う
  #\ん
  #\て
  #\の
  #\だ
  #\よ
  #\ま
  #\や
  #\ど
  #\る
  #\も
  #\と
  #\こ
  #\れ
  #\が
  #\（
  #\）
  #\ら
  #\く
  #\し
  #\ー
  #\す
  #\で
  #\？
  #\！
  #\え
  #\さ
  #\ね
  #\あ
  #\を
  #\に
  #\ゃ
  #\け
  #\診
  #\痛
  #\む
  #\ン
  #\り
  #\キ
  #\ミ
  #\何
  #\言
  #\ぞ
  #\ひ
  #\お
  #\ベ
  #\入
  #\ふ
  #\人
  #\ち
  #\病
  #\き
  #\ッ
  #\看
  #\護
  #\婦
  #\１
  #\度
  #\来
  #\わ
  #\問
  #\題
  #\思
  #\俺
  #\一
  #\じ
  #\ト
  #\カ
  #\ア
  #\ぶ
  #\せ
  #\ゴ
  #\ム
  #\取
  #\触
  #\下
  #\着
  #\ズ
  #\ボ
  #\悪
  #\見
  #\ル)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (if (== (: 618) 0)
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "kuro.pd8")
    (proc 15)
    (set-arr~ @ 7 0)))
 (slot 1 7)
 (set-arr~ @ 7 0)
 (load "53.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (cond
  ((== (: 602) 0)
   (<>
    (text #:color 7 "【" 0 "】すいてるな・・・この病院、はやってないのか？")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 6 "【看護婦】" 0 "さん・・・１番のドアからお入りください。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "53.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 9)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "u01.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 25)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "u02.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 25)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u01.s4" (~ @ 2))
    (animate 0 0 2)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 59)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 1 "【医者】なんだ、またキミか・・・今度はどうしたのかね？")
    (wait)
    (set-reg: 602 1)))
  ((&& (== (: 618) 1) (== (: 619) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u03an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u03.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 1 "どたどたどたっ！！")
    (wait)
    (text #:color 6 "【やよい】あ・・・戻って来たようですわ。")
    (wait)
    (text #:color 1 "【医者】ふうふうふう・・・いやあすまんすまん、だいぶ待たせてしまったね。")
    (wait)
    (text #:color 1 "【医者】えーと・・・やよい君、ゴムの手袋を取ってくれたまえ。")
    (wait)
    (text #:color 6 "【やよい】・・・はい。")
    (wait)
    (text #:color 1 "【医者】どれどれ・・・うーむ。")
    (wait)
    (text #:color 7 "【" 0 "】ひゃひゃひゃひゃひゃっ・・・くすぐったいな、もう。")
    (wait)
    (text #:color 1 "【医者】触らないと診断できないよ・・・うーむ。")
    (wait)
    (text #:color 1 "【医者】何も問題ないと思うがね・・・ただ、人並以上の持物だな、キミは。")
    (wait)
    (text #:color 6 "【やよい】・・・。")
    (wait)
    (text #:color 1 "【医者】わっはっはっはっはっ！！")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 1 "【医者】はっはっ・・は。")
    (wait)
    (text #:color 6 "【やよい】下着とズボンをはいていいですよ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "53.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 9)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "u01.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 25)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "u02.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 25)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u01.s4" (~ @ 2))
    (animate 0 0 2)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 1 "【医者】どこも悪くないと思うが・・・本人が痛いと言うなら、どこかに問題があるかもしれんな。")
    (wait)
    (text #:color 7 "【" 0 "】（痛いなんて、俺は一言も言ってないぞ。）")
    (wait)
    (text #:color 1 "【医者】続けて痛むようだったら、もう一度来たまえ・・・また診てあげるから。")
    (wait)
    (set-reg: 10 2)
    (set-reg: 50 1)
    (set-reg: 618 0)))
  ((&& (== (: 618) 1) (== (: 619) 1))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "u03.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 24)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u03an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u03.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 59)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 1 "どたどたどたっ！！")
    (wait)
    (text #:color 6 "【やよい】内緒ですよ・・・" 0 "さん。")
    (wait)
    (text #:color 1 "【医者】ふうふうふう・・・いやあすまんすまん、だいぶ待たせてしまったね。")
    (wait)
    (text #:color 1 "【医者】えーと・・・やよい君、ゴムの手袋を取ってくれたまえ。")
    (wait)
    (text #:color 6 "【やよい】・・・はい。")
    (wait)
    (text #:color 1 "【医者】どれどれ・・・うーむ。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 1 "【医者】なんか・・・ベタベタしとるな、ふむ。")
    (wait)
    (text #:color 6 "【やよい】・・・。")
    (wait)
    (text #:color 1 "【医者】ベタベタしとる以外、何も問題ないと思うがね・・・ただ、人並以上の持物だな、キミは。")
    (wait)
    (text #:color 6 "【やよい】・・・。")
    (wait)
    (text #:color 1 "【医者】わっはっはっはっはっ！！")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 1 "【医者】はっはっ・・は。")
    (wait)
    (text #:color 6 "【やよい】下着とズボンをはいていいですよ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "53.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 9)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "u01.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 25)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "u02.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 25)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u01.s4" (~ @ 2))
    (animate 0 0 2)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 1 "【医者】どこも悪くないと思うが・・・本人が痛いと言うなら、どこかに問題があるかもしれんな。")
    (wait)
    (text #:color 7 "【" 0 "】（痛いなんて、俺は一言も言ってないぞ。）")
    (wait)
    (text #:color 1 "【医者】続けて痛むようだったら、もう一度来たまえ・・・また診てあげるから。")
    (wait)
    (set-reg: 10 2)
    (set-reg: 50 1)
    (set-reg: 618 0)
    (set-reg: 619 0)))
  ((&& (== (: 602) 1) (== (: 617) 0))
   (<>
    (text #:color 7 "【" 0 "】誰もいない・・・この病院、つぶれるんじゃないか？")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 6 "【看護婦】" 0 "さん・・・１番のドアからお入りください。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "53.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 9)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "u01.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 25)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "u02.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 25)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u01.s4" (~ @ 2))
    (animate 0 0 2)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 59)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 1 "【医者】なんだ、またまたキミか・・・はっきり言って、きみのチンポコは見飽きたぞ。")
    (wait)))
  ((&& (== (: 617) 1) (== (: 620) 0))
   (<>
    (text #:color 7 "【" 0 "】誰もいない・・・この病院、つぶれるんじゃないか？")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 6 "【看護婦】" 0 "さん・・・１番のドアからお入りください。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "53.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 9)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "u01.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 25)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "u02.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 25)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u01.s4" (~ @ 2))
    (animate 0 0 2)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 59)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 1 "【医者】なんだまたキミか・・・キミのチンポコはもう見たくないな。")
    (wait)))
  ((== (: 620) 1)
   (<>
    (text #:color 7 "【" 0 "】誰もいない・・・暇な病院だ。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 6 "【看護婦】" 0 "さん・・・１番のドアからお入りください。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "53.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 9)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "u01.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 25)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "u02.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 25)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u01.s4" (~ @ 2))
    (animate 0 0 2)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 59)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 1 "【医者】またキミか・・・今度はどうしたのかね？")
    (wait))))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "帰る") (text "やめる")))
      (cond
       ((&& (== N 1) (== (: 50) 0))
        (<> (text #:color 1 "【医者】こらこら、ふざけちゃいけないな・・・まだ何も診察してないじゃないか。") (wait)))
       ((&& (== N 1) (== (: 50) 1))
        (<>
         (text #:color 1 "【医者】ほい、お大事に。")
         (wait)
         (text #:color 6 "【やよい】・・・。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "kuro.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (text #:color 2 "【受け付け】" 0 "さん・・・今日は１００円になります。")
         (wait)
         (text #:color 7 "【" 0 "】ちぇっ、やっぱり金だけは取られるのか。")
         (wait)
         (set-var M (- M 100))
         (proc 11)
         (text #:color 2 "【受け付け】お大事にどうぞ・・・。")
         (wait)
         (set-var A 30)
         (proc 12)
         (proc 11)
         (set-var N 6)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((== N 2)
        (<> (text #:color 7 "【" 0 "】（うーん・・・俺はいったい、どこが悪いんだろ？）") (wait)))
       (else (<>)))))
    ((&& (== V 2) (== N 1) (== (: 10) 0) (== (: 617) 0))
     (<>
      (text #:color 1 "【医者】まだ痛むのかね・・・おかしいなあ、検査の結果は何ともなかったはずだぞ。")
      (wait)
      (set-reg: 10 1)))
    ((&&
      (== V 2)
      (== N 1)
      (> H 823)
      (== (: 10) 1)
      (== (: 609) 1)
      (== (: 617) 0))
     (<>
      (text #:color 1 "【医者】うーん、他の病気かもしれんな・・・ちょっと触診してみるか。")
      (wait)
      (text #:color 6 "【やよい】こちらのベットにどうぞ・・・ズボンと下着を脱いで、膝を立てて寝てください。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "u03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "u03an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "u03.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 1 "【医者】やよい君、ゴムの手袋を取ってくれたまえ。")
      (wait)
      (text #:color 6 "【やよい】・・・はい。")
      (wait)
      (text #:color 1 "【医者】どれどれ・・・うーむ。")
      (wait)
      (text #:color 2 "どたどたどたっ・・・ばたんっ！！")
      (wait)
      (text #:color 7 "【" 0 "】な、何だ！？")
      (wait)
      (text #:color 2 "【太った看護婦】先生っ！！１０５号室の患者さんが、")
      (set-var S (? 5))
      (if (== S 0) (<> (text "まだ熱いカップラーメン")))
      (if (== S 1) (<> (text "コンニャク鍋")))
      (if (== S 2) (<> (text "ゴムホース")))
      (if (== S 3) (<> (text "サソリが入った入れ物")))
      (if (== S 4) (<> (text "ピラニアの入った水槽")))
      (text "の中に自分の性器を入れて・・・大変なんですっ！！")
      (wait)
      (text #:color 1 "【医者】やややっ！？・・・ま、またあの患者か！？")
      (wait)
      (text #:color 7 "【" 0 "】（バ、バカじゃないか！？・・・何をしようとしたかは、用意に想像できるけど。）")
      (wait)
      (text #:color 1 "【医者】すまんな、ちょっと時間がかかるかもしれんが、このまま待っててくれたまえ。")
      (wait)
      (slot 1 7)
      (mes-jump "u03.mes")))
    ((&& (== V 2) (== N 1) (== (: 10) 1) (== (: 617) 0))
     (<>
      (text #:color 1 "【医者】うーん、他の病気かもしれんな・・・ちょっと触診してみるか。")
      (wait)
      (text #:color 6 "【やよい】こちらのベットにどうぞ・・・ズボンと下着を脱いで、膝を立てて寝てください。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "u03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "u03an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "u03.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 1 "【医者】やよい君、ゴムの手袋を取ってくれたまえ。")
      (wait)
      (text #:color 6 "【やよい】・・・はい。")
      (wait)
      (text #:color 1 "【医者】どれどれ・・・うーむ。")
      (wait)
      (text #:color 7 "【" 0 "】ひゃひゃひゃひゃひゃっ・・・くすぐったいな、もう。")
      (wait)
      (text #:color 1 "【医者】触らないと診断できないよ・・・うーむ。")
      (wait)
      (text #:color 1 "【医者】何も問題ないと思うがね・・・ただ、人並以上の持物だな、キミは。")
      (wait)
      (text #:color 6 "【やよい】・・・。")
      (wait)
      (text #:color 1 "【医者】わっはっはっはっはっ！！")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 1 "【医者】はっはっ・・は。")
      (wait)
      (text #:color 6 "【やよい】下着とズボンをはいていいですよ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "53.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 9)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "u01.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 25)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "u02.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 25)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "u01an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "u01.s4" (~ @ 2))
      (animate 0 0 2)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 1 "【医者】どこも悪くないと思うが・・・本人が痛いと言うなら、どこかに問題があるかもしれんな。")
      (wait)
      (text #:color 7 "【" 0 "】（痛いなんて、俺は一言も言ってないぞ。）")
      (wait)
      (text #:color 1 "【医者】続けて痛むようだったら、もう一度来たまえ・・・また診てあげるから。")
      (wait)
      (set-reg: 10 2)
      (set-reg: 50 1)))
    ((&& (== V 2) (== N 1) (== (: 617) 1) (== (: 620) 0))
     (<>
      (text #:color 1 "【医者】まだ痛むのかね？")
      (wait)
      (text #:color 7 "【" 0 "】はっはっはっ、全然痛くありません。")
      (wait)
      (text #:color 1 "【医者】それでは、また違う病気にでもかかったのかね？")
      (wait)
      (text #:color 7 "【" 0 "】いーえ、俺は健康です")
      (wait)
      (text #:color 1 "【医者】・・・。")
      (wait)
      (text #:color 1 "【医者】じゃあ医者に来る必要はないではないか・・・とっとと帰りたまえ。")
      (wait)
      (set-reg: 620 1)
      (set-reg: 50 1)))
    ((&& (== V 2) (== N 1) (== (: 617) 1) (== (: 620) 1))
     (<>
      (text #:color 1 "【医者】どこか具合が悪いのんね？")
      (wait)
      (text #:color 7 "【" 0 "】いーえ、俺は健康です")
      (wait)
      (text #:color 1 "【医者】・・・。")
      (wait)
      (text #:color 1 "【医者】じゃあ医者に来る必要はないではないか・・・とっとと帰りたまえ。")
      (wait)
      (set-reg: 50 1)))
    ((&& (== V 2) (== N 1) (== (: 50) 1))
     (<> (text #:color 1 "【医者】ん？・・・もう帰っていいよ。") (wait)))
    ((&& (== V 2) (== N 5) (== (: 11) 0) (== (: 50) 0) (== (: 617) 0))
     (<>
      (text #:color 7 "【" 0 "】ねえねえ、お茶でもどう？")
      (wait)
      (text #:color 1 "【医者】こらこら、ここは診療室だぞ・・・キミは何か勘違いしてないか？")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 2) (== N 5) (== (: 11) 1) (== (: 50) 0) (== (: 617) 0))
     (<>
      (text #:color 6 "【やよい】・・・。")
      (wait)
      (text #:color 1 "【医者】キミねえ・・・医者は私だよ。")
      (wait)))
    ((&& (== V 2) (== N 5) (== (: 50) 1) (== (: 11) 0) (== (: 617) 0))
     (<>
      (text #:color 6 "【やよい】何か？")
      (wait)
      (text #:color 7 "【" 0 "】ねえねえ、デートしようぜ。")
      (wait)
      (text #:color 1 "【医者】こらこら、キミはポコチンが痛いんだろ？")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 2) (== N 5) (== (: 50) 1) (== (: 11) 1) (== (: 617) 0))
     (<>
      (text #:color 7 "【" 0 "】ねえねえ・・・。")
      (wait)
      (text #:color 1 "【医者】看護婦に用はないばすだ・・・違うかね？")
      (wait)))
    ((&& (== V 2) (== N 5) (== (: 617) 1) (== (: 11) 0))
     (<>
      (text #:color 6 "【やよい】（内緒ですよ・・・" 0 "さん。）")
      (wait)
      (text #:color 7 "【" 0 "】（わかってるって・・・。）")
      (wait)
      (text #:color 1 "【医者】ん？・・・二人で何を目配せしてるのかね？")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 2) (== N 5) (== (: 617) 1) (== (: 11) 1))
     (<> (text #:color 1 "【医者】何度も言うようだが・・・医者は私だよ。") (wait)))
    ((&& (== V 1) (== N 2))
     (<> (text #:color 7 "【" 0 "】（やーい、ハゲハゲっ！！）") (wait)))
    ((&& (== V 1) (== N 3))
     (<> (text #:color 7 "【" 0 "】（聴診器だな・・・これがあれば、お医者さんごっこができる。）") (wait)))
    ((&& (== V 1) (== N 4))
     (<> (text #:color 7 "【" 0 "】（太ってるなあ・・・医者の不養生を絵に描いたような医者だ。）") (wait)))
    ((&& (== V 1) (== N 6) (== (: 617) 0))
     (<> (text #:color 7 "【" 0 "】（やよいさんだ・・・美人だぜ、まったく。）") (wait)))
    ((&& (== V 1) (== N 6) (== (: 617) 1))
     (<> (text #:color 7 "【" 0 "】（やよいさんは・・・白衣の天使だ。）") (wait)))
    ((&& (== V 1) (== N 7) (== (: 617) 1))
     (<> (text #:color 7 "【" 0 "】（うーん・・・触れてみたい。）") (wait)))
    ((&& (== V 1) (== N 7) (== (: 617) 1))
     (<> (text #:color 7 "【" 0 "】（うーん・・・やよいさんの髪は、すごく柔らかかった。）") (wait)))
    ((&& (== V 1) (== N 8) (== (: 617) 0))
     (<>
      (text #:color 7 "【" 0 "】（くんか、くんか・・・クレゾールの匂いにまざって、ほのかにやよいさんの香りがする。）")
      (wait)))
    ((&& (== V 1) (== N 8) (== (: 617) 1))
     (<> (text #:color 7 "【" 0 "】（やよいさん・・・あなたの姿を見てるだけで、幸せな気分になってくる。）") (wait)))
    ((&& (== V 1) (== N 9))
     (<> (text #:color 7 "【" 0 "】（机だな・・・別に変わった所はないぞ。）") (wait)))
    ((&& (== V 1) (== N 10))
     (<> (text #:color 7 "【" 0 "】（たぶんスケジュール表だろう・・・。）") (wait)))
    ((&& (== V 1) (== N 11))
     (<> (text #:color 7 "【" 0 "】（ここは診察室だ・・・色々な薬が置いてある。）") (wait)))
    ((&& (== V 1) (== N 12))
     (<> (text #:color 7 "【" 0 "】（カーテンがあるな・・・ベットを使う時は、このカーテンを閉めるんだ。）") (wait)))
    ((&& (== V 1) (== N 13))
     (<>
      (text #:color 7 "【" 0 "】（このベットは診察する為のものだ・・・セックスする為のベットではないぞ。）")
      (wait)
      (if-else (== (: 617) 1)
        (<>
         (text #:color 7 "【" 0 "】（・・・。）")
         (wait)
         (text #:color 7 "【" 0 "】（似たような事をしちゃったけど・・・。）")
         (wait))
        (<>))))
    ((&& (== V 1) (== N 14))
     (<> (text #:color 7 "【" 0 "】（見たくもないけど・・・見てしまうな。）") (wait)))
    ((&& (== V 1) (== N 15))
     (<> (text #:color 7 "【" 0 "】（カルテだな・・・いったい誰のカルテなんだ？）") (wait)))
    ((&& (== V 1) (== N 16))
     (<> (text #:color 7 "【" 0 "】（診察室だ・・・クレゾールの匂いが充満してる。）") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))