(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\っ
  #\！
  #\子
  #\い
  #\な
  #\て
  #\亜
  #\。
  #\し
  #\ん
  #\だ
  #\の
  #\、
  #\は
  #\る
  #\う
  #\た
  #\が
  #\？
  #\か
  #\あ
  #\き
  #\を
  #\ま
  #\に
  #\そ
  #\さ
  #\事
  #\君
  #\ら
  #\よ
  #\も
  #\れ
  #\好
  #\で
  #\と
  #\ち
  #\く
  #\言
  #\す
  #\ゃ
  #\じ
  #\私
  #\つ
  #\わ
  #\本
  #\当
  #\や
  #\け
  #\ど
  #\め
  #\真
  #\大
  #\嫌
  #\ッ
  #\こ
  #\え
  #\出
  #\行
  #\俺
  #\り
  #\お
  #\結
  #\婚
  #\ス
  #\気
  #\聞
  #\決
  #\人
  #\ろ
  #\ね
  #\何
  #\ー
  #\姉
  #\エ
  #\チ
  #\質
  #\体
  #\愛
  #\キ
  #\一
  #\帰)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (sound 1)
 (set-var I 9)
 (proc 26)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 9 (&& (~ @ 9) 65534))
 (set-arr~ @ 6 1)
 (image "t04.pd8")
 (set-arr~ @ 9 (// (~ @ 9) 1))
 (proc 24)
 (set-arr~ @ 6 1)
 (image "t04an.pd8")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 0)
 (load "t04.s4" (~ @ 2))
 (animate 0 0 0)
 (animate 1 0)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "t06.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (if (== (: 665) 1)
   (<>
    (if (== (: 676) 0)
      (<>
       (text #:color 2 "【亜子】" 0 "君・・・い、いつからそこにいたの！？")
       (wait)
       (text #:color 7 "【" 0 "】亜子さんっ！！好きだっ！！好きなんだあっ！！")
       (wait)
       (text #:color 2 "【亜子】だ、だめよっ！！・・・何をする気なのっ！？")
       (wait)))
    (if (== (: 676) 1)
      (<>
       (text #:color 2 "【亜子】" 0 "君・・・お、同じ事を何度もしないでっ！！")
       (wait)
       (text #:color 7 "【" 0 "】亜子さんっ！！好きだっ！！好きなんだあっ！！")
       (wait)
       (text #:color 2 "【亜子】だ、だめえっ！！・・・だめだったらあ！！")
       (wait)))
    (set-reg: 676 1)
    (text #:color 7 "【" 0 "】駄目と言われても・・・そんなポーズをしてる、亜子さんがいけないんだあ！！")
    (wait)
    (text #:color 2 "【亜子】" 0 "君がいけないのよっ・・・勝手に奥まで入ってくるんだから！！")
    (wait)
    (text #:color 7 "【" 0 "】好きなんだよう・・・亜子さんの事が。")
    (wait)
    (text #:color 2 "【亜子】嘘。")
    (wait)
    (text #:color 7 "【" 0 "】本当。")
    (wait)
    (text #:color 2 "【亜子】じゃあ聞くけど・・・私と真子姉さんとどっちが好き？")
    (wait)
    (text #:color 7 "【" 0 "】き、決まってるじゃないか・・・。")
    (wait)
    (set-reg: 101 0)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "真子") (text "亜子")))
    (if (== N 1)
      (<>
       (text #:color 7 "【" 0 "】真子さんに決まってるさ、ははは。")
       (wait)
       (text #:color 2 "【亜子】何が、はははよ・・・くやしいっ！！")
       (wait)
       (text #:color 7 "【" 0 "】し、しまったあ。")
       (wait)
       (text #:color 2 "【亜子】そんな事を言う" 0 "君なんて、大嫌いっ！！出て行って！！")
       (wait)
       (set-var A 15)
       (proc 12)
       (proc 11)
       (set-reg: 106 (- (: 106) 1))
       (set-var N 8)
       (slot 1 2)
       (mes-jump "town1.mes")))
    (if (== N 2)
      (<>
       (text #:color 7 "【" 0 "】決まってるじゃないか・・・俺が好きなのは亜子さんだよ。")
       (wait)
       (text #:color 2 "【亜子】本当に？")
       (wait)
       (text #:color 7 "【" 0 "】ああ、本当だとも。")
       (wait)))
    (text #:color 2 "【亜子】じゃあ・・・私の恋人になってくれるの？")
    (wait)
    (set-reg: 101 0)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "なる") (text "ならない")))
    (if (== N 1)
      (<>
       (text #:color 7 "【" 0 "】もちろんなるさ。")
       (wait)
       (text #:color 2 "【亜子】本当に？")
       (wait)
       (text #:color 7 "【" 0 "】本当だって・・・だからエッチな事をしてもいいでしょ、恋人なんだから。")
       (wait)
       (text #:color 2 "【亜子】だめっ・・・まだ聞きたい事があるの。")
       (wait)))
    (if (== N 2)
      (<>
       (text #:color 7 "【" 0 "】いやだよ、恋人だなんて・・・。")
       (wait)
       (text #:color 2 "【亜子】ショックだわ・・・私をおもちゃにするつもりだったのね。")
       (wait)
       (text #:color 7 "【" 0 "】し、しまったあ。")
       (wait)
       (text #:color 2 "【亜子】そんな事を言う" 0 "君なんて、大嫌いっ！！出て行って！！")
       (wait)
       (set-var A 15)
       (proc 12)
       (proc 11)
       (set-reg: 106 (- (: 106) 1))
       (set-var N 8)
       (slot 1 2)
       (mes-jump "town1.mes")))
    (text #:color 7 "【" 0 "】なんだよ・・・まだ聞きたい事って。")
    (wait)
    (text #:color 2 "【亜子】私と・・・結婚してくれる？")
    (wait)
    (text #:color 7 "【" 0 "】えーっ！？")
    (wait)
    (text #:color 2 "【亜子】返事をして・・・結婚してくれるの？")
    (wait)
    (set-reg: 101 0)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "結婚する") (text "結婚しない")))
    (if (== N 1)
      (<>
       (text #:color 7 "【" 0 "】しぶしぶしぶ・・・結婚するよう。")
       (wait)
       (text #:color 2 "【亜子】嘘つき・・・" 0 "君がそんな事を考えるはずがないもの。")
       (wait)
       (text #:color 7 "【" 0 "】しまったあ・・・。")
       (wait)
       (text #:color 2 "【亜子】今までの返事も、私とエッチしたいから嘘をついたでしょ！？")
       (wait)
       (text #:color 7 "【" 0 "】そ、そんな事はないさ・・・ははは。")
       (wait)
       (text #:color 2 "【亜子】そんな事を言う" 0 "君なんて、大嫌いっ！！出て行って！！")
       (wait)
       (set-var A 15)
       (proc 12)
       (proc 11)
       (set-reg: 106 (- (: 106) 1))
       (set-var N 8)
       (slot 1 2)
       (mes-jump "town1.mes")))
    (if (== N 2)
      (<>
       (text #:color 7 "【" 0 "】結婚は無理だよ・・・俺はまだ学生だし。")
       (wait)
       (text #:color 2 "【亜子】そうよね・・・" 0 "君が結婚の事まで考えるはずがないもの。")
       (wait)
       (text #:color 7 "【" 0 "】はあ？")
       (wait)
       (text #:color 2 "【亜子】今の質問はね・・・" 0 "君がエッチをしたいために、適当に返事をしてるのか知りたかったの。")
       (wait)))
    (text #:color 7 "【" 0 "】な、俺は嘘をついてないだろう？")
    (wait)
    (text #:color 2 "【亜子】まだ駄目よ・・・" 0 "君は、私以外の女の子とエッチをしない？")
    (wait)
    (set-reg: 101 0)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "しない") (text "する")))
    (if (== N 1)
      (<>
       (text #:color 7 "【" 0 "】しない・・・約束しよう。")
       (wait)
       (text #:color 2 "【亜子】本当に？")
       (wait)
       (text #:color 7 "【" 0 "】本当だって・・・疑り深いなあ。")
       (wait)))
    (if (== N 2)
      (<>
       (text #:color 7 "【" 0 "】うーん・・・しちゃうかもしれない。")
       (wait)
       (text #:color 2 "【亜子】私以外の女の子と・・・エッチをするの？")
       (wait)
       (text #:color 7 "【" 0 "】たぶん・・・する。")
       (wait)
       (text #:color 2 "【亜子】くやしいっ！！・・・そんな事、絶対に我慢できないわ！！")
       (wait)
       (text #:color 7 "【" 0 "】し、しまったあ。")
       (wait)
       (text #:color 2 "【亜子】そんな事を言う" 0 "君なんて、大嫌いっ！！出て行って！！")
       (wait)
       (set-var A 15)
       (proc 12)
       (proc 11)
       (set-reg: 106 (- (: 106) 1))
       (set-var N 8)
       (slot 1 2)
       (mes-jump "town1.mes")))
    (text #:color 2 "【亜子】まだ聞きたい事があるの・・・どうして私の事が好きなの？")
    (wait)
    (set-reg: 101 0)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "身体が好き") (text "顔が好き") (text "わからない")))
    (if (== N 1)
      (<>
       (text #:color 7 "【" 0 "】決まってるじゃないか・・・亜子さんの身体が好きなんだよ。")
       (wait)
       (text #:color 2 "【亜子】私の身体だけが好きなの？")
       (wait)
       (text #:color 7 "【" 0 "】それ以外に、好きになれる部分があるのか？")
       (wait)
       (text #:color 2 "【亜子】ひ、ひっどーいっ！！")
       (wait)
       (text #:color 7 "【" 0 "】し、しまったあ。")
       (wait)
       (text #:color 2 "【亜子】そんな事を言う" 0 "君なんて、大嫌いっ！！出て行って！！")
       (wait)
       (set-var A 15)
       (proc 12)
       (proc 11)
       (set-reg: 106 (- (: 106) 1))
       (set-var N 8)
       (slot 1 2)
       (mes-jump "town1.mes")))
    (if (== N 2)
      (<>
       (text #:color 7 "【" 0 "】決まってるじゃないか・・・亜子さんの顔が好きなんだよ。")
       (wait)
       (text #:color 2 "【亜子】顔だけが好きなの？")
       (wait)
       (text #:color 7 "【" 0 "】だって、かわいいもの。")
       (wait)
       (text #:color 2 "【亜子】・・・ぽっ。")
       (wait)))
    (if (== N 3)
      (<>
       (text #:color 7 "【" 0 "】わからないよ・・・好きって気持ちを言葉にするのは難しい。")
       (wait)
       (text #:color 2 "【亜子】それでも言葉にして欲しいの。")
       (wait)
       (text #:color 7 "【" 0 "】じゃあ・・・顔と身体と性格と、その他全部だな。")
       (wait)
       (text #:color 2 "【亜子】そんな好きでいてくれるの・・・ぽっ。")
       (wait)))
    (text #:color 7 "【" 0 "】な、俺の気持ちはわかっただろ？・・・二人でしっぽりと愛し合おうぜ。")
    (wait)
    (text #:color 2 "【亜子】まだだめっ・・・だいたい" 0 "君、愛し合うって言うけど私に何をするつもりなの？")
    (wait)
    (set-reg: 101 0)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "セックス") (text "キスする") (text "ちちもみ")))
    (if (== N 1)
      (<>
       (text #:color 7 "【" 0 "】おいおい、亜子さんは大人だろ・・・愛し合うって言ったら、セックスするに決まってるじゃないか。")
       (wait)
       (text #:color 2 "【亜子】い、いやらしいわっ！！")
       (wait)
       (text #:color 7 "【" 0 "】し、しまったあ。")
       (wait)
       (text #:color 2 "【亜子】そんな事を言う" 0 "君なんて、大嫌いっ！！出て行って！！")
       (wait)
       (set-var A 15)
       (proc 12)
       (proc 11)
       (set-reg: 106 (- (: 106) 1))
       (set-var N 8)
       (slot 1 2)
       (mes-jump "town1.mes")))
    (if (== N 2)
      (<>
       (text #:color 7 "【" 0 "】もう一度、キスしよう・・・お互いの愛を確かめる為に。")
       (wait)
       (text #:color 2 "【亜子】キスをもう一度するの・・・お互いの愛を確かめる為に。")
       (wait)
       (text #:color 7 "【" 0 "】そうさ・・・。")
       (wait)))
    (if (== N 3)
      (<>
       (text #:color 7 "【" 0 "】亜子さんは子供だから・・・そうだな、今日のところは『ちちもみ』で勘弁してやろう。")
       (wait)
       (text #:color 2 "【亜子】ち、ちちもみ！？・・・い、いやらしいっ！！")
       (wait)
       (text #:color 7 "【" 0 "】し、しまったあ。")
       (wait)
       (text #:color 2 "【亜子】そんな事を言う" 0 "君なんて、大嫌いっ！！出て行って！！")
       (wait)
       (set-var A 15)
       (proc 12)
       (proc 11)
       (set-reg: 106 (- (: 106) 1))
       (set-var N 8)
       (slot 1 2)
       (mes-jump "town1.mes")))
    (text #:color 2 "【亜子】素敵だけど・・・不安だわ。")
    (wait)
    (text #:color 7 "【" 0 "】何が？")
    (wait)
    (text #:color 2 "【亜子】だって、" 0 "君・・・本当に浮気をしない人なのかしら？")
    (wait)
    (text #:color 7 "【" 0 "】しないよ・・・俺は亜子さん一筋だ。")
    (wait)
    (text #:color 2 "【亜子】本当に？")
    (wait)
    (text #:color 7 "【" 0 "】だから、本当だって。")
    (wait)
    (text #:color 2 "【亜子】あのね、前からずっと気になってて・・・聞きたい事があったんだけど。")
    (wait)
    (text #:color 7 "【" 0 "】なんだよ・・・まだ質問があるのか？")
    (wait)
    (text #:color 2 "【亜子】うん・・・" 0 "君がこの店に来た時に、真子姉さんの香水の匂いがした事があったの。")
    (wait)
    (if (== (: 604) 1) (<> (text #:color 7 "【" 0 "】（ぎくうっ！！）") (wait)))
    (text #:color 2 "【亜子】まさか・・・真子姉さんと、変な事はしてないわよね？")
    (wait)
    (set-reg: 101 0)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "してる") (text "してない")))
    (if (== N 1)
      (<>
       (text #:color 7 "【" 0 "】はっはっはっ・・・してるよ、亜子さん。")
       (wait)
       (text #:color 2 "【亜子】や、やっぱりそうだったのね・・・くやしいーっ！！")
       (wait)
       (text #:color 7 "【" 0 "】し、しまったあ。")
       (wait)
       (text #:color 2 "【亜子】" 0 "君なんて、大嫌いっ！！・・・出て行って！！")
       (wait)
       (set-var A 15)
       (proc 12)
       (proc 11)
       (set-reg: 106 (- (: 106) 1))
       (set-var N 8)
       (slot 1 2)
       (mes-jump "town1.mes")))
    (if (&& (== N 2) (== (: 604) 1))
      (<>
       (text #:color 7 "【" 0 "】ははは、は・・・してない。")
       (wait)
       (text #:color 2 "【亜子】声が小さくて聞こえないわ。")
       (wait)
       (text #:color 7 "【" 0 "】してない。")
       (wait)
       (text #:color 2 "【亜子】もう一つ言っていいかしら・・・その時" 0 "君の服に、真子姉さんの髪の毛がついてたのよ。")
       (wait)
       (text #:color 7 "【" 0 "】え！？")
       (wait)
       (text #:color 2 "【亜子】どうして髪の毛までついてたの？")
       (wait)
       (text
        #:color
        7
        "【"
        0
        "】そ、それは・・・真子先生の髪が抜けやすい体質で、ちょうどその日は風が強くて、はらほれひれはれ。")
       (wait)
       (text #:color 2 "【亜子】" 0 "君、本気で疑ってる訳じゃないのに・・・" 0 "君がはっきり否定してくれないから。")
       (wait)
       (text #:color 7 "【" 0 "】ははは・・・。")
       (wait)
       (text #:color 2 "【亜子】はっきりしない" 0 "君って嫌いっ・・・もう一度、私の事を真剣に考えてから来てっ！！")
       (wait)
       (set-var A 15)
       (proc 12)
       (proc 11)
       (set-reg: 106 (- (: 106) 1))
       (set-var N 8)
       (slot 1 2)
       (mes-jump "town1.mes")))
    (if (&& (== N 2) (== (: 604) 0))
      (<>
       (text #:color 7 "【" 0 "】なんでそんな事を言うんだよ・・・俺の事がそんなに信じられないのか！？")
       (wait)
       (text #:color 2 "【亜子】だって・・真子姉さんってきれいだから。")
       (wait)))
    (text #:color 7 "【" 0 "】俺が好きなのは・・・亜子さんだけさ。")
    (wait)
    (text #:color 2 "【亜子】だって・・・まだ不安なんだもん。")
    (wait)
    (text #:color 7 "【" 0 "】ああ、じれったい・・・俺はちゃんと質問に答えたぞ。")
    (wait)
    (text #:color 2 "【亜子】" 0 "君、今日は帰って・・・私、また悩みそう。")
    (wait)
    (text #:color 7 "【" 0 "】帰れだあ！？・・・ここまでしつこく質問して帰れだとう！？")
    (wait)
    (text #:color 2 "【亜子】うん、帰って。")
    (wait)
    (text #:color 7 "【" 0 "】キスさせてくれたら・・・帰るよ。")
    (wait)
    (text #:color 2 "【亜子】・・・。")
    (wait)
    (text #:color 2 "【亜子】うん・・・キスして。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "t03.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 24)
    (set-arr~ @ 6 1)
    (image "t03an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "t03.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 29)
    (proc 26)
    (animate 0 8 0)
    (animate 4 8)
    (text #:color 2 "【亜子】んっ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 2 "【亜子】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 2 "【亜子】" 0 "君・・・だめ。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 2 "【亜子】いやあ・・・胸を触らないで。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 2 "【亜子】ち、ちょっと・・・どこをつまんでるの！？")
    (wait)
    (text #:color 7 "【" 0 "】乳首。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "t04.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 24)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "t05.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 25)
    (set-arr~ @ 6 1)
    (image "t04an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "t04.s4" (~ @ 2))
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 9)
    (proc 26)
    (animate 0 8 1)
    (animate 4 8)
    (text #:color 2 "【亜子】きゃあっ！！")
    (wait)
    (text #:color 7 "【" 0 "】亜子さんっ！！好きなんだようっ！！")
    (wait)
    (text #:color 6 "ドンッ！！")
    (wait)
    (set-var A 30)
    (proc 12)
    (proc 11)
    (slot 1 5)
    (mes-jump "t01.mes")))
 (set-arr~ @ 7 1))