(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\。
  #\っ
  #\い
  #\枚
  #\ん
  #\人
  #\、
  #\お
  #\な
  #\ま
  #\大
  #\０
  #\ば
  #\す
  #\さ
  #\１
  #\は
  #\だ
  #\で
  #\て
  #\ほ
  #\に
  #\る
  #\し
  #\り
  #\２
  #\た
  #\う
  #\か
  #\？
  #\ら
  #\ち
  #\れ
  #\あ
  #\円
  #\入
  #\よ
  #\を
  #\買
  #\く
  #\が
  #\そ
  #\君
  #\チ
  #\ケ
  #\ッ
  #\ト
  #\一
  #\わ
  #\と
  #\映
  #\の
  #\中
  #\も
  #\ゃ
  #\画
  #\ぜ
  #\売)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (while
  (== 1 1)
  (<>
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((&& (== V 135) (== (: 323) 1) (== (: 324) 0))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao39.pd8")
      (proc 15)
      (text #:color 2 "【おばさん】いらっしゃいませ・・・大人１枚１８００円、子供１枚１０００円になります。")
      (wait)
      (set-reg: 101 0)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "大人１枚") (text "大人２枚") (text "買わない")))
      (set-arr~ @ 7 1)
      (cond
       ((== N 1)
        (<>
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】大人１枚。")
         (wait)
         (text #:color 6 "【美穂】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】じゃなかった・・・大人２枚。")
         (wait)))
       ((== N 2)
        (<>
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】大人２枚・・・だな。")
         (wait)))
       ((== N 3)
        (<>
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】ただで入れてくれ。")
         (wait)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 2 "【おばさん】大人１００枚ですか？")
         (wait)
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】ただで入れてくれ。")
         (wait)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 2 "【おばさん】大人１億枚ですか？")
         (wait)
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】大人２枚だよ・・・ちっ。")
         (wait)))
       (else (<>)))
      (set-arr~ @ 13 28 48 65 127)
      (color 8)
      (clear)
      (text #:color 2 "【おばさん】大人２万枚ですね、ありがとうございます。")
      (wait)
      (set-arr~ @ 13 15 322 64 391)
      (color 8)
      (clear)
      (text #:color 7 "【" 0 "】２枚っ！！")
      (wait)
      (set-arr~ @ 13 28 48 65 127)
      (color 8)
      (clear)
      (text #:color 2 "【おばさん】ほほほっ、冗談ですよ・・・はい、大人２枚で１億４千万になります。")
      (wait)
      (set-arr~ @ 13 15 322 64 391)
      (color 8)
      (clear)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (set-arr~ @ 13 28 48 65 127)
      (color 8)
      (clear)
      (text #:color 2 "【おばさん】ほほほっ、冗談ですよ・・・大人２枚で３６００円ですね。")
      (wait)
      (set-var M (- M 3600))
      (proc 11)
      (set-arr~ @ 13 15 322 64 391)
      (color 8)
      (clear)
      (text #:color 6 "【美穂】" 0 "君、ありがとう。")
      (wait)
      (text #:color 7 "【" 0 "】いいって事よ・・・さてと、映画館の中に入ろうぜ。")
      (wait)
      (set-reg: 324 1)
      (slot 1 4)
      (mes-jump "eigain1.mes")))
    ((&& (== V 135) (== (: 465) 1) (== (: 471) 0))
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao39.pd8")
      (proc 15)
      (text #:color 2 "【おばさん】いらっしゃいませ・・・大人１枚１８００円、子供１枚１０００円になります。")
      (wait)
      (set-reg: 101 0)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "大人１枚") (text "大人２枚") (text "買わない")))
      (set-arr~ @ 7 1)
      (cond
       ((== N 1)
        (<>
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】大人１枚。")
         (wait)
         (text #:color 3 "【ちはる】" 0 "君のぶんも、出してあげるってば。")
         (wait)
         (text #:color 7 "【" 0 "】あ・・・そうか。")
         (wait)
         (text #:color 3 "【ちはる】大人２枚お願いします。")
         (wait)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 2 "【おばさん】２枚で３６００円になります・・・ちなみに、肉体関係はあります？")
         (wait)
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】黙れ、ババア。")
         (wait)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 2 "【おばさん】ほーっほっほっほっ。")
         (wait)
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 3 "【ちはる】" 0 "君、買ったわよ・・・早く中に入りましょ？")
         (wait)
         (text #:color 7 "【" 0 "】そうだな・・・映画館の中に入ろう。")
         (wait)))
       ((== N 2)
        (<>
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】大人２枚・・・だな。")
         (wait)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 2 "【おばさん】２枚で３６００円になります。")
         (wait)
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 3 "【ちはる】はい・・・" 0 "君、お金。")
         (wait)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 2 "【おばさん】ちなみに・・・肉体関係はあります？")
         (wait)
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】黙れ、ババア。")
         (wait)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 2 "【おばさん】ほーっほっほっほっ。")
         (wait)
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 3 "【ちはる】" 0 "君・・・チケットも買ったし、早く中に入りましょ？")
         (wait)
         (text #:color 7 "【" 0 "】そうだな・・・そうするか。")
         (wait)))
       ((== N 3)
        (<>
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】ただで入れてくれ。")
         (wait)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 2 "【おばさん】大人１００枚ですか？")
         (wait)
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】ただで入れてくれ。")
         (wait)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 2 "【おばさん】大人１億枚ですか？")
         (wait)
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】大人２枚だよ・・・ちっ。")
         (wait)
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 3 "【ちはる】はい・・・" 0 "君、お金。")
         (wait)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 2 "【おばさん】ありがとうございました。")
         (wait)
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 3 "【ちはる】" 0 "君・・・チケットも買ったし、早く中に入りましょ？")
         (wait)
         (text #:color 7 "【" 0 "】そうだな、そうするか・・・。")
         (wait)))
       (else (<>)))
      (set-reg: 471 1)
      (slot 1 5)
      (mes-jump "eigain2.mes")))
    ((&& (== V 135) (> T 0) (< T 600))
     (<>
      (text #:color 7 "【" 0 "】チケット売場はしまっている・・・こんな時間に、チケットを売っていたら逆に恐いぜ。")
      (wait)
      (break)))
    ((&& (== V 135) (== T 0) (< T 600))
     (<>
      (text #:color 7 "【" 0 "】チケット売場はしまっている・・・こんな時間に、チケットを売っていたら逆に恐いぜ。")
      (wait)
      (break)))
    ((&& (== V 135) (> T 1859) (< T 2359))
     (<>
      (text #:color 7 "【" 0 "】チケット売場はしまっている・・・もう上映時間を過ぎているからな、閉まっていて当然だぜ。")
      (wait)
      (break)))
    ((== V 135)
     (<>
      (proc 19)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "kao39.pd8")
      (proc 15)
      (text #:color 2 "【おばさん】いらっしゃいませ・・・大人１枚１８００円、子供１枚１０００円になります。")
      (wait)
      (set-reg: 101 0)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "大人１枚") (text "大人２枚") (text "買わない")))
      (set-arr~ @ 7 1)
      (cond
       ((&& (== N 1) (== (: 205) 0))
        (<>
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】だからあ・・・俺は一人で映画を見るつもりはないぞ。")
         (wait)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 2 "【おばさん】大人１万枚ですね、ありがとうございます。")
         (wait)
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】誰がそんな事を言ったんだよ。")
         (wait)
         (set-reg: 205 1)))
       ((&& (== N 1) (== (: 205) 1))
        (<>
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】一人で映画を見るくらいだったら、自分の部屋で寝てた方がマシだ。")
         (wait)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 2 "【おばさん】一緒に寝ましょうか？")
         (wait)
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】映画を見てた方がマシだ。")
         (wait)))
       ((&& (== N 2) (== (: 206) 0))
        (<>
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】２枚って・・・俺は一人だぜ。")
         (wait)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 2 "【おばさん】ほほほ、私とご一緒します？")
         (wait)
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】おばはん、仕事中だろう？")
         (wait)
         (set-reg: 206 1)))
       ((&& (== N 2) (== (: 206) 1))
        (<>
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】だからあ、俺は一人だって。")
         (wait)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 2 "【おばさん】私がいるじゃない・・・ほほほほ。")
         (wait)
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】絶対に一人だ。")
         (wait)))
       ((&& (== N 3) (== (: 207) 0))
        (<>
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】はっはっはっ、単なる冷やかしです。")
         (wait)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 2 "【おばさん】今度そんな事をしたら、身体で払ってもらうわよ。")
         (wait)
         (set-reg: 207 1)))
       ((&& (== N 3) (== (: 207) 1))
        (<>
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (set-arr~ @ 13 28 48 65 127)
         (color 8)
         (clear)
         (text #:color 2 "【おばさん】何を黙ってるのよ・・・買わないの？")
         (wait)
         (set-arr~ @ 13 15 322 64 391)
         (color 8)
         (clear)
         (text #:color 7 "【" 0 "】買いません。")
         (wait)))
       (else (<>)))
      (break)))
    (else (<>)))))
 (set-arr~ @ 7 1))