(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\い
  #\【
  #\】
  #\と
  #\な
  #\。
  #\さ
  #\て
  #\っ
  #\、
  #\み
  #\の
  #\だ
  #\か
  #\る
  #\よ
  #\ん
  #\は
  #\し
  #\に
  #\が
  #\ら
  #\う
  #\あ
  #\た
  #\？
  #\ー
  #\を
  #\も
  #\で
  #\ゃ
  #\わ
  #\く
  #\ね
  #\ち
  #\れ
  #\こ
  #\！
  #\じ
  #\り
  #\え
  #\お
  #\ま
  #\そ
  #\け
  #\事
  #\や
  #\き
  #\ど
  #\ス
  #\０
  #\言
  #\何
  #\俺
  #\つ
  #\女
  #\ょ
  #\私
  #\人
  #\す
  #\店
  #\気
  #\イ
  #\ろ
  #\子
  #\ト
  #\来
  #\ぜ
  #\一
  #\マ
  #\ば
  #\出
  #\ア
  #\め
  #\コ
  #\見
  #\円
  #\悪
  #\ル
  #\茶
  #\入
  #\タ
  #\ヒ
  #\ふ
  #\ほ
  #\金
  #\払
  #\待
  #\変
  #\へ
  #\喫
  #\時
  #\前
  #\大
  #\聞
  #\方
  #\文
  #\休
  #\男
  #\せ
  #\間
  #\今
  #\ッ
  #\ツ
  #\ず
  #\レ
  #\げ
  #\思
  #\度
  #\合
  #\別
  #\ン
  #\仕
  #\む
  #\日
  #\バ
  #\学
  #\分
  #\ケ
  #\４
  #\自
  #\誰
  #\注
  #\話
  #\ご
  #\物
  #\相)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "30.pd8")
 (proc 15)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "30an.pd8")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 0)
 (load "30.s4" (~ @ 2))
 (animate 0 0 0)
 (animate 1 0)
 (set-arr~ @ 7 0)
 (if (== (: 835) 0) (<> (sound 1) (set-var I 50) (proc 26) (set-reg: 835 1)))
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (set-reg: 179 0)
 (cond
  ((&& (== (: 177) 0) (< H 817))
   (<>
    (text #:color 7 "【" 0 "】ふう・・・涼しいぜ。")
    (wait)
    (text #:color 7 "【" 0 "】どうせだったら、パンツ一枚になって涼んでやろうかな・・・なーに、誰も見ちゃいないさ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text
     #:color
     6
     "【さとみ】最近姿を見ないと思ったら、いきなりパンツ一枚になるですって？・・・"
     0
     "は、相変わらず下品が服を来ているわね。")
    (wait)
    (text #:color 7 "【" 0 "】ぎょっ！！・・・ど、どこから湧き出て来たんだ！？")
    (wait)
    (text #:color 6 "【さとみ】失礼な、こうやって注文を取りに来てやったんじゃない・・・ありがたく思ってよ。")
    (wait)
    (text
     #:color
     7
     "【"
     0
     "】さとみよう、接客態度が悪いぞ・・・だいたい、客とテーブルの間に立つウェイトレスがどこにいると言うんだ。")
    (wait)
    (text #:color 6 "【さとみ】" 0 "が、こんな端っこの席に座るからいけないのよ・・・あーあ、注文が取りにくい場所だわ。")
    (wait)
    (text #:color 7 "【" 0 "】右に回れ、右側に・・・そのまま座ると、俺様の膝の上に乗る事になるぞ。")
    (wait)
    (text #:color 6 "【さとみ】やだやだ・・・" 0 "の膝の上に座ったら、子供ができちゃうもん。")
    (wait)
    (text #:color 7 "【" 0 "】へっへっへっ、本当は俺の子供が欲しいくせに・・・なんだったら、ここで仕込んでやろうか？")
    (wait)
    (text #:color 6 "【さとみ】くだらない事を言ってないで、とっとと注文を言ってよ・・・『水』だなんて言ったらたたいちゃうから。")
    (wait)))
  ((&& (== (: 177) 1) (== (: 178) 0) (< H 817))
   (<>
    (text #:color 7 "【" 0 "】うーん、涼しくて気持ちがいいな・・・これでさとみがいなかったら、ベスト・オブ・ザ・喫茶店なのにな。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】何がベスト・オブよ・・・" 0 "が喫茶店に来ると、周りの空気が不謹慎になっていけないわ。")
    (wait)
    (text #:color 7 "【" 0 "】俺様とテーブルの間に立つな！！・・・周りの客が見たら、ただならぬ関係だと思われるぞ。")
    (wait)
    (text
     #:color
     6
     "【さとみ】ははははは・・・私みたいに上品な顔をした女性が、"
     0
     "なんかと『ただならぬ関係』なんて思われる訳がないじゃない。")
    (wait)
    (text #:color 7 "【" 0 "】あのなあ、それが客に対する態度か？・・・時給を減らすぞ。")
    (wait)
    (text #:color 6 "【さとみ】この店は私の美貌でもっているんのよ・・・私の時給が上がる事はあっても、下がる事は絶対になーい。")
    (wait)
    (set-reg: 178 1)))
  ((&& (== (: 178) 1) (== (: 182) 0) (< H 817))
   (<>
    (text #:color 7 "【" 0 "】さとみのやつが間に入れないように・・・椅子を前にずらして・・・と。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】よいしょっ・・・と。")
    (wait)
    (text #:color 7 "【" 0 "】いててててっ！！む、無理に身体を入れるなっ！！")
    (wait)
    (text #:color 6 "【さとみ】あ・・・悪い、悪い、痛かった？")
    (wait)
    (text #:color 6 "【さとみ】私のふとももで感じちゃった？・・・" 0 "は幸せなやつよねえ。")
    (wait)
    (text #:color 7 "【" 0 "】なんて乱暴な女なんだ・・・とっとと注文をとって、あっちに行ってくれ。")
    (wait)
    (text #:color 6 "【さとみ】あーあ、心にもない事を言っちゃて・・・今日はいったい何を頼むの？・・・砂糖水？")
    (wait)
    (text #:color 7 "【" 0 "】俺はアリじゃないぞ。")
    (wait)))
  ((&& (== (: 182) 1) (== (: 265) 0) (< H 817))
   (<>
    (text #:color 7 "【" 0 "】さとみのやつが間に入れないように・・・椅子を前にずらして・・・と。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】よいしょっ・・・と。")
    (wait)
    (text #:color 7 "【" 0 "】いててててっ！！む、無理に身体を入れるなっ！！")
    (wait)
    (text #:color 6 "【さとみ】ははは、私の身体と密着できてうれしいでしょ？")
    (wait)
    (text #:color 7 "【" 0 "】なんて乱暴な女なんだ・・・とっとと注文をとって、あっちに行ってくれ。")
    (wait)
    (text #:color 6 "【さとみ】あーあ、心にもない事を言っちゃて・・・今日はいったい何を頼むの？・・・塩水？")
    (wait)))
  ((&& (== (: 265) 1) (== (: 269) 0) (< H 817))
   (<>
    (text #:color 7 "【" 0 "】ふう・・・。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】" 0 "・・・駄目よ、女の子をだましちゃ。")
    (wait)
    (text #:color 7 "【" 0 "】誰がだましてるんだよっ！！")
    (wait)
    (text #:color 6 "【さとみ】" 0 "と一緒に来た女の子・・・なかなかかわいい子だったわね、" 0 "には似合わないと思うけど。")
    (wait)
    (text #:color 7 "【" 0 "】ふふん、大きなお世話さ！！")
    (wait)
    (set-reg: 269 1)))
  ((&& (== (: 321) 1) (== (: 322) 0) (< H 817))
   (<>
    (text #:color 7 "【" 0 "】えーと・・・さとみはどこかな？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】ご指名ありがとうございます・・・料金に１０パーセント加算されますが、よろしいですか？")
    (wait)
    (text #:color 7 "【" 0 "】バカな事を言ってるなよ・・・それよりさとみ、最近何か変わった事があったのか？")
    (wait)
    (text #:color 6 "【さとみ】何よ、いきなり・・・何もないわよ。")
    (wait)
    (text #:color 7 "【" 0 "】本当に？")
    (wait)
    (text #:color 6 "【さとみ】本当にって・・・どうしてそんな事を聞くの？")
    (wait)
    (text #:color 7 "【" 0 "】いや、何か相談事があったら・・・俺が聞いてやるぜ。")
    (wait)
    (text #:color 6 "【さとみ】はははっ・・・" 0 "に相談したら、まとまる話もまとまらなくなっちゃうわよ。")
    (wait)
    (set-reg: 322 1)))
  ((&& (== (: 182) 1) (< H 811) (< H 817))
   (<>
    (text #:color 7 "【" 0 "】この場所が俺様のお気に入りなんだ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】またこの席に座るの？")
    (wait)
    (text #:color 7 "【" 0 "】あのなあ、何度も言うがいきなり出て来るなよ。")
    (wait)
    (text #:color 6 "【さとみ】ここは私が仕切ってる店なのよ、気に入らないなら・・・お金だけ払って出てって。")
    (wait)
    (text #:color 7 "【" 0 "】ひっどい事を言うな。")
    (wait)))
  ((&& (> H 811) (== (: 262) 0) (< H 817))
   (<>
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あれれ！？・・・さとみは休みなのかな？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】私が休む時は、この店も休みになる時よ。")
    (wait)
    (text #:color 7 "【" 0 "】さとみ、先負学園を退学して、この店のチイママになったらどうだ？")
    (wait)
    (text #:color 6 "【さとみ】お断りだわ・・・ここでの仕事はアルバイトよ、それ以上でも以下でもないわ。")
    (wait)
    (set-reg: 262 1)))
  ((&& (== (: 262) 1) (< H 817))
   (<>
    (text #:color 7 "【" 0 "】さとみー・・・" 0 "様が来たぞっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】ちょっとお、気安く呼ばないでよ・・・ここは喫茶店なんだから。")
    (wait)))
  ((&& (== (: 412) 0) (> H 816) (== (: 419) 0))
   (<>
    (text #:color 7 "【" 0 "】おーい、さとみっ！！")
    (wait)
    (text #:color 4 "【マスター】" 0 "ちゃん、いらっしゃい。")
    (wait)
    (text #:color 7 "【" 0 "】（げっ！！・・・大仏頭！？）")
    (wait)
    (text #:color 4 "【マスター】さとみちゃんねえ、具合が悪いらしくて・・・しばらくお店を休むって言うのよお、まったく困っちゃうわあ。")
    (wait)
    (text #:color 7 "【" 0 "】さとみが休んでいる？・・・めずらしい事もあるんだな。")
    (wait)
    (text #:color 4 "【マスター】おかげで私がお店に出るはめになっちゃって・・・早くさとみちゃん、出て来てくれないかしらあ。")
    (wait)
    (text #:color 4 "【マスター】あ、ごめんなさいね・・・" 0 "ちゃん、何にする？")
    (wait)
    (text #:color 7 "【" 0 "】何でもいいよ。")
    (wait)
    (text #:color 4 "【マスター】じゃあ、特製のコーヒーを入れるわね・・・ちょっと待ってて。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】（さとみが喫茶店を休むなんて・・・よっぽどの事だよなあ。）")
    (wait)
    (text #:color 4 "【マスター】お待たせ、" 0 "ちゃん・・・ゆっくりしてってね。")
    (wait)
    (set-arr~ @ 7 0)
    (load "30.a6" 47104)
    (set-reg: 412 1)
    (set-reg: 179 1)))
  ((&& (== (: 412) 1) (== (: 413) 0) (== (: 419) 0))
   (<>
    (text #:color 4 "【マスター】いらっしゃあい・・・あら、" 0 "ちゃんじゃない。")
    (wait)
    (text #:color 7 "【" 0 "】さとみは？")
    (wait)
    (text #:color 4 "【マスター】まだ出て来ないのよお・・・" 0 "ちゃん、何とかして。")
    (wait)
    (text #:color 7 "【" 0 "】何とかしてって言われても・・・。")
    (wait)
    (text #:color 4 "【マスター】今日も特製のコーヒーを入れてあげる・・・ちょっと待ってて。")
    (wait)
    (text #:color 7 "【" 0 "】（さとみのやつ・・・どうしたのかなあ？）")
    (wait)
    (text #:color 4 "【マスター】お、ま、た、せ・・・熱いから気をつけてね。")
    (wait)
    (set-arr~ @ 7 0)
    (load "30.a6" 47104)
    (set-reg: 179 1)))
  ((&& (== (: 413) 1) (== (: 419) 0))
   (<>
    (text #:color 4 "【マスター】いらっしゃあい・・・あら、" 0 "ちゃん、また来てくれたのお？")
    (wait)
    (text #:color 7 "【" 0 "】（あれれ！？・・・さとみのやつ、まだ出て来てないんだ。）")
    (wait)
    (text #:color 4 "【マスター】さとみちゃん？・・・まだ出て来てないわよお。")
    (wait)
    (text #:color 4 "【マスター】今日は特別おいしいコーヒーを入れてあげる・・・いつもの席に座って待っててね。")
    (wait)
    (text #:color 7 "【" 0 "】（さとみ・・・まだ悩んでいるのか？）")
    (wait)
    (text #:color 4 "【マスター】はーい、おまたせ・・・熱いから、ふーふーして飲んでね。")
    (wait)
    (set-arr~ @ 7 0)
    (load "30.a6" 47104)
    (set-reg: 179 1)))
  ((&& (== (: 419) 1) (== (: 420) 0) (== (: 423) 0))
   (<>
    (text #:color 7 "【" 0 "】さとみは・・・いるかな？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】心配しないで・・・ちゃんといるわよ。")
    (wait)
    (text #:color 7 "【" 0 "】へえ、けっこう元気そうじゃないか。")
    (wait)
    (text #:color 6 "【さとみ】" 0 "のおかげ・・・かな？")
    (wait)
    (text #:color 6 "【さとみ】そんな事より、" 0 "・・・何を飲む？")
    (wait)
    (set-reg: 423 1)))
  ((&& (== (: 419) 1) (== (: 420) 1) (== (: 423) 0))
   (<>
    (text #:color 7 "【" 0 "】さとみは・・・いるかな？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】心配しないで・・・ちゃんといるわよ。")
    (wait)
    (text #:color 7 "【" 0 "】へえ、けっこう元気そうじゃないか。")
    (wait)
    (text #:color 6 "【さとみ】・・・。")
    (wait)
    (text #:color 6 "【さとみ】やっぱり・・・ちょっと恥ずかしいわね。")
    (wait)
    (text #:color 7 "【" 0 "】同感だ。")
    (wait)
    (set-reg: 423 1)))
  ((&& (== (: 423) 1) (< H 822))
   (<>
    (text #:color 7 "【" 0 "】さとみ・・・真面目に働いてるかい！？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】もう、大きな声を出さないでよ。")
    (wait)
    (text #:color 7 "【" 0 "】真面目に働いて、俺に貢いでくれるんだろ？")
    (wait)
    (text #:color 6 "【さとみ】" 0 "の冗談って、たまーに冗談に聞こえないのよね。")
    (wait)))
  ((&& (== (: 423) 1) (== H 822))
   (<>
    (text #:color 7 "【" 0 "】さとみ、隠れてるのはわかってるんだ・・・出てこいっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】あのねえ・・・私は喫茶店にたてこもった犯人なの？")
    (wait)
    (text #:color 7 "【" 0 "】ははは、出てきたな。")
    (wait)
    (text #:color 6 "【さとみ】" 0 "の冗談って、たまーに冗談に聞こえないのよね。")
    (wait)))
  ((&& (== (: 423) 1) (== H 823))
   (<>
    (text #:color 7 "【" 0 "】さとみっ！！・・・愛してるよっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】ば、馬鹿・・・恥ずかしいじゃない。")
    (wait)
    (text #:color 7 "【" 0 "】照れるなよ、俺とさとみの間柄で。")
    (wait)
    (text #:color 6 "【さとみ】もう・・・馬鹿。")
    (wait)
    (text #:color 7 "【" 0 "】せめて『アホ』にしてくれ。")))
  ((&& (== (: 423) 1) (== H 824))
   (<>
    (text #:color 7 "【" 0 "】ああ・・・セックスがしたいなあ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】こらっ！！" 0 "っ！！")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・セックスと言ったら、さとみが出てきた。")
    (wait)
    (text #:color 6 "【さとみ】大声で変な事を言わないでよ・・・他のお客さんの迷惑だわ。")
    (wait)))
  ((&& (== (: 423) 1) (== H 825))
   (<>
    (text #:color 7 "【" 0 "】うっ・・・ど、毒が身体に回ってきたあ！！")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あれ？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】" 0 "・・・注文もしないで、よくそんな事が言えるわね。")
    (wait)
    (text #:color 7 "【" 0 "】はは、さとみを呼ぶ為に言ったんだ・・・この店は何も言わないと水も出ないからな。")
    (wait)
    (text #:color 6 "【さとみ】それはね、" 0 "だけよ。")
    (wait)))
  ((&& (== (: 423) 1) (== H 826))
   (<>
    (text #:color 7 "【" 0 "】さとみっ！！さとみっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】いいかげんにして・・・営業妨害だわ。")
    (wait)
    (text #:color 7 "【" 0 "】どうしてだよう・・・名前を呼んだだけだろ？")
    (wait)
    (text #:color 6 "【さとみ】" 0 "の声が下品ですもの・・・だから営業妨害なの。")
    (wait)))
  ((&& (== (: 423) 1) (== H 827))
   (<>
    (text #:color 7 "【" 0 "】あーあ・・・退屈だなあ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】" 0 "、私が話相手になってあげるわよ。")
    (wait)
    (text #:color 7 "【" 0 "】いやあ、さとみは優しいなあ・・・いいお嫁さんになれるぜ。")
    (wait)
    (text #:color 6 "【さとみ】１０分、３０００円でどう？・・・ちょっと安すぎるかしら？")
    (wait)
    (text #:color 7 "【" 0 "】一生、結婚できない身体にしてやる・・・。")
    (wait)))
  ((&& (== (: 423) 1) (== H 828))
   (<>
    (text #:color 7 "【" 0 "】あーあ・・・もう８月２８日だよ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】" 0 "、宿題はやった？")
    (wait)
    (text #:color 7 "【" 0 "】俺に聞くだけ時間の無駄だ・・・ははは。")
    (wait)
    (text #:color 6 "【さとみ】" 0 "、最後の夏休みなんだから、宿題ぐらいちゃんとやりなさい。")
    (wait)))
  ((&& (== (: 423) 1) (== H 829))
   (<>
    (text #:color 7 "【" 0 "】うーん・・・喫茶店でお茶を飲んでて、俺はいいのだろうか？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】" 0 "、何か悩みがありそうね・・・私に相談してもいいわよ。")
    (wait)
    (text #:color 7 "【" 0 "】やだよ、お金を取りそうだから。")
    (wait)
    (text #:color 6 "【さとみ】やだ、領収書を持ってきた事・・・どうしてわかったの？")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)))
  ((&& (== (: 423) 1) (> H 829))
   (<>
    (text #:color 7 "【" 0 "】ふあああ・・・ああ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (set-arr~ @ 7 0)
    (load "30a.a6" 47104)
    (text #:color 6 "【さとみ】" 0 "、あくびをしながら入ってこないでよ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】いいじゃないかよう、俺はこれでも客だぜ・・・あくびをしようが、唄いながら入ってこようが俺の勝手だ。")
    (wait)
    (text #:color 6 "【さとみ】じゃあ皿洗いをしながら床の掃除をして、出て行くっていうのは・・・どう？")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait))))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show
       (<.>
        (text "外に出る")
        (if (&& (== (: 179) 0) (== (: 412) 0)) (text "注文をする"))
        (if (&& (== (: 179) 0) (== (: 419) 1)) (text "注文をする"))
        (text "やめる")))
      (cond
       ((&& (== N 1) (== (: 179) 0) (< H 817))
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・帰ろうっと。")
         (wait)
         (text #:color 6 "【さとみ】あ、何も頼まないで帰る気なの？・・・" 0 "、ここは涼みに来る場所じゃないのよ。")
         (wait)
         (text #:color 7 "【" 0 "】ははは、俺様の顔が見れただけでも幸せだと思うんだな・・・じゃあな！！")
         (wait)
         (text #:color 6 "【さとみ】こらっ！！待てっ！！・・・冷房泥棒よっ！！")
         (wait)
         (set-var N 9)
         (set-reg: 177 1)
         (set-reg: 175 1)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 1) (== (: 179) 1) (< H 817))
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・ここでゆっくりお茶をしている場合じゃないか。")
         (wait)
         (text #:color 7 "【" 0 "】だいたい一人で喫茶店に来るなんて・・・退屈以外の何ものでもないぞ。")
         (wait)
         (text #:color 6 "【さとみ】どうもありがとうございましたー！！")
         (wait)
         (text #:color 7 "【" 0 "】ちぇっ、わざとらしい事を言う女だぜ・・・。")
         (wait)
         (set-var N 9)
         (set-reg: 177 1)
         (set-reg: 175 1)
         (set-reg: 179 0)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 1) (> H 816) (== (: 413) 0) (== (: 419) 0))
        (<>
         (text #:color 7 "【" 0 "】えーと・・・コーヒーはいくらだっけ？")
         (wait)
         (text #:color 4 "【マスター】いいのよお、" 0 "ちゃんは特別なんだから・・・ツケておくわよ。")
         (wait)
         (text #:color 7 "【" 0 "】ははは・・・。")
         (wait)
         (text #:color 4 "【マスター】また来てね・・・気をつけて帰るのよお。")
         (wait)
         (set-var N 9)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 1) (> H 816) (== (: 413) 1) (== (: 419) 0))
        (<>
         (text #:color 4 "【マスター】" 0 "ちゃん、今日もツケといてあげる・・・。")
         (wait)
         (text #:color 7 "【" 0 "】ははは・・・どうも。")
         (wait)
         (text #:color 4 "【マスター】また来てね・・・気をつけて帰るのよお。")
         (wait)
         (set-var N 9)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 1) (== (: 419) 1) (== (: 179) 0))
        (<>
         (text #:color 7 "【" 0 "】さてと・・・帰ろうかな。")
         (wait)
         (text #:color 6 "【さとみ】帰ろうかなって、まだ何も注文してないじゃない。")
         (wait)
         (text #:color 7 "【" 0 "】ははは・・・悪いな、涼しかったぜ。")
         (wait)
         (set-var N 9)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 1) (== (: 419) 1) (== (: 179) 1))
        (<>
         (text #:color 7 "【" 0 "】さてと・・・帰ろうかな。")
         (wait)
         (text #:color 6 "【さとみ】ありがとうございましたー！！")
         (wait)
         (set-var N 9)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 2) (< H 817))
        (<>
         (text #:color 6 "【さとみ】" 0 "、何を頼むの？")
         (wait)
         (set-reg: 101 1)
         (proc 18)
         (menu-show
          (<.>
           (text "水")
           (text "コーヒー")
           (text "アイスコーヒー")
           (text "ジュース")
           (text "パフェ")
           (text "フルコース")))
         (cond
          ((== N 1) (<> (text #:color 6 "【さとみ】水！？・・・" 0 "、ふざけているの？") (wait)))
          ((&& (== N 2) (== (: 180) 0))
           (<>
            (text
             #:color
             6
             "【さとみ】"
             0
             "、コーヒーは身体に悪いわよ・・・特に"
             0
             "は砂糖を山のように入れるからね。")
            (wait)
            (text #:color 7 "【" 0 "】大きなお世話だよ・・・俺はコーヒーが飲みたいんだ。")
            (wait)
            (text #:color 6 "【さとみ】仕方がないなあ・・・ちょっと待ってて。")
            (wait)
            (set-arr~ @ 7 1)
            (set-arr~ @ 1 4096)
            (set-arr~ @ 6 1)
            (image "30.pd8")
            (proc 15)
            (set-arr~ @ 7 1)
            (set-arr~ @ 1 4096)
            (set-arr~ @ 6 1)
            (image "30an.pd8")
            (set-arr~ @ 6 0)
            (set-arr~ @ 7 0)
            (load "30.s4" (~ @ 2))
            (animate 0 0 0)
            (animate 1 0)
            (set-arr~ @ 7 0)
            (set-arr~ @ 7 0)
            (load "30.a6" 47104)
            (text #:color 7 "【" 0 "】・・・。")
            (wait)
            (text #:color 7 "【" 0 "】・・・。")
            (wait)
            (text #:color 6 "【さとみ】はい、ホットコーヒーお待ちー・・・４００円になります。")
            (wait)
            (text #:color 7 "【" 0 "】ホットコーヒーお待ちって、どこにコーヒーがあるんだよ。")
            (wait)
            (text #:color 6 "【さとみ】自分の目の前にあるじゃない・・・視界に入ってないだけでしょ？")
            (wait)
            (text #:color 7 "【" 0 "】あ・・・本当だ。")
            (wait)
            (text #:color 6 "【さとみ】それより４００円よ・・・早く払って。")
            (wait)
            (text #:color 7 "【" 0 "】４００円！？・・・相変わらず暴利をむさぼっているなあ。")
            (wait)
            (text #:color 6 "【さとみ】文句があるなら、店長を呼ぶわよー・・・言っておくけど、店長は大仏頭だなんだから。")
            (wait)
            (text #:color 7 "【" 0 "】いい、いい、呼ばなくていい・・・気持ち悪いんだよ、あのオッサンは。")
            (wait)
            (text #:color 6 "【さとみ】" 0 "、４００円だって言ってるじゃない・・・ほら、早く払ってよ。")
            (wait)
            (text #:color 7 "【" 0 "】払うって・・・今ここで払うのか？")
            (wait)
            (text #:color 6 "【さとみ】" 0 "は先負町一の危険人物だからねー、" 0 "だけは物々交換よ。")
            (wait)
            (cond
             ((< M 400)
              (<>
               (text #:color 7 "【" 0 "】ひっでえ差別・・・ほら、払えばいいんだろ。")
               (wait)
               (text #:color 7 "【" 0 "】・・・。")
               (wait)
               (text #:color 7 "【" 0 "】あれれ！？・・・お金が足りない。")
               (wait)
               (text #:color 6 "【さとみ】いい根性してるわね・・・仕方がないわ、ツケとくからあり金全部よこしなさいよ。")
               (wait)
               (set-var M 0)
               (proc 11)))
             ((> M 399)
              (<>
               (text #:color 7 "【" 0 "】ひっでえ差別・・・ほら、払えばいいんだろ。")
               (wait)
               (set-var M (- M 400))
               (proc 11)
               (text #:color 6 "【さとみ】ははは、毎度ありがとうございまーす・・・飲んだらとっとと帰ってね。")
               (wait)))
             (else (<>)))
            (text #:color 7 "【" 0 "】まったく・・・なんちゅー喫茶店だ。")
            (wait)
            (set-reg: 180 1)
            (set-reg: 179 1)))
          ((&& (== N 2) (== (: 180) 1))
           (<>
            (text #:color 6 "【さとみ】コーヒーか・・・ちょっと待ってて。")
            (wait)
            (set-arr~ @ 7 1)
            (set-arr~ @ 1 4096)
            (set-arr~ @ 6 1)
            (image "30.pd8")
            (proc 15)
            (set-arr~ @ 7 1)
            (set-arr~ @ 1 4096)
            (set-arr~ @ 6 1)
            (image "30an.pd8")
            (set-arr~ @ 6 0)
            (set-arr~ @ 7 0)
            (load "30.s4" (~ @ 2))
            (animate 0 0 0)
            (animate 1 0)
            (set-arr~ @ 7 0)
            (set-arr~ @ 7 0)
            (load "30.a6" 47104)
            (text #:color 7 "【" 0 "】・・・。")
            (wait)
            (text #:color 7 "【" 0 "】・・・。")
            (wait)
            (text #:color 6 "【さとみ】はい、ホットコーヒーお待ちー・・・砂糖をあまり入れないでね、もったいないから。")
            (wait)
            (cond
             ((< M 400)
              (<>
               (text #:color 7 "【" 0 "】わかった、わかった・・・ほら４００円。")
               (wait)
               (text #:color 7 "【" 0 "】・・・。")
               (wait)
               (text #:color 7 "【" 0 "】あれれ！？・・・お金が足りない。")
               (wait)
               (text #:color 6 "【さとみ】いい根性してるわね・・・仕方がないわ、ツケとくからあり金全部よこしなさいよ。")
               (wait)
               (set-var M 0)
               (proc 11)))
             ((> M 399)
              (<>
               (text #:color 7 "【" 0 "】わかった、わかった・・・ほら４００円。")
               (wait)
               (set-var M (- M 400))
               (proc 11)
               (text
                #:color
                6
                "【さとみ】コーヒー一杯で何時間も粘っちゃだめよ・・・喫茶店は、客の回転率で利益が決るんだから。")
               (wait)))
             (else (<>)))
            (text #:color 7 "【" 0 "】しっしっ、しーーーっ！！")
            (wait)
            (set-reg: 179 1)))
          ((&& (== N 3) (== (: 180) 0))
           (<>
            (text #:color 6 "【さとみ】" 0 "、忘れたの？・・・以前アイスコーヒーを飲んで、下痢ピーになったじゃない。")
            (wait)
            (text #:color 7 "【" 0 "】大きなお世話だよ・・・俺はアイスコーヒーが飲みたいんだ。")
            (wait)
            (text #:color 6 "【さとみ】仕方がないなあ・・・ちょっと待ってて。")
            (wait)
            (set-arr~ @ 7 1)
            (set-arr~ @ 1 4096)
            (set-arr~ @ 6 1)
            (image "30.pd8")
            (proc 15)
            (set-arr~ @ 7 1)
            (set-arr~ @ 1 4096)
            (set-arr~ @ 6 1)
            (image "30an.pd8")
            (set-arr~ @ 6 0)
            (set-arr~ @ 7 0)
            (load "30.s4" (~ @ 2))
            (animate 0 0 0)
            (animate 1 0)
            (set-arr~ @ 7 0)
            (set-arr~ @ 7 0)
            (load "30.a6" 47104)
            (text #:color 7 "【" 0 "】・・・。")
            (wait)
            (text #:color 7 "【" 0 "】・・・。")
            (wait)
            (text #:color 6 "【さとみ】はい、お待ちー・・・４００円になります。")
            (wait)
            (text #:color 7 "【" 0 "】お待ちって、どこにアイスコーヒーがあるんだよ。")
            (wait)
            (text #:color 6 "【さとみ】自分の目の前にあるじゃない・・・視界に入ってないだけでしょ？")
            (wait)
            (text #:color 7 "【" 0 "】あ・・・本当だ。")
            (wait)
            (text #:color 6 "【さとみ】それより４００円よ・・・早く払って。")
            (wait)
            (text #:color 7 "【" 0 "】４００円！？・・・相変わらず暴利をむさぼっているなあ。")
            (wait)
            (text #:color 6 "【さとみ】文句があるなら、店長を呼ぶわよー・・・言っておくけど、店長は大仏頭なんだから。")
            (wait)
            (text #:color 7 "【" 0 "】いい、いい、呼ばなくていい・・・気持ち悪いんだよ、あのマスターは。")
            (wait)
            (text #:color 6 "【さとみ】" 0 "、４００円だって言ってるじゃない・・・ほら、早く払って。")
            (wait)
            (text #:color 7 "【" 0 "】払うって・・・今ここで払うのか？")
            (wait)
            (text #:color 6 "【さとみ】" 0 "は先負町一の危険人物だからねー、" 0 "だけは物々交換よ。")
            (wait)
            (cond
             ((< M 400)
              (<>
               (text #:color 7 "【" 0 "】ひっでえ差別・・・ほら、払えばいいんだろ。")
               (wait)
               (text #:color 7 "【" 0 "】・・・。")
               (wait)
               (text #:color 7 "【" 0 "】あれれ！？・・・お金が足りない。")
               (wait)
               (text #:color 6 "【さとみ】いい根性してるわね・・・仕方がないわ、ツケとくからあり金全部よこしなさいよ。")
               (wait)
               (set-var M 0)
               (proc 11)))
             ((> M 399)
              (<>
               (text #:color 7 "【" 0 "】ひっでえ差別・・・ほら、払えばいいんだろ。")
               (wait)
               (set-var M (- M 400))
               (proc 11)
               (text #:color 6 "【さとみ】ははは、毎度ありがとうございまーす・・・飲んだらとっとと帰ってね。")
               (wait)))
             (else (<>)))
            (text #:color 7 "【" 0 "】まったく・・・なんちゅー喫茶店だ。")
            (wait)
            (set-reg: 180 1)
            (set-reg: 179 1)))
          ((&& (== N 3) (== (: 180) 1))
           (<>
            (text #:color 6 "【さとみ】アイスコーヒーか・・・ちょっと待ってて。")
            (wait)
            (set-arr~ @ 7 1)
            (set-arr~ @ 1 4096)
            (set-arr~ @ 6 1)
            (image "30.pd8")
            (proc 15)
            (set-arr~ @ 7 1)
            (set-arr~ @ 1 4096)
            (set-arr~ @ 6 1)
            (image "30an.pd8")
            (set-arr~ @ 6 0)
            (set-arr~ @ 7 0)
            (load "30.s4" (~ @ 2))
            (animate 0 0 0)
            (animate 1 0)
            (set-arr~ @ 7 0)
            (set-arr~ @ 7 0)
            (load "30.a6" 47104)
            (text #:color 7 "【" 0 "】・・・。")
            (wait)
            (text #:color 7 "【" 0 "】・・・。")
            (wait)
            (text #:color 6 "【さとみ】はい、アイスコーヒーお待ちー・・・一気に飲んで下痢ピーにならないでね。")
            (wait)
            (cond
             ((< M 400)
              (<>
               (text #:color 7 "【" 0 "】あの時は、たまたま腹の調子が悪かったんだよ・・・ほら４００円。")
               (wait)
               (text
                #:color
                6
                "【さとみ】よしよし、何も言わなくてもお金を払うようになったわね・・・やっぱり動物は飼育するのが一番だわ。")
               (wait)
               (text #:color 7 "【" 0 "】・・・。")
               (wait)
               (text #:color 7 "【" 0 "】あれれ！？・・・お金が足りない。")
               (wait)
               (text #:color 6 "【さとみ】いい根性してるわね・・・仕方がないわ、ツケとくからあり金全部よこしなさいよ。")
               (wait)
               (set-var M 0)
               (proc 11)))
             ((> M 399)
              (<>
               (text #:color 7 "【" 0 "】あの時は、たまたま腹の調子が悪かったんだよ・・・ほら４００円。")
               (wait)
               (set-var M (- M 400))
               (proc 11)
               (text
                #:color
                6
                "【さとみ】よしよし、何も言わなくてもお金を払うようになったわね・・・やっぱり動物は飼育するのが一番だわ。")
               (wait)))
             (else (<>)))
            (text #:color 7 "【" 0 "】さとみ、いつか犯してやる。")
            (wait)
            (text #:color 6 "【さとみ】だめだめ、" 0 "じゃ役不足だもん・・・ははははは。")
            (wait)
            (set-reg: 179 1)))
          ((&& (== N 4) (== (: 180) 0))
           (<>
            (text #:color 6 "【さとみ】ジュースか・・・ちょっと待ってて。")
            (wait)
            (set-arr~ @ 7 1)
            (set-arr~ @ 1 4096)
            (set-arr~ @ 6 1)
            (image "30.pd8")
            (proc 15)
            (set-arr~ @ 7 1)
            (set-arr~ @ 1 4096)
            (set-arr~ @ 6 1)
            (image "30an.pd8")
            (set-arr~ @ 6 0)
            (set-arr~ @ 7 0)
            (load "30.s4" (~ @ 2))
            (animate 0 0 0)
            (animate 1 0)
            (set-arr~ @ 7 0)
            (set-arr~ @ 7 0)
            (load "30.a6" 47104)
            (text #:color 7 "【" 0 "】・・・。")
            (wait)
            (text #:color 7 "【" 0 "】・・・。")
            (wait)
            (text #:color 6 "【さとみ】はい、お待ちー・・・５００円になります。")
            (wait)
            (text #:color 7 "【" 0 "】お待ちって、どこにジュースがあるんだよ。")
            (wait)
            (text #:color 6 "【さとみ】自分の目の前にあるじゃない・・・視界に入ってないだけでしょ？")
            (wait)
            (text #:color 7 "【" 0 "】あ・・・本当だ。")
            (wait)
            (text #:color 6 "【さとみ】そんな事より、５００円って言ったでしょ？")
            (wait)
            (text #:color 7 "【" 0 "】５００円！？・・・相変わらず暴利をむさぼっているなあ。")
            (wait)
            (text #:color 6 "【さとみ】文句があるなら、店長を呼ぶわよー・・・言っておくけど、店長は大仏頭なんだから。")
            (wait)
            (text #:color 7 "【" 0 "】いい、いい、呼ばなくていい・・・気持ち悪いんだよ、あのマスターは。")
            (wait)
            (text #:color 6 "【さとみ】" 0 "、５００円だって言ってるじゃない・・・ほら、早く払ってよ。")
            (wait)
            (text #:color 7 "【" 0 "】払うって・・・今ここで払うのか？")
            (wait)
            (text #:color 6 "【さとみ】" 0 "は先負町一の危険人物だからねー・・・" 0 "だけは物々交換よ。")
            (wait)
            (cond
             ((< M 500)
              (<>
               (text #:color 7 "【" 0 "】ひっでえ差別・・・ほら、払えばいいんだろ。")
               (wait)
               (text #:color 7 "【" 0 "】・・・。")
               (wait)
               (text #:color 7 "【" 0 "】あれれ！？・・・お金が足りない。")
               (wait)
               (text #:color 6 "【さとみ】いい根性してるわね・・・仕方がないわ、ツケとくからあり金全部よこしなさいよ。")
               (wait)
               (set-var M 0)
               (proc 11)))
             ((> M 499)
              (<>
               (text #:color 7 "【" 0 "】ひっでえ差別・・・ほら、払えばいいんだろ。")
               (wait)
               (set-var M (- M 500))
               (proc 11)
               (text #:color 6 "【さとみ】ははは、毎度ありがとうございまーす・・・飲んだらとっとと帰ってね。")
               (wait)))
             (else (<>)))
            (text #:color 7 "【" 0 "】まったく・・・なんちゅー喫茶店だ。")
            (wait)
            (set-reg: 180 1)
            (set-reg: 179 1)))
          ((&& (== N 4) (== (: 180) 1))
           (<>
            (text #:color 6 "【さとみ】そうよね、" 0 "は子供だからジュースがぴったりよね。")
            (wait)
            (text #:color 7 "【" 0 "】ちぇっ、さとみと同じ歳じゃないか・・・自分だけ大人ぶりやがって。")
            (wait)
            (text #:color 6 "【さとみ】経験が違うわよ、経験が・・・ちょっと待って、すぐに持ってくるから。")
            (wait)
            (text #:color 6 "【さとみ】そうそう、ジュースを持って来るまでに・・・５００円、ちゃんと用意しておいてね。")
            (wait)
            (set-arr~ @ 7 1)
            (set-arr~ @ 1 4096)
            (set-arr~ @ 6 1)
            (image "30.pd8")
            (proc 15)
            (set-arr~ @ 7 1)
            (set-arr~ @ 1 4096)
            (set-arr~ @ 6 1)
            (image "30an.pd8")
            (set-arr~ @ 6 0)
            (set-arr~ @ 7 0)
            (load "30.s4" (~ @ 2))
            (animate 0 0 0)
            (animate 1 0)
            (set-arr~ @ 7 0)
            (set-arr~ @ 7 0)
            (load "30.a6" 47104)
            (text #:color 7 "【" 0 "】・・・。")
            (wait)
            (text #:color 7 "【" 0 "】まったく・・・ひどい店だぜ。")
            (wait)
            (text #:color 6 "【さとみ】はーい、ジュースお待ちー・・・５００円になりまーす。")
            (wait)
            (cond
             ((< M 500)
              (<>
               (text #:color 7 "【" 0 "】ほらよ、釣りはいらないぜ・・・とっときな。")
               (wait)
               (text #:color 7 "【" 0 "】・・・。")
               (wait)
               (text #:color 7 "【" 0 "】あれれ！？・・・お金が足りない。")
               (wait)
               (text #:color 6 "【さとみ】いい根性してるわね・・・仕方がないわ、ツケとくからあり金全部よこしなさいよ。")
               (wait)
               (set-var M 0)
               (proc 11)))
             ((> M 399)
              (<>
               (text #:color 7 "【" 0 "】ほらよ、釣りはいらないぜ・・・とっときな。")
               (wait)
               (set-var M (- M 500))
               (proc 11)
               (text #:color 6 "【さとみ】釣りはいらないって、ぴったり５００円じゃない・・・ケチ。")
               (wait)
               (text
                #:color
                7
                "【"
                0
                "】俺の５００円は普通の５００円以上の価値があるんだよ・・・もう注文を取ったんだから、あっちへ行ってくれ。")
               (wait)
               (text
                #:color
                6
                "【さとみ】はははは・・・"
                0
                "、あんまりナンパばっかりしていると、そのうち刺されちゃうよ。")
               (wait)))
             (else (<>)))
            (set-reg: 179 1)))
          ((== N 5)
           (<>
            (text #:color 6 "【さとみ】" 0 "・・・甘いものは太るよ。")
            (wait)
            (text
             #:color
             6
             "【さとみ】"
             0
             "は、デブになったら今以上に見られないんだから・・・よしたほうがいいと思うけどな。")
            (wait)
            (text #:color 7 "【" 0 "】さとみ、お前の口の中には悪魔が住んでいるぜ。")
            (wait)
            (text #:color 6 "【さとみ】やーね、小悪魔って言って。")
            (wait)))
          ((== N 6)
           (<>
            (text #:color 6 "【さとみ】フルコースね・・・うちのフルコースは、ちょっと高いわよ。")
            (wait)
            (text #:color 6 "【さとみ】そうだなー・・・５００００円払ったら出してあげる。")
            (wait)
            (text #:color 7 "【" 0 "】いらない。")
            (wait)))
          (else (<>)))))
       ((&& (== N 3) (== (: 419) 1))
        (<>
         (text #:color 6 "【さとみ】" 0 "、何を頼むの？")
         (wait)
         (set-reg: 101 1)
         (set-arr~ @ 7 0)
         (proc 18)
         (menu-show (<> (text "何でもいい")))
         (if-else (== N 1)
           (<>
            (text #:color 7 "【" 0 "】何でもいいや。")
            (wait)
            (text #:color 6 "【さとみ】わかった・・・じゃあ、特別においしい")
            (set-var S (? 6))
            (if (== S 0) (<> (text "コーヒー")))
            (if (== S 1) (<> (text "アイスコーヒー")))
            (if (== S 2) (<> (text "エスプレッソ")))
            (if (== S 3) (<> (text "レモンツィスト")))
            (if (== S 4) (<> (text "レモンティー")))
            (if (== S 5) (<> (text "紅茶")))
            (text "を入れてあげる。")
            (wait)
            (set-arr~ @ 7 1)
            (set-arr~ @ 1 4096)
            (set-arr~ @ 6 1)
            (image "30.pd8")
            (proc 15)
            (set-arr~ @ 7 1)
            (set-arr~ @ 1 4096)
            (set-arr~ @ 6 1)
            (image "30an.pd8")
            (set-arr~ @ 6 0)
            (set-arr~ @ 7 0)
            (load "30.s4" (~ @ 2))
            (animate 0 0 0)
            (animate 1 0)
            (set-arr~ @ 7 0)
            (set-arr~ @ 7 0)
            (load "30.a6" 47104)
            (text #:color 7 "【" 0 "】ちょっと・・・前のさとみと違うような気がするな。")
            (wait)
            (text #:color 6 "【さとみ】" 0 "、お待たせ・・・４００円になります。")
            (wait)
            (text #:color 7 "【" 0 "】前とちっとも変わってない。")
            (wait)
            (cond
             ((< M 400)
              (<>
               (text #:color 7 "【" 0 "】・・・。")
               (wait)
               (text #:color 7 "【" 0 "】さとみ・・・お金がたりない。")
               (wait)
               (text #:color 6 "【さとみ】もう・・・しょうがないわね、あり金全部置いていきなさい。")
               (wait)
               (set-var M 0)
               (proc 11)
               (text #:color 6 "【さとみ】喫茶店に来る時ぐらい、ちゃんとお金を持ってきなさいよ。")
               (wait)
               (text #:color 7 "【" 0 "】ははは・・・。")
               (wait)))
             ((> M 399)
              (<>
               (text #:color 7 "【" 0 "】ほら、４００円と・・・。")
               (wait)
               (set-var M (- M 400))
               (proc 11)
               (text #:color 6 "【さとみ】ありがとうございまーす！！")
               (wait)))
             (else (<>))))
           (<>))
         (set-reg: 179 1)))
       ((&& (== N 4) (== (: 179) 0) (< H 817))
        (<> (text #:color 6 "【さとみ】ねえ・・・ここにいたいのなら、何か注文してよ。") (wait)))
       ((&& (== N 4) (== (: 179) 1) (< H 817))
        (<> (text #:color 7 "【" 0 "】ふう・・・もう少しここにいようぜ。") (wait)))
       ((== N 4) (<> (text #:color 7 "【" 0 "】あれれ！？・・・俺は何をしようとしてたんだ！？") (wait)))
       (else (<>)))))
    ((&& (== V 2) (== N 9) (== (: 24) 0) (== (: 419) 0))
     (<>
      (text #:color 7 "【" 0 "】ねえねえ、そこのおねーちゃん。")
      (wait)
      (text #:color 2 "【女の人】それでね、その人ったらね・・・。")
      (wait)
      (text #:color 7 "【" 0 "】聞いちゃいない。")
      (wait)
      (if-else (== (: 179) 0)
        (<>
         (text #:color 6 "【さとみ】よしなさいよ・・・邪魔しちゃ悪いじゃない。")
         (wait)
         (text #:color 7 "【" 0 "】人が幸せそうなのを見ると、ぶち壊したくなるんだよ。")
         (wait)
         (text #:color 6 "【さとみ】屈折しているわねー。")
         (wait))
        (<>))
      (set-reg: 24 1)))
    ((&& (== V 2) (== N 9) (== (: 24) 1) (== (: 419) 0))
     (<>
      (text #:color 7 "【" 0 "】ねえねえねえ、そこのかーのじょ！！")
      (wait)
      (text #:color 2 "【女の人】そしたらね、京子が私に言うのよ・・・でも私は・・・。")
      (wait)
      (text #:color 7 "【" 0 "】まったく聞いちゃいない。")
      (wait)
      (if-else (== (: 179) 0)
        (<> (text #:color 6 "【さとみ】だから、よしなさいって言っているでしょ？") (wait))
        (<>))))
    ((&& (== V 2) (== N 9))
     (<>
      (text #:color 7 "【" 0 "】ねえねえ、そこの彼女・・・いつもこの喫茶店にいるね？")
      (wait)
      (text #:color 2 "【女の人】今度の日曜、どこかに行きたいな・・・。")
      (wait)
      (text #:color 7 "【" 0 "】相変わらず聞いちゃいない。")
      (wait)
      (if-else (== (: 179) 0)
        (<> (text #:color 6 "【さとみ】" 0 "、邪魔しちゃだめ。") (wait))
        (<>))))
    ((&& (== V 2) (== N 11) (== (: 25) 0) (== (: 419) 0))
     (<>
      (text #:color 7 "【" 0 "】おい、にーちゃん・・・女の人を置いて、お前はとっとと帰れよ。")
      (wait)
      (text #:color 1 "【男の人】ふんふん、なるほど・・・その気持ちはわかるけどね。")
      (wait)
      (text #:color 7 "【" 0 "】まったく聞いちゃいない。")
      (wait)
      (if-else (== (: 179) 0)
        (<> (text #:color 6 "【さとみ】あなたはカヤの外なんだから、ほっておきなさいよ。") (wait))
        (<>))
      (set-reg: 25 1)))
    ((&& (== V 2) (== N 11) (== (: 25) 1) (== (: 419) 0))
     (<>
      (text #:color 7 "【" 0 "】にーちゃん、前にいるねーちゃんとは、もう肉体関係を結んだのか？ええ、おい？")
      (wait)
      (text #:color 1 "【男の人】それが、おかしなヤツでさあ・・・昨日も電話があって・・・。")
      (wait)
      (text #:color 7 "【" 0 "】うっうっうっ・・・誰も俺の話を聞いてくれない。")
      (wait)
      (if-else (== (: 179) 0)
        (<> (text #:color 6 "【さとみ】いいかげんにやめたら？") (wait))
        (<>))))
    ((&& (== V 2) (== N 11))
     (<>
      (text #:color 7 "【" 0 "】にーちゃん、セックスしてるかい？")
      (wait)
      (text #:color 1 "【男の人】遊園地に行きたいな・・・今度の日曜、遊園地に行こうぜ。")
      (wait)
      (text #:color 7 "【" 0 "】無視されちゃった。")
      (wait)
      (if-else (== (: 179) 0)
        (<> (text #:color 6 "【さとみ】" 0 "は、私と話をすればいいの。") (wait))
        (<>))))
    ((&& (== V 2) (== N 14) (== (: 26) 0) (== (: 419) 0))
     (<>
      (text #:color 7 "【" 0 "】男の人が一人じゃ、何を話してもおもしろくないよ・・・やーめた。")
      (wait)
      (if-else (== (: 179) 0)
        (<> (text #:color 6 "【さとみ】男の人が一人じゃなくても、バカなまねはしないでね。") (wait))
        (<>))
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 14) (== (: 26) 1) (== (: 419) 0))
     (<>
      (text #:color 7 "【" 0 "】おやじと話すほど暇じゃない。")
      (wait)
      (if-else (== (: 179) 0)
        (<>
         (text #:color 6 "【さとみ】まったく・・・" 0 "って、女の子がいないと生きていけないんじゃない？")
         (wait)
         (text #:color 7 "【" 0 "】そりゃそうさ、さとみだって男なしじゃ生きていけないだろ？")
         (wait)
         (text #:color 6 "【さとみ】殴るわよ。")
         (wait))
        (<>))))
    ((&& (== V 2) (== N 14))
     (<>
      (text #:color 7 "【" 0 "】おやじに話かけるのか？")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】やっぱりやめた。")
      (wait)
      (if-else (== (: 179) 0)
        (<> (text #:color 6 "【さとみ】" 0 "・・・この店に遊びに来てるでしょ？") (wait))
        (<>))))
    ((&& (== V 2) (== N 20) (== (: 350) 1) (== (: 354) 1) (== (: 355) 0))
     (<>
      (text #:color 7 "【" 0 "】なあ・・・学校の倉庫で何をしてたんだ？")
      (wait)
      (text #:color 6 "【さとみ】だから何もしてないって・・・変な事を気にしないでよ。")
      (wait)
      (text #:color 7 "【" 0 "】何もしてないのに、わざわざバイトを抜けて行くのか？")
      (wait)
      (text #:color 6 "【さとみ】私だって、一人になりたい時があるの・・・。")
      (wait)
      (text #:color 7 "【" 0 "】一人になる為に、学校の倉庫にねえ・・・まあいいか。")
      (wait)
      (set-reg: 355 1)))
    ((&& (== V 2) (== N 20) (== (: 181) 0))
     (<>
      (text #:color 6 "【さとみ】ひさしぶりじゃない・・・どこで何をしてたの？")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】あのねえ、別に悪い事をしてた訳じゃないんだから・・・夏休みの前半はずっとアルバイト三昧だったんだよ。")
      (wait)
      (text #:color 6 "【さとみ】どうせ、女の子と遊ぶ資金でも稼いでたんでしょ？")
      (wait)
      (text #:color 7 "【" 0 "】ぎくうっ！！")
      (wait)
      (text #:color 6 "【さとみ】ところが遊ぶ相手もいなくて、仕方がないからぶらぶらしているだけ・・・図星でしょ？")
      (wait)
      (text #:color 7 "【" 0 "】大きなお世話だよ。")
      (wait)
      (text #:color 6 "【さとみ】" 0 "・・・いいかげんに、ちゃんとした彼女をつくったら？")
      (wait)
      (text #:color 7 "【" 0 "】俺は自由なのが好きなんだ・・・特定の女性とつきあうなんて、息が詰まっちゃうよ。")
      (wait)
      (text
       #:color
       6
       "【さとみ】私には理解できないけど、"
       0
       "の事が好きだって言う女の子もいるのよ・・・こんなちゃらんぽらんの男のどこがいいんだか。")
      (wait)
      (text #:color 7 "【" 0 "】えっ！？・・・誰！？お、教えてっ！！")
      (wait)
      (text #:color 6 "【さとみ】だーめ・・・教えたら、その女の子がかわいそうな目に合うに決っているわ。")
      (wait)
      (text #:color 7 "【" 0 "】ちゃんとつきあうからさ・・・ね？ね？")
      (wait)
      (text #:color 6 "【さとみ】さっきと言ってる事が、ぜんぜん違うじゃない・・・もう。")
      (wait)
      (set-reg: 181 1)))
    ((&& (== V 2) (== N 20) (== (: 181) 1) (== (: 182) 0))
     (<>
      (text #:color 6 "【さとみ】考えてみれば、本当に最後の夏休みなのね・・・来年は何をしているやら。")
      (wait)
      (text #:color 7 "【" 0 "】だろう？・・・さとみだって、アルバイトをしている場合じゃないぜ。")
      (wait)
      (text #:color 6 "【さとみ】心配は無用よ・・・私だって、ちゃんと青春してるんだから。")
      (wait)
      (text #:color 7 "【" 0 "】へえ、さとみに彼氏がいるのか？・・・どうして俺に紹介してくれないんだよ。")
      (wait)
      (text #:color 6 "【さとみ】いやよ、何を言い出すかわからないもの・・・" 0 "には、絶対に会わせたくないわね。")
      (wait)
      (text #:color 7 "【" 0 "】ちぇっ、古いつき合いなのに冷たいよな。")
      (wait)
      (text
       #:color
       6
       "【さとみ】考えてみたら、本当に古いつきあいよね・・・中学の時から同じ学校で、いつもお互いに憎まれ口を言いながら、こうやってつき合ってきたんですもの。")
      (wait)
      (text #:color 7 "【" 0 "】ようするに、腐れ縁ってやつだな。")
      (wait)
      (set-reg: 182 1)))
    ((&& (== V 2) (== N 20) (== (: 182) 1) (== (: 26) 0) (== (: 262) 0))
     (<>
      (text #:color 6 "【さとみ】" 0 "は・・・好きな人がいないの？")
      (wait)
      (text #:color 7 "【" 0 "】うーん、かわいい女の子は全部好きだな。")
      (wait)
      (text #:color 6 "【さとみ】" 0 "って、女の子を本当に好きになった事がないんじゃない？")
      (wait)
      (text #:color 7 "【" 0 "】そんな事はないさ・・・逆に惚れっぽくて困っているくらいさ。")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 20) (== (: 26) 1) (== (: 262) 0))
     (<>
      (text #:color 6 "【さとみ】ねえ・・・最後の夏休みだと思うと、なんだか寂しいね。")
      (wait)
      (text #:color 7 "【" 0 "】はっはっはっ・・・さとみは来年も夏休みがあるかもよ。")
      (wait)
      (text #:color 6 "【さとみ】失礼ね、私はちゃんと卒業するわよ。")
      (wait)))
    ((&& (== V 2) (== N 20) (== (: 262) 1) (== (: 26) 0) (< H 812))
     (<>
      (text #:color 6 "【さとみ】" 0 "、暇そうじゃない・・・せっかくの夏休みなのに、時間がもったいないわよ。")
      (wait)
      (text #:color 7 "【" 0 "】へっへっへっーだ、俺は俺なりに楽しんでいるんだよ。")
      (wait)
      (text #:color 6 "【さとみ】女の子を追いかけている事なら、夏休みじゃなくても同じ事をしてるじゃない。")
      (wait)
      (text #:color 7 "【" 0 "】違うんだぜ・・・夏休みってのはだな、女の子の股間が開放的になるんだよ、パカッとね。")
      (wait)
      (text #:color 6 "【さとみ】あーあ、こんな男と中学の時から知合いだなんて、自分で自分が恥ずかしくなるわ。")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 20) (== (: 262) 1) (== (: 26) 1) (< H 812))
     (<>
      (text #:color 7 "【" 0 "】さとみ、アルバイトもいいけど・・・こんな事ばかりしてると、股間の蜘の巣が張っちゃうぜ。")
      (wait)
      (text #:color 6 "【さとみ】余計な心配をしなくていいわ・・・２４時間、ここでアルバイトをしてる訳じゃありません。")
      (wait)
      (text #:color 7 "【" 0 "】へえ、夜に何をしてるんだ・・・内職か？")
      (wait)
      (text #:color 6 "【さとみ】" 0 "には教えない・・・私だって、ちゃんと青春してるのよ。")
      (wait)
      (text #:color 7 "【" 0 "】ふーん。")
      (wait)
      (set-reg: 26 2)))
    ((&& (== V 2) (== N 20) (== (: 262) 1) (== (: 26) 2) (< H 812))
     (<>
      (text #:color 6 "【さとみ】さっさと注文しなさいよ。")
      (wait)
      (text #:color 7 "【" 0 "】それが客に対する態度か？")
      (wait)
      (text #:color 6 "【さとみ】" 0 "は別よ。")
      (wait)))
    ((&& (== V 2) (== N 20) (< H 813) (== (: 26) 0))
     (<>
      (text #:color 6 "【さとみ】" 0 "・・・早く彼女をつくりなさいよ。")
      (wait)
      (text #:color 7 "【" 0 "】さとみには関係ないだろ？・・・俺は特定の彼女をつくる気はないんだ。")
      (wait)
      (text #:color 6 "【さとみ】私は関係ない・・・わよね。")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 20) (< H 813) (== (: 26) 1))
     (<>
      (text #:color 6 "【さとみ】" 0 "って自由でいたいから、彼女をつくらないんでしょ？")
      (wait)
      (text #:color 7 "【" 0 "】そうだよ・・・俺は先負町の自由人だ。")
      (wait)
      (text #:color 6 "【さとみ】彼女ができないのか、つくろうと思ってないのか・・・怪しいわねー。")
      (wait)
      (text #:color 7 "【" 0 "】ばっかやろう・・・俺には女の子の友達がいっぱいいるんだぞっ！！")
      (wait)
      (text #:color 6 "【さとみ】友達じゃ仕方がないじゃない。")
      (wait)
      (text #:color 7 "【" 0 "】う・・・。")
      (wait)
      (set-reg: 26 2)))
    ((&& (== V 2) (== N 20) (< H 813) (== (: 26) 2))
     (<>
      (text #:color 6 "【さとみ】" 0 "・・・来年は何をしてるの？")
      (wait)
      (text #:color 7 "【" 0 "】さあね、先負学園の学生じゃない事だけは確かだな。")
      (wait)))
    ((&& (== V 2) (== N 20) (< H 814) (== (: 26) 0))
     (<>
      (text #:color 6 "【さとみ】" 0 "、最近美穂ちゃんに会ってる？")
      (wait)
      (text #:color 7 "【" 0 "】え！？・・・どうして！？")
      (wait)
      (text #:color 6 "【さとみ】美穂ちゃんがこの間来てね、" 0 "の事を聞いてたわよ。")
      (wait)
      (text #:color 7 "【" 0 "】ふーん・・・何を聞いてたんだ？")
      (wait)
      (text #:color 6 "【さとみ】" 0 "君って、変な人？・・・って。")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 20) (< H 814) (== (: 26) 1))
     (<>
      (text #:color 7 "【" 0 "】さとみ、最近お肌のツヤがいいじゃないか・・・エッチな事ばかりしてるんじゃないか？")
      (wait)
      (text #:color 6 "【さとみ】" 0 "と違って、私は健全ですからね・・・お肌のツヤは生まれつきなのよ。")
      (wait)
      (text #:color 7 "【" 0 "】そうか、毎晩ゴマ油を塗ってるんだな。")
      (wait)))
    ((&& (== V 2) (== N 20) (< H 815) (== (: 26) 0))
     (<>
      (text #:color 7 "【" 0 "】さとみ・・・キスマークがついてるぜ。")
      (wait)
      (text #:color 6 "【さとみ】えっ！？・・・ど、どこに！？")
      (wait)
      (text #:color 7 "【" 0 "】へえ・・・そのアセり方は、何もエッチな事をしてないって反応じゃないな。")
      (wait)
      (text #:color 6 "【さとみ】いいかげんにしてよ・・・覚えがなくたって、誤解されたくないからアセっただけ。")
      (wait)
      (text #:color 7 "【" 0 "】へー、ふーん、ほー。")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 20) (< H 815) (== (: 26) 1))
     (<>
      (text #:color 6 "【さとみ】" 0 "もさあ・・・もっと大人になったらどう？")
      (wait)
      (text #:color 7 "【" 0 "】俺は大人だよ。")
      (wait)
      (text #:color 6 "【さとみ】一人暮らししてるところとかは大人だけど・・・やってる事がイマイチ子供よね。")
      (wait)))
    ((&& (== V 2) (== N 20) (< H 816) (== (: 26) 0))
     (<>
      (text #:color 6 "【さとみ】" 0 "ってさ・・・健二君と仲が悪いの？")
      (wait)
      (text #:color 7 "【" 0 "】さとみだって知ってるだろう？・・・俺と健二は犬猿の仲さ。")
      (wait)
      (text #:color 6 "【さとみ】でも、どうしてなのかしら？")
      (wait)
      (text #:color 7 "【" 0 "】お互いに気に入らないんじゃないか？・・・舞ちゃんの事もあるし。")
      (wait)
      (text #:color 6 "【さとみ】舞ちゃんがどうかしたの？")
      (wait)
      (text #:color 7 "【" 0 "】舞ちゃんに正面きって手を出そうとしてるのは、俺と健二ぐらいなもんだ。")
      (wait)
      (text #:color 6 "【さとみ】そうよね・・・。")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 20) (< H 816) (== (: 26) 1))
     (<>
      (text #:color 6 "【さとみ】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】さとみ。")
      (wait)
      (text #:color 6 "【さとみ】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】おーいっ！！")
      (wait)
      (text #:color 6 "【さとみ】え？・・・何か言った？")
      (wait)
      (text #:color 7 "【" 0 "】駄目だ、こりゃ。")
      (wait)))
    ((&& (== V 2) (== N 20) (< H 817) (== (: 26) 0))
     (<>
      (text #:color 7 "【" 0 "】なあ・・・何か悩み事があるんじゃないか？")
      (wait)
      (text #:color 6 "【さとみ】別にないわよ。")
      (wait)
      (text #:color 7 "【" 0 "】誰もただで聞いてやるとは言ってないぜ・・・この店の飲物、一年間無料でどうだ？")
      (wait)
      (text #:color 6 "【さとみ】だから、何もないって言ってるでしょ！？")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 20) (< H 817) (== (: 26) 1))
     (<>
      (text #:color 6 "【さとみ】男の人の気持ちって・・・よくわからないのよね。")
      (wait)
      (text #:color 7 "【" 0 "】コーヒーでも飲もうかな？")
      (wait)
      (text #:color 6 "【さとみ】本当に自分の事が好きか、確認する方法ってないのかしら？")
      (wait)
      (text #:color 7 "【" 0 "】それとも、アイスコーヒーにしようかな？")
      (wait)
      (text #:color 6 "【さとみ】ねえ、私の言ってる事を聞いてる？")
      (wait)
      (text #:color 7 "【" 0 "】全然。")
      (wait)
      (set-reg: 26 2)))
    ((&& (== V 2) (== N 20) (< H 817) (== (: 26) 2))
     (<>
      (text #:color 6 "【さとみ】とっとと注文しなさいよ。")
      (wait)
      (text #:color 7 "【" 0 "】さとみ、男心ってものはだな・・・。")
      (wait)
      (text #:color 6 "【さとみ】怒るわよ。")
      (wait)))
    ((&& (== V 2) (== N 20) (== (: 437) 0))
     (<>
      (text #:color 6 "【さとみ】やだ・・・そんな顔で見ないでよ。")
      (wait)
      (text #:color 7 "【" 0 "】悪かったな、こん顔で。")
      (wait)
      (text #:color 6 "【さとみ】そういう意味で言ったんじゃないってば。")
      (wait)
      (if-else (== (: 420) 1)
        (<>
         (text #:color 7 "【" 0 "】でも・・・こうして喫茶店に戻ってくれてよかったよ。")
         (wait)
         (text #:color 6 "【さとみ】私がいないと寂しいんでしょ？")
         (wait)
         (text #:color 7 "【" 0 "】そうだな。")
         (wait)
         (text #:color 6 "【さとみ】やだ・・・そうだな、なんて言わないでよ。")
         (wait))
        (<>))
      (set-reg: 437 1)))
    ((&& (== V 2) (== N 20) (< H 821) (== (: 26) 0))
     (<>
      (text #:color 6 "【さとみ】ね・・・私、いつも通りでしょ？")
      (wait)
      (if-else (== (: 420) 1)
        (<>
         (text #:color 7 "【" 0 "】（駄目だ・・・さとみの顔を見てると、公園での事が思い出される。）")
         (wait)
         (text #:color 6 "【さとみ】" 0 "・・・変な事を思い出しているでしょ？")
         (wait)
         (text #:color 7 "【" 0 "】とってもいい事を思い出してたんだ。")
         (wait)
         (text #:color 6 "【さとみ】もう・・・やだ。")
         (wait)
         (set-reg: 26 1))
        (<>))))
    ((&& (== V 2) (== N 20) (< H 821) (== (: 26) 1))
     (<>
      (text #:color 6 "【さとみ】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】さとみ、黙るなよ。")
      (wait)
      (text #:color 6 "【さとみ】あ・・・ごめんね。")
      (wait)))
    ((&& (== V 2) (== N 20) (== H 821) (== (: 26) 0))
     (<>
      (text #:color 6 "【さとみ】ねえねえ、" 0 "って・・・どうしてスケベなのに、人気があるのかしら？")
      (wait)
      (text #:color 7 "【" 0 "】はっはっはっ、スケベだから人気があるんじゃないか？")
      (wait)
      (text #:color 6 "【さとみ】健二君もスケベだけど、あまり人気がないじゃない。")
      (wait)
      (text #:color 7 "【" 0 "】やつの場合はスケベじゃなくて、『妙にいやらしい』って言うんだ。")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 20) (== H 821) (== (: 26) 1))
     (<>
      (text #:color 7 "【" 0 "】さとみ・・・今日は何日だっけ？")
      (wait)
      (text #:color 6 "【さとみ】えーと、今日は８月２１日よ。")
      (wait)
      (text #:color 7 "【" 0 "】夏休みもあと１０日か・・・。")
      (wait)))
    ((&& (== V 2) (== N 20) (== H 822) (== (: 26) 0))
     (<>
      (text #:color 6 "【さとみ】" 0 "、相変わらず女の子を追いかけてるの？")
      (wait)
      (text #:color 7 "【" 0 "】女の子に追いかけられてるんだ。")
      (wait)
      (text #:color 6 "【さとみ】嘘つき。")
      (wait)
      (text #:color 7 "【" 0 "】あれ？・・・どうしてわかったの？")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 20) (== H 822) (== (: 26) 1))
     (<>
      (text #:color 6 "【さとみ】あーあ・・・このまま青春は終ってしまうのかしら？")
      (wait)
      (text #:color 7 "【" 0 "】青春なんて気の持ちようだぜ・・・俺はきっと、５０歳になっても青春してるぜ。")
      (wait)
      (text #:color 6 "【さとみ】それって、ちょっと気持ち悪くない？")
      (wait)))
    ((&& (== V 2) (== N 20) (== H 823) (== (: 26) 0))
     (<>
      (text #:color 7 "【" 0 "】さとみ、何かいい事あったのか？")
      (wait)
      (text #:color 6 "【さとみ】どうして？")
      (wait)
      (text #:color 7 "【" 0 "】だってさ・・・顔がなんだか元気だぜ。")
      (wait)
      (text #:color 6 "【さとみ】でしょう？・・・別にいい事はないけど、最近変に元気なのよ。")
      (wait)
      (text #:color 7 "【" 0 "】発情期かな？")
      (wait)
      (text #:color 6 "【さとみ】いつか刺してやるわ・・・。")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 20) (== H 823) (== (: 26) 1))
     (<>
      (text #:color 7 "【" 0 "】あーあ・・・何かいい事がないかな？")
      (wait)
      (text #:color 6 "【さとみ】こうして私と話をしてるじゃない。")
      (wait)
      (text #:color 7 "【" 0 "】そう言われると、返事に困るな・・・。")
      (wait)))
    ((&& (== V 2) (== N 20) (== H 824) (== (: 26) 0))
     (<>
      (text #:color 6 "【さとみ】相変わらず暇そうね・・・もう一度アルバイトをやったら？")
      (wait)
      (text #:color 7 "【" 0 "】俺、夏休みの前半、ずーっとアルバイトしてたんだぜ。")
      (wait)
      (text #:color 6 "【さとみ】アルバイトをやめて暇になるより、まだ何かしてた方がいいと思うけど・・・。")
      (wait)
      (text #:color 7 "【" 0 "】何かしてるから、俺はいいんだよ。")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 20) (== H 824) (== (: 26) 1))
     (<>
      (text #:color 6 "【さとみ】最近、お客さんが少ないのよ・・・景気が悪いのかしら？")
      (wait)
      (text #:color 7 "【" 0 "】景気が悪いと、宝くじが売れて喫茶店に客が来なくなる・・・か。")
      (wait)))
    ((&& (== V 2) (== N 20) (== H 825) (== (: 26) 0))
     (<>
      (text #:color 6 "【さとみ】" 0 "・・・誰かとつきあってる？")
      (wait)
      (text #:color 7 "【" 0 "】どうしてそんな事を聞くんだ？")
      (wait)
      (text #:color 6 "【さとみ】いいから答えてよ・・・。")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "つき合ってる") (text "つき合ってない")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】実は・・・俺にも彼女ができたんだ。")
         (wait)
         (text #:color 6 "【さとみ】やっぱりね・・・この間、一哉君が来て色々と言ってたわよ。")
         (wait)
         (text #:color 7 "【" 0 "】（あれれ！？・・・俺は誰とつき合ってるんだっけ。）")
         (wait)
         (text #:color 6 "【さとみ】・・・。")
         (wait)
         (set-reg: 105 (- (: 105) 1))))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】誰ともつき合ってないぜ・・・俺は彼女はつくらない主義なんだ。")
         (wait)
         (text #:color 6 "【さとみ】そうよね、おかしいと思ったんだ・・・。")
         (wait)))
       (else (<>)))
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 20) (== H 825) (== (: 26) 1))
     (<>
      (text #:color 7 "【" 0 "】俺の事より、さとみはどうなんだよ。")
      (wait)
      (text #:color 6 "【さとみ】うん・・・好きな人ができそうな感じ。")
      (wait)
      (text #:color 7 "【" 0 "】へえ・・・。")
      (wait)))
    ((&& (== V 2) (== N 20) (== H 826) (== (: 26) 0))
     (<>
      (text #:color 7 "【" 0 "】さとみ、マスターは元気かい？")
      (wait)
      (text #:color 6 "【さとみ】いるわよ・・・私がいる時は、店に出て来ないけど。")
      (wait)
      (text #:color 7 "【" 0 "】なあ・・・あのマスターって、変じゃないか？")
      (wait)
      (text #:color 6 "【さとみ】" 0 "、私の親戚なのよ・・・変とは何よ。")
      (wait)
      (text #:color 7 "【" 0 "】あ・・・そうだったな。")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 20) (== H 826) (== (: 26) 1))
     (<>
      (text #:color 6 "【さとみ】私ね・・・早く学校を卒業したいんだ。")
      (wait)
      (text #:color 7 "【" 0 "】どうして？")
      (wait)
      (text #:color 6 "【さとみ】へへへ・・・内緒。")
      (wait)))
    ((&& (== V 2) (== N 20) (== H 827) (== (: 26) 0))
     (<>
      (text #:color 6 "【さとみ】ねえ、" 0 "・・・学校を卒業しても、この店に顔を出してくれるでしょ？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "もちろん") (text "二度と来ない")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】もちろん顔を出すぜ・・・ここに『ＯＴＩＭＴＩＭ』が存在してる限りだけど。")
         (wait)
         (text #:color 6 "【さとみ】よかった・・・『ＯＴＩＭＴＩＭ』は永遠に不滅よ。")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】やだなあ、二度と来る訳がないだろ？")
         (wait)
         (text #:color 6 "【さとみ】どうしてよ。")
         (wait)
         (text #:color 7 "【" 0 "】卒業したら忙しくて、喫茶店に来てる暇なんかないさ。")
         (wait)
         (text #:color 6 "【さとみ】・・・。")
         (wait)
         (set-reg: 105 (- (: 105) 1))))
       (else (<>)))
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 20) (== H 827) (== (: 26) 1))
     (<>
      (text #:color 6 "【さとみ】卒業したら・・・みんなバラバラになっちゃうね。")
      (wait)
      (text #:color 7 "【" 0 "】仕方がないさ、そうやって大人になっていくんだ。")
      (wait)))
    ((&& (== V 2) (== N 20) (== H 828) (== (: 26) 0))
     (<>
      (text #:color 6 "【さとみ】" 0 "、夏休みもあと３日ね。")
      (wait)
      (text #:color 7 "【" 0 "】ははは・・・宿題なんかクソくらえ、だ。")
      (wait)
      (text #:color 6 "【さとみ】" 0 "は毎年やらないじゃない・・・私なんて、アルバイトが終ってから毎晩必死でやってるのよ。")
      (wait)
      (text #:color 7 "【" 0 "】さとみ、見せろ。")
      (wait)
      (text #:color 6 "【さとみ】だーめ・・・私ね、" 0 "を甘やかさない事に決めたの。")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 20) (== H 828) (== (: 26) 1))
     (<>
      (text #:color 6 "【さとみ】" 0 "も家に帰って、宿題をやったら？")
      (wait)
      (text #:color 7 "【" 0 "】そんな事をしたら、具合が悪くなっちゃうよ。")
      (wait)))
    ((&& (== V 2) (== N 20) (== H 829) (== (: 26) 0))
     (<>
      (text #:color 6 "【さとみ】ねえねえ、私・・・元気じゃない？")
      (wait)
      (text #:color 7 "【" 0 "】ああ、元気だなあ・・・すごく元気だ。")
      (wait)
      (text #:color 6 "【さとみ】真面目に答えてる？")
      (wait)
      (text #:color 7 "【" 0 "】答えてるよ・・・肌のツヤはいいし、脈も正常だし、食欲もある。")
      (wait)
      (text #:color 6 "【さとみ】あのね・・・私は病人じゃないのよ。")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 20) (== H 829) (== (: 26) 1))
     (<>
      (text #:color 6 "【さとみ】あと少しで二学期か・・・進学する人は大変よね。")
      (wait)
      (text #:color 7 "【" 0 "】俺の事か？")
      (wait)
      (text #:color 6 "【さとみ】" 0 "は・・・留年でしょ？")
      (wait)
      (text #:color 7 "【" 0 "】おいおい。")
      (wait)))
    ((&& (== V 2) (== N 20) (== H 830) (== (: 26) 0))
     (<>
      (text #:color 6 "【さとみ】私ね、やっと宿題が終ったの。")
      (wait)
      (text #:color 7 "【" 0 "】ごくろう・・・で、いつ貸してくれるんだ？")
      (wait)
      (text #:color 6 "【さとみ】貸さないわよ・・・前に言わなかった？")
      (wait)
      (text #:color 7 "【" 0 "】何を？")
      (wait)
      (text #:color 6 "【さとみ】" 0 "を甘やかさないって決めたの・・・自分の事は自分でやりなさい。")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 2) (== N 20) (== H 830) (== (: 26) 1))
     (<>
      (text #:color 6 "【さとみ】" 0 "・・・来年は何をしてるの？")
      (wait)
      (text #:color 7 "【" 0 "】そうだなあ・・・自分でもわからないや。")
      (wait)
      (text #:color 6 "【さとみ】ノンキね、" 0 "って。")
      (wait)))
    ((&& (== V 1) (== N 1) (== (: 10) 0))
     (<>
      (text #:color 7 "【" 0 "】うーん、向かいの椅子には誰もいない・・・。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<>
         (text #:color 6 "【さとみ】" 0 "、今年もさびしい夏休みになりそうねー。")
         (wait)
         (text #:color 7 "【" 0 "】そういうさとみだって、相変わらずバイト三昧の夏休みじゃないか。")
         (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<> (text #:color 6 "【さとみ】いいじゃない、私がいるんだから。") (wait)))
       (else (<>)))
      (set-reg: 10 1)))
    ((&& (== V 1) (== N 1) (== (: 10) 1))
     (<>
      (text #:color 7 "【" 0 "】あーあ、一人で喫茶店で時間をつぶしているなんて・・・俺は孤独だぜ。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<>
         (text #:color 6 "【さとみ】私がそばにいるじゃない・・・元気を出しなさいよ。")
         (wait)
         (text #:color 7 "【" 0 "】じゃあ・・・やらせてくれ。")
         (wait)
         (text #:color 6 "【さとみ】絶対にイヤ。")
         (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<>
         (text #:color 6 "【さとみ】私がいるでしょ？・・・私じゃいやなの？")
         (wait)
         (text #:color 7 "【" 0 "】（何か言ってる事が以前と違うんだよなあ・・・。）")
         (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 2) (== (: 179) 0) (== (: 419) 0))
     (<>
      (text #:color 7 "【" 0 "】テーブルだな・・・。")
      (wait)
      (text #:color 6 "【さとみ】" 0 "、テーブルの上には何も乗ってないわよ・・・早く注文しなさいよ。")
      (wait)))
    ((&& (== V 1) (== N 2) (== (: 179) 0) (== (: 419) 1))
     (<>
      (text #:color 7 "【" 0 "】テーブルの上には・・・さとみが乗ってる。")
      (wait)
      (text #:color 6 "【さとみ】乗ってないわよ・・・前に立ってるだけ。")
      (wait)))
    ((&& (== V 1) (== N 2) (== (: 179) 1))
     (<> (text #:color 7 "【" 0 "】テーブルだな・・・テーブルを眺めていても、無駄な時間が過ぎるだけか。") (wait)))
    ((&& (== V 1) (== N 3) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】ガラスの窓を通して、ショップルーフが見える。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<>
         (text #:color 6 "【さとみ】盗んじゃだめだよ。")
         (wait)
         (text #:color 7 "【" 0 "】誰があんなビニールのかたまりを盗むんだよ。")
         (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<> (text #:color 6 "【さとみ】いい天気よね・・・最後に雨が降ったの、いつだったかしら？") (wait)))
       (else (<>)))
      (set-reg: 11 1)))
    ((&& (== V 1) (== N 3) (== (: 11) 1))
     (<>
      (text #:color 7 "【" 0 "】ショップルーフだ・・・。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<> (text #:color 6 "【さとみ】" 0 "、誰に言ってるの？") (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<>
         (text #:color 6 "【さとみ】" 0 "って、ぼーっとしてる時があるのよ・・・いったい何を考えてるのかしら？")
         (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 4) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】植え込みだな・・・毛深い女のように、ワサワサと生えているぞ。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<> (text #:color 6 "【さとみ】あのねえ・・・もうちょっと、他の言い方ができない？") (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<> (text #:color 6 "【さとみ】" 0 "の・・・エッチ。") (wait)))
       (else (<>)))
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 4) (== (: 12) 1))
     (<>
      (text #:color 7 "【" 0 "】植え込みだ・・・毛深い男のようにワサワサと生えている。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<> (text #:color 6 "【さとみ】わざわざ人間にたとえないでよ・・・ただの植え込みでしょ？") (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<> (text #:color 6 "【さとみ】もう・・・。") (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 5) (== (: 13) 0))
     (<>
      (text #:color 7 "【" 0 "】でかい窓だな・・・俺様の指紋の味をたっぷりと味あわせてやるか。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<> (text #:color 6 "【さとみ】そんな事をしたら、自分で拭いてもらうからね。") (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<> (text #:color 6 "【さとみ】いちいち、言い方がいやらしいんだから。") (wait)))
       (else (<>)))
      (set-reg: 13 1)))
    ((&& (== V 1) (== N 5) (== (: 13) 1))
     (<>
      (text #:color 7 "【" 0 "】窓の外を見ると、かわいい女の子が・・・。")
      (wait)
      (text #:color 7 "【" 0 "】歩いてない。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<>
         (text #:color 6 "【さとみ】かわいい女の子は、みーんな、" 0 "君の事を避けているのよ。")
         (wait)
         (text #:color 7 "【" 0 "】ありがとう。")
         (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<>
         (text #:color 6 "【さとみ】" 0 "は、かわいい女の子が好きなの？")
         (wait)
         (text #:color 7 "【" 0 "】はあ？")
         (wait)
         (text #:color 6 "【さとみ】私は・・・かわいくないもんね。")
         (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 6) (== (: 14) 0))
     (<>
      (text #:color 7 "【" 0 "】絵がかかっているな・・・訳のわからない幾何学模様が描かれている。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<> (text #:color 6 "【さとみ】へえ・・・女の子しか見ないと思ったら、ちゃんと絵も見ているんだ。") (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<>
         (text #:color 6 "【さとみ】" 0 "って絵がうまいのよね・・・中学の時から美術と体育だけはよかったのよ。")
         (wait)
         (text #:color 7 "【" 0 "】その美術と体育だけってのはやめてくれ。")
         (wait)))
       (else (<>)))
      (set-reg: 14 1)))
    ((&& (== V 1) (== N 6) (== (: 14) 1))
     (<>
      (text #:color 7 "【" 0 "】意味不明の絵だな・・・どうして喫茶店には、訳のわからない絵が飾ってあるんだろう。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<>
         (text #:color 6 "【さとみ】店長を呼んで、聞いてみましょうか？")
         (wait)
         (text #:color 7 "【" 0 "】いい、呼ばなくていい・・・あの言葉使いを聞くと、気分が悪くなってくるんだ。")
         (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<> (text #:color 6 "【さとみ】本当の事を言うとね・・・私もわからないの。") (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 7) (== (: 15) 0))
     (<>
      (text #:color 7 "【" 0 "】観葉植物だな・・・絵が飾ってある前に置いてあるようだ。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<>
         (text #:color 6 "【さとみ】食べちゃだめよ。")
         (wait)
         (text #:color 7 "【" 0 "】俺はさとみを食べたい。")
         (wait)
         (text #:color 6 "【さとみ】だって、" 0 "って浮気者だから・・・私は一途な男性が好きなの。")
         (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<> (text #:color 6 "【さとみ】リース契約で置いてるのよ・・・だから２ヶ月に一回業者が取りにくるの。") (wait)))
       (else (<>)))
      (set-reg: 15 1)))
    ((&& (== V 1) (== N 7) (== (: 15) 1))
     (<>
      (text #:color 7 "【" 0 "】観葉植物だ・・・あれは食べられないぜ。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<>
         (text
          #:color
          6
          "【さとみ】"
          0
          "だったら、食べられるんじゃない？・・・パイナップルの葉っぱまで、食べちゃったって話を聞いた事があるわよ。")
         (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<> (text #:color 6 "【さとみ】私だって食べられないわよ・・・。") (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 8) (== (: 16) 0))
     (<>
      (text #:color 7 "【" 0 "】天井からは、照明がぶらさがっている・・・。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<> (text #:color 6 "【さとみ】そう言えば・・・あの照明がついているところを、見た事がないわね。") (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<> (text #:color 6 "【さとみ】" 0 "って、色々と観察するのね・・・。") (wait)))
       (else (<>)))
      (set-reg: 16 1)))
    ((&& (== V 1) (== N 8) (== (: 16) 1))
     (<>
      (text #:color 7 "【" 0 "】照明だ・・・なんだか家庭の台所にある照明みたいだな。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<>
         (text #:color 6 "【さとみ】店長を呼んで、聞いてみましょうか？")
         (wait)
         (text #:color 7 "【" 0 "】いい、呼ばなくていい・・・あの言葉使いを聞くと、気分が悪くなってくるんだ。")
         (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<> (text #:color 6 "【さとみ】そろそろこの店も、インテリアを変えた方がいいのかしら・・・？") (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 10) (== (: 17) 0))
     (<>
      (text #:color 7 "【" 0 "】髪の毛が長い女の人がいるぞ・・・こっちからでは、顔は見えないが。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<>
         (text
          #:color
          6
          "【さとみ】側に行って、顔を覗かないでよ・・・以前に同じ事をして、ケンカになった事を忘れてないでしょうね？")
         (wait)
         (text #:color 7 "【" 0 "】あれは、俺もまだ若かったからだよ・・・もう、そんな子供じみた事はしないさ。")
         (wait)
         (text #:color 6 "【さとみ】若かったって、ほんの一ヶ月前の事じゃない。")
         (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<>
         (text #:color 6 "【さとみ】" 0 "って、女の人だったら誰でもいいの？")
         (wait)
         (text #:color 7 "【" 0 "】かわいければ、誰でもいい。")
         (wait)
         (text #:color 6 "【さとみ】あ・・・そうなの、ふーん。")
         (wait)))
       (else (<>)))
      (set-reg: 17 1)))
    ((&& (== V 1) (== N 10) (== (: 17) 1))
     (<>
      (text #:color 7 "【" 0 "】かわいいかなあ・・・それとも、動物園シリーズかなあ？")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<>
         (text #:color 6 "【さとみ】とにかくあの女性は、あなたの人生にはかかわりあいのない人よ・・・ちょっかいを出さないでね。")
         (wait)
         (text #:color 7 "【" 0 "】さとみ・・・ヤキモチを妬いているのか？")
         (wait)
         (text #:color 6 "【さとみ】この店のレベルを落としたくないだけよ。")
         (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<>
         (text #:color 6 "【さとみ】さっき見たけど・・・動物園だったわよ。")
         (wait)
         (text #:color 7 "【" 0 "】ひどい・・・。")
         (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 13) (== (: 18) 0))
     (<>
      (text #:color 7 "【" 0 "】ちっ・・・男を見ても仕方がない。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<>
         (text #:color 6 "【さとみ】・・・差別だわ。")
         (wait)
         (text
          #:color
          7
          "【"
          0
          "】男が男を差別しても、誰も文句は言わないぜ・・・わけのわからないおばさんが文句を言うパターンは、男が女を差別した時のみだ。")
         (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<> (text #:color 6 "【さとみ】けっこういい男かもね・・・私が見てこようかな？") (wait)))
       (else (<>)))
      (set-reg: 18 1)))
    ((&& (== V 1) (== N 13) (== (: 18) 1))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】あの男は、きっと悪い病気を持っているに違いない・・・正面に座っている女性に、そっと教えてやるか。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<> (text #:color 6 "【さとみ】余計な事をしないで、" 0 "はここでじっとしていなさい。") (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<>
         (text #:color 6 "【さとみ】だめだってば・・・もう、" 0 "って中年になってもこのままなのかしら？")
         (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 15) (== (: 19) 0))
     (<>
      (text #:color 7 "【" 0 "】椅子だな・・・俺が座っているのと同じだ。")
      (wait)
      (text #:color 7 "【" 0 "】不満だぜ、俺様が座る椅子は他と違わないとな・・・はっはっはっ！！")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<>
         (text #:color 6 "【さとみ】いいわよ、物置の奥にしまってあるパイプ椅子と取り替えてあげる。")
         (wait)
         (text #:color 7 "【" 0 "】このままでいいです。")
         (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<>
         (text #:color 6 "【さとみ】" 0 "、ぜいたくを言わないでよ・・・喫茶店の椅子なんて、こんなものなんだから。")
         (wait)))
       (else (<>)))
      (set-reg: 19 1)))
    ((&& (== V 1) (== N 15) (== (: 19) 1))
     (<>
      (text #:color 7 "【" 0 "】椅子だ・・・処女の女の肌のように、スベスベとした椅子だ。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<> (text #:color 6 "【さとみ】" 0 "・・・いつから、中年のオヤジになったの？") (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<>
         (text #:color 6 "【さとみ】" 0 "って処女が好き？")
         (wait)
         (text #:color 7 "【" 0 "】うーん・・・非常に難しい質問だ。")
         (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 16) (== (: 20) 0))
     (<>
      (text #:color 7 "【" 0 "】窓だな・・・あの窓の右横に、入口があるんだ。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<>
         (text #:color 6 "【さとみ】まさか・・・店が閉まった後に、こっそりと忍び込む計画を立てているの？")
         (wait)
         (text #:color 7 "【" 0 "】あのねえ、俺は善良な市民で、良識ある子供だ。")
         (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<> (text #:color 6 "【さとみ】何よ・・・初めて来たみたいな事を言っちゃって。") (wait)))
       (else (<>)))
      (set-reg: 20 1)))
    ((&& (== V 1) (== N 16) (== (: 20) 1))
     (<>
      (text #:color 7 "【" 0 "】だから、大きなガラスの窓だ。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<>
         (text #:color 6 "【さとみ】世界一大きなガラス窓ね。")
         (wait)
         (text #:color 7 "【" 0 "】さとみの嘘つき。")
         (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<> (text #:color 6 "【さとみ】割らないでよ・・・高いんだから。") (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 17) (== (: 21) 0))
     (<>
      (text #:color 7 "【" 0 "】壁には花がかけてある・・・いつ来ても同じ花だな。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<>
         (text #:color 6 "【さとみ】あれは造花なのよ・・・いい香りのする、芳香剤入りなの。")
         (wait)
         (text #:color 7 "【" 0 "】ふーん。")
         (wait)
         (text #:color 6 "【さとみ】" 0 "のパンツに入れておくと、ちょうどいいかもね。")
         (wait)
         (text #:color 7 "【" 0 "】ふふん、俺のパンツの臭いをかいだ事があるのかよう。")
         (wait)
         (text #:color 6 "【さとみ】かがなくても、十分に想像できるわ。")
         (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<>
         (text #:color 6 "【さとみ】芳香剤入りの造花よ・・・" 0 "の家のトイレにもかけたら？")
         (wait)
         (text #:color 7 "【" 0 "】やだよ、俺は男だぜ・・・トイレに花なんて女の子みたいだ。")
         (wait)))
       (else (<>)))
      (set-reg: 21 1)))
    ((&& (== V 1) (== N 17) (== (: 21) 1))
     (<>
      (text #:color 7 "【" 0 "】芳香剤入りの造花か・・・横にトイレがあるから、飾ってあるのかな？")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<> (text #:color 6 "【さとみ】" 0 "って、色々と真剣に考えるのね・・・考えなくてもいい事まで。") (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<>
         (text #:color 6 "【さとみ】トイレの横だから飾ってある訳じゃなくて・・・もう説明するのが面倒だわ。")
         (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 18) (== (: 22) 0))
     (<>
      (text #:color 7 "【" 0 "】トイレのドアだな・・・何回か利用した事があるぞ。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<> (text #:color 6 "【さとみ】" 0 "・・・用を足したら、ちゃんと流さないとだめよ。") (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<> (text #:color 6 "【さとみ】" 0 "って、駅のトイレを使わないでここに来るのよね。") (wait)))
       (else (<>)))
      (set-reg: 22 1)))
    ((&& (== V 1) (== N 18) (== (: 22) 1))
     (<>
      (text #:color 7 "【" 0 "】だからトイレのドアだ。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<>
         (text #:color 6 "【さとみ】トイレットペーパーは、２０センチまでよ。")
         (wait)
         (text #:color 7 "【" 0 "】さとみ、いつから小姑になったんだ？")
         (wait)
         (text #:color 6 "【さとみ】やーね、冗談よ。")
         (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<>
         (text #:color 6 "【さとみ】いいわよ、使っても。")
         (wait)
         (text #:color 7 "【" 0 "】今は大も小もしたくない。")
         (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 21) (== (: 27) 0) (== (: 419) 0))
     (<>
      (text #:color 7 "【" 0 "】さとみ、いつから白髪になったんだ？")
      (wait)
      (text #:color 6 "【さとみ】白髪？・・・変な事を言わないでよ、光線のかげんじゃない？")
      (wait)
      (set-reg: 27 1)))
    ((&& (== V 1) (== N 21) (== (: 27) 1) (== (: 419) 0))
     (<>
      (text #:color 7 "【" 0 "】さとみって、昔からショートなんだよな・・・俺はロングが好きなんだけど。")
      (wait)
      (text #:color 6 "【さとみ】知ってるわよ、だから短くしているの。")
      (wait)
      (text #:color 7 "【" 0 "】あ・・・そう。")
      (wait)))
    ((&& (== V 1) (== N 21) (== (: 419) 1) (== (: 27) 0))
     (<>
      (text #:color 7 "【" 0 "】さとみって、髪の毛を伸ばした事があるのか？")
      (wait)
      (text #:color 6 "【さとみ】一度だけね・・・でもショートの方が似合うわよ。")
      (wait)
      (text #:color 7 "【" 0 "】そうかなあ・・・。")
      (wait)
      (set-reg: 27 1)))
    ((&& (== V 1) (== N 21) (== (: 419) 1) (== (: 27) 1))
     (<>
      (text #:color 7 "【" 0 "】さとみって、長い髪も似合うんじゃないか？")
      (wait)
      (text #:color 6 "【さとみ】そうかしら・・・今度、伸ばしてみようかな。")
      (wait)))
    ((&& (== V 1) (== N 22) (== (: 28) 0) (== (: 419) 0))
     (<>
      (text #:color 7 "【" 0 "】あれれ！？・・・ノドボトケがあるんじゃないか？")
      (wait)
      (text #:color 6 "【さとみ】同じ事をもう一度言ってごらんなさい・・・二度と喫茶店に来れない身体にしてあげる。")
      (wait)
      (text #:color 7 "【" 0 "】おー、恐い。")
      (wait)
      (set-reg: 28 1)))
    ((&& (== V 1) (== N 22) (== (: 28) 1) (== (: 419) 0))
     (<>
      (text #:color 7 "【" 0 "】へえ・・・首だけは女っぽいな。")
      (wait)
      (text #:color 6 "【さとみ】首だけは余計よ・・・" 0 "が想像できないくらい、私は女っぽいのよ。")
      (wait)))
    ((&& (== V 1) (== N 22) (== (: 419) 1) (== (: 28) 0))
     (<>
      (text #:color 6 "【さとみ】なによ・・・じっと見ちゃって。")
      (wait)
      (text #:color 7 "【" 0 "】いいじゃないか、減るもんじゃないだろ？")
      (wait)
      (set-reg: 28 1)))
    ((&& (== V 1) (== N 22) (== (: 419) 1) (== (: 28) 1))
     (<>
      (text #:color 6 "【さとみ】もう・・・首を見つめないで。")
      (wait)
      (text #:color 7 "【" 0 "】あ・・・わかった？")
      (wait)))
    ((&& (== V 1) (== N 24) (== (: 29) 0) (== (: 419) 0))
     (<>
      (text #:color 7 "【" 0 "】さとみって、太っているか痩せているのか・・・よくわからないよな。")
      (wait)
      (text #:color 6 "【さとみ】知っているのは私の彼氏だけ・・・ふふふ。")
      (wait)
      (text #:color 7 "【" 0 "】ちぇっ、のろけちゃってさあ。")
      (wait)
      (set-reg: 29 1)))
    ((&& (== V 1) (== N 24) (== (: 29) 1) (== (: 419) 0))
     (<>
      (text #:color 7 "【" 0 "】髪型もボーイッシュだが、服装もボーイッシュだな・・・スカートをはいた事がないんじゃないか？")
      (wait)
      (text #:color 6 "【さとみ】失礼ね・・・スカートの方が好きなくらいよ。")
      (wait)))
    ((&& (== V 1) (== N 24) (== (: 419) 1) (== (: 29) 0))
     (<>
      (text #:color 7 "【" 0 "】（こうして見ると・・・女性らしいよな。）")
      (wait)
      (set-reg: 29 1)))
    ((&& (== V 1) (== N 24) (== (: 419) 1) (== (: 29) 1))
     (<>
      (text #:color 6 "【さとみ】" 0 "・・・どこを見てるの？")
      (wait)
      (text #:color 7 "【" 0 "】さとみの身体。")
      (wait)
      (text #:color 6 "【さとみ】いやらしいなあ・・・もう。")
      (wait)))
    ((&& (== V 1) (== N 25) (== (: 31) 0) (== (: 419) 0))
     (<>
      (text #:color 7 "【" 0 "】さとみって、よく見ると美人なんだよな・・・。")
      (wait)
      (text #:color 6 "【さとみ】今ごろ気づいたの？・・・よく見なくても美人よ。")
      (wait)
      (set-reg: 31 1)))
    ((&& (== V 1) (== N 25) (== (: 31) 1) (== (: 419) 0))
     (<>
      (text #:color 7 "【" 0 "】俺の事を見ている・・・気があるんじゃないか？")
      (wait)
      (text #:color 6 "【さとみ】どこからそういう結論が出るのかな・・・私には自信過剰としか思えないけど。")
      (wait)))
    ((&& (== V 1) (== N 25) (== (: 419) 1) (== (: 31) 0))
     (<>
      (text #:color 7 "【" 0 "】じいいいい・・・。")
      (wait)
      (text #:color 6 "【さとみ】や、やめてよ・・・恥ずかしいじゃない。")
      (wait)
      (set-reg: 31 1)))
    ((&& (== V 1) (== N 25) (== (: 419) 1) (== (: 31) 1))
     (<>
      (text #:color 7 "【" 0 "】じいいいいっ！！")
      (wait)
      (text #:color 6 "【さとみ】やだ・・・もう。")
      (wait)
      (text #:color 7 "【" 0 "】へえ・・・さとみでも、照れる事があるんだ。")
      (wait)))
    ((&& (== V 5) (== N 19) (== (: 23) 0))
     (<>
      (text #:color 7 "【" 0 "】開けるって・・・俺はトイレに行きたくないぜ。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<>
         (text #:color 6 "【さとみ】歳をとると、トイレが近くなるのよねー。")
         (wait)
         (text #:color 7 "【" 0 "】一週間も便秘するよりはマシだぜ・・・なあ、さとみ？")
         (wait)
         (text #:color 6 "【さとみ】うるさいわね、今は快眠快便だもん。")
         (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<> (text #:color 6 "【さとみ】だったら、ドアを開ける必要はないわね・・・。") (wait)))
       (else (<>)))
      (set-reg: 23 1)))
    ((&& (== V 5) (== N 19) (== (: 23) 1))
     (<>
      (text #:color 7 "【" 0 "】だからあ、俺はトイレに用はない。")
      (wait)
      (cond
       ((&& (== (: 179) 0) (== (: 419) 0))
        (<> (text #:color 6 "【さとみ】用がないなら、ドアを開けないでよ・・・他にお客さんがいるんだからね。") (wait)))
       ((&& (== (: 179) 0) (== (: 419) 1))
        (<> (text #:color 6 "【さとみ】" 0 "って、用もないのにドイレのドアを開けるの？") (wait)))
       (else (<>)))))
    ((&& (== V 9) (== N 23) (== (: 30) 0) (== (: 419) 0))
     (<>
      (text #:color 6 "【さとみ】ちょっと・・・何をするつもり！？")
      (wait)
      (text #:color 7 "【" 0 "】さとみ、俺様が胸をもんで大きくしてあげよう。")
      (wait)
      (text #:color 6 "【さとみ】冗談じゃないわよ、どうして" 0 "に胸を触られないといけないの？")
      (wait)
      (set-reg: 30 1)))
    ((&& (== V 9) (== N 23) (== (: 30) 1) (== (: 419) 0))
     (<>
      (text #:color 6 "【さとみ】" 0 "・・・友人として忠告するわ。")
      (wait)
      (text #:color 6 "【さとみ】よしなさい。")
      (wait)))
    ((&& (== V 9) (== N 23) (== (: 419) 1) (== (: 30) 0))
     (<>
      (text #:color 7 "【" 0 "】（うーん・・・冗談でもできなくなってしまった。）")
      (wait)
      (set-reg: 30 1)))
    ((&& (== V 9) (== N 23) (== (: 419) 1) (== (: 30) 1))
     (<> (text #:color 7 "【" 0 "】（触りたい・・・けど、触れない。）") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))