(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\。
  #\い
  #\な
  #\っ
  #\、
  #\は
  #\だ
  #\ん
  #\て
  #\の
  #\か
  #\る
  #\う
  #\あ
  #\よ
  #\に
  #\！
  #\た
  #\し
  #\と
  #\ち
  #\ゃ
  #\さ
  #\？
  #\ら
  #\く
  #\が
  #\も
  #\れ
  #\で
  #\こ
  #\ま
  #\ー
  #\み
  #\り
  #\お
  #\を
  #\や
  #\君
  #\そ
  #\じ
  #\事
  #\わ
  #\ね
  #\つ
  #\一
  #\子
  #\き
  #\ン
  #\ど
  #\俺
  #\け
  #\私
  #\す
  #\気
  #\言
  #\え
  #\夏
  #\ぜ
  #\ふ
  #\ろ
  #\行
  #\美
  #\プ
  #\茶
  #\時
  #\店
  #\ぞ
  #\ラ
  #\哉
  #\太
  #\郎
  #\め
  #\ル
  #\女
  #\入
  #\舞
  #\何
  #\人
  #\前
  #\喫
  #\『
  #\』
  #\ト
  #\穂
  #\Ｔ
  #\Ｉ
  #\Ｍ
  #\今
  #\書
  #\タ
  #\ょ
  #\間
  #\日
  #\げ
  #\ウ
  #\二
  #\ば
  #\大
  #\中
  #\ド
  #\Ｏ
  #\合
  #\ず
  #\出
  #\ご
  #\ッ
  #\見
  #\業
  #\む
  #\イ
  #\好
  #\健
  #\本
  #\フ
  #\持
  #\亜
  #\営
  #\レ
  #\明
  #\マ
  #\ロ
  #\思
  #\当
  #\方)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "29.pd8")
 (proc 15)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "29.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (cond
  ((== (: 172) 0)
   (<>
    (text #:color 7 "【" 0 "】ここは俺がよく来る喫茶店『ＯＴＩＭＴＩＭ』だ・・・『おてぃむてぃむ』って読むんだぜ。")
    (wait)
    (text
     #:color
     7
     "【"
     0
     "】この喫茶店で、さとみがアルバイトしているんだっけ・・・彼女と俺は妙に気が合うと言うか、まったく合わないと言うか・・・。")
    (wait)))
  ((&& (== (: 710) 0) (== H 830) (> T 800) (< T 1900) (== (: 733) 0))
   (<>
    (text #:color 7 "【" 0 "】ふう・・・明日で夏休みも終りかあ。")
    (wait)
    (text #:color 5 "【男の声】" 0 "君。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】げっ！？・・・またマタロウか。")
    (wait)
    (text #:color 5 "【太郎】ふっふっふっ・・・今日は君に、僕の彼女を紹介しようと思ってな。")
    (wait)
    (text #:color 7 "【" 0 "】彼女！？・・・マタロウに！？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "f.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 2)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 27)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【美穂】こんにちは、" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】げえーーっ！？")
    (wait)
    (text #:color 5 "【太郎】まあそういう訳だ・・・これからもよろしく頼むよ、" 0 "君。")
    (wait)
    (text #:color 6 "【美穂】太郎君ったらね、私のあとをつけるほど好きなんだって・・・私の事が。")
    (wait)
    (text #:color 6 "【美穂】私、その事を聞いて感激しちゃったの。")
    (wait)
    (text #:color 7 "【" 0 "】ち、ちょっと違うような気が・・・する。")
    (wait)
    (text #:color 5 "【太郎】負け惜しみか、" 0 "君・・・ふっふっふっ。")
    (wait)
    (text #:color 6 "【美穂】じゃあね・・・私達、これからデートなの。")
    (wait)
    (text #:color 5 "【太郎】僕達はこれで失敬するよ・・・ふっふっふっ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】はあ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ふう・・・。")
    (wait)
    (text #:color 7 "【" 0 "】どうして・・・こうなるの？")
    (wait)
    (set-reg: 733 1)
    (set-reg: 102 (- (: 102) 5))))
  ((&& (== (: 753) 1) (== H 830) (> T 800) (< T 1900) (== (: 760) 0))
   (<>
    (slot 1 6)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "v14.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "v14an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "v14.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (animate 0 8 1)
    (animate 4 8)
    (sound 1)
    (set-var I 24)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・！？")
    (wait)
    (text #:color 4 "【健二】はーっはっはっはっはっ！！")
    (wait)
    (text #:color 3 "【舞】・・・。")
    (wait)
    (text #:color 4 "【健二】そういう事だよ、" 0 "君。")
    (wait)
    (text #:color 3 "【舞】・・・。")
    (wait)
    (text #:color 4 "【健二】そう、これでいいのさ！！")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 4 "【健二】何も言えないだろう、言葉などあるはずがないもんな、はーっはっはっはっ！！")
    (wait)
    (text #:color 3 "【舞】・・・。")
    (wait)
    (text #:color 4 "【健二】" 0 "君、もう舞に手を出すなよ・・・彼女は僕とつき合うと言ってくれたんだからな。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 4 "【健二】じゃあな、" 0 "君・・・ホテルに行こう、舞。")
    (wait)
    (text #:color 3 "【舞】はい・・・。")
    (wait)
    (slot 1 2)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なんで・・・こうなるの？")
    (wait)
    (set-reg: 760 1)
    (set-reg: 111 (- (: 111) 5))))
  ((&& (== (: 378) 0) (== (: 262) 1) (> T 1900) (== (: 412) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれれ！？・・・さとみじゃないか。")
    (wait)
    (text #:color 6 "【さとみ】" 0 "・・・もう店はおしまいよ。")
    (wait)
    (text #:color 7 "【" 0 "】そうか、そうだよな・・・。")
    (wait)
    (text #:color 6 "【さとみ】一人暮しの私の部屋で、一緒にお茶でも飲む？")
    (wait)
    (text #:color 7 "【" 0 "】え！？・・・ほ、本当！？")
    (wait)
    (text #:color 6 "【さとみ】ははははっ！！" 0 "、しっかりしてよ・・・私がいつ一人暮ししたのよ。")
    (wait)
    (text #:color 7 "【" 0 "】ははは、俺もついつい言葉の内容だけに気を取られて、さとみが言ってる事を忘れてた。")
    (wait)
    (text #:color 6 "【さとみ】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 6 "【さとみ】じゃあ・・・ね。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】さとみのやつ・・・怒ったのかな？")
    (wait)
    (set-reg: 378 1)))
  ((&&
    (== (: 379) 0)
    (== (: 222) 1)
    (== (: 361) 1)
    (== (: 151) 0)
    (> T 800)
    (< T 2300))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "jan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 2 "【女の人】あ・・・ごめんなさい、ぶつかったかしら？")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (text #:color 2 "【女の人】？？？")
    (wait)
    (text #:color 7 "【" 0 "】じいいいい・・・。")
    (wait)
    (text #:color 2 "【女の人】わ、私・・・急ぎますから。")
    (wait)
    (text #:color 7 "【" 0 "】俺と・・・デートしてくれ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】ちっ・・・逃げられちまった。")
    (wait)
    (set-reg: 379 1)))
  ((&&
    (== (: 379) 0)
    (== (: 222) 1)
    (== (: 361) 1)
    (== (: 151) 1)
    (> T 1900)
    (== (: 480) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "jan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれ、夏子さん。")
    (wait)
    (text #:color 2 "【夏子】びっくりした・・・" 0 "君じゃない。")
    (wait)
    (text #:color 7 "【" 0 "】仕事は・・・もう終ってるよな、ははは。")
    (wait)
    (text #:color 2 "【夏子】仕事は７時迄よ、前に言わなかったかしら？")
    (wait)
    (text #:color 7 "【" 0 "】じゃあ今はフリータイムだから、俺と一緒にお茶しない？")
    (wait)
    (text #:color 2 "【夏子】ごめんなさい、今お茶したばかりなの・・・それに、学校の課題も大変だし。")
    (wait)
    (text #:color 7 "【" 0 "】わかった、その課題とやらを持って、俺と一緒にホテルでやろう。")
    (wait)
    (text #:color 2 "【夏子】いけないわ、急いで家に帰らないと・・・" 0 "君も、夏休みの宿題は早目にやった方がいいわよ、じゃあね。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】ちっ・・・逃げられちまった。")
    (wait)
    (set-reg: 379 1)))
  ((&& (== (: 380) 0) (== (: 306) 1) (> T 800) (< T 1900) (== (: 745) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "v.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "van.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "v.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 24)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ま、ま、ま、舞ちゃんっ！！")
    (wait)
    (text #:color 3 "【舞】びっくりした・・・" 0 "君、脅かさないで。")
    (wait)
    (text #:color 7 "【" 0 "】舞ちゃん・・・まさか、健二と一緒に喫茶店でお茶してたなんて言わないよね？")
    (wait)
    (text #:color 3 "【舞】違うわよ、私、健二君と二人っきりになった事がないから。")
    (wait)
    (text #:color 7 "【" 0 "】じゃあ、俺と一緒にお茶しようよ・・・いいだろ？")
    (wait)
    (text #:color 3 "【舞】誘ってくれるのはうれしいけど、また今度にしましょ？・・・じゃあね、" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】うーん・・・舞ちゃんは、俺に好意を持ってないのかな？")
    (wait)
    (set-reg: 380 1)))
  ((&& (== (: 381) 0) (== (: 306) 1) (> T 800) (< T 1900))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】なんだか、いきなり走り出したくなったぞ。")
    (wait)
    (text #:color 5 "【太郎】友よ、会いたかったぞ。")
    (wait)
    (text #:color 7 "【" 0 "】マタロウ、競争しようぜ。")
    (wait)
    (text #:color 5 "【太郎】やっと僕の事を友と認めてくれたんだな・・・いいだろう、適度な運動は頭の血行を促進させる。")
    (wait)
    (text #:color 7 "【" 0 "】よーい・・・どんっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text
     #:color
     7
     "【"
     0
     "】マタロウのやつ、後ろも振り返らないで一心不乱に走ってるぜ・・・勉強はマタロウの方が上だが、悪知恵は俺様にかなうまい。")
    (wait)
    (set-reg: 381 1)))
  ((&& (== (: 687) 1) (> T 800) (< T 2100) (== (: 688) 0) (== (: 690) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "l.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "lan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "l.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 3 "【美沙】" 0 "・・・。")
    (wait)
    (text #:color 7 "【" 0 "】よう・・・セーラー服少女。")
    (wait)
    (text #:color 3 "【美沙】喫茶店でお茶を飲んでる場合か？")
    (wait)
    (text #:color 7 "【" 0 "】いきなりなんだよ・・・美沙、最近ずーっと生理なんじゃないか？")
    (wait)
    (text #:color 3 "【美沙】ふんっ！！お前みたいなやつは・・・。")
    (wait)
    (text #:color 7 "【" 0 "】好き？")
    (wait)
    (text #:color 3 "【美沙】も、もう・・・知らないっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】うーん・・・美沙のやつ、絶対に生理が止まらないに違いない。")
    (wait)
    (set-reg: 688 1)))
  ((&& (== (: 481) 1) (> H 818) (> T 800) (< T 1900) (== (: 511) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "q.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "qan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "q.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【くるみ】あ・・・" 0 "さんだ。")
    (wait)
    (text #:color 7 "【" 0 "】やあ、くるみちゃん・・・一人で喫茶店に入っちゃいけないよ。")
    (wait)
    (text #:color 6 "【くるみ】私・・・子供じゃないもん。")
    (wait)
    (text #:color 7 "【" 0 "】ははは、背伸びしたい気持ちはわかるけどさ・・・男の前で脚を広げられるまでは子供だな、うん。")
    (wait)
    (text #:color 6 "【くるみ】脚を広げるって・・・どういう事？")
    (wait)
    (text #:color 7 "【" 0 "】だからあ、男の前で脚を広げるって事は・・・ああ、説明するのがめんどくさい。")
    (wait)
    (text #:color 7 "【" 0 "】そうだ、言葉よりも実戦で説明した方が早いな・・・これから一緒にホテルに行こう。")
    (wait)
    (text #:color 6 "【くるみ】" 0 "さんのエッチ！！")
    (wait)
    (text #:color 7 "【" 0 "】はっはっはっ、でも俺と話をすると元気になるだろ？")
    (wait)
    (text #:color 6 "【くるみ】うん・・・。")
    (wait)
    (text #:color 7 "【" 0 "】よかった、よかった・・・はっはっはっ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】はっはっはっ・・・は？")
    (wait)
    (text #:color 7 "【" 0 "】くるみちゃーん。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なんだよ・・・どこに行ったんだ、ちっ！！")
    (wait)
    (set-reg: 511 1)))
  ((&& (== (: 419) 1) (== (: 429) 0) (> T 1900) (< T 2359) (> H 824))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "p.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "pan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "p.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 42)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【さとみ】・・・" 0 "？")
    (wait)
    (text #:color 7 "【" 0 "】あれれ・・・さとみ。")
    (wait)
    (text #:color 6 "【さとみ】暗くて、最初は誰だかわからなかったわ。")
    (wait)
    (text #:color 7 "【" 0 "】これから帰るのか？")
    (wait)
    (text #:color 6 "【さとみ】うん、今日も一日終っちゃったわねー・・・夏休みもあと少しでおしまいだし。")
    (wait)
    (text #:color 7 "【" 0 "】ああ・・・。")
    (wait)
    (text #:color 6 "【さとみ】宿題、ちゃんとやってる？")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・俺に聞くのが間違いだよ。")
    (wait)
    (text #:color 6 "【さとみ】私だって、自慢じゃないけど何もしてないのよ・・・今年の夏は色々とあったし・・・ね。")
    (wait)
    (text #:color 7 "【" 0 "】マタロウに見せてもらおうぜ。")
    (wait)
    (text #:color 6 "【さとみ】あははは・・・太郎君は、" 0 "の事が好きなのよ。")
    (wait)
    (text #:color 7 "【" 0 "】よせよ、気持ち悪い。")
    (wait)
    (text
     #:color
     6
     "【さとみ】さーてと、帰ってお風呂に入って、ちょっとだけ宿題をやって、それから寝ようっと・・・じゃあね、"
     0
     "。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】本当に、夏休みもあと少しで終りだよな・・・なんだかアセってくるぜ。")
    (wait)
    (set-reg: 429 1)))
  ((&& (== (: 753) 1) (> H 824) (> T 800) (< T 2000) (== (: 754) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "v.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "van.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "v.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 24)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あ・・・舞ちゃんっ！！")
    (wait)
    (text #:color 3 "【舞】安心して、" 0 "君・・・だんだん嫌いになれそうだから。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】お、おーいっ！！")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】はあ・・・。")
    (wait)
    (set-reg: 111 (- (: 111) 1))
    (set-reg: 754 1)))
  ((&& (== (: 603) 1) (> H 829) (> T 1900) (== (: 680) 0))
   (<>
    (text #:color 7 "【" 0 "】ふう・・・かわいい女の子でもいないかな？")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】おっ！！・・・あの後ろ姿はなかなかよさそうだぜ。")
    (wait)
    (text #:color 7 "【" 0 "】おねーさんっ！！・・・これからどこかに行くのっ！？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "t.pd8")
    (proc 16)
    (set-arr~ @ 7 0)
    (set-arr~ @ 6 1)
    (image "tan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "t.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 3)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 2 "【亜子】" 0 "君・・・こんばんは。")
    (wait)
    (text #:color 7 "【" 0 "】あ、あ、あ、あ、亜子さんっ！？")
    (wait)
    (text #:color 2 "【亜子】私・・・いつから" 0 "君のお姉さんになったのかしら？")
    (wait)
    (text #:color 7 "【" 0 "】い、いや・・・亜子さんは歳上だから、お姉さんだろ？")
    (wait)
    (text #:color 2 "【亜子】" 0 "君・・・私との約束を覚えてる？")
    (wait)
    (text #:color 7 "【" 0 "】も、もちろんさあ。")
    (wait)
    (text #:color 2 "【亜子】よかった・・・。")
    (wait)
    (text #:color 7 "【" 0 "】うん、よかった。")
    (wait)
    (text #:color 2 "【亜子】" 0 "君もちゃんと帰ってね・・・夜の街は誘惑が多いから、出歩いちゃだめ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】おやすみ・・・亜子さん。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】し、心臓が止まるかと思ったぜえ・・・はあはあはあ。")
    (wait)
    (set-reg: 680 1)))
  ((&&
    (== (: 539) 1)
    (== (: 547) 1)
    (> H 827)
    (> T 1000)
    (< T 1900)
    (== (: 533) 0)
    (== (: 527) 0)
    (== (: 548) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j11.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】夏子さん！！")
    (wait)
    (text #:color 2 "【夏子】" 0 "君・・・最近、よく会うわね。")
    (wait)
    (text #:color 7 "【" 0 "】やっぱり縁があるんだよ、うんうん。")
    (wait)
    (text #:color 2 "【夏子】" 0 "君は、これからどこかに行くのかしら？")
    (wait)
    (text #:color 7 "【" 0 "】暇だぜ俺は・・・どこにでもつき合うけど。")
    (wait)
    (text #:color 2 "【夏子】ごめんね、私は用があるの・・・これから友達の家でパーティーがあるのよ、じゃあね！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ちっ、何がパーティーだよ・・・日本のパーティーは、正月だけで十分だぞ。")
    (wait)
    (set-reg: 548 1)))
  ((&& (== (: 467) 1) (== (: 840) 0) (> H 822) (> T 800) (< T 1900))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n.pd8")
    (proc 16)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 6)
    (proc 26)
    (text #:color 7 "【" 0 "】あ・・・ちはるちゃん。")
    (wait)
    (text #:color 3 "【ちはる】" 0 "君じゃない・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 3 "【ちはる】なんだか照れるわね・・・変な気持ち。")
    (wait)
    (text #:color 7 "【" 0 "】ここで何をしてるの？")
    (wait)
    (text #:color 3 "【ちはる】今から用があって・・・そうだわ、急いで行かないと。")
    (wait)
    (text #:color 3 "【ちはる】じゃあね、" 0 "君・・・ばいばい！！")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・ち、ちょっと。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】行ってしまったよ・・・おい。")
    (wait)
    (set-reg: 840 1)))
  ((&& (== (: 479) 1) (== (: 840) 0) (> H 822) (> T 800) (< T 1900))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n.pd8")
    (proc 16)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 6)
    (proc 26)
    (text #:color 7 "【" 0 "】あ・・・ちはるちゃん。")
    (wait)
    (text #:color 3 "【ちはる】ふん！！")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・ち、ちょっと。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】行ってしまったよ・・・おい。")
    (wait)
    (set-reg: 840 1)))
  ((&&
    (== (: 716) 1)
    (== (: 726) 0)
    (> H 821)
    (> T 1000)
    (< T 1900)
    (== (: 728) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "man.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 27)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【美穂】あ・・・" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】美穂ちゃん・・・手紙、読んだぜ。")
    (wait)
    (text #:color 6 "【美穂】やだあ・・・恥ずかしい。")
    (wait)
    (text #:color 7 "【" 0 "】美穂ちゃん・・・。")
    (wait)
    (text #:color 6 "【美穂】" 0 "君、何も言わないで・・・お返事はいつでもいいから。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】あれれっ・・・行っちゃった。")
    (wait)
    (set-reg: 726 1)))
  ((&& (== (: 617) 1) (> H 824) (> T 1900) (== (: 627) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "uan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 59)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【やよい】" 0 "さん・・・こんばんは。")
    (wait)
    (text #:color 7 "【" 0 "】やよいさん、会いたかった・・・。")
    (wait)
    (text #:color 6 "【やよい】" 0 "さんって、そんな事ばかり言っているんですね。")
    (wait)
    (text #:color 7 "【" 0 "】何を言うんだ、俺がこんな事を言うのはやよいさんだけさ。")
    (wait)
    (text #:color 6 "【やよい】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】朝起きたら、一番最初に考える事は・・・やよいさんの事なんだ。")
    (wait)
    (text #:color 6 "【やよい】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】そして、寝る前に考える事は・・・必ずやよいさんの事さ。")
    (wait)
    (text #:color 6 "【やよい】私の胸が・・・大きいから？")
    (wait)
    (text #:color 7 "【" 0 "】違うよ・・・容姿で好きになったわけじゃない、中身が大好きなんだ。")
    (wait)
    (text #:color 6 "【やよい】ありがとう、うれしいですよ・・・すごく。")
    (wait)
    (text #:color 7 "【" 0 "】じゃあこれから・・・どこかに行こうよ。")
    (wait)
    (text #:color 6 "【やよい】ごめんなさいね、明日仕事だし・・・おやすみなさい、" 0 "さん。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】あらら・・・行っちゃった。")
    (wait)
    (text #:color 7 "【" 0 "】うーん、どうしてうまくいかないんだろ・・・精いっぱいくどいたのに。")
    (wait)
    (set-reg: 627 1)))
  ((&& (== (: 467) 1) (== (: 846) 0) (> H 825) (> T 800) (< T 1900))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n.pd8")
    (proc 16)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 6)
    (proc 26)
    (text #:color 3 "【ちはる】" 0 "君・・・また会っちゃったわね。")
    (wait)
    (text #:color 7 "【" 0 "】そんなにいやそうに言うなよう・・・傷つくじゃないか。")
    (wait)
    (text #:color 3 "【ちはる】" 0 "君って、私の気持ちがわかってないんだから・・・もう。")
    (wait)
    (text #:color 7 "【" 0 "】私の気持ちって、どんな気持ちだよ。")
    (wait)
    (text #:color 3 "【ちはる】私だってね・・・" 0 "君の事を考えてるのよ。")
    (wait)
    (text #:color 7 "【" 0 "】へ？")
    (wait)
    (text #:color 3 "【ちはる】もう・・・あなたって本当に不思議な男の子ね、忘れようとしても忘れられないんだから。")
    (wait)
    (text #:color 7 "【" 0 "】インパクトが強いからな・・・俺は。")
    (wait)
    (text #:color 3 "【ちはる】そうよ・・・それでまたこうして会っちゃうと、ますます忘れられなくなるわ。")
    (wait)
    (text #:color 3 "【ちはる】あんまり顔を見てると、夢に出てきそうだから・・・じゃあね、ばいばい！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】おーいっ！！")
    (wait)
    (text #:color 7 "【" 0 "】ちはるちゃーん！！")
    (wait)
    (text #:color 7 "【" 0 "】行っちゃった・・・なんだよ、もう。")
    (wait)
    (set-reg: 846 1)))
  ((&& (== (: 483) 1) (== (: 492) 0) (> T 800) (< T 1900) (== (: 514) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j12.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j11.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】なんだ・・・一哉じゃないか。")
    (wait)
    (text #:color 5 "【一哉】いやあ、まいっちゃうぜ・・・くるみには。")
    (wait)
    (text #:color 7 "【" 0 "】何がだ？")
    (wait)
    (text #:color 5 "【一哉】電話がかかって来ても無視してたんだけど・・・この間、俺自身が取っちゃってさ。")
    (wait)
    (text #:color 7 "【" 0 "】ふんふん。")
    (wait)
    (text #:color 5 "【一哉】そうしたら、『最近の一哉君、絶対におかしい』って言われちゃって。")
    (wait)
    (text #:color 7 "【" 0 "】当然だな。")
    (wait)
    (text #:color 5 "【一哉】私の事が嫌いになった？・・・とか聞くから、俺は答えてやったんだ。")
    (wait)
    (text #:color 7 "【" 0 "】うんうん、なんて？")
    (wait)
    (text #:color 5 "【一哉】好きだよって。")
    (wait)
    (text #:color 7 "【" 0 "】ははははっ！！")
    (wait)
    (text #:color 5 "【一哉】笑うなよ、ついつい言っちゃったんだよ・・・そうしたら、くるみのやつ電話の向こうで泣き出しちゃってさあ。")
    (wait)
    (text #:color 7 "【" 0 "】いやあ、一哉も一人前になりつつあるな。")
    (wait)
    (text #:color 5 "【一哉】冗談じゃないよ、俺は一刻も早く夏子さんとつき合えるようになって・・・くるみと完全に手を切りたいんだ。")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・くるみちゃんだ。")
    (wait)
    (text #:color 5 "【一哉】ぎくうっ！！")
    (wait)
    (text #:color 7 "【" 0 "】嘘。")
    (wait)
    (text #:color 5 "【一哉】はあはあはあはあ。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 5 "【一哉】はあはあはあはあ・・・" 0 "、言っていい嘘と悪い嘘があるぞ。")
    (wait)
    (text #:color 7 "【" 0 "】ははは。")
    (wait)
    (text #:color 5 "【一哉】お、俺はもう行くぞ・・・心臓が止まるかと思った。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】行ってしまったよ・・・おい。")
    (wait)
    (set-reg: 492 1)))
  ((&& (== (: 581) 1) (> H 820) (> T 800) (< T 2359) (== (: 593) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "e.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ean.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "e.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 22)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】かおり・・・さん？")
    (wait)
    (text #:color 6 "【かおり】" 0 "君じゃない・・・何をしてるの？")
    (wait)
    (text #:color 7 "【" 0 "】ははは、ブラブラとしてるだけだぜ・・・。")
    (wait)
    (text #:color 6 "【かおり】ブラブラするのは、おポコチンだけにしなさいね・・・暇なら勉強をしなさいよ。")
    (wait)
    (text #:color 7 "【" 0 "】え！？")
    (wait)
    (text #:color 6 "【かおり】だから、勉強をしなさいよ。")
    (wait)
    (text #:color 7 "【" 0 "】え！？")
    (wait)
    (text #:color 6 "【かおり】" 0 "君が、ちゃんと学校を卒業してくれないと・・・私とつき合えないって事。")
    (wait)
    (text #:color 7 "【" 0 "】どうしてだよ、今でも十分つき合えるぜ。")
    (wait)
    (text #:color 6 "【かおり】私がいやなのよ、学生とはつき合いたくないの・・・いくら好きでもね。")
    (wait)
    (text #:color 7 "【" 0 "】よくわからないけど、過去に暗い思い出があるに違いない。")
    (wait)
    (text #:color 6 "【かおり】ほらあ、こんな所で立ち話なんかするから・・・約束に遅れそうじゃない。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】胸をゆさゆさ揺すりながら行ってしまった。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "e.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ean.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "e.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 22)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ぎょっ！？")
    (wait)
    (text #:color 6 "【かおり】ち、ちょっと、そんな言い方をされたら、まるで私がデブみたいじゃない。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】かおりさんも、けっこう暇なんじゃないか？")
    (wait)
    (set-reg: 593 1)))
  ((&&
    (== (: 488) 1)
    (== (: 491) 0)
    (> T 800)
    (< T 1900)
    (== (: 498) 0)
    (== (: 539) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j11.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 2 "【夏子】" 0 "君っ！！")
    (wait)
    (text #:color 7 "【" 0 "】夏子さんっ！！")
    (wait)
    (text #:color 2 "【夏子】元気ね・・・一哉君の言う通りだわ。")
    (wait)
    (text #:color 7 "【" 0 "】何が？")
    (wait)
    (text #:color 2 "【夏子】" 0 "君って、元気じゃない時がないって・・・つまり、いつも元気って事。")
    (wait)
    (text #:color 7 "【" 0 "】それじゃ、まるで馬鹿じゃないか・・・俺だって落ち込む事ぐらいあるんだぜ。")
    (wait)
    (text #:color 2 "【夏子】" 0 "君って、落ち込むとどうなるのかしら？")
    (wait)
    (text #:color 7 "【" 0 "】えーと・・・えーと・・・すいぶん前の事だから思い出せない。")
    (wait)
    (text #:color 2 "【夏子】あはははっ・・・おもしろい子だわ、" 0 "君って。")
    (wait)
    (text #:color 7 "【" 0 "】（ちくしょう・・・俺の事を子供扱いしてるな。）")
    (wait)
    (text #:color 2 "【夏子】あ・・・いけない、もう行かないと。")
    (wait)
    (text #:color 7 "【" 0 "】まだいいじゃないかよう。")
    (wait)
    (text #:color 2 "【夏子】ごめんなさい、用があるから・・・それじゃあ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】くんか、くんか・・・いい匂いがする。")
    (wait)
    (text #:color 7 "【" 0 "】夏子さんの香水の匂いだ・・・なんてアダルトな香りなんだろう。")
    (wait)
    (set-reg: 498 1)))
  ((&&
    (== (: 718) 1)
    (> H 824)
    (> T 1000)
    (< T 1900)
    (== (: 723) 0)
    (== (: 728) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "m.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "man.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 27)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【美穂】あ・・・" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】頼むから、俺から逃げないでくれよう。")
    (wait)
    (text #:color 6 "【美穂】だって・・・まだ心の準備ができてないの。")
    (wait)
    (text #:color 7 "【" 0 "】俺はできてるんだよう。")
    (wait)
    (text #:color 6 "【美穂】" 0 "君も・・・手紙で返事をして。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】おいおい、俺は年賀状も書かないようなやつだぜ・・・手紙なんて御免だよ。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なんだ・・・またかよ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【太郎】" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】うわわわわっ！！")
    (wait)
    (text #:color 5 "【太郎】ここで・・・何をしているのだ？")
    (wait)
    (text #:color 7 "【" 0 "】な、何って・・・見ての通りだよ。")
    (wait)
    (text #:color 5 "【太郎】立っているのか？")
    (wait)
    (text #:color 7 "【" 0 "】そうだ、俺は立ってるんだ。")
    (wait)
    (text #:color 5 "【太郎】一人でか？")
    (wait)
    (text #:color 7 "【" 0 "】二人に見えるか？・・・メガネを変えた方がいいぞ。")
    (wait)
    (text #:color 5 "【太郎】" 0 "君・・・邪魔して悪かったな。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】美穂ちゃんは行っちゃうし、マタロウには会っちゃうし・・・まいったな。")
    (wait)
    (set-reg: 723 1)))
  ((&& (== (: 598) 1) (> H 820) (> T 1900) (== (: 613) 0) (== (: 617) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "u.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "uan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "u.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 59)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【やよい】あ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あれれ・・・やよいさん。")
    (wait)
    (text #:color 6 "【やよい】こんばんわ・・・夜になると、少しは涼しくなりますね。")
    (wait)
    (text #:color 7 "【" 0 "】ははは、そうだね・・・。")
    (wait)
    (text #:color 6 "【やよい】それじゃあ私はこれで・・・お大事に。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】お大事に、か・・・俺は病人じゃないんだけどな。")
    (wait)
    (set-reg: 613 1)))
  ((&&
    (== (: 519) 1)
    (== (: 522) 0)
    (> H 827)
    (> T 800)
    (< T 1900)
    (== (: 527) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "r.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ran.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "r.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【くるみ】" 0 "さん！！")
    (wait)
    (text #:color 7 "【" 0 "】び、びっくり・・・した。")
    (wait)
    (text #:color 6 "【くるみ】はあはあ・・・" 0 "さんの姿を見て、走ってきちゃった。")
    (wait)
    (text #:color 7 "【" 0 "】くるみちゃんとは思えない、大きな声だったな。")
    (wait)
    (text #:color 6 "【くるみ】やだ・・・そんなに大きかった？")
    (wait)
    (text #:color 7 "【" 0 "】なあ、一つ聞きたいんだけど・・・一哉の事はどうなったんだ？")
    (wait)
    (text #:color 6 "【くるみ】前に言わなかった？・・・もう電話もしてないし、家にも行ってないの。")
    (wait)
    (text #:color 7 "【" 0 "】で、どうするの？")
    (wait)
    (text #:color 6 "【くるみ】ううん、どうもしないわよ・・・くすくす。")
    (wait)
    (text #:color 7 "【" 0 "】な、なんだよう。")
    (wait)
    (text #:color 6 "【くるみ】だって・・・私より" 0 "さんの方が、一哉君の事を気にしてるんですもの・・・おっかしいの。")
    (wait)
    (text #:color 7 "【" 0 "】そりゃあ、気になるさ。")
    (wait)
    (text #:color 6 "【くるみ】どうして気になるの？")
    (wait)
    (text #:color 7 "【" 0 "】そ、そりゃあ・・・。")
    (wait)
    (text #:color 6 "【くるみ】あ、" 0 "さんの顔・・・赤い。")
    (wait)
    (text #:color 7 "【" 0 "】うるさいなあ。")
    (wait)
    (text #:color 6 "【くるみ】じゃあね、" 0 "さん・・・私、お母さんからお使い頼まれてるの。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】元気だなあ・・・本当に元気だ。")
    (wait)
    (set-reg: 522 1)))
  ((&&
    (== (: 728) 1)
    (== (: 710) 1)
    (> H 827)
    (< H 829)
    (> T 800)
    (< T 2359)
    (== (: 737) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ぎょっ！？")
    (wait)
    (text #:color 5 "【太郎】君達は・・・君達は・・・不潔だあっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】あらら、走って行っちゃったよ。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・転んでやんの。")
    (wait)
    (set-reg: 737 1)))
  ((&&
    (== (: 728) 1)
    (== (: 710) 0)
    (> H 827)
    (< H 829)
    (> T 800)
    (< T 2359)
    (== (: 737) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ぎょっ！？")
    (wait)
    (text #:color 5 "【太郎】ふっ・・・ふっふっ。")
    (wait)
    (text #:color 7 "【" 0 "】な、なんだよ・・・。")
    (wait)
    (text #:color 5 "【太郎】" 0 "君、君の負けだよ・・・ふっふっふっ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "29.pd8")
    (proc 15)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 50)
    (proc 26)
    (set-reg: 835 1)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なんだ、あいつ・・・気味が悪いやつだぜ。")
    (wait)
    (set-reg: 737 1)))
  ((== (: 172) 1)
   (<>
    (text #:color 7 "【" 0 "】ＯＴＩＭＴＩＭの前だぞ・・・中に入るのか？")
    (wait)
    (if (< T 959)
      (<>
       (text #:color 7 "【" 0 "】と言っても、営業時間外だな・・・中に入る事イコール、不法侵入って事になるぞ。")
       (wait)))
    (if (> T 1859)
      (<>
       (text #:color 7 "【" 0 "】と言っても、営業時間外だな・・・中に入る事イコール、不法侵入って事になるぞ。")
       (wait))))))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "他の場所に行く") (text "中に入る") (text "やめる")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・他の場所に行くか。")
         (wait)
         (set-var N 9)
         (set-reg: 172 1)
         (slot 1 2)
         (mes-jump "town1.mes")))
       ((&& (== N 2) (> T 1859))
        (<>
         (text #:color 7 "【" 0 "】この喫茶店の唯一の欠点は、営業時間が午後７時までって事だ・・・。")
         (wait)
         (text #:color 7 "【" 0 "】つまり、今の時間は営業してないって事だな・・・素直に諦めようぜ。")
         (wait)))
       ((&& (== N 2) (< T 959))
        (<>
         (text #:color 7 "【" 0 "】この喫茶店は、午前１０時から開くんだ・・・まだ中に入る事はできないな。")
         (wait)))
       ((&& (== N 2) (== (: 282) 1) (> H 810) (== (: 283) 0) (== (: 598) 0))
        (<>
         (text #:color 7 "【" 0 "】そうだな、さとみの顔でも見てやるか。")
         (wait)
         (sound 1)
         (set-var I 37)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 6 "ドスンッ！！")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "u.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "uan.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "u.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 59)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 7 "【" 0 "】い、いいかげんにしろ。")
         (wait)
         (text #:color 6 "【奇麗な女性】ごめんなさい・・・大丈夫？")
         (wait)
         (text #:color 7 "【" 0 "】大丈夫じゃないぞ。")
         (wait)
         (text #:color 6 "【奇麗な女性】よかったわ、大丈夫なのね・・・それじゃあ私は急ぎますから。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "29.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)
         (text #:color 7 "【" 0 "】人の言う事をまったく聞いてない。")
         (wait)
         (text #:color 7 "【" 0 "】気を取り直して、喫茶店の中に入ろう。")
         (wait)
         (sound 1)
         (set-var I 37)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 6 "ドスンッ！！")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "e.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "ean.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "e.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 22)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 7 "【" 0 "】おいっ！！")
         (wait)
         (cond
          ((== (: 217) 0)
           (<>
            (text #:color 6 "【またまた奇麗な女性】あ、ごめんね！！")
            (wait)
            (text #:color 7 "【" 0 "】な、なんなんだ！？")
            (wait)
            (text #:color 6 "【またまた奇麗な女性】怪我はないわよね、絶対にないわ・・・じゃあね！！")
            (wait)))
          ((== (: 217) 1)
           (<>
            (text #:color 6 "【かおり】あ、ごめんね！！")
            (wait)
            (text #:color 7 "【" 0 "】あ、あれ！？")
            (wait)
            (text #:color 6 "【かおり】怪我はないわよね・・・絶対にないわよね、よかった、じゃあね！！")
            (wait)))
          (else (<>)))
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "29.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 50)
         (proc 26)
         (set-reg: 835 1)
         (text #:color 7 "【" 0 "】な、なんなんだよ・・・俺に恨みでもあるのか！？")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】ちっ・・・気を取り直して喫茶店の中に入ろうぜ。")
         (wait)
         (set-reg: 283 1)
         (slot 1 2)
         (mes-jump "tim_in.mes")))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】よし、中に入ろう・・・。")
         (wait)
         (set-reg: 172 1)
         (slot 1 2)
         (mes-jump "tim_in.mes")))
       ((== N 3)
        (<> (text #:color 7 "【" 0 "】やめるって・・・ここにずっと立っているつもりか！？") (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 1) (== (: 172) 0))
     (<>
      (text #:color 7 "【" 0 "】店の前には、植え込みがある・・・ネコの死体を蹴り込んでも、誰も気が付かないだろう。")
      (wait)))
    ((&& (== V 1) (== N 1) (== (: 172) 1) (== (: 10) 0))
     (<>
      (text #:color 7 "【" 0 "】植木だな・・・。")
      (wait)
      (text #:color 7 "【" 0 "】そうだ、女の子に観葉植物をプレゼントする時は、この植木を拝借しようぜ。")
      (wait)
      (set-reg: 10 1)))
    ((&& (== V 1) (== N 1) (== (: 172) 1) (== (: 10) 1))
     (<> (text #:color 7 "【" 0 "】ただの植え込みだ・・・何度も見るもんじゃない。") (wait)))
    ((&& (== V 1) (== N 2) (== (: 172) 0))
     (<>
      (text #:color 7 "【" 0 "】メニューと書かれているな・・・まさか、ここで注文を取る訳じゃないだろうな？")
      (wait)))
    ((&& (== V 1) (== N 2) (== (: 172) 1) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】よくあるパターンだが、この喫茶店も昼時にはランチタイムがあるようだ・・・。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 1) (== N 2) (== (: 172) 1) (== (: 11) 1))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】えーと、Ａランチが『若鳥のクリーム煮定食』で、Ｂランチが『和風ハンバーグ定食』か・・・どっちもまずそうだ。")
      (wait)))
    ((&& (== V 1) (== N 3) (== (: 172) 0))
     (<> (text #:color 7 "【" 0 "】『ＯＴＩＭＴＩＭ』のドアだな・・・。") (wait)))
    ((&& (== V 1) (== N 3) (== (: 172) 1) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】ここのオーナーは怠慢だな・・・いつ来ても『ＯＰＥＮ』というプレートがさげてあるぞ。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 3) (== (: 172) 1) (== (: 12) 1))
     (<> (text #:color 7 "【" 0 "】ウェルカムか・・・どうして日本語で書かないんだ、この非国民め。") (wait)))
    ((&& (== V 1) (== N 4) (== (: 172) 0))
     (<> (text #:color 7 "【" 0 "】サンルーフだな・・・ようするに、『日除け』って事だぜ。") (wait)))
    ((&& (== V 1) (== N 4) (== (: 172) 1) (== (: 13) 0))
     (<>
      (text #:color 7 "【" 0 "】三角形のサンルーフだ・・・いつかいたずら書きをしてやろう。")
      (wait)
      (text #:color 7 "【" 0 "】俺のサインでも入れてやれば、この店の価値がグンと上がるってもんだな。")
      (set-reg: 13 1)))
    ((&& (== V 1) (== N 4) (== (: 172) 1) (== (: 13) 1))
     (<>
      (text #:color 7 "【" 0 "】俺様の部屋にぴったりのサンルーフだな。")
      (wait)
      (text #:color 7 "【" 0 "】と、言っても・・・俺の部屋にサンルーフをつける場所などないが、ははは。")
      (wait)))
    ((&& (== V 1) (== N 5) (== (: 172) 0))
     (<>
      (text #:color 7 "【" 0 "】置き看板だな・・・中には蛍光灯が入っているはずだ。")
      (wait)
      (text #:color 7 "【" 0 "】蛍光灯入りの看板を作るぐらいだったら、午後７時で店を閉めるなよ・・・２４時間営業にしろ。")
      (wait)))
    ((&& (== V 1) (== N 5) (== (: 172) 1) (== (: 14) 0))
     (<>
      (text #:color 7 "【" 0 "】このタイプの置き看板は、酔っぱらいによく蹴られるんだ・・・この看板の寿命も長くはないだろう。")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 1) (== N 5) (== (: 172) 1) (== (: 14) 1))
     (<>
      (text #:color 7 "【" 0 "】看板とかけて、店の人気者ととく・・・その心は？")
      (wait)
      (text #:color 7 "【" 0 "】『看板娘』・・・なんちゃってね。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】笑ってくれよう。")
      (wait)))
    ((&& (== V 1) (== N 6) (== (: 172) 0))
     (<>
      (text #:color 7 "【" 0 "】この建物の施工年月日が書かれている・・・普通はもっと、目立たない場所に張り付けてあるんだぜ。")
      (wait)))
    ((&& (== V 1) (== N 6) (== (: 172) 1) (== (: 15) 0))
     (<>
      (text #:color 7 "【" 0 "】施工年月日が書かれたプレートだ・・・興味がないぜ。")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 1) (== N 6) (== (: 172) 1) (== (: 15) 1))
     (<>
      (text #:color 7 "【" 0 "】こんなプレートを見ている時間があったら、壁に頬ずりしていた方がまだましだ。")
      (wait)))
    ((&& (== V 1) (== N 7) (== (: 172) 0))
     (<> (text #:color 7 "【" 0 "】営業時間が書いてあるプレートだ・・・金属の板でできているようだ。") (wait)))
    ((&& (== V 1) (== N 7) (== (: 172) 1) (== (: 16) 0))
     (<>
      (text #:color 7 "【" 0 "】営業時間に書いてあるプレートだ・・・午前１０時から、午後７時までと書いてある。")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 1) (== N 7) (== (: 172) 1) (== (: 16) 1))
     (<> (text #:color 7 "【" 0 "】プレートだな・・・営業時間を書き換えちゃおうか？") (wait)))
    ((&& (== V 1) (== N 8) (== (: 172) 0))
     (<>
      (text #:color 7 "【" 0 "】魔法のランプだな・・・こすると、絶世の美女が出てくるんだ。")
      (wait)
      (text #:color 7 "【" 0 "】うーん、俺って想像力がたくましいな・・・きっと小説家になれるぞ。")
      (wait)))
    ((&& (== V 1) (== N 8) (> T 1800) (< T 1900) (== (: 176) 0))
     (<>
      (text #:color 7 "【" 0 "】ランプだな・・・今は電気がついている。")
      (wait)
      (text #:color 2 "【ランプの精】まあ、私が明るくなっている時に気づいてくれるなんて・・・本当に久しぶりだわ。")
      (wait)
      (text #:color 7 "【" 0 "】だ、誰！？")
      (wait)
      (text #:color 2 "【ランプの精】みんな私が明るくなっても、気づいてくれないの・・・あなたって優しい人なのね。")
      (wait)
      (text #:color 7 "【" 0 "】まあな、みんなそう言うぜ。")
      (wait)
      (text #:color 2 "【ランプの精】これは私からのささやかなプレゼント・・・受けとってちょうだい。")
      (wait)
      (sound 1)
      (set-var I 58)
      (proc 26)
      (set-reg: 835 0)
      (set-var M (+ M 5000))
      (proc 11)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (sound 1)
      (set-var I 50)
      (proc 26)
      (set-reg: 835 1)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】何だったんだ？・・・今のは？")
      (wait)
      (set-reg: 176 1)))
    ((&& (== V 1) (== N 8) (> T 1800) (< T 1900) (== (: 176) 1))
     (<>
      (text #:color 7 "【" 0 "】ランプだ・・・明りがついているぞ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】おーーいっ！！ランプの精、出て来いっ！！")
      (wait)))
    ((&& (== V 1) (== N 8))
     (<> (text #:color 7 "【" 0 "】ランプだ・・・今は消えている。") (wait)))
    ((&& (== V 1) (== N 9) (== (: 172) 0))
     (<> (text #:color 7 "【" 0 "】ショップルーフだ・・・『ＣＯＦＦＥＥ　ＨＯＵＳＥ』と書かれているぞ。") (wait)))
    ((&& (== V 1) (== N 9) (== (: 172) 1) (== (: 17) 0))
     (<> (text #:color 7 "【" 0 "】ショップルーフだな・・・。") (wait) (set-reg: 17 1)))
    ((&& (== V 1) (== N 9) (== (: 172) 1) (== (: 17) 1))
     (<> (text #:color 7 "【" 0 "】だからショップルーフだって・・・そんなに興味があるのか？") (wait)))
    ((&& (== V 1) (== N 10) (== (: 172) 0))
     (<> (text #:color 7 "【" 0 "】ウィンドウには、『ＯＴＩＭＴＩＭ』と書かれているな。") (wait)))
    ((&& (== V 1) (== N 10) (== (: 172) 1) (== (: 18) 0))
     (<>
      (text #:color 7 "【" 0 "】『ＯＴＩＭＴＩＭ』・・・つまり、この喫茶店の名前だ。")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 1) (== N 10) (== (: 172) 1) (== (: 18) 1))
     (<> (text #:color 7 "【" 0 "】『ＯＴＩＭＴＩＭ』か・・・最低の名前だな。") (wait)))
    ((&& (== V 3) (== N 11) (== (: 172) 0))
     (<>
      (text #:color 6 "ドンドンドン・・・ピシッ！！")
      (wait)
      (text #:color 7 "【" 0 "】うーん・・・割れそうな音かするぞ。")
      (wait)))
    ((&& (== V 3) (== N 11) (== (: 172) 1) (== (: 19) 0))
     (<>
      (text #:color 6 "ドンドンドンッ！！・・・ピシピシッ！！")
      (wait)
      (text #:color 7 "【" 0 "】ほほう・・・そんなに厚くないガラスだぞ、さては経費を節約したな。")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 3) (== N 11) (== (: 172) 1) (== (: 19) 1))
     (<> (text #:color 7 "【" 0 "】はっはっはっ・・・これ以上たたくと、本当に割れちゃうぞ。") (wait)))
    ((&& (== V 1) (== N 12) (== (: 172) 0))
     (<> (text #:color 7 "【" 0 "】喫茶店だ・・・。") (wait)))
    ((&& (== V 1) (== N 12) (== (: 172) 1) (== (: 20) 0))
     (<> (text #:color 7 "【" 0 "】だから喫茶店だよ・・・。") (wait) (set-reg: 20 1)))
    ((&& (== V 1) (== N 12) (== (: 172) 1) (== (: 20) 1))
     (<> (text #:color 7 "【" 0 "】え？・・・何を見ようとしたんだ！？") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))