(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\。
  #\い
  #\っ
  #\な
  #\舞
  #\て
  #\！
  #\る
  #\あ
  #\ん
  #\か
  #\、
  #\（
  #\）
  #\の
  #\う
  #\？
  #\し
  #\だ
  #\よ
  #\も
  #\く
  #\に
  #\た
  #\ゃ
  #\が
  #\君
  #\ら
  #\ち
  #\す
  #\を
  #\で
  #\わ
  #\れ
  #\と
  #\ま
  #\ー
  #\ス
  #\こ
  #\つ
  #\ど
  #\は
  #\お
  #\キ
  #\ず
  #\り
  #\恐
  #\事
  #\そ
  #\け
  #\目
  #\じ
  #\き
  #\や
  #\ろ
  #\気
  #\ょ
  #\え
  #\ね
  #\私
  #\誰
  #\俺
  #\返
  #\開
  #\さ
  #\後
  #\み)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 9 (&& (~ @ 9) 65534))
 (set-arr~ @ 6 1)
 (image "v09.pd8")
 (set-arr~ @ 9 (// (~ @ 9) 1))
 (proc 24)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "v09an.pd8")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 0)
 (load "v09.s4" (~ @ 2))
 (set-arr~ @ 7 0)
 (sound 1)
 (set-var I 31)
 (proc 26)
 (set-reg: 835 0)
 (animate 0 8 0)
 (animate 4 8)
 (set-arr~ @ 7 0)
 (load "v09.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (if (== (: 762) 1)
   (<>
    (text #:color 7 "【" 0 "】（あれま・・・目をつぶってるよ。）")
    (wait)
    (text #:color 3 "【舞】" 0 "君・・・いるわよね。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 3 "【舞】" 0 "君ったらあ。")
    (wait)))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<> (text "脅かす")))
      (cond
       ((&& (== N 1) (== (: 10) 0))
        (<>
         (text #:color 7 "【" 0 "】わあっ！！")
         (wait)
         (text #:color 3 "【舞】きゃっ！！・・・ど、どうしたの！？")
         (wait)
         (text #:color 7 "【" 0 "】なんでもない。")
         (wait)
         (text #:color 3 "【舞】も、もうっ・・・" 0 "君のいじわるっ！！")
         (set-reg: 10 1)))
       ((&& (== N 1) (== (: 10) 1))
        (<>
         (text #:color 7 "【" 0 "】わ、わああっ！！")
         (wait)
         (text #:color 3 "【舞】きゃああっ！！")
         (wait)
         (text #:color 7 "【" 0 "】なんでもないよ、舞ちゃん。")
         (wait)
         (text #:color 3 "【舞】もう・・・怒るわよ。")
         (wait)))
       (else (<>)))))
    ((&& (== V 2) (== N 1) (== (: 21) 0))
     (<>
      (text #:color 7 "【" 0 "】舞ちゃん。")
      (wait)
      (text #:color 3 "【舞】な、なあに・・・" 0 "君。")
      (wait)
      (text #:color 7 "【" 0 "】ずっと目をつぶってるつもり？")
      (wait)
      (text #:color 3 "【舞】だって・・・恐いんだもの。")
      (wait)
      (set-reg: 21 1)))
    ((&& (== V 2) (== N 1) (== (: 21) 1))
     (<>
      (text #:color 3 "【舞】" 0 "君・・・わ、私の回りに、誰かいるような気がするの。")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "いる") (text "いない")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】いるよ。")
         (wait)
         (text #:color 3 "【舞】きゃっ！！・・・だ、誰がいるの！？")
         (wait)
         (text #:color 7 "【" 0 "】俺。")
         (wait)
         (text #:color 3 "【舞】や、やだ・・・" 0 "君以外の人って事よ。")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】いないよ・・・回りには誰も。")
         (wait)
         (text #:color 3 "【舞】や、やだあ・・・なんか気配がするのよ。")
         (wait)))
       (else (<>)))
      (set-reg: 21 2)))
    ((&& (== V 2) (== N 1) (== (: 21) 2))
     (<>
      (text #:color 3 "【舞】あーん・・・いつまで続くのかしら？")
      (wait)
      (text #:color 7 "【" 0 "】ひっひっひっ、永久に出られなかったりして。")
      (wait)
      (text #:color 3 "【舞】変な事を言わないで・・・。")
      (wait)
      (set-reg: 21 3)))
    ((&& (== V 2) (== N 1) (== (: 21) 3))
     (<>
      (text #:color 3 "【舞】" 0 "君・・・そばにいるわよね？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "返事をする") (text "黙ってる")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】いるよ、目の前に。")
         (wait)
         (text #:color 3 "【舞】よかった・・・。")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 3 "【舞】" 0 "君？")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 3 "【舞】も、もう・・・返事をして。")
         (wait)))
       (else (<>)))
      (set-reg: 21 4)))
    ((&& (== V 2) (== N 1) (== (: 21) 4))
     (<>
      (text #:color 3 "【舞】" 0 "君・・・いるわよね？")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "返事をする") (text "黙ってる")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】だから、平気だって・・・目の前にいるよ。")
         (wait)
         (text #:color 3 "【舞】よかった・・・。")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 3 "【舞】" 0 "君？")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 3 "【舞】" 0 "君ったら・・・。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 3 "【舞】も、もう・・・恐くて目を開けられないんだから。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 3 "【舞】返事をして。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 3 "【舞】まさか・・・いないの？")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "v08.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "v08an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "v08.s4" (~ @ 2))
         (set-arr~ @ 7 0)
         (animate 0 8 0)
         (animate 4 8)
         (text #:color 7 "【" 0 "】（ぎょっ！？）")
         (wait)
         (text #:color 3 "【舞】やだ・・・ちゃんといるじゃない。")
         (wait)
         (text #:color 3 "【舞】・・・。")
         (wait)
         (text #:color 3 "【舞】" 0 "君・・・どうしてそんなに驚いた顔をしてるの？")
         (wait)
         (text #:color 7 "【" 0 "】後ろにもいる。")
         (wait)
         (text #:color 3 "【舞】" 0 "君っていじわるね・・・どうして返事をしてくれないの？")
         (wait)
         (text #:color 7 "【" 0 "】舞ちゃん・・・後ろ。")
         (wait)
         (text #:color 3 "【舞】後ろ？")
         (wait)
         (text #:color 5 "【一つ目小僧】びよーーんっ！！")
         (wait)
         (text #:color 3 "【舞】きゃあああああああああっ！！")
         (animate 0 8 0)
         (animate 4 8)
         (animate 0 8 1)
         (animate 4 8)
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "v07.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "v07an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "v07.s4" (~ @ 2))
         (set-arr~ @ 7 0)
         (animate 0 8 0)
         (animate 4 8)
         (animate 0 8 1)
         (animate 4 8)
         (text #:color 7 "【" 0 "】（おおおっ！！こ、この時を待ってたんだあっ！！）")
         (wait)
         (text #:color 3 "【舞】こ、恐いっ！！")
         (wait)
         (text #:color 7 "【" 0 "】（ああ・・・舞ちゃんの身体って・・・。）")
         (wait)
         (text #:color 3 "【舞】" 0 "くーんっ！！")
         (wait)
         (text #:color 7 "【" 0 "】（い、いい匂いだあ・・・くんか、くんか。）")
         (wait)
         (text #:color 3 "【舞】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】（震えてるな・・・よっぽど恐かったんだ。）")
         (wait)
         (text #:color 7 "【" 0 "】（・・・。）")
         (wait)
         (text #:color 7 "【" 0 "】（なんか・・・かわいそうになっちゃったな。）")
         (wait)
         (text #:color 3 "【舞】" 0 "君・・・もういない？")
         (wait)
         (text #:color 7 "【" 0 "】いないよ・・・平気だぜ。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "v02.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "v02an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "v02.s4" (~ @ 2))
         (set-arr~ @ 7 0)
         (animate 0 8 0)
         (animate 4 8)
         (text #:color 3 "【舞】・・・恐かったの。")
         (wait)
         (text #:color 7 "【" 0 "】（どっきん！！）")
         (wait)
         (text #:color 3 "【舞】・・・。")
         (wait)
         (set-reg: 101 1)
         (set-arr~ @ 7 0)
         (proc 18)
         (menu-show
          (<.>
           (text "キスする")
           (text "キスする")
           (text "キスする")
           (text "キスする")
           (text "キスする")
           (text "キスする")
           (text "キスする")
           (text "キスする")
           (text "キスする")
           (text "キスする")))
         (if-else (//
                   (== N 1)
                   (== N 2)
                   (== N 3)
                   (== N 4)
                   (== N 5)
                   (== N 6)
                   (== N 7)
                   (== N 8)
                   (== N 9)
                   (== N 10))
           (<>
            (text #:color 7 "【" 0 "】・・・。")
            (wait)
            (text #:color 3 "【舞】いや・・・" 0 "君。")
            (wait))
           (<>))
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "v04.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "v04an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "v04.s4" (~ @ 2))
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 29)
         (proc 26)
         (set-reg: 835 0)
         (animate 0 8 0)
         (animate 4 8)
         (text #:color 3 "【舞】もう少し・・・このままでいたい。")
         (wait)
         (text #:color 7 "【" 0 "】（・・・。）")
         (wait)
         (text #:color 7 "【" 0 "】（キスできなかったけど・・・この方がいいかな？）")
         (wait)
         (text #:color 3 "【舞】こうしていけば・・・ちっとも恐くない。")
         (wait)
         (text #:color 7 "【" 0 "】（舞ちゃんの胸のふくらみを・・・感じる。）")
         (wait)
         (text #:color 3 "【舞】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】（舞ちゃんの身体が・・・暖かい。）")
         (wait)
         (text #:color 3 "【舞】私、" 0 "君の事を・・・ずっと前から・・・。")
         (wait)
         (text #:color 7 "【" 0 "】ず、ずっと！？")
         (wait)
         (text #:color 3 "【舞】ずっと・・・。")
         (wait)
         (text #:color 7 "【" 0 "】ず、ず、ずっと！？")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "kuro.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (sound 1)
         (text #:color 5 "【係員】はーい、お疲れさまでしたあ。")
         (wait)
         (text #:color 7 "【" 0 "】おいおいおいおいっ！！")
         (wait)
         (text #:color 5 "【係員】ここが終点でえす、降りてくださあい。")
         (wait)
         (text #:color 7 "【" 0 "】おい・・・もう一周してくれ。")
         (wait)
         (text #:color 5 "【係員】だめですよう、ほーらこんなに並んでいるでしょお？")
         (wait)
         (text #:color 7 "【" 0 "】あれれ、いつのまに・・・。")
         (wait)
         (text #:color 3 "【舞】" 0 "君・・・降りましょうよ。")
         (wait)
         (text #:color 7 "【" 0 "】（ちくしょうっ！！あの一つ目のやつが、もう少し早く出て来てたら・・・。）")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "58.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "v.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "van.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "v.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 61)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 3 "【舞】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】ふう・・・なんだか咽が渇いたな。")
         (wait)
         (text #:color 3 "【舞】恥ずかしい・・・私。")
         (wait)
         (text #:color 7 "【" 0 "】え？")
         (wait)
         (text #:color 3 "【舞】う、ううん・・・私も叫びすぎちゃって、咽がからからよ。")
         (wait)
         (text #:color 7 "【" 0 "】じゃあ、あそこでジュースを買ってくるよ。")
         (wait)
         (text #:color 3 "【舞】" 0 "君は、何を飲むの？")
         (wait)
         (text #:color 7 "【" 0 "】俺は・・・コーラかな？")
         (wait)
         (text #:color 3 "【舞】私が買って来てあげる・・・パラソルの所に座って待ってて。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "58.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "58an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "58.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】あらら・・・走って行ってしまった。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】パラソルって言うと・・・ああ、あそこだな。")
         (wait)
         (set-reg: 111 (+ (: 111) 1))
         (set-var A 15)
         (proc 12)
         (proc 11)
         (slot 1 6)
         (mes-jump "yuench7.mes")))
       (else (<>)))))
    ((&& (== V 1) (== N 2) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】（目をつぶったままだよ・・・よっぽど恐いんだな。）")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 1) (== N 2) (== (: 11) 1))
     (<> (text #:color 7 "【" 0 "】（口が『へ』の字だぜ・・・かわいいなあ。）") (wait)))
    ((&& (== V 1) (== N 3) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】（髪の毛が・・・後ろになびいてるような？）")
      (wait)
      (text #:color 7 "【" 0 "】（そんなにスピードの出る乗物じゃないと思うけど・・・。）")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 3) (== (: 12) 1))
     (<> (text #:color 7 "【" 0 "】（誰かが後ろから引っ張ってるとか・・・ははは、まさかね。）") (wait)))
    ((&& (== V 1) (== N 4) (== (: 13) 0))
     (<>
      (text #:color 7 "【" 0 "】（ああ・・・あんなふうに握って欲しいっ！！）")
      (wait)
      (set-reg: 13 1)))
    ((&& (== V 1) (== N 4) (== (: 13) 1))
     (<> (text #:color 7 "【" 0 "】（両手で握って欲しいっ・・・そんなに長くないけど。）") (wait)))
    ((&& (== V 1) (== N 5) (== (: 14) 0))
     (<>
      (text #:color 7 "【" 0 "】（み、見えそうで・・・見えないっ！！）")
      (wait)
      (text #:color 3 "【舞】" 0 "君・・・まだ終らないの？")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 1) (== N 5) (== (: 14) 1))
     (<>
      (text #:color 7 "【" 0 "】（白かな？ピンクかな？オレンジかな？・・・まさか、黒って事はないだろうな？）")
      (wait)))
    ((&& (== V 5) (== N 6) (== (: 15) 0))
     (<>
      (text #:color 7 "【" 0 "】（開けっ！！開けっ！！ぱっと開けっ！！）")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 5) (== N 6) (== (: 15) 1))
     (<>
      (text #:color 7 "【" 0 "】（ぐいぐいっと・・・。）")
      (wait)
      (text #:color 3 "【舞】" 0 "君っ・・・膝に何か当たってるわ！！")
      (wait)
      (text #:color 7 "【" 0 "】俺の膝。")
      (wait)
      (set-reg: 15 2)))
    ((&& (== V 5) (== N 6) (== (: 15) 2))
     (<> (text #:color 7 "【" 0 "】（ちくしょー・・・手で開くわけにもいかないしなあ。）") (wait)))
    ((&& (== V 1) (== N 7) (== (: 16) 0))
     (<>
      (text #:color 7 "【" 0 "】（うーん・・・いい雰囲気を出してくれるぜ。）")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 1) (== N 7) (== (: 16) 1))
     (<> (text #:color 7 "【" 0 "】（あのちょうちんが、舞ちゃんの脚の間に落ちてくれればいいのに。）") (wait)))
    ((&& (== V 1) (== N 8) (== (: 17) 0))
     (<>
      (text #:color 7 "【" 0 "】（なんか・・・公園にある向い合わせのブランコみたいだな。）")
      (wait)
      (set-reg: 17 1)))
    ((&& (== V 1) (== N 8) (== (: 17) 1))
     (<> (text #:color 7 "【" 0 "】（これって・・・降りようと思えば、途中下車できちゃうんじゃないか？）") (wait)))
    ((&& (== V 1) (== N 9) (== (: 18) 0))
     (<>
      (text #:color 7 "【" 0 "】（あんな所にバイブがある。）")
      (wait)
      (text #:color 7 "【" 0 "】（・・・。）")
      (wait)
      (text #:color 7 "【" 0 "】（誰も突っ込んでくれない・・・パイプだろ？）")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 1) (== N 9) (== (: 18) 1))
     (<> (text #:color 7 "【" 0 "】（もしかして、パイプじゃなくて『てすり』かな？）") (wait)))
    ((&& (== V 1) (== N 10) (== (: 19) 0))
     (<>
      (text #:color 7 "【" 0 "】（うーん・・・いい雰囲気だ、舞ちゃんをもっと恐がらせてくれ。）")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 1) (== N 10) (== (: 19) 1))
     (<> (text #:color 7 "【" 0 "】（おーいっ・・・もっと恐がらせてもいいぞうっ！！）") (wait)))
    ((&& (== V 1) (== N 11) (== (: 20) 0))
     (<>
      (text #:color 7 "【" 0 "】（なんか・・・身体全身が固くなってるな。）")
      (wait)
      (text #:color 7 "【" 0 "】（俺もごく一部が固くなりそうだ・・・ははは。）")
      (wait)
      (set-reg: 20 1)))
    ((&& (== V 1) (== N 11) (== (: 20) 1))
     (<>
      (text #:color 7 "【" 0 "】（しがみついてるな・・・どうせだったら、俺のちんちんにしがみついてくれ。）")
      (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))