(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\な
  #\い
  #\。
  #\、
  #\の
  #\っ
  #\だ
  #\て
  #\か
  #\ん
  #\う
  #\る
  #\は
  #\あ
  #\に
  #\し
  #\！
  #\た
  #\が
  #\と
  #\よ
  #\？
  #\く
  #\人
  #\も
  #\ゃ
  #\を
  #\ら
  #\で
  #\こ
  #\ち
  #\ー
  #\れ
  #\そ
  #\男
  #\じ
  #\や
  #\り
  #\俺
  #\さ
  #\み
  #\わ
  #\ど
  #\事
  #\ま
  #\一
  #\お
  #\女
  #\ぜ
  #\え
  #\け
  #\君
  #\す
  #\子
  #\ろ
  #\気
  #\き
  #\美
  #\ね
  #\舞
  #\言
  #\つ
  #\ふ
  #\間
  #\哉
  #\行
  #\時
  #\何
  #\ル
  #\ぞ
  #\め
  #\沙
  #\二
  #\ょ
  #\町
  #\ン
  #\吹
  #\健
  #\矢
  #\夏
  #\達
  #\ラ
  #\前
  #\げ
  #\パ
  #\見
  #\本
  #\私
  #\セ
  #\元
  #\イ
  #\穂
  #\ッ
  #\今
  #\思
  #\せ
  #\大
  #\聞
  #\場
  #\ビ
  #\不
  #\当
  #\待
  #\ば
  #\ク
  #\ス
  #\ひ
  #\色
  #\夜
  #\来
  #\デ
  #\マ
  #\ツ
  #\話
  #\手
  #\生
  #\太
  #\車
  #\日
  #\悪
  #\ご
  #\ト
  #\ぎ
  #\違
  #\物)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "01.pd8")
 (proc 15)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "01.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (cond
  ((&&
    (== (: 388) 0)
    (== (: 151) 1)
    (== (: 188) 1)
    (> T 800)
    (< T 2300)
    (== (: 481) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "i.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ran.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "r.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【一哉】" 0 "っ！！")
    (wait)
    (if (> T 2000)
      (<>
       (text #:color 7 "【" 0 "】一哉、しっかり不良してるじゃないか・・・ナンパでもしてるのか？")
       (wait)
       (text #:color 5 "【一哉】俺は" 0 "じゃないよ・・・今から帰るところさ。")
       (wait)))
    (if (< T 1959)
      (<>
       (text #:color 7 "【" 0 "】一哉、一人で何やってるんだ・・・くるみちゃんは一緒じゃないのか？")
       (wait)
       (text #:color 5 "【一哉】俺だって、くるみとべったりって訳じゃないぜ・・・たまには一人でいたい時もある。")
       (wait)))
    (text #:color 7 "【" 0 "】そうそう、くるみちゃんを見たぜ・・・ラブホテルの前で。")
    (wait)
    (text #:color 5 "【一哉】な、なにいっ！？")
    (wait)
    (text #:color 7 "【" 0 "】嘘だよ。")
    (wait)
    (text #:color 5 "【一哉】はあはあはあはあはあ。")
    (wait)
    (text #:color 5 "【一哉】はあはあはあはあはあ。")
    (wait)
    (text #:color 7 "【" 0 "】ははは、心臓に悪いだろ？")
    (wait)
    (text #:color 5 "【一哉】" 0 "・・・はあはあはあ、俺はもう帰るぞ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01.pd8")
    (proc 15)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】あらら、本当に帰っちゃったよ・・・。")
    (wait)
    (set-reg: 388 1)))
  ((&& (== (: 745) 1) (== H 824) (> T 950) (< T 1050) (== (: 746) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "v.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "van.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "v.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 24)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 3 "【舞】" 0 "君・・・おはよう。")
    (wait)
    (text #:color 7 "【" 0 "】舞ちゃんっ！！")
    (wait)
    (if (> T 1030)
      (<>
       (text #:color 3 "【舞】" 0 "君、来ないかと思って・・・心配しちゃったわ。")
       (wait)
       (text #:color 7 "【" 0 "】ははは、ごめん・・・ちょっと遅刻したかな。")
       (wait)
       (set-reg: 111 (- (: 111) 1))))
    (text #:color 3 "【舞】いい天気でよかったわ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】うーん、俺と舞ちゃんの初デートにふさわしい天気だな。")
    (wait)
    (text #:color 3 "【舞】" 0 "君との初デートは・・・私にとって、初めてのデートなのよ。")
    (wait)
    (text #:color 7 "【" 0 "】え？")
    (wait)
    (text #:color 3 "【舞】だから、私は男の人と遊びに行くのが初めてって事。")
    (wait)
    (text #:color 7 "【" 0 "】うっうっ・・・か、感激だなあ。")
    (wait)
    (text #:color 3 "【舞】" 0 "君、泣いてないで・・・早く行きましょうよ。")
    (wait)
    (text #:color 7 "【" 0 "】う、うん・・・遊園地に行こうっ！！")
    (wait)
    (set-reg: 761 1)
    (set-reg: 746 1)
    (set-var N 21)
    (slot 1 3)
    (mes-jump "town1.mes")))
  ((&&
    (== (: 389) 0)
    (== (: 291) 1)
    (== (: 188) 1)
    (> T 800)
    (< T 1900)
    (== (: 481) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "q.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "qan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "q.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【くるみ】あっ・・・" 0 "さんだ。")
    (wait)
    (text #:color 7 "【" 0 "】お嬢さん、いくら？")
    (wait)
    (text #:color 6 "【くるみ】え？")
    (wait)
    (text #:color 7 "【" 0 "】かわいいねえ、そのセーラー服の下はどうなってるのかなあ？")
    (wait)
    (text #:color 6 "【くるみ】" 0 "さん、またおぢさんごっこ？")
    (wait)
    (text #:color 7 "【" 0 "】くるみちゃん、矢吹町でセーラー服姿なんて・・・危険すぎるぜ。")
    (wait)
    (text #:color 6 "【くるみ】どうして？")
    (wait)
    (text #:color 7 "【" 0 "】どうしてって、他の商売の人と間違われちゃうぜ。")
    (wait)
    (text #:color 6 "【くるみ】？？？")
    (wait)
    (text #:color 7 "【" 0 "】だからあ・・・セーラー服を着てても、偽者のセーラー服があるんだよ。")
    (wait)
    (text #:color 6 "【くるみ】？？？")
    (wait)
    (text #:color 7 "【" 0 "】だからあ、セーラー服が本物でも、中身の女の子が偽者って事。")
    (wait)
    (text #:color 6 "【くるみ】？？？")
    (wait)
    (text #:color 7 "【" 0 "】もういい・・・子供は帰りなさい。")
    (wait)
    (text #:color 6 "【くるみ】はーい。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01.pd8")
    (proc 15)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ふう・・・一哉の苦労がわかるぜ。")
    (wait)
    (set-reg: 389 1)))
  ((&&
    (== (: 390) 0)
    (== (: 248) 1)
    (== (: 188) 1)
    (> T 800)
    (< T 1800)
    (== (: 745) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "w.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "wan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "w.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 24)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 3 "【舞】" 0 "君・・・。")
    (wait)
    (text #:color 7 "【" 0 "】舞ちゃんっ！！デートしようっ！！")
    (wait)
    (text #:color 3 "【舞】元気よね、" 0 "君って。")
    (wait)
    (text #:color 7 "【" 0 "】デートが駄目だったら、せめてお喋りしようっ！！")
    (wait)
    (text #:color 3 "【舞】明るくて、元気で、ちょっといやらしくて、それでいて子供っぽくて・・・だから人気があるのかしら？")
    (wait)
    (text #:color 7 "【" 0 "】お喋りが駄目だったら・・・一緒に歩こうっ！！")
    (wait)
    (text #:color 3 "【舞】ごめんね、ママを待ってるの。")
    (wait)
    (text #:color 7 "【" 0 "】じゃあ、ママも一緒にデートしよう！！")
    (wait)
    (text #:color 3 "【舞】" 0 "君・・・自分で言ってる事、わかってるのかしら？")
    (wait)
    (text #:color 7 "【" 0 "】はっはっはっはっ！！")
    (wait)
    (text #:color 3 "【舞】あ、ママが来たみたい・・・じゃあね、" 0 "君。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01.pd8")
    (proc 15)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】舞ちゃーんっ！！")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】舞ちゃーん、てばっ！！")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】知ってるよ、もういないんだろ？")
    (wait)
    (set-reg: 390 1)))
  ((&&
    (== (: 391) 0)
    (== (: 223) 1)
    (== (: 188) 1)
    (> T 800)
    (< T 1900)
    (== (: 685) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "a.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "aan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "a.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 3 "【美沙】" 0 "っ！！")
    (wait)
    (text #:color 7 "【" 0 "】美沙、大きな声を出すな・・・恥ずかしいじゃないか。")
    (wait)
    (text #:color 3 "【美沙】はははっ！！" 0 "の口から『恥ずかしい』なんて言葉で出でくるとは、夢にも思わなかったぜ。")
    (wait)
    (text #:color 7 "【" 0 "】たたくぞ。")
    (wait)
    (text #:color 3 "【美沙】逃げるから平気だよ。")
    (wait)
    (text #:color 7 "【" 0 "】追いかけてやる、俺は早いぞ。")
    (wait)
    (text #:color 3 "【美沙】本当にそうなんだよな・・・" 0 "、前に何度か言った事があるけどさ、どうして陸上部に入らないんだ？")
    (wait)
    (text #:color 7 "【" 0 "】嫌いなんだよ、クラブ活動ってやつが。")
    (wait)
    (text
     #:color
     3
     "【美沙】前は入ってたじゃないか『卓球部』とか『邦楽部』とか・・・"
     0
     "はスポーツだけは万能なんだから、もっと他にいいクラブがあるだろ？")
    (wait)
    (text #:color 7 "【" 0 "】ははは、あれにはちゃんと理由がある・・・。")
    (wait)
    (text #:color 3 "【美沙】知ってるよ、かわいい女の子がいたからだろ？")
    (wait)
    (text #:color 7 "【" 0 "】でも、一ヶ月もたたないで除名されたんだ・・・ちくしょう、まだ何もしてないのに。")
    (wait)
    (text
     #:color
     3
     "【美沙】十分してるよ、卓球の台に暗幕をかけて女の子は引っ張り込むし・・・尺八を吹けって邦楽部の子に強要するし、やってる事がメチャクチャなんだよ。")
    (wait)
    (text #:color 7 "【" 0 "】あーあ、誰も俺の事を理解してくれない。")
    (wait)
    (text #:color 3 "【美沙】いるんだよな、そんな" 0 "が好きって子が・・・私はそっちの方が理解できない。")
    (wait)
    (text #:color 7 "【" 0 "】美沙君、その話を詳しく聞こうじゃないか・・・ん？")
    (wait)
    (text #:color 3 "【美沙】じゃあな・・・私は忙しいから、勝手に考えれば？")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01.pd8")
    (proc 15)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ちっくしょう・・・なんて思わせぶりなやつだ。")
    (wait)
    (set-reg: 391 1)))
  ((&&
    (== H 827)
    (== (: 513) 1)
    (== (: 515) 1)
    (== (: 539) 0)
    (> T 950)
    (< T 1030))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j11.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】夏子さん、お待たせっ！！")
    (wait)
    (text #:color 2 "【夏子】" 0 "君・・・。")
    (wait)
    (text #:color 7 "【" 0 "】あれ・・・どうしたの？")
    (wait)
    (text #:color 2 "【夏子】ごめんなさい、実は急用ができちゃって。")
    (wait)
    (text #:color 7 "【" 0 "】え！？")
    (wait)
    (text #:color 2 "【夏子】本当にごめんなさい・・・じゃあ。")
    (wait)
    (text #:color 7 "【" 0 "】あ・・・そ、そんなあ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01.pd8")
    (proc 15)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】俺が・・・何をしたって言うんだよう。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】夏子のばっかやろっ！！・・・楽しみにしてたのにっ！！")
    (wait)
    (set-reg: 539 1)))
  ((&&
    (== H 827)
    (== (: 513) 1)
    (== (: 515) 0)
    (== (: 539) 0)
    (> T 950)
    (< T 1050))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j11.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 30)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】夏子さん、お待たせっ！！")
    (wait)
    (text #:color 2 "【夏子】あ・・・" 0 "君。")
    (wait)
    (text #:color 7 "【" 0 "】いい天気でよかったよな・・・うん、実にいい天気だ。")
    (wait)
    (text #:color 2 "【夏子】なんだかワクワクしちゃうわね・・・早く泳ぎたいわ。")
    (wait)
    (text #:color 7 "【" 0 "】（ひっひっひっ・・・夏子さんの水着ってどんなのかな？）")
    (wait)
    (text #:color 2 "【夏子】" 0 "君、行かないの？")
    (wait)
    (text #:color 7 "【" 0 "】い、行くさ・・・遊園地の方向は、えーと・・・あっちだな。")
    (wait)
    (text #:color 2 "【夏子】行きましょ？")
    (wait)
    (text #:color 7 "【" 0 "】よーし、行くぜっ！！")
    (wait)
    (set-reg: 539 1)
    (set-reg: 540 1)
    (set-reg: 542 1)
    (set-var N 21)
    (slot 1 3)
    (mes-jump "town1.mes")))
  ((&& (== (: 686) 1) (> T 800) (< T 1900) (== (: 687) 0) (== (: 690) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "a.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "aan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "a.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 28)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれ・・・美沙じゃないかよ。")
    (wait)
    (text #:color 3 "【美沙】" 0 "・・・。")
    (wait)
    (text #:color 7 "【" 0 "】なあ・・・何を怒ってんだ？")
    (wait)
    (text #:color 3 "【美沙】" 0 "が鈍感だからだよっ！！・・・私が見ててもイライラするぜ。")
    (wait)
    (text #:color 7 "【" 0 "】俺が鈍感？")
    (wait)
    (text #:color 3 "【美沙】まったく・・・かわいそうだよ、美穂のやつが。")
    (wait)
    (text #:color 7 "【" 0 "】どうして美穂ちゃんがかわいそうなんだよ・・・美沙、美穂ちゃんに変な事をしたんじゃないか？")
    (wait)
    (text #:color 3 "【美沙】" 0 "君の馬鹿っ！！牛の頭っ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01.pd8")
    (proc 15)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あらら・・・走って行っちゃったよ。")
    (wait)
    (text #:color 7 "【" 0 "】馬鹿はいいけど・・・牛の頭って何だ？")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・鈍いって事かな？")
    (wait)
    (set-reg: 687 1)))
  ((&& (== (: 753) 1) (> H 828) (> T 800) (< T 2000) (== (: 758) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "v.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "van.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "v.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 24)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 3 "【舞】" 0 "君・・・じゃない。")
    (wait)
    (text #:color 7 "【" 0 "】舞ちゃん・・・俺の話も聞いてくれよ。")
    (wait)
    (text #:color 3 "【舞】言い訳なんか聞きたくないわ・・・それに、" 0 "君の事が嫌いになってきたの。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01.pd8")
    (proc 15)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】そ、そんなあ・・・。")
    (wait)
    (set-reg: 111 (- (: 111) 1))
    (set-reg: 758 1)))
  ((&& (== (: 467) 1) (== (: 848) 0) (> H 827) (> T 800) (< T 2100))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "n10.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "n10an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "n10.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 6)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 3 "【ちはる】" 0 "君っ！！")
    (wait)
    (text #:color 7 "【" 0 "】ちはるちゃん・・・やけに元気だなあ。")
    (wait)
    (text #:color 3 "【ちはる】" 0 "君は元気じゃないの？")
    (wait)
    (text #:color 7 "【" 0 "】ちはるちゃんの顔を見たら、すっごく元気になった。")
    (wait)
    (text #:color 3 "【ちはる】口がうまいわねー・・・他の女の子にもそんな事を言ってるんでしょ？")
    (wait)
    (text #:color 7 "【" 0 "】俺がこんな事を言うのは、これが最初で最後さ・・・。")
    (wait)
    (text #:color 3 "【ちはる】あーあ・・・" 0 "君と話してると、我慢できなくなりそう。")
    (wait)
    (text #:color 7 "【" 0 "】え・・・もしかして俺と話をするのが我慢できないとか？")
    (wait)
    (text #:color 3 "【ちはる】逆よ・・・今度は私が、だーっといっちゃいそうって事。")
    (wait)
    (text #:color 7 "【" 0 "】？？？")
    (wait)
    (text #:color 3 "【ちはる】いいのよ、わからなくて・・・じゃあね、" 0 "君！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01.pd8")
    (proc 15)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ちはるちゃん・・・どこに行くんだろ？")
    (wait)
    (text #:color 7 "【" 0 "】なんか最近、彼女の事が気になるんだよなあ・・・。")
    (wait)
    (set-reg: 848 1)))
  ((&& (== (: 558) 1) (== (: 561) 0) (> H 821) (> T 800) (< T 1800))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "d.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "dan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "d.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 38)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 2 "【麗子】あ・・・" 0 "さん。")
    (wait)
    (text #:color 7 "【" 0 "】麗子さん・・・。")
    (wait)
    (text #:color 2 "【麗子】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】買物・・・かな？")
    (wait)
    (text #:color 2 "【麗子】ええ・・・じゃあ、さようなら。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01.pd8")
    (proc 15)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】うーん・・・気まずい雰囲気だったな。")
    (wait)
    (set-reg: 561 1)))
  ((&&
    (== (: 718) 1)
    (> H 823)
    (> T 800)
    (< T 1900)
    (== (: 720) 0)
    (== (: 728) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "f.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 27)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【美穂】あ・・・。")
    (wait)
    (text #:color 7 "【" 0 "】美穂ちゃん・・・俺の話も聞いてくれよ。")
    (wait)
    (text #:color 6 "【美穂】だって・・・恐いんだもん。")
    (wait)
    (text #:color 7 "【" 0 "】恐いと言えば、もうあとをつけられる事はなくなった？")
    (wait)
    (text #:color 6 "【美穂】うん・・・。")
    (wait)
    (text #:color 7 "【" 0 "】美穂ちゃん、手紙の事だけど・・・。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01.pd8")
    (proc 15)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】ちょっと待ったあ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "f.pd8")
    (proc 16)
    (set-arr~ @ 7 0)
    (text #:color 6 "【美穂】だって・・・。")
    (wait)
    (text #:color 7 "【" 0 "】だ、だから・・・俺の返事はね。")
    (wait)
    (set-reg: 101 0)
    (set-arr~ @ 7 0)
    (proc 18)
    (menu-show (<.> (text "好き") (text "嫌い")))
    (if (== N 1)
      (<>
       (set-arr~ @ 7 1)
       (set-arr~ @ 1 4096)
       (set-arr~ @ 6 1)
       (image "01.pd8")
       (proc 15)
       (set-arr~ @ 7 1)
       (set-arr~ @ 1 4096)
       (set-arr~ @ 6 1)
       (image "01an.pd8")
       (set-arr~ @ 6 0)
       (set-arr~ @ 7 0)
       (load "01.s4" (~ @ 2))
       (animate 0 0 0)
       (animate 1 0)
       (set-arr~ @ 7 0)
       (sound 1)
       (set-var I 62)
       (proc 26)
       (set-reg: 835 0)
       (text #:color 7 "【" 0 "】俺も美穂ちゃんの事が好き・・・あれれ！？")
       (wait)))
    (if (== N 2)
      (<>
       (set-arr~ @ 7 1)
       (set-arr~ @ 1 4096)
       (set-arr~ @ 6 1)
       (image "01.pd8")
       (proc 15)
       (set-arr~ @ 7 1)
       (set-arr~ @ 1 4096)
       (set-arr~ @ 6 1)
       (image "01an.pd8")
       (set-arr~ @ 6 0)
       (set-arr~ @ 7 0)
       (load "01.s4" (~ @ 2))
       (animate 0 0 0)
       (animate 1 0)
       (set-arr~ @ 7 0)
       (sound 1)
       (set-var I 62)
       (proc 26)
       (set-reg: 835 0)
       (text #:color 7 "【" 0 "】悪いけど、俺は美穂ちゃんの事が嫌い・・・あれれ！？")
       (wait)))
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】いいかげんにしろよ・・・おい。")
    (wait)
    (set-reg: 720 1)))
  ((&& (== (: 581) 1) (> H 823) (> T 800) (< T 2100) (== (: 587) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "e.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "ean.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "e.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 22)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 6 "【かおり】あらあ、" 0 "君・・・元気？")
    (wait)
    (text #:color 7 "【" 0 "】かおりさん・・・相変わらず輝いてるね。")
    (wait)
    (text #:color 6 "【かおり】ありがとう、うれしいわ。")
    (wait)
    (text #:color 7 "【" 0 "】装飾品が。")
    (wait)
    (text #:color 6 "【かおり】" 0 "君、一度でも抱いた女に・・・そんな事を言っちゃだめよ。")
    (wait)
    (text #:color 7 "【" 0 "】だってさ、かおりさんがあれ以来相手にしてくれないから・・・いじけてるんだぜ。")
    (wait)
    (text #:color 6 "【かおり】" 0 "君の事が好きだから、相手にしてないの・・・りっぱにすくすくと育って欲しいもの。")
    (wait)
    (text #:color 7 "【" 0 "】母親みたいな事を言わないでくれる？")
    (wait)
    (text #:color 6 "【かおり】あはは・・・じゃあね、ママはもう行くわよ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01.pd8")
    (proc 15)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ちぇっ・・・もうかおりさんを抱く事はできないのかな？")
    (wait)
    (if (== (: 403) 1)
      (<>
       (set-arr~ @ 7 1)
       (set-arr~ @ 1 4096)
       (set-arr~ @ 6 1)
       (image "o14.pd8")
       (proc 16)
       (set-arr~ @ 7 1)
       (set-arr~ @ 1 4096)
       (set-arr~ @ 6 1)
       (image "o14an.pd8")
       (set-arr~ @ 6 0)
       (set-arr~ @ 7 0)
       (load "o14.s4" (~ @ 2))
       (animate 0 0 0)
       (animate 1 0)
       (set-arr~ @ 7 0)
       (sound 1)
       (set-var I 2)
       (proc 26)
       (set-reg: 835 0)
       (text #:color 4 "【冬彦】おい・・・ハデな女だな。")
       (wait)
       (text #:color 7 "【" 0 "】ぎょっ！！")
       (wait)
       (text #:color 4 "【冬彦】君は、あんな女とつき合っているのかよう？")
       (wait)
       (text #:color 7 "【" 0 "】あんなとは何だよ、あんなとは・・・え！？")
       (wait)
       (text #:color 4 "【冬彦】ふふん、ひろみちゃんの方がずーっといいよう・・・君にはお似合いだけどよう。")
       (wait)
       (set-arr~ @ 7 1)
       (set-arr~ @ 1 4096)
       (set-arr~ @ 6 1)
       (image "01.pd8")
       (proc 15)
       (set-arr~ @ 7 1)
       (set-arr~ @ 1 4096)
       (set-arr~ @ 6 1)
       (image "01an.pd8")
       (set-arr~ @ 6 0)
       (set-arr~ @ 7 0)
       (load "01.s4" (~ @ 2))
       (animate 0 0 0)
       (animate 1 0)
       (set-arr~ @ 7 0)
       (sound 1)
       (set-var I 62)
       (proc 26)
       (set-reg: 835 0)
       (text #:color 7 "【" 0 "】・・・。")
       (wait)
       (text #:color 7 "【" 0 "】今度、冬彦の首に鈴をつけておこう。")
       (wait)))
    (set-reg: 587 1)))
  ((&&
    (== (: 767) 1)
    (> H 824)
    (> T 800)
    (< T 2100)
    (== (: 765) 0)
    (== (: 769) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "b.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "man.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "m.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 4 "【健二】ふっ・・・" 0 "か。")
    (wait)
    (text #:color 7 "【" 0 "】誰だ？")
    (wait)
    (text #:color 4 "【健二】健二だっ！！")
    (wait)
    (text #:color 7 "【" 0 "】なーんだ・・・健二か。")
    (wait)
    (text #:color 4 "【健二】舞と・・・会ってないだろうな。")
    (wait)
    (text #:color 7 "【" 0 "】ははは・・・さあね。")
    (wait)
    (text #:color 4 "【健二】舞はまだ外出禁止なんだ・・・舞の家の家政婦に、理由を聞いても答えてくれないしな。")
    (wait)
    (text #:color 7 "【" 0 "】健二の事が嫌いなんだよ。")
    (wait)
    (text #:color 4 "【健二】違うな・・・僕には言えない理由なんだ、きっと。")
    (wait)
    (text #:color 7 "【" 0 "】（その通りだよ、健二君。）")
    (wait)
    (text #:color 4 "【健二】うーん・・・どうにかして、舞に会える方法がないだろうか？")
    (wait)
    (text #:color 7 "【" 0 "】ひとつ・・・あるな。")
    (wait)
    (wait)
    (text #:color 4 "【健二】な、なんだ？・・・教えてもらってもいいぞ。")
    (wait)
    (text #:color 7 "【" 0 "】健二が死ねば・・・舞ちゃんは外出禁止とはいえ、線香の一本くらいくれるだろう。")
    (wait)
    (text #:color 4 "【健二】・・・。")
    (wait)
    (text #:color 4 "【健二】じゃあな、" 0 "・・・無駄な時間を費やしてしまった。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01.pd8")
    (proc 15)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】ははは・・・いいアイデアだと思ったけどな。")
    (wait)
    (set-reg: 769 1)))
  ((&& (== (: 483) 1) (== (: 496) 0) (> T 800) (< T 2100))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j12.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "j11an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "j11.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【一哉】うっ・・・うっ・・・" 0 "。")
    (wait)
    (text #:color 7 "【" 0 "】ど、どうした一哉！！")
    (wait)
    (text #:color 5 "【一哉】うっ・・・ううっ！！")
    (wait)
    (text #:color 7 "【" 0 "】ケンカか！？・・・ちくしょう、誰だ一哉を殴ったやつは！！")
    (wait)
    (text #:color 7 "【" 0 "】俺はつえーぞ！！・・・こらっ！！どこのどいつだっ！！")
    (wait)
    (text #:color 5 "【一哉】" 0 "・・・ち、違う。")
    (wait)
    (text #:color 7 "【" 0 "】え？")
    (wait)
    (text #:color 5 "【一哉】下痢だ・・・さっき食べたメンタイコおにぎりが当たったらしい。")
    (wait)
    (text #:color 7 "【" 0 "】じゃあな、一哉。")
    (wait)
    (text #:color 5 "【一哉】ま、待て・・・ティッシュを持ってないか？")
    (wait)
    (text #:color 7 "【" 0 "】持ってるぜ・・・ティッシュは俺様の必需品だからな。")
    (wait)
    (text #:color 5 "【一哉】悪いな、借りるぜ・・・うっ・・・うっ・・・ああっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01.pd8")
    (proc 15)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】なんだあいつ・・・アヒルみたいな歩き方をしやがって。")
    (wait)
    (set-reg: 496 1)))
  ((&& (== (: 641) 1) (== (: 655) 0) (> T 900) (< T 1900) (> H 827))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "c.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "can.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "c.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 60)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】あれれ・・・よしこ先生。")
    (wait)
    (text #:color 6 "【よしこ】" 0 "君・・・。")
    (wait)
    (text #:color 7 "【" 0 "】わかった・・・生徒達が変な遊びをしてないか、ここで見張ってるんでしょ？")
    (wait)
    (text #:color 6 "【よしこ】違いますよ、もうそんな事はやめました・・・一番大事な事は、生徒達を信じてあげる事ですから。")
    (wait)
    (text #:color 7 "【" 0 "】へえ・・・俺でも？")
    (wait)
    (text #:color 6 "【よしこ】" 0 "君は、一番信じてますよ。")
    (wait)
    (text #:color 7 "【" 0 "】な、なんだよ・・・変な言い方をするな。")
    (wait)
    (text #:color 6 "【よしこ】あなたは、とってもいい子です・・・そのまま大人になりきって欲しいですね。")
    (wait)
    (text #:color 7 "【" 0 "】このまま大人になったら、単なるスケベじじいだぜ。")
    (wait)
    (text #:color 6 "【よしこ】そうじゃない事は、" 0 "君が一番よく知っているでしょう・・・わかってますよ、先生には。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 6 "【よしこ】夏休みも、もう終りですね・・・新学期を楽しみにしてますよ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01.pd8")
    (proc 15)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】なんか・・・変なんだよなあ。")
    (wait)
    (set-reg: 655 1)))
  ((&&
    (== (: 519) 1)
    (== (: 520) 0)
    (> H 825)
    (> T 800)
    (< T 1900)
    (== (: 527) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "q.pd8")
    (proc 16)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "qan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "q.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 23)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】くるみちゃん！？")
    (wait)
    (text #:color 6 "【くるみ】" 0 "さん、こんにちは。")
    (wait)
    (text #:color 7 "【" 0 "】ねえ・・・なんだか元気じゃない？")
    (wait)
    (text #:color 6 "【くるみ】うん、" 0 "さんのおかげ。")
    (wait)
    (if (&& (== (: 514) 1) (== (: 515) 0))
      (<>
       (text #:color 7 "【" 0 "】俺・・・何かしたっけ？")
       (wait)
       (text #:color 6 "【くるみ】うん、色々と相談にのってくれたじゃない。")
       (wait)
       (text #:color 7 "【" 0 "】まあ、話はしたけど・・・。")
       (wait)
       (text #:color 6 "【くるみ】とにかく元気になれたの・・・夜もちゃんと眠れるし、御飯だってたくさん食べちゃうんだから。")
       (wait)
       (text #:color 7 "【" 0 "】ふーん。")
       (wait)))
    (if (== (: 515) 1)
      (<>
       (text #:color 7 "【" 0 "】俺のおかげって・・・あの事？")
       (wait)
       (text #:color 6 "【くるみ】うん、それだけじゃないけど・・・今の私って、とっても楽しいの。")
       (wait)
       (text #:color 7 "【" 0 "】どうして？")
       (wait)
       (text #:color 6 "【くるみ】だって・・・本当に好きなんだもん。")
       (wait)
       (text #:color 7 "【" 0 "】それは前と同じじゃないか。")
       (wait)
       (text #:color 6 "【くるみ】違うの・・・一哉君じゃない。")
       (wait)
       (text #:color 7 "【" 0 "】？？？")
       (wait)))
    (text #:color 6 "【くるみ】さーて、これから友達と買物をするの・・・じゃあね、" 0 "さん！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01.pd8")
    (proc 15)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】元気だなあ・・・本当に元気だ。")
    (wait)
    (set-reg: 520 1)))
  ((&&
    (== (: 728) 1)
    (== (: 710) 1)
    (> H 827)
    (< H 829)
    (> T 800)
    (< T 2359)
    (== (: 739) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】いいかげんにしようぜ。")
    (wait)
    (text #:color 5 "【太郎】君達は・・・君達は・・・不潔だあっ！！")
    (wait)
    (text #:color 5 "【太郎】不潔だあっ！！・・・不潔だあっ！！")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01.pd8")
    (proc 15)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】うるさいな・・・俺のあとをつけてるんじゃないか？")
    (wait)
    (set-reg: 739 1)))
  ((&&
    (== (: 728) 1)
    (== (: 710) 0)
    (> H 827)
    (< H 829)
    (> T 800)
    (< T 2359)
    (== (: 739) 0))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "s.pd8")
    (proc 16)
    (set-arr~ @ 6 1)
    (image "fan.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "f.s4" (~ @ 2))
    (animate 0 0 1)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 2)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 5 "【太郎】やあ、これからは僕の時代のようだ。")
    (wait)
    (text #:color 7 "【" 0 "】あのね、いきなり訳のわからない事を言わないでくれる？")
    (wait)
    (text #:color 5 "【太郎】僕にはわかっているのだよ・・・ふっふっ。")
    (wait)
    (text #:color 7 "【" 0 "】はあ・・・もうどうでもいいや。")
    (wait)
    (text #:color 5 "【太郎】" 0 "君に・・・勝ったな。")
    (wait)
    (text #:color 7 "【" 0 "】だからあ、何が俺に勝ったんだよう。")
    (wait)
    (text #:color 5 "【太郎】ふふふっ・・・ふっ・・・ふっ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01.pd8")
    (proc 15)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】無視しようぜ・・・。")
    (wait)
    (set-reg: 739 1)))
  ((> T 1900)
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】夜とはいえ、昼間と変わらない雰囲気だな・・・さすが矢吹町だ。")
    (wait)))
  ((&& (> T 0) (< T 400))
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】深夜なのに、みんな何をしているんだろ・・・もちろん、俺もその中の一人だが。")
    (wait)))
  ((== (: 188) 0)
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】矢吹町駅だな・・・賑やかな繁華街だ。")
    (wait)
    (if (&& (> T 0) (< T 5000))
      (<>
       (text #:color 7 "【" 0 "】さすがに、時間に関係なく人がいるな・・・まるで不夜城のような街だ。")
       (wait)))))
  ((== (: 188) 1)
   (<>
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 6 1)
    (image "01an.pd8")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 0)
    (load "01.s4" (~ @ 2))
    (animate 0 0 0)
    (animate 1 0)
    (set-arr~ @ 7 0)
    (sound 1)
    (set-var I 62)
    (proc 26)
    (set-reg: 835 0)
    (text #:color 7 "【" 0 "】ここは矢吹町駅の前だ・・・異性を求める若者達や、夜は好色なおっさん達がゴキブリのように集まる街だ。")
    (wait)
    (if (&& (> T 0) (< T 5000))
      (<> (text #:color 7 "【" 0 "】しかし、時間に関係なく人がいるな・・・まるで不夜城のようだぜ。") (wait))))))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "他の場所に行く") (text "電車に乗る") (text "やめる")))
      (cond
       ((&&
         (== N 1)
         (== (: 283) 1)
         (> H 810)
         (> T 900)
         (< T 1900)
         (== (: 284) 0)
         (== (: 598) 0))
        (<>
         (text #:color 7 "【" 0 "】そうだな、他の場所に行こうぜ・・・。")
         (wait)
         (sound 1)
         (set-var I 37)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 6 "ドスンッ！！")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "u.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "uan.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "u.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 59)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 6 "【奇麗な女性】あ・・・ごめんなさいね。")
         (wait)
         (text #:color 7 "【" 0 "】いてててっ！！・・・いいかげんにしろっ！！")
         (wait)
         (text #:color 6 "【奇麗な女性】怒るとハゲるわよ。")
         (wait)
         (text #:color 7 "【" 0 "】大きなお世話だよっ！！")
         (wait)
         (text #:color 6 "【奇麗な女性】怪我がなくてよかったわ・・・じゃあね、私は急ぐから。")
         (wait)
         (text #:color 7 "【" 0 "】ま、待てっ！！")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "01.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 62)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 7 "【" 0 "】なんなんだ、あの女は・・・新手の当り屋か！？")
         (wait)
         (set-reg: 284 1)
         (set-var N 21)
         (slot 1 3)
         (mes-jump "town1.mes")))
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・他の場所に行こうぜ。")
         (wait)
         (set-var N 21)
         (set-reg: 188 1)
         (slot 1 3)
         (mes-jump "town1.mes")))
       ((&& (== N 2) (> T 0) (< T 500))
        (<> (text #:color 7 "【" 0 "】電車に乗るって・・・今の時間は動いていないじゃないか。") (wait)))
       ((&& (== N 2) (< M 300))
        (<>
         (text #:color 7 "【" 0 "】まいったぜ・・・電車賃がないぞ。")
         (wait)
         (text #:color 7 "【" 0 "】うっうっうっ・・・みじめだ、みじめすぎるうっ！！")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・『先負町』に戻るか。")
         (wait)
         (text #:color 7 "【" 0 "】３００円で切符を買ってと・・・よーし、先負町駅に戻ろう。")
         (wait)
         (set-reg: 188 1)
         (set-var A 30)
         (proc 12)
         (set-var M (- M 300))
         (proc 11)
         (set-var N 1)
         (mes-call "den.mes")
         (slot 1 2)
         (mes-jump "sakima.mes")))
       ((== N 3)
        (<> (text #:color 7 "【" 0 "】そうだな、せっかく来たんだ・・・もう少し矢吹町にいようぜ。") (wait)))
       (else (<>)))))
    ((&& (== V 1) (== N 1) (== (: 10) 0))
     (<> (text #:color 7 "【" 0 "】街路灯だな・・・。") (wait) (set-reg: 10 1)))
    ((&& (== V 1) (== N 1) (== (: 10) 1))
     (<> (text #:color 7 "【" 0 "】だから街路灯だ。") (wait)))
    ((&& (== V 1) (== N 2) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】矢吹町の駅前広場には、色々な樹木が植えてある。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 1) (== N 2) (== (: 11) 1))
     (<>
      (text #:color 7 "【" 0 "】樹木だ・・・今は夏だから、葉もよく繁っている。")
      (wait)
      (set-reg: 11 2)))
    ((&& (== V 1) (== N 2) (== (: 11) 2))
     (<>
      (text #:color 7 "【" 0 "】そうだな、たまにはセミの気分になって木にとまってみるか。")
      (wait)
      (set-reg: 11 3)))
    ((&& (== V 1) (== N 2) (== (: 11) 3))
     (<>
      (text #:color 7 "【" 0 "】考えてみれば、植物の寿命は水と太陽と二酸化炭素がある限り、永遠なんだよなあ。")
      (wait)
      (text #:color 7 "【" 0 "】それに比べて俺達人間の寿命は、せいぜい１００年くらいか・・・ああ、無情。")
      (wait)))
    ((&& (== V 1) (== N 3) (== (: 12) 0))
     (<>
      (text #:color 7 "【" 0 "】１０１だな・・・矢吹町のシンボルのようなビルだ。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 3) (== (: 12) 1))
     (<>
      (text #:color 7 "【" 0 "】１０１だな・・・あのビルの中には、色々な物が売っているぞ。")
      (wait)
      (text #:color 7 "【" 0 "】でも俺は人混みが嫌いだからな・・・一度も行った事がないぞ。")
      (wait)))
    ((&& (== V 1) (== N 4) (== (: 13) 0))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】高層ビルという程ではないが、色々なビルが建ち並んでいる・・・大地震が起きたら、このあたりはパニックだろうな。")
      (wait)
      (set-reg: 13 1)))
    ((&& (== V 1) (== N 4) (== (: 13) 1))
     (<>
      (text #:color 7 "【" 0 "】雑居ビル、映画館・・・数えたらきりがないぜ。")
      (wait)
      (set-reg: 13 2)))
    ((&& (== V 1) (== N 4) (== (: 13) 2))
     (<>
      (text #:color 7 "【" 0 "】ビル、ビル、ビル・・・とにかくたくさんの建物が建っているぜ。")
      (wait)
      (set-reg: 13 3)))
    ((&& (== V 1) (== N 4) (== (: 13) 3))
     (<>
      (text #:color 7 "【" 0 "】駅前広場にいる人達だけでなく、このビルの中には人間がぎゅうぎゅうに詰まっているんだ。")
      (wait)
      (text #:color 7 "【" 0 "】うーん、人類ってなんてスケベなんだ。")
      (wait)))
    ((&& (== V 1) (== N 5) (== (: 14) 0))
     (<>
      (text #:color 7 "【" 0 "】ここは『矢吹町駅』の駅前広場だ・・・時間に関係なく、色々な人がいるな。")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 1) (== N 5) (== (: 14) 1))
     (<> (text #:color 7 "【" 0 "】このあたりに住んだら、絶対に睡眠不足になりそうだ・・・。") (wait)))
    ((&& (== V 1) (== N 11) (== (: 20) 0))
     (<>
      (text
       #:color
       7
       "【"
       0
       "】後ろ姿だからな、顔を見る事はできないが・・・俺様ぐらいのレベルになると、相手の男の風体を見ただけでどんな女だかわかるんだぜ。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】普通の女だな、うん。")
      (wait)
      (set-reg: 20 1)))
    ((&& (== V 1) (== N 11) (== (: 20) 1))
     (<>
      (text #:color 7 "【" 0 "】女性が後ろ手に紙袋をもっている時は、『今夜もＯＫよ』という合図だそうだ。")
      (wait)
      (text #:color 7 "【" 0 "】みんな信じないように。")
      (wait)))
    ((&& (== V 1) (== N 12) (== (: 21) 0))
     (<>
      (text #:color 7 "【" 0 "】サングラスをかけた男だな・・・ガラが悪いとまでは言わないが、性格は悪そうだ。")
      (wait)
      (set-reg: 21 1)))
    ((&& (== V 1) (== N 12) (== (: 21) 1))
     (<> (text #:color 7 "【" 0 "】男には興味がない・・・無視しようぜ。") (wait)))
    ((&& (== V 1) (== N 13) (== (: 22) 0))
     (<>
      (text #:color 7 "【" 0 "】忙しそうな男だな・・・セカセカと歩いているぞ。")
      (wait)
      (set-reg: 22 1)))
    ((&& (== V 1) (== N 13) (== (: 22) 1))
     (<>
      (text #:color 7 "【" 0 "】忙しいと言うか、あわただしいと言うか・・・男はもっと、どっしりとかまえていたいもんだ。")
      (wait)))
    ((&& (== V 1) (== N 14) (== (: 23) 0))
     (<>
      (text #:color 7 "【" 0 "】若いやつらがウジャウジャいるぞ・・・どうせナンパでもしているんだろう。")
      (wait)
      (set-reg: 23 1)))
    ((&& (== V 1) (== N 14) (== (: 23) 1))
     (<> (text #:color 7 "【" 0 "】後頭部かりあげの、ツンツン頭だ・・・触ってみたい。") (wait)))
    ((&& (== V 1) (== N 15) (== (: 24) 0))
     (<>
      (text #:color 7 "【" 0 "】なんだよ・・・俺の事を見ているのか？")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】違うな・・・キョロキョロしているところを見ると、ひっかかりそうな女の子を捜してるみたいだ。")
      (wait)
      (set-reg: 24 1)))
    ((&& (== V 1) (== N 15) (== (: 24) 1))
     (<> (text #:color 7 "【" 0 "】ん？・・・俺に気があるのか？") (wait)))
    ((&& (== V 1) (== N 17) (> T 0) (< T 600))
     (<>
      (text #:color 7 "【" 0 "】こんな時間なのに、みんな何をしてるんだろ？")
      (wait)
      (text #:color 7 "【" 0 "】あ・・・俺もそのうちの一人か。")
      (wait)))
    ((&& (== V 1) (== N 17) (== (: 25) 0))
     (<>
      (text #:color 7 "【" 0 "】とにかくたくさんの人がいる・・・俺の知り合いはいないようだが。")
      (wait)
      (set-reg: 25 1)))
    ((&& (== V 1) (== N 17) (== (: 25) 1))
     (<>
      (text #:color 7 "【" 0 "】おーい、みんな元気かいっ！！")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ははは、誰も返事をしない。")
      (wait)))
    ((&& (== V 1) (== N 18) (> T 0) (< T 600))
     (<> (text #:color 7 "【" 0 "】げげげっ！！こんな時間に、親子連れがいるぞ・・・変な家族だな。") (wait)))
    ((&& (== V 1) (== N 18) (== (: 26) 0))
     (<>
      (text #:color 7 "【" 0 "】子供連れの夫婦のようだな・・・結婚は人生の墓場とか言うが、本当の事なんだろうか？")
      (wait)
      (text #:color 7 "【" 0 "】こればっかりは、してみないとわからないだろうな・・・俺が結婚するのは何歳なんだろう？")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 1) (== N 18) (== (: 26) 1))
     (<> (text #:color 7 "【" 0 "】家族連れだ・・・俺にはファミリーな雰囲気は似合わない。") (wait)))
    ((&& (== V 1) (== N 19) (> T 0) (< T 500))
     (<> (text #:color 7 "【" 0 "】こんな時間に、新聞を読まなくてもいいと思うぞ・・・勝手だけど。") (wait)))
    ((&& (== V 1) (== N 19) (== (: 27) 0))
     (<>
      (text #:color 7 "【" 0 "】新聞を読んでいるな・・・車にひかれても知らないぞ。")
      (wait)
      (set-reg: 27 1)))
    ((&& (== V 1) (== N 19) (== (: 27) 1))
     (<> (text #:color 7 "【" 0 "】新聞がおやじを読んでいる・・・じゃなくて、おやじが新聞を読んでいる。") (wait)))
    ((&& (== V 1) (== N 20) (> T 0) (< T 600))
     (<>
      (text #:color 7 "【" 0 "】うーん、誰かを待っているのか・・・それとも、不特定多数の男を待っているのか？")
      (wait)
      (text #:color 7 "【" 0 "】さすが矢吹町だ・・・色々な人がいるから、人生の勉強になるなあ。")
      (wait)))
    ((&& (== V 1) (== N 20) (== (: 28) 0))
     (<>
      (text #:color 7 "【" 0 "】何をしているのかな？・・・なんとなく、大人の世界の匂いがするぜ。")
      (wait)
      (set-reg: 28 1)))
    ((&& (== V 1) (== N 20) (== (: 28) 1))
     (<>
      (text #:color 7 "【" 0 "】このスタイルといい、仕草といい、ふとももの太さといい、ただ者じゃないぞ。")
      (wait)
      (text #:color 7 "【" 0 "】ただ俺は、かかわり合いになりたくない。")
      (wait)))
    ((&& (== V 1) (== N 21) (> T 0) (< T 500))
     (<> (text #:color 7 "【" 0 "】矢吹町は、違法駐車だらけだ・・・みんな路上を駐車場だと思ってるな。") (wait)))
    ((&& (== V 1) (== N 21) (== (: 29) 0))
     (<>
      (text #:color 7 "【" 0 "】矢吹町は、いつも渋滞している・・・ひどい時は１時間で５メートルぐらいしか動かないんだ。")
      (wait)
      (set-reg: 29 1)))
    ((&& (== V 1) (== N 21) (== (: 29) 1))
     (<>
      (text #:color 7 "【" 0 "】色々な車が走ってるな・・・。")
      (wait)
      (text #:color 7 "【" 0 "】あ・・・あの車、パンクしてるぞ。")
      (wait)))
    ((&& (== V 1) (== N 22) (== (: 30) 0))
     (<>
      (text #:color 7 "【" 0 "】さすがに矢吹町の空だ、昼でも夜でも、霞がかかったようにどんよりしている。")
      (wait)
      (set-reg: 30 1)))
    ((&& (== V 1) (== N 22) (== (: 30) 1))
     (<> (text #:color 7 "【" 0 "】本当の空の色が見たいのなら、飛行機に乗って雲の上に出ないとな・・・。") (wait)))
    ((&& (== V 6) (== N 16) (== (: 25) 0))
     (<>
      (text #:color 7 "【" 0 "】あのなあ・・・俺は何を考えているんだ？")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】実を言うと、何も考えてなかったんだ。")
      (wait)
      (set-reg: 25 1)))
    ((&& (== V 6) (== N 16) (== (: 25) 1))
     (<>
      (text #:color 7 "【" 0 "】そうだな、ペンキをつけて・・・汚れてますよと言って。")
      (wait)
      (text #:color 7 "【" 0 "】冗談だよ、そんな事をしに矢吹町に来た訳じゃない。")
      (wait)))
    ((&& (== V 2) (== N 6) (> T 1900))
     (<>
      (text #:color 2 "【女の人】やっと大人の時間がやって来たわね・・・。")
      (wait)
      (text #:color 1 "【男の人】ああ・・・今日も濃厚なのを、こんこんこーんっ！！とやってやるぜ。")
      (wait)))
    ((&& (== V 2) (== N 6) (> T 0) (< T 400))
     (<>
      (text #:color 2 "【女の人】やっと大人の時間がやって来たわね・・・。")
      (wait)
      (text #:color 1 "【男の人】ああ・・・今日も濃厚なのを、こんこんこーんっ！！とやってやるぜ。")
      (wait)))
    ((&& (== V 2) (== N 6) (== (: 15) 0))
     (<>
      (text #:color 2 "【女の人】ねえ・・・どこかに遊びに行こうよー。")
      (wait)
      (text #:color 1 "【男の人】そうだな、この近所のホテルに行かないか？・・・イッパツやろうぜ。")
      (wait)
      (text #:color 2 "【女の人】イッパツだけじゃいや。")
      (wait)
      (text #:color 7 "【" 0 "】おいおい。")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 2) (== N 6) (== (: 15) 1))
     (<>
      (text #:color 2 "【女の人】ねえねえ、私、お腹がすいちゃた。")
      (wait)
      (text #:color 1 "【男の人】しょうがねえなあ、俺の肉棒でも食べるか？")
      (wait)
      (text #:color 2 "【女の人】うれしいっ！！その言葉を待ってたのよ！！")
      (wait)
      (text #:color 7 "【" 0 "】・・・ふう。")
      (wait)))
    ((&& (== V 2) (== N 7) (> T 1900))
     (<>
      (text #:color 1 "【男の人】やっと暗くなったな・・・昼間だと、どうも人目が気になるよ。")
      (wait)
      (text #:color 2 "【女の人】こんな場所で、やろうとするあなたが悪いのよ。")
      (wait)))
    ((&& (== V 2) (== N 7) (> T 0) (< T 400))
     (<>
      (text #:color 1 "【男の人】やっと暗くなったな・・・昼間だと、どうも人目が気になるよ。")
      (wait)
      (text #:color 2 "【女の人】こんな場所で、やろうとするあなたが悪いのよ。")
      (wait)))
    ((&& (== V 2) (== N 7) (== (: 16) 0))
     (<>
      (text #:color 1 "【男の人】なあ・・・これからどこかに出かけないか？")
      (wait)
      (text #:color 2 "【女の人】いや・・・私はあなたと二人きりになりたいの。")
      (wait)
      (text #:color 2 "【女の人】いいでしょ？・・・ひさしぶりにイッパツやりましょうよ。")
      (wait)
      (text #:color 1 "【男の人】イッパツだけかい？")
      (wait)
      (text #:color 2 "【女の人】もう、見栄を張らないでよ・・・あなたはイッパツしかできない体質じゃない。")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 2) (== N 7) (== (: 16) 1))
     (<>
      (text #:color 1 "【男の人】なあ・・・なんだかお腹が空かないか？")
      (wait)
      (text #:color 2 "【女の人】ふふふ、わかってるわよ・・・私の股間についてる、ジュシーなギョウザを食べさせてあげる。")
      (wait)
      (text #:color 1 "【男の人】やったあ！！うれしいなっと！！")
      (wait)
      (text #:color 7 "【" 0 "】・・・日本は滅びるんじゃないか？")
      (wait)))
    ((&& (== V 2) (== N 8) (> T 1900))
     (<> (text #:color 1 "【男の人】まだ帰れないぞ・・・もしかして俺は、一生家に帰れないんじゃないか？") (wait)))
    ((&& (== V 2) (== N 8) (> T 0) (< T 400))
     (<> (text #:color 1 "【男の人】こんな時間に仕事をしているなんて・・・俺ってかわいそうだな、うっうっうっ。") (wait)))
    ((&& (== V 2) (== N 8) (== (: 17) 0))
     (<>
      (text #:color 1 "【男の人】あーあ、まったく・・・どうしてこんなに働かないといけないんだ。")
      (wait)
      (text
       #:color
       1
       "【男の人】休みもなくみっちり働いて、いったい何が残ると言うのだ・・・残るのは疲労だけじゃないか、ぶつぶつぶつ。")
      (wait)
      (set-reg: 17 1)))
    ((&& (== V 2) (== N 8) (== (: 17) 1))
     (<>
      (text #:color 1 "【男の人】くっそー・・・忙しいなあ、まったく。")
      (wait)
      (text #:color 1 "【男の人】これでもう５日間も寝てないぞ・・・だんだん今日が何日で、何曜日だかわからなくなってくるな。")
      (wait)))
    ((&& (== V 2) (== N 9) (> T 0) (< T 600) (== (: 18) 0))
     (<>
      (text #:color 1 "【男の人】なあ、どこかにかわいい女の子はいないかな？")
      (wait)
      (text
       #:color
       4
       "【男の人】そうだな、こんな時間にウロウロしている女の子だったら、声をかけなくても目配せだけでついて来そうだぜ。")
      (wait)
      (text #:color 1 "【男の人】よーし、がんばってサセ子ちゃんを捜そうっ！！")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 2) (== N 9) (> T 0) (< T 600) (== (: 18) 1))
     (<>
      (text #:color 1 "【男の人】なあ、やりてえよなあ。")
      (wait)
      (text #:color 4 "【男の人】ああ、やりたい。")
      (wait)
      (text #:color 1 "【男の人】こうなったら、どんな女の子でもいいか・・・。")
      (wait)
      (text #:color 4 "【男の人】そうだな、どんな女でもいいぜ・・・とにかく、どこかにシケ込まないとシャレにならないぜ。")
      (wait)))
    ((&& (== V 2) (== N 9) (== (: 18) 0))
     (<>
      (text #:color 1 "【男の人】なあ、最近の不況についてどう思う？")
      (wait)
      (text
       #:color
       4
       "【男の人】そうだなあ、なんと言っても土地重視の経済が破綻した訳だからな・・・しかし、日本で資産として認められる物は、やはり土地しかないと思うぞ。")
      (wait)
      (text #:color 1 "【男の人】なるほど・・・しかし、総量規制が解除されたとしても、銀行もサービス基準とかがあるし・・・。")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 2) (== N 9) (== (: 18) 1))
     (<>
      (text #:color 1 "【男の人】なあ、最近の女の事をどう思う？")
      (wait)
      (text #:color 4 "【男の人】噂では、バブルジジイ達に囲われていたねーちゃん達が、路頭に迷っているって話だぜ。")
      (wait)
      (text #:color 1 "【男の人】ふっふっふっ、やっと俺達のような、若い肉体が活躍する時がやってきたという訳か。")
      (wait)))
    ((&& (== V 2) (== N 10) (> T 0) (< T 600) (== (: 19) 0))
     (<>
      (text
       #:color
       1
       "【男の人】なあ・・・俺は、この深夜の繁華街を見ていると、エコロジーとか叫ばれている事が無意味に思えてくるんだ。")
      (wait)
      (text #:color 4 "【男の人】そうだな、セックスの激しい腰使いもエコロジーに反するよな。")
      (wait)
      (text #:color 1 "【男の人】お前・・・俺の言う事を聞いてないだろ？")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 2) (== N 10) (> T 0) (< T 600) (== (: 19) 1))
     (<>
      (text #:color 1 "【男の人】最近は病気に気をつけないとな・・・フリーセックスの時代は終ったんだ。")
      (wait)
      (text #:color 4 "【男の人】ああ、でもお前は平気でやっているじゃないか。")
      (wait)
      (text #:color 1 "【男の人】俺は大丈夫だよ、ちゃんとコンドームを３枚重ねでやってるからな。")
      (wait)))
    ((&& (== V 2) (== N 10) (== (: 19) 0))
     (<>
      (text #:color 1 "【男の人】どこかに、いい穴が歩いてないかな？")
      (wait)
      (text #:color 4 "【男の人】お前、その『穴』って言い方はよせよ・・・下品だぜ。")
      (wait)
      (text #:color 1 "【男の人】きれい事を言うなよ、お前だってやりたいから、こうやってナンパをしてるんだろ？")
      (wait)
      (text #:color 4 "【男の人】いいや・・・俺は人生をというものを極める為に、新しい女性を求めているのだ。")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 2) (== N 10) (== (: 19) 1))
     (<>
      (text #:color 1 "【男の人】なあ・・・ナンパなんかやめて、俺達二人でホテルに行かないか？")
      (wait)
      (text #:color 4 "【男の人】・・・。")
      (wait)
      (text #:color 4 "【男の人】・・・。")
      (wait)
      (text #:color 4 "【男の人】・・・。")
      (wait)
      (text #:color 4 "【男の人】・・・行こうか。")
      (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))