(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\。
  #\太
  #\郎
  #\い
  #\な
  #\っ
  #\と
  #\て
  #\！
  #\る
  #\？
  #\か
  #\あ
  #\が
  #\ー
  #\に
  #\行
  #\お
  #\、
  #\ぜ
  #\の
  #\く)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "01.pd8")
 (proc 15)
 (set-arr~ @ 6 1)
 (image "s.pd8")
 (proc 16)
 (set-arr~ @ 6 1)
 (image "fan.pd8")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 0)
 (load "f.s4" (~ @ 2))
 (animate 0 0 1)
 (animate 1 0)
 (set-arr~ @ 7 0)
 (sound 1)
 (set-var I 2)
 (proc 26)
 (set-reg: 835 0)
 (set-arr~ @ 7 0)
 (load "s.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (if (== (: 453) 0)
   (<>
    (text #:color 7 "【" 0 "】あらら・・・マタロウがいるぞ。")
    (wait)
    (text #:color 5 "【太郎】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】おーい。")
    (wait)
    (text #:color 5 "【太郎】・・・。")
    (wait)
    (text #:color 7 "【" 0 "】やっほー！！")
    (wait)
    (text #:color 5 "【太郎】ん？・・・" 0 "君じゃないか。")
    (wait)
    (text #:color 7 "【" 0 "】ぼーっとしてると、車にひかれるぜ。")
    (wait)
    (text #:color 5 "【太郎】誰がぼーっとしてるって？・・・僕は平気だ。")
    (wait)
    (set-reg: 453 1)))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "他の場所に行く") (text "電車に乗る") (text "やめる")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】じゃあな・・・俺は行くぜ。")
         (wait)
         (text #:color 5 "【太郎】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】とっとと、行こう。")
         (wait)
         (set-var N 21)
         (slot 1 3)
         (mes-jump "town1.mes")))
       ((&& (== N 2) (< M 300))
        (<>
         (text #:color 7 "【" 0 "】（げっ・・・３００円すら、俺は持ってないのか！？）")
         (wait)
         (text #:color 7 "【" 0 "】（電車賃がなくて、先負町に帰れないなんて・・・口が裂けても言えないぜ。）")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】じゃあな・・・俺は行くぜ。")
         (wait)
         (text #:color 5 "【太郎】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】とっとと、行こう。")
         (wait)
         (set-var A 30)
         (proc 12)
         (set-var M (- M 300))
         (proc 11)
         (set-var N 1)
         (mes-call "den.mes")
         (slot 1 2)
         (mes-jump "sakima.mes")))
       ((== N 3)
        (<>
         (text #:color 5 "【太郎】ん？・・・何か言ったか？")
         (wait)
         (text #:color 7 "【" 0 "】何も言ってないぜ・・・お告げでも聞いたのか？")
         (wait)))
       (else (<>)))))
    ((&& (== V 3) (== N 8))
     (<>
      (sound 1)
      (set-var I 37)
      (proc 26)
      (text #:color 5 "【太郎】・・・。")
      (wait)
      (sound 1)
      (set-var I 2)
      (proc 26)
      (text #:color 7 "【" 0 "】あれれ！？・・・反応がないぞ。")
      (wait)))
    ((&& (== V 1) (== N 9))
     (<>
      (text #:color 5 "【太郎】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】なあ。")
      (wait)
      (text #:color 5 "【太郎】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】おい。")
      (wait)
      (text #:color 5 "【太郎】・・・。")
      (wait)))
    ((&& (== V 1) (== N 10))
     (<>
      (text #:color 5 "【太郎】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】おーい。")
      (wait)
      (text #:color 5 "【太郎】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】マタロウっ！！")
      (wait)
      (text #:color 5 "【太郎】・・・。")
      (wait)))
    ((&& (== V 1) (== N 11))
     (<>
      (text #:color 5 "【太郎】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】セックス。")
      (wait)
      (text #:color 5 "【太郎】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】したい。")
      (wait)
      (text #:color 5 "【太郎】・・・。")
      (wait)))
    ((&& (== V 1) (== N 12))
     (<>
      (text #:color 5 "【太郎】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】リンリン。")
      (wait)
      (text #:color 5 "【太郎】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ランラン。")
      (wait)
      (text #:color 5 "【太郎】・・・。")
      (wait)))
    ((&& (== V 1) (== N 13))
     (<>
      (text #:color 5 "【太郎】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ところで・・・その本だけど。")
      (wait)
      (text #:color 5 "【太郎】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】おいっ！！")
      (wait)
      (text #:color 5 "【太郎】・・・。")
      (wait)))
    ((&& (== V 2) (== N 7) (== (: 18) 0))
     (<>
      (text #:color 5 "【太郎】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】他の場所に行こうかなー。")
      (wait)
      (text #:color 5 "【太郎】・・・。")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 2) (== N 7) (== (: 18) 1))
     (<>
      (text #:color 7 "【" 0 "】じゃあな・・・。")
      (wait)
      (text #:color 5 "【太郎】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ばいばい。")
      (wait)
      (text #:color 5 "【太郎】・・・。")
      (wait)
      (set-reg: 18 2)))
    ((&& (== V 2) (== N 7) (== (: 18) 2))
     (<>
      (text #:color 5 "【太郎】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 5 "【太郎】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】（だめだ・・・気が狂いそうになってくる。）")
      (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))