(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\。
  #\い
  #\ん
  #\な
  #\、
  #\た
  #\の
  #\だ
  #\っ
  #\し
  #\は
  #\て
  #\あ
  #\ー
  #\俺
  #\よ
  #\う
  #\が
  #\彼
  #\女
  #\と
  #\か
  #\さ
  #\を
  #\く
  #\に
  #\れ
  #\も
  #\ま
  #\や
  #\見
  #\り
  #\じ
  #\で
  #\ら)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (sound 1)
 (set-var I 59)
 (proc 26)
 (set-reg: 835 0)
 (while
  (== 1 1)
  (<>
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (if-else (== N 14)
     (<>
      (text #:color 7 "【" 0 "】よーし、やよいさんのデータを見るぞ。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "52.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "u.pd8")
      (proc 16)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "uan.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "u.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】うーん・・・あのぶつかりねーちゃんが、やよいさんだったんだ。")
      (wait)
      (slot 1 7)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "53.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 9)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "u01.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 25)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "u02.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 25)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "u01an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "u01.s4" (~ @ 2))
      (animate 0 0 2)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】やよいさんは、看護婦さんなんだ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】じじいが邪魔だな・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "53.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 9)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "u01.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 25)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "u01an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "u01.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】うんうん、これでいいぞ。")
      (wait)
      (text #:color 7 "【" 0 "】彼女の名前は『草薙　やよい』・・・うーん、なんていい名前なんだ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "u04.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "u04an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "u04.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】もしかしたら俺は、世界一奇麗な看護婦さんと知り合ってしまったのかもしれないぞ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ああ、思い出しただけで・・・俺様の純なハートがうずくぜ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "u05.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】うーん、満足だぜ・・・じっくりと思い出してしまった。")
      (wait)
      (if-else (== (: 602) 1)
        (<>
         (slot 1 7)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "u03.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "u03an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "u03.s4" (~ @ 2))
         (animate 0 0 2)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text
          #:color
          7
          "【"
          0
          "】やよいさんの下着を見たあとは、今度は俺のナニを見られてしまった・・・まあ泌尿器科だから、不思議な事ではないけど。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】彼女が俺のナニを見る視線は・・・ちょっと普通じゃなかったような？")
         (wait))
        (<>))
      (if-else (== (: 617) 1)
        (<>
         (slot 1 7)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "u07.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "u07an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "u07.s4" (~ @ 2))
         (set-arr~ @ 7 0)
         (animate 0 8 0)
         (animate 4 8)
         (text #:color 7 "【" 0 "】そして・・・こんな事になってしまったんだ。")
         (wait)
         (text #:color 7 "【" 0 "】俺は彼女を見ながら、自分でしごいた・・・。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "u06.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "u06an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "u06.s4" (~ @ 2))
         (set-arr~ @ 7 0)
         (animate 0 8 0)
         (animate 4 8)
         (text #:color 7 "【" 0 "】彼女の胸は大きかった・・・柔らかくて、形がよくて、何よりも優しさを感じる胸だった。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】ああ・・・もう一度触りたい、なめたい、噛みたいっ！！")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "u08.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "u08an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "u08.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】彼女は俺の為に、色々なポーズをとってくれた・・・彼女こそ俺にとっては白衣の天使だった。")
         (wait)
         (text #:color 7 "【" 0 "】黒い下着と淡いグリーンの看護服・・・ああ、なんて色っぽいんだ。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "u09.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "u09an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "u09.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (animate 0 8 1)
         (animate 4 8)
         (text #:color 7 "【" 0 "】このポーズは、とてつもなく刺激的だった・・・あんな奇麗な人が俺の為だけにしてくれたんだ。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】彼女の心は天使以上に優しいのかもしれない・・・。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "u10.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】そして俺は、彼女の胸の中で・・・はててしまったんだ。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait))
        (<>))
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "42.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】あの病院に行けば、彼女に会える事は確実だが・・・問題は俺が健康だという事だな。")
      (wait)
      (set-reg: 608 1)
      (slot 1 2)
      (mes-jump "myroom.mes"))
     (<>))))
 (set-arr~ @ 7 1))