(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\し
  #\て
  #\の
  #\た
  #\。
  #\な
  #\っ
  #\、
  #\い
  #\だ
  #\を
  #\先
  #\に
  #\生
  #\よ
  #\う
  #\ん
  #\俺
  #\か
  #\は
  #\る
  #\が
  #\と
  #\で
  #\れ
  #\も
  #\事
  #\あ
  #\け
  #\こ
  #\そ
  #\ら
  #\ゃ
  #\ま
  #\見
  #\ど
  #\く
  #\じ
  #\ン
  #\え
  #\？
  #\ー
  #\時
  #\ろ
  #\さ
  #\ち
  #\来
  #\や
  #\す
  #\部
  #\屋
  #\り
  #\ト
  #\女
  #\ぜ
  #\色
  #\キ
  #\め
  #\ッ)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (sound 1)
 (set-var I 60)
 (proc 26)
 (set-reg: 835 0)
 (while
  (== 1 1)
  (<>
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((&& (== N 7) (== (: 641) 0))
     (<>
      (text #:color 7 "【" 0 "】え！？・・・よしこ先生のデータを見るのか？")
      (wait)
      (slot 1 3)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "c01.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "c01an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "c01.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】『芹沢　よしこ』・・・先負学園の先生で、俺達の担任でもある。")
      (wait)
      (text #:color 7 "【" 0 "】年齢は知らないけど、たぶん２５歳前後だろう・・・とにかく男女交際についてはうるさい先生だぜ。")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】まあ、いやな先生じゃないし、ただ単に真面目すぎるんだろうけど・・・もう少し、俺達の甘酸っぱい気持ちを理解して欲しいよなあ。")
      (wait)
      (slot 1 3)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "c02.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 0)
      (text
       #:color
       7
       "【"
       0
       "】それにしても、あのポーズは過激だったぜ・・・まさか俺が見ている事を知っていた訳じゃないだろうな！？")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】でも、俺が机の下にいる事はわかってるんだから・・・普通だったら足を組まないんじゃないか？")
      (wait)
      (if-else (== (: 317) 1)
        (<>
         (slot 1 2)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "35.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "c.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "can.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "c.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text
          #:color
          7
          "【"
          0
          "】うーん・・・肌を見せない着こなしといい、手で胸を隠すようにするポーズといい、男の対して警戒心を持ってるように感じるが。")
         (wait)
         (text #:color 7 "【" 0 "】しかし、あの下着はハデだったぜ・・・いったいどっちが本当の芹沢先生なんだろう？")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】芹沢先生って・・・けっこうモンモンとした夜を過ごしてるんじゃないか？")
         (wait))
        (<>))
      (if-else (== (: 633) 1)
        (<>
         (slot 1 7)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "c13.pd8")
         (proc 15)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "c13an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "c13.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】そうだよ・・・そのモンモンとしたよしこ先生が、俺の部屋に来たんだっけ。")
         (wait)
         (text #:color 7 "【" 0 "】色々と話をしたけど・・・俺はロクな返事をしなかったよな。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】考えてみれば、悪い事をしたかな・・・？")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "c03.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 0)
         (text
          #:color
          7
          "【"
          0
          "】そうそう、話の流れで中学の卒業アルバムを見せて・・・先生が俺の方に来て、アルバムをのぞき込んだ時だよ・・・。")
         (wait)
         (text #:color 7 "【" 0 "】胸元が見えて・・・なんかドキドキしちゃったよな。")
         (wait)
         (text #:color 7 "【" 0 "】ほんのりとシャンプーの香りがして・・・ああ、よしこ先生も女性なんだよなあ。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】先生はまさか・・・いやらしい事を期待して、俺の部屋に来たわけじゃないだろうな？")
         (wait))
        (<>))
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "42.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】やめた・・・たぶん俺の考えすぎだろう。")
      (wait)
      (set-reg: 608 1)
      (slot 1 2)
      (mes-jump "myroom.mes")))
    ((&& (== N 7) (== (: 641) 1))
     (<>
      (text #:color 7 "【" 0 "】よしこ先生のデータを見るのか・・・。")
      (wait)
      (slot 1 3)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "c01.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "c01an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "c01.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】『芹沢　よしこ』・・・先負学園の先生で、俺達の担任でもある。")
      (wait)
      (slot 1 3)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "c02.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】よしこ先生は口うるさいけど・・・優しい女性のような気がする。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "35.pd8")
      (proc 15)
      (set-arr~ @ 6 1)
      (image "c.pd8")
      (proc 16)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "can.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "c.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】前は男嫌いかと思ってたけど・・・そんな事はないんだよな。")
      (wait)
      (text #:color 7 "【" 0 "】先生だって一人の女性だし・・・ただ俺達の先生ってだけで、多少は色メガネで見てたようだ。")
      (wait)
      (slot 1 7)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "c13.pd8")
      (proc 15)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "c13an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "c13.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】俺の部屋に来てくれたのも、考えてみれば・・・将来の事を心配してくれた訳だし。")
      (wait)
      (text #:color 7 "【" 0 "】適当に答えて、悪い事をしたよな・・・本当に。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "c03.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】中学の卒業アルバムを見せた時・・・初めて先生の女らしさを感じたんだ。")
      (wait)
      (text #:color 7 "【" 0 "】もっとも、先生はそんなつもりじゃなかっただろうけど・・・色っぽかったよな、本当に。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "c04.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "c04an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "c04.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】そして・・・よしこ先生が痴漢に襲われてる所に、偶然俺が通りかかって。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "c05.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "c05an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "c05.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 7 "【" 0 "】あの馬鹿痴漢野郎の事を思い出すと、今でも腹が立ってくるぜ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】俺はパンツを脱いで、あの馬鹿を油断させて・・・先生を助けたんだ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "c06.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "c06an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "c06.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 7 "【" 0 "】メガネは割れちゃうし、ストッキングは破れちゃう・・・ひどかったよな。")
      (wait)
      (text #:color 7 "【" 0 "】で、俺は先生を自分の部屋・・・つまりここに連れて来たんだ。")
      (wait)
      (text #:color 7 "【" 0 "】先生がシャワーを使ってる間に、俺はストッキングを買って来て・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "c07.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "c07an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "c07.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】部屋に戻ったら、ちょうど先生がバスルームのドアの所に立っていて・・・。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】まさか、シャツだけで出てくるとは思わなかったから・・・びっくりしたよな。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "c08.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "c08an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "c08.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】それで俺のベットの上に座ってもらって・・・色々と話をしたんだ。")
      (wait)
      (text #:color 7 "【" 0 "】そうだよ・・・先生の姿を見てたら、俺は色々と変な事を想像しちゃったんだ。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "c09.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "c09an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "c09.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 7 "【" 0 "】抱きしめて、キスした時の事や・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "c10.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "c10an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "c10.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 7 "【" 0 "】ベットに押し倒して、シャツをはがし、胸に顔を埋めた時の事や・・・。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "c11.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "c11an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "c11.s4" (~ @ 2))
      (animate 0 0 0)
      (animate 1 0)
      (set-arr~ @ 7 0)
      (animate 0 8 1)
      (animate 4 8)
      (text #:color 7 "【" 0 "】そして・・・先生と結ばれた時の事を。")
      (wait)
      (text #:color 7 "【" 0 "】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】俺もとんでもないやつだよな・・・あんな目に合った直後に、考える事じゃないぜ、まったく。")
      (wait)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 9 (&& (~ @ 9) 65534))
      (set-arr~ @ 6 1)
      (image "c12.pd8")
      (set-arr~ @ 9 (// (~ @ 9) 1))
      (proc 24)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "c12an.pd8")
      (set-arr~ @ 6 0)
      (set-arr~ @ 7 0)
      (load "c12.s4" (~ @ 2))
      (set-arr~ @ 7 0)
      (animate 0 8 0)
      (animate 4 8)
      (text #:color 7 "【" 0 "】先生が・・・俺が怪我してると思って、立とうとした時だ。")
      (wait)
      (text #:color 7 "【" 0 "】先生はまだフラフラしてて・・・俺が手を伸ばして支えようとしたんだ。")
      (wait)
      (text #:color 7 "【" 0 "】二人でベットの上に倒れてしまった・・・そして俺の手が先生の胸に・・・。")
      (wait)
      (text #:color 7 "【" 0 "】あの時の俺は、セメントで固められたように動けなくなってしまった。")
      (wait)
      (slot 1 2)
      (set-arr~ @ 7 1)
      (set-arr~ @ 1 4096)
      (set-arr~ @ 6 1)
      (image "42.pd8")
      (proc 15)
      (set-arr~ @ 7 0)
      (text #:color 7 "【" 0 "】先生が部屋を出て行く時に言った言葉が・・・今でも忘れられない。")
      (wait)
      (set-reg: 608 1)
      (slot 1 2)
      (mes-jump "myroom.mes")))
    (else (<>)))))
 (set-arr~ @ 7 1))