(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\。
  #\い
  #\ー
  #\っ
  #\舞
  #\る
  #\、
  #\な
  #\ん
  #\あ
  #\う
  #\！
  #\（
  #\）
  #\だ
  #\く
  #\て
  #\ゃ
  #\は
  #\の
  #\に
  #\た
  #\か
  #\よ
  #\？
  #\ら
  #\ち
  #\し
  #\乗
  #\君
  #\と
  #\も
  #\わ
  #\き
  #\が
  #\え
  #\ン
  #\す
  #\り
  #\れ
  #\ひ
  #\ね
  #\そ
  #\ど
  #\や
  #\け
  #\ま
  #\じ
  #\ぜ
  #\お
  #\俺
  #\を
  #\ゆ
  #\見
  #\ろ
  #\で
  #\こ
  #\つ
  #\プ
  #\キ
  #\何
  #\タ
  #\ド
  #\カ
  #\ッ
  #\言
  #\コ
  #\ょ
  #\物
  #\事
  #\リ
  #\人
  #\一
  #\色
  #\ぶ
  #\回
  #\ゴ
  #\ト
  #\ば
  #\二
  #\さ
  #\私
  #\ガ
  #\気
  #\『
  #\』
  #\ル
  #\化
  #\バ
  #\イ
  #\度
  #\行
  #\シ
  #\ュ
  #\ぷ
  #\屋
  #\敷
  #\グ
  #\ご
  #\げ
  #\み
  #\胸
  #\せ
  #\ラ
  #\日
  #\首
  #\ぽ)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "58.pd8")
 (proc 15)
 (set-arr~ @ 6 1)
 (image "v.pd8")
 (proc 16)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "van.pd8")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 0)
 (load "v.s4" (~ @ 2))
 (animate 0 0 0)
 (animate 1 0)
 (set-arr~ @ 7 0)
 (sound 1)
 (set-var I 61)
 (proc 26)
 (set-reg: 835 0)
 (set-arr~ @ 7 0)
 (load "58v.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (if (== (: 762) 1)
   (<>
    (text #:color 7 "【" 0 "】や、やっとついたあ・・・。")
    (wait)
    (text #:color 3 "【舞】わあ・・・ドキドキしてきちゃった。")
    (wait)
    (text #:color 7 "【" 0 "】（ドキドキって・・・そうか、ずっと遊園地には来てなかったんだもんな。）")
    (wait)
    (text #:color 3 "【舞】ねえねえ、" 0 "君・・・何から乗ろうか？")
    (wait)
    (text #:color 7 "【" 0 "】（うーん、すっかり童心にかえってるような？）")
    (wait)))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<> (text "走る")))
      (cond
       ((&& (== N 1) (== (: 10) 0))
        (<> (text #:color 3 "【舞】たからね・・・もう走る必要はないわよ。") (wait) (set-reg: 10 1)))
       ((&& (== N 1) (== (: 10) 1))
        (<>
         (text #:color 3 "【舞】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】わかってるって・・・走らないよ。")
         (wait)))
       (else (<>)))))
    ((&& (== V 2) (== N 1))
     (<>
      (cond
       ((== (: 10) 0)
        (<>
         (text #:color 3 "【舞】ねえねえ、" 0 "君・・・何から遊ぶ？")
         (wait)
         (text #:color 7 "【" 0 "】うーん・・・。")
         (wait)))
       ((== (: 10) 1)
        (<> (text #:color 3 "【舞】ねえねえ、" 0 "君・・・次は何に乗ろうか？") (wait)))
       (else (<>)))
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show
       (<.>
        (if (== (: 11) 0) (text "観覧車"))
        (if (== (: 12) 0) (text "ループコースター"))
        (text "お化け屋敷")
        (if (== (: 13) 0) (text "バイキング"))
        (if (== (: 14) 0) (text "散歩"))
        (if (== (: 15) 0) (text "回転木馬"))
        (if (== (: 16) 0) (text "ゴーカート"))
        (if (== (: 17) 0) (text "エレベーター"))
        (if (== (: 40) 0) (text "舞ちゃん"))
        (if (== (: 41) 0) (text "コーヒーカップ"))))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】（高い所は嫌いだけど・・・観覧車に乗れば、二人きりになれるぞ。）")
         (wait)
         (text #:color 7 "【" 0 "】舞ちゃんっ！！観覧車に乗ろうよ。")
         (wait)
         (text #:color 3 "【舞】" 0 "君、ごめんなさい・・・私、すごく高い所って苦手なの。")
         (wait)
         (text #:color 7 "【" 0 "】あ・・・そう。")
         (wait)
         (set-reg: 11 1)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】（げっ！？・・・本当に乗るのか！？）")
         (wait)
         (text #:color 7 "【" 0 "】舞ちゃん・・・ループコースターに乗らないよね？")
         (wait)
         (text #:color 3 "【舞】わあ・・・私、一度乗ってみたかったんだ。")
         (wait)
         (text #:color 7 "【" 0 "】いいんだよ、無理しなくても。")
         (wait)
         (text #:color 3 "【舞】早く行きましょうよ・・・ほら、あそこに並べばいいのよ。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "kuro.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (text #:color 3 "【舞】" 0 "君、ついてるわ・・・すぐに乗れるじゃない。")
         (wait)
         (text #:color 6 "プシューッ！！")
         (wait)
         (text #:color 7 "【" 0 "】（や、やだなあ・・・この待ってる間が。）")
         (wait)
         (text #:color 3 "【舞】" 0 "君・・・ドキドキしてる。")
         (wait)
         (text #:color 7 "【" 0 "】（む、胸に触っちゃおうかなあ・・・。）")
         (wait)
         (text #:color 6 "バビューーン！！")
         (wait)
         (text #:color 3 "【舞】きゃあああああっ！！")
         (wait)
         (text #:color 7 "【" 0 "】ぶひひひひひっ！！")
         (wait)
         (text #:color 3 "【舞】きゃっ！！きゃああああっ！！")
         (wait)
         (text #:color 7 "【" 0 "】ぶひーーーーっ！！")
         (wait)
         (text #:color 3 "【舞】きゃああああああっ！！きゃあっ、きゃあっ！！")
         (wait)
         (text #:color 7 "【" 0 "】ぶひーっ！！も、もう止めてくれえっ！！")
         (wait)
         (text #:color 6 "プシュー・・・。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "58.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "v.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "van.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "v.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】はあはあはあ・・・も、もう二度と乗るもんか。")
         (wait)
         (text #:color 3 "【舞】面白かったあ・・・" 0 "君、もう一度乗らない？")
         (wait)
         (text #:color 7 "【" 0 "】ま、舞ちゃん・・・また後にしようよ、ね？")
         (wait)
         (set-var A 15)
         (proc 12)
         (proc 11)
         (set-reg: 12 1)))
       ((&& (== N 3) (== (: 12) 1) (== (: 13) 1) (== (: 15) 1) (== (: 41) 1))
        (<>
         (text #:color 7 "【" 0 "】な、なんか目が回るな・・・。")
         (wait)
         (text #:color 3 "【舞】あははっ・・・でもすっごく楽しいわ。")
         (wait)
         (text #:color 3 "【舞】・・・。")
         (wait)
         (text #:color 3 "【舞】遊園地に来なくても・・・" 0 "君と一緒にいると、すごく楽しいの。")
         (wait)
         (text #:color 7 "【" 0 "】え？・・・何か言った？")
         (wait)
         (text #:color 3 "【舞】う、ううん・・・" 0 "君、次の乗物は？")
         (wait)
         (text #:color 7 "【" 0 "】今度こそお化け屋敷に行こうよ・・・ね？")
         (wait)
         (text #:color 3 "【舞】恐いけど・・・いいわよ。")
         (wait)
         (text #:color 7 "【" 0 "】よーし、お化け屋敷は・・・あそこの建物だな。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "kuro.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (sound 1)
         (text #:color 3 "【舞】やだ・・・誰も乗ってないわよ。")
         (wait)
         (text #:color 5 "【係員】お乗りになりますかあ？")
         (wait)
         (text #:color 3 "【舞】きゃっ！！・・・びっくりした。")
         (wait)
         (text #:color 5 "【係員】お二人様で向い合わせに座ってくださあい・・・いきますよお。")
         (wait)
         (text #:color 7 "【" 0 "】舞ちゃん・・・乗ろうぜ。")
         (wait)
         (text #:color 3 "【舞】う、うん・・・。")
         (wait)
         (text #:color 6 "プシュー・・・ガッコン。")
         (wait)
         (text #:color 6 "ガタガタガタ・・・ガタガタガタ・・・。")
         (wait)
         (text #:color 7 "【" 0 "】な、なんだかトロッコに乗ってるような感覚だな。")
         (wait)
         (text #:color 3 "【舞】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】あれれ！？・・・舞ちゃん！？")
         (wait)
         (slot 1 6)
         (mes-jump "v09.mes")))
       ((&& (== N 3) (== (: 45) 0))
        (<>
         (text #:color 7 "【" 0 "】（お化け屋敷と言えば・・・暗闇で二人きりだぜ。）")
         (wait)
         (text #:color 7 "【" 0 "】舞ちゃん、お化け屋敷に行こうよ。")
         (wait)
         (text #:color 3 "【舞】" 0 "君・・・私、恐いの苦手なの。")
         (wait)
         (text #:color 7 "【" 0 "】大丈夫さ、俺がついてるから。")
         (wait)
         (text #:color 3 "【舞】じゃあ・・・他の乗物に乗った後に行かない？")
         (wait)
         (text #:color 7 "【" 0 "】そうだな・・・ははは、ちぇっ。")
         (wait)
         (set-reg: 45 1)))
       ((&& (== N 3) (== (: 45) 1))
        (<>
         (text #:color 3 "【舞】" 0 "君、もう少し後で行きましょうよ。")
         (wait)
         (text #:color 7 "【" 0 "】はーい、ちぇっ。")
         (wait)))
       ((== N 4)
        (<>
         (text #:color 7 "【" 0 "】（げっ・・・あのブランコのお化けみたいのに乗るのか！？）")
         (wait)
         (text #:color 7 "【" 0 "】舞ちゃん・・・バイキングに乗らないよね？")
         (wait)
         (text #:color 3 "【舞】あ・・・私、乗りたいと思ってたの。")
         (wait)
         (text #:color 7 "【" 0 "】ははは・・・そう答えるだろうと思ったよ。")
         (wait)
         (text #:color 3 "【舞】" 0 "君、行きましょうよ・・・ほら、バイキングはあっちよ。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "kuro.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (text #:color 3 "【舞】" 0 "君、今日はついてるわね・・・すぐに乗れたじゃない。")
         (wait)
         (text #:color 7 "【" 0 "】ははは・・・は。")
         (wait)
         (text #:color 6 "ブーッ！！")
         (wait)
         (text #:color 3 "【舞】" 0 "君・・・動き出すわよ。")
         (wait)
         (text #:color 6 "ゆーら・・・ゆーら・・・。")
         (wait)
         (text #:color 7 "【" 0 "】（なんだ・・・大した事ないじゃないか。）")
         (wait)
         (text #:color 6 "ゆーーら・・・ゆーーーら。")
         (wait)
         (text #:color 7 "【" 0 "】（平気、平気・・・。）")
         (wait)
         (text #:color 6 "ゆーーーら・・・ゆーーーら。")
         (wait)
         (text #:color 7 "【" 0 "】（・・・。）")
         (wait)
         (text #:color 6 "ゆーーーーら・・・ゆーーーーら・・・ゆーーーーーら・・・ゆーーーーーら。")
         (wait)
         (text #:color 7 "【" 0 "】ぶひいいいいっ！！")
         (wait)
         (text #:color 3 "【舞】きゃーーーっ！！")
         (wait)
         (text #:color 6 "ゆーーーーーーら・・・ゆーーーーーーら。")
         (wait)
         (text #:color 7 "【" 0 "】うっぷっ！！おえっぷっ！！")
         (wait)
         (text #:color 6 "ゆーーーーーーーら・・・ゆーーーーーーーら。")
         (wait)
         (text #:color 3 "【舞】きゃああああああっ！！")
         (wait)
         (text #:color 7 "【" 0 "】ぶひひひひっ！！・・・も、もう止めてくれようっ！！")
         (wait)
         (text #:color 6 "プシュー・・・。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "58.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "v.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "van.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "v.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】はあはあはあっ・・・二度と乗るもんか。")
         (wait)
         (text #:color 3 "【舞】" 0 "君、大丈夫？")
         (wait)
         (set-var A 15)
         (proc 12)
         (proc 11)
         (set-reg: 13 1)))
       ((== N 5)
        (<>
         (text #:color 7 "【" 0 "】舞ちゃん、散歩をしよう。")
         (wait)
         (text #:color 3 "【舞】サンポ・・・サンポ・・・" 0 "君、サンポなんて乗物は見あたらないわ。")
         (wait)
         (text #:color 7 "【" 0 "】（うーん、冗談も通じないほど喜んじゃってるのか！？）")
         (wait)
         (set-reg: 14 1)))
       ((== N 6)
        (<>
         (text #:color 7 "【" 0 "】（回転木馬・・・ようするに、メリーゴーランドの事だな。）")
         (wait)
         (text #:color 7 "【" 0 "】（女子供が乗るものだぜ・・・俺は乗りたくないけど。）")
         (wait)
         (text #:color 3 "【舞】" 0 "君、何に乗るの？")
         (wait)
         (text #:color 7 "【" 0 "】舞ちゃん、メリーゴーランドなんてどう？")
         (wait)
         (text #:color 3 "【舞】いいわよ・・・かわいいし。")
         (wait)
         (text #:color 7 "【" 0 "】俺は・・・すぐそばで見ているから。")
         (wait)
         (text #:color 3 "【舞】そうよね、男の人はちょっと乗りづらいもの・・・じゃあ、私だけ乗ってくるわね。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "kuro.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (text #:color 6 "ブーッ！！")
         (wait)
         (text #:color 7 "【" 0 "】（動き始めたぞ・・・。）")
         (wait)
         (text #:color 7 "【" 0 "】（・・・。）")
         (wait)
         (text #:color 7 "【" 0 "】（・・・。）")
         (wait)
         (text #:color 3 "【舞】" 0 "くーん！！")
         (wait)
         (text #:color 7 "【" 0 "】舞ちゃーん！！")
         (wait)
         (text #:color 7 "【" 0 "】（・・・。）")
         (wait)
         (text #:color 7 "【" 0 "】（・・・。）")
         (wait)
         (text #:color 3 "【舞】" 0 "くーん！！")
         (wait)
         (text #:color 7 "【" 0 "】舞ちゃーん！！")
         (wait)
         (text #:color 7 "【" 0 "】（・・・。）")
         (wait)
         (text #:color 7 "【" 0 "】（見てるだけで・・・いやになってきた。）")
         (wait)
         (text #:color 3 "【舞】" 0 "くーん！！")
         (wait)
         (text #:color 7 "【" 0 "】ま、舞ちゃーん！！")
         (wait)
         (text #:color 7 "【" 0 "】（・・・。）")
         (wait)
         (text #:color 7 "【" 0 "】（いいかげんにしようぜ・・・おい。）")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "58.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "v.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "van.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "v.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 3 "【舞】ああ、楽しかった・・・ああやって手を振るの、一度やってみたかったのよ。")
         (wait)
         (text #:color 7 "【" 0 "】ははは・・・よかったねえ。")
         (wait)
         (set-var A 15)
         (proc 12)
         (proc 11)
         (set-reg: 15 1)))
       ((== N 7)
        (<>
         (text #:color 7 "【" 0 "】（舞ちゃんはスカートだから、ゴーカートに乗ればパンツが見えるぜ・・・ひっひっひっ。）")
         (wait)
         (text #:color 3 "【舞】" 0 "君・・・どうするの？")
         (wait)
         (text #:color 7 "【" 0 "】舞ちゃん、ゴーカートに乗らないか？")
         (wait)
         (text #:color 3 "【舞】一緒にだったら乗ってもいいわよ。")
         (wait)
         (text #:color 7 "【" 0 "】い、いや・・・俺はそばで見てるよ。")
         (wait)
         (text #:color 3 "【舞】えーっ・・・一人じゃ乗りたくないわ。")
         (wait)
         (text #:color 7 "【" 0 "】あ・・・そう。")
         (wait)
         (set-reg: 16 1)))
       ((== N 8)
        (<>
         (text #:color 7 "【" 0 "】舞ちゃん、エレベーターに乗ろう？")
         (wait)
         (text #:color 3 "【舞】え？・・・" 0 "君、何か言った？")
         (wait)
         (text #:color 7 "【" 0 "】何も・・・言ってない。")
         (wait)
         (set-reg: 17 1)))
       ((== N 9)
        (<>
         (text #:color 7 "【" 0 "】ひっひっひっ、舞ちゃんに乗りたいな。")
         (wait)
         (text #:color 3 "【舞】いいわよ、一緒に乗りましょうよ。")
         (wait)
         (text #:color 7 "【" 0 "】舞ちゃん『と』じゃなくて、『に』って言ったのっ！！")
         (wait)
         (text #:color 3 "【舞】え？・・・" 0 "君、何か言った？")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (set-reg: 40 1)))
       ((== N 10)
        (<>
         (text #:color 7 "【" 0 "】（クルクル回るやつには・・・あまり乗りたくないなあ。）")
         (wait)
         (text #:color 3 "【舞】" 0 "君・・・何にするの？")
         (wait)
         (text #:color 7 "【" 0 "】コーヒーカップなんて・・・いやだよね、うん、いやだ。")
         (wait)
         (text #:color 3 "【舞】いいわあ、映画のシーンであったわよね・・・私、" 0 "君と一緒に乗ってみたい。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "kuro.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (text #:color 3 "【舞】コーヒーカップってすいてるわ・・・人気がないのかしら？")
         (wait)
         (text #:color 7 "【" 0 "】ははは・・・俺達の為に、貸しきりにしてくれたんだよ。")
         (wait)
         (text #:color 6 "ブーッ！！")
         (wait)
         (text #:color 3 "【舞】きゃっ・・・回り出したわよ。")
         (wait)
         (text #:color 6 "くるくるくるくる。")
         (wait)
         (text #:color 7 "【" 0 "】（うーん・・・遠心力がきつくなってきた。）")
         (wait)
         (text #:color 6 "くるくるくるくるくるくるくるくるくる。")
         (wait)
         (text #:color 7 "【" 0 "】（う、うっぷ・・・。）")
         (wait)
         (text #:color 6 "くるくるくるくるくるくるくるくるくる。")
         (wait)
         (text #:color 7 "【" 0 "】（う、うっぷ、おえっぷ・・・。）")
         (wait)
         (text #:color 6 "くるくるくるくるくるくるくるくるくる。")
         (wait)
         (text #:color 7 "【" 0 "】（うううっぷっ！！）")
         (wait)
         (text #:color 6 "くるくるくるくるくるくるくるくるくる。")
         (wait)
         (text #:color 7 "【" 0 "】（も、もう・・・十分だよう。）")
         (wait)
         (text #:color 6 "プシュー・・・。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "58.pd8")
         (proc 15)
         (set-arr~ @ 6 1)
         (image "v.pd8")
         (proc 16)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "van.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "v.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 3 "【舞】ちょっと・・・目が回ったわね。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 3 "【舞】" 0 "君・・・顔色が変。")
         (wait)
         (set-var A 15)
         (proc 12)
         (proc 11)
         (set-reg: 41 1)))
       (else (<>)))
      (set-reg: 10 1)))
    ((&& (== V 1) (== N 2) (== (: 18) 0))
     (<>
      (text #:color 3 "【舞】" 0 "君・・・ここにずっと立ってるつもりなの？")
      (wait)
      (text #:color 7 "【" 0 "】（髪の毛に触れたい・・・。）")
      (wait)
      (text #:color 3 "【舞】" 0 "君・・・聞いている？")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 1) (== N 2) (== (: 18) 1))
     (<>
      (text #:color 7 "【" 0 "】舞ちゃんの髪って奇麗だよなあ・・・。")
      (wait)
      (text #:color 3 "【舞】そうかしら・・・普通だと思うけど。")
      (wait)))
    ((&& (== V 1) (== N 3) (== (: 19) 0))
     (<>
      (text #:color 3 "【舞】" 0 "君・・・どうしたの？")
      (wait)
      (text #:color 7 "【" 0 "】い、いや・・・見とれてただけさ。")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 1) (== N 3) (== (: 19) 1))
     (<> (text #:color 7 "【" 0 "】（舞ちゃんは、どこで見てもかわいいなあ・・・。）") (wait)))
    ((&& (== V 1) (== N 4) (== (: 20) 0))
     (<>
      (text #:color 7 "【" 0 "】（黄色いリボンだ・・・舞ちゃんって、いつも黄色いリボンだな。）")
      (wait)
      (set-reg: 20 1)))
    ((&& (== V 1) (== N 4) (== (: 20) 1))
     (<> (text #:color 7 "【" 0 "】（黄色いリボンをしてると、何かいい事があるとか・・・？）") (wait)))
    ((&& (== V 10) (== N 5) (== (: 21) 0))
     (<>
      (text #:color 7 "【" 0 "】（俺は舞の首筋に、舌を這わせる・・・『あっ』と声を上げる舞。）")
      (wait)
      (text #:color 7 "【" 0 "】（俺の舌は首筋から胸の谷間へ・・・ふくらんだ二つの丘をかき分けるように愛撫する。）")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】（『いいわ・・・"
       0
       "君』と舞は思わず言ってしまう・・・俺は舌先を、突起した舞の乳首に這わせ、そして強く歯を立てた。）")
      (wait)
      (text
       #:color
       7
       "【"
       0
       "】（『いったーい』と悲鳴を上げる舞、しかし俺はもう止まらないっ・・・さらに強く、乳首をカリカリといたぶるんだあっ！！）")
      (wait)
      (text #:color 7 "【" 0 "】はあっはあっはあっ・・・。")
      (wait)
      (text #:color 3 "【舞】ど、どうしたの？")
      (wait)
      (text #:color 7 "【" 0 "】理由はあるけど、ぜいぜい・・・絶対に説明できない。")
      (wait)
      (set-reg: 21 1)))
    ((&& (== V 10) (== N 5) (== (: 21) 1))
     (<> (text #:color 7 "【" 0 "】（疲れるから・・・もうよそう。）") (wait)))
    ((&& (== V 1) (== N 6) (== (: 22) 0))
     (<>
      (text #:color 7 "【" 0 "】（これをはずすと・・・どうなるんだろ？）")
      (wait)
      (text #:color 7 "【" 0 "】（・・・。）")
      (wait)
      (text #:color 7 "【" 0 "】（まさか・・・下着が見えるなんて事はないだろうな。）")
      (wait)
      (set-reg: 22 1)))
    ((&& (== V 1) (== N 6) (== (: 22) 1))
     (<> (text #:color 7 "【" 0 "】（またまた黄色だぜ・・・。）") (wait)))
    ((&& (== V 1) (== N 7) (== (: 23) 0))
     (<>
      (text #:color 7 "【" 0 "】（舞ちゃんの胸を・・・見れる時がくるのだろうか？）")
      (wait)
      (text #:color 7 "【" 0 "】（いいや、弱気は禁物だぜ・・・『見せぬなら、見せてもらおう舞ちゃんの胸』おそまつ。）")
      (wait)
      (set-reg: 23 1)))
    ((&& (== V 1) (== N 7) (== (: 23) 1))
     (<>
      (text #:color 7 "【" 0 "】（舞ちゃんの胸は・・・ピンク色に違いない。）")
      (wait)
      (text #:color 7 "【" 0 "】（言っておくけど、乳首の事だぜ。）")
      (wait)))
    ((&& (== V 1) (== N 8) (== (: 24) 0))
     (<>
      (text #:color 7 "【" 0 "】（舞ちゃんとデートしてるんだぜ・・・わかってるのか？）")
      (wait)
      (set-reg: 24 1)))
    ((&& (== V 1) (== N 8) (== (: 24) 1))
     (<> (text #:color 7 "【" 0 "】（舞ちゃんと俺の関係は・・・今日次第って感じがするぜ。）") (wait)))
    ((&& (== V 1) (== N 9) (== (: 25) 0))
     (<>
      (text #:color 7 "【" 0 "】ん？・・・誰だあいつは。")
      (wait)
      (text #:color 6 "【にいちゃん】じいいいいいいい。")
      (wait)
      (text #:color 7 "【" 0 "】すっぽんぴゃろぴょろぽーん！！")
      (wait)
      (text #:color 6 "【にいちゃん】じ、じいいいい・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ぴゃらろれぽすぽぽーん！！")
      (wait)
      (text #:color 6 "【にいちゃん】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】勝ったな。")
      (wait)
      (text #:color 3 "【舞】" 0 "君、何をしてるのかしら？")
      (wait)
      (set-reg: 25 1)))
    ((&& (== V 1) (== N 9) (== (: 25) 1))
     (<>
      (text #:color 7 "【" 0 "】なんだよ・・・まだ見てるぜ。")
      (wait)
      (text #:color 6 "【にいちゃん】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】そうか、俺に気があるんだな・・・ウィンクをしてやろう。")
      (wait)))
    ((&& (== V 1) (== N 10) (== (: 26) 0))
     (<>
      (text #:color 7 "【" 0 "】いやあ、色々な人がいるなあ。")
      (wait)
      (text #:color 3 "【舞】今日は日曜日だから・・・家族連れが多いんじゃないかしら？")
      (wait)
      (set-reg: 26 1)))
    ((&& (== V 1) (== N 10) (== (: 26) 1))
     (<> (text #:color 7 "【" 0 "】（ふっふっふっ・・・俺達以上のカップルは存在しないぜ。）") (wait)))
    ((&& (== V 1) (== N 11) (== (: 27) 0))
     (<>
      (text #:color 7 "【" 0 "】（メリーゴーランドだな・・・回ってるように見える。）")
      (wait)
      (text #:color 7 "【" 0 "】（見えるだろ？）")
      (wait)
      (set-reg: 27 1)))
    ((&& (== V 1) (== N 11) (== (: 27) 1))
     (<> (text #:color 7 "【" 0 "】（だからあ、メリーゴーランドだよ。）") (wait)))
    ((&& (== V 1) (== N 12) (== (: 28) 0))
     (<>
      (text #:color 7 "【" 0 "】（ゆーら、ゆーら・・・見てるだけで酔いそうだ。）")
      (wait)
      (text #:color 3 "【舞】" 0 "君・・・なんだか変よ。")
      (wait)
      (text #:color 7 "【" 0 "】（ああ・・・バイキングの中で、舞ちゃんとしたい。）")
      (wait)
      (set-reg: 28 1)))
    ((&& (== V 1) (== N 12) (== (: 28) 1))
     (<> (text #:color 7 "【" 0 "】（バイキングだぜ・・・俺は嫌いだ。）") (wait)))
    ((&& (== V 1) (== N 13) (== (: 29) 0))
     (<>
      (text #:color 7 "【" 0 "】（ループコースターだな・・・。）")
      (wait)
      (text #:color 7 "【" 0 "】（俺は・・・嫌いだっ。）")
      (wait)
      (set-reg: 29 1)))
    ((&& (== V 1) (== N 13) (== (: 29) 1))
     (<> (text #:color 7 "【" 0 "】（女の子は『きゃーっ！！』と言いつつ大喜びなんだよな。）") (wait)))
    ((&& (== V 1) (== N 14) (== (: 30) 0))
     (<>
      (text #:color 7 "【" 0 "】（トイレじゃない事は確かだな・・・うん。）")
      (wait)
      (text #:color 7 "【" 0 "】（あの建物の中に舞ちゃんを連れ込んで・・・ひっひっひっ。）")
      (wait)
      (set-reg: 30 1)))
    ((&& (== V 1) (== N 14) (== (: 30) 1))
     (<>
      (text #:color 3 "【舞】" 0 "君・・・早く乗物に乗りましょうよ。")
      (wait)
      (text #:color 7 "【" 0 "】（俺は舞ちゃんに乗りたい・・・。）")
      (wait)))
    ((&& (== V 1) (== N 15) (== (: 31) 0))
     (<>
      (text #:color 7 "【" 0 "】舞ちゃん、緑が奇麗だねえ。")
      (wait)
      (text #:color 3 "【舞】やだあ、" 0 "君ったら・・・おじいさんみたいな言い方をしないで。")
      (wait)
      (set-reg: 31 1)))
    ((&& (== V 1) (== N 15) (== (: 31) 1))
     (<>
      (text #:color 7 "【" 0 "】緑よりも・・・舞ちゃんの方が奇麗だぜ。")
      (wait)
      (text #:color 3 "【舞】え？")
      (wait)
      (text #:color 7 "【" 0 "】なんだ、聞いてなかったの？")
      (wait)
      (set-reg: 31 2)))
    ((&& (== V 1) (== N 15) (== (: 31) 2))
     (<> (text #:color 7 "【" 0 "】緑だよ。") (wait)))
    ((&& (== V 1) (== N 16) (== (: 32) 0))
     (<>
      (text #:color 7 "【" 0 "】いい天気でよかったな・・・舞ちゃん。")
      (wait)
      (text #:color 3 "【舞】そうね、私達って相性がいいのよ・・・きっと。")
      (wait)
      (set-reg: 32 1)))
    ((&& (== V 1) (== N 16) (== (: 32) 1))
     (<>
      (text #:color 7 "【" 0 "】気持ち（いい事したい）がいいなあ。")
      (wait)
      (text #:color 3 "【舞】本当・・・いやな事を全部忘れられそう。")
      (wait)))
    ((&& (== V 1) (== N 17) (== (: 33) 0))
     (<>
      (text #:color 7 "【" 0 "】（この広い遊園地が・・・舞ちゃんのパパの物なんだぜ、すごいだろ。）")
      (wait)
      (text #:color 7 "【" 0 "】（と、俺がいばる事じゃない。）")
      (wait)
      (set-reg: 33 1)))
    ((&& (== V 1) (== N 17) (== (: 33) 1))
     (<> (text #:color 7 "【" 0 "】（色々な乗物があるぜ・・・どうするんだ？）") (wait)))
    ((&& (== V 1) (== N 18) (== (: 34) 0))
     (<> (text #:color 7 "【" 0 "】（観覧車だな・・・俺は高所恐怖症だ。）") (wait) (set-reg: 34 1)))
    ((&& (== V 1) (== N 18) (== (: 34) 1))
     (<> (text #:color 7 "【" 0 "】（高いけど・・・二人きりなれるんだよな。）") (wait)))
    ((&& (== V 1) (== N 19) (== (: 35) 0))
     (<> (text #:color 5 "【男】ジョーどこ？") (wait) (set-reg: 35 1)))
    ((&& (== V 1) (== N 19) (== (: 35) 1))
     (<> (text #:color 5 "【男】ジョー・・・どこ？") (wait) (set-reg: 35 2)))
    ((&& (== V 1) (== N 19) (== (: 35) 2))
     (<> (text #:color 5 "【男】どこじょー。") (wait) (set-reg: 35 0)))
    ((&& (== V 1) (== N 20) (== (: 36) 0))
     (<> (text #:color 7 "【" 0 "】（見てると・・・腹が減ってくるなあ。）") (wait) (set-reg: 36 1)))
    ((&& (== V 1) (== N 20) (== (: 36) 1))
     (<> (text #:color 7 "【" 0 "】（舞ちゃんの次に食べたい・・・。）") (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))