(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\・
  #\【
  #\】
  #\。
  #\い
  #\っ
  #\な
  #\子
  #\夏
  #\て
  #\う
  #\ん
  #\、
  #\だ
  #\は
  #\か
  #\よ
  #\の
  #\？
  #\に
  #\ら
  #\る
  #\た
  #\り
  #\あ
  #\ー
  #\し
  #\も
  #\こ
  #\！
  #\ち
  #\く
  #\と
  #\ゃ
  #\で
  #\君
  #\わ
  #\さ
  #\塗
  #\美
  #\そ
  #\ぬ
  #\れ
  #\ま
  #\を
  #\ふ
  #\ね
  #\が
  #\け
  #\す
  #\ょ
  #\お
  #\沙
  #\ル
  #\ど
  #\や
  #\寝
  #\穂
  #\何
  #\言
  #\え
  #\イ
  #\（
  #\）
  #\き
  #\ぜ
  #\せ
  #\俺
  #\行
  #\ば
  #\泳
  #\気
  #\オ
  #\着
  #\事
  #\カ
  #\ト
  #\ン
  #\げ
  #\つ
  #\へ)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 9 (&& (~ @ 9) 65534))
 (set-arr~ @ 6 1)
 (image "j03.pd8")
 (set-arr~ @ 9 (// (~ @ 9) 1))
 (proc 24)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "j03an.pd8")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 0)
 (load "j03.s4" (~ @ 2))
 (animate 0 0 0)
 (animate 1 0)
 (set-arr~ @ 7 0)
 (set-arr~ @ 7 0)
 (load "j05.a6" 47104)
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (if (== (: 539) 1)
   (<>
    (text #:color 2 "【夏子】ふう・・・泳いだ後の脱力感って、気持ちいいのよね。")
    (wait)
    (text #:color 7 "【" 0 "】ああ・・・気分いい。")
    (wait)
    (text #:color 2 "【夏子】ねえ・・・オイルを塗ってくれないかしら？")
    (wait)
    (text #:color 7 "【" 0 "】どこに？")
    (wait)
    (text #:color 2 "【夏子】やだ・・・私の身体に決まってるわよ。")
    (wait)
    (text #:color 7 "【" 0 "】ぜ、全身に塗っていいの！？")
    (wait)
    (text #:color 2 "【夏子】手が届かない所に・・・背中だけ塗ってくれないかしら？")
    (wait)
    (text #:color 7 "【" 0 "】（背中だけかあ・・・。）")
    (wait)
    (text #:color 2 "【夏子】いやだったら、他の人に塗ってもらうけど。")
    (wait)
    (text #:color 7 "【" 0 "】やります、やらせていただきます！！")
    (wait)
    (text #:color 2 "【夏子】ありがとう・・・ちょっと待ってね。")
    (wait)
    (text #:color 2 "【夏子】水着のあとを残したくないから・・・はい、これでいいわ。")
    (wait)
    (set-arr~ @ 7 1)
    (set-arr~ @ 1 4096)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 1)
    (image "j05.pd8")
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (proc 24)
    (set-arr~ @ 7 0)
    (text #:color 7 "【" 0 "】（ごっくん。）")
    (wait)
    (text #:color 2 "【夏子】" 0 "君、塗って・・・。")
    (wait)
    (text #:color 7 "【" 0 "】も、もっと色っぽく言ってくれ。")
    (wait)
    (text #:color 2 "【夏子】塗ってえ・・・これでいい？")
    (wait)
    (text #:color 7 "【" 0 "】（ま、まずい・・・股間が膨張してきた。）")
    (wait)))
 (while
  (== 1 1)
  (<>
   (proc 17)
   (menu-show (<>))
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 512 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (cond
    ((== V 0)
     (<>
      (set-reg: 101 1)
      (proc 18)
      (menu-show (<.> (text "襲いかかる") (if (== (: 50) 1) (text "一緒に寝る"))))
      (cond
       ((&& (== N 1) (== (: 50) 1))
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】寝かせておいてあげよう・・・な？")
         (wait)))
       ((&& (== N 1) (== (: 10) 0))
        (<>
         (text #:color 7 "【" 0 "】だーーーーっ！！")
         (wait)
         (text #:color 2 "【夏子】" 0 "君・・・ちゃんとオイルを塗って。")
         (wait)
         (text #:color 7 "【" 0 "】・・・はい。")
         (wait)
         (set-reg: 10 1)))
       ((&& (== N 1) (== (: 10) 1))
        (<>
         (text #:color 7 "【" 0 "】だあーーーーっ！！")
         (wait)
         (text #:color 2 "【夏子】" 0 "君・・・。")
         (wait)
         (text #:color 7 "【" 0 "】はい、ちゃんと塗ります。")
         (wait)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】そうだな・・・俺もなんだか眠くなってきたよ。")
         (wait)
         (text #:color 7 "【" 0 "】ふあああ・・・夏子さんより、かわいい女性がいるはずもないし・・・寝ちゃおうかな。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "kuro.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (sound 1)
         (text "・・・。")
         (wait)
         (text "・・・。")
         (wait)
         (text #:color 7 "【" 0 "】うーん・・・むにゃむにゃ。")
         (wait)
         (text "・・・。")
         (wait)
         (text "・・・。")
         (wait)
         (set-var A 2)
         (proc 13)
         (proc 11)
         (text #:color 2 "【夏子】" 0 "君・・・。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "j03.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 24)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "j03an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "j03.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 36)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 2 "【夏子】ふふふ・・・おはよう。")
         (wait)
         (text #:color 7 "【" 0 "】おはようって・・・ここはプールだよね？")
         (wait)
         (text #:color 2 "【夏子】よく寝てたわよ、私も人の事は言えないけど。")
         (wait)
         (text #:color 7 "【" 0 "】げっ・・・２時間も寝てたんだ。")
         (wait)
         (text #:color 2 "【夏子】気持ちよかったわ・・・こんなにリラックスして寝たのはひさしぶりよ。")
         (wait)
         (text #:color 7 "【" 0 "】ふあああ・・・俺も。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】なんだかノドがカラカラだぜ。")
         (wait)
         (text #:color 2 "【夏子】私も・・・汗をいっぱいかいたからね、きっと。")
         (wait)
         (text #:color 2 "【夏子】ねえ、外に出て・・・お茶しましょうよ。")
         (wait)
         (text #:color 7 "【" 0 "】そうだな、そうするか・・・もう泳ぐ気しないし。")
         (wait)
         (text #:color 2 "【夏子】わかった・・・急いで着替えてくるから、さっきの場所で待ってて。")
         (wait)
         (text #:color 7 "【" 0 "】あ・・・俺も着替えるって。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "kuro.pd8")
         (proc 15)
         (set-arr~ @ 7 0)
         (sound 1)
         (text #:color 7 "【" 0 "】ふう・・・なんだか眠いな。")
         (wait)
         (text #:color 7 "【" 0 "】おっと、今度こそ夏子さんより先に行かないと・・・トロい男だと思われちゃうぞ。")
         (wait)
         (text #:color 7 "【" 0 "】パンツを脱いで・・・パンツをはいて。")
         (wait)
         (text #:color 5 "【隣で着替えてる男】ほほう・・・りっぱですね。")
         (wait)
         (text #:color 7 "【" 0 "】うるさいな・・・シャツを着て、ズボンをはいて、と。")
         (wait)
         (text #:color 7 "【" 0 "】よーし、これでカンペキだ・・・今度は俺の方が早いだろう。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "45.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 9)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "45an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "45.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (sound 1)
         (set-var I 36)
         (proc 26)
         (set-reg: 835 0)
         (text #:color 7 "【" 0 "】ほーら・・・夏子さんはまだ来てない。")
         (wait)
         (text #:color 3 "【女の声】" 0 "！！")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "j02.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 25)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "j02an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "j02.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 7 "【" 0 "】げーーっ！？")
         (wait)
         (text #:color 3 "【美沙】な、なんだよ・・・そんなに驚く事はないだろ！？")
         (wait)
         (text #:color 6 "【美穂】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】な、なんだ・・・美沙と美穂ちゃんも来てたのか、ははは。")
         (wait)
         (text #:color 3 "【美沙】" 0 "は一人でプールか？・・・寂しいやつだな。")
         (wait)
         (text #:color 7 "【" 0 "】美沙こそ、陸上部の練習をさぼるなよ。")
         (wait)
         (text #:color 3 "【美沙】うるさいな、何も知らないくせに・・・これから学校に行って、ちゃんと練習に出るつもりなんだよ。")
         (wait)
         (text #:color 7 "【" 0 "】なんだよ、何も知らないくせにって・・・美穂ちゃん、俺は何を知らないんだ？")
         (wait)
         (text #:color 6 "【美穂】・・・。")
         (wait)
         (text #:color 3 "【美沙】はっはっはっ、美穂のやつ照れてるよ・・・" 0 "に水着姿を見られたもんだから。")
         (wait)
         (text #:color 6 "【美穂】やだ・・・美沙ちゃんったら。")
         (wait)
         (text #:color 7 "【" 0 "】さ、さーてと・・・俺は泳いでこようかな？")
         (wait)
         (text #:color 3 "【美沙】・・・。")
         (wait)
         (text #:color 6 "【美穂】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】なんだよ。")
         (wait)
         (text #:color 3 "【美沙】泳ぎに行くんだろ・・・行けよ。")
         (wait)
         (text #:color 7 "【" 0 "】（ま、まずい・・・夏子さんがこっちに歩いてくる！？）")
         (wait)
         (text #:color 3 "【美沙】なんだよ、泳ぎに行くんじゃないのか？")
         (wait)
         (text #:color 7 "【" 0 "】あーーっ！！あんな所にカール君が泳いでるっ！！")
         (wait)
         (text #:color 3 "【美沙】カール君って、あの陸上のカール君が！？・・・ど、どこだ、" 0 "！？")
         (wait)
         (text #:color 7 "【" 0 "】あそこだよ・・・ほら、あそこ！！")
         (wait)
         (text #:color 3 "【美沙】美穂、行こうぜ！！・・・サインをもらおう！！")
         (wait)
         (text #:color 6 "【美穂】うん・・・" 0 "君、ばいばい。")
         (wait)
         (text #:color 7 "【" 0 "】美穂ちゃん、ばいばい・・・ははは。")
         (wait)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "45.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 9)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 1)
         (image "j11.pd8")
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (proc 25)
         (set-arr~ @ 7 1)
         (set-arr~ @ 1 4096)
         (set-arr~ @ 6 1)
         (image "j11an.pd8")
         (set-arr~ @ 6 0)
         (set-arr~ @ 7 0)
         (load "j11.s4" (~ @ 2))
         (animate 0 0 0)
         (animate 1 0)
         (set-arr~ @ 7 0)
         (text #:color 2 "【夏子】" 0 "君・・・お友達？")
         (wait)
         (text #:color 7 "【" 0 "】そう、ただのお友達・・・ははははっ！！")
         (wait)
         (text #:color 2 "【夏子】いいの？・・・どこかに行っちゃったけど。")
         (wait)
         (text #:color 7 "【" 0 "】いいの、いいの・・・そんな事より、早く外に出てティータイムにしましょう、ね、ね！？")
         (wait)
         (text #:color 2 "【夏子】変な" 0 "君・・・。")
         (wait)
         (text #:color 7 "【" 0 "】（ふう・・・危なかったな。）")
         (wait)
         (slot 1 6)
         (mes-jump "yuench5.mes")))
       (else (<>)))))
    ((&& (== V 8) (== N 1) (== (: 11) 0))
     (<>
      (text #:color 7 "【" 0 "】・・・これでいい？")
      (wait)
      (text #:color 2 "【夏子】うん・・・それでいいわ。")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 8) (== N 1) (== (: 11) 1))
     (<>
      (text #:color 2 "【夏子】" 0 "君・・・全体によく伸ばさないと、ムラになっちゃうから。")
      (wait)
      (text #:color 7 "【" 0 "】へいへい。")
      (wait)
      (set-reg: 11 2)))
    ((&& (== V 8) (== N 1) (== (: 11) 2))
     (<>
      (text #:color 7 "【" 0 "】（夏子さんの背中って・・・すべすべだ。）")
      (wait)
      (text #:color 7 "【" 0 "】（オイルのせいじゃないだろう・・・なんて奇麗な肌なんだ。）")
      (wait)
      (set-reg: 11 3)))
    ((&& (== V 8) (== N 1) (== (: 11) 3))
     (<>
      (text #:color 7 "【" 0 "】ぬりぬりぬりぬり・・・。")
      (wait)
      (text #:color 2 "【夏子】あ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】へ？")
      (wait)
      (text #:color 2 "【夏子】う、ううん・・・何でもないの。")
      (wait)
      (set-reg: 11 4)))
    ((&& (== V 8) (== N 1) (== (: 11) 4))
     (<>
      (text #:color 2 "【夏子】" 0 "君って、オイルを塗るのがうまいわね・・・プロになれるわよ。")
      (wait)
      (text #:color 7 "【" 0 "】オイル塗りのプロってのもいいな・・・色々な女の子の肌に触れるぞ。")
      (wait)
      (text #:color 2 "【夏子】でも、冬になったら仕事がなくなっちゃうわね・・・ふふふ。")
      (wait)
      (set-reg: 11 5)))
    ((&& (== V 8) (== N 1) (== (: 11) 5))
     (<>
      (text #:color 2 "【夏子】う・・・ん・・・。")
      (wait)
      (text #:color 7 "【" 0 "】何か言った？")
      (wait)
      (text #:color 2 "【夏子】ううん・・・何も言ってないわ。")
      (wait)
      (set-reg: 11 6)))
    ((&& (== V 8) (== N 1) (== (: 20) 0))
     (<>
      (text #:color 2 "【夏子】う・・・ん・・・。")
      (wait)
      (text #:color 7 "【" 0 "】何か言った？")
      (wait)
      (text #:color 2 "【夏子】ううん・・・何も言ってないわ。")
      (wait)
      (set-reg: 20 1)))
    ((&& (== V 8) (== N 1) (== (: 20) 1))
     (<>
      (text #:color 2 "【夏子】う・・・ん・・・。")
      (wait)
      (text #:color 7 "【" 0 "】何か言った？")
      (wait)
      (text #:color 2 "【夏子】ううん・・・何も言ってないわ。")
      (wait)
      (set-reg: 20 2)))
    ((&& (== V 8) (== N 1) (== (: 11) 6))
     (<>
      (text #:color 2 "【夏子】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ぬりぬりぬりぬり・・・こんなもんでいいかな？")
      (wait)
      (text #:color 2 "【夏子】だめ・・・もっとよく塗って。")
      (wait)
      (text #:color 7 "【" 0 "】（うーん、だんだん夏子さんのシモベのような気がしてきた。）")
      (wait)
      (set-reg: 11 7)))
    ((&& (== V 8) (== N 1) (== (: 50) 0))
     (<>
      (text #:color 7 "【" 0 "】よーく、伸ばして・・・これでどう？")
      (wait)
      (text #:color 2 "【夏子】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】夏子さん？")
      (wait)
      (text #:color 2 "【夏子】すうすう・・・。")
      (wait)
      (text #:color 7 "【" 0 "】ありゃりゃ・・・寝ちゃったよ。")
      (wait)
      (set-reg: 50 1)))
    ((&& (== V 8) (== N 1) (== (: 50) 1))
     (<> (text #:color 7 "【" 0 "】いや・・・夏子さんは寝てるんだ、このまま寝かせてあげよう。") (wait)))
    ((&& (== V 8) (== N 2) (== (: 50) 1) (== (: 13) 0))
     (<>
      (text #:color 7 "【" 0 "】寝てるからな・・・触ってもわからないぞ。")
      (wait)
      (set-reg: 101 1)
      (set-arr~ @ 7 0)
      (proc 18)
      (menu-show (<.> (text "さわる") (text "さわらない")))
      (cond
       ((== N 1)
        (<>
         (text #:color 7 "【" 0 "】ちょっとだけ・・・触っちゃおっと。")
         (wait)
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】柔らかい・・・。")
         (wait)
         (set-reg: 109 (- (: 109) 1))
         (set-reg: 13 1)))
       ((== N 2)
        (<>
         (text #:color 7 "【" 0 "】・・・。")
         (wait)
         (text #:color 7 "【" 0 "】やーめた・・・男らしくないもんな。")
         (wait)
         (text #:color 2 "【夏子】・・・。")
         (wait)
         (set-reg: 109 (+ (: 109) 1))
         (set-reg: 13 1)))
       (else (<>)))))
    ((&& (== V 8) (== N 2) (== (: 50) 1) (== (: 13) 1))
     (<>
      (text #:color 7 "【" 0 "】おいおい・・・さわるのか？")
      (wait)
      (text #:color 2 "【夏子】うーん・・・。")
      (wait)
      (text #:color 7 "【" 0 "】び、びっくりしたあ・・・。")
      (wait)))
    ((&& (== V 8) (== N 2) (== (: 12) 0))
     (<>
      (text #:color 2 "【夏子】" 0 "君・・・胸は塗らなくていいのよ。")
      (wait)
      (text #:color 7 "【" 0 "】あ・・・そうなの、なーんだ。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 8) (== N 2) (== (: 12) 1))
     (<>
      (text #:color 2 "【夏子】" 0 "君・・・。")
      (wait)
      (text #:color 7 "【" 0 "】へいへい、胸は塗る必要がないって言いたいんでしょ？")
      (wait)
      (text #:color 2 "【夏子】ふふふ・・・残念でしょ？")
      (wait)
      (text #:color 7 "【" 0 "】ちょっとね。")
      (wait)
      (set-reg: 12 2)))
    ((&& (== V 8) (== N 2) (== (: 12) 2))
     (<>
      (text #:color 7 "【" 0 "】ねえ・・・ちょっとだけ塗ってもいい？")
      (wait)
      (text #:color 2 "【夏子】・・・。")
      (wait)
      (text #:color 2 "【夏子】ちょっとだけよ。")
      (wait)
      (text #:color 7 "【" 0 "】ぬりぬりぬり・・・。")
      (wait)
      (text #:color 2 "【夏子】・・・。")
      (wait)
      (text #:color 7 "【" 0 "】うーん、満足した。")
      (wait)
      (set-reg: 12 3)))
    ((&& (== V 8) (== N 2) (== (: 12) 3))
     (<>
      (text #:color 2 "【夏子】" 0 "君、もうだめ。")
      (wait)
      (text #:color 7 "【" 0 "】ちぇっ。")
      (wait)))
    ((== (: 50) 1)
     (<>
      (text #:color 7 "【" 0 "】いや・・・夏子さんは寝てるんだ。")
      (wait)
      (text #:color 7 "【" 0 "】ふあああ・・・俺まで眠くなってきたぜ。")
      (wait)))
    ((&& (== V 8) (== N 3) (== (: 14) 0))
     (<>
      (text #:color 2 "【夏子】" 0 "君、そこは塗らなくていいのよ・・・。")
      (wait)
      (text #:color 7 "【" 0 "】あ・・・そうか。")
      (wait)
      (set-reg: 14 1)))
    ((&& (== V 8) (== N 3) (== (: 14) 1))
     (<>
      (text #:color 2 "【夏子】" 0 "君・・・そこは自分で塗れるから平気よ。")
      (wait)
      (set-reg: 14 2)))
    ((&& (== V 8) (== N 3) (== (: 14) 2))
     (<>
      (text #:color 7 "【" 0 "】ぬりぬりぬり・・・。")
      (wait)
      (text #:color 2 "【夏子】" 0 "君ってば・・・。")
      (wait)
      (text #:color 7 "【" 0 "】わかってるよう・・・ここは自分で塗れるんでしょ？")
      (wait)))
    ((&& (== V 8) (== N 4) (== (: 50) 1))
     (<>
      (text #:color 2 "【夏子】すうすう・・・。")
      (wait)
      (text #:color 7 "【" 0 "】よそうぜ・・・起こしちゃかわいそうだ。")
      (wait)))
    ((&& (== V 8) (== N 4) (== (: 15) 0))
     (<>
      (text #:color 2 "【夏子】きゃっ・・・顔に塗らないでね。")
      (wait)
      (text #:color 7 "【" 0 "】あ・・・そうか。")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 8) (== N 4) (== (: 15) 1))
     (<>
      (text #:color 2 "【夏子】" 0 "君、わざとやってる？")
      (wait)
      (text #:color 7 "【" 0 "】まさか・・・髪の毛が邪魔だったから、どけようとしただけさ。")
      (wait)
      (set-reg: 15 2)))
    ((&& (== V 8) (== N 4) (== (: 15) 2))
     (<> (text #:color 2 "【夏子】" 0 "君・・・顔は塗らなくていいのよ。") (wait)))
    ((&& (== V 8) (== N 5) (== (: 50) 1))
     (<>
      (text #:color 7 "【" 0 "】よそうぜ・・・無防備な女性にいたずらをするのは。")
      (wait)
      (text #:color 2 "【夏子】・・・。")
      (wait)))
    ((&& (== V 8) (== N 5) (== (: 16) 0))
     (<>
      (text #:color 2 "【夏子】" 0 "君、トリートメントじゃないわよ・・・髪についたらベトベトになっちゃう。")
      (wait)
      (text #:color 7 "【" 0 "】ははは・・・ごめん。")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 8) (== N 5) (== (: 16) 1))
     (<> (text #:color 2 "【夏子】" 0 "君・・・オイルを髪につける事はないでしょ？") (wait)))
    ((&& (== V 8) (== N 6) (== (: 50) 1))
     (<> (text #:color 7 "【" 0 "】ははは・・・馬鹿な事はよそうぜ。") (wait)))
    ((&& (== V 8) (== N 6) (== (: 17) 0))
     (<>
      (text #:color 7 "【" 0 "】ぬりぬりぬり。")
      (wait)
      (text #:color 2 "【夏子】どこに塗ってるの？")
      (wait)
      (text #:color 7 "【" 0 "】ははは・・・ぼーっとしてた。")
      (wait)
      (text #:color 2 "【夏子】" 0 "君、私の麦わら帽子を貸してあげましょうか？・・・暑さのせいじゃない？")
      (wait)
      (text #:color 7 "【" 0 "】大丈夫、ちゃんと塗るから。")
      (wait)
      (set-reg: 17 1)))
    ((&& (== V 8) (== N 6) (== (: 17) 1))
     (<>
      (text #:color 2 "【夏子】" 0 "君・・・どこに塗ってるの？")
      (wait)
      (text #:color 7 "【" 0 "】色々と・・・ぬりぬりぬり。")
      (wait)))
    (else (<>)))))
 (set-arr~ @ 7 1))